### ISSUE TITLE
Adding filter hook into get_google_fonts()

### ISSUE THREAD

**Issue by dariodev** [themeum/kirki#1000]
Hi @aristath 
Could you add a filter hook into function get_google_fonts(). Something like this?

``` php
$path_new = Kirki::$path . '/includes/webfonts.php';
$fonts = include wp_normalize_path( apply_filters( 'kirki/fonts/google_fonts_path', $path_new ) );
```

I want to provide my own array of Google fonts in order to reduce the number of available fonts.
Similar thing is asked here #85 but adding filter would be better solution.

**Comment by aristath** [comment]
@dariodev we already have a filter for that...
It doesn't allow you to change the path of the google-fonts array file.
Instead, it allows you direct access to the array of google fonts.
Please use the `kirki/fonts/google_fonts` filter.
You can see how the array is built here: https://github.com/aristath/kirki/blob/2.3.2/includes/class-kirki-fonts.php#L130-L142
