### ISSUE TITLE
Kirki and Timber

### ISSUE THREAD

**Issue by JakeHenshall** [themeum/kirki#1001]
### Issue description:

Is there any detailed documentation about integrating Kirki with Timber or can you give me an overview of simply things todo like including images etc... Also is there anyway to debug what is produced by kirki and Timber?
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
WP 4.5.2 / Kirki 2.3.2
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
    Kirki::add_field( 'beast', array(
        'settings' => 'header_logo_setting',
        'label'    => __( 'Setting for the logo', 'theme_slug' ),
        'section'  => 'header_switch',
        'type'     => 'image',
        'priority' => 11,
        'default'  => '',
        'output' => array(
            'element'  => 'img.my-thumb-class',
            'property' => 'background_image',
        ),
    ) );

    {% if theme.theme_mod('beast', 'header_logo_setting') %}

            <div style="background-image: url('{% theme.theme_mod('beast', 'header_logo_setting') %}')" class="my-thumb-class" alt="Image for {{post.title}}" />

    {% endif %}
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
