### ISSUE TITLE
Syntax Highlighter: PHP requries C-like modes

### ISSUE THREAD

**Issue by HardeepAsrani** [themeum/kirki#1003]
I noticed that Kirki isn't calling clike.js file when using PHP in syntax highlighter.

If you remove clike.js from it, it fails terribly: http://codemirror.net/mode/php/index.html

Haven't actually tried in Kirki. @aristath 

If you want I can send a patch. :)

**Comment by aristath** [comment]
Fixed on https://github.com/aristath/kirki/commit/a650b9af756fd8448a00b4f6a619e5836e0e817c#diff-24df45ecd0f9ef2889cd46ce356c74b8
