### ISSUE TITLE
Repeater image issue

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#1004]
### Issue description:

After update to v 2.3.3 the customizer is blank. It makes the repeater image field.
VM4260:243 Uncaught TypeError: Cannot read property 'no-image-selected' of undefined
### Version used:

WP 2.3.3, Dev 2.3.3
### Using theme_mods or options?

theme_mods 
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'giga_store_settings', array(
    'type'       => 'repeater',
    'label'      => __( 'Carousel Items', 'giga-store' ),
    'section'    => 'brands_section',
    'priority'   => 10,
    'settings'   => 'repeater_brands',
    'default'    => '',
    'fields'     => array(
        'brands_image'   => array(
            'type'       => 'image',
            'label'      => __( 'Photo', 'giga-store' ),
            'default'    => '',
        ),
        'brands_title'   => array(
            'type'       => 'text',
            'label'      => __( 'Title', 'giga-store' ),
            'default'    => '',
        ),
        'brands_desc'    => array(
            'type'       => 'text',
            'label'      => __( 'Description', 'giga-store' ),
            'default'    => '',
        ),
        'brands_url'     => array(
            'type'       => 'text',
            'label'      => __( 'Link', 'giga-store' ),
            'default'    => '',
        ),
    ),
) );
```

**Comment by voidlz** [comment]
`color` and `upload` types as well.
Error:
`TypeError: window.kirki.l10n[data.kirkiConfig] is undefined`

**Comment by aristath** [comment]
@x-bull @hijackfl Can you guys please check if the latest develop branch on this repository fixes the issue so that I may release 2.3.4 ASAP?

Thanks!

**Comment by x-bull** [comment]
Develop branch works. New bug: The buttons are empty inside the repeater rows - no text there (color is set)
![kirki](https://cloud.githubusercontent.com/assets/14072537/15692007/42d19e0c-278c-11e6-985b-20a283489a8b.jpg)

**Comment by aristath** [comment]
@x-bull thanks for checking!
I missed a line in the previous commit, can you please check again? I just pushed another commit that should fix this permanently...

**Comment by x-bull** [comment]
@aristath Now is perfect :+1:

**Comment by aristath** [comment]
Great, thanks!
I'll be releasing 2.3.4 then in a few minutes to fix this.
