### ISSUE TITLE
Suggestion : Min/max values and subsets

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#1007]
Would be nice to have to ability to specify a range of values for composite fields (for example font size and line height in the typography field).

Also for the typography field another nice addition could be the ability to define only a selection of webfonts available to the user.

Both would make life much easier for devs because this way we can give user only the right amount of control over some of the design components of the site.

**Comment by aristath** [comment]
> Would be nice to have to ability to specify a range of values for composite fields (for example font size and line height in the typography field).

I've been thinking about it and I don't think I can find a way to do that.
I don't mean technically, that's the easy part. I mean conceptually... Users are able to use any valid CSS unit they want! So font-size can be 18px, 1.2em, 1.5rem, 120% or whatever they choose!
How are in & max values going to work? The only way this would be viable is if we were forcing the use of a specific CSS unit for these fields. But I wouldn't want to do that...

> Also for the typography field another nice addition could be the ability to define only a selection of webfonts available to the user.

It's already possible to do that but so far it's global and there isn't the ability to define font-families on a per-field basis. This is worth considering and adding.

Any ideas on what to do with the units?

**Comment by manuelmoreale** [comment]
First idea that comes to mind is to allow the dev to specify min max and type of unit. This way if you don't care about what the user input is you can leave the user free to insert whatever value and unit he or she wants. But if you want it to be constrained in a particular range then you can specify a unit which is also helpful because that can be consistent across the entire theme. For example I usually use `rem` with body font size set to `62.5%` so in my case would be nice to have the user only to input font sizes using rem.

I'll have a thing and see if I can come up with other possible solutions.

**Comment by manuelmoreale** [comment]
Just a quick mention to @aristath in case you missed my reply ;)

**Comment by aristath** [comment]
Marking as a feature request for 3.1

**Comment by aristath** [comment]
I think I've got an idea about this one...
If you define min/max values and a unit, it can become a slider.
I think that would be the only way to ensure everything works out.

**Comment by manuelmoreale** [comment]
Hey @aristath , that is a good idea. Another option is to use html5 `min` and `max`attribute on the input field and have the unit appended at the end.

Kinda like this
<img width="366" alt="screen shot 2017-05-29 at 8 39 44 am" src="https://cloud.githubusercontent.com/assets/1738077/26539012/6c963de8-444a-11e7-87d7-20bfed451b53.png">

**Comment by ghost** [comment]
Sliders are ok only if you can manually type in the value if you prefer.

On 29 May 2017 4:10 PM, "Manuel Moreale" <notifications@github.com> wrote:

Hey @aristath <https://github.com/aristath> , that is a good idea. Another
option is to use html5 min and maxattribute on the input field and have the
unit appended at the end.

Kinda like this
[image: screen shot 2017-05-29 at 8 39 44 am]
<https://cloud.githubusercontent.com/assets/1738077/26539012/6c963de8-444a-11e7-87d7-20bfed451b53.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aristath/kirki/issues/1007#issuecomment-304584282>, or mute
the thread

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
