### ISSUE TITLE
Reset Button Missing

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#1009]
### Issue description:

Reset Button Missing
### Version used:

2.3.4
### Using theme_mods or options?

theme_mods 
### Code to reproduce the issue (config + field(s))

Hi @aristath, I noticed that the latest version of KIRKI the button RESET has no label and does not appear in the Customizer. Do you agree?

Cheers,
Davide

**Comment by mahdiyazdani** [comment]
Hi,
Still couldn't find "Reset" button and "Remove" button in repeater fields. Using 2.3.4
