### ISSUE TITLE
Controls cheat sheet page on documentation

### ISSUE THREAD

**Issue by edirpedro** [themeum/kirki#1011]
Kirki has a bunch of controls and could be easier to decide witch to use if documentation had a page to show all the options using their sample image. At this moment I saved all the controls images in a folder on my desktop to take a look at the options, but this could be documented in a page too and this is much better than read the controls menu and open the page to see if I can use it or not. Just the sample image  linked to the their page is enough. What do you think?

A list of Hooks available would be a good additional information too!

**Comment by aristath** [comment]
The truth is that my day job simply takes up most of my time so I didn't have a lot of time to deal with adding extra documentation etc...

I want to do this but I simply don't have an ETA.
In the meantime if you want to contribute I'd be more than happy to merge any pull-requests!
All docs are in the [gh-pages](https://github.com/aristath/kirki/tree/gh-pages) branch 👍

**Comment by Vishal-Deshpande** [comment]
Let me have a look at it.

**Comment by edirpedro** [comment]
@PlayerThemes #1056
