### ISSUE TITLE
Empty option for Palette control

### ISSUE THREAD

**Issue by edirpedro** [themeum/kirki#1019]
The Palette control has no option to define an empty choice. In my situation, I used it to offer pre-defined colors to choose and another fields to create a new composition. But how to determine witch one to use, the palette or the user colors? The Palette control cannot deselect the option after selected. (Maybe this simple action could resolve the problem, deselect the choice)

I tried to use the first choice as `array(0 => 'My own definition')`, it could work but sound strange the interface, not good to understand. I returned to a simple Select, but this option has no color example as Palette does.

**Comment by danielbachhuber** [comment]
Instead of an empty option, I'm using a palette named "custom" and using that as the logic for whether or not to show the user colors options.

**Comment by edirpedro** [comment]
@danielbachhuber But how the users understand that this option is for a custom palette? The Palette control only shows hexadecimal values for the colors, no text message like "Custom".

![palette](https://cloud.githubusercontent.com/assets/831507/16875055/92a88d46-4a73-11e6-800c-9ebf1f5eb95c.png)

**Comment by danielbachhuber** [comment]
> But how the users understand that this option is for a custom palette? The Palette control only shows hexadecimal values for the colors, no text message like "Custom".

Oh, I'm going to hack it in place for now.

**Comment by aristath** [comment]
Hey there!

Palettes don't have a `label` argument which is why something like this has not been implemented yet.
All they have is an ID and then the array of HEX colors to be displayed.
If we were to add a label, where do you think it would be best to show it?

**Comment by edirpedro** [comment]
If you add a label, this could be like a normal palette in white or transparent background and the label inside it "My Colors".

But my first option would be enable the user to deselect a palette to disable it. I could write a description to the field explaining users that disabling a palette will make the theme uses the colors set instead.

**Comment by aristath** [comment]
palette controls are essentially radio controls, the only thing that changes is some CSS.
Radio controls unfortunately can't be deselected...

**Comment by edirpedro** [comment]
Yes, using a hidden input and some javascript to pass the selected option would be a solution here.

But another idea, it could be added an option to the control `show_option_none => true` and this option should only show at the top, a palette like photoshop does with a slash, or a label `show_option_none => 'My custom palette'`.

![captura de tela 2016-07-16 as 11 43 00](https://cloud.githubusercontent.com/assets/831507/16895374/8eeaf8ce-4b4a-11e6-9f78-59e18f012e94.png)

**Comment by edirpedro** [comment]
Thinking of a bit, my problem was a conflict with a section showing the palette options and another section showing a set of colors options for each part of the theme "menu, links, header, etc". A solution to me already exist, I could simply override the palette option if some color was set by the user, because the color field has an option to disable it, setting `default => ''` the color field shows a button **clear** to make the value empty. So, if a color is empty I use the palette and if not I override the palette for that specific color option.

@danielbachhuber does this solution solves yours?
