### ISSUE TITLE
Fatal error: Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#102]
After updating to latest commit and replacing `get_theme_mod` with `kirki_get_option` im getting the following error:

```
Fatal error: Maximum function nesting level of '100' reached, aborting! in /Users/luismartins/Sites/testing.dev/wp-includes/l10n.php on line 710
Call Stack
#   Time    Memory  Function    Location
1   0.0229  232576  {main}( )   ../index.php:0
2   0.0231  235384  require( '/Users/luismartins/Sites/testing.dev/wp-blog-header.php' )    ../index.php:17
3   0.5453  22024800    require_once( '/Users/luismartins/Sites/testing.dev/wp-includes/template-loader.php' )  ../wp-blog-header.php:16
4   0.5529  22174944    include( '/Users/luismartins/Sites/disclosure.dev/wp-content/themes/disclosure/front-page.php' )    ../template-loader.php:74
5   0.5529  22175168    Timber::get_context( )  ../front-page.php:21
6   0.5699  22253472    apply_filters( ???, ??? )   ../timber.php:257
7   0.5699  22254808    call_user_func_array:{/Users/luismartins/Sites/testing.dev/wp-includes/plugin.php:213} ( ???, ??? ) ../plugin.php:213
8   0.5699  22254992    StarterSite->add_to_context( ??? )  ../plugin.php:213
9   0.5882  22580200    kirki_get_option( ??? ) ../functions.php:89
10  0.5916  22627704    kirki_get_option( ???, ??? )    ../helpers.php:90
11  0.5944  22674672    kirki_get_option( ???, ??? )    ../helpers.php:90
12  0.5962  22721640    kirki_get_option( ???, ??? )    ../helpers.php:90
13  0.5980  22768608    kirki_get_option( ???, ??? )    ../helpers.php:90
14  0.6010  22815576    kirki_get_option( ???, ??? )    ../helpers.php:90
15  0.6027  22862544    kirki_get_option( ???, ??? )    ../helpers.php:90
16  0.6042  22909512    kirki_get_option( ???, ??? )
```

**Comment by aristath** [comment]
It doesn't make any sense...
PHP doesn't have a "maximum function nesting level"!

Are you by any chance using xdebug?
If yes, then I'm assuming this happens on a test server and not a live site, right?
Can you please try editing your php.ini file and set 
`xdebug.max_nesting_level=999`

**Comment by lmartins** [comment]
Im running it locally and yes, I have xdebug active.

**Comment by aristath** [comment]
Can you pull and check again?

**Comment by lmartins** [comment]
After deactivating xdebug and updating Kirki, I now get:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /Users/luismartins/Sites/disclosure.dev/wp-content/themes/disclosure/mdf/setup/kirki.php on line 213`

Enabling XDebug will then show:
![kirki](https://cloud.githubusercontent.com/assets/151981/6770013/55ebd352-d0aa-11e4-9121-f0a1f30c0cc8.png)

It seems strange the amount off `kirki_get_option` calls since I only have a few variables.

**Comment by aristath** [comment]
Can you please try replacing the `kirki_get_option` function from the helpers.php file with this one and let me know if that works:

``` php
function kirki_get_option( $option ) {

    // Get the array of controls
    $controls = Kirki_Controls::get_controls();
    $controls_array = array();
    foreach ( $controls as $control ) {
        $controls_array[$control['settings']] = $control;
    }
    $selected_control = $controls_array[$option];
    $default_value    = $selected_control['default'];
    $value = get_theme_mod( $option, $default_value );

    return $value;

}
```

**Comment by aristath** [comment]
Sorry for using you as a test subject here, I just don't use xdebug and never had this issue...
On my vagrant test sites and a live server it's working fine so it's just a matter of resolving the xdebug conflict there. :)

**Comment by lmartins** [comment]
C'mon Aristeides, don't be sorry im more than happy to help. 
And btw, im now getting the suspicion I am the one who should apologise since im suspecting my editor (Atom) fu**\* up when I did find & replace to replace the `get_theme_mod`, it actually replaced the library occurrences as well creating what I imagine is an infinite loop.
Atom doesn't yet support the negation patterns and I blindly replaced everything... Damn!! Sorry about that.

**Comment by aristath** [comment]
LOL no need to apologise.

So it works as-is?
Which one is the one that works for you? The one committed, or the one posted above?

**Comment by lmartins** [comment]
They both run without any problem.Not in console neither on Xdebug. Thanks! :)
