### ISSUE TITLE
Delete button for Repeater Control Items not appering.

### ISSUE THREAD

**Issue by geocef** [themeum/kirki#1021]
### Issue description:

I have updated to kirki.2.3.4. Now the delete button in the repeater control does not appear. I tried editing the file "kirki/includes/controls/class-kirki-controls-repeater-control.php" on  line 502. to this and it worked. 
`<button type="button" class="button-link repeater-row-remove">Remove</button>`

But the problem now is that ones a repeater row is deleted, the remaining rows index's do not rearrange. And when I drag them it causes a mess.
### Version used: kirki 2.3.4

I also tried the development version but the problem is still the same.
### Using theme_mods or options?

Using theme_mods

![1](https://cloud.githubusercontent.com/assets/19708524/15889813/2b432c26-2d5c-11e6-8fbc-f418f34051c8.jpg)
![2](https://cloud.githubusercontent.com/assets/19708524/15889814/2b6bd70c-2d5c-11e6-92da-9869f5b03d33.jpg)

**Comment by aristath** [comment]
Did you try using the development branch from this repository?
I believe this has already been fixed

**Comment by geocef** [comment]
I have tried the development branch again. Now the delete button appears. But once the a repeater row is deleted and a new row is added, if I try to rearrange the rows it cause a mess. 
![3](https://cloud.githubusercontent.com/assets/19708524/15890129/9cfe63f2-2d5d-11e6-9bd5-8eea00be5050.jpg)

**Comment by aristath** [comment]
If I have 6 rows and I delete row 4, then I'm left with rows 1,2,3,5,6 (4 removed).
When I click on row 2 and move it to 4, then the numbers change and reflect the new structiure so it becomes 1,2,3,4,5 (6 removed, 4 added).
Is that what you mean by "mess"? 'Cause that's the worst I could do, I can't understand how you got the result you have on your screenshot there!!!!

**Comment by geocef** [comment]
Thanks for the reply. what you just said works perfect.

> If I have 6 rows and I delete row 4, then I'm left with rows 1,2,3,5,6 (4 removed).
> When I click on row 2 and move it to 4, then the numbers change and reflect the new structure so it becomes 1,2,3,4,5 (6 removed, 4 added).

BUT the problem is that if I have 6 rows and I delete row 4, then I'm left with rows 1,2,3,5,6 (4 removed). But if i do not move any one of the remaining rows to a new position but i go straight away and click on "Add new row" button, then I get this results 1,2,3,5,6,6new . Now if i drag the last row (6new) to any position above it (say first position), it will still remain 6 like this 6new,2,3,4,5,6. 

And the output (that is) on the main site (when echoing the get_theme_mod()) it will be like this 

_ , 2,3,4,5,6new . That is the first item on the main site will be blank but the last item will be showing the 6new content.

Sorry for not explaining myself well at first.

**Comment by guillaumemolter** [comment]
Update: Ok just saw it's already patched here 9d57caa5dd43832fe9660725eb490b53acd616fd my bad!

Hmmm...jumping in on this one. The comments seems to be a little off-topic ( Delete button for Repeater Control Items not appearing).

@aristath I think 1419382815d2b983d9191569b7b168527677032c broke the remove row button as it is not showing up anymore.

![screen shot 2016-06-14 at 16 11 14](https://cloud.githubusercontent.com/assets/1478527/16058082/bb65b038-324a-11e6-8fc7-469baced83d5.png)

The button is in the DOM but it's label is empty.

![screen shot 2016-06-14 at 16 12 20](https://cloud.githubusercontent.com/assets/1478527/16058121/dc17767c-324a-11e6-8e15-0a656c87dd07.png)

**Comment by artboard-studio** [comment]
I just use this temp fix, just add this css to your admin

button.button-link.repeater-row-remove:before {
    content: 'Remove';
}
