### ISSUE TITLE
wp.customize (on javascript) executed everytime page changed not only when control value changed

### ISSUE THREAD

**Issue by jegbagus** [themeum/kirki#1024]
### Issue description:

wp.customize (on javascript) keep executed every time page changed (ex : link clicked). it prevent us to add more functionality.

wp.customize value.bind should executed only when control value changed, not when page change by clicking link on page.
### Version used:

2.3.4
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

to reproduce : 
- change color on customizer, you will have alert because color just changed
- click one link on live preview, when page load, alert will shown without customizer color option clicked.

``` javascript
wp.customize('my_color', function (value) {
    value.bind(function (state) {
        alert('only execute when item change, not during first time load or page change');
    });
});
```

``` php
Kirki::add_field( 'mytheme', array (
    'type'      => 'color',
    'settings'  => 'my_color'',
    'label'     => __( 'Text Color', 'translation_domain' ),
    'section'   => 'custom_color',
    'default'   => 1,
    'priority'  => 1,
    'transport' => 'postMessage',
    'js_vars'   => array(
        array(
            'element'  => 'body',
            'function' => 'css',
            'property' => 'background-color',
        ),
        array(
            'flag' => 'do_something'
        )
    )
));
```

**Comment by aristath** [comment]
Using the develop branch I can't replicate your issue...
I used your field and added this at the end of this file: https://github.com/aristath/kirki/blob/develop/assets/js/controls/color.js I added the following:

``` js
wp.customize( 'my_color', function( value ) {
    value.bind( function( state ) {
        console.log( state );
    });
});
```

Everything seems to be working perfectly fine on my end!
Perhaps there's some other code triggering this?

**Comment by jegbagus** [comment]
hi aristath, thank you for replying me back. i create simple WordPress themes for you to replicate this issue https://dl.dropboxusercontent.com/u/31421656/ngetest.zip (i also try it using clean wordpress install)

i also create video for you  https://youtu.be/rXH2Z6nIP1c

i'm not using any plugin, and using latest WordPress version (4.5.2) and using develop branch 

issues is when i click a link, it always give me alert because everytime link clicked, it execute this code : 

``` javascript
var api = wp.customize;

api('ngetest_color', function (value) {
    value.bind(function (color) {
        alert('only execute when item change, not during first time load or page change');
    });
});
```

Thank you

**Comment by jegbagus** [comment]
hi  aristath , i finally found out fix for this problem.
its from sanitize color. once i disable it sanitize callback from Kirki_Field_Color class, i don't have this kind of problem anymore.
hope this help someone who have same issues.

Thank you

**Comment by aristath** [comment]
I believe this is no longer an issue so I'll go ahead and close this ticket.
If it happens again feel free to open a new ticket 👍
