### ISSUE TITLE
Upgraded to latest version and nothing is working

### ISSUE THREAD

**Issue by Digital-Odyssey** [themeum/kirki#1025]
### Issue description:

Hi, i just updated the framework files in my theme and now when i try to access the theme customizer i get a whack of javascript errors and the page only partially loads.

All of the errors are similar to the following:

Timestamp: 2016-06-08 4:44:27 PM
Error: SyntaxError: expected expression, got '<'
Source File: http://wp.pulsarmedia.ca/viennalite/assets/js/vendor/wp-color-picker-alpha.js?ver=1.2
Line: 1
Source Code:
<br /> 

It looks like its a path issue. How do i fix this?
### Version used:

develop branch from github

**Comment by Digital-Odyssey** [comment]
I am also getting the following error:

Timestamp: 2016-06-08 5:02:18 PM
Error: TypeError: window.kirki is undefined
Source File: http://wp.pulsarmedia.ca/viennalite/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,customize-base,wp-a11y,customize-controls,backbone,wp-util,wp-backbone,customize-widgets,accordion,customize-nav-menu&load%5B%5D=s,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,shortcode,media-models,wp-plupload,mediaelement,wp-mediaelement,media&load%5B%5D=-views,media-editor,media-audiovideo,mce-view,imgareaselect,image-edit,customize-models,customize-views&ver=4.5.2 line 5 > Function
Line: 9

**Comment by aristath** [comment]
Can you please try the latest develop branch from this repository and let me know if that still happens there?

**Comment by Digital-Odyssey** [comment]
Yea i am using the latest develop branch - i mentioned it in my first message under Version Used

**Comment by aristath** [comment]
I can't replicate this issue on my localhost, everything seems to be working fine here!
Can you please send me a copy of your theme so that I may see what's wrong?

**Comment by Digital-Odyssey** [comment]
[vienna-lite.zip](https://github.com/aristath/kirki/files/305832/vienna-lite.zip)

Sure, it should be attached to this reply. Thanks.

**Comment by aristath** [comment]
Can you please pull the latest commit from the develop branch and test if that fixes the issue for you?
It seems to do the trick using your theme on my localhost. 👍

**Comment by Digital-Odyssey** [comment]
yup its working now...and there are no PHP errors showing either in the customizer area (something i forgot to mention earlier)

Thanks for your help :]

**Comment by aristath** [comment]
👍 Glad I could help!
