### ISSUE TITLE
sortable request 

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#1026]
@aristath I use sortable control and found it super easy to use for displaying social link. But the problem is that there is no text field for the link. Do you have any plan to add text type to sortable or I'd better use repeater control ?
Thanks

**Comment by Vishal-Deshpande** [comment]
@robbisy Repeater control won't be handy in this case. I second the request for text field in sortable control.

**Comment by aristath** [comment]
Added as a feature request.

**Comment by mapsteps** [comment]
We have done this in our Premium Add-On for Page Builder Framework by conditionally displaying an input field, if certain fields in the sortable field are turned on. It's additional work but gets the job done.
