### ISSUE TITLE
Return as inline CSS for Typography field on Kirki::get_variables()

### ISSUE THREAD

**Issue by edirpedro** [themeum/kirki#1027]
I'm compiling Sass directly on theme, so i'm using variables to store the settings and not outputting inline CSS. I'm trying to figure out how to output properly the Typography field as a variable to Sass.

For `output` atribute, Kirki builds this array:

```
array (
  'global' => 
  array (
    'body' => 
    array (
      'font-family' => '"Open Sans", Helvetica, Arial, sans-serif',
      'font-weight' => '400',
      'font-style' => 'normal',
      'font-size' => '14px',
      'line-height' => '1.5em',
      'letter-spacing' => '0',
    ),
  ),
)
```

But for `variables` atribute, I can only receive back-end values:

```
array (
  'font-family' => 'Open Sans',
  'font-size' => '14px',
  'variant' => 'regular',
  'line-height' => '1.5em',
  'letter-spacing' => '0',
  'subsets' => 
  array (
    0 => 'latin-ext',
  ),
)
```

What do you think if `variables` atribute could return exactly like the CSS output, with the complete font-family using a font fallback and the variant options set. There is not utility to store **variant**, **subsets** and a single **font-family** to use inside a Sass code.

I could write something like this for example:

```
Theme_Kirki::add_field(THEME_ID, array(
    'type'          => 'typography',
    'settings'      => 'typography_content',
    'label'         => __('Content', THEME_ID),
    'description'   => __('All text content.', THEME_ID),
    'section'       => 'typography_general',
    'default'       => array(
        'font-family' => 'Open Sans',
        'variant' => 'regular',
        'subsets' => array('latin'),
        'font-size' => '14px',
        'line-height' => '1.5em',
        'letter-spacing' => '0',
    ),
    'variables'     => array(
        array(
            'name' => 'typography_content',
            'callback' => 'sass_typography_map'
        )
    )
));

// Maybe this could be included to Helpers
function sass_typography_map($value) {
    $output = array();
    foreach($value as $property => $val) {
        $output[] = "$property : $val";
    }
    return '(' . join(', ', $output) . ')';
}
```

**Comment by aristath** [comment]
Adding as a feature request for 3.1

**Comment by JeffAspen** [comment]
Is this currently a feature?

**Comment by aristath** [comment]
Not yet implemented but in the to-do list, will be implemented pretty soon. 👍 
Moving to 3.0.10, I think we can make it for this update.

**Comment by aristath** [comment]
Added tweaks for typography controls so closing this one.

You can get the variables using `Kirki_Util::get_variables()`.
After that you can map them however you like.
