### ISSUE TITLE
Sortable Field doesn't give default values

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#1028]
Hi @aristath 
### Issue description:

> > Sortable field return empty string even we set default values. It returns array only after we have made some change in the sortable field.
### Version used:

latest develop branch
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'my_config', array(
        'type'        => 'sortable',
        'settings'    => 'sort_aboutpage',
        'label'       => **( 'Sort Sections', 'my_textdomain' ),
        'section'     => 'sort_about_section',
        'default'     => array( 'intro', 'stat', 'mission', 'core', 'client' ),  
        'choices'     => array(
            'intro'   => esc_attr**( 'Intro Section', 'my_textdomain' ),
            'stat'    => esc_attr__( 'Stat Counter Section', 'my_textdomain' ),
            'mission' => esc_attr__( 'Our Mission Section', 'my_textdomain' ),
            'core'    => esc_attr__( 'Our Core Values Section', 'my_textdomain' ),
            'client'  => esc_attr__( 'Our Client Section', 'my_textdomain' ),  
        ),  
    ) );

In Front End
$sections = get_theme_mod( 'sort_aboutpage', array( 'intro', 'stat', 'mission', 'core', 'client' ) );

Thanks

**Comment by Vishal-Deshpande** [comment]
I don't think there is anything wrong with it. All the fields of customizer ( nothing to do with Kirki) returns empty by default. This looks odd but that is how it is. That is why you need to specify the second parameter for get_theme_mod which you have rightly done.  You can test with any other field.

**Comment by aristath** [comment]
@manandharsudin theme mods are by default empty, and only have a value after you change them.
Default values are only there to control what will be shown in the controls if no value is set.
Default values however are not saved in the database and they will never be saved because the WordPress Themes Review Team prohibits that (for good reason).

Adding a default value in the `get_theme_mod` function is mandatory.
