### ISSUE TITLE
Slider control not accurate

### ISSUE THREAD

**Issue by JAW-Dev** [themeum/kirki#1034]
### Issue description:

The slider jumps after adjusting. For instance when you slide down to 10. After the refresh it jumps to 9, and when you slide up to 10. It's at 11 after the refresh
### Version used:

2.3.4
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Yes
### Using theme_mods or options?

options

**Comment by aristath** [comment]
Hey there!

What options exactly are you using for min/max/step so that I may try to replicate this?

**Comment by JAW-Dev** [comment]
All types really, I experimented with different min/max/step variations and they all do it. Here is an example.

``` php
Kirki::add_field( FCCT_Settings, array(
    'type'        => 'slider',
    'settings'    => FCCT_THEME_PREFIX . '_footer_bottombar_padding_right',
    'label'       => __( 'Right Padding', 'fcct' ),
    'section'     => FCCT_THEME_PREFIX . '_footer_bottombar_section',
    'default'     => '0',
    'priority'    => 10,
    'choices'     => array(
        'min'  => '0',
        'max'  => '200',
        'step' => '1',
    )
) );
```

**Comment by Vishal-Deshpande** [comment]
Could not replicate the issue on FF and Chrome.  @jawittdesigns  Which browser you are using?

**Comment by aristath** [comment]
I'm afraid I couldn't replicate this either....
