### ISSUE TITLE
postmessage function don't get save

### ISSUE THREAD

**Issue by soniapello** [themeum/kirki#1035]
### Issue description:

the postmessage function works properly in the customizer but it doesn't work outside
### Version used:

the last develop branch from github
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'my_config', array(
  'type'        => 'radio-image',
  'settings'    => 'my_ser',
  'label'       => esc_html__( 'Radio image', 'my_textdomain' ),
  'section'     => 'slideri',
  'default'     => 'ball-clip-rotate',
  'priority'    => 10,
  'choices'     => array(
    'ball-clip-rotate'   => trailingslashit( get_template_directory_uri() ) . '/images/grid-1.jpg',
    'square-spin' => trailingslashit( get_template_directory_uri() ) . '/images/grid-2.jpg',
    'ball-rotate'  => trailingslashit( get_template_directory_uri() ) . '/images/grid-3.jpg',

  ),
  'transport'   => 'postMessage',

    'js_vars'   => array(

        array(

            'element'  => '#loaders',

            'function' => 'loader_preview'
        ),

    ),

) );
```

loader_preview.js

```
(function( $ ) {
    "use strict";

    wp.customize( 'my_ser', function( value ) {
        value.bind( function( to ) {
            $( '#loaders' ).unwrap().removeClass().wrap( "<section class='loading-overlay'></section>" ).addClass(  'loading-overlay loader-inner ' +  to );

        } );
    });


})( jQuery );
```

**Comment by aristath** [comment]
`js_vars` are only used to handle the customizer's `postMessage`.
The options are saved, but in order to see the changes applied to your frontend you can either use the `output` argument for CSS changes, or in your case just add the changes to your PHP template.
In your example above, I think you'd have to do something like this in your template file:

```
<section class="loading-overlay">
    <div id="loaders" class="loading-overlay loader-inner <?php echo esc_attr( get_theme_mod( 'my_ser', 'ball-clip-rotate' ) ); ?>">
        The #loader contents here
    </div>
</section>
```

**Comment by soniapello** [comment]
@aristath  Thanks for your answer but i have one question on get theme mod . Is there any special filter on that ?
Because when I'm trying to echo `$loaders_val` variable in PHP. This variable are HTML tag but it's seen like text in the browser. I've trying two different way` echo '<section id="loader">'.$loaders_val.'</section>'; `and echo` "<section id='loaders'>$loaders_val</section>"; `but without success so maybe get_theme_mod internally calls apply_filters for output ?

    <footer  class="site-footer" role="contentinfo">
    	        <?php    $preloader_val = get_theme_mod( 'my_s', 'homepage' );
    	                 $loaders_val = get_theme_mod( 'my_ser', '<div class="loading-overlay"><div class="loader-inner ball-zig-zag"><div></div><div></div></div></div>' );
    					    if (  $preloader_val == "page") {
    			     echo '<section id="loader">'.$loaders_val.'</section>';
    			}elseif ($preloader_val == "homepage" && is_front_page()){
    			  echo "<section id='loaders'>$loaders_val</section>";
    			} elseif ($preloader_val == "none") {
    			  return;
    			}?> 
    </footer>


Which give something like this in the browser:
[![enter image description here][1]][1]


  [1]: http://i.stack.imgur.com/doqTH.png

**Comment by aristath** [comment]
@soniapello did you manage to resolve this one?
I see you closed this issue...

**Comment by soniapello** [comment]
@aristath  yes get_theme_mod escape his output so to to output html I had to hook  theme modification like this:

function my_htmlspecialchars($value) {
    return htmlspecialchars_decode($value);
}  
add_filter('theme_mod_my_ser', 'my_htmlspecialchars');
