### ISSUE TITLE
Typography field with multi-selectors and different properties.

### ISSUE THREAD

**Issue by abouolia** [themeum/kirki#1036]
### Issue description:

Why is this not possible? is there another way to do like that or something? because typography field so restricted. Thanks.

```
 Kirki::add_field('postvision', array(
        'type'        => 'typography',
        'settings'    => 'typography-h3',
        'label'       => __('Headings H3' ),
        'description' => __('Custom typography style for heading tag H3.'),
        'section'     => 'typography',
        'default'     => array(
            'font-size' => '32px',
            'color'     => $headings__color,
        ),
        'priority'    => 80,
        'choices'     => array(
            'font-style'     => false,
            'font-family'    => false,
            'font-size'      => true,
            'font-weight'    => false,
            'line-height'    => false,
            'letter-spacing' => false,
            'color'          => true,
            'units'          => array( 'px', 'rem' ),
        ),
        'output' => array(
            array(
                'element'     => 'h3',
                'property' => 'font-size',
                'media_query' => '@media (min-width: 768px)',
            ),
            array(
                'element'     => 'h3',
                'property' => 'color',
            ),
        ),
    ) );

```

**Comment by abouolia** [comment]
By the way how do i deal with `exclude` argument in typography field? I think doesn't support it yet.

**Comment by abouolia** [comment]
I suggest the `exclude` argument in typography field or in any multi-fields control to be like that

```
'exclude' => array(
        'font-size' => array('14px'),
        'line-height' => array('1'),
),
```

**Comment by aristath** [comment]
For consistency reasons typography fields apply all properties to the same selectors.
If you want each property of the typography field to be applied to different selectors, then perhaps it would be best to separate them a bit on your implementation.
So you can have the typography field to select the font-family for example for elements A, B & C.
Then a separate dimension field for example to select the font-size that will be applied to elements A & B, and a slider for line-height that will be applied to elements B & C.
