### ISSUE TITLE
Allow using settings instead of theme options

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#104]
Now that the `kirki_get_option` works this will be possible.

**Comment by aristath** [comment]
Just thinking out loud here...

`theme_mods` are basically just wrappers for options.
So... what we could do is this:
1. ALWAYS use options
2. Write our own implementation for `theme_mods`
3. if we want to use `theme_mods` then all we have to do is set the option name to `theme_mod_{$theme_name}`

This will also facilitate integration with other frameworks such as Redux (see https://github.com/aristath/kirki/issues/8)

**Comment by aristath** [comment]
The alternative would be to use theme_mods in the customizer, and when we save the customizer, then clone the theme_mods to an option.

**Comment by vpratfr** [comment]
Not sure it's a good idea: there are some WP customizer fields that appear by default (static pages, menus, header, etc.)

Those default sections may be saving their setting using theme mods. And if Kirki is using options, we would be having an inconsistency.

So I personnally think that you should simply provide a wrapper to get the setting value and that wrapper would use theme_mod functions.

**Comment by aristath** [comment]
The problem I'm currently facing is that I was contacted by a theme dev who wants to use Kirki, but their commercial theme uses Redux and options instead of theme_mods.
They want to use Kirki but so far have been unable to, because we currently have to way to use options.
As explained by Otto [here](http://wordpress.stackexchange.com/questions/155072/get-option-vs-get-theme-mod-why-is-one-slower/162131#162131) options are faster than theme mods so performance could be an extra benefit for some people.

In the end, the WordPress Customizer API gives the option to use `option` or `theme_mod` when creating a setting, and we're forcing the use of theme mods.
I'd like to change that and provide at least the same options that WP Core offers!

It's just a matter of finding the best way to do that.

Any ideas?

**Comment by vpratfr** [comment]
Well, to me the answer from Otto can be summarized in his first sentence:

> The answer that yes, the theme_mod functions will be slower, but not significantly, and the benefits outweigh the differences.

I don't see why that would be a problem. Redux does it differently, I am not convinced that is better though. And I prefer your approch to stay as close as possible to the WP core stuff (only augmenting the amount of controls that are offered).

Anyway, if you allow using options, take care to store them in a single array, and make sure that array has a unique name (for instance the theme name). In the end, you would end up writing something similar to theme_mod functions.

I chose Kirki for my upcoming commercial products because it is not bloated like most other frameworks. If you want to turn it into the next Redux, I'll pick a different option or just fork Kirki and keep it simple :)

**Comment by aristath** [comment]
The problem is that I have not only augmented the number of controls...
I have taken away the ability to use options.

I agree with you 100% that theme_mods are preferable... but WP Core does have the ability to use options, and I have removed that ability.
I'll definitely NOT turn this into Redux... there's a reason I stopped using it. Though perfectly well-coded, it's bloated like you said.
I just want to give back something that I should not have removed in the first place... something that exists in WP Core.

**Comment by ghost** [comment]
Please do not turn this into another Redux. I wish the product I have invested so many hours already doesn't rely on it so heavily. Not only that, but it is bloated the crap out  of our plugin. However Dovy did make some special tool to be able to include only the things you need. But still, the name just goes through my bones like a kniife.

I am in same boat wanting to choose Kirki in the next product. I love what is being done here.

**Comment by aristath** [comment]
LOL I never said anything about turning this into redux.

The fact remains that from day 1 of this project I hard-coded the use of theme-mods, and took away the native WP ability to choose if we want to use theme mods or options. That was a mistake I made when I first started this project and I have to make it right at some point.
The majority of frameworks use options instead of theme mods. I don't want to force either, I want people using Kirki to have the ability to choose on their own. I want to default to using theme_mods, but if someone explicitly wants to use options instead then that's their choice, not mine.

What I am trying to do is provide a way for people to use the customizer.
There are a ton of themes out there that use redux, smof and others.
Eventually I would like to build a **separate** plugin that will take care of integration/migration from other frameworks to Kirki (I don't want this in the plugin core, it will be a separate plugin).

The Customizer is the native WP options framework.
Isn't helping people migrate to using that instead of other frameworks worth it?

**Comment by ghost** [comment]
Worth it indeed... whew on the R...x thing. Makes me shudder each time I hear the name. Makes me cringe even more that I have it in my product.

If anything I would love to see Kirki and Advanced Admin Framework get married and have chicklets that share the same parents, as these are on the same wavelength.

**Comment by aristath** [comment]
Advanced Admin Framework?
I don't know that one... Can you post a link?

**Comment by ghost** [comment]
OOPS > meant Admin Page Framework by Micheal Uno
https://github.com/michaeluno/admin-page-framework

**Comment by vpratfr** [comment]
@aristath about how to do that: 
- for a start, you can expose that 'storage_type' as a property of the control in the configuration (either 'setting' or 'theme_mod').
- then when you register the setting, you can pass that info
- for fetching the value, as far as I can remember there is something like $wp_customize->get_setting(...), no?

**Comment by aristath** [comment]
We can now use options in the customizer.
`'options_type'` has to be defined in the configuration in order to use this:

``` php
/**
 * Configuration sample for the Kirki Customizer
 */
function kirki_demo_configuration_sample() {

    $args = array(
        'logo_image'    => 'http://kirki.org/images/logo.png',
        'description'   => __( 'This is the theme description. You can edit it in the Kirki configuration and add whatever you want here.', 'kirki' ),
        'color_accent'  => '#00bcd4',
        'color_back'    => '#455a64',
        'options_type'  => 'option',
    );

    return $args;

}
add_filter( 'kirki/config', 'kirki_demo_configuration_sample' );
```

Please not that for the time being each setting is set individually in the database.
In the future we will also be able to define an option name and if one is defined then the sub-settings will simply be an array.
