### ISSUE TITLE
Repeater row_label arguments are undocumented

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1040]
### Issue description:

The repeater control has optional arguments for a row label and button label, but I had to dig into the code to find them. As far as I can tell, these options are not documented in the official documentation.
### Version used:

https://kirki.org/docs/controls/repeater.html
### Using theme_mods or options?

N/A
### Code to reproduce the issue (config + field(s))

N/A

**Comment by iliman** [comment]
Yes, documentation hasn't been updated for a long time. But you can read about `row_label` [here](https://github.com/aristath/kirki/pull/844#issuecomment-211394140).
And if you can create a pull request to `gh-pages` branch and document this, it would be great. (My english isn't very good to write documentation)

**Comment by aristath** [comment]
If someone can spare a few minutes to update the docs on https://kirki.org/docs/controls/repeater.html that would be great...
Sorry I'm not doing it myself, time is a luxury right now. 😞
