### ISSUE TITLE
The panel/section hidden

### ISSUE THREAD

**Issue by tutv** [themeum/kirki#1044]
### Issue description:

I add custom field to the customizer but I only want to include kirki in admin but it does not work properly.

[Video demo](https://i.imgflip.com/170nv4.gif)

![demo](https://cloud.githubusercontent.com/assets/7255177/16641700/6984741c-442d-11e6-952e-b13907d7c321.png)
### Version used:

Version 2.3.5 (Download from wordpress.org)
### Using theme_mods or options?
- theme_mod
### Code to reproduce the issue (config + field(s))

```
if (is_admin()) {
    function kk_run() {
        Kirki::add_config( 'my_them___e', array(
            'capability'  => 'edit_theme_options',
            'option_type' => 'theme_mod',
        ) );

        Kirki::add_panel( 'panel_id', array(
            'priority'    => 10,
            'title'       => __( 'My Title', 'textdomain' ),
            'description' => __( 'My Description', 'textdomain' ),
        ) );

        Kirki::add_section( 'custom_css', array(
            'title'          => __( 'Kirki section' ),
            'description'    => __( 'Add custom CSS here' ),
            'panel'          => '', // Not typically needed.
            'priority'       => 160,
            'capability'     => 'edit_theme_options',
            'theme_supports' => '', // Rarely needed.
        ) );

        Kirki::add_field( 'custom_css', array(
            'type'     => 'code',
            'settings' => 'code_demo',
            'label'    => __( 'Code Control', 'my_textdomain' ),
            'section'  => 'custom_css',
            'default'  => 'body { background: #fff; }',
            'priority' => 10,
            'choices'  => array(
                'language' => 'css',
                'theme'    => 'monokai',
                'height'   => 250,
            ),
        ) );
    }

    add_action('plugins_loaded', 'kk_run');
}
```

**Comment by aristath** [comment]
Hey there!

What exactly do you mean by "I only want to include kirki in admin"??
Kirki is in the customizer, therefore it's ALWAYS in the admin.
The customizer's URL is /wp-admin/customize.php.
That never changes, so I really don't understand what it is you're trying to achieve.
Can you please elaborate?

**Comment by tutv** [comment]
Hi @aristath 

So I include kirki without adding any conditions? And it will not affect the performance of front-end!

Thanks.

**Comment by aristath** [comment]
> So I include kirki without adding any conditions? And it will not affect the performance of front-end!

Well, it depends... If you add 900 color fields in the customizer and use Kirki to output the CSS result of those colors in your frontend then yes, it will have an impact. But no more than a couple of milliseconds at worst. 👍
