### ISSUE TITLE
variables - accessing Kirki class instance in my compiler file

### ISSUE THREAD

**Issue by julie2234** [themeum/kirki#1045]
I am trying to use Kirki to write SCSS variables to a file before compiling my CSS. I am following the documentation here https://kirki.org/docs/arguments/variables.html. I am using http://leafo.net/scssphp/ as my scss php compiler.

I am stuck on the line `$variables = Kirki::get_variables();` (third section of code in the [documentation](https://kirki.org/docs/arguments/variables.html)). I can't figure out which file to include to get a reference to the Kirki class. I've tried 'kirki.php' in the plugins folder, 'include-kirki.php' in my theme's lib folder, and 'class-s216master-kirki.php' the wrapper class for Kirki for my theme.

Any help would be greatly appreciated!

`<?php

require "scss.inc.php";
//require dirname(**FILE**).'/../../../plugins/kirki/kirki.php';
//require 'class-s216master-kirki.php';
//require 'include-kirki.php';

ob_start(); // Capture all output into buffer
$variables = Kirki::get_variables();
foreach ( $variables as $variable => $value ) {
   echo '$' . $variable . ':' . $value . ';';
}
$scss = ob_get_clean(); // Store output in a variable, then flush the buffer

$directory = "../assets/styles/main";
file_put_contents($directory . '/_kirki_variables.scss', $scss, LOCK_EX);

scss_server::serveFrom($directory);

?>`

**Comment by aristath** [comment]
I don't get it...
If Kirki is installed as a plugin and activated, then you should be able tyo simply do something like this:

``` php
add_action( 'customize_save_after', function() {
  // Your code here
});
```

**Comment by julie2234** [comment]
Oh I see, I was trying to get the Kirki variables in my compiler file. I didn't realize I should do that from the Wordpress functions file. I tried your suggestion and it's working now. Thank you so much!
