### ISSUE TITLE
Type editor do not work properly

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1046]
### Issue description:

'type'        => 'editor', works but not perfectly. we can not add link etc. this is very important field so please give it high priority.
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.5
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

'type'        => 'editor',

**Comment by rinkuyadav999** [comment]
is there any alternate type since editor is not working perfectly.

**Comment by thatvideowebguy** [comment]
Same problem here

**Comment by aristath** [comment]
I'm unable to replicate this one, I can add links perfectly fine!

**Comment by stev0n** [comment]
Hi

Could this be the same problem that I experienced >
Link button popup and tools tips are hidden underneath. z-index needed adjusting

see: #1159

regards
steve

**Comment by rinkuyadav999** [comment]
Tested type = editor in twentyseventeen theme. Same issue. Screenshot added !!
![type-editor-issue](https://cloud.githubusercontent.com/assets/9743287/21751193/3798e052-d5e9-11e6-8195-cc181a51d63a.png)

**Comment by rinkuyadav999** [comment]
When we click on insert link button, popup should appear like this:

![editor-issue-1](https://cloud.githubusercontent.com/assets/9743287/21751831/a46830b6-d5f3-11e6-913b-ec375c80f8e5.png)

**Comment by rinkuyadav999** [comment]
What is problem?
Answer: It is actually working but problem is in user interface / css / js.

When i add manually css> z-index:50000; it display popup to insert link.

![editor-issue-3](https://cloud.githubusercontent.com/assets/9743287/21752079/400aa770-d5f8-11e6-9193-04a750a19338.png)



when click on setting icon, it does not work because another div should have proper css> z-index

**Comment by thatvideowebguy** [comment]
are you able to add settings to the editor ? 
Like hide media_upload button
or show style (headings, p, ...)

**Comment by rinkuyadav999** [comment]
Media upload button is working fine and i think, can be hide using css.
Problem is that we can not insert link using insert link button.

**Comment by thatvideowebguy** [comment]
Yes same issue here. I was just wondering if we have access to some options ( settings from the wp_editor() function ) when the field is registered with Kirki

**Comment by rinkuyadav999** [comment]
@aristath how it can be fixed?

**Comment by rinkuyadav999** [comment]
@thatvideowebguy @aristath @stev0n @andreg @doitmax 

https://github.com/aristath/kirki/pull/1246

This works fine for me.

**Comment by aristath** [comment]
This should be working in the develop branch so I'm closing this one.
If it's still an issue please feel free to reopen (note: this has not been fixed in the 2.3.7 version, just on the develop version)
