### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by vpratfr** [themeum/kirki#105]
Fatal error: Call to undefined method Kirki_Controls::control_clean() in .../vendor/aristath/kirki/includes/helpers.php on line 32

We have the latest master branch as of today at 7:45pm Paris time

**Comment by aristath** [comment]
Hey there! Can you please check now?

**Comment by vpratfr** [comment]
I'll try tomorrow and open a new issue if not resolved.

Would be great if you could be a little more strict on your usage of git/packagist. For a start as soon as possible, please link packagist to the github web hooks and make a first tag so that we can start using kirki from composer with a proper version number dependency.

Also, would be good if you could work on a "develop" branch and merge that branch to "master" only when you tag a new release. This would avoid getting such fatal errors while we are developing.
