### ISSUE TITLE
Image field saves ID and sometimes the image URL

### ISSUE THREAD

**Issue by allysonsouza** [themeum/kirki#1052]
### Issue description:

Creating an image field in the same project, in the same panel, and one return the ID, and the other return the image URL.
### Version used:

2.3.5
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

I just created two simple image fields, and uploaded different images for each one.

**Comment by aristath** [comment]
Can you please post the exact code you were using because I'm unable to replicate this?
Thank you!

**Comment by allysonsouza** [comment]
Sorry for open this issue, it's a mistake in my code.
