### ISSUE TITLE
Output HTML code

### ISSUE THREAD

**Issue by thehung2224** [themeum/kirki#1053]
Hi, I had one quick question for you. I was wondering if its possible to output html to a section's description? The code is below but what I'm trying to do is add html to the text. Am I missing something simple or is this not advised/possible? Thanks so much!

Kirki::add_field( 'thememove', array(
    'type'     => 'text',
    'settings' => 'page_404_big_title',
    'label'    => esc_attr__( 'Title', 'tm-heli' ),
    'section'  => $section,
    'priority' => $priority ++,
    'default'  => 'PAGE NOT FOUND',
) );

In Customize
http://prntscr.com/brrtm0

Output
http://prntscr.com/brrtpv

After that, when I checked again, html code auto convert to entity code 
http://prntscr.com/brrt7n

**Comment by aristath** [comment]
@thehung2224 You're using a text field for that.
text-fields by default in Kirki are sanitized using the `esc_textarea` WordPress function.
Try adding this line in your field:
`'sanitize_callback' => 'wp_kses_post',`

or you can write your own sanitization functions and use them. 👍

**Comment by thehung2224** [comment]
It doesn't work.

**Comment by aristath** [comment]
> It doesn't work.

Please provide more information. 
Can you post the full code you're using? (config + field)

**Comment by thehung2224** [comment]
Sorry for late reply, please check this code

```
Kirki::add_field( 'thememove', array(
    'sanitize_callback' => 'wp_kses_post',
    'type'     => 'text',
    'settings' => 'page_404_big_title',
    'label'    => __( 'Title', 'tm-heli' ),
    'section'  => $section,
    'priority' => $priority ++,
    'default'  => '<b>PAGE</b> NOT FOUND',
) );
```
