### ISSUE TITLE
Live Preview seems not working with color field

### ISSUE THREAD

**Issue by fakrulislam** [themeum/kirki#1054]
### Issue description:

Hi @aristath , I am trying to include a color field type for a element to set background color & it's working perfectly (successfully saved). 

But the live preview in the customizer is not working, I tried to figure it out but failed. Could you please take a look at the config code what I am doing wrong?
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

2.3.5
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
    tcsupport_Kirki::add_field( 'tcsupport_header_bg_color_option', array(
        'type'        => 'color',
        'settings'    => 'tcsupport_header_bg_color_option',
        'label'       => __( 'Change header background color', 'tcsupport' ),
        'section'     => 'tcsupport_header_style_section',
        'default'     => '#2196f3',
        'priority'    => 10,
        'alpha'       => true,
        'transport'   => 'postMessage',
        'js_vars'     => array(
            array(
                'element'  => '#tc-header',
                'function' => 'css',
                'property' => 'background-color',
            ),
        ),              
    ) );
```

**Note:** When I change the function **css** to **html** it shows the HEX value in real-time (while changing through the color picker) . See: http://prntscr.com/bs9tnc

Thanks for your help.

**Comment by aristath** [comment]
Try using this code instead and let me know if that fixes your issue:

``` php
    tcsupport_Kirki::add_field( 'tcsupport_header_bg_color_option', array(
        'type'        => 'color',
        'settings'    => 'tcsupport_header_bg_color_option',
        'label'       => __( 'Change header background color', 'tcsupport' ),
        'section'     => 'tcsupport_header_style_section',
        'default'     => '#2196f3',
        'priority'    => 10,
        'alpha'       => true,
        'transport'   => 'auto',
        'output'      => array(
            array(
                'element'  => '#tc-header',
                'property' => 'background-color',
            ),
        ),              
    ) );
```

**Comment by fakrulislam** [comment]
Hi @aristath , 
Sorry for late reply, was out of city.

Thanks it's working now with your code. 

Could you give me any suggestion about this https://github.com/aristath/kirki/issues/1058 ?

I saw your suggested code https://github.com/aristath/kirki/blob/2.3.5/includes/output/field/class-kirki-output-field-typography.php#L44-L56 & it's working fine in the customizer preview. But can't find any way to get the variant value separately (font-weight, font-style) for displaying in frontend when selected italic form. 

https://kirki.org/docs/controls/typography.html .
