### ISSUE TITLE
Suggestion: Change the font family drop down

### ISSUE THREAD

**Issue by VladNov** [themeum/kirki#1060]
### Issue description:

Hi Guys,

What do you think about changing the font family dropdown UI? Currently it's a bit hard to find a desired font in the list of all available fonts. The dropdown with a search field, as used in Redux Framework, can easily solve it.
### Version used:

Latest dev.
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

Just the Typography field.

**Comment by aristath** [comment]
@VladNov Redux is using https://select2.github.io/ for dropdowns.

In the past we were also using Select2, but there were a lot of conflicts with 3rd-party plugins that were also using the same script and were not properly defining properties etc, so we were forced to switch to another script.

We now use http://selectize.github.io/selectize.js/ and that gave us the opportunity to solve many other issues as well...

**Comment by VladNov** [comment]
@aristath 

Thank you for your answer. I meant the functionality of search inside the dropdown and i see that Selectize have this option.

I can't believe i missed it. Now i see that that if i hit the Delete key it allows me to type the font name.

**Comment by aristath** [comment]
Yeah, i get your point and I fully agree! Admittedly it would be better if the delete key was not needed...
