### ISSUE TITLE
Font variants multiple select or all (disable variants)

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#1062]
### Issue description:

I tried to disable variants (by not including variants in "typograhy" > "default" array), becuase I need my body font to be able to use multiple variants - in content it should be possible to use multiple text formatting (bold, italic, light ...). Currently, the select field allows only single option.
Wouldn't it be better to have multiple select (like "subset"), or to disable variants (and allow all available) ?
### Version used:

2.3.5
Not tested with development verison
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'natura_micemade_customizer',array(
    'type'        => 'typography',
    'settings'    => 'fonts_body',
    'label'       => esc_html__( 'Body font', 'natura' ),
    'description' => esc_html__( 'set font for all elements except for titles', 'natura' ),
    'help'        => esc_html__( 'use this setting visely as it affects all body font on site (except for titles and main menu)', 'natura' ),
    'section'     => 'fonts_section',
    'default'     => array(
        'font-family'    => 'Roboto',
        'font-size'      => '16px',
        'line-height'    => '1.5',
        'letter-spacing' => '0',
        'subsets'        => array( 'latin-ext' ),
        //'variant'        => '',
        //'color'          => '#333333',
        //'text-transform' => 'none',
        //'text-align'     => 'left'
        ),
    'priority'    => 10,

    'output'      => array(
        array(
            'element'  => 'body',
        ),
    ),
) );

```

**Comment by Anydog** [comment]
Anyone ?

**Comment by aristath** [comment]
Try adding this:

``` php
add_action( 'wp', function() {
    if ( class_exists( 'Kirki_Fonts_Google' ) {
        Kirki_Fonts_Google::$force_load_all_variants = true;
    }
});
```

This will force-load all variants for selected google fonts. 👍

**Comment by Anydog** [comment]
Thanks Aristath :clap:
this works. However, wouldn't it be nice to have multiselect possiblity, like for variants ?
Just a suggetsion ... (if I had required knowledge I would do it and do the pull req. ... ) :flushed:

**Comment by aristath** [comment]
> However, wouldn't it be nice to have multiselect possiblity, like for variants ?

I'm afraid not.
typographies are assigned via the `output` argument to a specific element so that developers may easier control the output of those elements.
If you have a typography control for H1 headers for example, you should be able to select that you want them bold via the customizer.
If we allow multi-select for variants, then google-fonts will be loaded with all the variants the user selects, but the element that is controlled by that typography control will not have any variant applied since we can't know which one to apply.

The typography control is not a google-fonts-loader.
It's a typography control that allows you to select what kind of typography options you want applied to a specific element of your page.

**Comment by Anydog** [comment]
Thanks for your time to explain, Aris (may I call you Aris ? ;) )
I read this couple of times and ... I couldn't agree ...

If user selects multiple variants then those variants will apply correctly  if in WP editor user bolded or "italicized" text. If he/she uses only one variant (since there's no multi-variants) then the blog text (for example) will have **only that variant available** and formatted text will not have font native variants (only browser false bolded or italic)

... or, I don't understand something ... :/

**Comment by Qodux** [comment]
> I'm afraid not.
> typographies are assigned via the output argument to a specific element so that developers may easier control the output of those elements.
> If you have a typography control for H1 headers for example, you should be able to select that you want them bold via the customizer.
> If we allow multi-select for variants, then google-fonts will be loaded with all the variants the user selects, but the element that is controlled by that typography control will not have any variant applied since we can't know which one to apply.
> 
> The typography control is not a google-fonts-loader.
> It's a typography control that allows you to select what kind of typography options you want applied to a specific element of your page.

Hey there,

I've started to use your great plugin in my themes and for now I'm building customizer options.

I know about your reasons that you don't want to add multiple variants for typography field though that would be a great feature for typography. For now I've put an option to force loading all variants but that would load all variants for all the google fonts used in theme. I need for example just "Open Sans" font with 300, 400, 700 weights only and a multiple select for variants would be great. You could use the "**drag_drop**" plugin for selectize.js. This way the user/author will load the font weights needed and the output for that element will take the #1 variant. Users could easily drag_drop the variants they need by default on the first place.

The other loaded variants could be very useful. Theme authors could have another option for an element where they can select another variant (if it exists). Authors won't be forced to use another typography field with unnecessary options and the users could place even their own CSS in new Additional CSS section, with different font weights for specific elements.

This multiple variants would be very useful in authors have an option to load a custom font. This way, users could upload a custom font besides the default theme options, they can choose different variants/weights and use them for specific elements with different weights in Custom/Additional CSS. 

This is just a suggestion if you don't mind.

I've read somewhere that you'll introduce "optgroups" for select fields. It would be useful even in typography field to separate standard fonts from google fonts. I've used your filters to add more standard fonts in typography field.

Also the transport postMessage for typography doesn't work for font family, variant and subsets. It works for the rest of typography options.

Best Regards,
Qodux

**Comment by Khoapq** [comment]
I have a plugin (add on for Kirki) allow load all or multiple variants.
Download: https://wordpress.org/plugins/customize-kirki-variants/  

Hope this plugin useful for you.
