### ISSUE TITLE
 Failing output kirki plugin

### ISSUE THREAD

**Issue by mohammadamin9627** [themeum/kirki#1066]
I'm having trouble output kirki plugin.
Example:

```
$fields[] = array(
        'type'        => 'slider',
        'setting'     => 'font_size',
        'label'       => __( 'Font-Size', 'text-domain' ),
        'description' => __( 'Please choose a font-size for your body.', 'text-domain' ),
        'section'     => 'typography',
        'default'     => 1,
        'priority'    => 20,
        'choices'     => array(
            'min'  => .7,
            'max'  => 2,
            'step' => .01
        ),
        output        => array(
            array(
                'element'  => 'body',
                'property' => 'font-size',
                'units'    => 'em',
            ),
```

The code is correct but does  not run.
Thanks for your help. :)

**Comment by aristath** [comment]
Hey there!

The code above is incomplete, can you please post the complete code you're using?
where is `$fields` located? How is it added? Using an action/filter?

Please post your full code.

**Comment by mohammadamin9627** [comment]
Hello my friend.

I'm created customize-loader.php file

## The code used in the customize-loader.php and Connected kirki.php file.

require_once get_template_directory() . '/core/customizer/kirki.php';

if (!function_exists('Dm_Theme_customizer_update_url')) {
    function Dm_Theme_customizer_update_url($config)
    {
        $config['url_path'] = get_stylesheet_directory_uri() .
'/core/customizer/';
        return $config;
    }
}
add_filter('kirki/config', 'Dm_Theme_customizer_update_url');
Kirki::add_config('Dm_Theme', array(
    'capability' => 'edit_theme_options',
    'option_type' => 'theme_mod',
));

## created panle

/\*  panle
*************************************************\* */
Kirki::add_panel('header_panle', array(
    'priority' => 10,
    'title' => __('header', 'David'),
    'description' => __('change header items', 'David'),
));

## created section

/\* section
*************************************************\* */

Kirki::add_section('header_section', array(
    'title' => __('header section'),
    'description' => __('header Controls change'),
    'panel' => 'header_panle',
    'priority' => 160,
    'capability' => 'edit_theme_options',
));

## created field

/\*  color
  *********************/
Kirki::add_field('David', array(
    'type' => 'color',
    'settings' => 'color_change',
    'label' => __('color change', 'David'),
    'section' => 'header_section',
    'default' => 'rgba(30,30,30,0.5)',
    'priority' => 10,
    'alpha' => true,
    'output'      => array(
        array(
            'element'  => ' h1, h2, h3, h4, h5, h6',
            'property' => 'color',
        ),
    ),

## ));

The code will not run!!

Thank you for helping me!😃

**Comment by aristath** [comment]
In the `Kirki::add_config()` method you're defining a config-id `Dm_Theme`.
Please change that to `dm_theme` (lowercase)

Then in `Kirki::add_field()` you're using `David` as the config-id, and you have not defined that anywhere.
Please change that to 'dm_theme`(lowercase, mathing the ID you've defined in the`Kirki::add_config()` call).
