### ISSUE TITLE
Tooltip in image field doesn't work

### ISSUE THREAD

**Issue by tutv** [themeum/kirki#1067]
### Issue description:

Tooltip in image field doesn't work
### Version used:

develop branch latest.
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'my_config', array(
        'type'        => 'image',
        'settings'    => 'image_demo',
        'label'       => __( 'This is the label', 'my_textdomain' ),
        'description' => __( 'This is the control description', 'my_textdomain' ),
        'help'        => __( 'This is some extra help text.', 'my_textdomain' ),
        'tooltip'  => 'Example',
        'section'     => 'my_section',
        'default'     => '',
        'priority'    => 10,
    ) );
```

**Comment by pagelab** [comment]
I confirm this.

**Comment by aristath** [comment]
Marking as a bug, I'll try to fix this one before the next release.

**Comment by joakimaglo** [comment]
Still doesn't work. Tried with 'tooltip' as well. Any plans to fix this? :)

**Comment by aristath** [comment]
This has been fixed in the develop branch, fix will be included in the next release.

**Comment by joakimaglo** [comment]
Great, thanks! 👍  Any ETA on that release?

**Comment by aristath** [comment]
No, no ETA yet... This next release is a rewrite of a lot of things so the most important thing right now is testing and reporting bugs. 
If you can do some tests on your localhost with the develop branch and report any issues you find that would really help me to get it released sooner! 👍
