### ISSUE TITLE
Adding link to href using transport postMessage and js_vars

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1069]
### Issue description:

I have read https://kirki.org/docs/arguments/js_vars.html but if i want to add a link to a href using 'transport' => 'postMessage', and 'js_vars' . How is it possible?
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
latest from w.org plugins
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

`my_option::add_field( 'my_config', array(
    'type'          => 'text',
    'settings'      => 'my_social_profile_link_facebook',
    'label'         => esc_attr__( 'Facebook Link', 'text-domain' ),
    'section'       => 'social_options',
    'default'       => 'http://facebook.com',
    'priority'      => 10,
    'transport' => 'postMessage',
    'js_vars'   => array(
        //i want to do something like this
        array(
            'element'  => 'a.myclss href',
            'function' => 'link',
        ),
    )
) );`

**Comment by aristath** [comment]
You can use the `attr` argument.
See https://github.com/aristath/kirki/issues/957#issuecomment-216273605 for an example.
