### ISSUE TITLE
Packagist not updated

### ISSUE THREAD

**Issue by vpratfr** [themeum/kirki#107]
Packagist.org does not seem to get notified when you make your commits. Thus composer does not update the code to the latest commit. 

You must setup the webhook in this github repository as explained on packagist: 

> GitHub Service Hook
> 
> Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub. To do so you can go to your GitHub repository, click the "Settings" button, then "Webhooks & Services". Add a "Packagist" service, and configure it with your API token (see above), plus your Packagist username. Check the "Active" box and submit the form. You can then hit the "Test Service" button to trigger it and check if Packagist removes the warning about the package not being auto-updated.

**Comment by aristath** [comment]
Done.

Sorry, I don't use packagist so I didn't know the details.
It's now been taken care of. :+1:
