### ISSUE TITLE
Greater than symbols

### ISSUE THREAD

**Issue by thehung2224** [themeum/kirki#1071]
### Issue description:

I can't use > to customize my own CSS.

Works:
@media (max-width: 1300px){
# site-navigation .menu li a {

padding: 42px 6px 42px 6px !important;
font-size: 11px !important;
}
}

Doesn't works:
@media (max-width: 1300px){
# site-navigation .menu > li > a {

padding: 42px 6px 42px 6px !important;
font-size: 11px !important;
}
}
### Version used:

1.0.2
### Code to reproduce the issue (config + field(s))

Kirki::add_section( 'custom_css', array(
    'title'       => esc_html__( 'Custom CSS', 'tm-polygon' ),
    'description' => esc_html__( 'In this section you can control custom css', 'tm-polygon' ),
    'panel'       => 'custom',
    'priority'    => $priority ++
) );

**Comment by aristath** [comment]
Please update to the latest version of the plugin.
This was fixed a long time ago.
