### ISSUE TITLE
Not set Theme for type Code

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1073]
Hi,
I tried here: https://kirki.org/docs/controls/code.html
and i have field:
`type = 'code'`
and
`
'choices'     => array(
    'language' => 'css',
    'theme'    => 'material',
    'height'   => 250,
),
`
but the editor until is `monokai` theme.
What wrong?

**Comment by ghost** [comment]
Can you help me @aristath ??

**Comment by aristath** [comment]
@ttn10 A lot of people were complaining that Kirki has been growing is size (and that makes it sometimes difficult to use in a theme when you want to embed Kirki in it), so we removed most themes for CodeMirror, and now only have 2: 
`kirki-dark` and `kirki-light`.

Try using one of those 2 and let me know if that works for you!
If you want to improve these 2 themes, please feel free to submit a PR. 👍
