### ISSUE TITLE
White (#ffffff) color on .accordion-section-title:hover

### ISSUE THREAD

**Issue by MikeiLL** [themeum/kirki#1075]
### Issue description:

I'm using the latest (awesome) develop branch. Having trouble tracking down (and changing) the white color when hovering over the accordion section titles. When the plugin is activated, in the customizer, `.accordion-section-title:hover` is WHITE, set in wordpress native customizer.php:

```
#customize-controls .control-section .accordion-section-title:focus, #customize-controls .control-section .accordion-section-title:hover, #customize-controls .control-section.open .accordion-section-title, #customize-controls .control-section:hover > .accordion-section-title {
    color: #ffffff;
}
```

I can't seem to override it, either: `color: #999 !important;`
### Version used:

Just cloned it from the repo.
### Using theme_mods or options?

I think I'm using `theme_mods`.

**Comment by aristath** [comment]
Can you please share your config?
I'm assuming you're using custom colors...
