### ISSUE TITLE
Default Fields

### ISSUE THREAD

**Issue by Tascam424** [themeum/kirki#1083]
Firstly may i say thank you for this great plugin. I'm really very new to theme development and Kirki has made things so much simpler.

I'm having a little issue and i hope this is the correct place to ask.

I'm trying to show a list of social network links. Below is an example of my Kirki options

``` php
Kirki::add_field( 'vision_config', array(
    'type'     => 'text',
    'settings' => 'facebook_icon',
    'label'    => __( 'Facebook', 'vision-multipurpose-theme' ),
    'section'  => 'social_icons',
    'default'  => __( 'https://www.facebook.com/themecanvas', 'vision-multipurpose-theme' ),
    'priority' => 10,
) );
```

and my code in my template

``` php
<?php $facebook_icon = get_theme_mod('facebook_icon');  ?>
<div class="col-md-6 header-social">
    <div class="list-group list-group-horizontal pull-right">
        <?php if (!empty($facebook_icon) ) : ?>
            <a class="social-profile" href="<?php echo get_theme_mod( 'facebook_icon','https://www.facebook.com/themecanvas'); ?>" title="Follow us on facebook"><i class="social_icon fa fa-facebook"></i></a>
        <?php endif; ?>
    </div>
</div>
```

So my fields within the customiser are propagated with my defaults but the php in my template still detects it as empty until i edit it and save. From what i have read, this is actually the correct behaviour, but i'm wondering if there is a correct work around for this scenario. I've used similar code in different areas, where i haven't used php to detect if the field is empty and my inline default value has been used correctly, so i'm guessing it comes down to that php.

Apologies if this is the wrong place and i thank you for any help you may be able to offer.

**Comment by aristath** [comment]
Please check the documentation for the `get_theme_mod` function in wordpress.org: https://codex.wordpress.org/Function_Reference/get_theme_mod
You should define the `default` value if you want to retrieve it.
Check explanation on https://github.com/aristath/kirki/issues/1088#issuecomment-242259545 for more details (different issue, same cause).
