### ISSUE TITLE
Color reset if default not set

### ISSUE THREAD

**Issue by macrodreams** [themeum/kirki#1084]
### Issue description:

In the color control doesn't have default value set. if we change the color in customizer we couldn't reset the color using 'clear' button. the color remains same.
### Version used:

2.3.5
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'my_config', array(
    'type'        => 'color',
    'settings'    => 'my_setting',
    'label'       => __( 'This is the label', 'my_textdomain' ),
    'section'     => 'my_section',
    'default'     => '',
    'priority'    => 10,
    'alpha'       => true,
) );

**Comment by aristath** [comment]
You should always use a default value.

**Comment by macrodreams** [comment]
Thanks for clarification.
