### ISSUE TITLE
Editor not working

### ISSUE THREAD

**Issue by umairrazzaq** [themeum/kirki#1085]
### Issue description:

Hi, the editor isn't working, instead blue button is appearing which don't have any value/label. I believe it will be "Open Editor". but this blank buttons isn't working either. I've uploaded reference image as well.
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
No I've plugin installed of this, and its added by TGMPluginActivation.
### Using theme_mods or options?

theme_mods
![kirki-editor](https://cloud.githubusercontent.com/assets/5692632/17853037/cf2441c4-6883-11e6-9f3f-8a5247307a21.png)

**Comment by aristath** [comment]
Please post the code you're using, I'm unable to replicate this one and nobody else has reported this on the latest version, which makes me think there's something unique with your configuration that's causing this.

**Comment by umairrazzaq** [comment]
hello Aristath, thanks for the reply. Please check attached screenshot as code reference. Also here is the piece of code for About Section.

**Code:**
`cleanresume_Kirki::add_field( 'about_section_content', array(
      'type'        => 'editor',
      'setting'     => 'about_section_content',
      'label'       => __( 'About Section Content', 'cleanresume-lite' ),
      'section'     => 'about_content_section',
      'priority'    => 30,
) );`

**Attachment:**
![kirki-editor-screenshot](https://cloud.githubusercontent.com/assets/5692632/18004663/b9085208-6bae-11e6-97a7-449cc38825d7.jpg)

**Note:**
I'm only using 1 editor in whole customizer.

**Comment by aristath** [comment]
can you also post your config?

**Comment by umairrazzaq** [comment]
Hi, thanks for the reply. I'm sorry are you referring to wp-config.php ?

**Comment by aristath** [comment]
No, I mean your `Kirki::add_config()` 👍

**Comment by umairrazzaq** [comment]
Hi, please check attached screenshot for Kirki Config

![kirki-config-screenshot](https://cloud.githubusercontent.com/assets/5692632/18052771/afd7ad8c-6e15-11e6-99f9-5e4c412440c1.jpg)

**Comment by umairrazzaq** [comment]
Hi, any update regarding my issue. Its still not resolved yet. Although Its working in localhost but not on live server.

**Comment by aristath** [comment]
In your `Kirki::add_config()` function you're defining that the ID of your configuration is `cleanresume`.
However, when adding your fields you're using `about_section_content`.

These need to be the same as per the docs on https://aristath.github.io/kirki/docs/getting-started/fields.html#breakdown-of-a-field-creation-call

**Comment by umairrazzaq** [comment]
Well it still not work either with 'cleanresume' or 'wysiwyg'.
Although I've another 3 field types for 'code' which are working both on localhost & live linux server

**Comment by aristath** [comment]
I'm afraid I won't be able to help unless I see your entire code.
Can you please send me your theme via email so that I may test this on my localhost?

**Comment by umairrazzaq** [comment]
Thanks for the reply and helping me out on this issue.
I can send you my website login information so you can check there. Its working fine on localhost but not on live.

**Comment by thatvideowebguy** [comment]
Hi, Any news on this one ?
I still can't add a full working editor field 
#1159  
#968 
thanks

**Comment by rinkuyadav999** [comment]
https://github.com/aristath/kirki/issues/1046

**Comment by rinkuyadav999** [comment]
https://github.com/aristath/kirki/pull/1246

**Comment by ondasStevo** [comment]
Hello, 
I had this problem too.
![image](https://cloud.githubusercontent.com/assets/13402079/25237523/30c7fb3a-25eb-11e7-8e6e-435fc6be9e1f.png)
Which version of Kirki are you using? I was working on version '2.4.0-beta.2'. I tried version '2.3.7' (last stable version) and editor works fine.

**Comment by umairrazzaq** [comment]
Hi, i already got this resolved by adding theme slug on each field, especially with Editor field.
Thanks for the comment, though :)
