### ISSUE TITLE
question on repeater

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#1086]
I've made a repeater front-page do display latest categories posts like latest sport posts or news posts and i would like to add more load button but the problem is that it does load the post that have already been display.
I've obliviously offset and page problem 
How do you get back these values in the repeater ?
like this ?
$offset = (isset($_POST['offset'])) ? $_POST['offset'] : 0;
$page = (isset($_POST['pageNumber'])) ? $_POST['pageNumber'] : 0;

**Comment by aristath** [comment]
I don't understand what the repeater has anything to do with your load-more implementation...
