### ISSUE TITLE
Repeater default values array is empty when called on front end

### ISSUE THREAD

**Issue by lunule** [themeum/kirki#1088]
Hi Aristeides,

I have an issue with getting the Repeater default values on the front end ( in header.php ).

The code in the Kirki config file:

```
Drnf_kirki::add_field( 'drnf', array(
    'type'        => 'repeater',
    'option_type' => 'theme_mod',
    'label'       => esc_attr__( 'Accounts', 'drnf' ),
    'section'     => 'drnf_section_sticky_social',
    'priority'    => 10,
    'settings'    => 'drnf_setting_sticky_social',
    'row_label'   => array(
        'type'      => 'text',
        'value'     => 'account',
        //'field'     => 'a-field-id'
            //only used if type = field, the field-id must exist in fields and be a text field
    ),
    'default'     => array(
        array(
            'link_text' => esc_attr__( 'Facebook', 'drnf' ),
            'link_url'  => 'https://www.facebook.com/drnicolafallon/?fref=ts',
        ),
        array(
            'link_text' => esc_attr__( 'Instagram', 'drnf' ),
            'link_url'  => 'https://www.instagram.com/drnicolafallon/',
        ),
        array(
            'link_text' => esc_attr__( 'LinkedIn', 'drnf' ),
            'link_url'  => 'https://au.linkedin.com/in/nicola-fallon-6b275330',
        ),
    ),
    'fields' => array(
        'link_text' => array(
            'type'        => 'text',
            'label'       => esc_attr__( 'Social Network Name', 'drnf' ),
            //'description' => esc_attr__( '', 'drnf' ),
            'default'     => '',
        ),
        'link_url' => array(
            'type'        => 'text',
            'label'       => esc_attr__( 'Account URL', 'drnf' ),
            //'description' => esc_attr__( '', 'drnf' ),
            'default'     => '',
        ),
    )
) );
```

The below attempt results in an empty array on the front end, but shows the default values in the customizer preview pane ( btw this problem occurs only with the default values, once some of the fileds is/are updated and saved on the customizer side, things on the front end start working fine ) : 
`$dummy = get_theme_mod( 'drnf_setting_sticky_social', array() );`

And the below one works with default values too, however the 'option_type' is set to 'theme_mod' in the Kirki config file:
`$accounts = Drnf_kirki::get_option( 'drnf', 'drnf_setting_sticky_social' );`

So, as I imagine, `$dummy = get_theme_mod( 'drnf_setting_sticky_social', array() );` should work also with default values, but it doesn't. Did I miss something? Is there something I need to change or add to the `get_theme_mod()` call?

Thanks in advance for your help.

.........................................................................................................................................................................
### Version used:

2.3.5
### Using theme_mods or options?

theme_mods

**Comment by aristath** [comment]
theme_mods are only stored when their value changes.
If you take a look at the documentation on https://codex.wordpress.org/Function_Reference/get_theme_mod you'll see that the function has 2 parameters: 

``` php
<?php get_theme_mod( $name, $default ); ?>
```

The `default` value you use in Kirki is simply the value that will be used in the Customizer UI.
However, if the user doesn't change that value, nothing will be stored in the database.
Therefore, the value used in the `$default` parameter of the function will be used instead.
Kirki simply extends the WP Customizer, and the Customizer so the values defined as defaults are not saved.

All you have to do is enter the same default value you used in Kirki in your get_theme_mod call. 👍

**Comment by lunule** [comment]
Hi Aristeides,

Thanks for your quick answer.

As you write, "_All you have to do is enter the same default value you used in Kirki in your get_theme_mod call._"
This is exactly what I don't get: how to add the defaults as a parameter in 

`get_theme_mod( 'drnf_setting_sticky_social', array() );` - instead of `array()` which doesn't work.

I mean, it's easy to add the default value as second parameter when the field has a single default value, such as in case of field type 'text'. Here I add a specific string as default value, the same thing I define in the setting declaration in the Kirki config file.
E.g. 
**IN THE CONFIG FILE:**

```
Kirki::add_field( 'my_config', array(
    'type'     => 'text',
    'settings' => 'my_setting',
    'label'    => __( 'Text Control', 'my_textdomain' ),
    'section'  => 'my_section',
    'default'  => esc_attr__( 'This is a default value', 'my_textdomain' ),
    'priority' => 10,
) );
```

**ON THE FRONT END:**
`get_theme_mod( 'my_setting', esc_attr__( 'This is a default value', 'my_textdomain' ) );`

But in case of 'repeater' the default value is an array of arrays of values - there doesn't seem to be a way to add the specific array content as second parameter to get the default values on the front end - using simply `array()` doesn't work.

Is there a way to get the default array content on the front end, or in case of repeaters only values saved in the database can be retrieved with get_theme_mod()?

Thanks again for taking a look at this.

**Comment by aristath** [comment]
``` php
$default = array(
    array(
        'link_text' => esc_attr__( 'Facebook', 'drnf' ),
        'link_url'  => 'https://www.facebook.com/drnicolafallon/?fref=ts',
    ),
    array(
        'link_text' => esc_attr__( 'Instagram', 'drnf' ),
        'link_url'  => 'https://www.instagram.com/drnicolafallon/',
    ),
    array(
        'link_text' => esc_attr__( 'LinkedIn', 'drnf' ),
        'link_url'  => 'https://au.linkedin.com/in/nicola-fallon-6b275330',
    ),
);
$value = get_theme_mod( 'drnf_setting_sticky_social', $default );
```

**Comment by aristath** [comment]
Or

``` php
$value = get_theme_mod( 'drnf_setting_sticky_social', array(
    array(
        'link_text' => esc_attr__( 'Facebook', 'drnf' ),
        'link_url'  => 'https://www.facebook.com/drnicolafallon/?fref=ts',
    ),
    array(
        'link_text' => esc_attr__( 'Instagram', 'drnf' ),
        'link_url'  => 'https://www.instagram.com/drnicolafallon/',
    ),
    array(
        'link_text' => esc_attr__( 'LinkedIn', 'drnf' ),
        'link_url'  => 'https://au.linkedin.com/in/nicola-fallon-6b275330',
    ),
) );
```

it's the same thing...

**Comment by lunule** [comment]
Gosh! I get it now.

## **You're the man!**

GREAT THANKS!!!
