### ISSUE TITLE
"container_inclusive" is disregarded on the selective refresh class

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#1089]
Hi Ari,

The "container_inclusive" argument is very important when you add a partial refresh. What you did in: https://github.com/aristath/kirki/blob/72ea3dc343706f02fc49702a9e90956c23c6c259/includes/class-kirki-selective-refresh.php#L49 makes it impossible to pass the "container_inclusive" argument to the native WordPress Selective Refresh API.

Can you take a look at it?

**Comment by aristath** [comment]
You're absolutely right...
Marking as a bug, I'll take a look.

**Comment by aristath** [comment]
I think this last commit in the develop branch fixes the issue but didn't have any time to test, can you please verify that it works for you?

**Comment by daviedR** [comment]
Hi Ari, just tested and it works perfectly. Thanks!

**Comment by aristath** [comment]
👍 awesome, thanks for checking!
Will be included in the next release.
