### ISSUE TITLE
Clean up OOP design

### ISSUE THREAD

**Issue by vpratfr** [themeum/kirki#109]
To make it compliant with PSR 4 / PSR 0 and to avoid running filters more than necessary (ex. filter kirki/config is ran every time you call Kirki_Config::getConfig())

I have some ideas about this but this could lead to some heavy changes in file structure. This would be for the best though and would be nice to do before improving on number of controls & co.

**Comment by aristath** [comment]
Yeah, I wanted to improve the structure too...
This is just something that I still haven't figured out how to properly do.
One idea was to create a main Kirki object. All other classes would then extend the main Kirki class, and settings and controls would be variables inside the class that would be easy to call from child classes.
Ideally it would not use any static methods.
However I tried that a few days ago and the issue I had was that I could not get the `kirki_get_option` function to work. No idea why... so after 10 hours I just got frustrated and nuked the whole thing.

I'm still a bit fuzzy on what would be best...
The current implementation is just clean and works.

If you have some ideas I'd be more than happy to discuss this or even merge a PR!

**Comment by padalec** [comment]
Why not use namspace? Look what I do https://github.com/padalec/kirki/tree/namspace/SilverWp

**Comment by vpratfr** [comment]
@padalec it is what is being done slowly (see branch develop and feature/class-naming)

**Comment by vpratfr** [comment]
@padalec By the way, feel free to use the develop branch so that you can test the latest features. If you have any PR, make sure to base them on the develop branch and not on the master branch.

**Comment by aristath** [comment]
Closing this one, we have a PR in place on #115 
Any comments should go there. :+1:
