### ISSUE TITLE
Outdated Google Fonts List

### ISSUE THREAD

**Issue by getbowtied** [themeum/kirki#1091]
Hi,

please update the list of Google Webfonts. There are only 733 fonts on Kirki. (808 on https://fonts.google.com/)

Thank you.

**Comment by aristath** [comment]
fonts updated, will be included in the next release.

**Comment by getbowtied** [comment]
Thank you!

**Comment by ariona** [comment]
@aristath Is there any tutorial to update Google Fonts List manually? some new fonts are not listed here.

**Comment by aristath** [comment]
No tutorial. Running grunt in the master branch updates the fonts, that's all that's needed.
