### ISSUE TITLE
Question about section and users roles

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#1099]
Not an issue but just a question. 
Is it possible to makes some panel or section appears according to users capacities with kirki ?
For example an editor could see some section that an author can't see .
Thanks

**Comment by iliman** [comment]
I'm not sure about panels, but sections and fields should support the `capability` argument.
You can read about that [here](https://aristath.github.io/kirki/docs/arguments/capability.html).

**Comment by robbisy** [comment]
Thanks @iliman
