### ISSUE TITLE
Exclude output not working for spacing field

### ISSUE THREAD

**Issue by joelcaramelo** [themeum/kirki#1100]
### Issue description:

Excluding specific output for a spacing field seems to be ignored, or am I missing something in my code? The exclude parameter isn't documented for fields with multiple values like the spacing field. Happy to know if and, when it's possible, how I can make the exclude work properly.

P.S. thanks for creating Kirki and maintaining it!
### Version used:

2.3.6
### Using theme_mods or options?

/
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_config( 'theme_123', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
) );

Kirki::add_field( theme_123', array(
      'type'      => 'spacing',
      'settings'  => 'button_margin',
      'section'   => 'general_button',
      'label'     => __( 'Margin', 'theme_123' ),
      'default'   => array(
          'top'    => '0',
          'right'  => '0',
          'bottom' => '0',
          'left'   => '0',
      ),
      'output'    => array(
          array(
              'element'  => '.some-element',
              'property' => 'margin',
              'exclude'  => array(
                  array(
                      'top'         => '0',
                      'right'       => '0',
                      'bottom'  => '0',
                      'left'        => '0',
                  ),
              ),
          ),
      ),
      'transport' => 'auto',
  ) );
```

**Comment by joelcaramelo** [comment]
@aristath Any news or tips on this issue?

**Comment by aristath** [comment]
This was because the value and the exclude were not identical.

I var_dump'd both and this this is the result:

```
array (size=4)
  'top' => string '0' (length=1)
  'right' => string '0' (length=1)
  'bottom' => string '0' (length=1)
  'left' => string '0' (length=1)
array (size=4)
  'top' => string '0' (length=1)
  'bottom' => string '0' (length=1)
  'left' => string '0' (length=1)
  'right' => string '0' (length=1)
```

They may look identical, but the fact that they have their items in a different order makes them different.

I added an extra check for this in version 3.0 (develop branch) so this will work fine in the next release, regardless of the order of those items.
