### ISSUE TITLE
Reset Section Button not working

### ISSUE THREAD

**Issue by macrodreams** [themeum/kirki#1106]
### Issue description:

Reset Section Button not working
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
### Using theme_mods or options?

theme_mods

**Comment by aristath** [comment]
A simple "doesn't work" is not that useful... It seems to be working fine for me!
Which version of the plugin are you using?
Are you using the latest version of WordPress Core?
Are you creating the section via Kirki, or via the Customizer API?
What kind of controls do you have in that section?
Did you try resetting other sections that contain different types of controls?
Do you have default values defined in the controls that are in that section?

When asking for support please provide as much info as possible so that we may understand what the actual issue is.
If we don't have enough info we're simply forced to ask more questions and this can only cause delays in getting the issue (if an issue actually exists) resolved.

**Comment by macrodreams** [comment]
Which version of the plugin are you using?
2.3.6
Are you using the latest version of WordPress Core?
Yes
Are you creating the section via Kirki, or via the Customizer API?
Kirki
What kind of controls do you have in that section?
Color
Did you try resetting other sections that contain different types of controls?
Yes
Do you have default values defined in the controls that are in that section?
Yes

**Comment by SH3ARK** [comment]
Yes reset button is not working on the latest version...

It's something with the tooltip field argument.

With this code you can reset because tooltip is set

```
    Kirki::add_config( 'kirki-demo', array(
        'option_type' => 'theme_mod',
        'capability'  => 'edit_theme_options',
    ));

    Kirki::add_section( 'checkbox', array(
        'title'          => esc_attr__( 'Checkbox Controls', 'kirki-demo' ),
        'capability'     => 'edit_theme_options',
    ) );

    Kirki::add_field( 'kirki_demo', array(
        'type'        => 'toggle',
        'settings'    => 'toggle_demo',
        'tooltip'        => esc_attr__( 'test 1234', 'kirki-demo' ),
        'section'     => 'checkbox',
        'default'     => true,
    ) );
```

but without a tooltip you can't reset the section.

```
    Kirki::add_config( 'kirki-demo', array(
        'option_type' => 'theme_mod',
        'capability'  => 'edit_theme_options',
    ));

    Kirki::add_section( 'checkbox', array(
        'title'          => esc_attr__( 'Checkbox Controls', 'kirki-demo' ),
        'capability'     => 'edit_theme_options',
    ) );

    Kirki::add_field( 'kirki_demo', array(
        'type'        => 'toggle',
        'settings'    => 'toggle_demo',
        'section'     => 'checkbox',
        'default'     => true,
    ) );
```

Try it out.

**Comment by macrodreams** [comment]
Yes @SH3ARK  it is working if tooltip is set in atleast one of the field in the section. But it is not working for multicolor field even if tooltip is set, it is showing [object][object] in field value. if I click reset button.

**Comment by kmob2** [comment]
I can confirm that this is indeed broken. Just like SH3ARK mentioned, without using tooltip, the reset button doesn't work.

**Comment by rainb3rry** [comment]
This issue is still active in the spacing control, I am using the reset button, I getting [object][object] output.

Thanks for your helps.

**Comment by aristath** [comment]
@traderxc is that on the 2.3.7 version, or the development branch from this repository?
If you haven't tested the development version from here can you please give that a try and let me know if this still happens for you there?

**Comment by rainb3rry** [comment]
I use by integrating kirki plugin (https://tr.wordpress.org/plugins/kirki/) downloaded files.

**Comment by aristath** [comment]
Can you please try using the development version? https://github.com/aristath/kirki/archive/develop.zip

**Comment by traderxc** [comment]
How can i embed it, is there any documentation on this ?

**Comment by sethstha** [comment]
Also if default value of multicolor is capitalized for e.g. ` #FFFFFF `, resetting will change default value to `[object Object]` along with button name `object`

![image](https://cloud.githubusercontent.com/assets/2367137/23603502/a0d861ee-027d-11e7-8ece-2dcbe0df1f68.png)

**Comment by rainb3rry** [comment]
@sethstha Kirki Project is very nice but this issue is present in some setting fields.

**Comment by sethstha** [comment]
@traderxc You said it very well, we all love kirki. I think we need more contributors. 
Is this fixed in development branch?
