### ISSUE TITLE
Disable output of kirki-styles.css

### ISSUE THREAD

**Issue by muracevic** [themeum/kirki#1109]
I tried every solution that can be found here, or around the web. No success...

Using latest develop with theme mods.
### Kirki Config

`Kirki::add_config( 'bo', array(
    'option_type' => 'theme_mod',
    'capability'    => 'edit_theme_options',
        'option_name'   => 'bo',
    'disable_output' => true,
) );`
### If plugin isn't used, loading kirki from within theme

`if( ! class_exists('Kirki') ) {
    include_once( dirname( __FILE__ ) . '/inc/adm/kirki/kirki.php' );
}
require_once('options-config.php');`

**Comment by aristath** [comment]
can't replicate any longer in the 3.0-dev so closing this one.
