### ISSUE TITLE
theme_mod not working on some scenario. 

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1112]
### Issue description:

theme_mod is not working when placed in add_config see the code below
### Version used:

Version : 2.3.6
### Using theme_mods or options?

Both
### Code to reproduce the issue (config + field(s))

<pre>
// Start Not working 

All code save under 'mrc' key, on theme_mod nothing is saved

Kirki::add_config( 'wpcb_my_config', array(
        'capability'    => 'edit_theme_options',
        'option_type'   => 'option',
        'option_name'   => 'mrc',
    ) );

Kirki::add_field( 'wpcb_my_config', array(
        'type'          => 'text',
        'settings'      => 'banner_heading',
        'label'         => __( 'Banner Heading', 'HN' ),
        'section'       => 'banner_section',
    ) );

Kirki::add_field( 'wpcb_my_config', array(
        'type'          => 'text',
        'settings'      => 'banner_heading2',
        'label'         => __( 'Banner Heading', 'HN' ),
        'section'       => 'banner_section',
        'option_type' => 'theme_mod',
    ) );
// End Not working 

// Start working

Kirki::add_config( 'wpcb_my_config', array(
        'capability'    => 'edit_theme_options',
        'option_type'   => 'option',
    ) );

Kirki::add_field( 'wpcb_my_config', array(
        'type'          => 'text',
        'settings'      => 'banner_heading',
        'label'         => __( 'Banner Heading', 'HN' ),
        'section'       => 'banner_section',
        'option_type'   => 'option',
        'option_name' => 'mrc'
    ) );

Kirki::add_field( 'wpcb_my_config', array(
        'type'          => 'text',
        'settings'      => 'banner_heading2',
        'label'         => __( 'Banner Heading', 'HN' ),
        'section'       => 'banner_section',
        'option_type' => 'theme_mod',
    ) );

// End working  

Quick reply will be very helpful. Thanks
</pre>

**Comment by aristath** [comment]
Do you change the values of those controls?
Only changed controls get saved.

**Comment by ravishakya** [comment]
Yes i did changed the values. Is this a bug ??

**Comment by aristath** [comment]
Wait a minute 'cause I think I may have misunderstood initially what you're saying.

So... If your config uses options and you have option_name defined, then you can't override the data-type in a specific control and make it use theme_mods, but if the option_name is not defined in the global config then you can override the data-type on specific fields and make them use theme_mods?

In other words the data is saved, but the per-field override to theme_mods doesn't work when the global config has option_name defined?

**Comment by ravishakya** [comment]
1. So... If your config uses options and you have option_name defined, then you can't override the data-type in a specific control and make it use theme_mods, but if the option_name is not defined in the global config then you can override the data-type on specific fields and make them use theme_mods? In other words the data is saved, but the per-field override to theme_mods doesn't work when the global config has option_name defined?

=> Yes, Exactly

**Comment by aristath** [comment]
Please try using the version from the development branch on this repository.
I believe this one was just fixed.

Please confirm so that I may include this fix in the next version of the plugin... 👍

**Comment by ravishakya** [comment]
It worked :+1:
