### ISSUE TITLE
Panel description "display:none" problem

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1115]
### Issue description:

Panel description is hidden.
### Using theme_mods or options?

Both

![Image description](https://s14.postimg.org/6lgv108g1/Untitled_1.jpg)

**Comment by aristath** [comment]
Marked as a bug, will get this one fixed in the next release 'cause I'll have to refactor panels & sections anyway to accomodate some changes in the next version of Core WP.

**Comment by aristath** [comment]
Not a bug.
Descriptions in the customizer show if you click the ( ? ) icon.
This comes from WP-Core.
