### ISSUE TITLE
Trigger slider value update on move, rather than on mouseup?

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#1119]
### Issue description:

I noticed that when using the slider, the value is not actually being passed on to the customizer, unless the mouse button is being let go (mouseup).

I'm adding some custom customizer functions like this:

```
wp.customize( 'my_slider_padding_top', function( value ) {
        value.bind( function( newval ) {
            $('.site-inner').css('padding-top', newval + 'px' );
        } );
    } );    
```

Please note, that is just an example code that demonstrates the same issue, my actual code involves dozens of custom functions. Adding css output using js_vars, has the same effect.

With the current way the slider behaves, the `wp.customize` function is only being trigger on mouseup, which is very user unfriendly, and kills the entire experience of a fluid slider option that updates the preview on slider movement.

I'm new to kirki and I haven't been able to find the file yet, that is responsible for this action.

Can anyone guide me to the right file?
### Version used:

Latest
### Using theme_mods or options?

Theme Mods

**Comment by kmob2** [comment]
Okay, I found a way that works, but it's probably not the cleanest solution.

https://github.com/aristath/kirki/blob/develop/assets/js/controls/slider.js#L31 
replace `'change'` with `'mousemove'`

**Comment by aristath** [comment]
Not sure about this yet, have to think it through.
It will probably have to be done conditionally...
So if transport uses `postMessage` we can use that, otherwise when using refresh it will have to be done on change.

Marked as a feature request and will be included in the next version.
