### ISSUE TITLE
Code 'default value' not setting to default after reset

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1122]
### Issue description:
1. When i put default value in 'type=>code'. It is not setting to default value after reset button is clicked. 
2. The choices for the code is not working eg. language, theme and height. As i can see the layout for the code has been changed in the newer version so the choices are depreciated ??

``` php
Kirki::add_field( 'my_config', array(
    'type'        => 'code',
    'choices'     => array(
        'language' => 'css',
        'theme'    => 'monokai',
        'height'   => 250,
    ),
) );
```

**Comment by aristath** [comment]
fixed in 3.0
