### ISSUE TITLE
Image field uploads other extensions also

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1123]
### Issue description:

When i upload or select file from 'type => image' it should only allow to select and upload image files but i can upload and select other extensions also. Should this be happening ??? If yes then why we need "type => image" and "type => upload".

**Comment by aristath** [comment]
Marked as a bug, will be fixed in the next release.

**Comment by aristath** [comment]
Not a bug.
Image controls use the WordPress-Core `WP_Customize_Image_Control` control and have no control over it (yet).
