### ISSUE TITLE
Font Icon in select field

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1124]
### Issue description:

Is there a way to put font icons in select field ?? I want to use font awesome on the customizer. I saw this post https://github.com/aristath/kirki/issues/548 which says you can use the select field for that. Thats gud but i want to show the icons also beside the texts. 

I found an example on here http://codepen.io/Angelfire/details/eynoC
But i have no idea how to customize the js on the select field. http://codepen.io/Angelfire/pen/eynoC.js ( see the bottom )

Any help ??

**Comment by aristath** [comment]
Not currently.
Adding this as a feature request...
There are considerations to switch to using select2 soon so the JS will probably change a bit. But We'll add it for sure 👍

**Comment by CodeCurosity** [comment]
Any ETA on this?

**Comment by aristath** [comment]
Fixed in 3.0.
It's pretty simple now... You just add your HTML inside the option and it shows what you want.

**Comment by aristath** [comment]
An example on how it can be done via JS can also be seen in the new fontawsome control.

**Comment by ravishakya** [comment]
can you show me an example ?? I have tried but couldn't use it

**Comment by ravishakya** [comment]
i am trying to add fontawesome in repeater.
