### ISSUE TITLE
Custom field reset issue when using input fields

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#1128]
### Issue description:

When using the custom field along with an input field (see code below), and then clicking on the Reset button in the panel, the input field will use it's entire default field as the value of the default input field.

![Custom Field with Input content](http://i.imgur.com/8GH8lwX.png)
### Version used:

Dev branch
### Using theme_mods or options?

 theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'my_theme', array(
    'type'        => 'custom',
    'settings'    => 'my_generator',
    'label'       => __( 'Generator', 'my_textdomain' ),
    'section'     => 'my_section',
    'default'     => '  <input type="submit" value="Submit">',
    'priority'    => 0,
) );
```

**Comment by aristath** [comment]
fixed in 3.0
