### ISSUE TITLE
Import and Export

### ISSUE THREAD

**Issue by vgnanendra** [themeum/kirki#1132]
### Issue description:

 Is there a way to backup the customizer options into a json file or to display json data anywhere in admin panel??
If not, are you planning to add this feature? 

Thanks for your time. Great work. :)

**Comment by rahulv3a** [comment]
There is already a plugin for that https://wordpress.org/plugins/customizer-export-import/

**Comment by vgnanendra** [comment]
Thanks Rahul. :)
