### ISSUE TITLE
Glitch on sortable field when using partial_refresh

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#1136]
Hi Ari,

I noticed a small glitch, not really an issue though. Let's say we have a sortable field and use `partial_refresh` on that field, when go to Customizer page, the partial element did refresh once just seconds after the preview iframe loaded.

Of course I haven't made any change to the option (sortable field), but why did the element refresh on the Customizer iframe load?

Does your plugin populate values to the sortable field via JS? If so, maybe that's the reason.

**Comment by aristath** [comment]
Moving to the 3.1 milestone.
It's weird, but doesn't cause any issues for now so not an immediate priority.

**Comment by DannyCooper** [comment]
Do you know if this was fixed @aristath? I'm struggling to replicate.

**Comment by aristath** [comment]
> Do you know if this was fixed @aristath? I'm struggling to replicate.

If I'm not mistaken this was fixed a long time ago when the field was refactored :+1:
