### ISSUE TITLE
New Control Type Not Working in Repeater!!!

### ISSUE THREAD

**Issue by developerzinan** [themeum/kirki#1142]
### Issue description:

I made a simple **new control** "social" like in the documentation [https://aristath.github.io/kirki/docs/advanced/register-control-types.html](https://aristath.github.io/kirki/docs/advanced/register-control-types.html) but its working normaly but **not in repeat filed type**.

Is it possible to give me solution ? If its a bug please update the plugin as soon as possible.

**Comment by aristath** [comment]
Hello there!

This is not a bug.
Repeater controls have to be defined explicitly in the repeater control itself.
We were planning to add filters to allow hooking in there and being able to add more controls but this is still to be implemented.
