### ISSUE TITLE
Editor - link button -not working

### ISSUE THREAD

**Issue by stev0n** [themeum/kirki#1144]
### Issue description:

Hi
The visual editor opens as expected(see screenshot)  and there are no js error messages.
The bold, align etc buttons work ok.

However, my link button in the visual editor does not work correctly, it makes the selected word go blue and underlines it. but the url selection box does not appear.
If you then click on the text view button, there is no a tag around the word.
![screen shot 2016-10-18 at 16 47 03](https://cloud.githubusercontent.com/assets/14977052/19485315/b9dbf928-9552-11e6-90ce-42f2dd9b3bcb.png)

The visual editor works as expected in the wp cms if I were to edit a post.
So I assume that the tinymce files are installed correctly.

Also, how does one specify which buttons the visual editor should display ?

Your help is appreciated.

Steve
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.6
### Using theme_mods or options?

mods
### Code to reproduce the issue (config + field(s))

function kirki_customizer_config() {
         $args = array(
        // Only use this if you are bundling the plugin with your theme 
        'url_path'     => $_SESSION['CODE_BASE_URL']. 'cms/kirki/',
        'description'   => __( 'This is the theme description. You can edit it in the Kirki configuration and add whatever you want here.', 'gogosimplicity' ),
        'width'        => '31%'
       );
       return $args;
       }
add_filter( 'kirki/config', 'kirki_customizer_config' );

```
$fields[] = array(
    'type'      => 'editor',
    'settings'  => 'contactpage_content',
    'label'     => __( 'Contact Page Contents', 'gogosimplicity' ),
    'section'   => 'contact_section',
    // 'transport'  =>  'postMessage',
    'default'   => ''
);
```

**Comment by aristath** [comment]
Hello there @stev0n 
The editor field needs to be rebuilt, this is something I'll start working on soon.
No dates or ETAs.

**Comment by stev0n** [comment]
ah, ok.

cheers.

steve

**Comment by rinkuyadav999** [comment]
https://github.com/aristath/kirki/issues/1046

**Comment by rinkuyadav999** [comment]
https://github.com/aristath/kirki/pull/1246
