### ISSUE TITLE
Adding Kirki to a pre-written theme

### ISSUE THREAD

**Issue by Brian-Duggan** [themeum/kirki#1149]
### Issue description:

I'm working on a multi-site network in which users will be able to select from a variety of themes. The default theme (Ornea) uses embedded Kirki to create the left-offcanvas-menu. I'm still fairly new to web-development, but I'd like to know how to migrate that specific function (the offcanvas menu) across all the themes available to the users, so that no matter what theme they choose that offcanvas menu will be included in their page. Not sure if this is the place for this question, but I couldn't find any other support areas for Kirki

**Comment by aristath** [comment]
You'd have to extract the code from the theme and build it as a separate plugin which would then be network-activated in order to be available to all your themes...
