### ISSUE TITLE
Duplicate exact copy of theme style CSS if Kirki is not installed or activated.

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#1150]
### Issue description:

When Kirki is not installed or deactivated, a duplicate exact copy of my theme style is included again. It's driving me nuts. Please help. I've tried wp_deregister_style wp_enqueue_style at the same priority. Nothing is happening.
### Version used:

2.3.7
### Using theme_mods or options?

mods
### Code to reproduce the issue (config + field(s))

Duplicate CSS if Kirki is not installed.

**Comment by aristath** [comment]
Do you have your code on github perhaps so I may take a look? If not, could you please email me a copy of your theme so that I may investigate?
If I remember correctly you're using the Kirki Helpers classes, tight?

**Comment by carasmo** [comment]
Okay, I figured out what is happening: 

BEFORE:

```
/**
     * Enqueues the stylesheet
     */
    public function enqueue_styles() {
        // If Kirki exists there's no need to proceed any further
        if ( class_exists( 'Kirki' ) ) {
            return;
        }
        // Get our inline styles
        $styles = $this->get_styles();
        // If we have some styles to add, add them now.
        if ( ! empty( $styles ) ) {
            // enqueue the theme's style.css file
            $current_theme = ( wp_get_theme() );
            wp_enqueue_style( $current_theme->stylesheet . '_no-kirki', get_stylesheet_uri(), null, null );
            wp_add_inline_style( $current_theme->stylesheet . '_no-kirki', $styles );
        }
    }
```

**AFTER**

```
/**
     * Enqueues the stylesheet
     */
    public function enqueue_styles() {
        // If Kirki exists there's no need to proceed any further
        if ( class_exists( 'Kirki' ) ) {
            return;
        }
        // Get our inline styles
        $styles = $this->get_styles();
        // If we have some styles to add, add them now.
        if ( ! empty( $styles ) ) {
            // enqueue the theme's style.css file
            $current_theme = ( wp_get_theme() );
            //wp_enqueue_style( $current_theme->stylesheet . '_no-kirki', get_stylesheet_uri(), null, null );

            $color_switch = LocalPro_Kirki::get_option( 'localpro_theme', 'change_color_scheme_switch' );

            if ( $color_switch != '0' ) {
                wp_add_inline_style( $current_theme->stylesheet, $styles ); // dep main style sheet not the duplicate
            }

        }
    }
```

So If Kirki is not installed/active but there are inline styles, then these work, but without an exact duplicate of the main CSS again. Also, I needed to check that the user switched the switch to actually load the colors since it was loading the first preset event though the switch was off.

**Comment by carasmo** [comment]
It works smoothly now.
