### ISSUE TITLE
Kirki wants to save after hovering over sliders.

### ISSUE THREAD

**Issue by WebTrooper** [themeum/kirki#1152]
Sorry I didn't do extensive testing but just want to raise the issue, when hovering over some sliders, Kirki loads the Save & Publish button, and I get the warning prompt when I close Customizer. This does not happen with all the sliders I'm using, just some of them. This happens when I have not made any changes... just hovered over one of the sliders.

Kirki version 2.3.7

**Comment by aristath** [comment]
Can't replicate in the current develop branch, closing this one.
