### ISSUE TITLE
Transport auto doesn't seem to work on text field.

### ISSUE THREAD

**Issue by WordpressGurus** [themeum/kirki#1153]
Here is what i am using but i have to refresh the page for form id to be updated.

**$form1id = get_theme_mod( 'frm1_form_id', 'default_value' );**

Kirki::add_field( 'form_style', array(
	'settings' => 'form_id_1',
	'label'    => __( 'FORM ID', 'twentyfifteen' ),
	'section'  => 'form_settings_1',
	'type'     => 'text',
	'priority' => 1,
	'transport' => 'auto'	
) );

Kirki::add_field( 'gravity_designer', array(
	'type'        => 'typography',
	'settings'    => 'title_typography_1',
	'label'       => esc_attr__( 'Form Title', 'kirki' ),
	'section'     => 'form_typography_1',
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '1',
		'subsets'        => array( 'latin-ext' ),
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left'
	),
	'priority'    => 10,
	'output'      => array(
		array(
			'element' => 'body #wrapper_' **. $form1id .** " .form_heading .form_title",
			'suffix'   => ' !important',
		),
	),
	'transport' => 'auto'
) );

**Comment by aristath** [comment]
@WordpressGurus I don't understand... what would you like it to do exactly?
transport auto tries to determine if `postMessage` can be used, and if it can't then it falls back to `refresh`.
In your case since you don't have an output argument defined for the text field it's only natural that it falls-back to using refresh.
What is the issue here?

**Comment by WordpressGurus** [comment]
My bad, i totally forgot about the output argument, thanks for pointing it out 👍
