### ISSUE TITLE
wp-content/themes/letsblog/modules/kirki/assets/css/ 404/410 response

### ISSUE THREAD

**Issue by ankitblog** [themeum/kirki#1155]
Hi
I bought this theme "letsblog" which has the latest version but i am getting error from kirki when i run through website tests for example i ran the website through https://tools.pingdom.com/ and got attached error.
Do you know what's the fix?
Many thanks!

P.S i contacted the theme authors they said they are not gettting this error which is weird.
Br
Ankit

![snap](https://cloud.githubusercontent.com/assets/23334380/20095260/1311bff2-a5a5-11e6-895f-dec9f88a114e.PNG)

**Comment by aristath** [comment]
Hey there!

That's weird indeed...
Is this by any chance a Windows Server (IIS) instead of an Apache or Nginx server?

**Comment by ankitblog** [comment]
Hi aristath,
The error is resolved. It was due to the fact that i was using CSS and JS compressor and it also compressed kirki-style.css file. As soon as i put an exception for this CSS file. the error was gone 

Thank for your help anyways  :)

**Comment by aristath** [comment]
Great, thanks for letting me know!

I'll go ahead and close this ticket. 👍
