### ISSUE TITLE
PHP Fatal error:  Call to undefined method Kirki_Controls::control_clean()

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#116]
Im getting this error `PHP Fatal error:  Call to undefined method Kirki_Controls::control_clean()`, referring to line 32 of helpers.php

Any tips?

**Comment by aristath** [comment]
Hey there!

Can you please try the [develop](https://github.com/aristath/kirki/tree/develop) branch and let me know if you have any issues there?

**Comment by aristath** [comment]
Fixed in the develop branch
