### ISSUE TITLE
Static CSS

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#1161]
Hi Ari,

This is a feature suggestion. Is it possible to make all customizer generated CSS written in a static CSS file, instead of inline style block in the `<head>`?

This would improve website's performance. I have many generated styles, and right now it looks a bit excessive for inline styles. The idea is by creating a CSS file on `wp-content` directory (perhaps inside `kirki` subdirectory).

A possible issue is default values, means we should generate the CSS file even when user haven't saved anything on Customizer.

What do you think?

**Comment by aristath** [comment]
Try adding this:

``` php
if ( class_exists( 'Kirki_Styles_Frontend' ) ) {
    Kirki_Styles_Frontend::$ajax = true;
}
```

Please note that this method is not thoroughly tested so I don't know if it will work... Kirki development will continue again soon (took a break because I had to focus on my day job for a couple of months) so this is going to be implemented properly soon.

**Comment by daviedR** [comment]
Took a dig on your code, we can also use filter `kirki/config` hook and add `$config['inline_css'] = false`. It works. But I don't know if AJAX request like this is good for SEO.

No pressure. This is not a critical issue, just for further optimizations. Thanks for keeping this awesome plugin alive!

**Comment by aristath** [comment]
> But I don't know if AJAX request like this is good for SEO.

SEO-Wise it won't be an issue, and the benefit is that caching plugins can also cache this request. 👍 

It just needs some proper testing and a better method to enable it.
I don't want to use the `kirki/config` filter as that filter affects all plugins & themes that are using Kirki on a site (and your theme may not be the only thing using Kirki).
This will probably be added to `Kirki::add_config()` as an extra parameter, it just hasn't been implemented yet.

For the time being both `Kirki_Styles_Frontend::$ajax = true;` and the `kirki/config` methods are only there for testing purposes pending the final implementation

**Comment by daviedR** [comment]
Great to know that works wisely for SEO!

Yeah, that would be great if you can implement this config on the `Kirki::add_config()` as an parameter.

**Comment by CodeCurosity** [comment]
I have used this

 `if ( class_exists( 'Kirki_Styles_Frontend' ) ) {
    Kirki_Styles_Frontend::$ajax = true;
}
`

It is including the css file but it's empty and inline css is still there in the header.

how can we make it work and how can we change the css file name and location?

**Comment by daviedR** [comment]
Hi Usman,

I used this snippet:

```
function kirki_static_css( $config ) {
    $config['inline_css'] = false;

    return $config;
}
add_filter( 'kirki/config', 'kirki_static_css' );
```

**Comment by CodeCurosity** [comment]
Yes this works and shows the css in admin-ajax.php?action=kirki_dynamic_css but is it possible to organize the css so its not all stacked together and the css file name and location can be changed?

**Comment by daviedR** [comment]
@UsmanShahzad I don't think it's possible.

**Comment by aristath** [comment]
Version 3.0 now compiles all CSS to file.

Just add this:

```php
add_filter( 'kirki/dynamic_css/method', function() {
    return 'file';
});
```
Also, it combines google-fonts in there too, saving you an extra request so that's another bonus 😉. 
I've been testing it and so far it looks good, with fallback to inline styles in case writing to file fails so at some point this will become the default method if enough people test it and verify it works ok under different server configurations etc.

**Comment by CodeCurosity** [comment]
I am trying the latest development version and the function you mentioned above but in any case the styles are not being written in css file or inline styles, i can see styles working in customizer preview but it is not being saved.
