### ISSUE TITLE
Changing a value based on URL paramerer

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#1164]
Hi there, is it possible to change a value without saving it based on URL parameter? The purpose is showing users theme features.

For example, https://mysite.com/?layout=grid&sidebar=no

Is it possible to change those two values on run-time without saving them actually?

**Comment by aristath** [comment]
Assuming you're using theme_mods, you can create a php file in your mu-plugins folder and add something like this in it:

```php
foreach( $_GET as $theme_mod => $value ) {
	add_filter( 'theme_mod_' . $theme_mod, function() {
		return $value;
	});
}
```

But this has nothing to do with Kirki, this will simply change the value of the setting retrieved by WP and may have unwanted side-effects if your theme-mods are not uniquely named.

**Comment by minimaluminium** [comment]
For someone who needs it in the future, the code above should be like below to access `$value` in the anonymous function.

```php
foreach ( $_GET as $theme_mod => $value ) {
	add_filter( 'theme_mod_' . $theme_mod, function() use( &$value ) {
		return $value;
	});
}
```

Thanks @aristath
