### ISSUE TITLE
Select default value not working

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#1167]
### Issue description:
If I understood it right, `default` value of a field acts as a default value while in customizer mode.

```php
Kirki::add_field( 'my_theme', array(
	'type'        => 'select',
	'settings'    => 'my_setting',
	'section'     => 'my_section',
	'default'     => 'option-1',
	'multiple'    => 1,
	'choices'     => array(
		'option-1' => esc_html__( 'Option One', 'textdomain' ),
		'option-2' => esc_html__( 'Option Two', 'textdomain' ),
		'option-3' => esc_html__( 'Option Three', 'textdomain' ),
	),
) );
```

So `get_theme_mod( 'my_setting' )` should return `instagram` while in customizer mode, however, it returns `false`.

When I change it to `get_theme_mod( 'my_setting', 'instagram' )`, it returns `instagram` on both modes(customizer and non-customizer).

### Version used:
2.3.7

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Not a bug.
`get_theme_mod` requires the 2nd argument if you want to return the default value.
default values are not saved in the db in WordPress, only modified values are.

**Comment by minimaluminium** [comment]
@aristath I asked because it acts different on `text` field.

```php
Kirki::add_field( 'my_theme', array(
	'type'     => 'text',
	'settings' => 'my_setting',
	'section'  => 'my_section',
        'default'  => 'Default Value'
) );
```

Now `get_theme_mod( 'my_setting' )` returns `Default Value` on customizer mode and `false` on non-customizer mode.

**Comment by aristath** [comment]
Yes, that is default WordPress behaviour.
When in the customizer, default values are recognised because in the customizer the fields are instantiated.
When not in the customizer, the fields are not instantiated and WordPress only retrieves saved values from the database.
You should **always** add your default value on `get_theme_mod()`.
