### ISSUE TITLE
upgrate give me notice in customizer

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#1168]
### Issue description:
When I upgrate from 2.3.6 to 2.3.7 I get this notices on the customizer. I try with the develop branch it gives me the same result 
Notice: Undefined index: link_text in wordpress/wp-content/themes/sagemaster/kirki/includes/field/class-kirki-field-repeater.php on line 79

Notice: Undefined index: link_url in wordpress/wp-content/themes/sagemaster/kirki/includes/field/class-kirki-field-repeater.php on line 79

These notice disappear when I use 2.3.6 or 2.3.5

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please post the code you're using to create that repeater field?

**Comment by robbisy** [comment]
In the theme-option.php
```
Kirki::add_field( 'my_config', array(
    'type'        => 'repeater',
    'label'       => esc_attr__( 'Repeater Control', 'kirki' ),
    'description' => esc_attr__( 'The "repeater" control allows you to create rows of data and you can define the fields that the rows will use. Valide field-types are: text, checkbox, radio, select, textarea. The data is saves as a multi-dimentional array.' ),
    'help'        => esc_attr__( 'This is a tooltip', 'kirki-demo' ),
    'section'     => 'social',
    'priority'    => 10,
    'row_label' => array( 'type' => 'field', 'value' => 'social','field'  => 'my_settings', ),
    'settings'    => 'repea',
        'fields' => array(
      'link_text' => array(
        'type'        => 'text',
        'label'       => esc_attr__( 'Social media', 'kirki-demo' ),
        'description' => esc_attr__( 'This will be the label for your link', 'kirki-demo' ),
      ),
     'my_settings' => array(
                    'type'        => 'select',            
                    'label'       => esc_html__( 'Social', 'my_textdomain' ),                        
                    'priority'    => 10,
                    'multiple'    => 999,  
                    'choices'     => array(
                        'facebook'  => esc_attr__( 'Facebook', 'theme-name' ),
        'twitter'   => esc_attr__( 'Twitter', 'theme-name' ),
        'google-plus'    => esc_attr__( 'Google+', 'theme-name' ),
        'instagram' => esc_attr__( 'Instagram', 'theme-name' ),
        'skype'     => esc_attr__( 'Skype', 'theme-name' ),
        'youtube'   => esc_attr__( 'Youtube', 'theme-name' ),
        'vimeo'     => esc_attr__( 'Vimeo', 'theme-name' ),
                        ),     
                    ),
      'link_url' => array(
        'type'        => 'text',
        'label'       => esc_attr__( 'Link URL', 'kirki-demo' ),
        'description' => esc_attr__( 'This will be the link URL', 'kirki-demo' ),
      ),
    ),
  ) );
```
and I use it like that in my content.php
<?php if ( true == get_theme_mod( 'socialed', true ) ) : ?>
		<div class="meta-share">
			<span class="share-text">Share:</span>
		<?php $repeater_value = get_theme_mod( 'repea'); ?>
		<?php foreach ( $repeater_value as $rowi ) : ?>
		  <?php if ( isset( $rowi['link_url'] ) && ! empty( $rowi['link_url'] ) ) : ?>
				<a href="<?php echo esc_url_raw( $rowi['link_url'] ); ?>"><i class="fa fa-<?php echo $rowi['my_settings']; ?>"></i></a>
          <?php endif; ?>
        <?php endforeach; ?>
        </div>
        <?php endif; ?>
