### ISSUE TITLE
Add class name to controls

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#117]
Hi there

How can I add custom class name to kirki controls (for styling with css).

Thanks a lot

**Comment by aristath** [comment]
Hey there!

Controls already have their own custom classes, you shouldn't have to add anything!

What is it exactly that you want to style?
I'd suggest you also take a look at the [develop](https://github.com/aristath/kirki/tree/develop) branch as all the styling has been re-coded from scratch there.
