### ISSUE TITLE
Visual Customizer Builder for KIRKI

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1174]
Hi,

This is not an issue. Just wanted to share something i made with your plugin. 
Currently to add customizer fields, codes has to be written but now that will be over.
I have made a plugin "Visual Customizer Builder for KIRKI". With this plugin you can make customizer fields within minutes.

Link of plugin : https://github.com/ravishakya/visual-customizer-builder-kirki

## Features
* Visually create your Fields
* All kirki fields are supported plus extra 3 fields( Page ID, Taxomony and users )
* Drag and drop options
* Supports Panels and Sections amd many more .............

**Comment by pingram3541** [comment]
@ravishakya Thanks for sharing!

**Comment by ravishakya** [comment]
It would be grt if I had feedback and suggestions on that to improve. :)

**Comment by aristath** [comment]
@ravishakya that's awesome! Thank you!
I installed it and took a look earlier today, seems to be working great!
I haven't taken a look at the code yet... I'll do that later today. I'll be rebuilding the main kirki site soon to add some tools & resources and I'd love to add that too... I'm just prioritizing a rewrite of the plugin at the moment (see the [modular](https://github.com/aristath/kirki/tree/modular) branch)

**Comment by ravishakya** [comment]
Thank you. You liked it.
You want to add the plugin "Visual Customizer Builder for KIRKI" inside KIRKI ??
If that's so. Thats great

**Comment by pingram3541** [comment]
I like it.  Export/import configs would be awesome.  Especially export to php.  Perfect use for rapid customizer theme or plugin builder.

Another idea to promote rapid development could be in providing the empty php code blocks that can be copied to the clipboard easily.  I like where this is going because one of the things that attracts me to Kirki in the first place is to short-circuit the much longer wp method to reduce dev time.

**Comment by ravishakya** [comment]
"Export to php" is also completed but i haven't release the code yet.

**Comment by geniuspro** [comment]
When you release "Export to PHP" feature? This feature is important for theme developers.
