### ISSUE TITLE
js_vars add class $ + keep existing using %value% using value_pattern

### ISSUE THREAD

**Issue by pingram3541** [themeum/kirki#1175]
### Issue description: Continued from this closed ticket - https://github.com/aristath/kirki/pull/1137#issuecomment-263335657

When using js_vars with the html function to replace an element's class attribute but retain existing "original DOM" class(es) the new classes were not being rendered and the placeholder $ would simply compound on each Kirki setting change.  i.e. class="original-class $ $ $" where the 3 $'s have been added because I changed my setting 3 times, but rather than adding the class values from the Kirki setting, it adds the placeholder.  On L79 of postmessage.js from #1137 we are not using the already rendered "val" variable but grabbing the original value of value_pattern which is what is throwing us the static $.

Additionally, even after fixing the $ rendering problem there is still the problem of concatenation of chosen values to classes as you change your Kirki setting each time. i.e. class="original-class bottom-right top-left top-right"

We likely don't prefer to keep adding classes.  So before that we should store the original DOM class attrs and use that instead.

### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'my_config', array(
    'settings'    => 'position',
    'section'     => 'general',
    'label'       => 'Position',
    'type'        => 'radio',
    'choices'     => array(
        'top-left' => esc_attr__( 'Top Left' ),
        'top-right'  => esc_attr__( 'Top Right'),
        '' => esc_attr__( 'Bottom Left'),
        'bottom-right'  => esc_attr__( 'Bottom Right')
    ),
    'default'     => '',
    'transport'=>'postMessage',
    'js_vars'   => array(
        array(
            'element'       => '.original-class',
            'function'      => 'html',
            'attr'          => 'class',
            'value_pattern' => '%value% $',
        ),
    ),
));
```

May be a bit rough on the edges but this works for me.

/assets/js/postmessage.js:

1) Initialize classes var with non-valid value early on
L2:	`var api = wp.customize, classes = false;`

2) In our jsVars loop, we check classes var against conditional to confirm it has a value and if so, use the existing value instead of getting it from the DOM...again (which would never contain %value% to match against after being changed once but does carry the extra classes we have previously appended which we don't want).  If it doesn't have value ( is false ), then we update the classes var from the DOM for the first time. Then on the next line we modify the original 

L79: 
```
if ( false === classes ) classes = jQuery( args.element ).attr( args.attr );
val = val.replace( /\%value%/g, classes ); 
```

**Comment by aristath** [comment]
See comment on https://github.com/aristath/kirki/pull/1137#issuecomment-267817233
