### ISSUE TITLE
How can I push my extentions to kirki master branch?!

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#118]
Hi there

(An amateur question)
I've added some new features (like extend the required feature to select controls) to kirki, but I don't know how can I push this changes to kirki master branch.

Any Advice?!

Thanks a lot

**Comment by vpratfr** [comment]
Hi,
1. Make a fork of the Kirki repository
2. Checkout the `develop` branch from your fork
3. Make a new branch named `feature/extend-select`
4. Commit all your changes to that `feature/extend-select`branch
5. Once you are done, go to your github repository (your fork) and select that branch
6. Click on the `Create pull request` button that should appear
7. Make sure to base your pull request on the kirki's `develop` branch (not the master branch)

See also: https://guides.github.com/activities/contributing-to-open-source/

**Comment by padalec** [comment]
Hi @vpratfr,
when I try to make clon in branch develop I got git error this branch doesn't exists. Any idea?

**Comment by vpratfr** [comment]
It does exist: https://github.com/aristath/kirki/tree/develop

Make sure you have pulled it with your fork and checked it out. Refer to the github and git documentation about that.
