### ISSUE TITLE
Unresponsive script on firefox

### ISSUE THREAD

**Issue by nicolas92** [themeum/kirki#1182]
Hello,

I have a small problem on the firefox browser, first of all, thank you for creating Kirki, it saves me a lot of time and the controls are awesome :)

I created a theme with several options in the customizer but when I wanted to try the customizer on firefox, I have a box "Unresponsive script", if I click on continue, it works but I would like to solve this if possible so that users who will use my theme is not that problem.
On chrome everything works perfectly.

Can you help me?

I can create an admin account and send you information in private.

Thank you very much :)

**Comment by aristath** [comment]
@nicolas92 I'm sorry I never got back to you on this one...
I was unable to replicate this no matter what I tried. Is this still an issue for you?

**Comment by nicolas92** [comment]
Hello, sorry, I had to rewrite my code to put options much simpler because many users use firefox and was wondering every time why there was this issue.
If one day, there is more this problem, I would be happy to re-use Kirki that I find great :)

**Comment by aristath** [comment]
OK. Since noboby else reported anything similar I think this may have been isolated to the version we had out in December.
This doesn't seem to be an issue any longer so I'll go ahead and close this issue 👍
