### ISSUE TITLE
typography field broken in latest github version

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#1188]
### Issue description:
It seems the typography field is completely broken. Well, multiple bugs.

1. No labels
Have a look at the screen shot: http://i.imgur.com/fMfrmnc.png
As you can see, none of the fields have any labels anymore, such as font-family, font-size etc.

2. font-size always adds "px" suffix in css.
In earlier versions, you had to enter a font-size value, followed by the unit, such as px, rem or em.
Now the CSS output always adds px by itself.
If I enter 3.6rem inside of the customizer, the css output will be 3.6rempx.

3. The transformation sub field is empty
Have a look at the screen shot: http://i.imgur.com/fMfrmnc.png
The transformation drop down menu is all blank. Multiple options are listed, but nothing is visible.

### Version used:
Latest github version as of 5.December 2016

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'my_config', array(
	'type'        => 'typography',
	'settings'    => 'my_setting',
	'label'       => esc_attr__( 'Control Label', 'kirki' ),
	'section'     => 'my_section',
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'subsets'        => array( 'latin-ext' ),
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left'
	),
	'priority'    => 10,
	'output'      => array(
		array(
			'element' => 'body',
		),
	),
) );
```

**Comment by aristath** [comment]
@kmob2 hey there!

The development branch contains an almost complete rewrite so some bugs are to be expected.
For a stable release you can use the [version from wordpress.org](https://wordpress.org/plugins/kirki/), otherwise if you can keep on testing the development version and report any bugs you find I'd be grateful! 👍

**Comment by aristath** [comment]
> No labels

Fixed last week.

> font-size always adds "px" suffix in css.

Fixed it just now. 👍 

> The transformation sub field is empty

Fixed.

Thanks for taking the time to test the development branch, I really appreciate it!
Try pulling the latest changes and if you find any other issues please create a new ticket. 👍
