### ISSUE TITLE
Reset not working with typography field type properly

### ISSUE THREAD

**Issue by robi09** [themeum/kirki#1193]
### Issue description:
I have a two issue:
1. the reset button is not working with typography because of this error:
07-Dec-2016 12:10:01 UTC] PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in C:\xampp\htdocs\ayelabs\rohas\wp-content\themes\wp60-wp\includes\kirki\includes\field\class-kirki-field-typography.php on line 133 
This error can be avoided if i add the 'variant' array key, but it will nice to work without variant too.

2. The font is not updated on the drop-down field after the reset is triggered.
### Version used:
2.3.7

### Using theme_mods or options?
I'm using theme_mods.

### Code to reproduce the issue (config + field(s))
Kirki::add_field( 'theme_customize', array(
	'type'        => 'typography',
	'settings'    => 'theme_fonts_primary',
	'label'       => esc_attr__( 'Primary font', 'theme' ),
	'description' => esc_attr__( 'Paragraphs, buttons, post navigation and content formatting.', 'theme' ),
	'section'     => 'theme_content_fonts',
	'default'     => array(
		'font-family'    => 'Source Sans Pro',
	),
	'output'      => array(
		array(
			'element' => '.formatting',
		)
	),
) );

Config:
Kirki::add_config( 'theme_customize', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
	'disable_output' => false
) );

**Comment by aristath** [comment]
> This error can be avoided if i add the 'variant' array key, but it will nice to work without variant too.

The font-family control actually adds the variants & subsets sub-controls by default because google-fonts require all 3 of them to properly work. So all 3 values will have to be defined in the defaults array.

> The font is not updated on the drop-down field after the reset is triggered.

Fixed.

**Comment by notrealdev** [comment]
Same here, reset only working when reload page!

**Comment by aristath** [comment]
fixed in https://github.com/aristath/kirki/commit/f66661c144f784066bcf023462fb596c59b65bca
