### ISSUE TITLE
Problem with replace single class

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#1196]
### Issue description:
Hi @aristath 
I can not find a way to replace a single standard class with a value in a select customized with partial refresh.

I have a situation where I have a section with three classes. One of these 'defColor' is that which is changed through the use of a select in the customizer.

My problem is that when you return, all classes and the content of the section is deleted, leaving only the value of my select.

You can change only a specific class, leaving unchanged the rest? I tried through value_pattern but without any success.

### Version used: 
stable 2.3.7

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```php
Kirki::add_field( 'wedding_day', array(
        'type'        => 'select',
        'settings'    => 'box_couple',
        'label'       => __( 'Change color section', 'goweddy' ),
        // 'help'        => __( 'Set the style and design of the website', 'goweddy' ),
        'panel'       => 'manage_section',
        'section'     => 'edit_couple',
        'default'     => 'defColor',
        'priority'    => 1,
        'choices'     => array(
            'defColor'    => __('Default Color','goweddy'),
            'altColor'    => __('Alternative Color','goweddy'),
        ),
        'transport'   => 'postMessage',
        'js_vars'     => array(
            array(
                'element'       => '#couple',
                'function'      => 'html',
                'attr'          => 'class',
                'value_pattern' => '%defColor%',
            ),
        ),
        'partial_refresh' => array(
            'partial_box_couple' => array(
                'selector'        => '#couple',
                'render_callback' => function() {
                    return get_theme_mod( 'box_couple' );
                },
            ),
        ), 
    ));
```

My HTML/PHP code:

```php
<section id="couple" class="highSpace <?php echo get_theme_mod('box_couple', 'defColor'); ?> pattern0">
    <div class="container">
        .....
    </div>
</section>
```

**Comment by daviedR** [comment]
Hi @sododesign, I got your email for help.

I think currently Kirki postMessage couldn't change class. You might need to do it manually using your own javascript.

**Comment by aristath** [comment]
This is still a work in progress....
The rewrite of Kirki in the develop branch has some issues to resolve, but this will be included in the final release.

**Comment by sododesign** [comment]
Thanks @daviedR and @aristath :)

**Comment by aristath** [comment]
See comment on https://github.com/aristath/kirki/pull/1137#issuecomment-267817233
