### ISSUE TITLE
Problem with the sortable control

### ISSUE THREAD

**Issue by nicolas92** [themeum/kirki#1197]
<h3>Issue description:</h3>
Hello @aristath, I noticed a small problem with WordPress 4.7 and the sortable control.
The button to save the customizer changes is "Saved" and if you change an option, the button becomes "Save & Publish" but when I insert the sortable control, the button is original to "Save & Publish ", it is not a big problem because if I make changes and I click on the button, my changes are saved but if it is possible to solve this small problem, it would be great :)
I tried with the latest version of kirki on wordpress and on github.
<h3>Version used:</h3>
stable 2.3.7 and I also test with the github version

<h3>Using theme_mods or options?</h3>
theme_mods

<h3>Code to reproduce the issue (config + field(s))</h3>
<pre>Kirki::add_field( 'my_config', array(
	'type'        => 'sortable',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'section_test',
	'default'     => array(
		'option3',
		'option1',
		'option4'
	),
	'choices'     => array(
		'option1' => esc_attr__( 'Option 1', 'kirki' ),
		'option2' => esc_attr__( 'Option 2', 'kirki' ),
		'option3' => esc_attr__( 'Option 3', 'kirki' ),
		'option4' => esc_attr__( 'Option 4', 'kirki' ),
		'option5' => esc_attr__( 'Option 5', 'kirki' ),
		'option6' => esc_attr__( 'Option 6', 'kirki' ),
	),
	'priority'    => 10,
) );</pre>

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/8a2f674d2015f092789e0e9af546728c6888dd4b

**Comment by nicolas92** [comment]
You are the best, thank you very much :)

**Comment by aristath** [comment]
:) glad I could help.
Please note though that this fix is on the develop branch which may include other bugs as well since it's a rewrite of a lot of things... If you could test it and report any issues you find I'd greatly appreciate it! 👍

**Comment by nicolas92** [comment]
You can count on me :)
