### ISSUE TITLE
Section type expanded not working in WordPress 4.7

### ISSUE THREAD

**Issue by RonalddeRooij** [themeum/kirki#1200]
### Issue description:
Updated to the latest version and the expanded panels are gone. The option type expanded doesn't work anymore.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.7

### Code to reproduce the issue (config + field(s))

Kirki::add_section( 'general_layout', array(
	'title' => __( 'Layout', 'caramelomedia' ),
	'panel' => 'general',
	'type'  => 'expanded',
) );

**Comment by aristath** [comment]
Yes, WP 4.7 changed a couple of things and now section-types currently don't work, I'm currently in the process of re-implementing them anew to fix this.
Marking as a bug

**Comment by RonalddeRooij** [comment]
Hi,

Thanks for the reply I'm looking forward to the solution.

Met vriendelijke groet,

Ronald de Rooij

Op 12/12/2016 om 12:15 schreef Aristeides Stathopoulos:

**Comment by aristath** [comment]
Hey there!

This was just fixed in the development branch.
Can you please download a fresh copy from this repository and test if it works for you now?

**Comment by RonalddeRooij** [comment]
Thanks Aristath,

The new copy solved my problem! The expanded sections are expanded again.

There is only 1 small problem, the expanded panels are pushed to the left due to the fact a scroll bar is appearing when I'm selecting a option. Example: http://recordit.co/vqQY9daTea

Also in the video you can see that my number input field looks really weird (small in height) this happend since 2.4.0.
