### ISSUE TITLE
Repeater field row_label should respect passed in string's casing

### ISSUE THREAD

**Issue by timelsass** [themeum/kirki#1204]
### Issue description:

When using the repeater field, the row_label always does something like ucwords() and uppercases the first letter of each "word" in my strings.

I would expect the string passed in for the row_label to respect my own casing decisions made.

### Version used: 
"https://github.com/aristath/kirki.git#2.3.7"

attempted:
"https://github.com/aristath/kirki.git#develop", but have too many errors currently.  I am upgrading them from 2.3.2 to 2.3.7.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'contact_details', array(
	'type'        => 'repeater',
	'label'       => esc_attr__( 'Contact Details', 'test' ),
	'section'     => 'footer_panel',
	'priority'    => 10,
	'row_label' => array(
		'field' => 'contact_block',
		'type' => 'field',
		'value' => esc_attr__( 'Contact Block', 'test' ),
	),
	'settings'    => 'contact_details_setting',
	'default'     => array(
		array(
			'contact_block' => esc_attr( 'info@example.com' ),
		),
	),
	'fields' => array(
		'contact_block' => array(
			'type'        => 'text',
			'label'       => esc_attr__( 'Text', 'test' ),
			'description' => esc_attr__( 'Enter the text to display in your contact details', 'test' ),
			'default'     => '',
		),
	)
) );
```
I expect the row_label for this item to read: info@example.com
Instead I see the row_label as: Info@Example.Com

**Comment by aristath** [comment]
Great catch!
It's a wonder nobody reported this sooner... It's been like that for months!
Fixed in the develop branch.

**Comment by timelsass** [comment]
Yeah it seemed odd to me, but everyone has their preferences I guess :) Thanks for the quick fix!
