### ISSUE TITLE
multicolor: output linear-gradient(90deg, color1, color2) in customizer and frontend

### ISSUE THREAD

**Issue by themenow** [themeum/kirki#1214]
### Issue description:

I needed to create an option for a style like this

`background: linear-gradient(90deg, color1, color2);`

I think value_pattern might be the answer but how to write it with multiple values?

`'value_pattern' => 'linear-gradient(90deg, $1, $2)',`

I tried above but not working

### Version used:

2.3.7

### Using theme_mods or options?

theme_mods

**Comment by aristath** [comment]
I'm afraid that won't work... There's currently no mechanism implemented to make css outputs properly work on multicolor fields using a value patter so you'll have to custom-code it.
Something like this should work:

```php
add_action( 'wp_enqueue_scripts', function() {
	$colors = get_theme_mod( 'my-setting' );
	$custom_css = '
		body .my-element {
			linear-gradient(90deg, ' . $colors['start'] . ', ' . $colors['end'] . '); 
		}';
	wp_add_inline_style( "kirki-styles-{$config_id}", $custom_css );
}, 1000 );
```

**Comment by themenow** [comment]
Thanks for the code, will try it later, does it work for live preview?

**Comment by aristath** [comment]
It works for live-previews too, provided of course that you don't use `postMessage`.
