### ISSUE TITLE
Issue with visual representation of color picker (alpha iris)

### ISSUE THREAD

**Issue by fongreecss** [themeum/kirki#1218]
### Issue description:
I am developing WP theme and using TGMPA to download and activate plugins. My theme downloads your plugin from wordpress.org. There is a problem with visual representation of color picker (see the picture). 

I've been testing on Google Chrome 55.0.2883.87 (64-bit). Elementary OS (Ubuntu based). 
[<img src="http://i.imgur.com/ZIejJbL.png">](http://i.imgur.com/ZIejJbL.png)

(Probably) The problem is with margin-left calculation of .iris-alpha-slider elements. 

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) No, as explained

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please try the development branch from this repository and let me know if you're still having an issues with that?
I can't do anything about version 2.3.7, except fix it in the next version.
That's what the develop branch here is... a beta version of the next release. 😄

**Comment by fongreecss** [comment]
Yes it is still the same. :)

**Comment by fongreecss** [comment]
quick fix would be: replacing 253rd line in controls/color/wp-color-picker-alpha.js
`self.controls[v].width( stripsWidth ).css({ 'margin-left': stripsMargin + 'px' });`
with
`self.controls[v].width( stripsWidth ).css({ 'margin-left': Math.floor(stripsMargin) + 'px' });`

**Comment by aristath** [comment]
Well, I can't replicate your issue, but I pushed a commit with those changes anyway. 
I hope that fixes your issue! 👍
