### ISSUE TITLE
After resetting the values shown at customizer buttons not changing in typography field

### ISSUE THREAD

**Issue by JustinJohnM** [themeum/kirki#1219]
After resetting the customizer typography section the preview area works fine, but the values shown at input fields will not changing to default. 
![issue](https://cloud.githubusercontent.com/assets/20510572/21389586/8853d5d2-c7a8-11e6-988b-d44f92df5766.png)

This can be reproduced at basic _s ,   wp 4.7 ,     kirki 2.3.7

Steps to reproduce :  change values in typography,    reset the typography section
Preview section works fine, also font-size & line-height input fields shows default value but font-family & color input fields shows values before reset.
![issue_s](https://cloud.githubusercontent.com/assets/20510572/21389927/29475954-c7aa-11e6-9538-9c31077bb720.png)

**Comment by aristath** [comment]
Can you please try this with the development branch from this repository and let me know if that fixes your issue?

**Comment by JustinJohnM** [comment]
I tried "kirki-develop" , Not resolved

**Comment by aristath** [comment]
fixed in https://github.com/aristath/kirki/commit/f66661c144f784066bcf023462fb596c59b65bca
