### ISSUE TITLE
Radio-image labels?

### ISSUE THREAD

**Issue by shelbyneilsmith** [themeum/kirki#1220]
I feel like adding labels for radio-image options would be highly useful. So, instead of just defining radio-image choices like `key => url`, you could have something like 

`key => array( 
    label => 'label',
    url => 'url'
)`

Then it could just add a title attribute to each option's .image-clickable span element. Are there any plans for anything like this?

**Comment by shelbyneilsmith** [comment]
Any thoughts on this? Seem like a relatively easy feature to implement...surely I can't be the only one that needs this..?

**Comment by aristath** [comment]
Fixed.
But instead of `label` and `url` I used `src` and `alt` 'cause those are the attribules used in the image, so it made more sense that way.

**Comment by shelbyneilsmith** [comment]
Fantastic! I'll update my themes asap!

**Comment by aristath** [comment]
Keep in mind that this only works with the development branch of the plugin...
Try it and if you have any suggestions regarding the styling, let me know. Pull requests are greatly appreciated :)

**Comment by shelbyneilsmith** [comment]
Yeah, I realized that as soon as I posted... may hold off on applying to themes, haha. anyway, I'll check it out and let you know if I have suggestions. Thanks for getting to this!
