### ISSUE TITLE
Customizer Setting integration not working in WordPress 4.7

### ISSUE THREAD

**Issue by allysonsouza** [themeum/kirki#1222]
### Issue description:
The Kirki install recomendation not displayed at customizer when usign the Customizer Setting integration in WordPress 4.7.

### Version used:
2.3.7

### Code to reproduce the issue (config + field(s))
Just follow the integration with Customizer Setting.

WordPress 4.7 does not support anymore expanded sections, I think it's breaking the Customizer Setting integration. There's a workaround for fix it? Or the best alternative now is to use TGM? (It's what I'm using at the moment)

**Comment by aristath** [comment]
Can you please try pulling the latest version from the github repository and let me know if that works for you?
The file on https://github.com/aristath/kirki-helpers/blob/master/include-kirki.php was updated a few days ago

**Comment by allysonsouza** [comment]
Thanks @aristath, I faced this problem on monday, it's already fixed in the actual version.
