### ISSUE TITLE
Where is version 2.4.0?

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#1223]
Hello,

Quick question. I see you a few comments you are mentioning version 2.4.0. 
In WordPress.org the version is still 2.3.7 and here on github  I can't seem to find any file that refers to a version number. When you said version 2.4.0, is that the development branch here on Github?

**Comment by aristath** [comment]
Yes, develop branch. 
I'll update the version number there later today but just pulling the develop branch will get you the latest commits. 👍

**Comment by aristath** [comment]
Tagged 2.4.0-beta.1
https://github.com/aristath/kirki/releases/tag/2.4.0-beta.1
