### ISSUE TITLE
Tooltip not closing when clicking outside of icon

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#1226]
### Issue description:
The tooltip is not closing when clicking outside the icon. So if the user clicks on the tooltip icon and then continues working, the tooltip will still be shown.

Video: https://cl.ly/iYl0

### Version used:
2.4.0-beta.1

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
Standard tooltip implementation.

**Comment by aristath** [comment]
Good catch!
Fixed 👍
