### ISSUE TITLE
Tooltip height fix in 2.4.0-beta.1

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#1228]
I have attached [tooltip-height.zip](https://github.com/aristath/kirki/files/670851/tooltip-height.zip) where I have fixed the tooltip height in 2.4.0-beta.1

### What I did
Removed min-height, adjusted tooltip arrow position and added
line-height.

### Before 1
![kirki tooltip height before 1](https://cloud.githubusercontent.com/assets/9765146/21455120/01f54cb0-c91e-11e6-87a9-58e13bcf8d02.png)

### After 1
![kirki tooltip height after 1](https://cloud.githubusercontent.com/assets/9765146/21455016/60f438f8-c91d-11e6-8c6a-490c231201c6.png)

### Before 2
![kirki tooltip height before 2](https://cloud.githubusercontent.com/assets/9765146/21455085/b7046650-c91d-11e6-81a9-29bbe7febd0c.png)

### After 2
![kirki tooltip height after 2](https://cloud.githubusercontent.com/assets/9765146/21455098/c7d8a9c8-c91d-11e6-8d55-899da4942a10.png)

**Comment by aristath** [comment]
I just commited this. 👍
