### ISSUE TITLE
2.4.0.beta Alpha => True doesn't work -- no rgba slider

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#1229]
### Issue description:

In 2.3.x the alpha worked as expected, in 2.4.0 there is no second slider. I tested with and without my custom css. So it's not my install specifically.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```/** 
 *
 * Breadcrumb Color
 * @since  1.0.0
 *
 */
Themename_Kirki::add_field( 'themename_theme', array(
    'settings'     => 'page_main_breadcrumb',
    'label'        => esc_attr__( 'Breadcrumb Color', 'text-domain' ),
    'section'      => 'page_main_section',
    'priority'     => 1,
    'alpha'        => 'true',
    'type'         => 'color',
	'choices' => array (
    	'palettes' => array(
    		'#222222',
        	'#00215b',
        	'#242454',
    		'#3f251a',
        	'#074549',
        	'#490010',
        	'#1a4205',
        	'#24253d',
    	),
	),    
    'default'      => 'rgba(255, 255, 255, 0.7)',
	
	'output' => array(
	
		array(
		
			'element'  => '.page-main-section .breadcrumb',
			'property' => 'color',
		
		),	
		
	),
	
    'active_callback'    => array( 
        array(
            'setting'  => 'keep_color_pattern',
            'operator' => '==',
            'value'    => '1',
        ),
     ),
) );
```
2.3.7 Works
![2 3 7-alpha](https://cloud.githubusercontent.com/assets/1124594/21472367/02ba2cc4-caa4-11e6-9de4-964e0ab08d66.png)

2.4.0 Not working
![2 4 0-alpha-gone](https://cloud.githubusercontent.com/assets/1124594/21472368/02ba95ec-caa4-11e6-8cf3-dc3a79115d86.png)

**Comment by aristath** [comment]
squashed another bug... 🐛 
Fixed. 👍

**Comment by carasmo** [comment]
Thanks!!!

**Comment by carasmo** [comment]
This is back again. Using the develop branch: https://github.com/aristath/kirki/branches

**Comment by aristath** [comment]
@carasmo i can't replicate the issue... Sees to be working fine!
