### ISSUE TITLE
Enhancement: Dynamic repeater label for select should not pick up the option VALUE

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#1230]
It is possible to use a dynamic repeater label based on a select value, which is great! But it would be even greater if it would pick up the option TEXT instead of the VALUE.

![kirki-dynamic-label](https://cloud.githubusercontent.com/assets/9765146/21485280/1a51648a-cba1-11e6-8632-9638dbde0cab.png)

In the example above, I would like the field label to be "Featured Products" instead of "featured-products".

**Comment by aristath** [comment]
Fixed in 3.0
