### ISSUE TITLE
Can i use Kirki for wp.org free theme repo and wp.com premium theme repo?

### ISSUE THREAD

**Issue by Ansif** [themeum/kirki#1231]
Hi,

Can i use kirki framework in a theme for uploading to wp.org and wp.com?

All the functions and backend things are developed based on review team best practices and code guide lines?

Thanks! 👍

**Comment by aristath** [comment]
Hey there!

Yes, you can use the plugin in a theme hosted on w.org
You can see instructions on https://aristath.github.io/kirki/docs/advanced/integration.html

**Comment by Ansif** [comment]
Ok, thanks! :)
