### ISSUE TITLE
Exclude stopped working in 2.4.0-beta.1

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#1232]
### Issue description:
The exclude argument stopped working for output in version.

### Version used:
2.4.0-beta.1. It worked in 2.3.7.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
<pre>scandinavian_Kirki::add_field('scandinavian_theme', array(
  'type' => 'switch',
  'settings' => 'shop_meta_data',
  'label' => _x('Meta data', 'Customizer → Shop', 'scandinavian'),
  'section' => 'shop_product',
  'default' => 0,
  'priority' => 30,
  'choices' => array(
    'on' => _x('Show', 'Customizer → Shop', 'scandinavian'),
    'off' => _x('Hide', 'Customizer → Shop', 'scandinavian')
  ),
  'output' => array(
    'element' => '.woocommerce.single-product .product_meta',
    'property' => 'display',
    'value_pattern' => 'none',
    'exclude' => array( '1' )
  )
));</pre>

I have tried setting
<pre>'exclude' => array( '1' )
'exclude' => array( 1 )
'exclude' => array( 'off' )
'exclude' =>'1'
'exclude' =>1
'exclude' =>'off'</pre>

...but nothing works. As I said, it worked in 2.3.7.

**Comment by aristath** [comment]
did you try using `true` (bool) instead of `'1'` (string) ?
The only breaking change so far is that checkboxes will now save boolean values instead of strings... This way we're compliant with the way WP-Core does it.
I'm still trying to figure out how to handle that for backwards-compatibility...

**Comment by joakimaglo** [comment]
Thanks, that worked!

<pre>scandinavian_Kirki::add_field('scandinavian_theme', array(
  'type' => 'switch',
  'settings' => 'shop_meta_data',
  'label' => _x('Meta data', 'Customizer → Shop', 'scandinavian'),
  'section' => 'shop_product',
  'default' => false,
  'priority' => 30,
  'choices' => array(
    'on' => _x('Show', 'Customizer → Shop', 'scandinavian'),
    'off' => _x('Hide', 'Customizer → Shop', 'scandinavian')
  ),
  'output' => array(
    'element' => '.woocommerce.single-product .product_meta',
    'property' => 'display',
    'value_pattern' => 'none',
    'exclude' => array( true )
  )
));</pre>
