### ISSUE TITLE
Retaining changes when switching to child theme

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1234]
Hello,

When I make a change using the customizer and then switch from parent theme to child theme, all the customization is lost. Is this the default behaviour and is there a way to carry over the customization to the child theme?

**Comment by aristath** [comment]
This is just the way WordPress theme-mods work.
However, you may be able to implement a semi-hacky solution that will allow your child themes to inherit any options that are not set on a child theme from the parent theme.

Please note that the code below is untested and I just came up with this now. I have no idea if it'll work, but reason suggests that it should.

```php
$current_theme = get_option( 'stylesheet' );
add_filter( "pre_get_option_theme_mods_{$current_theme}", function( $value ) {

	// return unchanged if not a child-theme.
	if ( ! is_child_theme() ) {
		return $value;
	}

	// Get the parent-theme name.
	$parent_theme = wp_get_theme()->get( 'Template' );

	// Get the parent-theme theme-mods.
	$parent_theme_mods = get_option( "theme_mods_{$parent_theme}" );
	
	// Merge the 2 arrays.
	// If a theme-mod doesn't exist in the child-theme,
	// the value from the parent-theme will be used.
	return wp_parse_args( $value, $parent_theme_mods );

} );
```

**Comment by ghost** [comment]
Which file do I put this code into?

**Comment by aristath** [comment]
Assuming you're building a theme and want to allow people using your theme to use that, you'd put this in your parent theme's functions.php file.

**Comment by minimaluminium** [comment]
Using `option` instead of `theme_mods` is straightforward in this case.
