### ISSUE TITLE
text area not being saved

### ISSUE THREAD

**Issue by kadetu** [themeum/kirki#1237]
### Issue description:
hi i've started working with kirk but i'm having a little problem. 
i've created a textarea, while editing the preview is updating normally the text i input but when i save&publish and refresh the page the saved text is not more there? 
what i'm doing wrong? 

thanks 

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
//text-area
Kirki::add_field('my_config_test1', array(
    'type' => 'textarea',
    'settings' => 'my_text_area1',
    'section' => 'my_section_test1',
    'label' => __('AREA DE TEXTO'),
    'default' => esc_attr__( 'ESTE É O VALOR DEFAULT', 'jorges' ),
    'priority' => 10,
    'transport' => 'postMessage',
    'js_vars'   => array(
		array(
			'element'  => '#jorges-i1h1',
			'function' => 'html',
		),
    ),
));
```

**Comment by aristath** [comment]
Can you please also post your config for `my_config_test1` ?

**Comment by aristath** [comment]
I can't replicate this issue so I'll go ahead and close this ticket.
If you have more info on how to replicate it please feel free to reopen the issue and post an update.
