### ISSUE TITLE
Custom Taxonomy terms multicheck problem

### ISSUE THREAD

**Issue by allysonsouza** [themeum/kirki#1238]
### Issue description:
I'm trying to populate a multicheck with terms from a custom taxonomy registered in my theme, but I think it's too soon and the taxonomy it's not ready (if I use category or tags works).

### Version used:
2.3.7

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
I just included the code to create my customizer fields into the top of functions.php, after include/require Kirki. The following function ideias_tema_options() is defined in the end of my functions.php.

```
    Ideias_e_Cia_Kirki::add_field( 'ideias', array(
    	'type'        => 'multicheck',
    	'settings'    => 'temas_destaque',
    	'label'       => esc_attr__( 'Temas em destaque', 'ideias' ),
    	'section'     => 'home',
    	'priority'    => 20,
    	'choices'     => ideias_tema_options(),
    ) );

function ideias_tema_options() {
    $terms = get_terms( array(
        'taxonomy'      => 'tema',
        'hide_empty'    => false,
        'orderby'       => 'name',
    ) );

    $options = array();

    if ( ! empty( $terms ) && ! is_wp_error( $terms ) ){
        foreach ( $terms as $term ) {
            $options[ $term->ID ] = $term->name;
        }
    }

	return $options;
}
```

To fix that I have to wrap the Kirki customizer field creation in some hook?

**Comment by allysonsouza** [comment]
Solved using the hook `customize_register` for wrap all my Kirki fields code.

**Comment by aristath** [comment]
If you add your fields on `customize_register` then CSS output will only work while in the customizer because once you exit the customizer no fields will be detected...
Have you tried `init` or `wp`?

**Comment by allysonsouza** [comment]
I've tried `init` (with less priority than the function that are registering the custom taxonomy),  but the taxonomy is not registered yet, and in `wp` no fields are displayed.

**Comment by allysonsouza** [comment]
For now I've just wrapped only the custom  taxonomy multicheck field into a function called in `customize_register`, since that field don't have any CSS to output.
