### ISSUE TITLE
Multiple Instances of CSS properties on inline CSS

### ISSUE THREAD

**Issue by sethstha** [themeum/kirki#1241]
### Issue description:
Thanks for your great effort. While i was trying to live preview text color of breadcrumbs. Inline CSS was inserted but it was replaced by default style.css. Next i found properties are being repeat for 3 times.

Here is the code i am using 
```
Suffice_Kirki::add_field( 'suffice_config', array(
	'type'			=>	'color',
	'settings'		=>	'suffice_breadcrumbs_font_color',
	'label'			=>	esc_html__( 'Breadcrumbs Font Color', 'suffice' ),
	'description'	=>	esc_html__( 'Controls the text color of breadcrumbs', 'suffice' ),
	'section'		=>	'suffice_section_breadcrumbs',
	'priority'		=>	10,
	'default'		=>	'#cbc9cf',
	'choices'     	=> array(
		'alpha'			=> false,
	),
	'transport'		=>	'postMessage',
	'js_vars'		=>	array(
		array(
			'element'	=>	'.breadcrumbs .breadcrumbs-trail a',
			'function'	=>	'css',
			'property'	=>	'color'
		)
	)
) );
```

Here is what I found while inspecting 
![image](https://cloud.githubusercontent.com/assets/2367137/21708477/2bef4b18-d401-11e6-96a9-b475b4676672.png)

![image](https://cloud.githubusercontent.com/assets/2367137/21708481/41ea8112-d401-11e6-9083-8ab3fbaea66e.png)

Version: 2.3.7

I am still not sure while default color properties for text is not being overwritten by inline CSS.

**Update:**
Just found Li was missing before a tag. That solved the live preview issue. But still why there is 3 more inline style?
Thank you

**Comment by aristath** [comment]
Does this only happen while in the customizer?
Or are you having this issue in the frontend of your site?

**Comment by aristath** [comment]
Can't replicate using the develop branch, so I'll go ahead and close this one.
