### ISSUE TITLE
Deprecated TinyMCE API call: <target>.onChange.add(..)

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1242]
### Issue description:
Firebug > Console > Deprecated TinyMCE API call: <target>.onChange.add(..)

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Latest form w.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Type = "editor"

**Comment by notrealdev** [comment]
same problem, wp.customize live preview not working with `editor` `Visual` mode
```
Deprecated TinyMCE API call: .onChange.add(..)
```
but work well with `editor` `Text` mode
