### ISSUE TITLE
Add remove button to repeater item's header

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#1250]
### Issue description:
Hi Pal

When I add a lot of social icons using repeater control I got caught in the traffic jam :) must open the item and scroll down to remove it .. very difficult

I asked you to add a remove icon on HOVER ONLY on the item's header.

Thanks for your great plugin.

### Version used:
2.3.7

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
For the time being this will stay as it is.
The current styling mirrors as closely as possible the way widgets work in the customizer.
If WordPress changes the way widgets work then we'll change things accordingly to match it.
The focus and goal is to make Kirki integrate with WP as seamlessly as possible.
