### ISSUE TITLE
typography field doesn't list standard font-families (Arial, Verdana ...

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#1252]
This is a follow up to issue #1189 - It's closed but I can't seem to open it again.

----
Hello aristath,

Sorry for opening this up again. I'm only just now continuing the typography on my theme.

I am very confused on why you would group the standard fonts together by "style".
Serif is not a font (typeface) by itself. Serif refers to if a font has a stroke a in their symbols or not. https://en.wikipedia.org/wiki/Serif - Respectively sans serif is without the stroke.

Grouping them all together doesn't really make sense to me, since they are all completely different looking fonts.
In css using `font-family`, if you have multiple fonts listed, they work as backups.

Example: `font-family: "Times New Roman", Times, serif;`
The browser first looks if the font `Times New Romand` is available, if nothing is found, then it looks for `Times` (which is similar), if again nothing is found, then it looks for all fonts styles that use `serif`.

The way the typography field currently is in kirki, is that if I select `sans serif` it outputs `'Monaco,"Lucida Sans Typewriter","Lucida Typewriter","Courier New",Courier,monospace'`, which are a group of completely different looking fonts, and since only the first one is being used by the browser, because they rest acts as backups, I have no way of selecting for example `Courier New`.

I really think all the standard web fonts as listed here: http://www.w3schools.com/cssref/css_websafe_fonts.asp should have their own selection field in the drop down. This current way of grouping them together is not really the way the fonts should be used.

**Comment by aristath** [comment]
Replied on https://github.com/aristath/kirki/issues/1189#issuecomment-277446554
