### ISSUE TITLE
Problem with sortable control

### ISSUE THREAD

**Issue by nicolas92** [themeum/kirki#1253]
### Issue description:
Hello, I noticed a problem with the sortable control, there are several sortable that do not serve anything, as on the screenshot, there should be 4 input sortables, there are 20 more.
There is no error in the console, I do not think it comes from the js but from the control.
I have this problem locally, I did not manage to reproduce it live but a person told me that it had exactly the same problem on a site in production.
Do you have any idea what might cause this issue?
Thank you very much :)

![screenshot](https://cloud.githubusercontent.com/assets/7522460/22000472/852553d0-dc3f-11e6-9340-d11e2cddb670.png)

### Version used:
Version 2.4.0

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
<pre>Kirki::add_field( 'meta', array(
	'type'        => 'sortable',
	'settings'    => 'my_setting',
	'label'       => __( 'Meta', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => array( 'author', 'date', 'categories', 'comments' ),
	'choices'     => array(
		'author' => esc_attr__( 'Author', 'my_textdomain' ),
		'date' => esc_attr__( 'Date', 'my_textdomain' ),
		'categories' => esc_attr__( 'Categories', 'my_textdomain' ),
		'comments' => esc_attr__( 'Comments', 'my_textdomain' ),
	),
	'priority'    => 10,
) );</pre>

**Comment by aristath** [comment]
Fixed. Should be ok now after you change the settings and re-save your options.

**Comment by nicolas92** [comment]
Thank you very much :)
