### ISSUE TITLE
Default dimension value does not process well percent units

### ISSUE THREAD

**Issue by fongreecss** [themeum/kirki#1254]
### Issue description:
I've set default value in percents to dimension field and I've come across this problem: Instead of `min-width:100%;`, it outputs `min-width:100;`. This happens only if units are given in percents. I've also tried with other css properties (like width, height).
EDIT: when I correct value in Customizer, it works as it should (but only then).

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) The latest develop branch

### Using theme_mods or options?
Theme_mods

### Code to reproduce the issue (config + field(s))
```php
		Sometheme_Kirki::add_field( THEME_TEXTDOMAIN, array(
			'type'        => 'dimension',
			'settings'    => 'button_min_width_mobile',
			'label'       => sometheme_esc_attr( 'Button Minimum Width - ' . MOBILE_INFO_TEXT ),
			'section'     => $section_id,
			'default'     => '100%',
			'priority'    => 10,
			'output'      => array(
				array(
					'media_query' => '@media (max-width: ' . MOBILE_WIDTH_MAX . 'px)',
					'element' => $button_css_selector,
					'property' => 'min-width',
				),
			),
		) );
```

**Comment by aristath** [comment]
I can't replicate this one...

**Comment by aristath** [comment]
I just checked again with the latest development version and this works fine now.
