### ISSUE TITLE
Repeater field not showing PDFs in the Media Library panel

### ISSUE THREAD

**Issue by bryanchalker** [themeum/kirki#1256]
### Issue description:
I'm using a repeater control to allow users to upload a series of PDFs on the page. When I test it and select "upload", the Media Library panel launches, but does not show the PDF files in the panel. 

I am able to upload them without issue, but it doesn't show them in the assets to choose.

### Version used:
Lastest Stable

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
$fields[] = array(
	'type'        => 'repeater',
	'label'       => esc_attr__( 'Visitor Packet(s)', 'mysite' ),
	'section'     => 'hb_section_visitorform',
	'priority'    => 10,
	'row_label' => array(
		'type'  => 'field',
		'value' => esc_attr__('Visitor Packet File', 'mysite' ),
		'field' => 'packet_name',
	),
	'settings'    => 'hb_visitorform_info_packet',
	'fields' => array(
			'packet_name' => array(
			'type'        => 'text',
			'label'       => esc_attr__( 'File Name', 'mysite' ),
			'default'     => '',
		),
		'packet_file' => array(
			'type'        => 'image',
			'label'       => esc_attr__( 'File', 'mysite' ),
			'default'     => '',
		),
		
	)
);

**Comment by aristath** [comment]
The `image` type is what it says: An image field.
It's not a file field... Just images are allowed.
Try using `upload` instead of `image` and let me know if that works for you.

**Comment by bryanchalker** [comment]
....do I win the "Blind Fool of the Week" award? Thanks :)
