### ISSUE TITLE
Don't allow select field (dropdown) to be empty when saving

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#1257]
I noticed when using the `select` field (dropdown), it's possible to hit the back space button to delete the entry, and then hit the save button. This will lead kirki to save an empty value, which can lead to unexpected results.

Can we have an option to make sure it's not possible to save as "empty", or if it's saved as empty, that the default value will be used instead?

**Comment by aristath** [comment]
Should be ok now.
Added some extra sanitization that uses the default value if empty is used.
