### ISSUE TITLE
Use as a mu-plugin

### ISSUE THREAD

**Issue by craigiswayne** [themeum/kirki#1258]
### Issue description:
Would love to be able to use this plugin as a mu-plugin, for themes that rely heavily on Kirki's functionality

### Version used:
master

**Comment by bryanchalker** [comment]
I use it on my Multisite setup without any issues. Works terrific. Don't Network Activate in order to keep the sub-site usage you want.

**Comment by aristath** [comment]
👍 
Yes, using as an mu-plugin shouldn't cause any issues whatsoever.
