### ISSUE TITLE
Overrinding parent-theme's field

### ISSUE THREAD

**Issue by kongebra** [themeum/kirki#1259]
### Issue description:
I have a theme that I made with Kirki, and it works fine. But when I am creating a child-theme, I meet some problems.

Currently I have a sortable-field, and I would like to add/edit the choices in it, in the child theme.

What I have tried:

This in a function which has `add_action( 'after_theme_setup', 'my_function' );`
`$fields = Kirki::$fields;`
`unset( $fields['my_setting'];`
`Kirki::$fields = $fields`

I have tried the normal WordPress way to remove controls:
`$wp_customize->remove_control( 'my_control );`

### Version used:
2.3.7

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

In parent_customize_register().
`Kirki::add_field( 'parent-theme', array(`
`        'type'              => 'sortable',`
`        'settings'          => 'my_setting',`
`        'label'             => __( 'Sortable', 'parent-theme' ),`
`        'section'           => 'my_section',`
`        'priority'          => 1,`
`        'default'           => array(`
`            'option-1',`
`            'option-2',`
`        ),`
`        'choices'           => array(`
`            'option-1'             => __( 'Option 1', 'parent-theme' ),`
`            'option-2'             => __( 'Option 2', 'parent-theme' ),`
`            'option-3'             => __( 'Option 3', 'parent-theme' ),`
`        ),`
`) );`

What I am trying in child_customize_register().
`Kirki::add_field( 'child-theme', array(`
`        'type'              => 'sortable',`
`        'settings'          => 'my_setting',`
`        'label'             => __( 'Sortable', 'child-theme' ),`
`        'section'           => 'my_section',`
`        'priority'          => 1,`
`        'default'           => array(`
`            'option-1',`
`            'option-2',`
`        ),`
`        'choices'           => array(`
`            'option-1'             => __( 'Option 1', 'parent-theme' ),`
`            'option-2'             => __( 'Option 2', 'parent-theme' ),`
`            'option-3'             => __( 'Option 3', 'parent-theme' ),`
`            'option-4'             => __( 'Option 4', 'parent-theme' ),`
`            'option-5'             => __( 'Option 5', 'parent-theme' ),`
`        ),`
`) );`

**Comment by aristath** [comment]
You can use a filter.

Parent theme:

```php
Kirki::add_field( 'parent-theme', array(
        'type'              => 'sortable',
        'settings'          => 'my_setting',
        'label'             => __( 'Sortable', 'parent-theme' ),
        'section'           => 'my_section',
        'priority'          => 1,
        'default'           => array(
            'option-1',
            'option-2',
        ),
        'choices'           => apply_filters( 'my_custom_parent_theme_my_settings', array(
            'option-1'             => __( 'Option 1', 'parent-theme' ),
            'option-2'             => __( 'Option 2', 'parent-theme' ),
            'option-3'             => __( 'Option 3', 'parent-theme' ),
        ) ),
) );
```

Child theme:

```php
function my_custom_child_theme_my_settings( $choices ) {
    $choices['option-4'] = __( 'Option 4', 'parent-theme' );
    $choices['option-5'] = __( 'Option 5', 'parent-theme' );
    return $choices;
}
add_filter( 'my_custom_parent_theme_my_settings', 'my_custom_child_theme_my_settings' );
```
