### ISSUE TITLE
Selective refreshes not working with repeater field 

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#1264]
### Issue description:
Selective refreshes not working with repeater field 

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Development version 

### Using theme_mods or options?

theme_mods

**Comment by tivnet** [comment]
Same as https://github.com/aristath/kirki/issues/1227 ?

**Comment by aristath** [comment]
Closing as a duplicate of #1227 

This is still a work in progress, repeater fields are a bit more complicated than others
