### ISSUE TITLE
Hi! Can I add available variants for my custom font?

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1265]
### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by aristath** [comment]
You could try something like this:

```php
apply_filters( 'kirki/fonts/google_fonts', function( $google_fonts ) {

	$my_custom_fonts = array(
		'Font Name' => array(
			'label'    => 'Font Name',
			'variants' => array(
				'100',
				'200',
				'400',
				'800',
			),
			'subsets'  => array(
				'cyrillic'     => 'Cyrillic',
				'cyrillic-ext' => 'Cyrillic Extended',
				'devanagari'   => 'Devanagari',
				'greek'        => 'Greek',
				'greek-ext'    => 'Greek Extended',
				'khmer'        => 'Khmer',
				'latin'        => 'Latin',
			),
			'category' => 'sans-serif',
		),
	);

	return array_merge_recursive( $my_custom_fonts, $google_fonts );
});
```

I haven't tested it but I think that might work

**Comment by vlthemes** [comment]
It`s not working :(

**Comment by vlthemes** [comment]
```
public function typekit_add_to_kirki(){

			if($this->typekit_enable && !empty($this->_typekit_id)){

				$typekit_fonts = trim($this->typekit_fonts, ' ');
				$typekit_fonts = explode(',', $typekit_fonts);
				
				foreach($typekit_fonts as $font => $value) {

					$fonts[$value] = array(
						'label' => $value,
						'stack' => $value . self::$fonts_sep . self::$typekit_subfont,
					);

				}

				return $fonts;

				add_filter('kirki/fonts/standard_fonts', array($this, 'typekit_add_to_kirki'));

			}
		}
```

But I have 4 default variants instead of all.

**Comment by aristath** [comment]
standard fonts don't have variants as they are basically the system fonts.
That's why I suggested using the `kirki/fonts/google_fonts` filter above with an example of how the array is formatted

**Comment by vlthemes** [comment]
Thank you so much!

**Comment by aristath** [comment]
I assume this has been resolved so I'm closing this ticket.
If you need further assistance with this feel free to reopen it 😄

**Comment by vlthemes** [comment]
Hi!
After that i hove another errors http://take.ms/j5J7P

I used this code https://github.com/vlthemes/VLThemes-Add-Typekit-fonts-to-Kirki/blob/master/ClassVlthemesAddTypekit.php

NOTICE: wp-includes/functions.php:4139 - wp_add_inline_style was called incorrectly. Do not pass <style> tags to wp_add_inline_style(). Please see Debugging in WordPress for more information. (This message was added in version 3.7.0.)
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/osmos/index.php'), get_header, locate_template, load_template, require_once('/themes/osmos/header.php'), wp_head, do_action('wp_head'), WP_Hook->do_action, WP_Hook->apply_filters, wp_enqueue_scripts, do_action('wp_enqueue_scripts'), WP_Hook->do_action, WP_Hook->apply_filters, Kirki_Modules_Webfonts_Embed->inline_css, wp_add_inline_style, _doing_it_wrong, trigger_error

**Comment by aristath** [comment]
Try adding this:

```php
add_filter( 'kirki/googlefonts_load_method', function( $method ) {
    return 'link';
});
```

**Comment by vlthemes** [comment]
It works, but not quite
http://take.ms/5CIFs

**Comment by aristath** [comment]
I'm unable to test your custom-coded implementation because I'm missing the rest of the theme which adds some typekit constants and functions that are required in your implementation.
Can you send your complete theme so that i may replicate and see what goes wrong?

**Comment by vlthemes** [comment]
Please send me any message and I'll send full theme to this email.

plafon89@gmail.com

**Comment by aristath** [comment]
This will require a refactor that's scheduled for version 3.1: #1364 
Right now, if you use the `kirki/fonts/google_fonts` Kirki will try to generate a link to get the font using the google-API which throws an error because the font doesn't exist in google, and if you use the `kirki/fonts/standard_fonts` filter, variants are pretty much standard and can't be affected.

I'm sorry but right now it isn't easy to accomplish unless you custom-implement this and completely bypass the typography controls.

**Comment by steve231293** [comment]
Hello @aristath,

Have you added this feature to latest Kirki yet?

is there any ways to select varation of custom fonts in Customizer?

I have used Kirki 3.1.9

Thanks in advanced.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
