### ISSUE TITLE
Post Select Field

### ISSUE THREAD

**Issue by coleh33** [themeum/kirki#1266]
Does KIRKI have any way to do a post select without it being a normal dropdown?  The issue with a normal select field is if you have thousands of posts it would be easier to click on a text input and start typing the post title and then enter after the post is found.  I have created a custom customizer control for this but I need it to work in a repeater field which is not supported yet with Kirki.  I was hoping I may have overlooked the documentation and that this was already possible? 

I noticed the selectize library being used has some similar types in there demo.

http://selectize.github.io/selectize.js/

The main goal is to allow the user to select posts from the website to feature somewhere and need a way to handle the possibility of there being a lot of posts that are being queried.

**Comment by aristath** [comment]
Hey there!

You can use the `Kirki_Helper::get_posts()` method.
That method will accept the same arguments as the [`get_posts`](https://codex.wordpress.org/Template_Tags/get_posts) core WP function and will return posts formatted as an array: `array( post_id => post_title )` so you can easily use it in any field you want.

**Comment by jasonbahl** [comment]
It would be nice if the Autocomplete actually searched posts as you type instead of being pre-populated with just a set of xx amount of posts from the `Kirki_Helper::get_posts()` method. 

Might have to explore making a new control that behaves that way. 🤔
