### ISSUE TITLE
Select Field in Repeater ?

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1268]
### Issue description:

Hello, I just want to know that is select field can work in repeater ? i have used but its not working fine. please help how to use select field in repeater.
### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.7
### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please elaborate? What exactly is not working?
Can you also test if this works with the development version from this repository?

**Comment by ghost** [comment]
'type'        => 'repeater',
			'label'       => 'Social Links',
			'section'     => 'social_links',
			'priority'    => 10,
			'row_label' => array(
				'type'  => 'field',
				'field' => 'social_text',
			),
                        'default'=>array(
                                                 array('social_text'=>'facebook'),
                                                array('social_text'=>'twitter')
                                        ),
			'settings'    => 'social_links',
			'fields' => array(
				'social_text' => array(
					'type'		=> 'select',
					'choices' 	=> array(
						''				=> 'Please Select',,
						'facebook'		=> 'Facebook',
						'twitter'		        => 'Twitter',
						'linkedin'		        => 'Linked In',
					)
				),
			)



when i m using this code in add_field function this will create repeater field and select box options in it and add new row button appears but there is no default field created for facebook and twitter as per this code i think it should. please point my mistake if i m doing any. also i did not check it on development branch yet. i m working on ver 2.3.7. please help. thanks in advance.

**Comment by ghost** [comment]
@aristath what about this issue ?

**Comment by aristath** [comment]
I just tested using the following code and it seems to be working fine:

```php
<?php

Kirki::add_field( 'kirki_demo', array(
	'type'        => 'repeater',
	'label'       => esc_attr__( 'Repeater Control', 'my_textdomain' ),
	'section'     => 'repeater',
	'priority'    => 10,
	'row_label' => array(
		'type' => 'text',
		'value' => esc_attr__('your custom value', 'my_textdomain' ),
	),
	'settings'    => 'my_setting',
	'default'     => array(
		array(
			'link_text' => esc_attr__( 'Kirki Site', 'my_textdomain' ),
			'link_url'  => 'https://aristath.github.io/kirki/',
			'social_text' => 'facebook',
		),
		array(
			'link_text' => esc_attr__( 'Kirki Repository', 'my_textdomain' ),
			'link_url'  => 'https://github.com/aristath/kirki',
			'social_text' => 'twitter',
		),
	),
	'fields' => array(
		'link_text' => array(
			'type'        => 'text',
			'label'       => esc_attr__( 'Link Text', 'my_textdomain' ),
			'description' => esc_attr__( 'This will be the label for your link', 'my_textdomain' ),
			'default'     => '',
		),
		'link_url' => array(
			'type'        => 'text',
			'label'       => esc_attr__( 'Link URL', 'my_textdomain' ),
			'description' => esc_attr__( 'This will be the link URL', 'my_textdomain' ),
			'default'     => '',
		),
		'social_text' => array(
			'type'		=> 'select',
			'choices' 	=> array(
				''				=> 'Please Select',
				'facebook'		=> 'Facebook',
				'twitter'		        => 'Twitter',
				'linkedin'		        => 'Linked In',
			),
			'default' => 'facebook',
		),
	),
) );
```

Please test the development branch and see if this has already been resolved.
