### ISSUE TITLE
Use an autoloader

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#127]

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/d93e378bfe528a3d0c4a766dddf73481038959ee

**Comment by ghost** [comment]
Hi Aris,

What is this function "Autoloader"?

**Comment by aristath** [comment]
Hey there!

The autoloader automatically detects the file where a class exists and it includes that file when the class is required.

For example without an autoloader, you'd have to do this:

``` php
<?php
include 'MyClass.php';
$my_class = new MyClass();
?>
```

However, with an autoloader you can do this:

``` php
<?php $my_class = new MyClass(); ?>
```

and PHP will automatically include the file for you. 
More info can be found on http://php.net/manual/en/function.spl-autoload-register.php :smile:
