### ISSUE TITLE
active_callback not working in 2.3.7

### ISSUE THREAD

**Issue by dtmgs** [themeum/kirki#1273]
###  'active_callback' not working?

`	Kirki::add_config( 'my_config', array(
	    'capability'    => 'edit_theme_options',
	    'option_type'   => 'theme_mod',
	) );

	Kirki::add_panel( 'panel_1', array(
		'title'       => __( 'Panel 1', 'textdomain' ),
	) );

	# Section 6
	Kirki::add_section( 'dt_section_6', array(
		'title'          => __( 'Section 6' ),
		'capability'     => 'edit_theme_options',
		'panel' 		 => 'panel_1'
	) );

		Kirki::add_field( 'my_config', array(
			'type'        => 'select',
			'settings'    => 'my_select_1',
			'label'       => __( 'Select 1', 'my_textdomain' ),
			'section'     => 'dt_section_6',
			'default'     => 'option-1',
			'priority'    => 10,
			'multiple'    => 1,
			'choices'     => array(
				'option-1' => esc_attr__( 'Option 1', 'my_textdomain' ),
				'option-2' => esc_attr__( 'Option 2', 'my_textdomain' ),
				'option-3' => esc_attr__( 'Option 3', 'my_textdomain' ),
				'option-4' => esc_attr__( 'Option 4', 'my_textdomain' ),
			),
		) );	

		Kirki::add_field( 'my_config', array(
				'type'     => 'text',
				'settings' => 'my_text_8',
				'label'    => __( 'Text 8', 'my_textdomain' ),
				'section'  => 'dt_section_6',
				'required' => array(
					array( 'setting' => 'my_select_1', 'operator' => '==', 'value' => 'option-2' )
				)
		) );`

**Comment by aristath** [comment]
Hey there!

Can you please try the version from this repository (develop branch) and let me know if that works for you?

**Comment by dtmgs** [comment]
Hey there,

No luck with kirki-develop version 2.4.0-beta.2 :(

**Comment by sethstha** [comment]
In title you have mentioned `active_callback` while you are using `required` argument.

Try this

```
Kirki::add_panel( 'panel_1', array(
	'title'       => __( 'Panel 1', 'textdomain' ),
) );

# Section 6
Kirki::add_section( 'dt_section_6', array(
	'title'          => __( 'Section 6' ),
	'capability'     => 'edit_theme_options',
	'panel' 		 => 'panel_1'
) );

Kirki::add_field( 'my_config', array(
	'type'        => 'select',
	'settings'    => 'my_select_1',
	'label'       => __( 'Select 1', 'my_textdomain' ),
	'section'     => 'dt_section_6',
	'default'     => 'option-1',
	'priority'    => 10,
	'multiple'    => 1,
	'choices'     => array(
		'option-1' => esc_attr__( 'Option 1', 'my_textdomain' ),
		'option-2' => esc_attr__( 'Option 2', 'my_textdomain' ),
		'option-3' => esc_attr__( 'Option 3', 'my_textdomain' ),
		'option-4' => esc_attr__( 'Option 4', 'my_textdomain' ),
	),
) );	

Kirki::add_field( 'my_config', array(
	'type'     => 'text',
	'settings' => 'my_text_8',
	'label'    => __( 'Text 8', 'my_textdomain' ),
	'section'  => 'dt_section_6',
	'active_callback' => array(
		array( 
			'setting' 	=> 'my_select_1', 
			'value' 	=> 'option-2',
			'operator' 	=> '==', 
		),
	),
) );
```

**Comment by dtmgs** [comment]
Hi sethstha ,

Not working :)

http://recordit.co/hokF3BRMtz

**Comment by sethstha** [comment]
@dtmgs Seems like javascript is not working on your side.

Basically, What kirki does is adds `display: none` by default and when selected provided value it adds `display: block`.

Check your console if it is throwing any error.

Have a look at here, it is working for me.

http://recordit.co/T6DFlw4AHl

**Comment by dtmgs** [comment]
:+1:

**Comment by aristath** [comment]
@dtmgs has this been resolved? Or is it still an issue?

**Comment by dtmgs** [comment]
@aristath Resolved!

**Comment by aristath** [comment]
Thanks for the update!
Closing this one 👍
