### ISSUE TITLE
Issue output with type cropped_image

### ISSUE THREAD

**Issue by notrealdev** [themeum/kirki#1276]
### Issue description:
Hi, I'm having a problem with `'type' => 'cropped_image'`.

With `'type' => 'image',` `output` working well:
```
'output'     => array(
	array(
		'element' => '.main nav',
		'function' => 'css',
		'property' => 'background-image',
	)
),
```
Output on website:
`    background-image: url(http://mywebsite.com/url-image.png);`

BUT ==== with `'type' => 'cropped_image',` `output` have trouble:
```
'output'     => array(
	array(
		'element' => '.main nav',
		'function' => 'css',
		'property' => 'background-image',
		'postfix'   => 'url(',
        	'suffix'    => ')',
	)
),
```
Output on website:
`    background-image: url(555);`

### Version used:
2.3.7

**Comment by notrealdev** [comment]
Hey @aristath , can you take a look at this issue?

**Comment by notrealdev** [comment]
I tried plugin DEV version, it working well.
When will the new version be updated?

**Comment by aristath** [comment]
@xttn the more people that test the develop version and report any issues & bugs you find, the sooner we'll be able to release it 👍
