### ISSUE TITLE
Control not showing in custom section (widget) 

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#1277]
### Issue description:
When I add control into custom section like widgets . It was not showing and i see in the browser code  have inline style 
```
element {
    display: none;
}

```
### Version used:
development version 

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
jQuery(document).ready(function() {
	/* Move  widgets */

	wp.customize.section( 'sidebar-widgets-sidebar_frontpage' ).panel( 'theme_options' );
	wp.customize.section( 'sidebar-widgets-sidebar_frontpage' ).priority( '5' );

});
```

```
Kirki::add_field( 'advance', array(
    'type'        => 'toggle',
    'settings'    => 'advance_header_checkbox',
    'label'       => esc_attr__( 'Disable Transparent Header ', 'advance' ),
    'section'     => 'sidebar-widgets-sidebar_frontpage',
    'default'     => '1',
    'priority'    => 10,
) );
```

![screen shot 2017-03-13 at 5 43 56 pm](https://cloud.githubusercontent.com/assets/10571385/23853120/67fb8c6e-0815-11e7-8cfa-9d0b5b8ea7f2.png)

**Comment by Imonthemes** [comment]
Hello any suggestion on this issue ?

**Comment by aristath** [comment]
to be honest I still don't understand what you're trying to do...

**Comment by Imonthemes** [comment]
Ok i try to explain again 

register widgets area into my theme :
	
```
register_sidebar(array(
				'name'          => __('Contact Section ', 'promote-pro'),
				'id'            => 'sidebar-contact',
				'before_widget' => '<div id="%1$s" class="widget %2$s" data-widget-id="%1$s">',
				'after_widget'  => '</div>',
				'before_title'  => '<h3 class="widgettitle">',
				'after_title'   => '</h3>'
																));
```


Add a section into customizer for this widgets area or move widgets  area into this section 

```
if ( ! empty( $our_client_section ) ) {
			$our_client_section->panel = 'theme_options';
			$our_client_section->title   = __( 'Client section', 'promote-pro' );
			$our_client_section->priority = 8;
			}
$contact_section = $wp_customize->get_section( 'sidebar-widgets-sidebar-contact' );
			if ( ! empty( $contact_section ) ) {
					$contact_section->panel = 'theme_options';
					$contact_section->title   = __( 'Contact section', 'promote-pro' );
					$contact_section->priority = 8;
					}
```

Now I am trying add some kirki fields into this section 

```
Kirki::add_field( 'promote-pro', array(
				'type'        => 'checkbox',
				'settings'    => 'promote_contactfixed_image',
				'label'       => __( 'Disable parallax effect', 'promote-pro' ),
				'section'     => 'sidebar-widgets-sidebar-contact',
				'default'     => '1',
				'priority'    => 10,


			) );

```
But kirki fields are not showing in this section or if you try to add any kirki fields into customize core section like background color or header it also not working 

Kikir fields auto add `display:none` inline code for those fields 


Thank you

**Comment by aristath** [comment]
Does this work if you use the default WordPress API to add fields instead of using Kirki?
I'm not sure WordPress Core allows adding custom controls in widget sections...

When using simple fields like checkboxes, Kirki acts as a simple proxy between your code and the WP-Core API.
To see if this is an issue with Kirki or if this is something that WP simply doesn't currently allow like this, try replacing this code:

```php
Kirki::add_field( 'promote-pro', array(
	'type'        => 'checkbox',
	'settings'    => 'promote_contactfixed_image',
	'label'       => __( 'Disable parallax effect', 'promote-pro' ),
	'section'     => 'sidebar-widgets-sidebar-contact',
	'default'     => '1',
	'priority'    => 10,
) );
```
with this:

```php
add_action( 'customize_register', function( $wp_customize ) {

	// Register the settings
	$wp_customize->add_setting( 'promote_contactfixed_image', array(
		'default'        => 1,
		'type'           => 'theme_mod',
		'capability'     => 'edit_theme_options',
	) );

	// Add the controls
	$wp_customize->add_control( 'my_setting', array(
		'label'       => __( 'Disable parallax effect', 'promote-pro' ),
		'section'     => 'sidebar-widgets-sidebar-contact',
		'settings'    => 'promote_contactfixed_image',
		'type'        => 'checkbox',
		'priority'    => 10,
    ) );	
} );
```

**Comment by Imonthemes** [comment]
Ohh !! it is not working if i using default customize API . You can close it 

By the way can you please tell me how i can use cropped_image ? and how can i control cropped_image size ?

Thanks

**Comment by aristath** [comment]
Kirki doesn't include a `cropped_image` control so if you use it, Kirki will simply act as a  proxy and your arguments will be passed-on to the WordPress API. For an example of what arguments that control accepts you can see https://make.wordpress.org/core/2015/07/16/new-customizer-media-controls-in-4-3-and-4-2/
