### ISSUE TITLE
How not to escape html code with sanitize_callback

### ISSUE THREAD

**Issue by Hujjat** [themeum/kirki#1279]
###  version 2.3.6
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### my code
`
function do_not_filter_anything( $value ) {
	return $value;
}
`

`

    $fields[] = array(
		'type'     => 'textarea',
		'settings' => 'copy_right',
		'label'    => __( 'Footer Copyright Note', 'upplanet' ),
		'section'  => 'footer_options',
		'default'  => "something",
		'priority' => 10,
		'sanitize_callback' => 'do_not_filter_anything',

	);

`

I use to use this method and it was working just fine. But the recent versions. it's not working. It's displaying the html code as it is. 

Thank's :)

**Comment by rahulv3a** [comment]
You can use `wp_kses_post` as `sanitize_callback` in this case. It sanitizes content for allowed HTML tags for post content.

**Comment by aristath** [comment]
@Hujjat is that in version 2.3.7, or the dev version from this repository?

**Comment by aristath** [comment]
You may wan to use [htmlentities](http://php.net/manual/en/function.htmlentities.php) too when outputing the HTML... that depends completely on your current implementation.
