### ISSUE TITLE
Active callback in the Repeater control

### ISSUE THREAD

**Issue by VladNov** [themeum/kirki#1280]
### Issue description: 
Active callback does not work in the Repeater control

### Version used: 2.3.7
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Tried the develop branch, but plugin could not be activated and return this message: "The plugin does not have a valid header."

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Regular active_callback argument.

**Comment by aristath** [comment]
Can you please post the code for your callback function here?

**Comment by VladNov** [comment]
Sure. I have two selects, "select_one" and "select_two", inside the repeater control . Second select have the active_callback argument which is called when the option "two" is selected in the first select. I just now see that maybe the repeater fields names are not considered as setting and therefor is does not work.

```
Kirki::add_field( 'my_config', array(
    'type'       => 'repeater',
    'label'      => esc_attr__( 'Repeater Control', 'my_textdomain' ),
    'section'    => 'my_section',
    'priority'   => 10,
    'row_label'  => array(
        'type'  => 'field',
        'value' => esc_attr__( 'custom text', 'my_textdomain' ),
        'field' => 'section_one',
    ),
    'settings'    => 'my_setting',
    'fields' => array(
        'select_one' => array(
            'type'        => 'select',
            'label'       => esc_attr__( 'Title 1', 'my_textdomain' ),
            'default'     => 'one',
            'choices'     => array(
                'one'   => esc_attr__( 'One', 'my_textdomain' ),
                'two'   => esc_attr__( 'Two', 'my_textdomain' ),
                'three' => esc_attr__( 'Three', 'my_textdomain' ),
            ),
        ),
        'select_two' => array(
            'type'        => 'select',
            'label'       => esc_attr__( 'Title 2', 'my_textdomain' ),
            'default'     => 'columns',
            'choices'     => array(
                'four' => esc_attr__( 'Four', 'my_textdomain' ),
                'five' => esc_attr__( 'Five', 'my_textdomain' ),
                'six'  => esc_attr__( 'Six', 'my_textdomain' ),
            ),
            'active_callback'    => array(
                array(
                    'setting'  => 'select_one',
                    'operator' => '==',
                    'value'    => 'two',
                ),
            )
        )
    ),
) );
```

**Comment by aristath** [comment]
ok, now I understand what you mean.

You want to hide a field inside a row in the repeater depending on the value of another field inside the same row of the same repeater control?
If this is what you want then I'm afraid it's not currently supported.
You can hide the repeater field (the whole repeater, not subfields selectively) depending on the value of another field (not a sub-field) if you want, but nested fields can't control - or be controlled.

**Comment by VladNov** [comment]
Thank you. Maybe you can consider this feature in the future.

**Comment by BenceSzalai** [comment]
Has this been implemented since maybe?

**Comment by aristath** [comment]
Not yet, this will be implemented after v3.1 as it requires a significant rewrite of some oartsbof the code.

**Comment by Oxibug** [comment]
Hey Guys,

I've solved the active_callback inside repeaters and upload the solution in the request **https://github.com/kirki-framework/kirki/pull/2368**

Go to files has changed https://github.com/kirki-framework/kirki/pull/2368/files and replace in your Kirki files, You can see the files' paths from the top

If you urgently need it, DO NOT Forget to change your Kirki version to prevent from automatic update until the commit approved.

Hope it helps :)

**Comment by Oxibug** [comment]
@VladNov @BenceSzalai 
Hey Guys, 

A new commit to enable active_callback in the newer version 4.x.x is available here https://github.com/kirki-framework/kirki/pull/2468

Best,
