### ISSUE TITLE
Combining Multiple Taxonomies In Select Field

### ISSUE THREAD

**Issue by coleh33** [themeum/kirki#1281]
Is there a way to combine multiple taxonomies in a select field?  I would like both categories and tribe events categories to display.  I've tried the various ways below.

`'choices'     => Kirki_Helper::get_terms( array('taxonomy' => array( 'category', 'tribe_events_cat'  ) ) ),`

`'choices'     => Kirki_Helper::get_terms( array('taxonomy' => 'category tribe_events_cat' ) ),`

`'choices'     => Kirki_Helper::get_terms( array('taxonomy' => 'category' ), array('taxonomy' => 'tribe_events_cat' ) ),`

**Comment by aristath** [comment]
[`Kirki_Helper::get_terms()`](https://github.com/aristath/kirki/blob/2.4.0-beta.2/core/class-kirki-helper.php#L217-L231) internally uses [`get_terms()`](https://developer.wordpress.org/reference/functions/get_terms/) so it should work using an array in `taxonomy`... all `Kirki_Helper::get_terms` does is simply format the array so it's easier to process in the customizer.

If you use `'choices' => Kirki_Helper::get_terms( array( 'taxonomy' => 'tribe_events_cat' ) ),` do you get the events categories?
If not then it's probably a timing issue. Perhaps you're trying to retrieve to terms before the taxonomy is registered?
If you're getting the terms with the above but not using an array then this makes no sense and I'll have to dig deeper

**Comment by coleh33** [comment]
The categories are not showing up with just `tribe_events_cat`.  We were able to get the terms in the normal customizer functions before switching to Kirki on a similar type of taxonomy select field.

However, the function being used in that custom control was `get_categories()` rather than `get_terms()`.

**Comment by aristath** [comment]
From what I can see in the events-calendar plugin, the taxonomy is registered on `init` with a priority of 10.

So try wrapping that field in a function that will be loaded on init like this:

```php
function my_theme_add_events_categories_customizer_control() {
   Kirki::add_field(.....);
}
add_action( 'init', 'my_theme_add_events_categories_customizer_control', 12 );
```
Note that the priority defined above is 12 so that it loads after the taxonomy has been defined.

Let me know if that works!

**Comment by coleh33** [comment]
That fixed the issue.  Thank you.
