### ISSUE TITLE
Customiser options disappear if too many items in section

### ISSUE THREAD

**Issue by michelle-may** [themeum/kirki#1285]
### Issue description:
If there are enough controls within an accordion section (about 95% of the height) of the customiser, the content disappears. If I zoom out on the browser, it'll reappear. 

This _has_ been addressed in the dev branch (I've tested and this problem does not occur) but I want to know if there is anything I can do to fix it from within my theme. I don't want to package the plugin with my theme, I'd rather the user keep it updated via the WP site but currently this issue is rendering parts of my theme customizer unusable.

**Comment by aristath** [comment]
@macaroons Most likely this is a CSS issue...
A lot has changed in the develop version so there's really no way for me to know exactly what goes on in your case as I was unable to replicate this locally.
If you can't debug this on your theme and find a quick fix, testing the develop version and reporting any bugs you find would help us get things fixed sooner and release version 3.0 which will fix - among other things - your issue as well
