### ISSUE TITLE
Customize does not load if woocommerce plugin activated

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1288]
### Issue description:
I have added some fields using kirki in customize. they works fine, when i deactivate woocommerce plugin but when i activate woocommerce plugin, customize does not load properly. Seems compatibility issue with woocommerce  plugin. also when i deactivate kirki and activate woocommerce then load customize, it load customize properly.

Web Console / JavaScript Error: Option 'data' is not allowed for Select2 when attached to a <select> element.

woocommerce  Version 2.6.14

### Version used:
3.0.0-alpha.1

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
---

**Comment by aristath** [comment]
Can you please try this using the WooCommerce version from github?
Kirki won't be released before WooCommerce 3.0 so all my test are done against the development version of WC

**Comment by rinkuyadav999** [comment]
If so, it should not an issue.
