### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#1290]
### Issue description:
After activating dev branch get this error:
Fatal error: Cannot make static method Kirki_Field_Number::sanitize() non static in class Kirki_Field_Spacing in C:\...\wp-content\plugins\akirki-develop\field\class-kirki-field-spacing.php on line 15

Spacing field generates this error.
### Version used:
develop branch from github - Version 3.0.0-alpha.1

### Using theme_mods or options?
theme_mods 

### Code to reproduce the issue (config + field(s))
`Kirki::add_field( 'my_settings', array(
	'type'		 => 'spacing',
	'settings'	 => 'logo_spacing',
	'label'		 => __( 'Logo/Title Spacing', 'my-theme' ),
	'section'	 => 'layout_section',
	'default'	 => array(
		'top'	 => '0px',
		'right'	 => '15px',
		'bottom' => '0px',
		'left'	 => '15px',
	),
	'output'	 => array(
		array(
			'element'	 => '.rsrc-header',
			'property'	 => 'padding',
		),
	),
) );`

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/11ecd65388674050a8531f4f8b346e91a65bf1f5
