### ISSUE TITLE
Issue with editor in fullscreen

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1293]
### Issue description:

I'm just testing the latest dev version here. 
There´s a small bug in the editor field, when we click on the fullscreen button the editor goes fullscreen as expected but it stays behind the customizer panel.
Seems like just a z-index issue.

### Version used:
Using the develop branch

### Using theme_mods or options?
 theme_mods

### Code to reproduce the issue (config + field(s))

----

Thanks for your great work!

**Comment by aristath** [comment]
great find... fixed. 👍
