### ISSUE TITLE
drop-down page control in repeater control have js error in Development version 

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#1294]
### Issue description:
drop-down page control well in 2.3.7 but in Development version it produce js error when i am using
drop-down page control in  repeater

```
TypeError: Cannot read property 'dropdown_pages' of undefined
 /101/wp-content/themes/promote-pro/inc/kirki/controls/repeater/repeater.js?ver=4.7.3:888
```

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Development
### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
fixed
