### ISSUE TITLE
Typography field requires backspace to get search working

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1296]
### Issue description:
Hey there,

it's kind of confusing that you have to first hit backspace before you can start typing and searching through font families in the typography field. It would be great if people could just start typing so it replaces the font family and filters directly.

### Version used:
development

**Comment by aristath** [comment]
Are you sure you tested the develop branch?
This has already been fixed.

**Comment by mapsteps** [comment]
Hey @aristath,

figured i wasn't using the very latest dev version. Works just fine!

Thanks!
