### ISSUE TITLE
kirki enqueues google font even if it's not in use

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1297]
### Issue description:
Hey there,

I use Roboto as the default font for the typography fields. Users are able to switch on typography options (with a toggle field) though. I'd like to prevent kirki loading the default google font if it's not actually in use. I think a workaround would be to check if one of the typography fields exists - and if not dequeue the font by myself. Not sure how complex it would be to do a check like this by default.

Great work btw! 

### Version used:
development

**Comment by aristath** [comment]
You mean you have a setting that users can enable if they want to enable google fonts?
If that's the case, then you could disable google fonts when the checkbox is disabled by doing something similar to this:

```php
if ( false === get_theme_mod( 'my_checkbox' ) ) {
    add_filter( 'kirki/enqueue_google_fonts', '__return_empty_array' );
}
```

**Comment by mapsteps** [comment]
Exactly what I was looking for, thanks! Keep up the great work!
