### ISSUE TITLE
Color Control's Clear Action Not Working

### ISSUE THREAD

**Issue by dtmgs** [themeum/kirki#1299]
### Clear Button in Color Control Not Working

**Here is my control**

```php
Kirki::add_section( 'dt_skin_sction', array(
	'title' => 'Site Colors'
) );

Kirki::add_field( $config, array(
	'type' => 'color',
	'settings' => 'bg-color',
	'label'    => 'Background Color',
	'section'  => 'dt_skin_sction',
	'choices' => array( 'alpha' => true ),
	'output' => array(
		array( 'element' => 'body',   'property' => 'background-color')
	)
));
```

**Explanation**
We're facing an issue with the color picker, whereas we can select and change any color which applies normally. But when we want to remove the selected color by using the "**clear**" option, it doesn't reflect any changes, instead it stays with the last selected color thereby.

Please have a look at the example given below, for the better understanding..

### [Watch Video](http://recordit.co/oVwXWs7y6b)

**Comment by aristath** [comment]
fixed in develop branch, will be included in version 3.0 👍
