### ISSUE TITLE
Add new font to typography 

### ISSUE THREAD

**Issue by dylan-ngo11** [themeum/kirki#1304]
### Issue description:
Hi! Are there any ways to add a new font that's outside Google font to Typography?

Thanks!

**Comment by aristath** [comment]
You can use the `kirki/fonts/standard_fonts` and `kirki/fonts/google_fonts` filters. You can see how these are formatted in the https://github.com/aristath/kirki/blob/97838ccf27dd0b9a88070ca067e8d0fcb080b75d/controls/typography/class-kirki-control-typography.php file 👍
