### ISSUE TITLE
Disable output

### ISSUE THREAD

**Issue by 2one2** [themeum/kirki#1305]
### Issue description:
Hi,

when ```'disable_output' => true``` css still loads.

I think the problem is in class-kirki-modules-css.php
line 100

```
// Allow completely disabling Kirki CSS output.
if ( ( defined( 'KIRKI_NO_OUTPUT' ) && KIRKI_NO_OUTPUT ) || ( isset( $config['disable_output'] ) && true !== $config['disable_output'] ) ) {
	return;
}
```

```true !== $config['disable_output']```

should be

```true === $config['disable_output']```

### Version used:
develop branch

### Using theme_mods or options?
theme_mods

**Comment by 2one2** [comment]
Just tried that and it doesn't work.
Maybe I'm doing something wrong...

**Comment by aristath** [comment]
You're right, there was an error on that line. I just pushed a fix for that.

This seems to be working fine:
```php
add_filter( 'kirki/config', function( $config ) {
	$config['disable_output'] = true;
	return $config;
});
```

As well as adding this line:
```php
if ( ! defined( 'KIRKI_NO_OUTPUT' ) ) {
	define( 'KIRKI_NO_OUTPUT', true );
}
```

Both ways are valid, it's just a matter of preference

**Comment by 2one2** [comment]
Works !

Thank You
