### ISSUE TITLE
Bug in integrating Kirki in theme

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1306]
### Issue description:
Can´t use Kirki integrated in a theme. Most of the controls don't appear. Seems like a CSS path issue.
If i use Kirki as a plugin everything works fine.

### Version used:
Latest dev version  3.0.0-beta.1

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
...

**Comment by aristath** [comment]
Fixed.
The problem was when Kirki existed as a plugin but was not activated. Extra checks were added and now it seems to be working fine :+1:
