### ISSUE TITLE
Bug in code field

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1307]
### Issue description:
Don’t know if its a bug or if i’m doing something wrong.
The code field seems to ignore the height option in choices.
No matter what height i choose it's ignored.

Please see image attached.

### Version used:
Latest dev version 3.0.0-beta.1

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'theme_prefix', array(
	'type'			=> 'code',
	'settings'		=> 'custom_css',
	'label'			=> __( 'Codes', 'theme_text_domain' ),
	'description'	=> __( 'Custom CSS', 'theme_text_domain' ),
	'section'		=> 'advanced',
	'default'		=> '/*body { background: #fff; }*/',
	'priority'		=> 10,
	'choices'     => array(
		'language' => 'css',
		'theme'    => 'monokai',
		'height'   => 50,
	),
));
```

![codes](https://cloud.githubusercontent.com/assets/6692380/25566729/3e61c78c-2dd7-11e7-960d-f8b803486fe0.png)

**Comment by aristath** [comment]
Caused by a recent update in the CodeMirror script. 
Fixed.

Thanks for testing, I really appreciate any issues you report. 👍
