### ISSUE TITLE
"Cheatin' uh?" message.

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1310]
### Issue description:
I´ve got this issue with Kirki when i access the customizer panel, change any setting and save & close, when i click on any link on my page i get this message:

![captura de ecra 2017-05-06 as 13 38 39](https://cloud.githubusercontent.com/assets/6692380/25772473/72ef3fc6-3263-11e7-8c8b-9a0a52738e4b.png)

Further more i noticed that immediately after saving and closing the customizer every link on the page have the suffix “&customize_changeset_uuid= …”  with the customizer already closed.

![link](https://cloud.githubusercontent.com/assets/6692380/25772480/8e8c27da-3263-11e7-8d79-50ee23b31818.jpg)

and i guess that’s why the error message appears.

That suffix also stays in the browser path bar. If i'm in my root url (www.mysite.com) and access the customizer after i change something and close it the path bar address is now "www.mysite.com/?customize_changeset_uuid=34bc8801-c3b6-4c20-8d68-ad8888f38da2"

If i erase that suffix from the path bar everything works fine.

Tested with my own custom theme and also with your _s theme with same results. 

### Version used:
dev version 3.0.0-beta.1

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
---

**Comment by aristath** [comment]
This has nothing to do with Kirki..
Recently changesets were implemented in the WP Core Customizer.
These "changesets" get deleted once published, so when you try to go to an already published changeset in the WP Customizer you get that message because it no longer exists.

**Comment by enginne** [comment]
I’m sorry to insist but i don’t know if i expressed myself right in the first place.


I´ve just made a fresh installation of WP with the current Kirki dev version and your _s theme and recorded a 20 second video of my issue, i would appreciate if you check it out.

[Video link](https://drive.google.com/file/d/0B2D2o4gyGjMHeXRQR0w0MWdBbnM/view?usp=sharing)

Please note how WP throws the error the second time i access the customizer.


The issue is reproduce like this: 
Access customizer -> change setting -> save & close -> access customizer again -> error


Doing this in a localhost.

**Comment by aristath** [comment]
As I said in my previous reply, this has nothing to do with Kirki.
This is default WP behaviour.
If you disable Kirki you'll still get the same results....

**Comment by enginne** [comment]
I disabled Kirki just to check if the behaviour is the same and.. it’s not. 
It’s works without any error message. As it always worked till ~2 weeks ago.

I enable Kirki and error comes again.

You can see it here with a clean WP install + your _s theme with kirki disabled.

[Video with Kirki disabled](https://drive.google.com/file/d/0B2D2o4gyGjMHOXBveDJCa1hubjg/view?usp=sharing)

[Video with Kirki enabled](https://drive.google.com/file/d/0B2D2o4gyGjMHeXRQR0w0MWdBbnM/view?usp=sharing)

From what i can see with Kirki **disabled** when i change a setting in the customizer (like color) a suffix is added to the browser bar url  (the ?customize_changeset_uuid=34bc8801-c3b6-4c2… ) and when i hit the save button that url suffix is removed. So when i close the panel the url in the browser path is the same as before i opened the panel.


When Kirki is **enabled** and a setting is changed that suffix is nor removed after i hit save and close the customizer panel. 
Thus the browser url is different after the panel is closed, and WP throws the error when trying to access the customizer panel again.


You can see this behavior in the videos in the browser path.


Maybe i'm expressing this issue with really bad English (i'm not native), and i’m sorry in advanced for it, but this cant be default behavior because i’m only getting this behavior from Kirki in the past week or two.

**Comment by aristath** [comment]
You're right, my bad. There's something wrong...
Reopened the issue, I'll try to figure this one out.
Thanks! 👍

**Comment by aristath** [comment]
Hey again!

I believe this was just fixed... At least in my tests it looks like this is working as expected now.
The issue was caused by a new feature that I was trying to add for collapsible fields (see #1187).

**Comment by enginne** [comment]
Just spend some time testing it.
So far so good.
Thanks

**Comment by aristath** [comment]
thanks for testing!!
