### ISSUE TITLE
Multicolor - Add Alpha Option?

### ISSUE THREAD

**Issue by bawright** [themeum/kirki#1321]
### Issue description:
Alpha (true/false) for multicolor control?

### Version used:
2.3.7

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'my_config', array(
    'type'        => 'multicolor',
    'settings'    => 'demo-multicolor',
    'label'       => __( 'Multicolor', 'text_domain' ),
    'section'     => 'demo',
    'priority'    => 10,
    'choices'     => array(
        'bg'        => __( 'Background', 'text_domain' ),
        'text'      => __( 'Text', 'text_domain' ),
    ),
    'default'     => array(
        'bg'        => '#000',
        'text'      => '#fff',
    ),
) );
```

**Comment by aristath** [comment]
@danielortiz was kind enough to submit a pull request that was just merged.
You can now set `'alpha' => true,` in your control.
Fix will be included in 3.0.9 when it is released.
