### ISSUE TITLE
Excessive escaping

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1330]
Hi,

With field examples you are escaping labels, descriptions, etc. 
E.g.
`'label'       => esc_attr__( 'My Control', 'my_textdomain' )`
`'option-1' => esc_attr__( 'Option 1', 'my_textdomain' )`

Source: https://aristath.github.io/kirki/docs/controls/multicheck.html

This seems as surplus, users cannot modify these strings. Also Poedit doesn't receive them at all when laid in this manner. Am I missing something?

**Comment by Slobork** [comment]
Poedit can receive that string, I just didn't have that keyword (esc_attr__) enrolled as a translatable string.
Still, is this excessive?

**Comment by aristath** [comment]
From the WordPress handbook on internationalizations: https://developer.wordpress.org/themes/functionality/internationalization/#escaping-strings

> It is good to escape all of your strings, preventing translators from running malicious code

That's why I try to escape everything... Not excessive, just following the guidelines and making sure everything is 100% secure. 👍
