### ISSUE TITLE
Fatal error when use active_callback

### ISSUE THREAD

**Issue by sophy** [themeum/kirki#1336]
When I use active_callback in my customize with message error below:
`Fatal error:  Uncaught Error: Call to a member function value() on null in path/kirki/core/class-kirki-active-callback.php:86
`

### Code to reproduce the issue (config + field(s))

```php
Theme_Slug_Kirki::add_field( 'theme_slug_conf', array(
	'settings' 			=> 'related_posts',
	'label'    			=> __( 'Enable Related Posts', 'theme-slug' ),
	'section'  			=> 'theme_slug_single',
	'type'     			=> 'switch',
	'default'     		=> 0,
	'priority' 			=> 40,
) );


Theme_slug_Kirki::add_field( 'theme_slug_conf', array(
	'settings' 			=> 'related_post_taxonomy',
	'label'    			=> __( 'Related Post Taxonomy', 'theme-slug' ),
	'section'  			=> 'theme_slug_single',
	'type'     			=> 'radio',
	'default'     		=> 'cat',
	'priority' 			=> 60,
	'choices'  			=> array(
                'cat' => esc_html__( 'Categories', 'theme-slug' ),
               'tag' => esc_html__( 'Tags', 'theme-slug' )
	),
	'active_callback'	=> array(
		array(
			'setting'  => 'related_posts',
			'operator' => '==',
			'value'    => '1'
			)
		)

) );
```

**Comment by sophy** [comment]
It is wrong from my config.

**Comment by sophy** [comment]
Sorry, I would like to reopen this issue again. Because it happens again when I change `option_type` from `option` to `theme_mod`.

```php
Theme_slug_Kirki::add_config( 'my_theme', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );
```

This error happens for both branch `develop` and stable branch `2.7.3`.

**Comment by aristath** [comment]
Hey there!

I just tested your code on a test theme and it seems to be working fine...
I can't replicate your issue (development branch).

Did you try deleting your theme_mods and options from your database?
While developing if you keep changing things, some values may not be what is expected. For example if you change a control type from something that saves a string to something that saves an array, the values in the database will be weird and not what the plugin is expecting.
If you're still having issues with this, can you post a link to your theme so I can download and test it?

**Comment by aristath** [comment]
Closing this for now, if it persists for you please reopen and post an update on your current status with as many details as possible.
