### ISSUE TITLE
Repeater add custom control

### ISSUE THREAD

**Issue by Micemade** [themeum/kirki#1337]
Hi,
is there a way to add custom controls to repeater ?
Thanks  ... :)

**Comment by aristath** [comment]
It depends on what you mean...
If by "custom control" do you mean a control that you have built on your own, then it's not currently possible to add that. 
This of the repeater field not as a wrapper for other controls, but as a wrapper for other input types. You can use these input types: `text`, `url`, `link`, `email`, `tel`, `date`, `hidden`, `checkbox`, `select`, `dropdown-pages`, `radio`, `radio-image`, `color`, `textarea`, `image`, `cropped_image`, `upload`, `custom`.

If by "custom control" you mean something similar to the "custom" control that Kirki already has (which outputs raw HTML) then you can use that without any issues and you HTML will be added.

**Comment by Micemade** [comment]
I meant, like custom field - I found some customizer scripts for adding FontAwesome ( or other iconfont libraries  ), and I would like to add it as one of repeater fields ...

**Comment by aristath** [comment]
I'm afraid you'd have to custom-code this, it's not currently available.
We have a `fontawesome` field outside the repeaters, but it's currently not supported inside a repeater.

**Comment by Micemade** [comment]
It's ok, I found and adapted a solution for that from here - https://github.com/cristian-ungureanu/customizer-repeater ( maybe you should check it ;) )
Thanks for your replies anyway ( and, off course, permanent thnx for Kirki :)  )

**Comment by aristath** [comment]
👍 I'm glad you found that!
