### ISSUE TITLE
PHP Error Notice: Array to string conversion.

### ISSUE THREAD

**Issue by briancwelch** [themeum/kirki#134]
_Notice: Array to string conversion in /srv/www/wordpress-default/wp-content/plugins/kirki/includes/styles/frontend.php on line 115_

`$styles[$element]['background-image'] = 'url("' . $bg_image . '")';`

Doesn't seem to have an effect on the page output, just the control.

Visual reference:
![capture](https://cloud.githubusercontent.com/assets/3002855/6885939/a92dc2b0-d5f9-11e4-90d6-b99e8d813b3a.PNG)

The above reference is when no image is set.

**Comment by aristath** [comment]
Somehow image controls don't get the default value properly....
If you hit "remove" there, the error goes away. It's just a matter of properly getting the default value.
I'm working on it. :)
