### ISSUE TITLE
Reset working on image field but not displaying the default image until Default button is pressed again

### ISSUE THREAD

**Issue by LebCit** [themeum/kirki#1345]
### Issue description:
Hello @aristath 
Everything is in the title.
I have this setting :
```
My_Theme_Kirki::add_field('mytheme', array(
    'type' => 'image',
    'settings' => 'default_header_background_image',
    'label' => __('Deafult Header Background Image', 'my-theme'),
    'section' => 'header_background_image',
    'default'  => get_template_directory_uri() . '/components/header/images/default-hero.jpg',
    'priority' => 5,
    'transport' => 'auto',
    'output' => array(
        array(
            'element' => '#masthead',
            'property' => 'background-image',
        ),
    ),
));
```
Everything is working as it should except the **Reset** button.
If I **Remove** the _default_ and press the **Reset** button, it will not display the _default_ image but the **No file selected** `div`. I have to press the **Default** button to see the _default_ image again.
### Version used:
2.3.8 WP repo

### Using theme_mods or options?
theme_mods

Thanks in advance for your time :)
SYA :)

**Comment by aristath** [comment]
The reset module was deprecated and removed in version 3.0.12.
WordPress 4.9 adds changesets and many improvements, and a reset feature is planned in the future for WordPress-Core so it makes no sense to keep a buggy implementation in Kirki.
