### ISSUE TITLE
PHP Error Warning: Scalar value as array.

### ISSUE THREAD

**Issue by briancwelch** [themeum/kirki#135]
Warning:  Cannot use a scalar value as an array in /srv/www/wordpress-default/wp-content/plugins/kirki/includes/scripts/customizer/required.php on line 60

https://github.com/aristath/kirki/blob/develop/includes/Scripts/Customizer/Required.php#L59-L61

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/e900e57
