### ISSUE TITLE
Plugin installed & activated but not appearing in Customizer

### ISSUE THREAD

**Issue by sgjopr** [themeum/kirki#1354]
### Version used: _2.3.8 with WordPress 4.7_
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) _I have looked through all the help forums._

**Comment by aristath** [comment]
@sgjopr I just tested the theme, it seems to be working fine for me...

If you see a "Google Fonts" section in the customizer for example, Kirki is enabled.

If you have support questions for the real-estate theme, I would advise you to post them in https://wordpress.org/support/theme/real-estate-lite.
I am not familiar with all the themes that use the kirki plugin, and though I can check if they properly implement the plugin (which seems to be fine in the case of this theme), if anyone can answer theme-specific questions it's the theme developers.
