### ISSUE TITLE
Getting chosen value in active_callback

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#1355]
Is it possible to get the chosen value in active_callback? I am trying to run a function depending on the selected value.

**Comment by aristath** [comment]
@sodbileg I don't quite understand what you're trying to do...

`active_callback` allows you to show/hide control A based on the values of control B.
If the visibility of control A depends on the value of control A, then once hidden it can't be revealed again since you won't be able to change the value of the that control since it will be hidden.

**Comment by minimaluminium** [comment]
Let's assume we have a `radio` field which has values `v1` and `v2`. When `v1` is selected, can I get this value in a callback function?

Something like,
```
'active_callback' => 'callback_function',
```
And,
```
function callback_function($chosen_value) {
  return $chosen_value;
}
```

What I'm trying to do is doing different things in the callback function depending on the chosen value.

**Comment by bahia0019** [comment]
Yes, I'm stuck on this right now as well. 
I have an option for Custom Text or Logo to be displayed.
Using Active Callback to display chosen option.

Since they're two different outputs, what is the method in which to call them in the theme template?

**Comment by aristath** [comment]
I guess you could write a custom callback function...
Read http://ottopress.com/2015/whats-new-with-the-customizer/ for more details on how the `active_callback` works in the customizer.
From his example there:
```php
function choice_a_callback( $control ) {
    if ( $control->manager->get_setting('demo_radio_control')->value() == 'a' ) {
        return true;
    } else {
        return false;
    }
}
```
