### ISSUE TITLE
custom default fonts output

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1357]
### Issue description:
Having problems creating a set of custom default fonts.

```
function my_custom_fonts( $standard_fonts ) {
	$fonts['helvetica'] = array(
		'label' => 'Helvetica',
		'variants' => array('300','300italic','regular','italic'),
		'stack' => '"Helvetica", sans-serif',
	);
	$fonts['helvetica_neue'] = array(
		'label' => 'Helvetica Neue',
		'variants' => array('300','300italic','regular','italic'),
		'stack' => '"Helvetica Neue", "Helvetica", sans-serif',
	);
	return $fonts;
}
add_filter( 'kirki/fonts/standard_fonts', 'my_custom_fonts' );
```

this is what it outputs in my css file: 

![bildschirmfoto 2017-06-02 um 16 06 23](https://cloud.githubusercontent.com/assets/22119831/26729301/733fe214-47ad-11e7-9658-383156dbc7ef.png)

and this is how I create the CSS:

```
<?php $page_font_family_value = get_theme_mod( 'page_font_family', array() ); ?>

<?php if ( isset( $page_font_family_value['font-family'] ) && ! empty( $page_font_family_value['font-family'] ) ) { ?>

body {
    font-family: '<?php echo $page_font_family_value['font-family'] ?>';
}

<?php } ?>
```

reference: #1082

**Comment by mapsteps** [comment]
Notice the quotes here:

`body {
    font-family: '<?php echo $page_font_family_value['font-family'] ?>';
}`

I tried to remove them (since they're not mandatory) and ended up with this:

![bildschirmfoto 2017-06-04 um 20 46 41](https://cloud.githubusercontent.com/assets/22119831/26764424/fa20d26a-4966-11e7-8b9f-052a6a553573.png)

**Comment by aristath** [comment]
Try this:

```php
font-family: <?php echo html_entity_decode( $page_font_family_value['font-family'], ENT_QUOTES ); ?>;
```
It seems to work fine with your example code.

**Comment by mapsteps** [comment]
Works like a charm, thanks!
