### ISSUE TITLE
Typography Control - If force loading multiple variant problem

### ISSUE THREAD

**Issue by bawright** [themeum/kirki#1359]
### Issue description:
Testing out the typography control with the new solution on #992 

If applying a default variant, Google fonts won't load. Take away the variant default, and it loads perfectly. Didn't know if this was the intended action...

This is also the case on filtering the fonts #1202 

Also, can you do both? Filter 'fonts' and force load 'variants'? Just curious, I always like to test extremes.

### Version used:
Develop

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'my_config', array(
    'type'        => 'typography',
    'settings'    => 'demo-filtered-typography',
    'label'       => __( 'Typography Control', 'text-domain' ),
    'section'     => 'demo',
    'default'     => array(
        'font-family'    => 'Roboto',
        // Leaving this in with the "choices" below will not load any typography control fonts.
        'variant'        => 'regular',
        'font-size'      => '1em',
        'line-height'    => '1.5',
        'letter-spacing' => '0',
        'text-transform' => 'none',
        'subsets'        => array( 'latin' ),
    ),
    // Force load variants (#992)
    'choices' => array(
        'variant' => array(
            'regular',
            'italic',
            '700',
            '700italic',
        ),
    ),
    'transport'   => 'auto',
    'output'      => array(
        array(
            'element'    => '#demo-2',
        ),
    ),
) );

**Comment by aristath** [comment]
> If applying a default variant, Google fonts won't load. Take away the variant default, and it loads perfectly. Didn't know if this was the intended action...

I don't understand... So it works if tou remove "regular" from the code you posted above?
Or it works if in the control you select something other than regular? And is the issue in the customizer, or the frontend of the site? It seems to be working fine to me...

> Also, can you do both? Filter 'fonts' and force load 'variants'? Just curious, I always like to test extremes.

Yes, it works fine. :) I just tested it

**Comment by bawright** [comment]
If `'variant' => 'regular'` is added to defaults, then no google fonts will load on the frontend of the site. It doesn't throw any errors on either the frontend or customizer, it just doesn't load any google fonts.

BTW, great plugin!

**Comment by aristath** [comment]
Hey there!

I just tested this and it seems to be working fine...
All I had to change was the `my_config` to a config that was already defined, and it worked perfectly!

**Comment by bawright** [comment]
It is working!! It must have been fixed in a past commit. The `my_config` was just for example. Thanks @aristath

**Comment by aristath** [comment]
Glad it works! 👍 
Closing this one
