### ISSUE TITLE
Slider Control Problem - using transport auto and value_pattern in the output

### ISSUE THREAD

**Issue by bawright** [themeum/kirki#1360]
### Issue description:
Slider Control - setting `'transport' => 'auto'` with a` 'value_pattern'` is throwing an error in the customizer while `'transport' => 'refresh'` works as expected. It also does the same thing with `postMessage` and `js_vars`.

The value for the element is showing as:
```
#some-element {
    width: newval0;
}
```
Saving the settings and refreshing the browser... it's saving the output as expected. Problem seems to be localized to js preview.

### Version used:
develop

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'my_config', array(
    'type'        => 'slider',
    'settings'    => 'demo_slider',
    'label'       => 'Slider Control',
    'section'     => 'demo',
    'default'     => 250,
    'choices'     => array(
        'min'  => '0',
        'max'  => '500',
        'step' => '1',
    ),
    'transport' => 'auto',
    'output'    => array(
        array(
            'element'       => ' #some-element',
            'property'      => 'width',
            // Throwing an error if used with transport "auto" or postMessage.
            'value_pattern' => 'calc($ / 16 * 1rem)',
        ),
    ),
) );
```

**Comment by aristath** [comment]
I believe this one just got fixed, can you please test it to make sure it works ok now?
As a sidenote, `calc($ / 16 * 1rem)` would be better written as `calc($rem / 16)` 😉 

Thanks for testing and reporting these bugs, I really appreciate it!

**Comment by bawright** [comment]
Works great! I wrote it like that as a hack to an old IE bug... old habit I need to kick. :)

I'll keep testing though.
