### ISSUE TITLE
add a "condition" argument in output.

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#1362]
Will have to work both for css and postMessage modules.
Something like 
```php
'conditions' => array(
    'js'  => 'js_function_name',
    'php' => 'php_function_name',
),
```

**Comment by aristath** [comment]
After further cnsideration this can already be achieved using js_callback and php_callback that we already have in v3.0, so no extra param is needed.

**Comment by themenow** [comment]
How to use js_callback and php_callback? This doesn't seem work:

```
'output' => array(
  array(
    'element'=>'a',
    'property'=>'margin',
    'php_callback'=>'php_function'
  ),
)
```
