### ISSUE TITLE
Add ability to use a custom URL for the webfonts API

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#1364]
This one for typography controls.
Developers should be able to use a custom URL with their own API key such as 
https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity
Details in https://developers.google.com/fonts/docs/developer_api
This would entail using the ajax feature of select2: https://select2.github.io/examples.html#data-ajax

**Comment by aristath** [comment]
While doing this we should also allow adding different font-groups. (standard/google/typekit etc)

**Comment by DannyCooper** [comment]
Is this still relevant? If so what is the benefit?

**Comment by aristath** [comment]
oh this is an old one... Back when this ticket was created we didn't have the extra args that are available now to show for example the 40 most popular fonts.
This is no longer relevant :+1:
