### ISSUE TITLE
Typekit integration in Kirki

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1365]
Hi!

This code has some issues.
https://github.com/aristath/kirki/issues/1265

When I have several fonts installed on my site, one with Google font and the other with a typekit, there appears an error and gfonts not loaded. Can I fixed it?

`https://fonts.googleapis.com/css?family=Work+Sans%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900%7CVidaloka%3Aregular%7CPlayfair+Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic%7Chalyard-display%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&subset=Cyrillic%2CCyrillic+Extended%2CDevanagari%2CGreek%2CGreek+Extended%2CKhmer%2CLatinFailed to load resource: the server responded with a status of 400 (HTTP/2.0 400)`

**Comment by vlthemes** [comment]
So in console i have next error
`https://fonts.googleapis.com/css?family=Work+Sans%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900%7CVidaloka%3Aregular%7CPlayfair+Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic%7Chalyard-display%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&subset=Cyrillic%2CCyrillic+Extended%2CDevanagari%2CGreek%2CGreek+Extended%2CKhmer%2CLatinFailed to load resource: the server responded with a status of 400 (HTTP/2.0 400)`

**Comment by Mountain-Themes** [comment]
Yes. I also have this problem. I hope, this problem will solution.

**Comment by aristath** [comment]
Hey there!

How exactly are you adding those typekit webfonts?
Do you have this in a repository on github perhaps?

**Comment by vlthemes** [comment]
Yep.
I tried to use this filter 'google_fonts', but this is not working. (See the first message of this issue)
https://github.com/vlthemes/VLThemes-Add-Typekit-fonts-to-Kirki

**Comment by vlthemes** [comment]
Is there a solution already?

**Comment by aristath** [comment]
fixed.
