### ISSUE TITLE
Replace fonts.googleapis.com with fonts.useso.com

### ISSUE THREAD

**Issue by thehung2224** [themeum/kirki#1366]
### Issue description:
I am working on a project in mainland China and Google services slow down the loading time of the site. Is it possible to permanently exchange the font loading reference from googleapis.com to useso.com?

### Version used:
2.0.7

### Using theme_mods or options?
```
Kirki::add_field( 'tm-finance', array(
	'type'        => 'typography',
	'settings'    => 'body_font',
	'description' => esc_html( esc_html__( 'Set up font settings for body text', 'tm-finance' ) ),
	'section'     => $section,
	'priority'    => $priority ++,
	'default'     => array(
		'font-style'     => array( 'bold', 'italic' ),
		'font-family'    => TM_FINANCE_SECONDARY_FONT,
		'font-size'      => '16px',
		'font-weight'    => '300',
		'line-height'    => '1.8',
		'letter-spacing' => '-.05em',
	),
	'choices'     => array(
		'font-style'     => true,
		'font-family'    => true,
		'font-size'      => true,
		'font-weight'    => true,
		'line-height'    => true,
		'letter-spacing' => true,
	),
	'output'      => array(
		array(
			'element' => 'body,p',
		),
	),
) );
```

**Comment by thehung2224** [comment]
Anyone here?

**Comment by aristath** [comment]
Hey there!
Version 3.0 is nearing completion so I won't be able to add this in this version.
Issue #1364 will make it possible to use other APIs and URLs and is planned for version 3.1 so I'll go ahead and close this one in favour of the abstraction in the other item. 👍

**Comment by thehung2224** [comment]
Thank you @aristath
