### ISSUE TITLE
Styles are not saving in the file or inline css.

### ISSUE THREAD

**Issue by CodeCurosity** [themeum/kirki#1367]
I just tried the typography field in the development version and the styles are not saving to css file or inline css?

**Comment by aristath** [comment]
Everything seems to be working fine now 👍

**Comment by CodeCurosity** [comment]
I get this error on new develop, 

Notice: wp_add_inline_style was called incorrectly. Do not pass <style> tags to wp_add_inline_style(). Please see Debugging in WordPress for more information. (This message was added in version 3.7.0.) in /Applications/MAMP/htdocs/wordpress/wp-includes/functions.php on line 4139

**Comment by aristath** [comment]
duplicate of #1410, we'll continue resolving this issue there.
