### ISSUE TITLE
Weird UI Behavior in Image Field

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#1371]
Hey @aristath been a while since I last open an issue on this repo (nice work on v3)

### Issue description:
Two weird issues.
First, the remove image button gets hidden every time I reload the customizer page.
![screen shot 2017-06-10 at 9 31 33 am](https://user-images.githubusercontent.com/1738077/27001006-a622eaec-4dbf-11e7-957d-c8e93b1b0377.png)
What I mean by that is that the button is hidden on the first load, is then displayed if I change the background image but if I save and leave the customizer and then come back the button is hidden again. Same behavior if I refresh the page

The button is actually there but has a `hidden` class on it coming from wp I presume.
![screen shot 2017-06-10 at 9 33 40 am](https://user-images.githubusercontent.com/1738077/27001022-fa5d6b00-4dbf-11e7-8c02-178c90407175.png)

The other issue is even weirder. It's as if the media uploader modal gets created twice.
I made a quick recording of the issue http://quick.as/q3wsdle5
As you'll see, when the media uploader modal appears, the background is way more darker than usual and after I click `select` the background behind the modal changes a bit but the modal stays right there. But if I click on the background before selecting an image everything works normal.

And by looking at the source code it seems that there actually are two uploader one on top of the other
![screen shot 2017-06-10 at 9 44 57 am](https://user-images.githubusercontent.com/1738077/27001089-9f1886f6-4dc1-11e7-87c6-7dcee9d75aca.png)

I only have 1 image field in my code so it's not some weird conflict with another field I created in my theme

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Running latest dev version (downloaded today) with WP 4.9 (and also tried 4.8)

### Using theme_mods or options?
Mix of both but Mods for this particular field.

### Code to reproduce the issue (config + field(s))
It's just a normale image field with no particular configurations

**Comment by aristath** [comment]
I believe that last commit fixes the issue, can you please check?
In previous versions there was no image field and we were using the WP-Core class for that.
In 3.0 I added a new field for images that by default behaves like the core WP control, but you can set this to save an array instead of just the url:
```php
'choices' => array(
    'save_as' => 'array',
),
```
The array saves `'id', 'url', 'width', 'height'`, and if the `save_as` argument is not defined then if falls-back to saving just the URL, and so it's still compatible with older versions.

**Comment by manuelmoreale** [comment]
If I use the latest commit the customizer doesn't load at all and I get this error.
I didn't change anything else in the theme code.
![screen shot 2017-06-12 at 3 49 08 pm](https://user-images.githubusercontent.com/1738077/27036963-d80dc838-4f86-11e7-8026-981b58e8944c.png)

**Comment by aristath** [comment]
The above was a typo, it was fixed in https://github.com/aristath/kirki/commit/f06819a13df1a83c536df3b508f51bc3d3fd9d3f and no other issues have been reported since with the image controls. 👍

**Comment by manuelmoreale** [comment]
Yes I dug in the code and spotted the typo, was about to sent a pull request and then I saw you had already fixed it. Thanks 😉
