### ISSUE TITLE
2 questions from the editor field

### ISSUE THREAD

**Issue by zkmark** [themeum/kirki#1373]
### Issue description:
1.- Because the editor field is not in the documentation?
Https://aristath.github.io/kirki/docs/getting-started/config.html

2.- The editor field works fine only but when I try to put it in the repeater it does not work

### Version used: 2.38
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
Kirki::get_option

### Code to reproduce the issue (config + field(s))
`$fields[] = array(
			'type'        => 'repeater',
			'label'       => esc_attr__( 'Repeater Control', 'my_textdomain' ),
			'section'     => 'header_default_section',
			'priority'    => 10,
			'row_label' => array(
				'type'  => 'field',
				'value' => esc_attr__('your custom value', 'my_textdomain' ),
				'field' => 'link_text',
			),
			'settings'    => 'my_setting',
			'default'     => array(
				array(
					'link_text' => esc_attr__( 'Kirki Site', 'my_textdomain' ),
				),
			),
			'fields' => array(
				'link_text' => array(
					'type'        => 'editor',
					'label'       => esc_attr__( 'Link Text', 'my_textdomain' ),
					'description' => esc_attr__( 'This will be the label for your link', 'my_textdomain' ),
					'default'     => '',
				),
			)
		);`

**Comment by aristath** [comment]
> 1.- Because the editor field is not in the documentation?

The documentation is pretty old and is mostly maintained by the community.
Feel free to submit any changes to the `gh-pages` branch.

> 2.- The editor field works fine only but when I try to put it in the repeater it does not work

Repeaters don't support the editor field.

**Comment by yubarajrai** [comment]
editor field is conflicting with each-other. When i enter content it is updating in another editor field also automatically. can anyone help me out to fix the error ?

**Comment by DannyCooper** [comment]
@yubarajrai I'm unable to replicate your issue:

```
Kirki::add_field( 'prefix_config', [
	'type'        => 'editor',
	'settings'    => 'my_editor_one',
	'label'       => esc_html__( 'My Editor Control', 'kirki' ),
	'description' => esc_html__( 'This is an editor control.', 'kirki' ),
	'section'     => 'title_tagline',
	'default'     => '',
] );

Kirki::add_field( 'prefix_config', [
	'type'        => 'editor',
	'settings'    => 'my_editor_two',
	'label'       => esc_html__( 'My Editor Control', 'kirki' ),
	'description' => esc_html__( 'This is an editor control.', 'kirki' ),
	'section'     => 'title_tagline',
	'default'     => '',
] );
```

If your issue persists, please create your own ticket. It's easier to track the progress that way.
