### ISSUE TITLE
Huge performance issue with typography field

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1375]
### Issue description:
Since I upgraded to the latest develop branch 2.3.8, there's a huge performance issue when there's the typography field. When I try to access a customizer's section with the typography field present, it gets so slowly, though most of the time it opens the section eventually. Try going back and forth with the section, it gets more obvious.

If there are more than one typography field in one section, it can get even unresponsive.

### Version used:
latest develop branch - 2.3.8

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
/***************************************************************
CONFIG
***************************************************************/
Kirki::add_config( 'my_theme', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

/* ----------------------------------------
   PANEL - General Styling
 ---------------------------------------- */
Kirki::add_panel( 'general_styling', array(
    'priority'    => 10,
    'title'       => esc_html__( 'General style', 'mytheme' ),
) );

    /* ------------------------
      SECTION - Overall
    ------------------------ */
    Kirki::add_section( 'general_overall', array(
        'panel'          => 'general_styling',
        'title'          => esc_html__( 'Overall', 'mytheme' ),
        'priority'       => 10,
        'capability'     => 'edit_theme_options',
        'theme_supports' => '', // Rarely needed.
    ) );

        /* ---------
           FIELDS
        --------- */

        Kirki::add_field( 'my_theme', array(
            'settings'    => 'general_typography',
            'section'     => 'general_overall',
            'type'        => 'typography',
            'label'       => esc_html__( 'Font settings', 'mytheme' ),
            'default'     => array(
                'font-family'    => 'Roboto',
                'variant'        => 'regular',
                'font-size'      => '18px',
                'line-height'    => '2',
                'letter-spacing' => '0',
                'subsets'        => array( 'latin-ext' ),
                'color'          => '#333',
                'text-transform' => 'none',
                'text-align'     => 'inherit',
            ),
            'priority'    => 10,
            'transport'   => 'postMessage',
            'js_vars'     => array(
                array(
                    'element'  => 'body',
                    'function' => 'css',
                ),
            ),
            'output'      => array(
                array(
                    'element' => 'body',
                ),
            ),
        ) );

**Comment by iliman** [comment]
And the fonts loads twice, by different methods (embed & link)

![image](https://user-images.githubusercontent.com/4136507/27015594-bf0032fe-4f22-11e7-86f6-13c7f81ad7f7.png)

**Comment by aristath** [comment]
@Slobork Fixed, can you please pull anew and test if it's ok now?
The performance should be ok now.
@iliman can you please create a different issue for this? thanks!

**Comment by Slobork** [comment]
Yeap, it's corrected. Thanks!

However, it seems this leaded to another problem:
#1377
