### ISSUE TITLE
Select field doesn't respond (latest develop branch)

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1376]
### Issue description:
After switching to the latest develop branch, select field is not responding. When I try to use the select field, it doesn't show options, or it closes itself immediately.

### Version used:
latest develop branch 2.3.8

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
/***************************************************************
CONFIG
***************************************************************/
Kirki::add_config( 'my_theme', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

/* ----------------------------------------
   PANEL - General Styling
 ---------------------------------------- */
Kirki::add_panel( 'general_styling', array(
    'priority'    => 10,
    'title'       => esc_html__( 'General style', 'mytheme' ),
) );

    /* ------------------------
      SECTION - Overall
    ------------------------ */
    Kirki::add_section( 'general_overall', array(
        'panel'          => 'general_styling',
        'title'          => esc_html__( 'Overall', 'mytheme' ),
        'priority'       => 10,
        'capability'     => 'edit_theme_options',
        'theme_supports' => '', // Rarely needed.
    ) );

        /* ---------
           FIELDS
        --------- */
        Kirki::add_field( 'my_theme', array(
            'settings'    => 'article_shadow',
            'section'     => 'general_overall',
            'type'        => 'select',
            'label'       => esc_html__('Box style', 'mytheme'), 
            'priority'    => 10,
            'multiple'    => 1,
            'choices'     => array(
                                  '0'  => esc_html__('none',      'mytheme'), 
                                  '1'  => esc_html__('Opt - 1',   'mytheme'), 
                                  '2'  => esc_html__('Opt - 2',   'mytheme'),
            ),
            'default'     => '0',
        ) );

**Comment by aristath** [comment]
Fixed, can you please pull anew and test if it's ok now?
