### ISSUE TITLE
Google fonts aren't loading (latest develop branch)

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1377]
### Issue description:
With the latest develop branch, updated today, you have omitted calling the `#kirki_google_fonts-css` stylesheet. So, google fonts aren't loading on the front side of the site. Either you have to bring this file back or to generate google used fonts directly in the `#kirki-styles-css` stylesheet.

This is happening when compiling css to a file is used:
```
add_filter( 'kirki/dynamic_css/method', function() {
    return 'file';
});
```

If this method isn't used, google fonts are rendering well with inline method, since the `#kirki_google_fonts-css` stylesheet is called, i.e. it is linking to google fonts with https://fonts.googleapis.com

Also, with inline method the `#kirki-styles-global-css` stlesheet is loading. I think you do not need this since css is generated inline and the file is completely empty.

### Version used:
latest develop branch

### Using theme_mods or options?
theme_mod

**Comment by aristath** [comment]
I believe this one just got fixed.
Works fine on my end now, can you please test it?

**Comment by Slobork** [comment]
@aristath Unfortunately this isn't resolved, the problem is almost same as I described in the OP, I'll try to light it up a bit:

1. With inline css: 

- google fonts are displayed well, but you do not need to render css file since the css is generated inline. That flie is excess and it's empty anyway. That empty file is still loading - `#kirki-styles-THEME-NAME-css`. 

- the file `#kirki_google_fonts-css` is loading here now. That's the file with `@font-face` code. You also have that code generated inline as well. I think it's enough to choose one way for `@font-face` code.

![font-face2](https://user-images.githubusercontent.com/6130788/27261952-e487fb30-544d-11e7-9ce5-0a2612b7869c.png)


2. When compiling css to a file is used:

- goolge fonts aren't reflected on the front side of the site (in the Customizer they are reflected because the WP are loading the google fonts for its admin pages anyway). We are missing `@font-face` here, i.e. the part of the code that is generated with the `#kirki_google_fonts-css` stylesheet. You are calling that file when inline css is used, instead of here (when the css is compiled to the file) - that's probably the problem. That file was loading with compiled css with the develop branch 2.3.7, but with the latest updates it's ommited. 
- It's either necessary to bring that file back `#kirki_google_fonts-css` or to generate its content inline. 

P.S. You've closed this issue, hopefully you'll notice it. If not, later I'll fire another issue referencing here.

**Comment by aristath** [comment]
This is using inline mode:

<img width="1162" alt="screenshot at jun 19 19-30-14" src="https://user-images.githubusercontent.com/588688/27295486-c913bef6-5525-11e7-87f5-cc33553885e4.png">

WordPress doesn't allow us to add `<style>...</style>` directly in the `<head> of a page (for good reason).
We are instead forced to use the [`wp_add_inline_style()`](https://codex.wordpress.org/Function_Reference/wp_add_inline_style) function.
That function requires a stylesheet it can attach itself to.
That's why the empty stylesheet is enqueued...
We have to enqueue it so that the inline styles can go somewhere.

If I switch from inline mode to file using this code:
```php
add_filter( 'kirki/dynamic_css/method', function() {
	return 'file';
});
```
then the source of my page looks like this:
<img width="1158" alt="screenshot at jun 19 19-29-15" src="https://user-images.githubusercontent.com/588688/27295533-f10c4392-5525-11e7-9f6e-066eeb6c612b.png">

So the stylesheet is compiled, and googlefonts are added inline.
It seems to be working fine on my end...
Did you try pulling the latest commits from the `develop` branch? https://github.com/aristath/kirki/archive/develop.zip

**Comment by aristath** [comment]
the

**Comment by Slobork** [comment]
OK, thanks for explaining regarding the inline and the empty file. 

However, I still do have a problem with the css compiled to the file. The `@font-face` part isn't generated, i.e. the inline code doesn't appear at all.

**Comment by aristath** [comment]
I still can't replicate the issue.
Can you please send me a copy of your theme so that I may check what happens? If I can't replicate it there's not much I can do to fix it

**Comment by Slobork** [comment]
@aristath  I've just sent it to your gmail. Hope you find the problem.

**Comment by Slobork** [comment]
I've just received the Daemon from my Yahoo that it couldn't deliver the message. Then I tried sending it from my gmail, but it immediately blocked the attachment with the message:
`Blocked for security reasons ...Gmail blocks messages that may spread viruses, like messages that include executable files or certain links.`

Very stupid and annoying.

Do you have some other email I could send it to?

**Comment by aristath** [comment]
😢 Unfortunately no, all my accounts are on google.
Perhaps upload to dropbox or google docs and just send me the link so I can download?

**Comment by Slobork** [comment]
Ok, here's the link:
https://www.dropbox.com/s/3fe0zb4wxncxgwm/theme.zip?dl=0

Btw, I'm not sending the theme I'm working on, there's not much to hide, just the theme name :-).
I'm sending you the simpler version which is actually the starter theme of another framework, but for the regular theme options.

With this theme the issue is the same as previously described, no difference.
You'll find the Kirki folder and inside is the kirki-fields.php where the fields are laid.

Kirki is called from the functions.php

Cheers

**Comment by aristath** [comment]
At first it didn't work.
I was getting the `@font-face` in the source of the page, but when I opened the compiled CSS file it was showing an old file.
I pushed a commit that fixes the issue for me and now everything works fine in the theme you sent.

HTML in the page:
```html
<link rel='stylesheet' id='kirki-styles-css'  href='http://local.wordpress.dev/wp-content/uploads/kirki-css/styles.css?ver=1497989439' type='text/css' media='all' />
<style id='kirki-styles-inline-css' type='text/css'>
@font-face {
  font-family: 'Paprika';
  font-style: normal;
  font-weight: 400;
  src: local('Paprika'), local('Paprika-Regular'), url(https://fonts.gstatic.com/s/paprika/v4/wzbKN-UTMCqP5Xrc1FmOdQ.ttf) format('truetype');
}
</style>
```

CSS in the file:
`
body{background-image:url("http://local.wordpress.dev/wp-content/uploads/2015/12/col_bkgd_10-compressor.jpg");background-color:#541d82;background-repeat:repeat-all;background-position:center center;background-attachment:fixed;-webkit-background-size:cover;-moz-background-size:cover;-ms-background-size:cover;-o-background-size:cover;background-size:cover;}.widget-title{font-family:Paprika, "Comic Sans MS", cursive, sans-serif;font-size:48px;font-weight:400;font-style:normal;letter-spacing:12px;line-height:3;text-align:inherit;text-transform:uppercase;color:#dd3333;}
`

The Paprika font is properly referenced in both the HTML and the CSS, and I can see it works fine in the frontend.

Can you please try pulling that last commit and test if that fixes the issue on your end?

**Comment by Slobork** [comment]
It's cool now :thumbsup:
Thanks!

**Comment by aristath** [comment]
Really??? Awesome!
Closing this one.
3.0 Release suddenly looks a lot closer 👍

**Comment by colmtroy** [comment]
@aristath - I appear to be experiencing something similar with 3.0.6. Issue resolves itself when I rollback to 2.3.8

Symptoms
- Google fonts url is not called at all on the frontend with 3.0.6 (i.e. this markup is missing `<link rel='dns-prefetch' href='//fonts.googleapis.com' />`), as is the following
```
    <link rel='stylesheet' id='kirki_google_fonts-css'  href='https://fonts.googleapis.com/css?family=XXX;subset=latin-ext' type='text/css' media='all' />
<link rel='stylesheet' id='kirki-styles-accentuate_config-css'  href='http://local.dev/wp-content/plugins/kirki-2.3.8/assets/css/kirki-styles.css' type='text/css' media='all' />
```

**Comment by aristath** [comment]
@colmtroy already fixed in https://github.com/aristath/kirki/issues/1430

**Comment by colmtroy** [comment]
@aristath - ah - excellent - thanks!
