### ISSUE TITLE
Support input_attrs in repeater sub-fields.

### ISSUE THREAD

**Issue by danielepani** [themeum/kirki#1382]
### Issue description:
I was looking for a way to limit the length of a text or textarea. I thought there would be some parameter to set this limit, or at least add custom attributes like <code>maxlength</code>.
### Version used:
2.2.0

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
    Kirki::add_config('field_configuration', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	));

    Kirki::add_section('my_section', array(
		'title' => _('My Section'),
		'description' => _('Section to host field'),
		'capability' => 'edit_theme_options'
	));
	
    Kirki::add_field('field_configuration', array(
		'type' => 'text',
		'label' => _('Field Label'),
		'description' => _('Field description. What can you do with this?'),
		'default' => '',
		'section' => 'my_section',
		'settings' =>  'help_video',
	));

**Comment by aristath** [comment]
```php
Kirki::add_field('field_configuration', array(
	'type' => 'text',
	'label' => _('Field Label'),
	'description' => _('Field description. What can you do with this?'),
	'default' => '',
	'section' => 'my_section',
	'settings' =>  'help_video',
	'input_attrs' => array(
		'maxlength' => '50',
	),
));
```

**Comment by danielepani** [comment]
@aristath Sorry to bother you more, but it seems like it's being ignored. Maybe this is not valid if text fields are inside a repeater?

**Comment by aristath** [comment]
No, this will currently not work in repeaters.
Adding this as a feature request for version 3.1 because we don't have time to implement it in 3.0.

**Comment by danielepani** [comment]
@aristath Thank you. Happy to have contributed somehow.

**Comment by aristath** [comment]
Closing this one as it will be taken care of with the rewrite on https://github.com/aristath/kirki/issues/1513
