### ISSUE TITLE
Editor field breaks the select field.

### ISSUE THREAD

**Issue by iliman** [themeum/kirki#1385]
### Issue description:
Typography field select inputs breaks too. If you delete the editor field, everything will work.

### Version used:
develop branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_config( 'my_config', array(
	'option_type' => 'theme_mod',
	'capability'  => 'edit_theme_options',
) );

Kirki::add_section( 'my_section', array(
	'title'       => __( 'My Section', 'my_textdomain' ),
) );

Kirki::add_field( 'my_config', array(
	'type'        => 'editor',
	'settings'    => 'editor',
	'label'       => __( 'Editor Field', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => '&copy; 2017',
) );

Kirki::add_field( 'my_config', array(
	'type'        => 'select',
	'settings'    => 'select',
	'label'       => __( 'Input Field', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => 'option-1',
	'priority'    => 1,
	'multiple'    => 1,
	'choices'     => array(
		'option-1'   => __( 'Option 1', 'my_textdomain' ),
		'option-2'   => __( 'Option 2', 'my_textdomain' ),
		'option-3'   => __( 'Option 3', 'my_textdomain' ),
		'option-4'   => __( 'Option 4', 'my_textdomain' ),
	),
) );
```

**Comment by aristath** [comment]
I just tested this and couldn't replicate. Also added a couple of typography fields and all sorts of other things that could affect it.
Still nothing...
Do you get any errors in the console?

**Comment by iliman** [comment]
Hi, @aristath
The issue is gone after I update the WordPress to the latest version(4.8), before I used 4.6.6.
Please update that "Requires at least: 4.8" in the readme. You can close this.
