### ISSUE TITLE
Radio-Image Preset not Working

### ISSUE THREAD

**Issue by umairrazzaq** [themeum/kirki#1387]
### Issue description:
Hi, I need your help regarding **Radio-Image**.
I've a theme where I put 3 template styles, I've make 1st template as default from code (customizer.php).
In my theme there are many elements/layouts dependent on template including repeater filed.

But after activating theme I've got many errors like;
**Warning: Invalid argument supplied for foreach() in File...**

So I've to first switch between any template (style) from customizer first to hide these errors.
Any help would be really appreciable as I'm messing with these from past week.

Another thing if i view any page in Customizer view (without making any changes), than i can see foreach() contents (Like Social Media Icons). Please see attached screenshots for this.

Thanks in Advance.

### Version used:
Kirki 2.2.0

### Using theme_mods or options?
`colorcv_Kirki::add_config( 'colorcv', array(`
`    'capability'    => 'edit_theme_options',`
`    'option_type'   => 'theme_mod',`
`));`

### Code to reproduce the issue (config + field(s))

**Screenshots**
![image](https://user-images.githubusercontent.com/5692632/27381789-8ef5f90e-569d-11e7-96c5-d887a8b11b06.png)

![image](https://user-images.githubusercontent.com/5692632/27381703-461f13e6-569d-11e7-96e9-42bef10873cc.png)

![image](https://user-images.githubusercontent.com/5692632/27382009-6cde4de8-569e-11e7-8947-e7f339e9d48e.png)
![image](https://user-images.githubusercontent.com/5692632/27382059-b7c3cedc-569e-11e7-9c41-0f1ffbf78f77.png)

**Comment by aristath** [comment]
> Warning: Invalid argument supplied for foreach() in File...

Which file? What line? What do you have in that line in that file? Can you please post your code?

**Comment by umairrazzaq** [comment]
Hi, thanks for the message and sorry for not providing sufficient info regarding this ticket.

I've used underscores starter theme and based on the template (style) selection I'm loading layout templates accordingly but content components are same. Below are details of some files with code reference.

### Description about Loading Template

#### customizer.php on Line 79 (config: theme_mod):
```
// Show Template Radio (Image)
colorcv_Kirki::add_field( 'colorcv', array(
    'type'        => 'radio-image',
    'settings'    => 'active_template',
    'label'       => esc_html__( 'Active Template', 'colorcv' ),
    'section'     => 'template_section',
    'default'     => 'template-01',
    'priority'    => 10,
    'choices'     => array(
        'template-01' => get_template_directory_uri() . '/assets/images/templates/template-01.png',
        'template-02' => get_template_directory_uri() . '/assets/images/templates/template-02.png',
        'template-03' => get_template_directory_uri() . '/assets/images/templates/template-03.png',
    ),
) );
```

#### index.php:
```
// Load Menu Template
get_template_part( 'template-parts/template', 'menu' );

// PHP Variables
$active_template = get_theme_mod( 'active_template', 'template-01' );

// Load theme template based on selection
if ( $active_template == 'template-01' ) {
    get_template_part( 'template-parts/content', 'template-01' );
} elseif ( $active_template == 'template-02' ) {
    get_template_part( 'template-parts/content', 'template-02' );
} elseif ( $active_template == 'template-03' ) {
    get_template_part( 'template-parts/content', 'template-03' );
}
```

#### content-template-01.php:
```
<div class="container-fluid">
    <div class="row">
        <main id="main" class="strips">
            <?php

            // Include profile section content
            get_template_part( 'template-parts/template', 'profile' );

            // Include resume section content
            get_template_part( 'template-parts/template', 'resume' );

            // Include portfolio section content
            get_template_part( 'template-parts/template', 'portfolio' );

            // Include blog section content
            get_template_part( 'template-parts/template', 'blog' );

            // Include contact section content
            get_template_part( 'template-parts/template', 'contact' );

            ?>
            <button class="btn btn-sm btn-link strip__close"><i class="fa fa-close fa-2x"></i></button>
        </main> <!-- /.strips -->
    </div> <!-- /.row -->
</div> <!-- /.container-fluid -->
```

**Note:** Other 2 templates (**content-template-02.php** & **content-template-03.php**) has slightly different (parent) tags in regard to its layout styles despite loading template parts.

-----------------------------------------------------------------------------------

### Customizer Fields Description
In this case I'll only reference profile (section) page customizer (repeater) fields, though I'm getting same error on other sections as well.

#### Social Media Icons:

**customizer.php - Repeater Field**
```
colorcv_Kirki::add_field( 'colorcv', array(
    'type'        => 'repeater',
    'label'       => esc_attr__( 'Social Icons', 'colorcv' ),
    'settings'    => 'social_menu_items',
    'section'     => 'social_section',
    'priority'    => 30,
    'row_label' => array(
        'type'  => 'field',
        'value' => esc_attr__('Social Menu', 'colorcv' ),
        'field' => 'item_text',
    ),
    'default'     => array(
        array(
            'item_text' => esc_attr__( 'Facebook', 'colorcv' ),
            'item_url'  => 'http://facebook.com/',
            'item_ico' => esc_attr__( 'fa-facebook', 'colorcv' ),
        ),
        array(
            'item_text' => esc_attr__( 'Twitter', 'colorcv' ),
            'item_url'  => 'http://twitter.com/',
            'item_ico' => esc_attr__( 'fa-twitter', 'colorcv' ),
        ),
        array(
            'item_text' => esc_attr__( 'Google Plus', 'colorcv' ),
            'item_url'  => 'http://plus.google.com/',
            'item_ico' => esc_attr__( 'fa-google-plus', 'colorcv' ),
        ),
        array(
            'item_text' => esc_attr__( 'LinkedIn', 'colorcv' ),
            'item_url'  => 'http://linkedin.com/',
            'item_ico' => esc_attr__( 'fa-linkedin', 'colorcv' ),
        ),
        array(
            'item_text' => esc_attr__( 'Adobe Behance', 'colorcv' ),
            'item_url'  => 'http://linkedin.com/',
            'item_ico' => esc_attr__( 'fa-behance', 'colorcv' ),
        ),
        array(
            'item_text' => esc_attr__( 'GitHub Profile', 'colorcv' ),
            'item_url'  => 'http://linkedin.com/',
            'item_ico' => esc_attr__( 'fa-github', 'colorcv' ),
        ),
    ),
    'fields' => array(
        'item_text' => array(
            'type'        => 'text',
            'label'       => esc_attr__( 'Item Text', 'colorcv' ),
            'description' => esc_attr__( 'Social Profile Name', 'colorcv' ),
        ),
        'item_url' => array(
            'type'        => 'url',
            'label'       => esc_attr__( 'Item URL', 'colorcv' ),
            'description' => esc_attr__( 'Social Profile URL', 'colorcv' ),
        ),
        'item_ico' => array(
            'type'        => 'text',
            'label'       => esc_attr__( 'Item Icon', 'colorcv' ),
            'description' => esc_attr__( 'Social Profile Icon - FontAwesome', 'colorcv' ),
        ),
    )
) );
```

**template-profile.php (Social Media Foreach Code)**
```
// Vars
$show_social_icos = get_theme_mod( 'show_social_icos', '1' );
$social_menu_items = get_theme_mod( 'social_menu_items' );

// Loop
<?php if ( $show_social_icos == '1' ) { ?>
<ul id="social-nav" class="list-inline clearfix">
    <?php foreach( $social_menu_items as $social_item ) :
    echo '<li><a href="' . $social_item['item_url'] . '" class="..." title="' . $social_item['item_text'] . '"><i class="fa ' . $social_item['item_ico'] . '"></i></a></li>';
    endforeach; ?>
</ul>
<?php } ?>
```
-----------------------------------------------------------------------------------------------------------------

I hope above code sections are enough for you to get picture of my issue. Though I've tried my best to explain my issue in to-the-point & concise way. But if there is anything still not clear than please do let me know I can share files for review.

Also there are many other repeater fields as well with foreach loop and I've used same pattern as mentioned above for Social Media Icons. Further more please see attached screenshot (last one) with 3 rectangles section highlights, which are repeater fields.

**Comment by aristath** [comment]
Can you please send me a copy of your theme?
If possible upload to dropbox or google docs, and send me a link to that file.
You can find my email on my profile. 👍

**Comment by umairrazzaq** [comment]
I've sent you mail, please check.

**Comment by DannyCooper** [comment]
Closed as moved to email.
