### ISSUE TITLE
Webfonts output ignore the active_callback

### ISSUE THREAD

**Issue by iliman** [themeum/kirki#1388]
### Issue description:
Even if toggle is disabled, Kirki embed the font:

![image](https://user-images.githubusercontent.com/4136507/27386614-6cc6e244-56a7-11e7-8d3c-c080fb36ae70.png)

### Version used:
Latest develop branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_config( 'my_config', array(
	'option_type' => 'theme_mod',
	'capability'  => 'edit_theme_options',
) );

Kirki::add_section( 'my_section', array(
	'title'       => __( 'My Section', 'my_textdomain' ),
) );

Kirki::add_field( 'my_config', array(
	'type'        => 'toggle',
	'settings'    => 'headers_h3_toggle',
	'label'       => __( 'H3 Headers', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => '0',
) );

Kirki::add_field( 'my_config', array(
	'type'            => 'typography',
	'settings'        => 'headers_h3',
	'section'         => 'my_section',
	'default'         => array(
		'font-family'    => 'Open Sans',
		'variant'        => '400',
		'font-size'      => '18px',
		'line-height'    => '1.5',
		'letter-spacing' => '1px',
		'color'          => '#111111',
		'subsets'        => array( 'latin' ),
	),
	'output'          => array(
		array(
			'element'    => array( 'h3', '.h3' ),
		),
	),
	'active_callback' => array(
		array(
			'setting'    => 'headers_h3_toggle',
			'operator'   => '==',
			'value'      => '1',
		),
	),
) );
```

### One more thing
The googlefonts_load_method filter doesn't work. Please check it, maybe I'm doing something wrong. The code:
```php
add_filter( 'kirki/my_config/googlefonts_load_method', function() {
	return 'link';
});
```

**Comment by aristath** [comment]
Both issues should be fine now.

Try using the `kirki/googlefonts_load_method` instead (no `my_config` in the middle)

**Comment by iliman** [comment]
@aristath the first issue was gone, but the filter doesn't work. It only works when I delete the 124-126 lines here [/modules/webfonts/class-kirki-modules-webfonts.php](https://github.com/aristath/kirki/blob/develop/modules/webfonts/class-kirki-modules-webfonts.php#L124).

**Comment by iliman** [comment]
@aristath I found the problem, we should use && instead of || in the condition:
```php
if ( 'async' !== $method && 'embed' !== $method && 'link' !== $method ) {
	$method = 'embed';
}
```

**Comment by aristath** [comment]
👍  merged
