### ISSUE TITLE
Exclude in background and color fields

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1392]
### Issue description:
Is there a way to exclude the value in background and color fields?

What I would like is to omit the value from the output if it's the same as in the theme's stylesheet, but using, for example, the `'exclude' => array( '#eaedf2' )` doesn't work. I have been utilizing the `exclude` with number field, but here it's not working.

I've also tried leaving the `default` to empty ( e.g. `'background-color' => '')`, but it's not the complete solution, because, in this case, when the value is changed from the Customizer's UI, bringing it back with a "Default" button doesn't do anything except voiding the field in the UI, while it outputs the last value it has recorded previously.

### Version used:
develop_branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
        Kirki::add_field( 'my_theme', array(
            'settings'    => 'body_background',
            'section'     => 'SET_SECTION',
            'type'        => 'background',
            'label'       => esc_html__('Site\'s background', 'mytheme'),
            'priority'    => 10,
            'transport'   => 'auto',
            'output' => array(
                array(
                    'element'  => 'body',
                    'property' => 'background',
                ),
            ),
            'default'  => array(
                              'background-color' => '#eaedf2',
                          ),
            'exclude'  => array( '#eaedf2' ),
        ) );

**Comment by Slobork** [comment]
Correction, that `exclude` should be inside the `output`, but still doesn't work.

**Comment by aristath** [comment]
What is it exactly that you want to exclude?
In the `exclude` argument you will have to enter an array of values that you want to exclude.
`#eaedf2` is not the how the value is saved, so it won't work.
If you want to see how to format the value you want to exclude, you can do `var_dump( get_theme_mod( 'body_background' ) );`
Then you can add it like this:
```php
'exclude' => array(
    array(
        'background-color' => '#eaedf2',
        'background-image' => '',
        // More properties here, exactly as seen in the var_dump.
    ),
),
```
each of the value1, value2, value3 in the above code are complete value sets as they are var_dump'd. So it will be an array of arrays.
