### ISSUE TITLE
Appearing Insert/edit link Box

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1395]
### Issue description:
If there is z-index, it display box behind transparent black background image so unable to insert link. When remove z-index, it display box properly.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Latest from w,org 3.0.1

### Using theme_mods or options?
--

### Code to reproduce the issue (config + field(s))
--

PR: https://github.com/aristath/kirki/pull/1394

**Comment by rinkuyadav999** [comment]
Seems it is fixed in core file -> wp-admin/load-styles.php

.wp-customizer #wp-link-wrap {
	z-index: 500105;
}

Works fine so we do not need our css code for z-index

**Comment by aristath** [comment]
merged the PR.

**Comment by rinkuyadav999** [comment]
@aristath also this change require in  kirki/controls/editor/editor.css May be it will added after compiled scss

**Comment by aristath** [comment]
it will be done automatically next time I `grunt`.
