### ISSUE TITLE
Theme Check Plugin Issues

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1398]
### Issue description:

WARNING: Both DOS and UNIX style line endings were found in the file readme.txt. This causes a problem with SVN repositories and must be corrected before the theme can be accepted. Please change the file to use only one style of line endings.

WARNING: file_get_contents was found in the file class-kirki-control-fontawesome.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.1

### Using theme_mods or options?
--

### Code to reproduce the issue (config + field(s))
--

**Comment by aristath** [comment]
> WARNING: Both DOS and UNIX style line endings were found in the file readme.txt. This causes a problem with SVN repositories and must be corrected before the theme can be accepted. Please change the file to use only one style of line endings.

Already fixed

> WARNING: file_get_contents was found in the file class-kirki-control-fontawesome.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.

Also fixed in https://github.com/aristath/kirki/commit/eee249e0e3ec3a8c2c229a21c016cadacd7eb13a
