### ISSUE TITLE
Type Editor issues

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1399]
### Issue description:
Editor was displaying footer of theme properly (above editor) in old version But theme footer displays behind editor in New Version. It creates difficultly to display updated text in real time because footer changes will be behind editor and theme users will unable to check updated text.

Displaying theme sections above editor will be better than behind editor.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.1

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Type Editor

**Comment by aristath** [comment]
tbh I don't quite understand what you mean here.
Perhaps some screenshots would help

**Comment by rinkuyadav999** [comment]
These CSS code missing

`
#customize-preview {
	&.is-kirki-editor-open{
		height: calc(100% - 301px);
	}
}
`

These was in \kirki\assets\scss\global.scss L20 - 24

**Comment by rinkuyadav999** [comment]
PR: https://github.com/aristath/kirki/pull/1400

**Comment by aristath** [comment]
merged.
