### ISSUE TITLE
Switch typography problem

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1408]
### Issue description:

I think this is not a big problem, but I have to constantly fix style files. If you remove the font, then everything will be ok.

Before:
https://monosnap.com/file/G4Myc30xZpN4g9TDf2nxk4mHOOJcg9

After:
https://monosnap.com/file/n3A54bRVTnzEsWdAmSoHP4Kxs007PO

### Version used:
dev or stable

**Comment by rinkuyadav999** [comment]
Seem not an issue. Displaying fine.


```
Kirki::add_field( 'my_config', array(
	'type'        => 'switch',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => '1',
	'priority'    => 10,
	'choices'     => array(
		'on'  => esc_attr__( 'Enable', 'my_textdomain' ),
		'off' => esc_attr__( 'Disable', 'my_textdomain' ),
	),
) );
```

![switch](https://user-images.githubusercontent.com/9743287/27477816-edac76ce-582a-11e7-8054-b0eddb0c4654.png)

**Comment by vlthemes** [comment]
MacOs :(

**Comment by aristath** [comment]
I'm on OSX too and I don't have any issues.
I had this a few days ago and it turned to to be nothing more than browser caches.
In Chrome dev tools this is what did the trick for me: 
<img width="876" alt="screenshot at jun 23 10-40-16" src="https://user-images.githubusercontent.com/588688/27471412-6d676660-5800-11e7-9669-8d9414456ae3.png">
After a refresh with that checked, things were back to normal.
Or you could simply reset all browser cache 7 cookies.

**Comment by vlthemes** [comment]
This problem is only in safari. But I'm satisfied with your answer.

**Comment by aristath** [comment]
Reopening, I haven't checked Safari yet 👍

**Comment by aristath** [comment]
Changed the implementation a bit so this one was fixed.
Also checked safari 😉

**Comment by vlthemes** [comment]
Niceee! Thank you so much, you are the best.
