### ISSUE TITLE
Escape variables on output

### ISSUE THREAD

**Issue by grappler** [themeum/kirki#141]
Hey, I am reviewing a theme for WordPress.org that is using Kirki.

It seems like there are a number of variables that are not escaped. There are too many to list here. e.g. `<?php echo $this->description; ?>`, `$control['settings']` in required.php, `$control['output']['element']` in class-kirki-style.php.

Please can you have a look at this as I cannot approve the theme till it is fixed. Let me know if you have any questions or need help.

**Comment by aristath** [comment]
Hey there!

Thanks... We're currently rebuilding the plugin and improved a lot of things on the [develop](https://github.com/aristath/kirki/tree/develop) branch, I'll go through all files right now and see if we missed anything.

**Comment by grappler** [comment]
So, I just looked at the code for v8.2 and still saw in a number of places variables being outputted without being escaped. e.g. `$this->description;` and `$this->id;`

The variables may be escaped beforehand but with such complex code it becomes time consuming to backtrack to see if the variable has been escaped before. The recommended security procedure is to escape as late as possible so that it is easier to check and so even if the variable is changed in between it is escaped.

**Comment by aristath** [comment]
Hey there!

I'm about to release 0.8.3
We pass ALL fields from the Fields class, and sanitize everything there: https://github.com/aristath/kirki/blob/master/includes/Fields.php#L42-L58

Then in the actual builder we get the fields from there and then pass it on to the Settings and Controls classes: https://github.com/aristath/kirki/blob/master/includes/Builder.php#L26-L46
This way everything is sanitized both when we create the settings as well as when we create the controls.

Then, if we are echoing any scripts or styles from the fields, we get the list of fields using 

``` php
Kirki::fields()->get_all();
```

So everything gets sanitized at all times.

We did this to avoid duplicating code and keep everything in one place.
This way if there's an issue with the sanitization of the field description for example, we can simply change it in one place instead of on each control and script where that is called separately.

**Comment by grappler** [comment]
Thank you for explaining the process. I am just seeing some inconsistencies. Here are some examples.

Why are you escaping `$this->value()` in [EditorControl.php#L18](https://github.com/aristath/kirki/blob/master/includes/Controls/EditorControl.php#L18) but not in [EditorControl.php#L24](https://github.com/aristath/kirki/blob/master/includes/Controls/EditorControl.php#L24)?

Why is [`$this->label`](https://github.com/aristath/kirki/blob/master/includes/Controls/EditorControl.php#L13) escaped but not [`$this->description;`](https://github.com/aristath/kirki/blob/master/includes/Controls/EditorControl.php#L15)?

Thanks

**Comment by aristath** [comment]
On EditorControl.php you're right, I should also escape line 24. I'll do that now.
As for escaping `$this->label` and not `$this->description` it doesn't really make any difference... They are both escaped in the Fields class anyway:
https://github.com/aristath/kirki/blob/master/includes/Fields.php#L152-L154 (label)
https://github.com/aristath/kirki/blob/master/includes/Fields.php#L207-L223 (description)

Gimme a few minutes... I'll update the controls and make this right.

**Comment by aristath** [comment]
done.

**Comment by grappler** [comment]
It is interesting to see the code and how you have built upon the customizer.

Last question: Where is [`$this->palette;`](https://github.com/aristath/kirki/blob/master/includes/Controls/ColorAlphaControl.php#L25) sanitized?

**Comment by aristath** [comment]
hah, you're right... I missed that one. Just fixed it :+1:

**Comment by grappler** [comment]
Great, thanks :+1:

**Comment by justintadlock** [comment]
I didn't know if you wanted a new ticket open or to append to this one.  I've been looking over the code to see the progress of everything.  Great job, BTW!

One thing I wanted to note is to make sure that attributes in the customizer controls are escaped like here: https://github.com/reduxframework/kirki/blob/develop/includes/controls/class-kirki-controls-multicheck-control.php#L58

**Comment by aristath** [comment]
thanks, I appreciate this!

I'm re-opening this one and marking it as a bug, I'll get it fixed ASAP. :+1: 
If you happen to see anything else wrong please do let me know.
