### ISSUE TITLE
Type Number does not work properly

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1412]
### Issue description:
'type' => 'number', Does not store value and also display 'Invalid Value' even value is valid and between max and min.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.3

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```php
Kirki::add_field( 'theme_config', array(
	'type'        => 'number',
	'settings'    => 'excerpt_length',
	'label'       => esc_attr__( 'Excerpt Length', 'text-domain' ),
	'description' => esc_attr__( 'How much words you want to display on Archive page?', 'text-domain' ),
	'section'     => 'blog_options',
	'default'     => 40,
	'choices'     => array(
		'min'  => 1,
		'max'  => 300,
		'step' => 1,
	),
	'active_callback'  => array(
		array(
			'setting'  => 'excerpt_or_content',
			'operator' => '==',
			'value'    => 'excerpt',
		),
	),
) );
```

**Comment by aristath** [comment]
Try pulling the latest commits.
It seems to be working fine on my end now.

**Comment by rinkuyadav999** [comment]
It works fine.
