### ISSUE TITLE
Invalid value for number type

### ISSUE THREAD

**Issue by Fellan-91** [themeum/kirki#1413]
### Issue description:
The error occurs after adding 'type' => 'number' field and trying to change the customization interface.
![1](https://user-images.githubusercontent.com/29658988/27483572-a1ebc6b4-582e-11e7-878b-5e029ba774ed.png)

### Code to reproduce the issue (config + field(s))
```php
        Kirki::add_config('godlike', array(
            'capability' => 'edit_theme_options',
            'option_type' => 'theme_mod',
        ));

        Kirki::add_panel('single_page', array(
            'priority' => 9,
            'title' => esc_html__('Single Page', 'godlike'),
        ));

        Kirki::add_section('single_page_header', array(
            'title' => esc_html__('Header', 'godlike'),
            'priority' => 12,
            'panel' => 'single_page',
        ));

        Kirki::add_field( 'godlike' ,array(
            'type' => 'number',
            'settings' => 'single_page_header_title_padding_bottom',
            'label' => esc_attr__('Title Padding Bottom', 'godlike'),
            'section' => 'single_page_header',
            'default' => 0,
            'priority' => 10,
            'choices' => array(
                'min' => '0',
                'max' => '500',
                'step' => '1',
            ),
        ));
```

**Comment by aristath** [comment]
I'm still unable to replicate...
I copy-pasted your code in my functions.php and it still works fine.
You can check the screencast below... Tried all sorts of values, tried changing with up/down arrows, tried entering a value, the only time I got "invalid value" was when I entered an invalid value on purpose (numbers with decimals, negative numbers, or text characters).

![number-test](https://user-images.githubusercontent.com/588688/27489481-5d2becb0-5843-11e7-9383-30277fc8bf0f.gif)

**Comment by Fellan-91** [comment]
After the upgrade to 3.0.4, this error is gone, thanks!
