### ISSUE TITLE
Can't get gradient to work

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1414]
### Issue description:
Hello,

Thank you for the excellent software and continuing to work on it! It's a work of art.

Maybe I'm just doing something wrong since I can't find documentation on it yet. I'm attempting to use the gradient field but it doesn't seem to affect the elements.

There isn't an error.

If I try to set the property as background then it just adds css for `background: Array` for the specified element.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Kirki 3.0.3

I did try the develop branch but it doesn't fix it.

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))

```
		Ty2u_Kirki::add_config( 'ty2u_theme', array(
			'option_type' => 'theme_mod',
		) );

		Ty2u_Kirki::add_field( 'ty2u_theme', array(
			'type'        => 'gradient',
			'settings'    => 'menu_bar_background',
			'label'       => esc_attr__( 'Menu Bar Background Color', 'ty2u' ),
			'description' => esc_attr__( 'Set the main menu bar background color gradient.', 'ty2u' ),
			'help'        => esc_attr__( 'The colors you set here apply to the menu bar background.', 'ty2u' ),
			'panel'       => 'nav_menus',
			'section'     => 'menu_styles',
			'priority'    => 1,
			'default'     => array(
				'start' => array(
					'color'    => '#A9A9A9',
					'position' => 0,
				),
				'end'   => array(
					'color'    => '#7A7A7A',
					'position' => 100,
				),
				'angle' => 0,
				'type'  => 'linear',
			),
			'choices'     => array(
				'alpha'     => true,
				'direction' => 'top-to-bottom',
			),
			'output'      => array(
				array(
					'element'  => '.nav-menu',
				),
			),
		) );
```

**Comment by aristath** [comment]
The gradient control is still a work in progress.
It's not yet complete which is why it's still undocumented and there's no mention of it anywhere. 👍 
It will be functional in version 3.1

**Comment by ghost** [comment]
Awesome! thanks :smiley:

**Comment by aristath** [comment]
To see a preview of the control in its current state you can add something like this:
```php
Kirki::add_field( '_s', array(
    'type'        => 'gradient',
    'settings'    => 'gradient_preview',
    'label'       => __( 'Control', 'text-domain' ),
    'section'     => 'theme_options',
    'priority'    => 999,
    'default'     => array(
        'angle' => 0,
        'start' => array(
            'color'    => '#333333',
            'position' => 10,
        ),
        'end'   => array(
            'color'    => '#cc0000',
            'position' => 100,
        ),
    ),
) );
```
The input fields available are:
* Angle
* Start Color
* Start Position
* End Color
* End Position

There will also be a linear/radial switch added and the layout of the input fields will probably change, I don't particularly like the way it looks right now.

This is a first draft of the control, so don't expect output etc to properly work as this is a WIP.

**Comment by aristath** [comment]
@ty2u the gradients control are now functional, with the exception of postMessage (right now it forces the `refresh` mode until I add scripts for postMessage there.
`output` works properly.

**Comment by DannyCooper** [comment]
@aristath Is the gradient control deprecated?

**Comment by aristath** [comment]
> @aristath Is the gradient control deprecated?

It was never officially added or supported. It was just an experiment that never lead anywhere...

**Comment by DannyCooper** [comment]
Related: https://github.com/aristath/kirki/issues/1757
