### ISSUE TITLE
Add text/html between sections or panels?

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1415]
### Issue description:
Is it possible to add some html between sections? Like so: 

![image](https://user-images.githubusercontent.com/18515722/27491518-6c9d8ea8-584b-11e7-89ff-510af2841a56.png)

Thanks so much!

**Comment by aristath** [comment]
It's possible using the new nested sections.
I'll post an example later today.

**Comment by runnickrun** [comment]
Hey @aristath, 
did you have a chance to figure this out? 

Thanks!

**Comment by runnickrun** [comment]
I actually figured it out myself. But there are new questions though: 
1. Do you need to add a control to the section, otherwise it is hidden?
2. Is it possible to attach a class to the section to target it in CSS? Because I'd like to have regular expanded and expanded-for-separating and they both have the same class.

```
//Intersection
Kirki::add_section( 'intersection', array(
	'title'          => __( 'Big options' ),
	'description'    => __( 'Global options for the site' ),
	'capability'     => 'edit_theme_options',
	'type' => 'expanded'
) );

//Needed to show that section?
Kirki::add_field( 'ipetri', array(
	'type'        => 'custom',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'intersection',
	'default'     => esc_html__( 'You can enter custom markup in this control and use it however you want', 'my_textdomain' ),
	'priority'    => 10,
) );
```

**Comment by aristath** [comment]
> Do you need to add a control to the section, otherwise it is hidden?

Yes.

> Is it possible to attach a class to the section to target it in CSS? Because I'd like to have regular expanded and expanded-for-separating and they both have the same class.

All sections have unique ID, you can just use that :)

**Comment by ravishakya** [comment]
I have found a work around for that. You can create a new control and return an empty string and the control will be hidden. here is the code

    // Add new control
    add_action( 'customize_register', function( $wp_customize ) {

	    class Hotelica_blank_content extends WP_Customize_Control {
		public $type = 'notice';
		public function render_content() { 
			echo '';
		}
	    }

	    // Register our custom control with Kirki
	    add_filter( 'kirki/control_types', function( $controls ) {
		$controls['notice'] = 'Hotelica_blank_content';
		return $controls;
	    } );

    } );

    // if you are using nested panels or sections then a blank field is needed
    Kirki::add_field( 'my_theme', array(
        'type'     => 'notice',
        'section'  => 'homepage_settings',
    ));
