### ISSUE TITLE
Exclude in multicolor

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1416]
### Issue description:
While I've overcome the similar problem with a background field, I just cannot get exclude to work on the multicolor. Please can you look where's the mistake?

### Version used:
 develop branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

        Kirki::add_field( 'MYTHEME', array(
            'settings'    => 'link_color',
            'section'     => 'SET_SECTOION',
            'type'        => 'multicolor',
            'label'       => esc_html__( 'Links color', 'mt' ),
            'priority'    => 10,
            'choices'     => array(
                'color'   => esc_html__( 'Color',  'mt' ),
                'hover'   => esc_html__( 'Hover',  'mt' ),
                'active'  => esc_html__( 'Active', 'mt' ),
            ),
            'default'     => array(
                'color'   => '#5B9fcc',
                'hover'   => '#ccc',
                'active'  => '#ddd',
            ),
            'transport'   => 'auto',
            'output'    => array(
                array(
                    'choice'    => 'color',
                    'element'   => 'a',
                    'property'  => 'color',
                    'exclude'   => array(
                                       array(
                                           'color'  => '#5B9fcc',
                                           'hover'  => '#ccc',
                                           'active' => '#ddd'
                                       ), 
                                    ),
                ),
                array(
                    'choice'    => 'hover',
                    'element'   => 'a:hover',
                    'property'  => 'color',
                ),
                array(
                    'choice'    => 'active',
                    'element'   => 'a:focus',
                    'property'  => 'color',
                ),
            ),
        ) );

I've tried setting the `exclude` option for each `choice`, but that didn't work as well.
Thanks!

**Comment by aristath** [comment]
It was a matter of sanitization.
If I use this for `default`:
```php
'default'     => array(
    'color'   => '#5b9fcc',
    'hover'   => '#cccccc',
    'active'  => '#dddddd',
),
```
and this for `exclude` it works:
```php
'exclude'   => array(
    array(
        'color'  => '#5b9fcc',
        'hover'  => '#cccccc',
        'active' => '#dddddd'
    ), 
),
```

However, I see that I failed to take into account cases where `choice` is used, so I just pushed another commit that will allow you to do this:
```php
'output'    => array(
    array(
        'choice'    => 'color',
        'element'   => 'a',
        'property'  => 'color',
        'exclude'   => array(
            '#5b9fcc',
        ),
    ),
    array(
        'choice'    => 'hover',
        'element'   => 'a:hover',
        'property'  => 'color',
        'exclude'   => array(
            '#cccccc',
        ),
    ),
    array(
        'choice'    => 'active',
        'element'   => 'a:focus',
        'property'  => 'color',
        'exclude'   => array(
            '#dddddd',
        ),
    ),
),
```
In other words, if you have a `choice` defined, then in the `exclude` argument you can either use a full array of the control's value - in which case it will check if all sub-values are true and only then will it exclude it, OR you can use an array of sub-values, in which case if it's equal to one of them it will be excluded.
