### ISSUE TITLE
after upgrade kirki is not working

### ISSUE THREAD

**Issue by gregory256** [themeum/kirki#1417]
### Issue description:
After upgrade I get this error:
Warning: array_values() expects parameter 1 to be array, null given in public_html/test/wp-includes/script-loader.php on line 988 Warning: array_values() expects parameter 1 to be array, null given in /test/wp-includes/script-loader.php on line 989 Warning: array_values() expects parameter 1 to be array, null given in /public_html/test/wp-includes/script-loader.php on line 992 Warning: array_values() expects parameter 1 to be array, null given in public_html/test/wp-includes/script-loader.php on line 993 Warning: array_values() expects parameter 1 to be array, null given in /public_html/test/wp-includes/script-loader.php on line 994 Fatal error: Call to a member function is_rtl() on null in /public_html/test/wp-includes/script-loader.php on line 997 

I did tried to uninstall the plugin and install fresh but it not helped

### Version used:
3.0.3 and 3.0.4

### Using theme_mods or options?
child theme of MaxStore Pro

**Comment by aristath** [comment]
There is only 1 instance of the `array_values` function in the Kirki plugin.

If the problem you're having was being caused by Kirki, then this last commit will take care of it (added a check for `is_array()` before calling the `array_values()` function).

**Comment by gregory256** [comment]
Thanks, the problem was in new Woocomerce 3.0.9 and now it works fine
