### ISSUE TITLE
'transport' => 'auto', doesn't work anymore with typography.

### ISSUE THREAD

**Issue by CodeCurosity** [themeum/kirki#1419]
I am using the latest build from https://wordpress.org/plugins/kirki/ and even tried the develop branch but still doesn't work, previously it used to work just fine but with 3+ doesn't work.

**Comment by vlthemes** [comment]
What happens with transport auto?

**Comment by CodeCurosity** [comment]
There is no page refresh, the changes are seen instantly.

**Comment by vlthemes** [comment]
Wow. awesome. thx

**Comment by vlthemes** [comment]
I just tried it, and it works on typography.

**Comment by CodeCurosity** [comment]
Which version are you using and can you share your code?

**Comment by vlthemes** [comment]
```
$priority = 0;

Kirki::add_field('osmos_customize', array(
	'type' => 'typography',
	'settings' => 'h1_typography',
	'label' => esc_html__('H1 Typography', 'osmos'),
	'section' => 'typography_headings',
	'priority' => $priority++,
    'transport' => 'auto',
	'default' => array(
		'font-family' => 'aktiv-grotesk',
		'variant' => 'regular',
		'font-size' => '40px',
		'line-height' => '1.9',
        'letter-spacing' => '0.05rem',
		'color' => '#000000',
		'text-transform' => 'none'
	),
	'output' => array(
		'element' => 'h1, .h1'
	)
));
```
Im using the latest dev version.

**Comment by UsmanShahzad** [comment]
Here is my code and it works just fine with ver 2 but doesn't work with 3+

`Kirki::add_field( 'gravity_designer', array(
	'type'        => 'typography',
	'settings'    => 'title_typography_1',
	'label'       => esc_attr__( 'Form Title', 'kirki' ),
	'section'     => 'form_typography_1',
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '1',
		'subsets'        => array( 'latin-ext' ),
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left'
	),
	'transport' => 'auto',
	'priority'    => 10,
	'output'      => array(
		array(
			'element' => 'body #gform_wrapper_' . $form1id . " .gform_heading .gform_title",
			'suffix'   => ' !important',
		),
	),
	
) );`

**Comment by CodeCurosity** [comment]
Thanks, i will look at the code later.

**Comment by CodeCurosity** [comment]
I tried using your code but only font option works, still doesn't change the color or other options.

**Comment by aristath** [comment]
Instead of this:

```php
'output' => array(
	'element' => 'h1, .h1'
)
```
Try this:
```php
'output' => array(
	array(
		'element' => 'h1, .h1',
	),
),
```
The output argument should _always_ be an array of arrays.

**Comment by aristath** [comment]
Seems to be working fine now in the develop branch so I'll go ahead and close this one.
If you're still having issues feel free to reopen this one or just post an update with details about the code you're using and what doesn't work.
