### ISSUE TITLE
Translations, i18n and l10n

### ISSUE THREAD

**Issue by grappler** [themeum/kirki#142]
The text domain has not been registered but a text domain is being used.

Either the translations should be collected in the framework like is done in Redux or you should recommend the theme authors to replace the text domain with their own like done in Options Framework.

**Comment by grappler** [comment]
Unfortunately this is not enough. You need to use `load_textdomain()` and create a languages folder and create a POT file.

For the theme authors I would really really recommend that they change the text domain when including the framework in the theme. The TRT only allows a maximum of two different text domains in a theme. The reason for this is that in the future WordPress.org will provide a platform for all themes and plugins to be translated on translate.wordpress.org. The POT generator on w.org will pull all of the strings regardless of the text domain.

A third option I forgot to mention is allow the strings be defined from a variable like in [TGMPA](http://tgmpluginactivation.com/)

**Comment by aristath** [comment]
crap, you're absolutely right... I completely forgot about that.

I'll push this in a few minutes, writing it now.

**Comment by aristath** [comment]
OK, I think I got everything this time.
If not then please do let me know...

Users will now be able to change the textdomain like this:

``` php
function custom_change_kirki_textdomain( $options ) {

  $options['textdomain'] = 'my-domain';
  return $options;

}
add_filter( 'kirki/config', 'custom_change_kirki_textdomain', 99 );
```

**Comment by grappler** [comment]
Unfortunately that will not be allowed on dotorg. The requirement is that the text domain should be a slug and not a variable or constant.

What I meant earlier about the variable was something like this:

``` php
$options['strings'] = array (
    'all'               => __( 'All', 'text-domain' ),
    'cyrillic'         => __( 'Cyrillic', 'text-domain' ),
    'cyrillic-ext'   => __( 'Cyrillic Extended', 'text-domain' ),
    'devanagari' => __( 'Devanagari', 'text-domain' ),
    'greek'          => __( 'Greek', 'text-domain' ),
    'greek-ext'    => __( 'Greek Extended', 'text-domain' ),
    'khmer'         => __( 'Khmer', 'text-domain' ),
    'latin'             => __( 'Latin', 'text-domain' ),
    'latin-ext'       => __( 'Latin Extended', 'text-domain' ),
    'vietnamese' => __( 'Vietnamese', 'text-domain' ),
);

public function get_google_font_subsets() {
    return array(
        'all'               => $options['strings']['all'],
        'cyrillic'         => $options['strings']['cyrillic'],
        'cyrillic-ext'   => $options['strings']['cyrillic-ext'],
        'devanagari' => $options['strings']['devanagari'],
        'greek'          => $options['strings']['greek'],
        'greek-ext'    => $options['strings']['greek-ext'],
        'khmer'         => $options['strings']['khmer'],
        'latin'             => $options['strings']['latin'],
        'latin-ext'       => $options['strings']['latin-ext'],
        'vietnamese' => $options['strings']['vietnamese'],
    );
}
```

**Comment by aristath** [comment]
Fixed. I'm updating the docs now and releasing a new version on w.org

**Comment by grappler** [comment]
Thank you for making the changes! :smile:

**Comment by aristath** [comment]
Thank you for being so thorough with your reviews...

I wouldn't have been able to fix these issues without your advice.
I owe you a beer! :beer: perhaps in WCEU if you're there.

**Comment by grappler** [comment]
I won't be able to make this year but perhaps in 2016 then.

**Comment by liveweb22** [comment]
Hi, how change kirki text domain with my own domain? 

WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs. The domains found are kirki, kc.

**Comment by mapsteps** [comment]
It's safe to use up to 2 different text domains in the WordPress repository. This warning is safe to be ignored @liveweb22. We do the same in our Page Builder Framework theme for instance. Alternatively, you can manually replace all kirki textdomains with your own.
