### ISSUE TITLE
Kirki plugin does not delete when bundled in theme

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1421]
### Issue description:
If kirki bundled in theme and there is plugin and if user want to delete it. it display message 'You cannot delete a plugin while it is active on the main site.'. May be core WP issue but please check it.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.4

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
--
![kirki-not-delete](https://user-images.githubusercontent.com/9743287/27509395-ad12c4ca-5919-11e7-8729-ee9476ccf0f7.png)

**Comment by rinkuyadav999** [comment]
This does not happen with 'Hello Dolly' plugin.

**Comment by tsquez** [comment]
I just downloaded `Outlook Pro` https://www.wpfreeware.com/outlook-pro/ which has Kirki bundled with it and I also have the Kirki plugin itself installed but not activated.

I activated the theme and checked to make sure the actual Kirki plugin was not activated, which, again, it wasn't. 

I then proceeded to delete the kirki plugin with no issues.

**Comment by rinkuyadav999** [comment]
Bundled version is 2.3.7 but test it will latest 3.0.4

**Comment by aristath** [comment]
fixed, will be included in 3.0.5
