### ISSUE TITLE
Default typography values

### ISSUE THREAD

**Issue by nk-o** [themeum/kirki#1423]
### Issue description:
When I tried to add 1 element of typography control (font-size or so), the CSS generates all available styles:
![image](https://user-images.githubusercontent.com/14810891/27516130-c6ce9c70-59bb-11e7-8773-0147fc727e16.png)

It is replaced my default text color from the main CSS file to #ffffff, that is not ok:
![image](https://user-images.githubusercontent.com/14810891/27516134-f8d1ce22-59bb-11e7-9fab-f02c6cd44e9a.png)

Also, I got this error and no auto-reload working:
![image](https://user-images.githubusercontent.com/14810891/27516216-3f59e29c-59be-11e7-8893-5d5ef352498b.png)

### Version used:
3.0.4 release

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_config('test', array(
    'capability' => 'edit_theme_options',
    'option_type' => 'theme_mod',
));

Kirki::add_section('typography', array(
    'title' => esc_html__('Typography', 'test'),
    'priority' => 11
));

Kirki::add_field('test', array(
    'type' => 'typography',
    'settings' => 'typography_html',
    'label' => esc_attr__('HTML', 'test'),
    'section' => 'typography',
    'default' => array(
        'font-size' => '15px'
    ),
    'priority' => 10,
    'output' => array(
        array(
            'element' => 'html',
        ),
    ),
    'transport' => 'auto'
));
```

**Comment by aristath** [comment]
Fixed, can you please test using the development branch from this repository?

**Comment by nk-o** [comment]
With the latest commits from the `master` branch it is working ok. With code from the `develop` branch - nothing changed.

Thank you.

**Comment by aristath** [comment]
Yeah, I just pushed the commits to the wrong branch... fixing that as we speak. 👍 

Glad it works now. Relieved actually... 😄
