### ISSUE TITLE
Lot's of PHP warnings after update to 3.05

### ISSUE THREAD

**Issue by antek83** [themeum/kirki#1428]
### Issue description:
After updating the plugin to V 3.05 I've got the following warnings:

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_CSS' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Customizer_Styling' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Icons' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Reset' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Tooltips' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Customizer_Branding' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_PostMessage' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Selective_Refresh' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Field_Dependencies' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Custom_Sections' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: call_user_func() expects parameter 1 to be a valid callback, function 'Kirki_Modules_Webfonts' not found or invalid function name in C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php on line 90

( ! ) Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at C:\wamp\www\antares\wp-content\plugins\kirki\core\class-kirki-modules.php:90) in C:\wamp\www\antares\wp-content\plugins\resize-images-before-upload\resize-images-before-upload.php on line 14

Fatal error: Uncaught Error: Class 'Kirki_Fonts' not found in C:\wamp\www\antares\wp-content\themes\antares\inc\antares-extend-customizer.php on line 18

Error: Class 'Kirki_Fonts' not found in C:\wamp\www\antares\wp-content\themes\antares\inc\antares-extend-customizer.php on line 18

### Version used:
3.05

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

Antares_Kirki::add_config( 'antares', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

```
Antares_Kirki::add_field( 'antares', array(
    'type'        => 'select',
    'setting'     => 'heading_font_family',
    'label'       => __( 'Heading Font Family', 'antares' ),
    'description' => __( 'Please choose a font for your site. This font-family will be applied to heading elements on your page.', 'antares'),
    'section'     => 'typography',
    'default'     => 'Montserrat',
    'priority'    => 10,
    'choices'     => Kirki_Fonts::get_font_choices(),
    'output'      => array(
        array(
            'element'  => 'h1, h2, h3, h4, h5, h6',
            'property' => 'font-family',
        ),
    ),
    'transport'   => 'refresh',
    'js_vars'     => array(
        array(
            'element'  => 'h1, h2, h3, h4, h5, h6',
            'function' => 'css',
            'property' => 'font-family',
        ),
    ),
) );
```
I assume the Kirki_Fonts class has been deprecated and I will need to switch to the Typography field.
But I cannot understand what happened that triggered all the other errors after the update.

Any idea?

**Comment by aristath** [comment]
Already fixed and released 3.0.6, it was a typo

**Comment by aristath** [comment]
The problem is that even though fixes are applied within seconds they are discovered, it takes more than 15 minutes to manage and upload on wordpress.org via SVN.

Can you please test 3.0.6 real quick and make sure it's ok for you now?

**Comment by antek83** [comment]
Sure, I switched the core folder with the develop branch and it worked fine. I'll update to 3.06 when available in the Updater. Thanks a lot and sorry to have bothered you again

**Comment by aristath** [comment]
Thanks for checking! 👍
