### ISSUE TITLE
Sanitize options

### ISSUE THREAD

**Issue by grappler** [themeum/kirki#143]
I see you are having trouble sanitizing [select](https://github.com/aristath/kirki/blob/master/includes/class-kirki-setting.php#L94) and [radio](https://github.com/aristath/kirki/blob/master/includes/class-kirki-setting.php#L91) options.

It seems like this article explains a way you can do it. http://cachingandburning.com/wordpress-theme-customizer-sanitizing-radio-buttons-and-select-lists/

Like I mentioned I am doing a theme review and I can't approve the theme till this is fixed.

**Comment by aristath** [comment]
All the issues you posted just got fixed in the develop branch. :+1:
