### ISSUE TITLE
No Google font links were embedded

### ISSUE THREAD

**Issue by sophy** [themeum/kirki#1430]
### Issue description:
No Google Font Link was embedded.

The problem in method `get_url_contents` of `Kirki_Modules_Webfonts_Embed` class. The problem is:

```php
  if ( ! isset( $response['response'] ) || 200 !== $response['response'] ) {
	return false;
}
```
But `$response['response']` return array below so it always return `fale`.

```php
Array
(
    [code] => 200
    [message] => OK
)
```

### Using theme_mods or options?: 

Use in custom plugin.

**Comment by aristath** [comment]
You're right, I don't know how I missed this...
Added in 3.0.7, will be released later today.
