### ISSUE TITLE
preview of color control doesn't work 

### ISSUE THREAD

**Issue by dylan-ngo11** [themeum/kirki#1435]
### Issue description:
Hi! When I activate kirki and Woocommerce plugin. The control color doesn't work.
Can you check it?
Thanks!
### Version used:
WP 4.8
Kirki 3.0.7
Woocommerce 3.0.9

**Comment by aristath** [comment]
@duongancol hey there!
I just tested this and didn't see any conflicts, everything loads fine.
Perhaps there's a 3rd party that affects this as well?
Can you please try deactivating your other plugins one by one and see if one of the combinations of **Kirki + WooCommerce + Other plugin** is what causes this issue?

**Comment by dylan-ngo11** [comment]
I'm sorry, I activated kirki plugin only and it still didn't work so I think it's not the conflict with Woocommerce plugin. 
Actually the preview of color control doesn't work. I made a video [here](https://monosnap.com/file/rhEeIj26tSGfDQHs1z9zuwXJNflt6V)
And here is the code that I use
```
TopSeo_Kirki::add_field( 'topseo', array(
	'type'      => 'color',
	'settings'  => 'primary_color',
	'label'     => esc_attr__( 'Primary color', 'topseo' ),
	'description' => esc_attr__( 'Choose color', 'topseo' ),
	'section'   => 'colors',
	'default'   => '#27ae61',
	'priority'  => 1,
	'transport' => 'auto',
	// output
	'output' => array(
```
Thanks!

**Comment by aristath** [comment]
oh, ok... so the controls don't have a problem.
Can you please post the COMPLETE code of the control you're using?

**Comment by dylan-ngo11** [comment]
It's very long code so I upload a file [here](https://drive.google.com/file/d/0B2YzET39Ww4WbDBvTWF3N0g3aW8/view?usp=sharing)

**Comment by notrealdev** [comment]
Hi @aristath I have the same error

Please test this code(working):
```php
Kirki::add_field( 'my-theme', array(
    'type'      => 'color',
    'settings'  => 'setting_color',
    'label'     => esc_attr__( 'Color', 'text' ),
    'section'   => 'general',
    'default'   => '#888888',
    'transport' => 'auto',
    'output' => array(
        array(
            'element' => 'html, body, h1, h2, h3, h4, h5, h6',
            'property' => 'background-color'
        )
    ),
));
```

and(not working):
```php
Kirki::add_field( 'my-theme', array(
    'type'      => 'color',
    'settings'  => 'setting_color',
    'label'     => esc_attr__( 'Color', 'text' ),
    'section'   => 'general',
    'default'   => '#888888',
    'transport' => 'auto',
    'output' => array(
        array(
            'element' =>
                 'html,
                 body,
                 h1,
                 h2,
                 h3,
                 h4,
                 h5,
                 h6', /*not working on kirki 3.x*/
            'property' => 'background-color'
        )
    ),
));
```

**Comment by aristath** [comment]
This is wrong:

```php
'element' =>
                 'html,
                 body,
                 h1,
                 h2,
                 h3,
                 h4,
                 h5,
                 h6',
```
It should either be like this:
```php
'element' => 'html, body, h1, h2, h3, h4, h5, h6',
```

or preferably like this:
```php
'element' => array(
	'html',
	'body',
	'h1',
	'h2',
	'h3',
	'h4',
	'h5',
	'h6',
),
```
If it worked the way you posted it in previous versions, then previous versions had a bug that allowed it.

**Comment by dylan-ngo11** [comment]
Thank you!
