### ISSUE TITLE
Remove Web Font Loader `Kirki_Modules_Webfonts_Async`

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#1437]
### Issue description:

I am using a Select field for font choices and used the typography portion of https://github.com/devinsays/customizer-library to load fonts since I could make a list and choose variants. In 2.3.8 and earlier, all was fine and I didn't get the font-face in my inline CSS. It works still but I get this inline font-face CSS.

**How to I remove the inline font-face CSS only?**

```
@font-face {
  font-family: 'Alegreya';
  font-style: normal;
  font-weight: 400;
  src: local('Alegreya Regular'), local('Alegreya-Regular'), url(https://fonts.gstatic.com/s/alegreya/v8/jvx_POxM6YeT6dBBhDfmufesZW2xOQ-xsNqO47m55DA.ttf) format('truetype');
}
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  src: local('Raleway'), local('Raleway-Regular'), url(https://fonts.gstatic.com/s/raleway/v11/bIcY3_3JNqUVRAQQRNVteQ.ttf) format('truetype');
}
```

### Version used:
3.0.8

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please test now?

**Comment by carasmo** [comment]
Beautiful! Thank you so much.

**Comment by aristath** [comment]
Great! Closing this one 👍
