### ISSUE TITLE
the google font doesn't load

### ISSUE THREAD

**Issue by donqq** [themeum/kirki#1440]
### Version used:
3.0.8

### Using theme_mods or options?
Setwood

### Code to reproduce the issue (config + field(s))
just update the kirki to the 3.0.8 and try to set the font, it does show in the preview, but in the normal view, even though the font is set, it doesn't load frot google.

**Comment by donqq** [comment]
just rolled back to 3.0.7 and the font issue was resolved, but I hope this version's problem will be solved too, as it's the latest version.

**Comment by aristath** [comment]
@stormyqq I'm afraid I don't have access to the "Setwood" theme, could you pelase send it over so that I may replicate this issue and fix it?
You can send me a dropbox link, or google-docs on my email (you can find it on my profile page here on github).

**Comment by aristath** [comment]
Using other themes it seems to be working fine so I'm wondering what this is... 😟

**Comment by donqq** [comment]
It's a paid theme, I am not sure I am allowed to do it.

**Comment by aristath** [comment]
In the context of providing support I'm sure the theme author wouldn't mind.
However if you don't want to send it I can totally understand and respect that, it's only natural.
But in that case I'm not sure there's much I can do... Have you tried contacting the theme author?

**Comment by donqq** [comment]
not yet, I don't mind to send you, if you keep it only for yourself and not use it for anywhere else for other purposes. do you have an email or something?

**Comment by aristath** [comment]
Actually, the theme author has already sent it (so we know he doesn't mind), but I've got version 1.0.0, and from what I can see version 1.5.2 is now available.
Can you send me a copy of the latest version so that I may solve this one and release a new version?
And of course this is for support use only and nothing is ever shared.

**Comment by donqq** [comment]
okay I will send it to your ar******@gmail.com email 👍

**Comment by aristath** [comment]
Don't send it as an attachment, gmail blocks them.
Instead upload to dropbox or google-drive (or any similar service) and send me a link so I can download it

**Comment by donqq** [comment]
yeah I only sent the link :)

**Comment by aristath** [comment]
I installed and activated the theme and Kirki 3.0.8
Went to Customizer > Typography Settings > Body, and there I selected a random font in the typography control.
The preview changed to show the font I selected, I then saved it, went to the frontend of the site, and the font was still showing fine there.

Is this issue you're having on ALL typography controls, or a specific one? Is it the font-family that has an issue, or another property like for example font-weight, line-height etc?

**Comment by donqq** [comment]
The problem is only in the sidebar, navigation bar's fonts, not the body fonts. The font is actually set, but I think it doesn't load for some reason.

**Comment by donqq** [comment]
oh haha I think I found the problem, I am not sure this is the exact problem, but I could REPRODUCE the problem. I checked this option in autoptimize, so I unchecked it and now it works fine, strangely the previous version did work without even unchecking it. 👍 
Thanks anyway for taking time to help :)

Remove Google Fonts?	

>  Check this if you don't need or want Google Fonts being loaded.

**Comment by aristath** [comment]
👍 OK, that makes sense then. 
I was going back and forth, looking at the theme's code and couldn't find anything wrong or any difference between 3.0.7 and 3.0.8... It was driving me crazy.

So I'm guessing we can close this issue?

The previous version was using a different method to load the googlefonts which was faster, but some users reported issues so I reverted to a more "standard" method to load googlefonts.
This is a temporary measure until I manage to resolve the issues others reported with the new - and improved - googlefonts loading method. 😄
