### ISSUE TITLE
Wordpress error cannot open site

### ISSUE THREAD

**Issue by pattayaearl** [themeum/kirki#1441]
### Issue description:

Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /wp-content/plugins/kirki/core/class-kirki-modules.php on line 88

### Version used:
3.0.0

### Code to reproduce the issue (config + field(s))

foreach ( self::$modules as $key => $module_class ) {
			if ( class_exists( $module_class ) ) {
				self::$active_modules[ $key ] = $module_class::get_instance();
			}

**Comment by aristath** [comment]
Hey there!
Have you tried updating to the latest version? We're currently on 3.0.8, and this issue has already been fixed
