### ISSUE TITLE
Expanded section bug with shortcut edit links

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1442]
### Issue description:
I'm using a section with 'type' => 'expanded', though clicking on the edit link in the frame seem not to understand this type yet 

![shortcut](http://g.recordit.co/KSgapwvLGX.gif)

### Version used:
3.0.8

### Using theme_mods or options?
themee_mods

### Code to reproduce the issue (config + field(s))

`Kirki::add_field( 'ipetri', array(
	'type'     => 'text',
	'settings' => 'header_phone',
	'label'    => __( 'Phone', 'my_textdomain' ),
	'section'  => 'header',
	'priority' => 10,
	'transport' => 'postMessage',
	'partial_refresh' => array(
		'header_phone' => array(
			'selector'        => '.phone__number',
			'render_callback' => function() {
				return get_theme_mod('header_phone');
			},
		)
	),
) );`

**Comment by aristath** [comment]
👍 Marking as a bug. I haven't found a solution to this one yet though, so not sure it will make it in the next version.

**Comment by runnickrun** [comment]
It's a pity, very promising one. Going back and forth with native WP panels is a pain, I don't know why they implemented it that way. Expanded sections though would reduce the effort significantly. Personally I hope you would figure it out!

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
