### ISSUE TITLE
How to inline options or combine multiple in one?

### ISSUE THREAD

**Issue by themenow** [themeum/kirki#1444]
### Issue description:

I want to create a `width x height` option, currently I do that by adding two `number `options, then using CSS to inline them, which is inconvenient and not re-usable. Is there already a method to handle needs like this?

And is it possible to remove the spinner?

**Comment by antek83** [comment]
just shooting in the dark here but maybe you could use the spacing control for that, if it works it's kind of a hack but I will give it a try... im curious

**Comment by themenow** [comment]
I'd like to use spacing control, but how to make it accept px only? rem,em,%, etc. is not working in this case.

**Comment by aristath** [comment]
If you want strictly numeric fields (without units), then no, unfortunately Kirki doesn't have a field like that.

But just out of curiosity, why won't rem/em etc work in your case?

**Comment by themenow** [comment]
That is for creating an image size, so px is obliged.

**Comment by aristath** [comment]
hmmm... I see.
In that case, your best option would be to create a custom control, or just do it using multiple controls like you do now

**Comment by themenow** [comment]
Gotcha, thanks!
