### ISSUE TITLE
Autolader fails under linux

### ISSUE THREAD

**Issue by gniewomir** [themeum/kirki#145]
strtolower function in autoloader causes problems in case-sensitive enviroment. Autoloader tries to get 'config.php' instead 'Config.php', and fails to load requested class. 

```
spl_autoload_register( function( $class ) {
    if ( stripos( $class, 'Kirki' ) === 0 ) {
    @include( KIRKI_PATH . DIRECTORY_SEPARATOR . 'includes' . str_replace( '\\', DIRECTORY_SEPARATOR, strtolower( substr( $class, strlen( 'Kirki' ) ) ) ) . '.php' );
}});
```

**Comment by aristath** [comment]
Thanks!

**Comment by gniewomir** [comment]
No problem, when i find some more time i will try to contribute more to kirki development - it saved me few days lately. ;)
