### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activate' of undefined

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1450]
I am using radiobutton set and it is working when i click first time but it generates this error and then in second click it does not work.

![Image of error](https://s14.postimg.org/uopatrmpd/Untaitled-1.jpg)

**Comment by danielortiz** [comment]
code to reproduce would be nice. I tested here and it worked just fine

**Comment by aristath** [comment]
@ravishakya I can't replicate this one either 🤔

**Comment by ravishakya** [comment]
I have created a gist check this out https://gist.github.com/ravishakya/dbb12c97ddb094505a2866d04098f51f

I also found where the problem is. When you delete this code in the gist it works.

    Kirki::add_field( 'my_theme', array(
		'type'        => 'text',
		'settings'    => 'slider_animationSpeed',
		'label'       => esc_html__( 'Animation Speed', 'hotelica' ),
		'section'     => 'header_settings',
		'default'     => 600,
		'description' => esc_html__( 'Set the speed of animations, in milliseconds', 'hotelica' ),
		'active_callback'    => array(
			array(
				'setting'  => 'option_banner_slider',
				'operator' => '==',
				'value'    => 'slider',
			),
		),
	) );

**To recreate the error** 

1. Goto Theme Options > Homepage Settings > Banner / Slider.
2. There is radio buttonset **Banner / Slider**
3. First time you change it, it will work but it will also give you error on the console. and second time you try to change it wont work.

Hope to get answer soon

**Comment by ravishakya** [comment]
Any updates on this ?

**Comment by aristath** [comment]
The problem here is the setting name.

`slider_animationSpeed` is invalid, it should be `slider_animation_speed`.
Once you change that everything works fine 👍

**Comment by ravishakya** [comment]
That worked but still confused how can one uppercase make it not work.
