### ISSUE TITLE
Checkbox field stopped working

### ISSUE THREAD

**Issue by danielortiz** [themeum/kirki#1462]
### Issue description:
Checkbox fields stopped working on the develop branch. They're working fine on master

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
10.0.9

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_section( 'test_section', array(
	'title'          => __( 'Test section' ),
	'priority'       => 160,
	'capability'     => 'edit_theme_options',
	'theme_supports' => '', // Rarely needed.
) );

Kirki::add_field( 'my_config', array(
	'type'        => 'checkbox',
	'settings'    => 'checkbox_test',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'test_section',
	'default'     => '1',
	'priority'    => 10,
) );
```

I will try to dig this one tomorrow. 3AM here in Brazil 😪

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/dc04accf885227f7993e61ea90b18f595a5a1c7d
