### ISSUE TITLE
Custom controls that don't use JS rendering don't work anymore

### ISSUE THREAD

**Issue by danielortiz** [themeum/kirki#1465]
### Issue description:
when I pushed this #1455   I wasn't aware that `register_control_type` method is only used when one wants to use JS template rendering through `content_template()`. So now that every  field is registered, the ones that use php template stopped working

**Check here:**
https://developer.wordpress.org/reference/classes/wp_customize_manager/register_control_type/
https://make.wordpress.org/core/2014/11/17/jsunderscore-template-rendered-custom-customizer-controls-in-wordpress-4-1/

**Comment by aristath** [comment]
Hmmmm....
I assume you're referring to this code? https://github.com/aristath/kirki/blob/3.0.9/core/class-kirki-init.php#L159-L177

**Comment by danielortiz** [comment]
Oops. Just noticed I linked the wrong commit. Yea, that's the one

**Comment by aristath** [comment]
Should be fixed now.
If a custom control uses a JS template, you should register it manually using
```php
add_action( 'customize_register', function( $wp_customize ) {
    $wp_customize->register_control_type( 'My_Control_Class' );
});
```
This is the way it always used to work so we shouldn't have any backwards-compatibility issues either. 

Can you please verify that this works ok for you now? 👍
