### ISSUE TITLE
Repeater change "rows" to something else

### ISSUE THREAD

**Issue by antek83** [themeum/kirki#1466]
### Issue description:
Hi @aristath sorry to bother you wth such a silly question.

In the. Repeater field each created block is called row, it's there a filter or an attribute to change it to something relevant to the flield that the user is creating?
It might be: Slide or Button or Section... A little thing like this would make the UX much more enjoyable imho 

Thanks a lot in advance

**Comment by aristath** [comment]
You can use the `row_label` argument.
See https://aristath.github.io/kirki/docs/controls/repeater.html for docs.
