### ISSUE TITLE
Update Google Fonts

### ISSUE THREAD

**Issue by joelbqz** [themeum/kirki#1476]
Hi guys, hope you doing well. Its possible you push a update with new google fonts? For example montserrat have new variations:

https://fonts.google.com/?selection.family=Montserrat:300,400,700|Playfair+Display&query=Montserrat

Take a look,
Thanks!!

**Comment by aristath** [comment]
fonts updated in the develop branch, will be included in the next release.
You can do it yourself too if you want... all you have to do is run `grunt` in the plugin's folder ;)
