### ISSUE TITLE
Array to string conversion when clicking reset button

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#1477]
### Issue description:
Using a couple of dimension fields with default values. Click reset
![screen shot 2017-07-24 at 4 51 41 pm](https://user-images.githubusercontent.com/1124594/28544179-68505152-7090-11e7-9320-660233556ddc.png)
 and I get `` Notice: Array to string conversion in /.../wp-content/plugins/kirki/modules/css/class-kirki-output.php on line 265``

It does not reset the values to the default values, instead it empties them but you only discover this on re-load. So there's nothing there. In the past, don't know which version, the values reset to the default values.

### Version used:

3.0.9

### Using theme_mods or options?

theme_mod

### Code to reproduce the issue (config + field(s))

```
    Theme_Kirki::add_field('theme_prefix', array(
        'settings' => 'logo_height,
        'label' => esc_attr__( 'Logo Height.', 'text-domain'),
        'description' => esc_attr__( 'This height is for small viewports.', 'text-domain'),
        'section' => 'nosh_pro_branding_section',
        'type' => 'dimension',
        'transport' => 'postMessage',
        'priority' => 99,
        'default' => '100px',
        'output' => array(
            array(
                'element' => '.logo > a',
                'property' => 'max-height',
            ),
        ),
        'active_callback' => array(
            array(
                'setting' => 'blog_title_text_or_logo',
                'operator' => '==',
                'value' => 'image',
            ),
        ),
    ));

```

**Comment by aristath** [comment]
Fixed

**Comment by carasmo** [comment]
Thanks!
