### ISSUE TITLE
Having issues with local paths

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#148]
Hi,

Im having a few problems locally, where the plugin can't load the JS and CSS assets.
Looking into it I've noticed that it is trying to load the assets with an invalid path:

```
http://webipack.dev/booklet/wp-content/plugins/Users/luismartins/Sites/webi…v/wp-content/themes/wip-roots/lib/kirki//assets/css/customizer.css?ver=0.5 
```

It is adding my local path to an URI and that will not work.

Worth mentioning this is a site running on a multisite install, perhaps it may have a relation to it.

Any way I can get around this?

**Comment by aristath** [comment]
Hey there!

Are you using Kirki as a plugin, or are you including it in your theme?
If you're including it in your theme, have you defined a `url_path` in your [configuration](http://kirki.org/#configuration)?
What are you using there?

**Comment by lmartins** [comment]
Hi again Aristeides!  Im such a pain in the back hum?! :D

Im embbeding Kirki in my theme and setting the `url_path` like this:

```
'url_path'     => get_template_directory_uri() . '/lib/kirki/',
```

I've already try switching the order my code, so that I would include the library before/after passing the filter `kirki/config` but can't make it behave differently. 

Im also a bit confused with the documentation. I was passing a property `url_path` for the `$args` object, but it seems that now it should be a variable called `$url`, is that correct?
Im asking because the docs refer to both.

I should also point out that no matter what I pass to any of them I can't make the request path to change so something isn't quite right on my code. 

UPDATE:
Please disregard my comment about the vars, just noticed the sample code is using `$url` just to declare the value.

**Comment by lmartins** [comment]
Doing some testing, here's what I found so far.
In the `Dependencies` class the `$controls` var is getting the value im passing through the config filter. For some reason the `$kirki_url` is not getting the correct value, as you can see here:
https://cloudup.com/cyz_Fqzs8_w

EDIT:
Ok, it's the var name that is incorrect. It's declared as `$controls` and it's trying to read a `$config` variable. Still there's something since now everything loads except the CSS. Still looking...

**Comment by lmartins** [comment]
Aristeides, I now managed to have it load all the files but somethings not right yet.
I've found two problems:
1. In dependencies.php you were reading the wrong variable name when setting `$kirki_url`
2. In customizer.php you're not checking for the existence of a `url_path`setting, so it always assumes the default value.

I would do a PR but im not sure my fix is the most efficient way to solve it.

The issue though, is that the customiser UI's still broken:
https://cloudup.com/cPOt9sPPJMK

As far as I can tell those settings are coming from customize.php, so im not sure where to look for next.

Can you help please?

Thanks.

**Comment by replynone** [comment]
Hi there, got the same issue, also got it in my theme without the usage of the plugin methode.

<code >http://website.nl/secret/wp-content/plugins/C:/domains/website.nl/www…cret/wp-content/themes/website/kirki//assets/css/customizer.css?ver=0.5 </code>
serialize.js, customizer.js also got this problem, for some reason tries to load those files from the plugin folder.

i got the latest files from github with these lines in my function.php 
<code>include_once ( dirname( **FILE** ) . '/kirki/kirki.php' );</code>

and ( http://kirki.org/#configuration ): 

<code> function kirki_demo_configuration_sample() {

```
$url  = get_stylesheet_directory_uri() . '/kirki/';

/**
 * If you need to include Kirki in your theme,
 * then you may want to consider adding the translations here
 * using your textdomain.
 * 
 * If you're using Kirki as a plugin then you can remove these.
 */

$strings = array(
    'background-color' => __( 'Background Color', 'kirki' ),
    'background-image' => __( 'Background Image', 'kirki' ),
   .......
);

$args = array(
    'logo_image'   => get_stylesheet_directory_uri() . '/images/logo.png',
    'description'  => __( 'The theme description.', 'kirki' ),
    'url_path'     => $url,
);
return $args;  } add_filter( 'kirki/config', 'kirki_demo_configuration_sample' ); 
```

</code>

So for example the slider does not show etc..

But when installing it as an plugin those 'error' were fixed and all works well.

**Comment by aristath** [comment]
Hey guys! Can you please try the [develop](https://github.com/aristath/kirki/tree/develop) branch and let me know if that fixes it for you?

**Comment by lmartins** [comment]
Sorry, couldn't test this out at home yesterday.
When I switch to dev im getting a 500 with the following in the console:

```
[01-Apr-2015 08:12:45 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /Users/luismartins/Sites/webipack.dev/wp-includes/functions.php on line 4470
[01-Apr-2015 08:12:45 UTC] PHP Stack trace:
[01-Apr-2015 08:12:45 UTC] PHP   1. {main}() /Users/luismartins/Sites/webipack.dev/index.php:0
[01-Apr-2015 08:12:45 UTC] PHP   2. require() /Users/luismartins/Sites/webipack.dev/index.php:17
[01-Apr-2015 08:12:45 UTC] PHP   3. require_once() /Users/luismartins/Sites/webipack.dev/wp-blog-header.php:16
```

To elaborate a little further on what I said above, another site using the same files is working. Not sure what triggered that 500, have to dig a little further. 

Still, even though the files are loaded:
![screen shot 2015-04-01 at 09 34 28](https://cloud.githubusercontent.com/assets/151981/6937302/8be92b1c-d852-11e4-89ad-012f236ec041.png)

The customiser interface itself is quite broken:
![screen shot 2015-04-01 at 09 36 31](https://cloud.githubusercontent.com/assets/151981/6937309/9a3d9d2e-d852-11e4-8c6d-59487e9f9b20.png)

The rule visible in the following screenshot I believe is coming from Kirki, and is setting both the text color and background to black:
![screen shot 2015-04-01 at 09 37 30](https://cloud.githubusercontent.com/assets/151981/6937329/c401167c-d852-11e4-94b5-046930390290.png)

Thanks.

**Comment by replynone** [comment]
hi there!
Deleted the old kirki folder and pasted in the develop one.
<code>
Fatal error: Class 'Kirki_Fonts' not found in C:\domains\reply-none.nl\wwwroot\secret\wp-content\themes\reply-none\inc\customizer.php on line 331
</code>
line 331 = 
<code>
$controls[] = array(
        'type'     => 'select',
        'setting'  => 'base_typography_font_family',
        'label'    => __( 'Font Family', 'example' ),
        'section'  => 'base_typography',
        'default'  => 'Roboto',
        'priority' => 20,
  <strong>      'choices'  => Kirki_Fonts::get_font_choices(), </strong>
        'output' => array(
            'element'  => 'body',
            'property' => 'font-family',
        ),
    );
</code>
'choices'  => Kirki_Fonts::get_font_choices(),  this gives the font error.

So deleted the font choices for some further testing:
 <code>
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'slider' not found or invalid function name in C:\domains\reply-none.nl\wwwroot\secret\wp-includes\plugin.php on line 213
 </code>
 <code>
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'text' not found or invalid function name in C:\domains\reply-none.nl\wwwroot\secret\wp-includes\plugin.php on line 213
</code>

used the '$control' examples from http://kirki.org/#field-types

Hope this will help, good luck.

edit:
the previous issue, load files from the plugin folder was not shown in the console! Seems to load the good ones now.
The slider did show in the theme customizer front-end, but when slided left or right it gave me the warning above. Same with the text field. When edited is gives a warning!

**Comment by lmartins** [comment]
Im rebuilding the affected site to see if I can isolate the issue, where's what I got so far:

```
[01-Apr-2015 09:08:39 UTC] PHP Warning:  Invalid argument supplied for foreach() in /Users/luismartins/Sites/webipack.dev/wp-content/themes/wip-roots/lib/kirki/includes/Helpers/helpers.php on line 31

[01-Apr-2015 09:08:39 UTC] PHP Warning:  Invalid argument supplied for foreach() in /Users/luismartins/Sites/webipack.dev/wp-content/themes/wip-roots/lib/kirki/includes/Scripts/Frontend/GoogleFonts.php on line 22

[01-Apr-2015 09:08:39 UTC] PHP Warning:  Invalid argument supplied for foreach() in /Users/luismartins/Sites/webipack.dev/wp-content/themes/wip-roots/lib/kirki/includes/Styles/Frontend.php on line 178

[01-Apr-2015 09:08:40 UTC] PHP Warning:  Invalid argument supplied for foreach() in /Users/luismartins/Sites/webipack.dev/wp-content/themes/wip-roots/lib/kirki/includes/Scripts/Customizer/PostMessage.php on line 47
```

I got to the point where I have a blank, fully configured site without the 500, so im guessing it's not related to Kirki. I've also managed to resolve the problem where text and background where at the same color. 

Apart from the notices above, I don't have standing issues in my project. Im not using the Google fonts control in this project.

**Comment by lmartins** [comment]
Jesus, im having a terrible time with Kirki this morning.

I've just noticed that with developer branch I can't make any change to the defaults, said in other way, `get_theme_mods()` returns an empty array no matter what.

Anything I can do about this?

**Comment by replynone** [comment]
did some testing with the twentyfourteen theme, got the same issues as stated above.
with the normal kirki it gives an error in console: double http request pluging folder

with the develop kirki it gives errors on the $controls

**Comment by aristath** [comment]
@replynone sorry about that, I deleted the Kirki_Fonts class by mistake yesterday. I just restored it...

Examining the other issues you guys reported right now.
I'll get back to you ASAP, hopefully with a fix.

**Comment by lmartins** [comment]
Thank you @aristath, don't let my grumpiness bother you as it wasn't the intention. It's just one of those days ;)

**Comment by aristath** [comment]
The main issue here is that I still can't replicate this issue so I don't know exactly what goes on.
Here's exactly what I did:
- I copied Kirki to the twentyfifteen theme, in inc/kirki
- I included the kirki main file from the functions.php file:

``` php
require get_template_directory() . '/inc/kirki/kirki.php';
```
- I added some demo fields and then added this configuration:

``` php
/**
 * Configuration sample for the Kirki Customizer
 */
function kirki_demo_configuration_sample() {

    $args = array(
        'logo_image'    => 'http://kirki.org/images/logo.png',
        'description'   => __( 'This is the theme description.', 'kirki' ),
        'color_accent'  => '#00bcd4',
        'color_back'    => '#455a64',
        'url_path'      => get_template_directory_uri() . '/inc/kirki',
    );

    return $args;

}
add_filter( 'kirki/config', 'kirki_demo_configuration_sample' );
```

It looks fine on my end!!

@lmartins would it be possible for you to send me some FTP & admin credentials for that site so that I may take a look at what goes on?
If yes, then please send them via email to aristath at gmail dot com

**Comment by lmartins** [comment]
@aristath The main topic of this issue was the loading of assets files and that is solved.
The 500 im getting in one site I've already disregarded as Kirki's triggered. I still don't know what happened but I can't replicate it in other sites either.

At this point the single issue Im having is that once I checkout the "develop" branch, no customisations get to the front-end, as if they were being stored with different identifiers. It saves the values in the backend, but nothing gets to front. Anything changed in this regard recently?

**Comment by aristath** [comment]
@lmartins oh! ok....
I didn't realise the assets issue had been resolved and it was driving me insane. :smile: 
Yeah, I was experimenting with https://github.com/aristath/kirki/issues/104 last night and just pushed my latest changes before going to sleep. It was an incomplete commit, I'll get that fixed in a couple of minutes. :+1:

**Comment by lmartins** [comment]
oh man, what a relief... thank you :D

**Comment by aristath** [comment]
Can you please check the develop branch now?

**Comment by lmartins** [comment]
I'm out of the office but I'll check it soon as I get there, in about 30 minutes. Thanks!

**Comment by lmartins** [comment]
Im getting a fatal error:

```
[01-Apr-2015 13:05:06 UTC] PHP Fatal error:  Call to undefined method Kirki::controls() in /lib/kirki/includes/Styles/Frontend.php on line 27
```

**Comment by aristath** [comment]
Try deleting that line. From what I can tell it's not used anymore.

**Comment by lmartins** [comment]
It used again later in the same file to retrieve in the function `loop_controls`:

```

    function loop_controls() {

        $controls = Kirki::controls()->get_all();
        $styles   = array();

        foreach ( $controls as $control ) {
            $element  = '';
```

I've also tried to replace that method call with:

```
$controls   = Kirki::config()->get_all();
```

But the result of this is that no customisations get loaded in the frontend.

**Comment by replynone** [comment]
So far so good!  Did some small testing with a textbox, got the value and no errors in the console. Going to setup a small customizer section tomorrow, I will keep you posted.
tnx for all your good work :+1:

**Comment by lmartins** [comment]
@replynone what branch did you tested?
For me, in branch develop, is outputting the fatal error stated above.

**Comment by replynone** [comment]
martins, yes I took the latest one from develop tab, deleted all the old files. 

function.php 
include_once ( dirname( **FILE** ) . '/kirki/kirki.php' );

/**
- Configuration sample for the Kirki Customizer
  */
  function customizer_config() {
  
  $args = array(
  
  ```
  // Change the logo image. (URL) Point this to the path of the logo file in your theme directory
          // The developer recommends an image size of about 250 x 250
  'logo_image'   => get_template_directory_uri() . '/images/logo.png',
  
  // Only use this if you are bundling the plugin with your theme (see above)
  'url_path'     => get_template_directory_uri() . '/kirki/', 
  
  // The color of active menu items, help bullets etc.
  'color_active' => '#444',
  
  // Color used for secondary elements and desable/inactive controls
  'color_light'  => '#eee',
  
  // Color used for button-set controls and other elements
  'color_select' => '#34495e',
  
  // You can add your own custom stylesheet for full control as well
  // For the parameter here, use the handle of your stylesheet you use in wp_enqueue
  'stylesheet_id' => 'customize-styles',
  ```
  
  );
  
  return $args;

}
add_filter( 'kirki/config', 'customizer_config' );

then took some pre settings from the kirki site.

**Comment by lmartins** [comment]
Im not sure why it is working for you. In my project Kirki is a gitsubmodule, so im just pulling directly from github and checking out the develop branch. 

The function in question does a loop for each control and as far as I can see isn't declared anywhere, so im a bit surprised is working for you.

Anyway, this is dev branch, master is ok, although in master there some styling issues.

@aristath Do you wan't me to help with styling in any way?

**Comment by aristath** [comment]
But is **is** declared... https://github.com/aristath/kirki/blob/develop/includes/Controls.php#L38-L49
That's what troubles me!

As for styling sure! If you have an improvement in mind just jubmit a PR. :)

**Comment by lmartins** [comment]
@aristath I said earlier that the assets were already loading ok, turns out I was mistaken. Damn. Sorry about that.

To saves us all from back and forth messages, im doing a PR with my proposed resolution that im asking you then to confirm if you don't mind.

There are three files missing, CSS and JS causing multiple issues. I'll update you once I submit the PR.

**Comment by briancwelch** [comment]
@lmartins, what method are you using to set the `url_path` for Kirki?  After some commits last night, I can't replicate the issue anymore, (though previously I had)

```
/**
 * Configuration sample for the Kirki Customizer
 */
function kirki_demo_configuration_sample() {

    $url  = get_stylesheet_directory_uri() . '/inc/kirki/';

    $args = array(
        'logo_image'    => 'http://kirki.org/images/logo.png',
        'description'   => __( 'This is the theme description. You can edit it in the Kirki configuration and add whatever you want here.', 'kirki' ),
        'color_accent'  => '#00bcd4',
        'color_back'    => '#455a64',
        'url_path'      => $url,
    );

    return $args;

}
add_filter( 'kirki/config', 'kirki_demo_configuration_sample' );
```

Can you ensure that you're using get_stylesheet_directory_uri() as outlined in the block above?

**Comment by lmartins** [comment]
@aristath 
https://github.com/aristath/kirki/pull/151 should fix the issues with assets loading if user sets the `url_path` option.

@briancwelch Im doing the same, but after reading the code I am surprised it works for you. As you can see in https://github.com/lmartins/kirki/commit/1b5b25bfd6015eb51f0ec000bcedc380e4d5963f the var wasn't being set for loading from the user specified option.  Are you sure you have the plugin bundled with your theme? If it was installed as a plugin this setting doesn't make a difference I believe.

**Comment by briancwelch** [comment]
@lmartins No plugin installation.  I started a fresh WordPress vagrant with TwentyFifteen and the Kirki develop branch included under /wp-content/themes/twentyfifteen/inc/kirki

The reason I asked, is because as soon as I change `get_stylesheet_directory_uri()` to `get_stylesheet_directory()`, I am able to replicate the issue instantly.

**Comment by lmartins** [comment]
The switch from `get_stylesheet_directory_uri()` it is normal to break as they produce different values. 

Im guessing that it works for you because you have the files inside the theme itself, which you shouldn't if you wan't to update it later. Because you're using the same path as Kirki gets by default, it ends up working with the default value. Just a guess, @aristath can say better im sure.

**Comment by briancwelch** [comment]
@lmartins I'm afraid I don't understand then. If Kirki is installed as a plugin, what benefit is there to setting the url_path?

**Comment by aristath** [comment]
@lmartins can you please try pulling the develop branch now and test this again?

**Comment by lmartins** [comment]
Ok, some weirdness going on.
I have the project as a git submodule on my now project. I've checked out `develop` and pulled from github.

Lines 26-27 from Frontend.php still shows me

```
$config   = Kirki::config()->get_all();
$controls = Kirki::controls()->get_all();
```

but on github site I see those lines are different.

Manually deleted every file and replaced it and it is now working. What the actual ******.
I have no ideia what happened here, and why git was showing me different code after checking out the repo but I am now quite hesitant about git submodules.

Well, it is loading just fine (code from the dev branch), so im closing this.
Thank you all for all the help.

**Comment by aristath** [comment]
@lmartins hey there! Out of curiosity did it work?
Do you still have an issue with this?

**Comment by lmartins** [comment]
Hi @aristath, sorry, I should have been clearer about that.
Yes, is working now, still scratching my head over the git remote thing but when it comes to Kirki everything seems fine now.

**Comment by aristath** [comment]
Awesome!
Thanks for the update man! :+1:

**Comment by lmartins** [comment]
Thank you for all the work.
Btw, do you have any ETA when will these get merged into master?

**Comment by aristath** [comment]
Hopefully by Monday I'll have any remaining bugs squashed, merge the branch and release an update.
If you want to help what we really need is just lots and lots of testing on the develop branch!!!
If you happen to find any bugs (no matter how large or small) just create a new issue so that we may deal with it. :+1:
