### ISSUE TITLE
date control: get raw value or convert to another format

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1482]
### Issue description:
Currently the date control outputs the string like **August 12, 2018** which is not desirable in all situations. Is there a way to get the raw value or convert to another format?

**Comment by aristath** [comment]
You can use PHP functions to do this directly and convert the date to whatever format you want:
http://php.net/manual/en/datetime.createfromformat.php
```php
$date = DateTime::createFromFormat( 'F j, Y', 'August 12, 2018' );
echo $date->format( 'Y-m-d' );
```
