### ISSUE TITLE
If plugin not installed, Kirki_Helper not work

### ISSUE THREAD

**Issue by fahimxyz** [themeum/kirki#1483]
Using the latest version of kirki, when I use Kirki_Helper method and if I deactivate kirki plugin, I found an unknown error, screen blank. My Wordpress debug mode on but no issue found. I use the below code: 

Remark: I using _s theme with kirki helper file.

```
_Kirki::add_field( 'puffin_press_theme', array(
	'type'        => 'select',
	'settings'    => 'pp_featured_exclude_category',
	'label'       => esc_attr__( 'Exclude Featured Categories', 'puffin-press' ),
	'section'     => 'pp_featured',
	'priority'    => 10,
	'multiple'    => 999,
	'choices'     => Kirki_Helper::get_terms( array('taxonomy' => 'category') ),
) );

```

Give me a solution, please.

**Comment by aristath** [comment]
Instead of this:
```php
'choices'     => Kirki_Helper::get_terms( array('taxonomy' => 'category') ),
```

use this:

```php
'choices'     => ( class_exists( 'Kirki_Helper' ) ) ? Kirki_Helper::get_terms( array('taxonomy' => 'category') ) : array(),
```

In cases where you're not 100% sure the class (or function)  you'll be using in your code actually exists, you should always add a check.
