### ISSUE TITLE
Embedding in theme doesn't work any more

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1485]
### Issue description:
Hi,

I'm embedding kirki in my theme. I wanted to update to the latest version but now, the customizer doesn't load any more. The console throws the following error:

![bildschirmfoto 2017-07-28 um 23 10 21](https://user-images.githubusercontent.com/22119831/28736476-35aad120-73ea-11e7-897a-8ad8888c1e9a.png)

### Version used:
3.0.0-beta.2

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Hey there!

Can you please try pulling the latest version and reset the browser caches?

**Comment by mapsteps** [comment]
Hey @aristath,

looks like just clearing the cache did the trick.
Sorry for that :)

Enjoy your weekend!
