### ISSUE TITLE
Issues With Select2 On Latest Development Branch

### ISSUE THREAD

**Issue by coleh33** [themeum/kirki#1493]
Can anyone else confirm the same issue on the latest development branch?

When trying to use it with this plugin https://wordpress.org/plugins/yuzo-related-post/ none of the options work in the customizer that have been setup through KIRKI.  The strange thing is that my local install appears to work fine but on the live server the customizer is broken.  This all happened after I updated to the latest development branch of KIRKI.  The other plugin hasn't been updated in a while so no updates were made to it during this time period.

Just trying to see if any select2 library changes were made or what could be causing conflicts.  No console errors are being reported but when attempting to click any text fields or select dropdowns, nothing happens and no options can be selected or text entered.

I found out the conflict by disabling plugins one by one and disabling the Yuzo Related Post attempted to fix the issue.  At first I thought it was Shortcake but I have a Select2 no conflict mode setup on that one.

Any help on this would be appreciated.

**Comment by aristath** [comment]
@coleh33 I'm terribly sorry, I completely missed this ticket and found it now by accident while searching for another select2 ticket!
Since August we switched from select2 to selectWoo, so should I assume this is no longer an issue?
