### ISSUE TITLE
Question update from 2.7

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#1494]
Hi @aristath,

I saw that Kirki version 3.0.9 was released. In my theme I have included the 2.7 version.
Are there any cautions I have to do before updating?

Thank you very much,
Davide

**Comment by sododesign** [comment]
News for this? Please?

**Comment by aristath** [comment]
@sododesign `background` fields is basically the only thing that is not backwards-compatible.
Other than that you shouldn't have any issues
