### ISSUE TITLE
Setting a default on category dropdown

### ISSUE THREAD

**Issue by michelle-may** [themeum/kirki#1495]
I have an optional theme feature where users can display a post from 4 different categories in a row. 

I am using Kirki_Helper::get_terms( 'category' ) and this loads the categories great. However it shows a category but I can only grab the default value in get_theme_mod and not the category ID until the user selects a different value.

Am I doing something wrong? Ideally I'd like to be able to set the default to match the ID of whatever is shown first in the category list, or have a blank option in the dropdown so the user always has to go in and set a category.

```
$fields[] = array(
	'settings'    => 'feat_cat_1',
	'type'        => 'select',
	'label'       => __( 'Choose a category', 'brio' ),
	'section'     => 'featured_cat_posts',
	'default'     => '',
	'choices'     => Kirki_Helper::get_terms( 'category' ),
);
```

**Comment by DannyCooper** [comment]
Your code is not setting a default `'default'     => '',` so that's what `get_theme_mod()` will return.
