### ISSUE TITLE
Store Image as ID

### ISSUE THREAD

**Issue by JiveDig** [themeum/kirki#1498]
### Issue description:

First off, I already read https://github.com/aristath/kirki/issues/712

I was a bit surprised when I realized Kirki stores image field values as a URL. I have an existing plugin that i'm converting to use Kirki and this is/was the only hiccup. I was easily able to store the value as an ID using the `sanitize_callback`, the only issue now is filtering that option (not theme_mods here) and converting the ID to URL when is_customize_preview(). Then my function to retrieve that field also needs to check if the value is a URL, and convert accordingly, though this only happens when using the customizer.

I was hoping `apply_filters( 'kirki/values/get_value', $value, $field_id );` would be the easy solution to convert ID to URL only for the field value, but that didn't work.

Is there a better way to do this considering I have a ton of active installs using ID, and I'd prefer to keep it that way?

Lastly, another option is to add a parameter to the image field to give the option to store as URL or ID.

### Version used:
3.0.9 from WP repo

### Using theme_mods or options?
options

**Comment by aristath** [comment]
@JiveDig saving as a URL is the default behaviour, but not the only option. 😉 
Try adding this to one of your image fields:

```php
'choices' => array(
    'save_as' => 'array'
),
```
This will save the value as an array containing the url, width, height and ID of the image.

**Comment by JiveDig** [comment]
Ooh that is interesting, and very helpful. Is there a built in way to only save as ID though?

`'save_as' => 'ID'` ?

**Comment by JiveDig** [comment]
https://github.com/aristath/kirki/blob/69488f63c712a5a8b68789cd2e315dfd4ba2abf7/field/class-kirki-field-image.php#L78 BINGO.

**Comment by aristath** [comment]
I think it's half-implemented... I started working on it but never tested if it works or not (which is why it's not even documented anywhere).
If it doesn't work let me know and I'll fix it 👍

**Comment by JiveDig** [comment]
Okay, it definitely stores the image as an ID, which is great (and easy enough to do with the sanitize_callback. But it has the same issue, the image preview is not showing now.

I'm guessing you upon loading of the field you need to check the `save_as` value and convert accordingly?

**Comment by aristath** [comment]
I just pushed a commit that _should_ fix this.
Sorry, I'm unable to test right now, but in theory that code should fix the issue and allow using the ID.
Could you please test it now and let me know if that works for you?

**Comment by JiveDig** [comment]
Hmmm, doesn't seem to work.

I just copied the changes to that file into my current local install. Is there an easier way to test? Is there a featured branch I can use? Pardon my git limitations here ;)

**Comment by aristath** [comment]
The easiest way is to just download the develop branch from here: https://github.com/aristath/kirki/archive/develop.zip
This always contains the latest commits. 👍 
I just pushed another fix, I found some time to test this and it seems to be working now.

**Comment by JiveDig** [comment]
Yes, this is working. Awesome. I'll lookout for an update before i push my code for my plugin. Thanks.

**Comment by JiveDig** [comment]
Not to be pushy, but i'm wondering if you have a timeline for the next release, so I can plan my dev/release schedule accordingly.

**Comment by aristath** [comment]
@JiveDig I'm hoping for sometime next week, though I can't make any promises about that.
version 3.0.10 changed quite a few things - mostly performance improvements - and I need to be thorough with my testing.

**Comment by JulienMelissas** [comment]
Hey there! Not to revive and old thread, but it looks like there are still some half-baked issues with saving images as IDs and arrays. Right now, I'm trying to save an image as an array and even when I make a change in the customizer it doesn't give me option to save or publish my changes. And also it's not removing the value from the customizer when I click "remove".

**Comment by JulienMelissas** [comment]
Nevermind! Ugh, silly user error on my part. Array field type is working for me, I think this issue can be closed.
