### ISSUE TITLE
Kirki does not load assets in customizer on develop version.

### ISSUE THREAD

**Issue by bawright** [themeum/kirki#1501]
### Issue description:
Kirki isn't loading any of its assets in the customer for the controls.

### Version used:
Latest develop version

### Using theme_mods or options?
Whatever the _s theme is using... I believe theme_mods

### Code to reproduce the issue (config + field(s))
This is what I'm using:
 - Blank WP install
 - _s theme provided by you https://github.com/aristath/_s
 - Only plugin active is Kirki

![ss](https://user-images.githubusercontent.com/6720156/29174537-9c5252a8-7db4-11e7-81f8-03224e3f8ef7.png)

**Comment by CodeCurosity** [comment]
Yes just tried few mins ago, same issue.

**Comment by aristath** [comment]
@bawright @UsmanShahzad Can you please try this again?
But please do
```bash
git clone --recursive https://github.com/aristath/kirki.git
``` 
because a lot of the assets were moved to a separate repository so you may not be getting them if you already had kirki cloned locally and did a `git pull`

**Comment by bawright** [comment]
It's working, thanks @aristath 

New version loads at least 50% faster btw, nice job!
