### ISSUE TITLE
Refactor the kirki-helpers, taking into account the new background field

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#1511]
I think these lines should be deleted https://github.com/aristath/_s/blob/master/inc/kirki-fallback.php#L162-L195

**Comment by carasmo** [comment]
I removed those lines and it didn't work. I'm using the plugin version, would that make a difference on why it's not falling back?

**Comment by aristath** [comment]
Closing this one, it was fixed on https://github.com/aristath/_s/commit/f7a7c3e513eb62f41ffdeb9f76d83762230e1b1b

**Comment by carasmo** [comment]
Thank you so much!!! Works great.
