### ISSUE TITLE
Preset Field not working with Gradient

### ISSUE THREAD

**Issue by krishna19** [themeum/kirki#1512]
### Issue description:
Hi, I need your help regarding **Preset** Field. I use the preset field to change the color scheme. Everything works fine except **Gradient** Type. The values are reflected only after refresh the page.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
No.
I try with the stable version Kirki 3.0.9

### Using theme_mods or options?
using theme_mods
<pre>Kirki::add_config( 'mytheme', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
));</pre>

### Code to reproduce the issue (config + field(s))
<pre>
function color_preset( $color ) {
	$red = array();
	$red['color_demo'] = '#dd3333';
	$red['color_alpha_demo'] = 'rgba(221,51,51,0.87)';
	$red['gradient_demo'] = isset( $options['gradient_demo'] ) ? $options['gradient_demo'] : array();
	$red['gradient_demo']['angle'] = 6;
	$red['gradient_demo']['start']['color'] = '#dd3333';
	$red['gradient_demo']['start']['position'] = 50;
	$red['gradient_demo']['end']['color'] = '#aa0000';
	$red['gradient_demo']['end']['position'] = 80;

	$green = array();
	$green['color_demo'] = '#dd3333';
	$green['color_alpha_demo'] = 'rgba(129,215,66,0.87)';
	$green['gradient_demo'] = isset( $options['gradient_demo'] ) ? $options['gradient_demo'] : array();
	$green['gradient_demo']['angle'] = 100;
	$green['gradient_demo']['start']['color'] = '#81d742';
	$green['gradient_demo']['start']['position'] = 50;
	$green['gradient_demo']['end']['color'] = '#009311';
	$green['gradient_demo']['end']['position'] = 80;

	if ( isset( $$color ) ) {
		return $$color;
	}
	return array();
}

// Preset
Kirki::add_field( 'mytheme', array(
    'type'        => 'preset',
    'settings'    => 'preset_demo',
    'label'       => esc_html__( 'Preset control', 'kirki' ),
    'description' => esc_html__( 'Bulk-changes the value of other controls.', 'kirki' ),
    'section'     => 'kirki_other_fields',
    'default'     => 'none',
    'priority'    => 1,
    'multiple'    => 3,
    'choices'     => array(
        'none' => array(
            'label'    => __( 'None', 'kirki' ),
        ),
        'red' => array(
            'label'    => __( 'Red', 'kirki' ),
            'settings' => color_preset( 'red' ),
        ),
        'green' => array(
            'label'    => __( 'Green', 'kirki' ),
            'settings' => color_preset( 'green' ),
        ),
    ),
) );

// Color - Alpha
Kirki::add_field( 'mytheme', array(
	'type'			=> 'color',
	'settings'		=> 'color_alpha_demo',
	'label'			=> esc_html__( 'Color Alpha', 'kirki' ),
	'description'	=> esc_html__( 'Color Description', 'kirki' ),
	'section'		=> 'kirki_other_fields',
	'default'		=> '#000000',
	'priority'		=> 2,
	'choices'     => array(
		'alpha' => true,
	),
) );

// Color
Kirki::add_field( 'mytheme', array(
	'type'			=> 'color',
	'settings'		=> 'color_demo',
	'label'			=> esc_html__( 'Color', 'kirki' ),
	'description'	=> esc_html__( 'Color Description', 'kirki' ),
	'section'		=> 'kirki_other_fields',
	'default'		=> '#000000',
	'priority'		=> 3,
	'choices'     => array(
		'alpha' => false,
	),
) );

// Gradient
Kirki::add_field( 'mytheme', array(
    'type'        => 'gradient',
    'settings'    => 'gradient_demo',
    'label'       => esc_html__( 'Gradient', 'kirki' ),
    'section'     => 'kirki_other_fields',
    'priority'    => 4,
    'default'     => array(
        'angle' => 0,
        'start' => array(
            'color'    => '#333333',
            'position' => 10,
        ),
        'end'   => array(
            'color'    => '#cc0000',
            'position' => 100,
        ),
    ),
) );
</pre>

Thanks

**Comment by aristath** [comment]
The gradient field is a work in progress which is why it is not documented anywhere.
It is not yet ready for production and should not, under any circumstances be used yet.

**Comment by krishna19** [comment]
@aristath Thanks for reply. Is it possible to use radio-image instead of select box?

**Comment by aristath** [comment]
Not yet. There is already a feature request for this on https://github.com/aristath/kirki/issues/1221

**Comment by krishna19** [comment]
@aristath Thanks for your reply
