### ISSUE TITLE
Active_callback not works when using contains

### ISSUE THREAD

**Issue by krishna19** [themeum/kirki#1514]
### Issue description:
Hi, Active_callback not works correctly when using **contains** or **in**. I also try this solution #1286 but not works.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Stable Version: Kirki 3.0.9

### Using theme_mods or options?
Using theme_mods
<pre>
Kirki::add_config( 'mytheme', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
));
</pre>

### Code to reproduce the issue (config + field(s))
<pre>
// Radio Image
Kirki::add_field( 'mytheme', array(
	'type'        => 'radio-image',
	'settings'    => 'radio_image_demo',
	'label'       => esc_html__( 'Radio Control', 'kirki' ),
	'section'     => 'kirki_other_fields',
	'default'     => 'cr',
	'choices'     => array(
		'cl'   => 'https://raw.githubusercontent.com/syamilmj/Options-Framework/master/admin/assets/images/2cl.png',
		'cr' => 'https://raw.githubusercontent.com/syamilmj/Options-Framework/master/admin/assets/images/2cr.png',
		'cf'  => 'https://raw.githubusercontent.com/syamilmj/Options-Framework/master/admin/assets/images/1col.png',
	),
) );

// Sortable
Kirki::add_field( 'mytheme', array(
	'type'        => 'sortable',
	'settings'    => 'sortable_demo',
	'label'       => esc_html__( 'Sortable', 'kirki' ),
	'section'     => 'kirki_other_fields',
	'default'     => array(
		'option3',
		'option1',
		'option4'
	),
	'choices'     => array(
		'option1' => esc_html__( 'Option 1', 'kirki' ),
		'option2' => esc_html__( 'Option 2', 'kirki' ),
		'option3' => esc_html__( 'Option 3', 'kirki' ),
		'option4' => esc_html__( 'Option 4', 'kirki' ),
		'option5' => esc_html__( 'Option 5', 'kirki' ),
		'option6' => esc_html__( 'Option 6', 'kirki' ),
	),
	'active_callback'	=> array(
		array(
			'setting'	=> 'radio_image_demo',
			'operator'	=> 'contains',
			'value'		=> array( 'cl', 'cr' ),
		),
	),
) );
</pre>

thanks

**Comment by aristath** [comment]
I don't get it...
Wouldn't it be simpler to do this instead?

```php
	'active_callback'	=> array(
		array(
			'setting'	=> 'radio_image_demo',
			'operator'	=> '!==',
			'value'		=> array( 'cf' ),
		),
	),
```

**Comment by krishna19** [comment]
@aristath Thanks for your reply. For this if I use like this it works
<pre>
	'active_callback'	=> array(
		array(
			'setting'	=> 'radio_image_demo',
			'operator'	=> '!==',
			'value'		=> 'cf',
		),
	),
</pre>

If I use array in **value** field with operator **contains** & **in** this not works.  I want to use multiple values, Because I have more than 5 headers in my theme some options are only works with few headers only at that time I need to hide those elements. For that I need this to work. Please suggest me some options.

Thanks

**Comment by aristath** [comment]
This:
```php
array(
	'setting' => 'radio_image_demo',
	'operator' => 'contains',
	'value' => 'array( 'cl', 'cr' ),',
),
```
can be worded like this:
* Show control `sortable_demo` if the value of the control `radio_image_demo` **contains** `array( 'cl', 'cr' )`.
* Show control `sortable_demo` if the `array( 'cl', 'cr' )` is a subset of the value of the control `radio_image_demo` (in)

BUT it's not like this:
Show control `sortable_demo` if the value of the control `radio_image_demo` is `'cl'` OR `'cr'`.

And the latter is what you want to do....
In order to accomodate use-cases like these, let me explain the AND/OR relation a bit more:

The 1st level is AND
The 2nd level is OR
The 3rd level is AND 
and so on:

```
'active_callback' => array(
	condition1
		AND
	condition2
		AND
	array( condition3 OR condition4 )
		AND
	condition5
)
```

So, if you want to do `( value === 'cl' OR value === 'cr' )` you'll have to nest the array one level deeper like this:

```php
'active_callback' => array(
	array(
		array(
			'setting'  => 'radio_image_demo',
			'operator' => '===',
			'value'    => 'cl',
		),
		array(
			'setting'  => 'radio_image_demo',
			'operator' => '===',
			'value'    => 'cr',
		),
	),
),
```

**Comment by krishna19** [comment]
@aristath still work like that. After I make some changes to the **contains & in** field-dependencies.js it works fine.
<pre>
case 'contains':
case 'in':
	if ( _.isArray(value2) ) {
		var found = false;
	    _.each(value2, function(index, value) {
	    	if ( _.isNumeric(value ) )
	    		value = parseInt(value);

	    	if (value1.indexOf(value) > -1)
	            found = true;
	    });

	    return found;
	} else {
	    return value1.indexOf(value2) > -1;
	}
</pre>

Thanks

**Comment by DannyCooper** [comment]
https://github.com/aristath/kirki/commit/47bc5917b5dac878a0670b9cef8ca372d8ea67b4
