### ISSUE TITLE
HTML entities in repeater text field being encoded on each save?

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1523]
When the user inputs an ampersand (&) in a repeater text field and saves, it later appears (in the front end) as &amp;, then &amp;amp;, then &amp;amp;amp;, etc (progressing after multiple customizer saves)

Not sure whether this is something silly I'm doing /  expected behaviour / or the field getting sanitized the wrong way (if one is using HTML characters).

Is there any way around this? `html_entity_decode` doesn't help once the entity has been encoded more than once....

### Version used:
3.0.9

### Code to reproduce the issue
```
	Kirki::add_config( 'mytheme', array(
	    'capability'    => 'edit_theme_options',
	    'option_type'   => 'theme_mod',
	) );
		// Highlight Points Section & Controls

	$wp_customize->add_section( 'mytheme_highlights', array(
		'title' => __( 'Home Highlight Points' ),
		'description' => __( '' ),
		'priority' => 60,
		'capability' => 'edit_theme_options',
	) );

	Kirki::add_field( 'mytheme', array(	'type' => 'repeater',
			'label'       => esc_attr__( 'Highlight Points', 'mytheme' ),
			'section'     => 'mytheme_highlights',
			'priority'    => 10,
			'row_label' => array(
				'type'  => 'field',
				'value' => esc_attr__('Highlight', 'mytheme' ),
				'field' => 'highlight_heading',
			),
			'settings'    => 'mytheme_highlights',
			'fields' => array(
				'highlight_heading' => array(
					'type'        => 'text',
					'label'       => esc_attr__( 'Heading', 'mytheme' ),
					'default'     => '',
				),
				'highlight_subtext' => array(
					'type'        => 'textarea',
					'label'       => esc_attr__( 'Subtext', 'mytheme' ),
					'default'     => '',
				),
		) ) );
```

On the front end:
```
$highlights = get_theme_mod( 'mytheme_highlights' );
$heading = $highlight['highlight_heading'];
echo '<h3>' . esc_html( $heading ) . '</h3>';
```

**Comment by aristath** [comment]
Thank you for reporting this, and most of all for posting the whole code necessary to replicate it. Made my life easier 👍 

That last commit fixed it for me in my tests, it will be included in 3.0.10

**Comment by ghost** [comment]
Thanks! Does the same thing need to apply to text fields as well as textarea? (it's actually text fields not textarea where I'm seeing the problem)?

I'm using the WP plugin so look forward to testing once 3.0.10 is released (if you have a approx. date that'd be great so I can set client expectations).

Thank you very much for making Kirki.

**Comment by ghost** [comment]
@aristath - any thoughts on this? I'm still seeing this issue occurring in text fields (as opposed to textarea).

Thanks!

**Comment by aristath** [comment]
@hexagongirl text fields were using `esc_textarea` for sanitization.
However that was wrong because text fields should be sanitized using `sanitize_text_field`.

It should be good after that last commit.

> if you have a approx. date that'd be great so I can set client expectations

I'm hoping it will be released by the end of this week.

**Comment by ghost** [comment]
Thank you @aristath! - appreciate it.
