### ISSUE TITLE
Dependant control not displaying after dependant parent shown

### ISSUE THREAD

**Issue by ge022** [themeum/kirki#1525]
### Issue description:
I have a control dependent on a parents toggle being enabled. The parent is dependent on another control's value. When the initial control's parent is hidden because of it's own parent's value not matching, the initial control is still shown.
Working: 
![image](https://user-images.githubusercontent.com/23706821/30181328-b8cb10b8-93c7-11e7-90d8-211805bd0590.png)
Issue:
![image](https://user-images.githubusercontent.com/23706821/30181373-e10d505e-93c7-11e7-960a-2e09a5ded598.png)

I have tried making the initial control defendant on both the parent and the parent's parent values, but then I get the initial control showing when it's parent is disabled.
Issue:
![image](https://user-images.githubusercontent.com/23706821/30181399-fe827f74-93c7-11e7-9ca9-547773261921.png)

### Version used:
3.0.9

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
/**
 * Add the Kirki configuration
 */
mortar_theme_Kirki::add_config( 'mortar_theme', array(
  'option_type' => 'theme_mod',
  'capability'  => 'edit_theme_options',
) );

/**
 * Add the Header section
 */
mortar_theme_Kirki::add_section( 'header', array(
  'title'          => __( 'Header' ),
  'description'    => __( 'Customize the header here' ),
  'priority'       => 60,
  'capability'     => 'edit_theme_options'
) );

// Optional custom header logo
mortar_theme_Kirki::add_field( 'mortar_theme', array(
  'type'        => 'toggle',
  'settings'    => 'optional_custom_header_logo',
  'label'       => __( 'Enable Custom Logo', 'mortar' ),
  'section'     => 'header',
  'default'     => '0',
  'priority'    => 10,
  'active_callback'   => array(
    array(
      'setting'  		=> 'custom_logo',
      'operator' 		=> '!==',
      'value'    		=> sprintf( false, get_template_directory_uri(), get_stylesheet_directory_uri() ), // custom_logo's image control
    ),
  ),
) );

// Header logo height
mortar_theme_Kirki::add_field( 'mortar_theme', array(
  'type'        => 'dimension',
  'settings'    => 'custom_header_logo_height',
  'label'       => __( 'Header Logo Height', 'mortar-theme' ),
  'section'     => 'header',
  'priority'    => 20,
  'active_callback'   => array(
    array(
      'setting'  		=> 'optional_custom_header_logo',
      'operator' 		=> '==',
      'value'    		=> '1',
    ),
  ),
  'default'     => '150px',
) );
```

**Comment by carasmo** [comment]
See: https://aristath.github.io/kirki/docs/arguments/active_callback.html

== is equal
!= is not equal
!== is not identical

**Comment by ge022** [comment]
@carasmo I changed the custom_header_logo_height's operator to === and it did not help. I also changed the optional_custom_header_logo's operator to !=, and it did not help.

**Comment by aristath** [comment]
The `optional_custom_header_logo` setting is a `toggle` (basically a checkbox with some elaborate CSS) so it saves `boolean` values.

This:
```php
  'active_callback'   => array(
    array(
      'setting'  		=> 'optional_custom_header_logo',
      'operator' 		=> '==',
      'value'    		=> '1',
    ),
  ),
```
should be
```php
  'active_callback'   => array(
    array(
      'setting'  		=> 'optional_custom_header_logo',
      'operator' 		=> '==',
      'value'    		=> true,
    ),
  ),
```

As for this one:

```php
  'active_callback'   => array(
    array(
      'setting'  		=> 'custom_logo',
      'operator' 		=> '!==',
      'value'    		=> sprintf( false, get_template_directory_uri(), get_stylesheet_directory_uri() ), // custom_logo's image control
    ),
  ),
```
Why `sprintf( false, get_template_directory_uri(), get_stylesheet_directory_uri() )` ?
Could you also post the `custom_logo` control you're using?

**Comment by ge022** [comment]
@aristath 
custom_logo is a built-in WordPress function (https://developer.wordpress.org/themes/functionality/custom-logo/) that adds an image control to the 'Site Identity' section, which allows you to add the logo anywhere using the_custom_logo(). I have mine in the header. Initially, I wanted to only allow customization or replacement of the logo when there is an image set by the WordPress custom_logo control. 
When the user wants to override the header logo, I am hooking into the get_custom_logo function (because it generates useful markup) and replacing the src with the custom image control's.
So, to output the overriding logo, the initial WordPress custom_logo control has to be set, because the get_custom_logo function, that I am filtering through, checks if get_theme_mod( 'custom_logo' ) is set. 
I replaced the 1's and 0's with bool, and it doesn't help that a toggle doesn't switch to false when it's parent value doesn't match, leaving the toggle's children visible, but the toggle itself not .

**Comment by DannyCooper** [comment]
`custom_logo` returns an ID. You are trying to compare it to a URI, that's why it's not working.
