### ISSUE TITLE
Make select multiple sortable

### ISSUE THREAD

**Issue by allysonsouza** [themeum/kirki#1528]
### Issue description:
Hi, I can't figure how to make a select multiple be sortable like the example image. [https://aristath.github.io/kirki/docs/controls/select.html](https://aristath.github.io/kirki/docs/controls/select.html)

### Version used:
Yes, I was using 3.0.9 but tried to install the development 3.0.10-beta

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))
```
Idexo_Kirki::add_field( 'my_config', array(
	'type'        => 'select',
	'settings'    => 'featured_posts',
	'label'       => __( 'Featured posts', 'my_theme' ),
	'section'     => 'blog',
        'multiple'    => 5,
	'choices'     => array(
		'option-1' => esc_attr__( 'Option 1', 'my_textdomain' ),
		'option-2' => esc_attr__( 'Option 2', 'my_textdomain' ),
		'option-3' => esc_attr__( 'Option 3', 'my_textdomain' ),
		'option-4' => esc_attr__( 'Option 4', 'my_textdomain' ),
	),
	'priority'    => 10,
) );
```

**Comment by JimmyAppelt** [comment]
@allysonsouza I have the same question 😄 , did you find any solution in the meanwhile?

**Comment by allysonsouza** [comment]
Sorry @JimmyAppelt, I could not find a solution, so I moved to repeater fields that are sortable, despite the worst interface.

**Comment by aristath** [comment]
@allysonsouza I replied to you on Slack yesterday but posting here as well so we can track this better.

> select2 needs to be combined with jQueryUI-sortable to make the selections sortable.
> Not impossible, it just wasn't on the top of my priorities list
> If you need them sortable and have a limited amount of choices, then the sortable control would be better for this task.
> At least until I can re-implement the sortable functionality in select2
> It's basically done in woocommerce I think, so I'll have to extract the related parts from this file https://github.com/woocommerce/woocommerce/blob/48e4bf757799942ced79e8689b88899f376cdb4c/assets/js/admin/wc-enhanced-select.js

**Comment by allysonsouza** [comment]
@aristath in which slack? 🤔

**Comment by JimmyAppelt** [comment]
I ended up switching everything up to the sortable control for 4.9 since we had options where it was necessary for users to sort.
Thanks for the feedback @aristath @allysonsouza 

@allysonsouza he probably meant to tag me instead 👍

**Comment by aristath** [comment]
@allysonsouza yeah, sorry about the wrong tagging. I meant to tag Jim instead 👍
