### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by dylan-ngo11** [themeum/kirki#1531]
### Issue description:
Hi! In our client site, I could not access the Customizer page, it shows 404 page when going to this page. 
Only Kirki plugin is activated. 
What's the issue and how to solve it? 
Thanks for the help!

### Version used:
The latest version from wordpress.org

**Comment by dylan-ngo11** [comment]
Sometime the customize page could not load.

**Comment by aristath** [comment]
@duongancol the `/wp-admin/customize.php` page is from WordPress-Core, not Kirki.
Kirki simply extends the customizer and adds additional functionality to it. 
If you can't access the `/wp-admin/customize.php` page then there's something wrong with your WordPress installation.

**Comment by dylan-ngo11** [comment]
Hi @aristath !
Thank for your response! I know there's something wrong with WP installation but The problem only happen when I activate Kirki plugin with our theme. It works well without Kirki plugin. 
What's the conflict? I need the clear answer to forward to the client.

**Comment by aristath** [comment]
does this happen on any site, or just the site of that particular client?
I have never encountered an issue like that before, nor has anyone else ever reported anything remotely similar.

Did you try enabling WP_DEBUG on that site and see if there are any errors reported?

**Comment by dylan-ngo11** [comment]
it's weird that only happen on the client site. I have enabled WP_DEBUG but it showed nothing.
Here is the screencast http://take.ms/o2e4H
Please note that I made another test with only Kirki and my theme activation and the result was the same. So I have no idea where the problem comes from.

**Comment by aristath** [comment]
@duongancol in your screencast there was no 404 error...
It just takes too long to load.
If left alone, does it eventually load? Or does it throw an error?
How many fields are you adding on that theme? Perhaps the user has a very low PHP Memory limit and extremely long PHP timeout so it doesn't actually time-out but tries to load everything?
Did you check the browser console for any errors there? It may be that there's a JS error that prevents it from rendering the customizer

**Comment by dylan-ngo11** [comment]
it showed 404 page before but now It keeps long loading then show 503 error.
The memory limit is 96mb and the max_execution_time is 30mb. 
I'll try to ask them to increase the memory limit to 256mb.

**Comment by dylan-ngo11** [comment]
It solved the problem. 
Thank you!
