### ISSUE TITLE
Spacing Field Not Works

### ISSUE THREAD

**Issue by krishna19** [themeum/kirki#1532]
### Issue description:
Spacing Field only works if I enable all sides(top,right,bottom,left). If I disable top and bottom it not works.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Stable Version: 3.0.9

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
<pre>Kirki::add_field( 'mytheme', array(
	'type'				=> 'spacing',
	'settings'			=> 'side_margin',
	'label'				=> esc_html__( 'Side Margin (px)', 'kirki' ),
	'section'			=> 'kirki_other_fields',
	'default'			=> array(
		'left'				=> '',
		'right'				=> '',
	),
) );</pre>

Thanks

**Comment by aristath** [comment]
@krishna19 can you please try this with the develop branch from this repository?
It seems to me like this is working fine there, so if there was an issue it must have already been fixed

**Comment by krishna19** [comment]
@aristath Thanks
