### ISSUE TITLE
Tooltip in repeater field

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#1534]
### Issue description:
1. Tooltip icon is hidden under field element when tooltip is assigned to repeater:
![zrzut ekranu z 2017-09-16 17-32-55](https://user-images.githubusercontent.com/11788346/30513530-189367c2-9b05-11e7-927a-d2c42cdc9d57.png)

2. Tooltip is not visible when tooltip is assigned to field inside repeater.
![image](https://user-images.githubusercontent.com/11788346/30513544-4ec649b8-9b05-11e7-929f-2e5900b5b096.png)

### Version used:
3.0.9 and develop branch from github

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))

```
Kirki::add_panel('modules', array(
	'priority' => 400,
	'title' => __('Modules', 'textdomain') ,
));
Kirki::add_config('theme_is_styles_global', array(
	'option_type' => 'option',
	'option_name' => 'is_global_modules_styles',
));
Kirki::add_section('modules_heading_section_global', array(
	'title' => __('Heading - Global') ,
	'priority' => 200,
	'panel' => 'modules'
));
Kirki::add_field('theme_is_styles_global', array(
	'type' => 'repeater',
	'label' => esc_attr__('', 'my_textdomain') ,
	'section' => 'modules_heading_section_global',
	'priority' => 10,
	'settings' => 'modules_isb_heading_simple_global',
	'option_type' => 'option',
	'default' => array() ,
	'fields' => array(
		'id' => array(
			'type' => 'text',
			'label' => esc_attr__('ID', 'my_textdomain') ,
			'default' => 'gl_',
			'description' => 'Pamiętaj o profiksie gl_',
			'tooltip' => 'PROBLEM NR2',
		) ,
	) ,
	'tooltip' => 'PROBLEM NR1',
));
```

**Comment by aristath** [comment]
This is because you have an empty label and it is therefore skipped.
Please add a label to the control and you'll see it works fine then.
