### ISSUE TITLE
HTML in tooltip is removed

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#1536]
### Issue description:
HTML tags are removed from tooltip. It's not possible to use - for example - `<strong>`, `<s>` or `<ul><li>` tags.
![image](https://user-images.githubusercontent.com/11788346/30515588-0a9d1390-9b2b-11e7-997f-6a7eb0658807.png)
![image](https://user-images.githubusercontent.com/11788346/30515598-5bef7ecc-9b2b-11e7-8fde-4a16de3f625c.png)

### Version used:
3.0.9 and dev branch from github

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))
```
Kirki::add_panel('modules', array(
	'title' => __('Modules', 'textdomain') ,
));
Kirki::add_config('theme_is_styles_global', array(
	'option_type' => 'option',
	'option_name' => 'is_global_modules_styles',
));
Kirki::add_section('modules_heading_section_global', array(
	'title' => __('Heading - Global') ,
	'panel' => 'modules'
));
Kirki::add_field('theme_is_styles_global', array(
	'type' => 'repeater',
	'section' => 'modules_heading_section_global',
	'settings' => 'modules_isb_heading_simple_global',
	'option_type' => 'option',
	'fields' => array(
		'id' => array(
			'type' => 'text',
			'label' => esc_attr__('ID', 'my_textdomain') ,
			'default' => 'gl_',
			'description' => 'Pamiętaj o profiksie gl_',
		) ,
	) ,
	'tooltip' => 'NORMAL TEXT <strong>STRONG TEXT</strong>',
));
```

**Comment by aristath** [comment]
fixed in the dev branch, will be included in 3.0.10
