### ISSUE TITLE
Change order of multiple select result

### ISSUE THREAD

**Issue by lucas-viewup** [themeum/kirki#1538]
### Issue description:
Hi there! I'm using select field with property multiple with value '3', then I add three posts following this order:

A, B, C

When I use get_theme_mod to get the selected posts, It comes C, B, A. Is there something to specify the order you selected? That would be interesting use something like Wordpress does in query like orderby and order properties.

### Version used:

Kirki version 2.2.7
Wordpress version 4.8.2

### Using theme_mods or options?

Using get_theme_mod function.

### Code to reproduce the issue (config + field(s))
Field: select
Properties: 
  multiple: '3'

**Comment by aristath** [comment]
Not currently...
There are plans to make select fields sortable but not until v3.1 (at which point we'll rewrite most fields and this can then be implemented).

But it should be fairly easy to sort them via PHP directly!
I'm assuming the way you're using it you get an array of post-IDs as the value, so from that point on you can sort them however you like!
