### ISSUE TITLE
Returning image URLS from radio-image field

### ISSUE THREAD

**Issue by Alanimus** [themeum/kirki#1539]
### Version used:

**3.0.10 beta**

### Using theme_mods or options?

**theme_mods**

### Code to reproduce the issue (config + field(s))

```
    Kirki::add_field( 'my_config', array(
	'type'        => 'radio-image',
	'settings'    => 'my_setting',
	'label'       => esc_html__( 'Radio Control', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => 'red',
	'priority'    => 10,
	'choices'     => array(
		'red'   => get_template_directory_uri() . '/assets/images/red.png',
		'green' => get_template_directory_uri() . '/assets/images/green.png',
		'blue'  => get_template_directory_uri() . '/assets/images/blue.png',
	),
) );
```

### Issue description:

**Using get_theme_mod('my_config', 'red'); only returns the key. I could save some code and effort if it would return the URL as I can use the same image for both the customizer control and the selected image it applies in this case.**

**Comment by aristath** [comment]
You can only get the key.
But it's not hard to get the URL from that... In your case something like this should work:
```php
$url = get_template_directory_uri() . '/assets/images/' . get_theme_mod( 'my_setting', 'red' ) . '.png'
```

**Comment by Alanimus** [comment]
Oh, nice. Thank you!

**Comment by aristath** [comment]
Just a note here, in my previous reply I forgot to add the default value in `get_theme_mod`.
I edited that comment to fix that 👍
