### ISSUE TITLE
Options won't update on develop branch

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#154]
Hi,

This was briefly discussed https://github.com/aristath/kirki/issues/148 but didn't get much attention due to other things going on. I've finally solved my git submodule issues and I believe things are stable now. 

I develop, which im using in production sites due to the assets loading problem in master, I've noticed some fields don't get updated. What I mean by this is that they keep their state between sessions, seem to trigger a page refresh in the customiser but the fields output is still the declared default value. This happened consistently both locally and in server with radio-image fields.

Have anything changed in this regard?

Thank you.

**Comment by aristath** [comment]
So...
1. You have a radio-image control.
2. You change its value
3. You refresh
4. The value is the old one and not the new one.

Did I get that right? If this is the case, can you check if this also happens with other field types as well, or isolated to the radio-images?

**Comment by lmartins** [comment]
Sort of, i think it's more like this:
1. I have a radio-image control.
2. I change its values and it's seems to be stored somewhere because it keeps it's state between sessions
3. I refresh and get the updated value in the control itself
4. but... if I inspect the outputted value in the front-end I get the default value (the actual property from the field configuration object)

I know this didn't happen this morning when I was already working with the develop branch on the server.

**Comment by aristath** [comment]
Oh! ok... So the controls and the customizer work fine.
What doesn't work is the CSS output of these controls, right?

Checking that now. :)

**Comment by lmartins** [comment]
In this case im reading the control value from PHP:

```
$layout = empty( kirki_get_option('shop_detail_layout') ) ? apply_filters( 'product_single_layout', 'content-sidebar' ) : kirki_get_option('shop_detail_layout');
```

**Comment by aristath** [comment]
ok... can you please do the following and let me know what you get?

``` php
$value = kirki_get_option( 'shop_detail_layout' );
var_dump( $value );
```

**Comment by lmartins** [comment]
Sure, I get:

```
string 'content-sidebar' (length=15)
```

which is the default value I pass in:

```
$controls[] = array(
                'type'     => 'radio-image',
                'section'  => 'layout_section_shop',
                'settings' => 'shop_detail_layout',
                'label'    => __( 'Product - sidebar position', 'wip' ),
                'choices'     => array(
                    'content-full' => PARENT_DIR_URI . '/img/kirki/content.png',
                    'content-sidebar' => PARENT_DIR_URI . '/img/kirki/content-sidebar.png',
                    'sidebar-content' => PARENT_DIR_URI . '/img/kirki/sidebar-content.png',
                ),
                'default'  => 'content-sidebar',
            );
```

At this point, the option I had active and saved was "content-full"

**Comment by aristath** [comment]
got it.
The kirki_get_option() value was always returning the default value. :+1: 
Try pulling the repo again and check...

**Comment by lmartins** [comment]
Oh yeah, working beautifully now :)
