### ISSUE TITLE
JavaScript error on Background Control

### ISSUE THREAD

**Issue by sazzadh** [themeum/kirki#1541]
### Issue description:
I am seeing a JavaScript error on Background Control and it's data is not being saved.

Uncaught TypeError: Cannot create property 'background-color' on string ''

### Version used:
3.0.10

### Using theme_mods or options?
theme_mods

**Comment by sazzadh** [comment]
@aristath

**Comment by aristath** [comment]
@sazzadh I can't replicate this one...
Can you please post the code you're using?

**Comment by sazzadh** [comment]
@aristath Please see this screenshot of the JS Error I am seeing. [http://prntscr.com/gom4mm](http://prntscr.com/gom4mm)

Here is the code that I am using
`SteedCOM_Kirki::add_field( 'steedcom', array(
				'type'     => 'background',
				'settings' => 'hero_section_bg',
				'label'    => __( 'Section Background', 'steed' ),
				'section'  => 'home_hero',
				'default'  => '',
				'priority' => 10,
			));`

**Comment by aristath** [comment]
Try this for default:
```php
	'default'     => array(
		'background-color' => '#333333',
		'background-image' => '',
	),

```

Where exactly did you see that `'default' => ''` that you're using? Do I have that in any docs? If so can you please point me to where you read it so that I may edit/fix it there?
Background controls save an array, not a string. So if you define a string as default value it will break.

**Comment by sazzadh** [comment]
@aristath Thanks now it is working.
Honestly I did not find any official documentation for background Control.
