### ISSUE TITLE
invalid format in field logo_image_3

### ISSUE THREAD

**Issue by ffrappo** [themeum/kirki#1545]
### Issue description:

After updating to the latest version there's an error repeating multiple times.

 `Notice: Kirki_Field::set_output Ã¨ stato richiamato in maniera scorretta. "output" invalid format in field logo_image_3. The "output" argument should be defined as an array of arrays. Leggi Debugging in WordPress per maggiori informazioni. (Questo messaggio Ã¨ stato aggiunto nella versione 3.0.10.) in /var/www/vhosts/poggioailegni.fornace.me/httpdocs/wp-includes/functions.php on line 4139`

Which translated would be: 
`Kirki_Field::set_output was called in a incorrect way. "output" invalid format in field logo_image_3. The "output" argument should be defined as an array of arrays.`

![screen shot 2017-09-27 at 13 21 41](https://user-images.githubusercontent.com/1463322/30910888-d7a092fa-a386-11e7-831a-6fff952a97e8.png)

### Version used:

3.0.10

### Using theme_mods or options?

Not sure, kirki came with a theme.

### Code to reproduce the issue (config + field(s))

**Comment by aristath** [comment]
Please contact the theme developer.

It looks like they have something like this in the `logo_image_3` field:
```php
'output' => array(
  'element' => 'something',
  'property' => 'something',
),
```
but as the error clearly states, the 'output' argument should be defined as an array of arrays as documented on https://aristath.github.io/kirki/docs/arguments/output.html
So the above should look like this:
```php
'output' => array(
  array(
    'element' => 'something',
    'property' => 'something',
  ),
),
```
