### ISSUE TITLE
Can Kirki also be used in post's meta: Meta Alternative

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1548]
Can Kirki also be used in post's meta? If yes then do you have any documentation? I am currently using CMB2, but if Kirki is capable of replacing that then I will go with Kirki. No point depending on two tools/library.

**Comment by ArekZw** [comment]
Unfortunately not :( Look #463 and #927

**Comment by aristath** [comment]
Not yet. This part is still under development, will probably be available in version 3.1.
