### ISSUE TITLE
[feature] Add simple repeater

### ISSUE THREAD

**Issue by maxviewup** [themeum/kirki#1549]
Sometimes i need an simple repeater (an repeater that have just one value - an simple array).

Currently, i use the code or textarea field and split the lines (eg: array of phones, names, etc).

The multiple select is an good example of what can be done: an field that multiple items (not pre-defined like multiple select) can be added and ordered.

**Comment by DannyCooper** [comment]
A simple repeater can be created like so:
```
Kirki::add_field(
	'arke_config_id',
	[
		'type'      => 'repeater',
		'label'     => esc_html__( 'Repeater Control', 'kirki' ),
		'section'   => 'title_tagline',
		'priority'  => 1,
		'row_label' => [
			'type'  => 'text',
			'value' => esc_html__( 'Repeater Field', 'kirki' ),
		],
		'settings'  => 'my_setting',
		'fields'    => [
			'simple_text' => [
				'type'        => 'text',
				'label'       => esc_html__( 'Text Field', 'kirki' ),
				'description' => esc_html__( 'A simple text field.', 'kirki' ),
				'default'     => '',
			],
		],
		'default'   => [
			[
				'simple_text' => esc_html__( 'Text Field Value', 'kirki' ),
			],
		],
	]
);
```

ref: https://kirki.org/docs/controls/repeater
