### ISSUE TITLE
Translation Parameter Issue

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1551]
> Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
> The domains found are puck, kirki

The theme check plugin is showing the above warning.

Now eliminating the extra text-domain is not a difficult task. we can use any **FIND AND REPLACE API** of sublime-text or atom, but when we change 'kirki' to 'puck' some functions and class also get changed that conflicts and the warning appear. Do you have any suggestions in which files I should avoid bulk changes through Find and replace?

**Comment by aristath** [comment]
You don't need to replace the textdomains... You shouldn't. See https://github.com/aristath/kirki/issues/1544#issuecomment-332286634 😉 
Replacing the textdomains would only be useful as a last resort in case the theme-reviewer doesn't understand the concept of internationalization in WP and the use of the `override_load_textdomain` filter in the plugin

**Comment by fastmarketo** [comment]
I am not using a plugin, but directly in my theme folder.

when I converted `, 'kirki'` into `, 'puck'` I got this error →

`Fatal error: Class 'Kirki_Toolkit' not found in /home2/....../wp-content/themes/puck/kirki/kirki.php on line 45`

The text domain should be one otherwise ThemeForest might refuse my theme upload.

**Comment by aristath** [comment]
I suspect you replaced not just `, 'kirki'` but also `, 'Kirki'`.

> The text domain should be one otherwise ThemeForest might refuse my theme upload.

No, they will not.
I provided a thorough explanation in https://github.com/aristath/kirki/issues/1544#issuecomment-332286634.

**Comment by fastmarketo** [comment]
Honestly, i couldn't spot the difference between the Two →

`, 'kirki'` but also `, 'Kirki'`

**Comment by aristath** [comment]
lowercase and uppercase K.
textdomains are lowercase.
PHP Classes however traditionally start with an uppercase letter as per the WP Coding standards.
The search and replace should be case-sensitive.
But I'll repeat once more: **I would strongly recommend against embedding the plugin in your theme. It is best if you require its installation as a plugin using something like [TGMPA](http://tgmpluginactivation.com/) for many many many reasons.**

**Comment by fastmarketo** [comment]
No, I haven't done that. yes, I know TGMPA.
