### ISSUE TITLE
Pulling Pages Is there way to Pull Posts

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1552]
https://aristath.github.io/kirki/docs/controls/dropdown-pages.html → This type is pulling pages. Is there any way to pull (only)posts also in a drop-down?

**Comment by aristath** [comment]
You can use a select control, and in the choices use the `Kirki_Helper::get_posts()` method.
Example:
```php
Kirki::add_field( 'my_config', array(
	'type'        => 'select',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => 'option-1',
	'priority'    => 10,
	'multiple'    => 1,
	'choices'     => Kirki_Helper::get_posts( array(
		'posts_per_page' => 10,
	) ),
) );
```
The `Kirki_Helper::get_posts` method accepts the same arguments as the [`get_posts`](https://codex.wordpress.org/Template_Tags/get_posts) function from WordPress core.
In fact if you look at [its code](https://github.com/aristath/kirki/blob/3.0.10/core/class-kirki-helper.php#L135-L167) you'll see it's just a wrapper for that function.

So the above method is just a faster way to write this:
```php
// Get the posts.
$args = array(
	'posts_per_page' => 10
);
$posts_from_args = get_posts( $args );

// Format the posts array like ( post_id => post_title ).
$posts_array = array();
foreach( $posts_from_args as $post ) {
	$posts_array[ $post->ID ] = $post->post_title;
}

// Add the control.
Kirki::add_field( 'my_config', array(
	'type'        => 'select',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => 'option-1',
	'priority'    => 10,
	'multiple'    => 1,
	'choices'     => $posts_array,
) );
```

**Comment by fastmarketo** [comment]
Ok Thanks, and how will I get the Post ID for the Post that is selected in the drop down?
Like this →
$selected_post_id = echo get_theme_mod('my_setting');

Or we need a certain extra bit.

Thanks for the Help.

**Comment by aristath** [comment]
Yup, that's how you get it.
The array of options using the above examples is formatted like `id => title`, so the saved value is the post-ID.
A simple `get_theme_mod` is all you need.

**Comment by fastmarketo** [comment]
thank you so much, sir.

I have to use it in my front page where currently hard code ID is there → 

`<?php $imvi = get_post_meta('311', 'bmeta_o', true); ?>
`
so this should be like →

`<?php $imvi = get_post_meta($selected_post_id, 'bmeta_o', true); ?>
`
Correct?

**Comment by fastmarketo** [comment]
I tried the above, but somehow it is not working not able to print?

which one is correct?
`$selected_post_id = echo get_theme_mod('my_setting');
`
or this →

`$selected_post_id = get_theme_mod('my_setting');
`
(W/O Echo)

**Comment by fastmarketo** [comment]
`$selected_post_id = echo get_theme_mod('my_setting');
`I think the above is not able to pull the Post ID: some tweak is needed. The entire approach is faulty. We have to combine it with get_the_id function somehow → 

> https://developer.wordpress.org/reference/functions/get_the_id/

**Comment by aristath** [comment]
```php
// Get the post-ID.
$selected_post_id = get_theme_mod( 'my_setting' );

// Print the post-ID.
echo $selected_post_id
```

**Comment by fastmarketo** [comment]
If I echo it gives pHP error →

`<?php $imvi = get_post_meta(echo $selected_post_id, 'bmeta_o', true); ?>`

If I make it like this then also PHP error → 
`<?php $imvi = get_post_meta(echo '$selected_post_id', 'bmeta_o', true); ?>`

When I was using the hard-coded Post ID it was working fine →
`<?php $imvi = get_post_meta('311', 'bmeta_o', true); ?>
`

I know the help I am seeking is a little bit more than Kirki support, but help will be highly appreciated.

**Comment by aristath** [comment]
`echo` works like this:

```php
echo 'SOMETHING';
```
Documentation for `echo can be found here: http://php.net/manual/en/function.echo.php

`get_theme_mod` works like this:
```php
$something_value = get_theme_mod( 'theme_mod_name', 'theme_mod_default_value' );
```
Documentation for `get_theme_mod` can be found here: https://codex.wordpress.org/Function_Reference/get_theme_mod

These 2 are wrong because you use `echo` inside `get_theme_mod`:
`<?php $imvi = get_post_meta(echo $selected_post_id, 'bmeta_o', true); ?>`
`<?php $imvi = get_post_meta(echo '$selected_post_id', 'bmeta_o', true); ?>`

This is wrong because you use 3 arguments in the get_theme_mod function and that function - as seen in its documentation page - only accepts 2 arguments:
`<?php $imvi = get_post_meta('311', 'bmeta_o', true); ?>`
The name of the setting is the 1st argument and the default value is the 2nd argument.

As mentioned in my previous reply, this is what your code should look like:
```php
// Get the post-ID and store it in a $selected_post_id variable.
$selected_post_id = get_theme_mod( 'my_setting' );

// Print the $selected_post_id variable.
echo $selected_post_id
```

If you insist on doing it in 1 line then it should be like this:
```php
echo get_theme_mod( 'my_setting' );
```
