### ISSUE TITLE
Need help creating demos

### ISSUE THREAD

**Issue by Gnodesign** [themeum/kirki#1556]
Hi,

First of all want to thank you for this beautiful plugin, I really love working with it.

I know this is not really a plugin issue but i have been searching to find an answer and I haven't find anything and I was hoping maybe someone could help me solve my issue.

So I have been developing a WordPress theme and i have given it a lot of options for the user to customize the site as he sees fit. The problem is how can i show them as a demo?

Lets say i have this code:
```
Kirki::add_field( 'my_config', array(
	'type'        => 'select',
        'label'       => esc_html__( 'Job Page Layout', 'cariera' ),
        'description' => esc_html__( 'Choose the sidebar side for your job page.', 'cariera' ),
        'section'     => 'single_job_option',
        'default'     => 'right-sidebar',
        'priority'    => 10,
        'choices'     => array(
              'left-sidebar'     =>  esc_attr__( 'Left Sidebar', 'cariera' ),
              'right-sidebar'    =>  esc_attr__( 'Right Sidebar', 'cariera' ),
              'fullwidth'        =>  esc_attr__( 'No Sidebar', 'cariera' ),
        ),
) );
```

Which means the "right-sidebar" is the default sidebar.
But how can i show the "left-sidebar" and "fullwidth" as demo pages?

I have seen a lot of people doing this for showing their demos:
mywebsite.com/blog/?sidebar=left-sidebar

I would really appreciate it if someone could help me achieve this.

Best regards,
Gino

**Comment by carasmo** [comment]
Hello,

This is well beyond the scope of this GitHub issues forum, which is bug reports and feature requests. 

There are many ways to do this. I would create three pages in my demo, add a body class to those pages that are left-sidebar and full-width, then with CSS that only loads with a plugin in your demo, you can show those pages as part of your demo site menu.

OR

Don't use the customizer and instead with ACF or CMB2 create a layout selector for that CPT type and create three entries in your Jobs CPT and then tick the radio for left, right, full on the different pages. Genesis and I believe Generate Press uses neither ACF or CMB2 and you can look how they do it. Not sure about Generate Press but with Genesis you can choose your layout globally and over-ride a layout on each archive page, post, page, or single CPT. 

When you see a parameter after a url, you can also just add those options with jQuery which adds a class based on the url parameter and then add CSS in your jQuery or load a style sheet and unload it. If you want it to persist after refresh, you will need to learn cookies or Session Storage. You would write the html, jQuery, and the CSS to make the demo panel.

**Comment by Gnodesign** [comment]
Thank you very much for your response.

I knew that from the beginning this was the last place that I could ask this kind of question.

The thing is that I have tons of different presets as like: preloaders, headers, footers, sidebars etc.

I thought maybe with some kind of hook or filter I could change the selected field temporary just for the specific page via the URL as a lot of other themes do.

I will have to dig in deeper to it.

Thank you very much for your time. :)

**Comment by aristath** [comment]
The usual practice and what most pro-themes do is to create a multisite installation and each demo is a site in that multisite.
Take for example the Avada theme:
https://avada.theme-fusion.com/music/
https://avada.theme-fusion.com/resume/
https://avada.theme-fusion.com/health/
^ These are just 3 sites in a multisite installation that has a couple dozen demos.

After the multisite is created, all you have to do is custom-code the sidebar that lets users switch from one demo to the other.

It's simple, effective, and let you do whatever you want. 👍
