### ISSUE TITLE
Typography controls bug

### ISSUE THREAD

**Issue by ukathemes** [themeum/kirki#1560]
Hi!

There is some problen with typography field. In this example: https://github.com/aristath/_s/blob/master/inc/customizer.php#L74-L124 if lines 114-117 commented out or deleted the same sub-fields in "body_typography" field don't work correctly.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
https://github.com/aristath/_s

**Comment by aristath** [comment]
Please elaborate.
What do you mean by "don't work correctly"?
The more details you provide the easier it will be for me to try and replicate the issue so that it can be fixed.

**Comment by ukathemes** [comment]
This sub-fields don't display default values and dont save it.

https://yadi.sk/i/GLCPChA43NTTpm

If "body_typography" and "headers_typography" have the same fields, all work correctly.

https://yadi.sk/i/x5C6LIVz3NTUz2

**Comment by dariodev** [comment]
This is the same issue as in #1521 - font-size and line-height are not saved in v3.0.10, also does not work in latest develop version. Works fine in v.3.0.9.

**Comment by ukathemes** [comment]
> This is the same issue as in #1521 - font-size and line-height are not saved in v3.0.10, also does not work in latest develop version. Works fine in v.3.0.9.

It happens when we have more than one typography field and if they have diferent sub-fields.
Also, reset button delete font variant.

**Comment by aristath** [comment]
Thank you both for the extra details, this was just fixed.
