### ISSUE TITLE
No tooltips with 3.0.10 update

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1562]
### Issue description:
As the title says i lost all help tooltips with last update. No icon shows nowhere

### Version used:
Version 3.0.10

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

I'm using your _s theme with a clean WP install for these tests.
Thanks!

**Comment by ukathemes** [comment]
Use "tooltip" instead "help".

**Comment by enginne** [comment]
@vakulesh Worked! Thanks!
