### ISSUE TITLE
Typography not working  in 3.0.10

### ISSUE THREAD

**Issue by stylethemes** [themeum/kirki#1564]
hi
so I'm working with kirki on a theme im developing and i'm facing a little problem with the typography 

here is the code I'm using the problem is when i change the font family nothing happens even when i did the use the typography filed still nothing happens

<h3>font using a select field</h3>
<pre>kirki::add_field( 'my_config', array(
        'type'      => 'select',
		'setting'   => 'blog_font_family',
		'label'     => __( 'blog Font Family', '' ),
		'section'   => 'typography_options',
		'default'   => 'Roboto',
        'choices'   => Kirki_Fonts::get_font_choices(),
        'output'      		=> array(
            array(
                'element'  		=> 'h1.entry-title',
                'property' => 'font-family',
            ),            
        ),
    ));
</pre>
<h3>font using typography field</h3>

<pre>
kirki::add_field( 'my_config', array(
	'type'        => 'typography',
	'setting'   => 'blog_font_family',
	'label'       => esc_attr__( 'Headers Typography', '_s' ),
	'description' => esc_attr__( 'Select the typography options for your headers.', '_s' ),
	'help'        => esc_attr__( 'The typography options you set here will override the Body Typography options for all headers on your site (post titles, widget titles etc).', '_s' ),
	'section'   => 'typography_options',
	'priority'    => 10,
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => '400',
		 'font-size'      => '16px',
		'line-height'    => '1.5',
		// 'letter-spacing' => '0',
		// 'color'          => '#333333',
	),
	'output' => array(
		array(
			'element' => 'h1.entry-title',
		),
	),
) );
</pre>
in both examples when i do change the font family in the customizer nothing happens.

is there is something I'm missing because i think the style get generated automatically when using the output argument

<h3>Version used: 3.0.10</h3>

<h3>Using theme_mods or options?</h3>
theme_mods

**Comment by victoras** [comment]
+1

**Comment by aristath** [comment]
This seems to be working fine:
```php
Kirki::add_field( 'kirki_demo', array(
	'type'        => 'typography',
	'settings'    => 'body_typography',
	'label'       => esc_attr__( 'Body Typography', '_s' ),
	'description' => esc_attr__( 'Select the main typography options for your site.', '_s' ),
	'help'        => esc_attr__( 'The typography options you set here apply to all content on your site.', '_s' ),
	'section'     => 'typography',
	'priority'    => 10,
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => '400',
		'font-size'      => '16px',
		'line-height'    => '1.5',
		'color'          => '#333333',
	),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element' => 'body',
		),
	),
) );

```
Do you by any chance have any CSS rules in a css file that may be overriding the CSS rules that Kirki outputs?

**Comment by stylethemes** [comment]
yeah its working fine now all i did is updating the kirki-fallback.php file i think it was causing the problem now everything is working fine
