### ISSUE TITLE
Multicolor control values are not saved completely (in css file)

### ISSUE THREAD

**Issue by kodeoagency** [themeum/kirki#1565]
### Issue description:

When using the multicolor control with a minimal output configuration (e.g. ‘output’ => [[ ‘element’ => ‘body’ ]]), the customizer preview works as expected, but the values are not being saved, except of color

Here is our control:

 'button_default_colors' => [
                        'type' => 'multicolor',
                        'choices' => [
                            'background' => _x( 'Background', 'Customizer', 'startgarten' ),
                            'border-color' => _x( 'Border', 'Customizer', 'startgarten' ),
                            'color' => _x( 'Text', 'Customizer', 'startgarten' )
                        ],
                        'output' => [[ 'element' => 'button' ]],
                    ],

### Version used:
3.0.10 (public)

**Comment by aristath** [comment]
Fixed in the develop branch, will be included in 3.0.11

**Comment by kodeoagency** [comment]
Thank you very much!!!
