### ISSUE TITLE
Typography / text-align not working

### ISSUE THREAD

**Issue by OrangeIdea** [themeum/kirki#1566]
### Issue description:
Hello, under typography field text-align not working.

### Version used:
3.0.10

### Code to reproduce the issue (config + field(s))
<pre>
Kirki::add_field( 'name', array(
	'type' => 'typography',
	'settings' => 'bottom_line_text_typography',
	'label' => esc_html__( 'TEXT -> Typography', 'textdomain' ),
	'section' => 'bottom_line',
	'default' => array(
		'font-family'    => 'Roboto',
                'variant'        => 'regular',
                'font-size'      => '12px',
                'line-height'    => '1.5',
                'letter-spacing' => '0',
                'subsets'        => array( 'latin-ext' ),
                'color'          => '#666',
                'text-transform' => 'none',
                'text-align'     => 'right'
	),
	'priority' => 3,
	'output' => array(
		array(
			'element' => '#bottomline',
		),
	)

) );
</pre>

Thre are no "text-align" in output
<pre>
#bottomline{font-family:Roboto, Helvetica, Arial, sans-serif;font-size:12px;font-weight:400;font-style:normal;line-height:1.5;text-transform:none;color:#666666;}
</pre>

Thre are no "text-align" in array
<pre>

Array
--
  | (
  | [font-family] => Roboto
  | [variant] => regular
  | [font-size] => 12px
  | [line-height] => 1.5
  | [letter-spacing] => 0
  | [color] => #666666
  | [font-weight] => 400
  | [font-style] => normal
  | [subsets] => Array
  | (
  | [0] => latin
  | )
  |  
  | [text-transform] => none
  | )

</pre>

**Comment by aristath** [comment]
fixed in https://github.com/aristath/kirki/commit/e3050efdb299d9270a5cf0b4450e684a2a544c5a
