### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1567]
### Issue description:

Hey @aristath,

I'm getting the following error using 3.0.10 and also with the latest dev branch having debug mode activated:

![undefined-index](https://user-images.githubusercontent.com/22119831/31234880-56544604-a9f0-11e7-8534-774e1614b34c.png)

### Version used:
latest dev & 3.0.10

**Comment by aristath** [comment]
can you post the code of your field please?

**Comment by mapsteps** [comment]
I guess this is not triggered by a specific field but I may be wrong.

**Comment by mapsteps** [comment]
PS: this just shows up for like a second, then the customizer is loaded properly.

**Comment by aristath** [comment]
This is weird...
I can't replicate it.

I make sure there's a `language` defined in https://github.com/aristath/kirki/blob/3.0.10/field/class-kirki-field-code.php#L39-L43 which runs before the `Kirki_Control_Code` class. So this should not be happening...
However I just pushed a commit that adds an extra fix there for sanity's sake.
It should be ok now in the dev branch 👍

**Comment by mapsteps** [comment]
Confiremd. Works with the latest dev branch :) Thanks!
