### ISSUE TITLE
Textarea field display issue

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1568]
### Issue description:

With 3.0.10 - and also the latest dev branch - my textarea's look like this:

![text-fields](https://user-images.githubusercontent.com/22119831/31235145-fc021d06-a9f0-11e7-92dc-3553a8a3d28b.png)

### Version used:
3.0.10 & latest dev

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'mytheme', array(
	'type' => 'textarea',
	'settings' => 'footer_column_one',
	'label' => __( 'Column 1', 'textdomain' ),
	'section' => 'footer_options',
	'default' => esc_attr__( '&copy; [year] - [blogname] | All rights reserved', 'textdomain' ),
	'priority' => 2,
	'active_callback' => array(
		array(
		'setting' => 'footer_layout',
		'operator' => '!=',
		'value' => 'none',
		),
	)
) );
```

**Comment by aristath** [comment]
I can't replicate this one either...

Control looks fine to me
<img width="290" alt="screenshot at oct 05 21-00-00" src="https://user-images.githubusercontent.com/588688/31242612-41cbd38a-aa10-11e7-8f66-2c516502f126.png">

**Comment by mapsteps** [comment]
Figured that both issues I reported have to do with me using kirki from a plugin, not a theme.

```
// Kirki Init
require_once( MY_THEME_DIR . '/assets/kirki/kirki.php' );

// Kirki
require_once( PLUGIN_DIR . 'inc/customizer/fields.php' );
```

I first grab the kirki.php from the theme to initialize it, while the fields.php file holds the kirki configuration, panels and fields. I'll dig deeper into this.

**Comment by mapsteps** [comment]
@aristath,

looks like I've found a solution here. Instead of initializing kirki again from the plugin, I wrapped all fields in a function and hooked them into the theme file which holds all fields. (The Plugin is a premium addon that adds more functionality to the theme).

Doing this solves multiple issues.

1. the one discussed here
2. https://github.com/aristath/kirki/issues/1518#issuecomment-328070860
3. https://github.com/aristath/kirki/issues/1567

Hooking into the theme works fine. Please let me know if you have any thoughts on this or a recommended solution.

Thanks!
