### ISSUE TITLE
shortcode field

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1570]
which Field type do you think can take shortcode and then print it in a required area like. I tried many field type, but none worked.

`get_theme_mod('kirki_one');`

**Comment by enginne** [comment]
You have to call the the output code with the do_shortcode() function, like:

$my_text_field = get_theme_mod( 'kirki_one', '' );
echo do_shortcode( $my_text_field);

Text, textarea and editor fields work with this approach.

**Comment by fastmarketo** [comment]
very nice sir. it worked like a charm.
