### ISSUE TITLE
get_option is not working for partial refresh.

### ISSUE THREAD

**Issue by asharirfan** [themeum/kirki#1571]
### Issue description:
Hello guys 🙌

Great plugin. I love it. It is simple and easy to use. I am trying out your plugin for my theme, and I have come across a strange issue.

I have added a **toggle** field, and I am using partial refresh along with it. Everything works fine. My content toggles just fine before saving the first time.

Then I turn the toggle option to ON and save the settings. After I refresh the page and come back. I try to turn the toggle OFF and suddenly the content is not going away.

I logged the **get_option** function inside **render_callback** to check and every time I turn the toggle switch, the same value is returned by get_option i.e. **1**. I have made the following screencasts for the issue.

Before saving toggle as ON:
[Screencast](http://jmp.sh/xrIjaca)

After saving the toggle as ON:
[Screencast](http://jmp.sh/tpKUYZV)

Any ideas why this might be happening?

### Version used:
3.0.10

### Using theme_mods or options?
Options

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'my_config_label', array(
	'type'     => 'toggle',
	'settings' => 'my_setting',
	'label'    => esc_html__( 'Show Footer Logo', 'text_domain' ),
	'section'  => 'my_footer_section',
	'default'  => '1',
	'priority' => 1,
	'partial_refresh' => array(
		'my_setting' => array(
			'selector'        => '.footer__logo a',
			'render_callback' => function() {
				my_log_function( get_option( 'my_setting' ) );
				if ( 1 == get_option( 'my_setting' ) ) {
					return my_content();
				} else {
					return '';
				}
			},
		),
	),
) );
```

**Comment by aristath** [comment]
Can you please also post your config?

**Comment by asharirfan** [comment]
Here is my config:

```php
$config_args = array(
	'capability' => 'edit_theme_options',
	'option_type' => 'option',
	'disable_output' => true,
);
Kirki::add_config( 'my_config', $config_args );
```

**Comment by aristath** [comment]
Hmmm... this is a really weird one.
Everything in Kirki seems to be working fine and all the data is passed-on properly. I couldn't find anything that would cause this in the plugin.
I also tested it with theme-mods and it works fine there.
The only difference between theme_mods and options is that theme_mods are autoloaded in WP while options are not. 🤔

**Comment by asharirfan** [comment]
@aristath I finally got it to work.

But now it is giving messed up values in partial refresh callback function. When I turn the toggle off, I am getting ```string (1)``` — [related screenshot](http://jmp.sh/YIyrbHE).

When I turn in on, I am getting ```boolean true``` which is fine — [related screenshot](http://jmp.sh/n5tTxkd).

Don't you think it should give ```false``` or an empty string when the toggle is turned off?
