### ISSUE TITLE
Fetching post ID

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1572]
```
    $fields[] = array(
        'type'        => 'select',
    	'settings'    => 'kirki_post_id',
    	'label'       => __( 'seclect the Box Post ID', 'blogeto' ),
    	'section'     => 'home_page',
    	'default'     => 'option-1',
    	'priority'    => 10,
    	'multiple'    => 1,
    	'choices'     => Kirki_Helper::get_posts( array(
    		'posts_per_page' => 20,
    	) ),
    );
```
![kirkipost_dropdown](https://user-images.githubusercontent.com/6827222/31308911-e76b2016-ab9b-11e7-965c-dd4912d8daf0.png)

Above is the arrangement through which I am trying to fetch the Post ID.

Is this syntax to fetch the Post ID correct:

`<?php $kirki_post_id = get_theme_mod('kirki_post_id'); ?>
`
or something like this →
`<?php $kirki_post_id = get_the_ID(get_theme_mod('kirki_post_id') ); ?>
`
Or perhaps both are wrong, and the correct syntax is something else?

**Comment by aristath** [comment]
The 1st one.

**Comment by fastmarketo** [comment]
see, 

In `single.php` the code looks like somewhat this →

`<?php $imv= get_post_meta(get_the_ID(), 'tvideo', true); ?>`

But that is something based on the loop, but what If we want this to be published somewhere on the homepage based on the POST ID selected? 

so instead of this →
`get_the_ID()` we need an ID based on the post chosen by the user.

so If i use the first one →
`<?php $kirki_post_id = get_theme_mod('kirki_post_id'); ?>`

How will this be written then→
`<?php $imv= get_post_meta(get_the_ID(), 'tvideo', true); ?>`


Like this →
`<?php $imv= get_post_meta(get_the_ID($kirki_post_id ), 'tvideo', true); ?>`

or

Like This →

`<?php $imv= get_post_meta(kirki_post_id , 'tvideo', true); ?>`

or absolute something other than what I am trying to do?

**Comment by fastmarketo** [comment]
is there a way i can send you my actual code in private(code branding issue)?

**Comment by aristath** [comment]
Your current code is this:
```php
<?php $imv= get_post_meta(get_the_ID(), 'tvideo', true); ?>
```
so you need to replace the `get_the_ID()` function with the new post-ID:
```php
<?php $kirki_post_id = get_theme_mod( 'kirki_post_id' ); ?>
<?php $imv= get_post_meta( $kirki_post_id, 'tvideo', true); ?>
```

It's not necessary to do it in 1 line...
Sometimes splitting to multiple lines makes things easier to understand.
In the 1st line there we're getting the post-id, and in the 2nd line we're using it in place of the `get_the_ID()` function.

> is there a way i can send you my actual code in private?

No reason to send your code, your issues are not related to kirki and forgive me if I'm being blunt or rude but I don't run a coding school. I help out as much as I can whenever I have a few minutes to spare, but you should really study PHP some more before even attempting to write a WordPress theme.

**Comment by fastmarketo** [comment]
Ok sir.
