### ISSUE TITLE
Mutliple image fields cannot be saved as array

### ISSUE THREAD

**Issue by darkogerguric** [themeum/kirki#1574]
Hi,
I am working with Kirki for the first time, and have found this post  #1555

Turns out it is possible to save image as the array, but after I save one, second image field cannot be saved.
If I remove this part from second image field it gets saved normally. 
Any idea what I am missing?
```
'choices' => array(
		'save_as' => 'array'
	), 
```

**Comment by aristath** [comment]
Welcome @dare023, I'm glad you like Kirki. 😄 

I just tested this but I can't replicate it.
Did you try using the develop branch? Or just the stable version from wordpress.org?
If you didn't try the develop branch from this repository can you please try that?
If that doesn't work either, please post your code here so that I may try to replicate the issue and see what's wrong.

**Comment by darkogerguric** [comment]
Hi, I tried both.
Here is a code, not sure if I am missing something, but saving as id works, I am ok with that too. 
One more thing, after I have set "save as" options form images, as soon I open customizer I can see enabled  "save" button and even after hitting it, I still get prompt if I try to leave customizer.
Heri is code, displaying array gives just empty fields, this is when using files from here, now it is not even saving at all
```
Kirki::add_field( 'geek_config', array(
	'type'        => 'image',
	'settings'    => 'icon_11',
	'label'       => __( 'Set icon under list', 'my_textdomain' ),
	'section'     => 'geek_id',
	'default'     => '',
	'priority'    => 10,
	'choices' => array(
		'save_as' => 'array'
	),
) );

Kirki::add_field( 'geek_config', array(
	'type'        => 'image',
	'settings'    => 'icon_12',
	'label'       => __( 'Set icon under list', 'my_textdomain' ),
	'section'     => 'geek_id',
	'default'     => '',
	'priority'    => 11,
	'choices' => array(
		'save_as' => 'array'
	),
) );
```

**Comment by DannyCooper** [comment]
Tested using the code provided by the original poster and this works as expected in the v3.0.41.
