### ISSUE TITLE
Popup Color Palettes

### ISSUE THREAD

**Issue by dwfee** [themeum/kirki#1575]
I need a lot of colorpalettes (all with complete material color set) and it would be very nice not to have them loaded all in a row since they take a lot of room, just for one color value it takes a lot of space.
So a colorpalette just like the multi-color field, but only with the palette colors would be great!
See https://github.com/carloscabo/jquery-palette-color-picker
Greetings DWFee

**Comment by mapsteps** [comment]
Good call, though probably rarely needed. I'm closing this for now but consider re-opening it if we get more requests for this.
