### ISSUE TITLE
[report] Field editor (differences between versions 3.0.9 and 3.0.10)

### ISSUE THREAD

**Issue by lucas-viewup** [themeum/kirki#1576]
### Issue description:
@aristath, I noticed some differences between the version **3.0.9** and **3.0.10**, just to let you know:

* In **3.0.9**, ~~the editor field is okay, but I found some encoding problem, specially when you use **&**, my guess it's because it's converted to html, the **&** becomes **\&amp;**.~~ That's the expected behaviour of editor, convert text to html, but this problem is happening in a **text field**.

* In **3.0.10**, ~~the encoding problem it's finally fixed~~, consider that for text field, but I noticed that  editor button doesn't close the editor (the close button is working at 3.0.9). I also got some duplicated content in two different editor fields (I will try to reproduce this below the best way I can, hold on).

### Versions used:
Kirki 3.0.9, 3.0.10, 3.1.0 and develop

### Using theme_mods or options?
Theme mods
### Code to reproduce the issue (config + field(s))

```php
Kirki::add_config( 'twentyseventeen', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

Kirki::add_panel( 'panel_test', array(
	'priority'    => 10,
	'title'       => __( 'The Panel', 'twentyseventeen' ),
	'description' => __( 'The Description', 'twentyseventeen' ),
) );

Kirki::add_section( 'section_test', array(
	'title'          => __( 'Test Section' ),
	'description'    => __( 'Test Section' ),
	'panel'          => 'panel_test', // Not typically needed.
	'priority'       => 160,
	'capability'     => 'edit_theme_options',
	'theme_supports' => '', // Rarely needed.
) );

Kirki::add_field( 'twentyseventeen', array(
	'settings' => 'my_setting',
	'label'    => __( 'My custom control', 'twentyseventeen' ),
	'section'  => 'section_test',
	'type'     => 'editor',
	'priority' => 10,
	'default'  => 'some-default-value',
) );
```

Hope in 3.1.0 these problems will be fixed.
Regards and thanks for support!

**Comment by lucas-viewup** [comment]
**Tested at 3.0.10:**

![kirki2](https://user-images.githubusercontent.com/28161720/31389621-f72c4940-ada7-11e7-99ab-3c84a617e429.gif)


**page-test.php**
```php
<?php get_header(); ?>

    <h1>first editor</h1>

    <?= get_theme_mod('my_setting', 'default of first setting'); ?>

    <h2>second editor</h2>

    <?= get_theme_mod('my_setting2', 'default of second setting'); ?>

<?php get_footer(); ?>
```
**customizer.php**

```php
        Kirki::add_config( 'twentyseventeen', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	) );


	Kirki::add_panel( 'panel_test', array(
		'priority'    => 10,
		'title'       => __( 'The Panel', 'twentyseventeen' ),
		'description' => __( 'The Description', 'twentyseventeen' ),
	) );
	
	
	Kirki::add_section( 'section_test', array(
		'title'          => __( 'Test Section' ),
		'description'    => __( 'Test Section' ),
		'panel'          => 'panel_test', // Not typically needed.
		'priority'       => 160,
		'capability'     => 'edit_theme_options',
		'theme_supports' => '', // Rarely needed.
	) );

	Kirki::add_section( 'section_test2', array(
		'title'          => __( 'Test Section 2' ),
		'description'    => __( 'Test Section 2' ),
		'panel'          => 'panel_test', // Not typically needed.
		'priority'       => 160,
		'capability'     => 'edit_theme_options',
		'theme_supports' => '', // Rarely needed.
	) );

	Kirki::add_field( 'twentyseventeen', array(
		'settings' => 'my_setting',
		'label'    => __( 'My custom control', 'twentyseventeen' ),
		'section'  => 'section_test',
		'type'     => 'editor',
		'priority' => 10,
		'default'  => 'some-default-value',
	) );

	Kirki::add_field( 'twentyseventeen', array(
		'settings' => 'my_setting2',
		'label'    => __( 'My custom control2', 'twentyseventeen' ),
		'section'  => 'section_test2',
		'type'     => 'editor',
		'priority' => 11,
		'default'  => 'some-default-value',
	) );
```

**Comment by aristath** [comment]
I think there's a slight misunderstanding here.
If you don't close the editor or click to open another editor, the previous data will be displayed and handled.
In your screencast I can see you change sections, but you don't click on the actual editor buttons to switch to the other control.

**Comment by lucas-viewup** [comment]
Ok, I admit I didn't switched the editor, but It's strange that two different settings have the same value. Is it possible to implement to close the editor when you switch the section or when you access other editor to avoid this mistake then? And other thing I observed was referenced in #1584. I guess it is an intermittent problem because I tested today and I didn't observed nothing, only the fact the missing last character. I will check it out the 3.0.11.

**Comment by kennydude** [comment]
I'm also seeing the same issue with the new version. The setting seems to have set for all of the editor settings which is rather annoying :/

**Comment by DannyCooper** [comment]
@aristath Is this an old UI for `editor`?

**Comment by aristath** [comment]
Yeah, it's about a previous implementation that was later removed when WP-Core added a way to add tinyMCE to widgets & the customizer.
This old version was forcing a hack which had its issues. There was a single instance of TinyMCE, and the "control" was a button that was triggering a content area to slide-up from the preview pane. When there were multiple editor controls, clicking on another control's button would change the content of the editor and so on. If I remember correctly it was inspired by a "Customize Posts" feature-plugin than never made it in WP Core.
Closing the ticket since it's no longer relevant.
