### ISSUE TITLE
Feature Request: Transparent Option in Color Controls

### ISSUE THREAD

**Issue by kodeoagency** [themeum/kirki#1577]
It would be super helpful to have a transparent option in color and multicolor controls, especially for background colors.

<img width="348" alt="bildschirmfoto 2017-10-11 um 09 25 31" src="https://user-images.githubusercontent.com/32045038/31427080-4e5f9e2e-ae66-11e7-8e63-9b7de733b190.png">

**Comment by aristath** [comment]
why don't you simply use it in rgba mode?

**Comment by kodeoagency** [comment]
This is what we're doing right now.
But for the end user it can be very confusing. 
Let say, we use rgba(255,0,0,0) as default.
Now the end user tries to change the color by using the selector. By doing this nothing will happen because the Alpha Slider is still set to 0 which make every new color look like transparent.

![bildschirmfoto 2017-10-11 um 17 06 14](https://user-images.githubusercontent.com/32045038/31449375-06854658-aea7-11e7-8284-3459876c3486.png)

**Comment by JPDubois** [comment]
Most color picker works with alpha channel. This would be for a very tiny part of user (apparently yours).

**Comment by kodeoagency** [comment]
Hi JPDubois, 
our end users are not developers, unfortunately.
From many years of experience with non developer users I know that those things can give them a hard time.

**Comment by DannyCooper** [comment]
```
Kirki::add_field( 'theme_config_id', [
	'type'        => 'color',
	'settings'    => 'color_setting_rgba',
	'label'       => __( 'Color Control (with alpha channel)', 'kirki' ),
	'description' => esc_html__( 'This is a color control - with alpha channel.', 'kirki' ),
	'section'     => 'section_id',
	'default'     => '#0088CC',
	'choices'     => [
		'alpha' => true,
	],
] );
```
