### ISSUE TITLE
Uncaught TypeError: data.value[choiceKey].replace is not a function

### ISSUE THREAD

**Issue by gbyat** [themeum/kirki#1578]
### Issue description:
VM987:39 Uncaught TypeError: data.value[choiceKey].replace is not a function
    at eval (eval at m.template (underscore.min.js?ver=1.8.3:5), <anonymous>:39:35)
    at c (underscore.min.js?ver=1.8.3:5)
    at wp-util.js?ver=4.8.2:34
    at child.renderContent (customize-controls.js?ver=4.8.2:2255)
    at child.actuallyEmbed (dynamic-control.js?ver=4.8.2:165)
    at Function.<anonymous> (dynamic-control.js?ver=4.8.2:145)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith (jquery.js?ver=1.12.4:2)
    at Function.set (customize-base.js?ver=4.8.2:221)
    at Function.d [as set] (jquery.js?ver=1.12.4:2)
Issue caused by control dimensions, line 137:
<input {{{ data.inputAttrs }}} type="text" value="{{ (data.value[ choiceKey ]).replace( '%%', '%' ) }}"/>
happens on zero values (0 != string)
<input {{{ data.inputAttrs }}} type="text" value="{{ (data.value[ choiceKey ]+'').replace( '%%', '%' ) }}"/>
fixed it but may be not the elegant way

### Version used:
WP 4.8.2 | Kirki 3.0.10

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
I was unable to replicate your issue, I suspect it has something to do with the code you're using or the saved values.
In any case, I added an extra check for this so it should be ok now.

**Comment by gbyat** [comment]
Thank you.

**Comment by gbyat** [comment]
found the cause of the issue. some of my controls are generated by a function and empty values were replaced by 0 (to keep the setting available). changed them to '0' - this fixed it. 
'0' now is a string. 0 was not a string. this caused the error. sorry for the circumstances. but possibly interesting and you want to know:
control dimension: `data.value.toString().replace( '%%', '%' )` would work for the 0-case
control dimensions: `data.value[ choiceKey ].toString().replace( '%%', '%' )` also

**Comment by gbyat** [comment]
found the issue. some of my controls are generated by a function. changed 0 (not a string > caused the issue) to '0' (string, no issue). this fixed it.
for this case in dimensions `data.value[ choiceKey ].toString().replace( '%%', '%' )` worked and in dimension `data.value.toString().replace( '%%', '%' )`
