### ISSUE TITLE
[feature] Styling Customizer - More options

### ISSUE THREAD

**Issue by maxviewup** [themeum/kirki#1579]
Currently Kirki allows the configuration of 2 colors to style the customizer. Then, it make some color math and calculate new colors from the 2 initials. Would be nice if Kirki allows the manual configuration of each color for more customization. 

An simple solution for this would be add an filter for the calculated colors or use the calculated colors as default and if user sets the color variable, the default would be override.

**Comment by niklasp** [comment]
possibly add the feature label

**Comment by aristath** [comment]
>  Would be nice if Kirki allows the manual configuration of each color for more customization.

Actually the plan is to completely remove that module from Kirki-core, and instead allow developers to easier define their own stylesheets.
There's no timeframe on that ir any solid plans on how the deprecation will happen. But at some point it will happen.
If you want to add custom styles to the customizer I'd advise you to simply add custom CSS using something like this:
```php
add_action( 'customize_controls_print_styles', function() {
	?>
	<style>
		/* Your custom styles here. */
	</style>
	<?php	
} );
```
