### ISSUE TITLE
Reset button does not work in the Static Front Page section

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#1580]
### Issue description:
Pressing the "Reset" button does not actually reset the fields in the Static Front Page section.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) 
Yes, I tried this with the dev branch.

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))
Do not apply (this is a WordPress default panel)

![screen-recording-2017-10-11-15-39-50](https://user-images.githubusercontent.com/1451087/31460005-51385a48-ae9b-11e7-9d8e-796d8716312d.gif)

**Comment by aristath** [comment]
Nice catch, fixed. 👍

**Comment by pagelab** [comment]
Thanks, @aristath. I just realized that the Reset button isn't' working also with widgets.

Tested with three themes: Twenty Seventeen, Twenty Fifteen and Riba Lite (just a random theme I installed to test this).

![screen-recording-2017-10-11-16-22-32](https://user-images.githubusercontent.com/1451087/31499787-2d26a9ec-af3c-11e7-8921-6c9d571703ed.gif)

**Comment by aristath** [comment]
Did you try pulling the latest commits?
Reset is now only added to Kirki sections

**Comment by pagelab** [comment]
Oh, I see. Yes, I tried the last commit and the Reset button was indeed removed in default sections. 👍

**Comment by pagelab** [comment]
@aristath, https://github.com/aristath/kirki/commit/1f59e2e2bcf11f7e4f9619750c70b4ca065d648f does not work with fields created using the default customizer API methods.

The class `control-section-kirki-default`, used in the conditional check, is added to the code only when Kirki methods are being used to add fields.

**Comment by aristath** [comment]
Yes, that was the intention.
TBH if I could I would completely remove the reset feature... It's problematic and [there's already a ticket in WP-Core to add reset there](https://core.trac.wordpress.org/ticket/21666), so I can't wait for that to happen :P
But if a plugin provides a reset feature, it makes sense that it would be intended for the sections created by that plugin.
Any section created using `Kirki::add_section()` will have the reset on top.

**Comment by pagelab** [comment]
Ok, got it. I'll use the Kirki methods then. Thanks @aristath.
