### ISSUE TITLE
New option type: Sidebar select does not save value

### ISSUE THREAD

**Issue by webangon** [themeum/kirki#1585]
Version:       3.0.10
Using : theme_mod

Here is my approach to select sidebar dropdown. The sidebars appear as dropdown but its not saving value into database. 
```
add_action( 'customize_register', function( $wp_customize ) {
	/**
	 * The custom control class
	 */
	class Kirki_Controls_Notice_Control extends WP_Customize_Control {
		public $type = 'sidebars';
		public function render_content() {
			$sidebar_options = $GLOBALS['wp_registered_sidebars'];
		 ?>
		    <select>
		        <?php foreach( $sidebar_options as $option ){ ?>
		            <option value="<?php echo $option['id']; ?>"><?php echo $option['name']; ?></option>
		        <?php } ?>
		    </select>

			<?php
		}
	}
	// Register our custom control with Kirki
	add_filter( 'kirki/control_types', function( $controls ) {
		$controls['sidebars'] = 'Kirki_Controls_Notice_Control';
		return $controls;
	} );

} );
```

**Comment by aristath** [comment]
Try replacing this part:
```php
<select>
	<?php foreach( $sidebar_options as $option ){ ?>
		<option value="<?php echo $option['id']; ?>"><?php echo $option['name']; ?></option>
	<?php } ?>
</select>
```
with this:
```php
<select <?php $this->link(); ?>>
	<?php foreach ( $sidebar_options as $option ) : ?>
		<option value="<?php echo esc_attr( $option['id'] ); ?>" <?php echo selected( $this->value(), $option['id'], false ); ?>><?php echo esc_html( $option['name'] ); ?></option>
	<?php endforeach; ?>
</select>
```
I didn't test the code but in theory it should work.

The important part is the `<?php $this->link(); ?>` in `<select>` which tells the WP Customizer API where to save the value, and then the `selected( $this->value(), $option['id'], false )` part will make sure that after saving and reloading the customizer, the selected option will be displayed.

There are many tutorials online about how to create your own custom controls, a good place to start is - as always - Otto's blog: http://ottopress.com/2012/making-a-custom-control-for-the-theme-customizer/

**Comment by aristath** [comment]
And you can always look at WP-Core to see how they do things there so you can base your code on that: https://github.com/WordPress/WordPress/blob/4.8.2/wp-includes/class-wp-customize-control.php#L544-L549

**Comment by webangon** [comment]
Thanks for your comment. I will check tonight.

**Comment by aristath** [comment]
Just a note here, you can also see https://github.com/aristath/kirki/issues/1702#issuecomment-351792415 I posted an example there
