### ISSUE TITLE
Kirki_Helper::get_post_types() doesn't return post types registered by plugins

### ISSUE THREAD

**Issue by dameer** [themeum/kirki#1586]
This method returns only default WordPress post types! In case we have WooCommerce installed it'll not include 'product' post type. I suppose it's due to the fact that WP's "get_post_types()" is triggered before plugins loaded.
Is there a way to fire this Kirki method on 'wp_loaded' hook somehow?

**Comment by enginne** [comment]
Use _add_action( 'init',...._    to get triggered before plugins load.

This is the way i did it to get the woo products taxonomies in a select field.

```
add_action( 'init', 'add_events_categories_customizer_control', 12 );

function add_events_categories_customizer_control()
{

	leo_Kirki::add_field( 'andy', array(
		'type'			=> 'select',
		'settings'		=> 'home-section-shop-select-category',
		'description'	=> __( 'Select category', 'andy' ),
		'section'		=> 'section-shop',
		'default'		=> '',
		'priority'		=> 11,
		'multiple'		=> 1,
		'choices'		=> Kirki_Helper::get_terms( array( 'taxonomy' => 'product_cat' ) ),
	));

}
```

**Comment by dameer** [comment]
Holy guacamole! That's something I didn't think of as an option. You saved my day mate, thanks! However, I believe that Kirki_Helper::get_post_types() method should work around it.

**Comment by aristath** [comment]
> I believe that Kirki_Helper::get_post_types() method should work around it.

No way to do that.
A post-type is not accessible before it's registered.
So if a custom post-type is added on `init` and the controls are added before that, then Kirki won't have access to them. 
Wrapping the `add_field` method in a function and adding it on `init` with a high priority is the recommended method (thanks @enginne for your help).
Most plugins register their custom post-types with a priority `10` so `12` will work in 99% of the cases. The only change I would make to that code is change `12` to `999` just to be on the safe side - in case a plugin adds a post type with a relatively high priority.
