### ISSUE TITLE
Several fields not working with WordPress 4.9 beta 2

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#1587]
### Issue description:
All kirki fields – except `checkbox`, `code`, `dropdown-pages`, `image`, `repeater` and `sortable` aren't working in WP 4.9 beta 2

### Version used:
v3.0.11

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Yes, I did.

### Using theme_mods or options?
`theme_mods`

### Code to reproduce the issue (config + field(s))
Here's the theme used: [_s-master.zip](https://github.com/aristath/kirki/files/1388979/_s-master.zip)

I have simply used your own `_s` theme with the default examples from the docs.

**Comment by aristath** [comment]
yes, WP4.9 changed the script for colorpickers, I'll have to refactor the color-alpha script.
I'll have it ready before 4.9 is released :)

**Comment by rinkuyadav999** [comment]
@aristath is it not possible to work kirki with both 4.8 and 4.9 ?

**Comment by aristath** [comment]
Yes, it's possible.
But I'm still working on this one, it's a work in progress.
As mentioned above it will be ready before WP 4.9 is released.

**Comment by aristath** [comment]
I just pushed a fix for this in the develop branch.
Can you guys please help test this?

**Comment by pagelab** [comment]
@aristath Both the `multicolor` and `typography` fields aren't loading yet – but all the others are loading fine.

Here's the error triggered in console for `multicolor`:

![kirki-multicolor-error](https://user-images.githubusercontent.com/1451087/32145051-6eaef462-bca9-11e7-97c2-550663f92c70.png)

And the error triggered by the `typography` field:

![kirki-typography-error](https://user-images.githubusercontent.com/1451087/32145054-7997ae46-bca9-11e7-812e-922438907b67.png)

Tested with WP latest beta (4.9-beta4-42036)

**Comment by aristath** [comment]
@pagelab thanks for testing this!
Fixed the multicolor control, moving on to typography now 👍

**Comment by aristath** [comment]
Tweaked the typography & background controls too but didn't have any time to test these things properly.
I'll have to run some detailed tests the following days for `color`, `background`, `multicolor` & `typography` controls in both WP 4.8.2 & 4.9 to make sure it works as expected for all versions.

**Comment by rinkuyadav999** [comment]
@aristath 

There is some issue with field type editor. Click on 'Open Editor' button and then close it. it does not close editor.

Note sure about message: Deprecated TinyMCE API call: <target>.onChange.add(..)

**Comment by rinkuyadav999** [comment]
@aristath Actually stop working on 4.8.3

**Comment by aristath** [comment]
@rinkuyadav999 the editor issue was fixed in #1596, will be included in 3.0.12 as soon as I finish testing everything with WP 4.9 & WP 4.8.3 to make sure other controls are ok too.

**Comment by JPDubois** [comment]
@aristath Did you update wp-color-alpha.js script -> https://github.com/kallookoo/wp-color-picker-alpha. They updated to 2.0 (like 20 hours ago..) for WP 4.9 compatibility.

I have tested Kirki last Dev build on 4.9beta4 and everything is fine (we have more than 100 different Kirki fields).
I have tested Kirki 3.0.11 & last Dev build on 4.8.X and everything is fine (we have more than 100 different Kirki fields.).

**Comment by aristath** [comment]
@JPDubois Nice! I hadn't seen they updated it
But I got tired of waiting for them to fix it so I fixed it in Kirki 5 days ago.
I don't know yet which version is better - mine or theirs, so I'll experiment with both and see which one to keep. 👍

**Comment by aristath** [comment]
Ended up using the script from https://github.com/kallookoo/wp-color-picker-alpha because I had to also support hue-only colorpickers.

Everything works fine now in WP 4.9 so closing this one.
