### ISSUE TITLE
[feature] Add an Link Field Type (URL field)

### ISSUE THREAD

**Issue by maxviewup** [themeum/kirki#1588]
### Feature description:
Kirki have the url field, but it only sanitize the input. Would be great to have an dedicated URL picker (maybe use the same on WYSIWYG - preview site pages and posts, etc).

### Example of use
When typing 'dogs' the URL picker would:
 - suggest posts/pages about dogs (title or content)
 - Suggest categories/archives about dogs

**Comment by AdsonCicilioti** [comment]
Make very very sense!!!
I was going to open an issue, but I saw that there was.
What do you need to implement this, @aristath ?

**Comment by aristath** [comment]
> What do you need to implement this, @aristath ?

A day off... 😂
