### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Kirki_Fonts' not found in ..... functions.php

### ISSUE THREAD

**Issue by jasondevine** [themeum/kirki#1589]
### Issue description:
When using the method from [kirki-helpers](https://github.com/aristath/kirki-helpers) to provide stylesheet fallbacks if using `output` and Kirki is not installed as a plugin, the renamed [class-my-theme-name](https://github.com/aristath/kirki-helpers/blob/master/class-my-theme-kirki.php) will proxy the `Kirki` class as expected but for some reason, has no bearing on `Kirki_Fonts`, and the error is thrown. 

### Version used:
3.0.11

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```php
amplifier_Kirki::add_field( 'amplifier', array(
    'type'        => 'typography',
    'settings'     => 'amplifier_headline_font',
    'label'       => __( 'Headline text', 'amplifierTheme' ),
    'description' => __( 'This is the typeface for post headlines', 'amplifierTheme' ),
    'section'     => 'core_typography',
    'choices'     => Kirki_Fonts::get_font_choices(),
    'default'     => array(
        'font-family'    => 'Montserrat',
        'variant'        => 'bold',
        'letter-spacing' => '-0.05em',
        'subsets'        => array( 'latin-ext' ),
        'color'          => '#222',
        'text-transform' => 'none',
        'text-align'     => 'left'
      ),
    'output'      => array(
        array(
          'element' => '.entry-link,.widgettitle',
        ),
      ),
    'priority'    => 10,
) );

**Comment by jasondevine** [comment]
Is there anything else you need from me with respect to my code to see what the problem is here? I'd like to be able to keep using Kirki but I need some help in overcoming this one because I don't understand the PHP well enough to come up with my own fix. Thanks for your time.

**Comment by aristath** [comment]
Instead of this:
```php
'choices'     => Kirki_Fonts::get_font_choices(),
```
Use this:
```php
'choices'     => ( class_exists( 'Kirki_Fonts' ) ) ? Kirki_Fonts::get_font_choices() : array(),
```
That will check if the class exists before using it.

**Comment by jasondevine** [comment]
Thank you very much, that fixed it for me - much appreciated.
