### ISSUE TITLE
Problem embedding Kirki in my theme

### ISSUE THREAD

**Issue by NickHeurter** [themeum/kirki#159]
I’m trying to embed it with my theme but I’ve got an error. I’ve done the following thinks:
1. I add the following line to my function.php: 
   
   <code> include_once( dirname( **FILE** ) . '/kirki/kirki.php' ); </code>
2. And the following line to my function.php file within the Configuration of Kirki:
   
   <code> 'url_path'     => get_template_directory_uri() . '/inc/kirki/‘, </code>
3. The plugin is upload in:
   
   <code> /wp-content/themes/klantnaam/inc/kirki </code>

But I seems to be doing something wrong since:
1. But the stylesheet customizer.css is loaded like:

<code>< link rel="stylesheet" id="kirki-customizer-css-css" href="http://www.website.nl/wp-content/plugins/home/nheurter/domains/website.nl/public_html/wp-content/themes/theme-name/inc/kirki//assets/css/customizer.css?ver=0.5" type="text/css" media="all” ></code>
1. The customizer.js like:

<code>< script type="text/javascript" src="http://www.website.nl/wp-content/plugins/home/nheurter/domains/website.nl/public_html/wp-content/themes/theme-name/inc/kirki/assets/js/customizer.js?ver=4.1.1" ></script>
1. And the serialize.js like:

<code>< script type="text/javascript" src="http://www.website.nl/wp-content/plugins/home/nheurter/domains/website.nl/public_html/wp-content/themes/theme-name/inc/kirki/assets/js/serialize.js?ver=4.1.1" ></script></code>

Even though the kiri-style.css is loaded perfectly like:

<code>< link rel="stylesheet" id="kirki-styles-css" href="http://www.website.nl/wp-content/themes/theme-name/inc/kirki/assets/css/kirki-styles.css" type="text/css" media="all” ></code>

Any thought on what I'm doing wrong?

**Comment by replynone** [comment]
Have a look at this issue:
https://github.com/aristath/kirki/issues/148

perhaps it will help

**Comment by aristath** [comment]
This has been fixed in the develop branch, please use that instead.
We'll update the version on wordpress.org soon to include these fixes. :)

**Comment by NickHeurter** [comment]
Thanks a lot guys!
