### ISSUE TITLE
Register dynamic settings per page or post

### ISSUE THREAD

**Issue by mahdiyazdani** [themeum/kirki#1590]
It makes it easy to add options such as "change background color" for themes. Such options will be stored in the database (in wp_options) with a name of your choice. You can then retrieve your value with get_option( 'field-name' );.

I'm wondering though if this also works on single posts or pages? So, is it possible to set different custom background color for each page with this tool and retrieve values using get_post_meta($id_of_the_current_post, 'field-name');?

**Comment by Alanimus** [comment]
You can do this by having the user select the post and using a default.

```
Mytheme_Kirki::add_field( 'mytheme_id', array(
		'type'     => 'select',
		'settings' => 'my_custom_templates',
		'label'    => esc_attr__( 'Templates', 'mytheme' ),
		'section'  => 'my_templates',
		'default'  => '73', // Manually set a default id
		'priority' => 10,
		'choices'  => Kirki_Helper::get_posts( array( 'posts_per_page' =>5, 'post_type' => 'my_layout' )),
	) );

```

You can also try the plugin ["wp-customize-posts"](https://github.com/xwp/wp-customize-posts)

**Comment by mahdiyazdani** [comment]
@Alanimus That is NOT what I asked although thanks for your reply.

**Comment by DannyCooper** [comment]
Hi @mahdiyazdani,

Would this not be more suited to a control on the editor level such as a metabox?

**Comment by DannyCooper** [comment]
Duplicate of https://github.com/aristath/kirki/issues/1604
