### ISSUE TITLE
active_callback arguments don't work on customizer page load

### ISSUE THREAD

**Issue by kodeoagency** [themeum/kirki#1591]
### Issue description:

When customizer page loads, required fields display all the time no matter what is selected in the parent setting. After re-select parent field or clicking RESET, it works.
But after (save &) refresh customizer page, it doesn't work again and required fields display again

The issue was already reported in [#125](https://github.com/aristath/kirki/issues/125).

### Version used:
3.0.11

**Comment by aristath** [comment]
That was an issue 2 years ago and has since been fixed.
It would be useful to see the code you're using, otherwise there's not much I can do here

**Comment by kodeoagency** [comment]
Hi.
I have recognized that the issue has been fixed, but I'm facing the exact same problem here.

This is our code:

```
'settings' => [
	'checkbox_control' => [
		'type' => 'checkbox',
		'default' => 0,
	],
	'color' => [
		'label' => 'Color',
		'type' => 'color',
		'default' => '#000',
		'output' => [['element' => 'h2','property' => 'color']],
		'active_callback' => [['setting' => 'checkbox_control','operator' => '==','value' => 1]],
	],
]
```

**Comment by aristath** [comment]
Please post the code for your config as well

**Comment by kodeoagency** [comment]
Hi.
We found out that the problem only appears in our custom installation, but not in the standard configuration.
We will further analyze the issue and get back to you.

**Comment by kodeoagency** [comment]
Hi.
I am sorry for the false alarm. The bug was happen due to our custom code.

**Comment by aristath** [comment]
Thanks! I couldn't wrap my head around this one 👍
