### ISSUE TITLE
PHP error in latest version 

### ISSUE THREAD

**Issue by webangon** [themeum/kirki#1598]
I love the latest version , It has  a lot improvement but this php error is shown .

> :  Warning:
:  A non-numeric value encountered in 
<b>C:\xampp\htdocs\plugins\wp-content\plugins\kirki\core\class-kirki-helper.php</b>

![capture](https://user-images.githubusercontent.com/7946657/32283636-27cb804e-bf4f-11e7-8a02-016eab4d8fd7.PNG)

**Comment by aristath** [comment]
> A non-numeric value encountered in C:\xampp\htdocs\plugins\wp-content\plugins\kirki\core\class-kirki-helper.php

Does it say which line in that file?

Could you please post the code you're using for your fields?

**Comment by webangon** [comment]
I just include the example.php file that comes from this repo. This happens for both github repo and wordpress.org plugin also. I did not create any options

**Comment by aristath** [comment]
Fixed just now in the last commit.
Thanks for reporting this, I would have missed it 👍

**Comment by wawansnw1007** [comment]
Dear all

Please help me.

when installing on localhost there is an error in this section kirki\core\class-kirki-helper.php on line 286

Thanks
