### ISSUE TITLE
Reset not working

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1600]
### Issue description:

Reset not working. Can you check it?

http://take.ms/FBJzC

### Version used:
Latest stable (on wp.org)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
$priority = 0;
Kirki::add_field( 'ramsay_customize', array(
	'type' => 'switch',
	'settings' => 'footer_subscribe',
	'section' => 'section_footer_subscribe',
	'label' => esc_html__( 'Show Subscribe', 'ramsay' ),
	'description' => esc_html__( 'Switch "Show" if you want to show subscribe section', 'ramsay' ),
	'priority' => $priority++,
	'transport' => 'auto',
	'choices' => array(
		'on' => esc_html__( 'Show', 'ramsay' ),
		'off' => esc_html__( 'Hide', 'ramsay' ) 
	),
	'default' => '0',
) );
Kirki::add_field( 'ramsay_customize', array(
	'type' => 'image',
	'settings' => 'subscribe_background',
	'section' => 'section_footer_subscribe',
	'label' => esc_html__( 'Subscribe Background', 'ramsay' ),
	'description' => esc_html__( 'Select background for subscribe section', 'ramsay' ),
	'priority' => $priority++,
	'transport' => 'auto',
	'choices' => array(
		'save_as' => 'array'
	),
	'default' => '',
	'active_callback' => array(
		array(
			'setting' => 'footer_subscribe',
			'operator' => '==',
			'value' => '1' 
		) 
	) 
) );
```

**Comment by aristath** [comment]
Can you please try puling the latest changes from this repository and check if this has been fixed there?
I'm unable to replicate the issue using the github version so this has probably been already fixed.

**Comment by aristath** [comment]
The reset module has been removed in version 3.0.12.
WordPress 4.9 adds changesets and many improvements, and a reset feature is planned in the future for WordPress-Core so it makes no sense to keep a buggy implementation in Kirki.

**Comment by vlthemes** [comment]
Good news. Thx

**Comment by minimaluminium** [comment]
Is there any way to simulate the reset feature even without reset button for development purpose?
