### ISSUE TITLE
Option type - fontawesome , does not work for repeater field.

### ISSUE THREAD

**Issue by webangon** [themeum/kirki#1601]
In latest version option type fontawesome does not work in repeater field though it work elsewhere. 
```
Kirki::add_field( 'gangster_demo', array(
	'type'        => 'repeater',
	'label'       => esc_attr__( 'Social Buttons', 'chup' ),
	'section'     => 'left_section',
	'row_label' => array(
		'type' => 'field',
		'value' => esc_attr__('meta', 'chup' ),
		'field' => 'social_icon',
	),
	'settings'    => 'socials',
	'fields' => array(
		'social_icon' => array(
			'type'        => 'fontawesome',
			'label'       => esc_attr__( 'Social vendor', 'chup' ),
		),
		'social_url' => array(
			'type'        => 'text',
			'label'       => esc_attr__( 'Social url', 'chup' ),
		)		
	),	
) );
```
![capture](https://user-images.githubusercontent.com/7946657/32307601-7c8a26d8-bfab-11e7-821c-0cd1182fd25d.PNG)

But this works fine 
```
Kirki::add_field( 'gangster_demo', array(
	'type'        => 'fontawesome',
	'settings'    => 'fontawesome_setting',
	'label'       => esc_attr__( 'Font Awesome Control', 'kirki' ),
	'description' => esc_attr__( 'Description Here.', 'kirki' ),
	'section'     => 'left_section',
	'default'     => 'bath',
) );
```

**Comment by ArekZw** [comment]
Repeater not support font awesome now. If I understand correctly, repeater will support new fields in Kirki 3.1
Look #1513 #1108 #652

**Comment by aristath** [comment]
@webangon exactly what @ArekZw said above.
This is a feature request that will be implemented in 3.1 👍

**Comment by ashikur11** [comment]
Hi there any news for fontawesome icon support in repeater?

**Comment by pawangurung66** [comment]
Yes, Even I Have been waiting for its and now its 2020 does it supports font-awesome/dash icons in a repeater? If not how can I make one? Are there any ways to do so?
![font](https://user-images.githubusercontent.com/41340313/80446666-33979480-8937-11ea-97ff-fc9b5b95b668.jpg)
Have a look at this screen shot. They are using icons inside repeater. How are they doing that?
