### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by lamiastartup** [themeum/kirki#1602]
Hi @aristath 

it seems that the latest version 3.0.11 does not perform custom translation implementation.

In my specific case I'm trying to translate "No File Selected" for the image field. How can I translate these fields?

I reading this, but not work :(

https://aristath.github.io/kirki/docs/advanced/integration.html

**Comment by aristath** [comment]
@lamiastartup the translation filter was removed in v3.0 and now when kirki is embedded in a theme, it uses the theme's native translations file and all strings can be translated (or changed) from those .mo files.

Have you tried translation using something like poedit?

-------------------------

EDIT: The documentation site had not been updated, I removed that info from there now.

**Comment by lamiastartup** [comment]
Hi @aristath I have also tried it so well. I want to add the strings to my .po file, I translate them into the .mo file but in spite of that the translations are ignored

**Comment by aristath** [comment]
There was indeed a bug in the translations and it wasn't possible to override them from a theme when Kirki was embedded.
Fixed in https://github.com/aristath/kirki/commit/a3f86d64b4f28e86d13231ab04c50e71a6d86c1f so if you use the develop branch this will work fine now. Tested it with 3 themes and 2 languages, works.
This fix will be included in v3.0.12 which will be released in a few days.

**Comment by lamiastartup** [comment]
Thank you @aristath 

I confirm that the development version works perfectly.

Thanks for making Kirki big <3

Last question: Do you think that you will integrate a Responsive Control in the future? It would be epic

Thanks for all,
Davide

**Comment by aristath** [comment]
Glad it works for you now 👍 

> Last question: Do you think that you will integrate a Responsive Control in the future? It would be epic

Could you please elaborate? What would such a control do? I'm sorry but I don't understand what a "responsive control" is 🤔

**Comment by lamiastartup** [comment]
Hi @aristath, a function like this :)

![wpbf-responsive-font-sizes](https://user-images.githubusercontent.com/31349279/32410434-11fe4256-c1c0-11e7-87bb-25ba8e67c948.gif)

**Comment by aristath** [comment]
So a control that allows you to set the breakpoints for mobile/tablet?

**Comment by lamiastartup** [comment]
Yes, sound good :)

**Comment by aristath** [comment]
If you're talking about controls that allow you to preview the different sizes, that's already available in WordPress....
Bottom of the controls panel:
<img width="298" alt="screenshot at nov 05 01-39-37" src="https://user-images.githubusercontent.com/588688/32410506-43ea5868-c1ca-11e7-83b9-eca7fb2bdbb0.png">
What confuses me in your screencast is the 28px/24px/20px. What is that for?

**Comment by lamiastartup** [comment]
It needs to set a different size for each type of device,

So not just the preview of the site.

**Comment by aristath** [comment]
I see.... Can you please create a new ticket for that with as many details as possible so that I can mark it as a feature request for a future version? If it gets implemented it's not going to be in v3.0.12 anyway, no time for that in this version 👍

**Comment by lamiastartup** [comment]
Yes, thanks @aristath  :)
