### ISSUE TITLE
add a "spacer" control

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#1605]
The goal is something like this:
<img width="321" alt="screenshot at nov 05 14-16-19" src="https://user-images.githubusercontent.com/588688/32414625-fa1967a0-c233-11e7-8909-61d8fcac516f.png">

**Comment by LuisAlejandre** [comment]
That would be a great addition! (though I doubt "spacer" is the best name for this new control)

**Comment by aristath** [comment]
I agree about the name, I just couldn't think of something at the time I created the ticket and I just entered it like that 'cause if I don't write down ideas like that I forget them. 😉 
Any ideas about the name are more than welcomed.

**Comment by LuisAlejandre** [comment]
Yeah, that´s what I guessed because of the quotes you used to wrap the name. I´ll give it a thought but... Damn, it´s not so straightforward!

**Comment by LuisAlejandre** [comment]
Maybe just "spacing" control?

The name "spacer" makes one think about some kind of separator element, but "spacing" seems to be more like what margins and paddings are about.

**Comment by aristath** [comment]
> Maybe just "spacing" control?

That's what I would have called it, but unfortunately there's already a "spacing" control in kirki... https://aristath.github.io/kirki/docs/controls/spacing.html
That's why I still haven't found a good name for it, the only thing that would be apt for this control is already taken!

**Comment by LuisAlejandre** [comment]
Gee, I wasn´t aware of the current spacing control! I´ve never used it.

**Comment by ArekZw** [comment]
@aristath - maybe "Box model control"? It's very suggestive name.

https://www.w3schools.com/css/css_boxmodel.asp

https://www.google.pl/search?biw=1920&bih=1036&tbm=isch&sa=1&ei=V1QEWqLQE8L7UozvrLAO&q=Box+model+control+CSS&oq=Box+model+control+CSS&gs_l=psy-ab.4...1078.1394.0.1507.4.4.0.0.0.0.111.215.0j2.2.0....0...1.1.64.psy-ab..2.0.0....0.rLTM07ooJe0

**Comment by DannyCooper** [comment]
Is this it? https://wplemon.com/downloads/kirki-box-model/

**Comment by aristath** [comment]
Yes! I knew there was a ticket somewhere.... 😂
Closing this one since it was already done
