### ISSUE TITLE
Header and footer background

### ISSUE THREAD

**Issue by yupii1986** [themeum/kirki#1607]
Hello,
Can you help me please? I try to add footer and header background changer ex:http://prntscr.com/h6ptd5

I want option to change background, but i dont know how,
I find only for text how to change.
Can you help me please?

Thank you

**Comment by Alanimus** [comment]
I don't know what theme you are using, so can't really help with exact CSS property. Just use Chrome dev tools to inspect and see what CSS class it uses. It looks like the menu bar, so you'd make a control do something like:

```
Kirki::add_field( 'kirki_demo', array(
	'type'        => 'color',
	'settings'    => 'color_setting_hex',
	'label'       => __( 'Color Control (hex-only)', 'kirki' ),
	'description' => esc_attr__( 'This is a color control - without alpha channel.', 'kirki' ),
	'section'     => 'color_section',
	'default'     => '#0088CC',
'output'    => array (
              array(
		'element'  => '.header-nav',
		'property' => 'background-color',
	),
)
 );
```

**Comment by aristath** [comment]
@yupii1986 I don't see how the question has anything to do with Kirki... At least not with the limited information provided so far.
If you want to change the CSS for your theme then you can do it using the WordPress Core customizer and the browser's developer tools mentioned above.
You can read this to figure out the element and what you need to change: https://developers.google.com/web/tools/chrome-devtools/css/reference

After that you can use the Custom CSS field in the customizer to add your custom CSS rules.
