### ISSUE TITLE
Missing remove_panel, remove_section, remove_field

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1609]
### Issue description:
Kirki::add_panel adds a panel but Kirki::remove_panel does not exist in class-kirki.php
Same for Section and Filed.

Suppose a theme added a Fields using Kirki::add_field but Kirki does not have a method to remove added filed. Same for section and panel.

### Version used:
Latest from w.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Looking something like:

Kirki::remove_field( 'mysettings' );

**Comment by rinkuyadav999** [comment]
@aristath They should be in Kirki or No, dev-feedback needed :)

**Comment by rinkuyadav999** [comment]
Closing due to:
$wp_customize->remove_control( 'setting-name' );

**Comment by aristath** [comment]
Reopening.
Still thinking about it... (sorry for not getting back to you sooner on this one).

**Comment by aristath** [comment]
Added `Kirki::remove_panel()`, `Kirki::remove_section()` and `Kirki::remove_control()`.
Note that it's `remove_control` and not `remove_field` because a field in Kirki is the sum of a control + its setting. The function removes the control but not the setting.

**Comment by rinkuyadav999** [comment]
@aristath Kirki calls 'field', field = setting + control.
So to add it 'add_field' and to remove 'remove_field'
I think 'field' will better than 'control'.
