### ISSUE TITLE
Customizer missing since last update (v3.0.12)

### ISSUE THREAD

**Issue by codebygina** [themeum/kirki#1612]
### Issue description:
Since the last update, Customizer is missing. **I am not sure if this is related** but in the console, there's the  error: `Uncaught ReferenceError: kirkiAllFonts is not defined`

![screenshot](https://i.imgur.com/5Uq4IHV.png)

### Version used:
3.0.12

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Customizer went perfectly fine with v3.0.11, I've developed the entire theme based on it. If I revert back all goes well.

**Comment by aristath** [comment]
I can't replicate this one...
Can you please try resetting your browser's cache?
Which WP version are you using?

**Comment by brnogz** [comment]
my situation is same. i use  wordpress 4.8.3 and it is same on different browsers and incognito mod.

**Comment by aristath** [comment]
I'm still unable to replicate.
Does this happen with a specific theme?
Have you tried disabling other plugins to see if it's a conflict of some sort?
If you update your site to WP 4.9 does this still happen?

**Comment by aristath** [comment]
If one of you can tell me what to do to replicate this issue I'll be able to debug it...
If not then perhaps someone could send me some administration and FTP credentials on a site that has this issue so that I may debug it there.
Unfortunately without replicating the issue there's not much I can do.

**Comment by codebygina** [comment]
I'd be happy to @aristath , please, let me know at which e-mail address can I send you the theme? So, to give you a bit info, this is a theme I personally developed under 3.0.11, so I know for sure it worked perfectly until 3.0.12.

**Comment by aristath** [comment]
@wowthemesnet thank for sending over your theme, I was able to replicate the issue with it.
Pushed a fix and now releasing version 3.0.13 with that bugfix. 👍

**Comment by codebygina** [comment]
Aristeides, bravo, it works!

I am so happy to be able to release the theme now. I very much appreciate your work and thank you so much. Have a great day! 

 

Best Regards,

Sal

 <http://www.wowthemes.net/> www.wowthemes.net

 

De la: Aristeides Stathopoulos [mailto:notifications@github.com] 
Trimis: Thursday, November 9, 2017 2:13 AM
Către: aristath/kirki <kirki@noreply.github.com>
Cc: WowThemesNet <wowthemesnet@gmail.com>; Mention <mention@noreply.github.com>
Subiect: Re: [aristath/kirki] Customizer missing since last update (v3.0.12) (#1612)

 

@wowthemesnet <https://github.com/wowthemesnet>  thank for sending over your theme, I was able to replicate the issue with it.
Pushed a fix and now releasing version 3.0.13 with that bugfix. 👍

**Comment by aristath** [comment]
I’m glad I could help :)

I’m pushing the 3.0.13 version on wordpress.org now, it should be online in a few minutes.

Good luck with your theme! I didn’t have time to take a good look at it because it’s 2am where I live right now, but I spent a couple of minutes with it and it looks pretty neat and organised. 

Have a great day!

**Comment by codebygina** [comment]
I'm on the same timezone being from Romania, so I understand the effort:) Once again, thank you so much!

**Comment by pasqualevitiello** [comment]
Same issue after updating to WordPress 4.9 and Kirki to 3.0.15.

**Comment by codebygina** [comment]
@pasqualevitiello , I think @aristath is aware, I've tested the latest 3.0.16-dev and the issue is solved, so it will probably follow an update soon on .org.
