### ISSUE TITLE
Theme Check Warnings

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1613]
### Issue description:
Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are themetxtxdmn, kirki, Kirki
WARNING: Found a translation function that is missing a text-domain. Function esc_attr__, with the arguments 'Textarea Control'
WARNING: Found a translation function that is missing a text-domain. Function esc_attr__, with the arguments 'Text Control'
WARNING: Found a translation function that is missing a text-domain. Function esc_attr__, with the arguments 'Description'
WARNING: Found a translation function that is missing a text-domain. Function esc_attr__, with the arguments 'Custom input Control.'

### Version used:
Latest from w.org

### Using theme_mods or options?
theme_mod

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/pull/1615 👍
