### ISSUE TITLE
Typography control - font-weight 400 output 'regular' insted '400' or 'normal'

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#1619]
### Issue description:
Typography control - font-weight 400 output 'regular' insted '400' or 'normal'. 'regular' is not valid property of font-weight and doesn't work.

https://www.w3schools.com/code/tryit.asp?filename=FLC5F10CD9P2

### Version used:
3.0.13 and 3.0.10

**Comment by aristath** [comment]
Fixed in the develop branch, can you please confirm that the fix works ok for you?

**Comment by ArekZw** [comment]
Aghhh... it was my mistake, I use 'variant' instead 'font-weight'. Commit is not necessary. I'm sorry for the trouble and thank you for your answer.

**Comment by aristath** [comment]
Ah ok, that makes sense.
In that case I'm reverting the commit 👍
