### ISSUE TITLE
wp4.9 customiser  not loading

### ISSUE THREAD

**Issue by unetics** [themeum/kirki#1621]
### Issue description:
the customiser wont load might just be xdebug breaking the load but i thought you would like to see the warning

### Version used:
Version 3.0.13
### Debug Code 
`<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Invalid argument supplied for foreach() in /wp-content/plugins/kirki/controls/php/class-kirki-control-typography.php on line <i>53</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.2449</td><td bgcolor='#eeeeec' align='right'>411296</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-admin/customize.php' bgcolor='#eeeeec'>.../customize.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>3.5624</td><td bgcolor='#eeeeec' align='right'>99742824</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-admin/customize.php' bgcolor='#eeeeec'>.../customize.php<b>:</b>210</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>3.5624</td><td bgcolor='#eeeeec' align='right'>99743200</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-includes/plugin.php' bgcolor='#eeeeec'>.../plugin.php<b>:</b>453</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>3.5624</td><td bgcolor='#eeeeec' align='right'>99743200</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>323</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>3.6184</td><td bgcolor='#eeeeec' align='right'>100468800</td><td bgcolor='#eeeeec'>WP_Customize_Manager->customize_pane_settings(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>298</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.7125</td><td bgcolor='#eeeeec' align='right'>100796904</td><td bgcolor='#eeeeec'>WP_Customize_Control->json(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-includes/class-wp-customize-manager.php' bgcolor='#eeeeec'>.../class-wp-customize-manager.php<b>:</b>3680</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.7125</td><td bgcolor='#eeeeec' align='right'>100796904</td><td bgcolor='#eeeeec'>Kirki_Control_Typography->to_json(  )</td><td title='/Users/mitchellbray/Sites/prime_git/wp-includes/class-wp-customize-control.php' bgcolor='#eeeeec'>.../class-wp-customize-control.php<b>:</b>350</td></tr>
</table></font>
<br />`

**Comment by aristath** [comment]
fixed
