### ISSUE TITLE
Can't define code field priority

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#1622]
### Issue description:
The `code` field does not obey the `priority` setting and shifts position randomly on reload.

![screen-recording-2017-11-10-19-49-58](https://user-images.githubusercontent.com/1451087/32680152-7f59735e-c650-11e7-8915-52c01468fac4.gif)

Inspecting the code, it's possible to see an unused second instance of the `code` field.

![screen-recording-2017-11-10-20-41-40](https://user-images.githubusercontent.com/1451087/32681676-c08978a4-c657-11e7-8d37-2da888667150.gif)

### Version used:
3.0.13

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Yes, I did.

### Using theme_mods or options?
`theme_mods`

### Code to reproduce the issue (config + field(s))
```php
/**
 * Add the theme configuration
 */
_s_Kirki::add_config( '_s_theme', array(
	'option_type' => 'theme_mod',
	'capability'  => 'edit_theme_options',
) );

/**
 * Add the kirki section
 */
_s_Kirki::add_section( 'kirki', array(
	'title'      => esc_attr__( 'Kirki', '_s' ),
	'priority'   => 2,
	'capability' => 'edit_theme_options',
) );

Kirki::add_field( '_s_theme', array(
	'type'        => 'code',
	'settings'    => 'code_demo',
	'label'       => __( 'Code Control', '_s' ),
	'section'     => 'kirki',
	'default'     => 'body { background: #fff; }',
	'priority'    => 10,
	'choices'     => array(
		'language' => 'css',
		'theme'    => 'monokai',
		'height'   => 250,
	),
) );

Kirki::add_field( '_s_theme', array(
	'type'        => 'color',
	'settings'    => 'my_setting_b',
	'label'       => __( 'This is the label', '_s' ),
	'section'     => 'kirki',
	'default'     => '#0088CC',
	'priority'    => 20,
	'choices'     => array(
		'alpha' => true,
	),
) );

Kirki::add_field( '_s_theme', array(
	'type'        => 'checkbox',
	'settings'    => 'my_setting_a',
	'label'       => __( 'This is the label', '_s' ),
	'section'     => 'kirki',
	'default'     => '1',
	'priority'    => 30,
) );
```

**Comment by aristath** [comment]
FYI the reason I'm not responding to this one is not because I'm ignoring it, just trying to figure things out. 😄

**Comment by mapsteps** [comment]
Having the same issue. Also is it possible to change the height of the code control?

**Comment by pagelab** [comment]
Thanks for fixing this, @aristath 👍
