### ISSUE TITLE
SOLUTION FOR implode() Error

### ISSUE THREAD

**Issue by wasabii2017** [themeum/kirki#1626]
### Issue description:
Error:
Warning: implode(): Invalid arguments passed in
 .../wp-content/plugins/kirki/modules/webfonts/class-kirki-modules-webfonts-link.php on line 146

### Version used:
 3.0.14
### SOLUTION:#####

Please declare the array like this in the "class-kirki-modules-webfonts-link.php"

130:	// Are we force-loading all subsets?
131:        $this->subsets =array();

**Comment by aristath** [comment]
@wasabii2017 I just pushed a commit for this, could you please check if that fixes your issue?
If it does I'll push an update real quick

**Comment by sducatt** [comment]
Had the exact same issue today and was able to fix it with this-- Thanks !

**Comment by aristath** [comment]
Fix verified by another user, released v3.0.15 what fixes this.
