### ISSUE TITLE
help with kirki ( and DARINA THEME)

### ISSUE THREAD

**Issue by Crspost** [themeum/kirki#1628]
### Issue description:
Warning: implode(): Invalid arguments passed in /home/circolo0/public_html/wp-content/plugins/kirki/modules/webfonts/class-kirki-modules-webfonts-link.php on line 146

### Version used:
last stable

### Using theme_mods or options?
DARINA theme

**Comment by aristath** [comment]
Can you please try editing that file and make this change?
https://github.com/aristath/kirki/commit/5bfe66fa4277015a9cb87b0b9eca6fe2494b6de4

**Comment by aristath** [comment]
Fix verified by another user, released v3.0.15 which fixes this.

**Comment by Crspost** [comment]
thank you very much, you saved me :)


2017-11-12 10:39 GMT+01:00 Aristeides Stathopoulos <notifications@github.com
