### ISSUE TITLE
Allow setting an option name in the configuration so that options are parts of an array

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#163]
See https://github.com/aristath/kirki/issues/104#issuecomment-89425820 for details

**Comment by vaclavgreif** [comment]
Any estimate on this one? This would really help to be able to switch from Redux to Kirki...

**Comment by vaclavgreif** [comment]
Hmmm, I can see in the code work on this has been done already, and it actually works once I add:

``` php
    'options_type'  => 'option',
    'option_name'  => 'tut',
```

Any downsides using this?

**Comment by aristath** [comment]
Nope, no downside. :)

using `'options_type' => 'option'` will force kirki to use options instead of theme mods.
If you don't set `'option_name'`, then each option will be saved separately in the options table, and if you use the `option_name` argument as well then the settings will be serialized.

The implementation looks fine to me so far but it hasn't been tested by a lot of people, that's why it's not officially documented and supported. We just need some more testing done on it... 

If you find any bugs then please do let us know!!

Keep in mind that we recommend using the `kirki_get_option()` function to get the values of your options.

We've done a lot of work on it so it should work no matter what mode you're using. :smile:
