### ISSUE TITLE
Typography menu name showing of upload control field in control dropdown menu in document section of website 

### ISSUE THREAD

**Issue by hrthakur007** [themeum/kirki#1640]
### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by aristath** [comment]
I seriously did not understand a word from that title.

>Typography menu name showing of upload control field in control dropdown menu in document section of website

Please elaborate. explain with as many details as possible.

**Comment by aristath** [comment]
AH ok, I understood now.
Sorry, it took me a while 👍 

Fixed in the docs site, thank you for reporting this!
