### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1642]
### Issue description:
Add `text-decoration` to the array - I think that would be a great addition.

### Version used:
3.0.15

### Using theme_mods or options?
mods

### Code to reproduce the issue (config + field(s))

`Kirki::add_field( 'my_config', array(

	'type'        => 'typography',
	'settings'    => 'my_setting',
	'label'       => esc_attr__( 'Control Label', 'kirki' ),
	'section'     => 'my_section',
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'subsets'        => array( 'latin-ext' ),
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left'
		'text-decoration' => 'none'
	),
	'priority'    => 10,
	'output'      => array(
		array(
			'element' => 'body',
		),
	),
) );`

**Comment by aristath** [comment]
Done, will be included in 3.0.17
