### ISSUE TITLE
Kirki installer not working on plugins

### ISSUE THREAD

**Issue by maxviewup** [themeum/kirki#1643]
### Issue description: The Kirki installer isn't working on plugins

https://github.com/aristath/kirki/blob/master/docs/files/class-kirki-installer-section.php

The problem: The `WP_Customize_Section` isn't created when the `Kirki_Installer_Section` wants to extends it. I solved it by creating the class inside the `kirki_installer_register` function.

**Comment by maxviewup** [comment]
Another problem: Kirki is also not created at this point even with it installed.

**Comment by aristath** [comment]
Can you please check again?
I just updated that class a few minutes ago, it should be ok now.

**Comment by maxviewup** [comment]
I solved the problem on my code changing the used hooks. I will test the new code soon as possible

**Comment by medabkari** [comment]
Hello, Can you please help me By Telling Me how Did you Solve it, i mean i'm facing the same Problem Right Now .
