### ISSUE TITLE
Kirki_Styles_Frontend not found

### ISSUE THREAD

**Issue by FrankM1** [themeum/kirki#1644]
### Issue description:
Kirki_Styles_Frontend is referenced in core/dynamic-css.php but the class doesn't seem to be available. I think Kirki_Modules_CSS should be used there instead.

### Version used:
3.0.15

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
General issue

**Comment by aristath** [comment]
@FrankM1 wow, I don't know how this one was missed...

Thank you! fixed in the develop branch, will be included in 3.0.16
