### ISSUE TITLE
Conditionally show/hide controls for each device preview?

### ISSUE THREAD

**Issue by munirkamal** [themeum/kirki#1645]
### Issue description:
Not an issue but a question or feature request/suggestion.

I am working on a WordPress theme and need to allow theme users to set different values for some controls for each device (desktop, tablet, mobile). Now that Kirki yet doesn't have any option/parameter in controls to handle this, I got two ideas.

**Option 1: Conditionally Show/Hide controls**
I create 3 variants of the same control each for desktop, tablet & mobile and then conditionally show/hide the variants when user switch the device preview in the customizer. I have yet to know how to achieve that and have posted it at stack exchange too if anyone here has any solution for this please suggest.
https://wordpress.stackexchange.com/q/286268/42696?sem=2

Above will get a bit messy if I got to create variants for many controls, but maybe the only possible solution as of now?

**Option 2: Which is a Feature Request actually.**
The best way I think to achieve it is if Kirki allows device-specific output for the controls. For example, this is the control code I have for the H1 Typography.

    Kirki::add_field( 'start', array(
	'type'        => 'typography',
	'settings'    => 'h1_typography',
	'label'       => __( 'H1', 'start' ),
	'section'     => 'headings_typography',
	'transport' => 'auto',
	'default'     => array(
		'font-size'      => '48px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'text-transform' => 'none',
	),
	'output'      => array(
		array(
			'element' => 'h1',
		),
	),
    ) );

How about Kirki allow us simply making this magic happen like this (just an idea).

    Kirki::add_field( 'start', array(
	'type'        => 'typography',
	'settings'    => 'h1_typography',
	'label'       => __( 'H1', 'start' ),
	'section'     => 'headings_typography',
	'transport' => 'auto',
	'default'     => array(
		'font-size'      => '48px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'text-transform' => 'none',
	),
	'output_desktop'      => array(
		array(
			'element' => 'h1',
		),
	),
       'output_tablet'      => array(
		array(
			'element' => 'h1',
		),
	),
       'output_mobile'      => array(
		array(
			'element' => 'h1',
		),
	),
    ) );

And behind the scene, it manages to create the responsive variants for the same control and also makes it conditionally show/hide when user switch to specific device preview in the customizer. If this happens that will be really great :)

-----------

But until then could someone please guide me a solution for option 1? Or how you guys achieve this using Kirki? Is there some other better way at the moment to make it happen?

TIA,
Munir

**Comment by munirkamal** [comment]
Anyone? Still waiting for a response.

TIA

**Comment by oziriemeka** [comment]
i tink the wordpress customiser is best suited for PC device, although responsive but for best experiece Pc is the best, you could do what you are trying out with Media queries getting on value and doing alot with them.

**Comment by DannyCooper** [comment]
Duplicate of https://github.com/aristath/kirki/issues/2124
