### ISSUE TITLE
Issue in the "Switch" control and "Number" control

### ISSUE THREAD

**Issue by pubudu7** [themeum/kirki#1648]
Hi,

### Issue description:
I was using 2.3.7 version on my theme. And I updated it to 3.0.16 because of the color controls were not working with WordPress 4.9. But the Swich doesn't seem to be styled properly. Please compare the two screenshots I have provided.

- 2.3.7 Version -
<img width="298" alt="2 3 7" src="https://user-images.githubusercontent.com/33783695/32981532-b94e4c22-cc9c-11e7-9963-75530045f7ca.png">

- 3.0.15 Version -
<img width="298" alt="3 0 15" src="https://user-images.githubusercontent.com/33783695/32981550-c7119a08-cc9c-11e7-8c9f-5ddc4dcaf3ee.png">

### Version used:
I used the development branch and it did not work. Also I encountered that number control uses two plus minus buttons instead of up down arrows. And plus minus buttons also not working. They are not saving.

### Using theme_mods or options?

I am using theme mods.

Thank You.

**Comment by aristath** [comment]
Fixed the number control issue. Buttons now work.
I can confirm the issue with the switch controls as well, but that's a minor CSS issue so nothing that will break anyone's site. It can wait for the next release since 3.0.16 has to go out later tonight to fix a couple of inconsistencies with WP 4.9

**Comment by aristath** [comment]
Moved this one to the 3.0.17 milestone, I'll examine the switches css after 3.0.16 is out.

**Comment by pubudu7** [comment]
Great..! Thank you.

**Comment by DannyCooper** [comment]
Switches tested and they are displaying correctly in 3.0.43.
