### ISSUE TITLE
Typography not only setting color despite output settings

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#1649]
### Issue description:
Using the code below, I expect `a` elements to pick up the set color only. But it seems to pick up other properties as well...

    stilren_Kirki::add_field('stilren', array(
      'type' => 'typography',
      'settings' => 'default_text_font',
      'label' => _x('Main Font', 'Customizer → Typography', 'stilren'),
      'tooltip' => _x('Used for most text. The chosen font size will be used for paragrahps etc. The font size of other elements, such as the menu, are set automatically realtive to the font size set here.',     'Customizer → Typography', 'stilren'),
      'section' => 'typography',
      'default' => array(
        'font-family' => 'Source Sans Pro',
        'variant' => 'regular',
        'font-size' => '18px',
        'line-height' => '1.6em',
        'letter-spacing' => '0',
        'color' => '#060606'
      ),
      'priority' => 10,
      'output' => array(
        array(
          'element' => array(
            'body'
          ),
        ),
        array(
          'element' => array(
            'a',
            'a:hover',
            'a:active',
            'a:focus',
          ),
          'property' => 'color'
        )
      )
    ));

### Version used:
3.0.15

### Using theme_mods or options?
`theme_mods`

### Code to reproduce the issue (config + field(s))
See above

**Comment by aristath** [comment]
You need to use the `choice` argument.

```php
array(
	'element'  => array( 'a', 'a:hover', 'a:active', 'a:focus' ),
	'property' => 'color',
	'choice'   => 'color',
),
```
The reason this is necessary is to allow for maximum flexibility.
For example it allows you to do things like this as well...

```php
array(
	'element'       => array( 'a', 'a:hover', 'a:active', 'a:focus' ),
	'property'      => 'padding-top',
	'choice'        => 'line-height',
	'value_pattern' => 'calc($ / 2 - 3px)'
),
```
In the above example it sets the `padding-top` to be dependent on the `line-height` with a value of `calc($line_height / 2 - 3px)`. It may be a useless example, but you get the point of what you can do... You can remove the line-height for example and make it depend on the font-size with some fancy calculations if that's what you want. 👍

**Comment by joakimaglo** [comment]
Thanks, that worked!
