### ISSUE TITLE
Refactor code controls

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#1650]
Right now I don't particularly like the way this is implemented. It's a bit hacky and should be revisited at some point. (see https://github.com/aristath/kirki/commit/1b3fa80afc09f3277b83789d5392c1a9e7cafcf3)

**Comment by mapsteps** [comment]
Hey @aristath,

is it possible to change the height of the code field currently?

Also, which languages are allowed? Pasting a shortcode gives me an error

![746c0cf5ac5c7f69f908](https://user-images.githubusercontent.com/22119831/33024690-11eca50c-ce0c-11e7-8454-b7985d4742dd.png)

Thanks! :)

**Comment by aristath** [comment]
Hey there! Sorry for the delay here... Code fields are a bit weird at the moment. It WILL be possible, and in fact I want v3.0.18 to be focused solely on code fields. But first I have to release 3.0.17 which fixes bugs with more frequently used fields... Once that's done I'll focus all my efforts to refactoring the code fields. 👍

**Comment by mapsteps** [comment]
Awesome, thanks @aristath! :)

**Comment by DannyCooper** [comment]
@aristath Did this refactor happen?

**Comment by aristath** [comment]
The refactor did happen.
I don't think `height` was added though...
The `code` control is now a simple proxy for the wp-core control, with a couple of tweaks to make things easier to write, basically simplifying the syntax required to init a control using the customizer API and nothing more than that.
