### ISSUE TITLE
Blank Customizer and console errors on 3.0.17-dev (Syntax and Reference errors)

### ISSUE THREAD

**Issue by Alanimus** [themeum/kirki#1654]
### Issue description:

Uncaught SyntaxError: Unexpected token .
script.js:3351 

Uncaught ReferenceError: kirkiAllFonts is not defined
    at child.getFonts (script.js:3351)
    at child.renderFontSelector (script.js:3123)
    at child.initKirkiControl (script.js:3035)
    at child.ready (script.js:3023)
    at Object.<anonymous> (customize-controls.js:3630)
    at i (jquery.js:2)
    at Object.add [as done] (jquery.js:2)
    at child.initialize (customize-controls.js:3627)
    at child.api.Class (customize-base.js:94)
    at child [as constructor] (customize-base.js:35)

### Version used:
3.0.17-dev

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Not sure it's coming from my code. I am on the latest Wordpress release nightly (5.0). Haven't got that far with the trouble-shooting.

**Comment by valentinuzzi** [comment]
same issue on our installation too...

we have this output on source code of our WP admin page on customization 


<script type='text/javascript'>
--
  | /* <![CDATA[ */
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | var kirki.l10n = {"noFileSelected":"No File Selected","remove":"Remove","default":"Default","selectFile":"Select File"};
  | /* ]]> */
  | </script>
