### ISSUE TITLE
Repeater bug

### ISSUE THREAD

**Issue by azikooo777** [themeum/kirki#1656]
Hello. In the repeater. When create the type select and click on the button add new row. Javascript code return undefind error.

function initSelect return error. 
argument data, since it is not passed.
and there is no check data argument for undefined.

please fix bug.
sorry I don't know good english.

**Version 3.0.16**

`Kirki::add_field( 'theme_config_id', array(
	'type'        => 'repeater',
	'label'       => esc_attr__( 'Repeater Control', 'textdomain' ),
	'section'     => 'solid_main_page_section_two',
	'priority'    => 10,
	'row_label' => array(
		'type' => 'text',
		'value' => esc_attr__('your custom value', 'textdomain' ),
	),
	'settings'    => 'myddsetting',
	'default'     => array(
		array(
			'link_url'  => 'option-1',
		),
	),
	'fields' => array(
		'link_url' => array(
			'type'        => 'select',
			'label'       => __( 'This is the label', 'textdomain' ),
			'priority'    => 10,
			'choices'     => array(
				'option-1' => esc_attr__( 'Option 1', 'textdomain' ),
				'option-2' => esc_attr__( 'Option 2', 'textdomain' ),
				'option-3' => esc_attr__( 'Option 3', 'textdomain' ),
				'option-4' => esc_attr__( 'Option 4', 'textdomain' ),
			),
		),
	)
) );`

![default](https://user-images.githubusercontent.com/33842191/33035740-0c077b20-ce4e-11e7-9945-cd34252d985b.PNG)
![-2](https://user-images.githubusercontent.com/33842191/33035742-0c8e5550-ce4e-11e7-9199-88eaefebbadb.PNG)
![-3](https://user-images.githubusercontent.com/33842191/33035743-0ccffb22-ce4e-11e7-85a4-02f734c53fbe.PNG)
![-5](https://user-images.githubusercontent.com/33842191/33035744-0d11478a-ce4e-11e7-91f0-76fd9b1bacf6.PNG)

**Comment by aristath** [comment]
Good catch... fixed, will be included in 3.0.17
