### ISSUE TITLE
Warning when code field has no label option

### ISSUE THREAD

**Issue by steve231293** [themeum/kirki#1658]
### Issue description:

Please test code field type when it has no label option

### Version used: 3.0.16
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'theme', array(
	'type'      => 'code',
	'settings'  => 'custom_css',
	'section'   => 'custom',
	'priority'  => 1,
	'choices'   => array(
		'language' => 'css',
		'theme'    => 'monokai',
	),
	'transport' => 'postMessage',
) );

**Comment by aristath** [comment]
Fixed, will be included in 3.0.17
