### ISSUE TITLE
Error Customizer not working

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#1659]
WordPress version: 4.9
Kirki version: 3.0.16

<img width="1204" alt="screen shot 2017-11-21 at 8 55 24 pm" src="https://user-images.githubusercontent.com/1287713/33076131-69ac34b8-cefe-11e7-8f86-a143a227553c.png">

Not sure about the "Unknown key" error

The first error, is because I use "line break" among the output "element" selectors.

<img width="1203" alt="screen shot 2017-11-21 at 8 52 47 pm" src="https://user-images.githubusercontent.com/1287713/33076132-69e40cb2-cefe-11e7-8a45-14e2bad6cfd6.png">

Please help ASAP

Thanks

**Comment by aristath** [comment]
Can you please post the code you're using so that I may replicate your issue and find where the error occurs?
Without a code sample to replicate the issue I don't even know where to start looking

**Comment by daviedR** [comment]
The first bug `Invalid or unexpected token` is caused by a line break and tab character on `output` definition. The code I used look like this:

```
	'output'      => array(
		array(
			'element' => '.button, button, input[type="button"], input[type="reset"], input[type="submit"],
				.woocommerce #respond input#submit, .woocommerce a.button, .woocommerce button.button, .woocommerce input.button, .woocommerce #respond input#submit.alt, .woocommerce a.button.alt, .woocommerce button.button.alt, .woocommerce input.button.alt, .woocommerce #respond input#submit.alt.disabled, .woocommerce #respond input#submit.alt.disabled:hover, .woocommerce #respond input#submit.alt:disabled, .woocommerce #respond input#submit.alt:disabled:hover, .woocommerce #respond input#submit.alt:disabled[disabled], .woocommerce #respond input#submit.alt:disabled[disabled]:hover, .woocommerce a.button.alt.disabled, .woocommerce a.button.alt.disabled:hover, .woocommerce a.button.alt:disabled, .woocommerce a.button.alt:disabled:hover, .woocommerce a.button.alt:disabled[disabled], .woocommerce a.button.alt:disabled[disabled]:hover, .woocommerce button.button.alt.disabled, .woocommerce button.button.alt.disabled:hover, .woocommerce button.button.alt:disabled, .woocommerce button.button.alt:disabled:hover, .woocommerce button.button.alt:disabled[disabled], .woocommerce button.button.alt:disabled[disabled]:hover, .woocommerce input.button.alt.disabled, .woocommerce input.button.alt.disabled:hover, .woocommerce input.button.alt:disabled, .woocommerce input.button.alt:disabled:hover, .woocommerce input.button.alt:disabled[disabled], .woocommerce input.button.alt:disabled[disabled]:hover, .woocommerce span.onsale, .woocommerce #respond input#submit.disabled, .woocommerce #respond input#submit:disabled, .woocommerce #respond input#submit:disabled[disabled], .woocommerce a.button.disabled, .woocommerce a.button:disabled, .woocommerce a.button:disabled[disabled], .woocommerce button.button.disabled, .woocommerce button.button:disabled, .woocommerce button.button:disabled[disabled], .woocommerce input.button.disabled, .woocommerce input.button:disabled, .woocommerce input.button:disabled[disabled]',
			'property' => 'background-color',
		),
	),
```

The older version works fine with line break and tab.

About the 2nd error, turns out I used and increment integer for the key of `partial_refresh`. Something like this:

```
	'partial_refresh' => array(
		$p++ => array(
			'selector'        => '#topbar',
			'render_callback' => 'render_topbar',
			'container_inclusive' => true,
		),
	),
```

The error is from WordPress javascript, so I guess I have to change the way I named the key.

**Comment by aristath** [comment]
Can you please check using the develop branch now? Should be fixed (see [commit](https://github.com/aristath/kirki/commit/ba68084f12412d2588bdf195be4775f3cd3dc25b))

**Comment by thehung2224** [comment]
@aristath It doesn't work for me

![image](https://user-images.githubusercontent.com/5288362/33816031-b84d303a-de68-11e7-8a7a-53cdaebd8a48.png)

**Comment by aristath** [comment]
@thehung2224 I don't see what your issue has to do with the issue reported in the original post.
Your issue is about the code control. And yes, there is currently a bug with code controls.
Will be fixed ASAP, there was just another bug with radio controls that had to be adressed first because radio controls, textareas etc are a lot more frequently used than code controls.

**Comment by thehung2224** [comment]
It's working now.
