### ISSUE TITLE
Nonexisting class is giving error

### ISSUE THREAD

**Issue by maxviewup** [themeum/kirki#1660]
### Issue description:
an class was added (`class Kirki_Field_Link extends Kirki_Field_Kirki_URL`) but the `Kirki_Field_Kirki_URL` doens't exist so is getting error. This happens on the Kirki stable plugin. 

The error only appears when an 'link' type is added.

On the develop it seems to be fixed.

**Comment by aristath** [comment]
@maxviewup it's a surprise this has not been reported before... Nothing has changed so it looks like people don't use the `link` control-type and use `url` instead.

It should be ok now, can you please check the develop branch of this repository?
Fix will be included in the next release (v3.0.17)

**Comment by maxviewup** [comment]
The develop branch is ok.
