### ISSUE TITLE
Select Error in Safari

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1662]
### Issue description:
JS Error with select field on safari(high sierra, all newest versions).
![zrzut ekranu 2017-11-21 o 21 39 11](https://user-images.githubusercontent.com/5921659/33095599-7994f198-cf04-11e7-8912-f317b325de8e.png)

### Version used:
Current Develop Branch

### Using theme_mods or options?
Using Kirki demo panel.

**Comment by aristath** [comment]
Fixed in the develop branch, thanks for reporting this!
Will be included in 3.0.17
