### ISSUE TITLE
Wrong output font family of typography type

### ISSUE THREAD

**Issue by steve231293** [themeum/kirki#1663]
### Issue description:

Hello, aristath
I have notice a bug of typography type.

Please add a typography type, then go to Customize change to another font for ex: Roboto'
Then go to frontend & expect element, font family has extra comma [http://prntscr.com/hdnna0](http://prntscr.com/hdnna0)

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

3.0.16

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'theme', array(
	'type'        => 'typography',
	'settings'    => 'heading_typo',
	'label'       => 'Font type',
	'section'     => $section,
	'priority'    => $priority++,
	'transport'   => 'auto',
	'default'     => array(
		'font-family'    => "Work sans",
		'variant'        => '400',
		'line-height'    => '1.2',
		'letter-spacing' => '-0.03em',
		'subsets'        => array( 'latin-ext' ),
	),
	'output'      => array(
		array(
			'element' => 'h1,h2,h3,h4,h5,h6',
		),
	),
) );

**Comment by steve231293** [comment]
This happened only with Kirki 3.0.16, I tested with 3.0.15 then it working normally. Please help me

**Comment by aristath** [comment]
@steve231293 can you please test the develop branch (v3.0.17-dev) and let me know if you still have that issue? it should no longer be happening now

**Comment by aristath** [comment]
So far I've been unable to replicate this issue in v3.0.17 so I'll go ahead and close this issue.
If however this still happens for you then please feel free to reply here so that I may reopen it and examine it again.
