### ISSUE TITLE
Memory Limits overwrites by webfonts.php

### ISSUE THREAD

**Issue by NickHeurter** [themeum/kirki#1664]
Hi Aristath,

### Issue description:
On our website since a while we receive a lot of 500 errors. When I look in our debug log I can find the following:

`2017/11/22 09:28:50 [error] 21058#21058: *7813248 FastCGI sent in stderr: "PHP message: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/nlfire-reposaari/wordpress/current/wp-content/plugins/kirki/modules/webfonts/webfonts.php on line 3" while reading response header from upstream, client: 185.94.197.40, server: www.firecom.nl, request: "GET /wp-admin/edit.php?post_type=product HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-fpm.nlfire-reposaari.sock:", host: "www.firecom.nl", referrer: "https://www.firecom.nl/wp-admin/edit.php?post_type=page"`

So it seems like there is something wrong with the webfonts.php file which overwrites our Memory Limit. Is it possible to solve this?

### Version used:
3.0.16

Thanks already for your help mate!

Bye,
Nick

**Comment by NickHeurter** [comment]
For now I've fixed this by increasing the memory limit on our website. But I think it is worth taking a look at this, because I can understand that there are other Wordpress installations with a memory limit less then 256M.

**Comment by aristath** [comment]
The webfonts.php was a direct copy from the googlefonts API.
I refactored it now and remove all unnecessary data using a custom grunt task (see below) so this shouldn't happen any more no matter how low the server memory is

https://github.com/aristath/kirki/blob/6af0bb1856f24b97b11bd5f251ea67460ccf4c28/Gruntfile.js#L214-L262

This will be included in v3.0.17
