### ISSUE TITLE
Change Google Fonts URL to local host

### ISSUE THREAD

**Issue by bobgarrow** [themeum/kirki#1667]
Hello,

I saw this issue brought up here earlier, but for me the resolution is unclear.

My other Google fonts are hosted locally using this css:

/* roboto-300 - latin */
--
  | @font-face {
  | font-family: 'Roboto';
  | font-style: normal;
  | font-weight: 300;
  | src: url('../fonts/roboto-v18-latin-300.eot'); /* IE9 Compat Modes */
  | src: local('Roboto Light'), local('Roboto-Light'),
  | url('../fonts/roboto-v18-latin-300.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  | url('../fonts/roboto-v18-latin-300.woff2') format('woff2'), /* Super Modern Browsers */
  | url('../fonts/roboto-v18-latin-300.woff') format('woff'), /* Modern Browsers */
  | url('../fonts/roboto-v18-latin-300.ttf') format('truetype'), /* Safari, Android, iOS */
  | url('../fonts/roboto-v18-latin-300.svg#Roboto') format('svg'); /* Legacy iOS */
  | }
  | /* roboto-regular - latin */
  | @font-face {
  | font-family: 'Roboto';
  | font-style: normal;
  | font-weight: 400;
  | src: url('../fonts/roboto-v18-latin-regular.eot'); /* IE9 Compat Modes */
  | src: local('Roboto'), local('Roboto-Regular'),
  | url('../fonts/roboto-v18-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  | url('../fonts/roboto-v18-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
  | url('../fonts/roboto-v18-latin-regular.woff') format('woff'), /* Modern Browsers */
  | url('../fonts/roboto-v18-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
  | url('../fonts/roboto-v18-latin-regular.svg#Roboto') format('svg'); /* Legacy iOS */
  | }

However, I still can't get this line to source locally:

link rel='stylesheet' id='kirki_google_fonts-css' href='https://fonts.googleapis.com/css?family=Roboto%3A300%2Cregular&#038;subset=latin-ext&#038;ver=3.0.16' type='text/css' media='all'

I tried changing the global.css in the theme, as that's the only place I've been able to find where it calls for that fonts.googleapis.com source to load.  But that doesn't work.  Can someone let me know where I can go to make sure the above stylesheet code references my local host instead of Google?

**Comment by bobgarrow** [comment]
link rel='stylesheet' id='kirki_google_fonts-css' href='https://fonts.googleapis.com/css?family=Roboto%3A300%2Cregular&#038;subset=latin-ext&#038;ver=3.0.16' type='text/css' media='all'

Sorry - That's the line that won't source locally.

**Comment by aristath** [comment]
I haven't tested it but this should do it...

```php
add_action( 'wp_print_scripts', function() {
    wp_dequeue_style( 'kirki_google_fonts' );
} );
```

Please keep in mind though that using fonts from local files is not generally recommended. Loading files like that from an external server like google's api which also uses a CDN improves performance.
Also if you happen to change the font in your typography controls in the customizer the new fonts will not load if you dequeue the googlefonts script.
