### ISSUE TITLE
THE "DROPDOWN-PAGES" CONTROL

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1668]
https://aristath.github.io/kirki/docs/controls/dropdown-pages.html

Sir,

Just to keep you posted we need to update how to echo or print it inside the code.

**Comment by aristath** [comment]
>Just to keep you posted we need to update how to echo or print it inside the code.

We don't.
The Kirki documentation assumes you're already familiar with WordPress functions.
The docs clearly state that the control returns the post-ID and it's completely up to you what you're going to do with that ID. There are some examples you could check out in the WordPress documentation for the `get_post()` function: https://developer.wordpress.org/reference/functions/get_post/

This will get you the post-ID:

```php
$post_id = get_theme_mod( 'my_setting' );
```

After that you can choose whatever you want to do with it.
For example you could choose to do this to print the title:

```php
<?php 
$post_id = get_theme_mod( 'my_setting' );
echo sanitize_title( get_the_title( $post_id ) );
?>
```
Or you could do this to print the title and the post-date.
The get_post() function returns a WP_Post object so the possibilities with that are practically limitless
```php
<?php
$post_id = get_theme_mod( 'my_setting' );
$post = get_post( $post_id );
?>
<h1><?php echo sanitize_title( $post->post_title ); ?></h1>
<?php print_r( esc_attr__( 'Posted on: %s', 'textdomain' ), esc_attr( $post->post_date ) ); ?>
```

Or you could even use the WP-REST API if you want. Or do a bunch of other cool stuff... All the control does is get the ID.

---------------

EDIT: Actually a correction... the control doesn't even get the ID. It only saves it. :)
