### ISSUE TITLE
Refactored color controls not working 

### ISSUE THREAD

**Issue by LuisAlejandre** [themeum/kirki#1674]
### Issue description:
Just to bring the issue here, it looks like some of us are experiencing problems with the refactored color controls of version 3.0.16, as reported here: https://wordpress.org/support/topic/unable-to-set-color-uncaught-typeerror/

### Version used:
3.0.16

### Using theme_mods or options?
I believe this issue applies to both cases

**Comment by aristath** [comment]
@LuisAlejandre please try the develop branch from this repository (https://github.com/aristath/kirki/archive/develop.zip)
Let me know if that fixes your issue.. An other user reported this a couple of days ago and I already fixed it but v3.0.17 will be out these days containing that fix (among others) so I'd appreciate the confirmation, just to be sure.

**Comment by LuisAlejandre** [comment]
@aristath I tried the the develop branch and I do confirm this issue has been fixed. Thank you.

**Comment by aristath** [comment]
Excellent, closing this one.
