### ISSUE TITLE
Translation not working on Customizer

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#1675]
Hi Aris,

The translation are not working on Customizer. I already make sure that the string has been translated on the .po file. Other translations on admin pages are working normally, except the Customizer fields that are generated using Kirki.

Please help

**Comment by aristath** [comment]
Hey there @daviedR, what exactly is not working for you?
If Kirki is embedded in a theme, the strings used in Kirki can be translated directly from the theme's .po/.mo files
Or are you referring to translating it when used as a plugin? Even in that case, using the WordPress standard methods seems to be working fine for me...

**Comment by DannyCooper** [comment]
Closing as no further information was supplied and translations appear to be working fine.
