### ISSUE TITLE
"choices" on typography field

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#1676]
Currently, I'm using the code below to load multiple variants on a typography field.

```php
Kirki::add_field( 'test', array(
	'type' => 'typography',
	'settings' => 'font_body',
	'transport' => 'auto',
	'choices' => array(
		'variant' => array(
			'italic',
		),
	),
	'default' => array(
		'font-family' => 'Overpass',
		'subsets' => array( 'latin' ),
		'variant' => 'regular',
	),
	'output' => array(
		array(
			'element' => array( 'body' ),
		),
	),
) );
```

And it outputs CSS below which is exactly what I wanted.

![screenshot 2017-11-29 20 08 54](https://user-images.githubusercontent.com/1418797/33374433-2756ec18-d541-11e7-8e0e-f8c243402900.png)

Is using `choices` attribute on `typography` field like this safe? It wasn't mentioned in the documentation, so I would like to know if it's safe to use on production.

**Comment by aristath** [comment]
Hey there!

Yes, that's fine. The docs are simply currently undergoing a complete rewrite so there are a few things missing.

**Comment by minimaluminium** [comment]
Hi there, thanks for your answer. Great plugin!
