### ISSUE TITLE
Botton Set without refresh

### ISSUE THREAD

**Issue by munirkamal** [themeum/kirki#1678]
### Issue description:

I've used buttons set to conditionally show/hide some controls. It works but with refresh, Is it possible to make it work without refresh? I've tried all 3 transport choices and without luck.

![screen recording 2017-11-29 at 07 17 pm](https://user-images.githubusercontent.com/5817882/33379930-447bf212-d53b-11e7-8ecb-78638f524b84.gif)

Anyone got a solution for this, please?

### Version used:
Latest stable version

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please check the develop branch?
I believe this was just fixed with a whole new implementation for field dependencies.

**Comment by munirkamal** [comment]
@aristath 

Well, I just tried it and it still refreshes, do I need to pass any additional parameter or something I am missing? Please advice.

TIA

**Comment by aristath** [comment]
Oh I'm sorry, I completely misunderstood the original post. My bad... Instead I refactored the field dependencies implementation.

Setting `'transport' => 'postMessage'` in the site-layout control will prevent it from refreshing.

If that doesn't work can you please post the code you're using for that control and its dependent fields?

**Comment by munirkamal** [comment]
Hi,

I tried it, and this works without refresh, but then we have another issue where values do not save properly and revert back while switching. Difficult to explain so I have created a demo site and demo screencast to explain better.

**Code for the demo:**
https://gist.github.com/munirkamal/17deb0a67eba34fc8ae3b5390b800e0a

**Quick Screencast to explain the issue:**
https://cl.ly/o6wg

**Demo site, so you may test it yourself.**
Login: http://tame-cheetah.w6.poopy.life/wp-admin/ 
Username: demo 
Password: kmn9Z40hK4VP

Looking forward to your help.

TIA,
Munir

**Comment by aristath** [comment]
About the missing styles:
I can see in the browser console that the styles.min.css file is missing.
Are you by any chance modifying the URL of kirki? Perhaps using a `kirki/config` filter and defining `url_path` in there?

As for the output:
If a field is not shown, then its CSS is not used either because we assume that since you hide them, they no longer apply. The dependencies were not originally designed to be used as tabs which is why it works this way.

I just added 2 filters that will disable that default behaviour so you can use those:

```php
add_filter( 'kirki/start/webfonts/skip_hidden', '__return_false' );
add_filter( 'kirki/start/css/skip_hidden', '__return_false' );
```
`start` of course is the config-ID you're using for your fields.

Once you add those 2 lines in your theme it should work the way you want it.

**Comment by munirkamal** [comment]
Awesome, That worked perfectly.

Now only issue is with the missing CSS min file which looks like a bug in v3.0.17

**Comment by aristath** [comment]
Already fixed in the wordpress.org version. Delete your copy and redownload. It was a problem with the SVN push.
I'll fix in the repo here later today :+1:

**Comment by munirkamal** [comment]
@aristath 

Hi,

This seems like since v3.0.22 the filters solution you provided to make button groups work as tabs don't work. I can see in the changelog that you have removed webfonts.php and now use the json file.

Could you please suggest an updated solution to this use case? I have used this extensively in my theme and now If I update to latest version of kirki nothing works :( 

Looking forward to your response.

TIA,
Munir

**Comment by aristath** [comment]
Can you try using this instead of the previous filters?

```php
add_filter( 'kirki_start_webfonts_skip_hidden', '__return_false' );
add_filter( 'kirki_start_css_skip_hidden', '__return_false' );
```

**Comment by munirkamal** [comment]
Thank you, that did the trick.
