### ISSUE TITLE
 Undefined variable: hex in \includes\Helpers\libraries\class-kirki-color.php on line 263

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#168]
( ! ) Notice: Undefined variable: hex in \includes\Helpers\libraries\class-kirki-color.php on line 263

Solution:
In line 262 of mentioned above file, please replace:
$color      = self::sanitize_hex( $color, false );
with:
$hex      = self::sanitize_hex( $color, false );

Regards

**Comment by aristath** [comment]
Please use the develop branch: https://github.com/aristath/kirki/tree/develop

This has already been fixed and will be included in the next release.

**Comment by DevelopOnline** [comment]
Thanks a lot :)
Good Luck
