### ISSUE TITLE
Sections with "outer" type.

### ISSUE THREAD

**Issue by Alanimus** [themeum/kirki#1683]
I was thinking it would be very cool if the new "outer" section type could be implemented into Kirki as a section type? It's a section type that essentially extends the sidebar like how the core widget section looks, and is implemented in Customizer core if you click the "publish settings" button.

As seen here: [https://make.wordpress.org/core/2017/11/01/improvements-to-the-customize-js-api-in-4-9/#outer-sections](https://make.wordpress.org/core/2017/11/01/improvements-to-the-customize-js-api-in-4-9/#outer-sections)

I managed to get it partially working but not using Kirki sections.

**Comment by aristath** [comment]
great idea, marking as a feature request! 👍

**Comment by aristath** [comment]
No reason to wait... It was simple enough, I added it in v3.0.17.
Just add `'type'=>'outer'` to a section and it'll work.

**Comment by Alanimus** [comment]
Thanks! Works perfect.

**Comment by sametakdemir** [comment]
Perfect! Thank you this share
