### ISSUE TITLE
field-dependencies.js:58 Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Alanimus** [themeum/kirki#1684]
### Issue description:
field-dependencies.js:58 Uncaught TypeError: Cannot read property 'get' of undefined
    at field-dependencies.js:58
    at Function.m.each.m.forEach (underscore.min.js:5)
    at Object.showKirkiControl (field-dependencies.js:57)
    at Function.<anonymous> (field-dependencies.js:9)
    at child.<anonymous> (customize-base.js:441)
    at Function.each (jquery.js:2)
    at Function.each (customize-base.js:440)
    at Object.init (field-dependencies.js:8)
    at HTMLDocument.<anonymous> (field-dependencies.js:138)
    at i (jquery.js:2)

### Version used:
Newest development branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

n/a

I just pulled new Dev branch changes and now get this error.

![capture](https://user-images.githubusercontent.com/1911237/33519346-bb041bb0-d759-11e7-80d5-54f6fe11fe9c.PNG)

**Comment by aristath** [comment]
@Alanimus can you please post the code you're using for the fields?
Do you have an `active_callback` somewhere referencing other fields?
I'll need your code in order to debug this and figure out what's wrong 'cause I can't replicate the issue with my tests

**Comment by aristath** [comment]
Try replacing this line: https://github.com/aristath/kirki/blob/2f970fb488f8b9ea564e52a0399f89479daa815f/modules/field-dependencies/field-dependencies.js#L58
with this:
```js
var requirementShow = self.evaluate( requirement.value, wp.customize.control( requirement.setting ).setting._value, requirement.operator );
```

and let me know if that works for you...

**Comment by aristath** [comment]
I just pushed a _possible_ fix for this.
I'm not sure it will work in your case since I don't have your code to see what goes on, but it will catch 99% of issues.
Please pull the latest develop branch and test this again... Remember to clear your browser caches otherwise the previous JS will be loaded instead 😉

**Comment by Alanimus** [comment]
Sorry for not getting back right away. It seems to be fixed now. I should have also mentioned I am using the latest nightly WP 5.0.

**Comment by aristath** [comment]
excellent, thanks for checking!
