### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setting' of undefined

### ISSUE THREAD

**Issue by sophy** [themeum/kirki#1685]
### Issue description:
After I update to new version of Kirki (3.0.16) all control color fields got the error.  When user try to change each color fields.

`Uncaught TypeError: Cannot read property 'setting' of undefined` from `plugins/kirki/controls/js/dist/script.min.js?ver=3.0.16`

When I try js script without minifying I got this error line 
```javascript
set: function(element, value, key) {
...
wp.customize.control(foundNode).setting.set(value); // line error
...
}
```

### Version used:
**3.0.16**

### Using theme_mods or options?

**Options**

### Code to reproduce the issue (config + field(s))

```php
// Config
ThemePrefix_Kirki::add_config( 'themeprefix_theme_conf', array(
	'option_type'	=> 'option',
	'option_name'	=> 'themeprefix_theme_options',
	'capability'	=> 'edit_theme_options',
) );
// Field
ThemePrefix_Kirki::add_field( 'themeprefix_theme_conf', array(
	'type'			=> 'color',
	'settings'		=> 'primary_color',
	'label'			=> __( 'Header Background', 'themeprefix' ),
	'section'		=> 'themeprefix_style_section',
	'default'		=> '#000000',
	'priority'		=> 2,
	'choices' => array(
        'alpha' => true,
    ),
) );
```

### Note: I am using Kirki inside my theme and from the plugin the same error.

**Comment by aristath** [comment]
Closing this one, it has already been fixed.
