### ISSUE TITLE
Missing styles.min.css since 3.0.17 update

### ISSUE THREAD

**Issue by Jaessun** [themeum/kirki#1687]
### Issue description:
Hi,
Since the 3.0.17 update there is a missing styles.min.css in the customizer.

![missing style](https://i.imgur.com/TacSVPz.png)

When I browse the /controls/css directory of the plugin, styles.min.css is not there. Only styles.css is there and if I rename it to styles.min.css it works as expected.
### Version used:
3.0.17

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Adding any control with Kirki can reproduce this issue.
For example:

```
Kirki::add_config( 'my_config', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

Kirki::add_section( 'my_section', array(
	'priority'    => 10,
	'title'       => 'My Section',
	'description' => 'My section description',
) );

Kirki::add_field( 'my_config', array(
	'type'        => 'color',
	'settings'    => 'my_setting',
	'label'       => 'This is the label',
	'section'     => 'my_section',
	'default'     => 42,
	'choices'     => array(
		'min'  => '0',
		'max'  => '100',
		'step' => '1',
	),
) );
```

**Comment by aristath** [comment]
Hey there!
I'm terribly sorry for this, there appears to have been an error in the deploy script that pushes the update on the wordpress.org repository.
Please delete your copy and re-download from wordpress.org, I just updates it there.
I'll fix the version on the repository later today 👍

**Comment by Jaessun** [comment]
I re-downloaded from wordpress.org and it seems to work just fine. Thank you!
