### ISSUE TITLE
styles-legacy.min doesn't exist

### ISSUE THREAD

**Issue by michelle-may** [themeum/kirki#1688]
### Issue description:
Noticed styling issue in the customizer on all the switches and radio buttons. A css file appears to be missing: controls/css/styles-legacy.min.css?ver=3.0.17

### Version used:
This is in 3.0.17

**Comment by iliman** [comment]
And /controls/css/styles.min.css?ver=3.0.17

**Comment by aristath** [comment]
This has already fixed in the wordpress.org version, please delete your copy and re-download. It was a problem with the SVN upload.
The dev version from this repo will be fixed later today.
