### ISSUE TITLE
Fields gets disturbed with version 3.0.17

### ISSUE THREAD

**Issue by two-points** [themeum/kirki#1689]
Edit: There is a problem with almost all kirki fields. styles.min.css in controls folder is missing.

### Issue description:
I have used typography field in my theme. It was working fine until version 3.0.16. With version 3.0.17, its layout looks disturbed in customizer and standard fonts don't appear in the drop-down.

**Screenshot on Version 3.0.16:** https://imgur.com/NjdG7lc
**Screenshot on Version 3.0.17:** https://imgur.com/CCGRU1C

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
version 3.0.17

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Kirki::add_field( 'custompress_theme', array(
	'settings' => 'body_typography',
	'label'    => __( 'Body Typography', 'custompress' ),
	'section'  => 'custom_typography',
	'type'     => 'typography',
	'priority' => 1,
    'default'     => array(
		'font-family'    => "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
		'variant'        => 'regular',
		'color'          => '#606c76',
	),
	'output'      => array(
		array(
			'element' => array( 'body', 'button', 'input', 'optgroup', 'select', 'textarea' ),
		),
	),
) );

**Comment by two-points** [comment]
Found another issue closed with the same problem. #1687 

But, even after downloading again from wordpress.org, has not solved the issue for me. I'm closing this ticket as it might get resolved in some time.

**Comment by aristath** [comment]
Check again in a couple of minutes please....

**Comment by two-points** [comment]
Sure. Thank you for the awesome plugin and excellent support.

**Comment by two-points** [comment]
Hello @aristath ,

Fields are getting displayed properly now. But, "Standard fonts" are missing in typography field drop-down. Google fonts are displayed properly. 

Screenshot: https://imgur.com/nHAis40

What can be the cause of this issue?

**Comment by aristath** [comment]
fixed in 3.0.18

**Comment by two-points** [comment]
Hello @aristath ,

Thank you for the update.

Standard fonts are displayed now in the drop-down. But, we are not able to change variant of standard fonts. It works perfectly for Google fonts.


Regards.
