### ISSUE TITLE
warnings displayed after upgrade kirki from ver. 0.7.1 to 0.8.2

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#169]
Hi there

Below warnings will are displaying on customizer (live-preview div) after upgrade kirki from ver. 0.7.1 to 0.8.2:

Warning: simplexml_load_file() [function.simplexml-load-file]: http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/developa/public_html/wp/wp-content/themes/new/lib/kirki/includes/Helpers/libraries/class-kirki-colourlovers.php on line 24

Warning: simplexml_load_file(http://www.colourlovers.com/api/palettes/top) [function.simplexml-load-file]: failed to open stream: no suitable wrapper could be found in /home/developa/public_html/wp/wp-content/themes/new/lib/kirki/includes/Helpers/libraries/class-kirki-colourlovers.php on line 24

Warning: simplexml_load_file() [function.simplexml-load-file]: I/O warning : failed to load external entity "http://www.colourlovers.com/api/palettes/top" in /home/developa/public_html/wp/wp-content/themes/new/lib/kirki/includes/Helpers/libraries/class-kirki-colourlovers.php on line 24

Warning: Invalid argument supplied for foreach() in /home/developa/public_html/wp/wp-content/themes/new/lib/kirki/includes/Helpers/libraries/class-kirki-colourlovers.php on line 27

Warning: Cannot modify header information - headers already sent by (output started at /home/developa/public_html/wp/wp-content/themes/new/lib/kirki/includes/Helpers/libraries/class-kirki-colourlovers.php:24) in /home/developa/public_html/wp/wp-includes/option.php on line 748

Warning: Cannot modify header information - headers already sent by (output started at /home/developa/public_html/wp/wp-content/themes/new/lib/kirki/includes/Helpers/libraries/class-kirki-colourlovers.php:24) in /home/developa/public_html/wp/wp-includes/option.php on line 749

Any Solution?!

**Comment by aristath** [comment]
Are you by any chance using our dummy configuration file?

If you are then you should probably just delete a couple 'palette' controls from it. If I'm not mistaken we have a couple of fields there that fetch palettes from the colourlovers API ( completely unnecessary, it was just for demo purposes)

**Comment by DevelopOnline** [comment]
Yes, exactly.

Thanks for your fast answer :)
