### ISSUE TITLE
Document use of exclude option

### ISSUE THREAD

**Issue by FrankM1** [themeum/kirki#1692]
### Issue description:
Looking at  the source code, it seems there are several ways to use the exclude option. Would be nice to have this great feature documented. Thanks.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
<pre>
$controls[] = [
        'label'     => esc_html__( 'Secondary Font', 'example' ),
        'desc'      => esc_html__( 'The secondary font for your site. This is used by headings, and large text.', 'example' ),
        'id'        => 'font_secondary_base',
        'section'   => 'general_typography',
        'default'   => [
            'font-family' => 'Cabin',
            'color'       => '#000',
        ],
        'type'      => 'typography',
        'transport' => 'auto',
        'exclude'   => [
            'variant',
            'font-size',
            'line-height',
            'letter-spacing',
            'text-align',
            'text-transform',
        ],
        'output'    => [
            [
                'element' => '.entry-title, h1,h2,h3,h4,h5,h6',
            ],
        ],
    ];
</pre>

**Comment by manchumahara** [comment]
I think the best way to update the document is to update the docs git repo and send PR . All docs are here https://github.com/aristath/kirki/tree/develop/docs

**Comment by DannyCooper** [comment]
The `exclude` argument is a sub-argument of `output`. Here is the relevant documentation - https://kirki.org/docs/modules/css#exclude

Pull Requests are welcomed if you think the docs could be improved upon.
