### ISSUE TITLE
typography control error

### ISSUE THREAD

**Issue by egi361** [themeum/kirki#1696]
### Issue description:
kirki typography control

### Version used:
3.0.19

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
array(
                'type'        => 'typography',
                'settings'    => 'main_font',
                'label'       => esc_html__( 'Main Font', 'sobari' ),
                'description' => esc_html__('Will be used on heading', 'sobari'),
                'priority'    => 10,
                'default'     => array(
                    'font-family'    => 'Poppins',
                    'variant'        => '600',
                    'subsets'        => array( 'latin-ext' ),
                ),
                'active_callback'   => array(
                    array(
                        'setting'   => 'typography_source_font',
                        'operator'  => '==',
                        'value'     => 'google-fonts',
                    ),
                ),
            )
```
when request fonts via admin ajax 
Request URL:http://192.168.88.213:88/sobari/wp-admin/admin-ajax.php
Request Method:POST
Status Code:400 Bad Request
Remote Address:192.168.88.213:88
Referrer Policy:no-referrer-when-downgrade
cause the ajax url must be something like this "http://192.168.88.213:88/sobari/wp-admin/admin-ajax.php?customize_changeset_uuid=32b5d103-5518-410a-934d-60efa8ac705d&customize_preview_nonce=84ff4ac820"
how can i fix this?

**Comment by aristath** [comment]
@egi361 I was unable to replicate your issue, however I just pushed a possible fix for this, could you please test the develop branch and let me know if that fixes your issue?

**Comment by aristath** [comment]
Nobody else ever reported this issue and there was a commit that was pushed in v3.0.20 so I'll go ahead and close this one.
If it still happens for you then please feel free to reopen the ticket and post an update with as many details as possible.

**Comment by S-Harabara** [comment]
I have the same problem , this problem reproduce if kirki directly embed in my theme,  if i use kirki as plugin ,typography control working normally.

**Comment by aristath** [comment]
@S-Harabara please check v3.0.25m it was just released a few minutes ago.
If that doesn't fix your issue then please open a new ticket with as many details as possible so that I may replicate and debug it.
