### ISSUE TITLE
set_url_scheme for images output (for users who switch from http to https or vice versa)

### ISSUE THREAD

**Issue by JimmyAppelt** [themeum/kirki#1697]
### Issue description:

When images are saved when a site is not using SSL, after switching to SSL they still use `http://`

(they invoke mixed content console errors)

### Proposal:

As shortly discussed on chat:

Implement `set_url_scheme()` on output

**Comment by aristath** [comment]
Fixed, will be included in v3.0.20

**Comment by JimmyAppelt** [comment]
Thank you @aristath !
