### ISSUE TITLE
Field "required" argument malfunction

### ISSUE THREAD

**Issue by WebTrooper** [themeum/kirki#17]
I copy pasted the following code directly from kirki.org, and using Kirki as a plugin. Once the required control is visible, it will only close by clicking option 1. You can see in the attached image I have 2 selected. 3 is the required option.
- Create the section
  */
  function my_custom_section( $wp_customize ) {
  
  // Create the "My Section" section
  $wp_customize->add_section( 'my_section', array(
      'title'    => __( 'My Section', 'translation_domain' ),
      'priority' => 12
  ) );

}
add_action( 'customize_register', 'my_custom_section' );

/**
- Create the setting
  */
  function my_custom_setting( $controls ) {

$controls[] = array(
    'type'     => 'radio',
    'mode'     => 'buttonset',
    'setting'  => 'parent_setting',
    'label'    => __( 'My Setting', 'textdomain' ),
    'section'  => 'my_section',
    'default'  => 'option_1',
    'priority' => 1,
    'choices'  => array(
        'option_1' => __( 'Option 1', 'textdomain' ),
        'option_2' => __( 'Option 2', 'textdomain' ),
        'option_3' => __( 'Option 3', 'textdomain' ),
        'option_4' => __( 'Option 4', 'textdomain' ),
    ),
);

$controls[] = array(
    'type'     => 'textarea',
    'setting'  => 'child_setting',
    'label'    => __( 'My Setting', 'textdomain' ),
    'section'  => 'my_section',
    'default'  => __( 'Default text', 'textdomain' ),
    'priority' => 1,
    'required' => array( 'parent_setting' => 'option_3' )
); 
    return $controls;
}
add_filter( 'kirki/controls', 'my_custom_setting' );

![untitled-1](https://cloud.githubusercontent.com/assets/2085159/4040341/0909d6ea-2ce2-11e4-913e-b80c60631203.png)

**Comment by jovethgallardo** [comment]
I'm not sure if this is the correct way to do it but it worked for me....
1. Open required.php --- located in kirki/includes/functions 
2. Change line 53 
   From: add_action( 'customize_controls_print_scripts', 'kirki_required_script', 999 );
   To: add_action( 'customize_controls_print_footer_scripts', 'kirki_required_script' );
   *\* I'm pretty sure that the way the customizer loads was preventing the element to be hidden. 
3. Then Change line 20
   
    From:  <?php if ( isset( $id ) && isset( $value ) && $value == intval( get_theme_mod( $id ) ) ) : ?>
    To:    <?php if(get_theme_mod( $id ) == $value) : ?>

Again I don't know if this is the correct way to do it but it worked for me

**Comment by aristath** [comment]
Hey there!

I just made some adjustments on the last commit on https://github.com/presscodes/kirki/commit/2641b594b0babaaf52f7980cac65a97df30a4722

Can you please check if it works ok for you now?

**Comment by jovethgallardo** [comment]
Works great! =)

**Comment by ghost** [comment]
Works fine :+1:

**Comment by aristath** [comment]
Thanks for checking!

I'll go ahead and close this one then. :smile:

**Comment by ghost** [comment]
Hey, @aristath  I Have a problem in kirki plugin.  live customizer is not working for me and also font-family list show in customizer  but when get  font-family at front end by using `get_theme_mod()`  then actual font is not show only show font-family name means font-family not load properly.

please help me.

thanks.

**Comment by aristath** [comment]
Hey there!

I don't see what this has to do with the issue described on the original thread here... Could you please create a separate issue for this?
