### ISSUE TITLE
Background control returns repeat-all instead of repeat

### ISSUE THREAD

**Issue by cgrant992** [themeum/kirki#1701]
### Issue description:
Like the title says, the background control returns 'repeat-all' for the background repeat property. Not an issue but just figured it should be changed to 'repeat' just so no logic is required when trying to output it for CSS.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by aristath** [comment]
I don't know how I missed this one... fixed. Will be included in 3.0.20
