### ISSUE TITLE
Dropdown list/select of available sidebars/widget areas

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#1702]
### Issue description:
I would like to list all available sidebars/widget areas in a dropdown. I know how to get categories with: 
`'choices' => Kirki_Helper::get_terms( 'category' )`

But I'm not sure how to do for the sidebars/widget areas.

**Comment by AlxMedia** [comment]
Here is how OptionTree does it, perhaps something worth adding? I'm moving from OT and this is the only thing I have had trouble with when converting over the options.

```
if ( ! function_exists( 'ot_type_sidebar_select' ) ) {
  
  function ot_type_sidebar_select( $args = array() ) {
  
    /* turns arguments array into variables */
    extract( $args );
    
    /* verify a description */
    $has_desc = $field_desc ? true : false;
    
    /* format setting outer wrapper */
    echo '<div class="format-setting type-sidebar-select ' . ( $has_desc ? 'has-desc' : 'no-desc' ) . '">';
      
      /* description */
      echo $has_desc ? '<div class="description">' . htmlspecialchars_decode( $field_desc ) . '</div>' : '';
      
      /* format setting inner wrapper */
      echo '<div class="format-setting-inner">';
      
        /* build page select */
        echo '<select name="' . esc_attr( $field_name ) . '" id="' . esc_attr( $field_id ) . '" class="option-tree-ui-select ' . $field_class . '">';

        /* get the registered sidebars */
        global $wp_registered_sidebars;

        $sidebars = array();
        foreach( $wp_registered_sidebars as $id=>$sidebar ) {
          $sidebars[ $id ] = $sidebar[ 'name' ];
        }

        /* filters to restrict which sidebars are allowed to be selected, for example we can restrict footer sidebars to be selectable on a blog page */
        $sidebars = apply_filters( 'ot_recognized_sidebars', $sidebars );
        $sidebars = apply_filters( 'ot_recognized_sidebars_' . $field_id, $sidebars );

        /* has sidebars */
        if ( count( $sidebars ) ) {
          echo '<option value="">-- ' . __( 'Choose Sidebar', 'kirkitheme' ) . ' --</option>';
          foreach ( $sidebars as $id => $sidebar ) {
            echo '<option value="' . esc_attr( $id ) . '"' . selected( $field_value, $id, false ) . '>' . esc_attr( $sidebar ) . '</option>';
          }
        } else {
          echo '<option value="">' . __( 'No Sidebars', 'kirkitheme' ) . '</option>';
        }
        
        echo '</select>';
        
      echo '</div>';
      
    echo '</div>';
    
  }
  
}
```
Or is there an easier way to fix a dropdown of sidebars?

I have to say you've made an amazing job with Kirki, it has been so easy to work with so far.

**Comment by aristath** [comment]
Hey there!

I'm glad you like Kirki, I really appreciate it.
For the sidebars selection it's mostly a timing issue.
Sometimes controls are registered before custom sidebars are added, so you need to delay the control a bit.
I added an example of how to do it here: https://github.com/aristath/kirki/blob/e4fc230efc8988442c0d65f3c8e613b16fee9f2a/example.php#L906-L929
The `Kirki::add_field()` call needs to be wrapped inside a function that will be added on `init` with a priority pretty high (like 999 in the example).
In this example I'm saving the sidebar-ID and displaying the sidebar-name - which is what I suppose is the most usual scenario

**Comment by AlxMedia** [comment]
Perfect, thank you.

The only issue now is that when I create a sidebar area with the repeater, the new sidebar does not appear in the dropdown unless I force-refresh the customizer. Is there any way to make it appear once saved?

Example: https://i.imgur.com/qBSoYs8.png

**Comment by aristath** [comment]
Oh, I didn't realize you were using a repeater to create the sidebars....
I'm afraid not, there (currently) is no implementation to live-update the selections inside a dropbox from the values of another control.
It's possible if you write some custom JS, but not out of the box.

**Comment by AlxMedia** [comment]
Might be stupid of me to use the repeater for it, but it will have to work for now - I'll just tell users to refresh. I'm trying to get all the features from OT to work here in Kirki.

Thanks for the quick responses, this is light night and day compared to OT which has been pretty much dead for 2 years. Awesome to see ongoing development. Fantastic work :-)

**Comment by aristath** [comment]
👍 I'm glad i could help!
You could add details on how to handle this in the repeater's description(save as draft and refresh page to see your new sidebars in the select - or something along those lines)

**Comment by AlxMedia** [comment]
Good idea! Added both a description and extra details in a tooltip. That will work!

**Comment by MrAndreius** [comment]
```
function kirki_sidebars_select_example() { 
        do_action('widgets_init');
 	$sidebars = array(); 
 	if ( isset( $GLOBALS['wp_registered_sidebars'] ) ) { 
 		$sidebars = $GLOBALS['wp_registered_sidebars']; 
 	} 
 	$sidebars_choices = array(); 
 	foreach ( $sidebars as $sidebar ) { 
 		$sidebars_choices[ $sidebar['id'] ] = $sidebar['name']; 
 	}  	
        return $sidebars_choices; 
 } 

Kirki::add_field( 'kirki_demo', array( 
 		'type'        => 'select', 
 		'settings'    => 'sidebars_select', 
 		'label'       => esc_attr__( 'Sidebars Select', 'kirki' ), 
 		'description' => esc_attr__( 'An example of how to implement sidebars selection.', 'kirki' ), 
 		'section'     => 'select_section', 
 		'default'     => 'primary', 
 		'choices'     => kirki_sidebars_select_example(), 
 		'priority'    => 30, 
 	) ); 
```


in the beginning, call the do_action('widgets_init');

**Comment by AlxMedia** [comment]
Hm, makes no difference here when I try. Still need to manually refresh the page for the sidebars to show up.

**Comment by MrAndreius** [comment]
@AlxMedia 
I use KIRKI it as a plugin (not built into the theme)

the list creation function was added after the initialization of the customizer

just checked, in 20 places where it is called all work fine

and there are no errors in the console or debug.log
