### ISSUE TITLE
On/Off switch reversed

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#1704]
### Issue description:
When I use the on/off switch in my theme with for example this code:

`<?php if ( get_theme_mod('site-description') != 'off' ): ?>Test<?php endif; ?>`

With this option code:

```
// Header: Site Description
Kirki::add_field( 'theme_config_id', array(
	'type'			=> 'switch',
	'settings'		=> 'site-description',
	'label'			=> esc_attr__( 'Site Description', 'kirkitheme' ),
	'description'	=> esc_attr__( 'The description that appears next to your logo', 'kirkitheme' ),
	'section'		=> 'header',
	'default'		=> 'on',
) );
```

It says On on the theme panel, but the option is off. To enable it I have to turn it Off. So the option is reversed as far as I can see. Unless I'm making some mistake somewhere.

**Comment by AlxMedia** [comment]
This works:

`<?php if ( get_theme_mod('site-description') == 'on' ): ?>Test<?php endif; ?>`

This does not (reversed):

`<?php if ( get_theme_mod('site-description') != 'off' ): ?>Test<?php endif; ?>`

Shouldn't "On" and "Not Off" mean the same?

**Comment by aristath** [comment]
switches are basically over-styled checkboxes.
See docs on https://aristath.github.io/kirki/docs/controls/switch.html#usage
Switches save boolean values (`true|false`).
Try something like this:
```php
<?php if ( get_theme_mod( 'site-description' ) ) : ?>Test<?php endif; ?>
```
or
```php
<?php if ( true === get_theme_mod( 'site-description' ) ) : ?>Test<?php endif; ?>
```

**Comment by AlxMedia** [comment]
Thank you - that works.
