### ISSUE TITLE
HTML in the label

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1705]
### Issue description:
Sorry if I missed it, but is it possible to add HTML in the control’s label / description? 
It seems all HTML is  being escaped there. 

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.20

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'settings', array(
	'type'        => 'image',
	'settings'    => 'my-settings',
	'label'       => '<a href="#">Learn more</a>' .  esc_html__('Some additional description'), // learn more is being escaped too
	'section'     => 'my-section',
) );
```

**Comment by AlxMedia** [comment]
I've had the same issue trying to add html to descriptions/labels. It works in tooltips though.

**Comment by aristath** [comment]
Should be ok now in the develop branch
