### ISSUE TITLE
Click on partial refresh edit link in preview area doesn’t focus sortable field

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1707]
### Issue description:
When you click on pencil icon in customizer preview area that is linked to sortable field, nothing happens. When you click on let’s say pencil <-> image field, panel correctly goes to the needed field and highlights `upload media` button.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.20

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please post the code you're using so that I may replicate the issue?

**Comment by DannyCooper** [comment]
Closing as it doesn't seem like the code will be shared.
