### ISSUE TITLE
Issue on first activation of new theme: Defaults are not used

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#1712]
### Issue description:
As it is right now, everything looks perfect in the customizer when activating a new theme. Options can be edited, tested and so on.  Default settings are shown correctly.

However when I load the website outside of the customizer none of the default options works. Even if I click save once in the customizer, the same problem remains. Right now I have to change the option, save, and then change it back and save in order for it to show up properly.

---

I see this: https://github.com/aristath/kirki/issues/1167 and https://github.com/aristath/kirki/issues/1275 - is there no easy way to use the defaults already applied? Adding them twice and in the templates isn't ideal.

Some more related:
* https://wordpress.stackexchange.com/questions/143789/use-default-value-of-wp-customizer-in-theme-mod-output
* https://wordpress.stackexchange.com/questions/248570/wordpress-customizer-not-setting-default-value-upon-initial-install/248605#248605
* https://wordpress.stackexchange.com/a/264050

I'd be happy if clicking save once in the customizer fixed the issue, but how come it doesn't save defaults when doing so? **Can the customizer be tricked into saving all fields, even if they are not touched?** If not, is it possible to have a separate file where all defaults are defined in a long list or do I have to place it in the template files?

**Comment by aristath** [comment]
> I'd be happy if clicking save once in the customizer fixed the issue, but how come it doesn't save defaults when doing so? **Can the customizer be tricked into saving all fields, even if they are not touched?**

I'm afraid not, that's just the way WordPress works... Only modified values get saved in the customizer.
You should ALWAYS use the 2nd argument in `get_theme_mod` calls.
GOOD:
```php
$value = get_theme_mod( 'my_setting', 'default_value' );
```
BAD:
```php
$value = get_theme_mod( 'my_setting' );
```

If you don't want to go through the process of adding it to everything you have, then you could change them all from `get_theme_mod` to `my_theme_get_theme_mod`, and then add this as a proxy function:

```php
function my_theme_get_theme_mod( $theme_mod ) {
	$default_value = '';
	if ( class_exists( 'Kirki' ) && isset( Kirki::$fields[ $field_id ] ) && isset( Kirki::$fields[ $field_id ]['default'] ) ) {
		$default_value = Kirki::$fields[ $field_id ]['default'];
	}
	$value = get_theme_mod( $field_id, $default_value );
}
```
Of course replace the `my_theme` with your actual theme-name 😉 

However, that's just a workaround... the _right_ way to do it would be to add the default values in all your `get_theme_mod` calls.

**Comment by AlxMedia** [comment]
Thanks for clarifying. 

Right now all of my settings looks like this throughout the whole theme (from OptionTree, I changed ot_get_option to get_theme_mod):
`<?php if ( get_theme_mod( 'post-nav' ) == 'content') { get_template_part('inc/post-nav'); } ?>`
or:
`<?php if ( get_theme_mod('post-comments') =='on' ) { comments_template('/comments.php',true); } ?>`
or:
`if ( get_theme_mod('color-mobile-menu') != '#222222' ) { }`

So I'm checking for the default value to not print the CSS for example.

Is this way not gonna work with Kirki/Customizer? How would I need to rewrite it to do it correctly? Sorry for the perhaps basic questions.

**Comment by aristath** [comment]
It depends on the `default` value of your controls.

If the default value for the `post-nav` setting is `content`, then this:
```php
get_theme_mod( 'post-nav' )
```
should look like this:
```php
get_theme_mod( 'post-nav', 'content' )
```

If the default value for the `color-mobile-menu` setting is for example `#000000`, then this:
```php
get_theme_mod('color-mobile-menu')
```
should look like this:
```php
get_theme_mod('color-mobile-menu', '#000000')
```

You just add the default value as a 2nd argument in all the `get_theme_mod` calls.
It's not hard, just a bit time consuming the 1st time you do it.

If I have this control:
```php
Kirki::add_field( 'my_config', array(
	'type'        => 'checkbox',
	'settings'    => 'checkbox_setting',
	'label'       => esc_attr__( 'Checkbox Control', 'kirki' ),
	'description' => esc_attr__( 'Description', 'kirki' ),
	'section'     => 'checkbox_section',
	'default'     => true,
) );
```
Then to get its value I'll do this:
```php
get_theme_mod( 'checkbox_setting', true )
```
Just copy-paste the value you're using in the field's `default` argument inside the `get_theme_mod` function calls.

**Comment by AlxMedia** [comment]
So, lets say I edit this line:
`<?php if ( get_theme_mod('sharrre') =='on' ) { get_template_part('inc/sharrre'); } ?>`
I just change that to:
`<?php if ( get_theme_mod('sharrre', 'on') =='on' ) { get_template_part('inc/sharrre'); } ?>`
Or am I misunderstanding it? Sorry for being slow today - thanks for all the help.

**Comment by aristath** [comment]
if the default value for `sharrre` is `on` then yes 👍

**Comment by AlxMedia** [comment]
Got it to work well now. Not as clean code as before but I guess this is how it has to be :-) Thanks again.

**Comment by asilcetin** [comment]
For those, who want to use the workaround which @aristath has posted above, here is the slightly corrected version:

```
if ( ! function_exists( 'my_theme_get_theme_mod' ) ) {
  function my_theme_get_theme_mod( $field_id, $default_value = '' ) {
    if ( $field_id ) {
      if ( !$default_value ) {
        if ( class_exists( 'Kirki' ) && isset( Kirki::$fields[ $field_id ] ) && isset( Kirki::$fields[ $field_id ]['default'] ) ) {
          $default_value = Kirki::$fields[ $field_id ]['default'];
        }
      }
      $value = get_theme_mod( $field_id, $default_value );
      return $value;
    }
    return false;
  }
}
```

I find this workaround useful, because I can define all my defaults in my kirki configuration and won't have to define them again while calling the get_theme_mod. The above code should also work if kirki is deinstalled and my_theme_get_theme_mod() function would then behave like the default get_theme_mod() function.

**Comment by aristath** [comment]
Ideally no workaround would be necessary and developers would simply get used to adding the 2nd argument in the `get_theme_mod()` function.
But yes, the above function should work fine.

**Comment by sgeray** [comment]
> For those, who want to use the workaround which @aristath has posted above, here is the slightly corrected version:
> 
> ```
> if ( ! function_exists( 'my_theme_get_theme_mod' ) ) {
>   function my_theme_get_theme_mod( $field_id, $default_value = '' ) {
>     if ( $field_id ) {
>       if ( !$default_value ) {
>         if ( class_exists( 'Kirki' ) && isset( Kirki::$fields[ $field_id ] ) && isset( Kirki::$fields[ $field_id ]['default'] ) ) {
>           $default_value = Kirki::$fields[ $field_id ]['default'];
>         }
>       }
>       $value = get_theme_mod( $field_id, $default_value );
>       return $value;
>     }
>     return false;
>   }
> }
> ```
> 
> I find this workaround useful, because I can define all my defaults in my kirki configuration and won't have to define them again while calling the get_theme_mod. The above code should also work if kirki is deinstalled and my_theme_get_theme_mod() function would then behave like the default get_theme_mod() function.

if you still need a solution the above doesn't work, but this one works (for me).

```
if ( ! function_exists( 'my_theme_get_theme_mod' ) ) {
	function my_theme_get_theme_mod( $field_id, $default_value = '' ) {
		if ( $field_id ) {
			if ( !$default_value ) {
				if ( class_exists( 'Kirki' ) && isset( Kirki::$all_fields[ $field_id ] ) && isset( Kirki::$all_fields[ $field_id ]['default'] ) ) {					
					$default_value = Kirki::$all_fields[ $field_id ]['default'];
				}
			}
			$value = get_theme_mod( $field_id, $default_value );
			return $value;
		}
		return false;
	}
}
```
