### ISSUE TITLE
Convert Redux to Kirki

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1718]
Currently using Redux in a theme, is there an easy way to convert to Kirki?

**Comment by AlxMedia** [comment]
As someone who just converted 13 themes the last week from OptionTree to Kirki, I don't think there is an easy way, or well, that depends on what you think is easy.

What I did:
1. Rewrote all theme options in Kirki manually to the same IDs as I had in OptionTree
2. Ran a replace-all **ot_get_option** with **get_theme_mod** in the theme dir
3. Fixed all get_theme_mod functions in templates to have a default value where needed

It took me 1.5-3 hours per theme I think, feels good to be done with it.

**Comment by anthonyryanrusso** [comment]
Ok that's what I needed to know.  I appreciate the feedback, guess I will get started on this conversion.
