### ISSUE TITLE
Dashicons not working in repeater?

### ISSUE THREAD

**Issue by two-points** [themeum/kirki#1721]
### Issue description:
I tried adding 'dashicons' field in the repeater. It doesn't work. Am I doing anything wrong?

### Version used: 3.0.21
(Did you try using the develop branch from github? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
no, you're not doing anything wrong.
This is not currently supported, repeaters will be able to use more field-types after version 3.1 (currently refactoring everything so that this can work).
It's going to take some time but eventually we'll be able to use any kind of control inside repeaters.
