### ISSUE TITLE
Accessibility issue on radio-buttonset

### ISSUE THREAD

**Issue by michelle-may** [themeum/kirki#1722]
### Issue description:
There is really poor contrast between background and text on the inactive buttons on the radio-buttonset field and does not pass WCAG AA. The text color was previously #555d66 which passes.

**Comment by aristath** [comment]
@macaroons if you create a pull-request for the 'scss file I'd be more than happy to review it and merge it.

**Comment by aristath** [comment]
Fixed in the develop branch, fix will be included in the next release (3.0.23)
