### ISSUE TITLE
Warning: The type attribute for the style element is not needed and should be omitted.

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1724]
Warning: The type attribute for the style element is not needed and should be omitted.

`Warning: The type attribute for the style element is not needed and should be omitted.

From line 36, column 1; to line 36, column 59

=3.0.20">↩<style id='kirki-styles-global-inline-css' type='text/css'>↩.enve`

![_kirki_warning](https://user-images.githubusercontent.com/6827222/34228633-5504490a-e5f7-11e7-8dc2-47fd15854c76.png)

**Comment by aristath** [comment]
This comes from the WordPress [`wp_enqueue_style`](https://developer.wordpress.org/reference/functions/wp_enqueue_style/) function - which is the recommended method to enqueue styles in WordPress. 
The `type` is then added here: https://github.com/WordPress/WordPress/blob/aaf99e691391cfceb004d848450dbbf3344b1bee/wp-includes/class.wp-styles.php#L195
You can use the [`style_loader_tag`](https://developer.wordpress.org/reference/hooks/style_loader_tag/) filter if you want and custom-code something to remove this. though it's not really necessary to remove... and definitely not something that Kirki should do.
