### ISSUE TITLE
Problem under class-kirki-field-color.php

### ISSUE THREAD

**Issue by plannmarketing** [themeum/kirki#1726]
### Issue description:
Hello,
I installed the Kirki plugin on the Wordpress Lifeband theme and as soon as I activated it the following errors are presented in my Wordpress dashboard:

Warning: strpos(): needle is not a string or an integer in /home/plann190/public_html/questaodecoaching/wp-content/plugins/kirki/field/class-kirki-field-color.php on line 60

Warning: Cannot modify header information - headers already sent by (output started at /home/plann190/public_html/questaodecoaching/wp-content/plugins/kirki/field/class-kirki-field-color.php:60) in /home/plann190/public_html/questaodecoaching/wp-admin/includes/misc.php on line 1114

Warning: Cannot modify header information - headers already sent by (output started at /home/plann190/public_html/questaodecoaching/wp-content/plugins/kirki/field/class-kirki-field-color.php:60) in /home/plann190/public_html/questaodecoaching/wp-includes/option.php on line 919

Warning: Cannot modify header information - headers already sent by (output started at /home/plann190/public_html/questaodecoaching/wp-content/plugins/kirki/field/class-kirki-field-color.php:60) in /home/plann190/public_html/questaodecoaching/wp-includes/option.php on line 920

### Version used:
3.0.22

### Using theme_mods or options?
No. I didn't make changes to the plugin.

### Code to reproduce the issue (config + field(s))
-

**Comment by aristath** [comment]
@plannmarketing hey there!

Can you please email me that theme so that I may debug and fix it?
It looks weird, perhaps they are improperly defining the default color... I'll need to check the theme code to see what goes on.

**Comment by aristath** [comment]
Until this is fixed in the theme - or kirki, I don't know which yet - you can hide the error messages: https://aristath.github.io/blog/wp-hide-php-errors

**Comment by iamarif** [comment]
Hi i'm the owner of Lifeband WordPress Theme. When i face the same problem during the installation. I check the php version and upgrade it. After upgrading php version the errors disappear.

But some of the buyers not all of them facing this problem and i suggest to them upgrading the php version and hiding php errors..

If you find a solution about this it'll be very good aristath.

Thanks..

**Comment by aristath** [comment]
@iamarif could you please send me a copy of your theme so that I may check and see what goes on? So far I've been unable to replicate this issue with Kirki and some dummy controls.

**Comment by aristath** [comment]
I just re-read the original post here and this is what gave me a clue about what might be happening:
> Warning: strpos(): needle is not a string or an integer in /home/plann190/public_html/questaodecoaching/wp-content/plugins/kirki/field/class-kirki-field-color.php on line 60

Line 60 in the `class-kirki-field-color.php` file looks like this:
`if ( property_exists( $this, 'default' ) && ! empty( $this->default ) && false === strpos( 'rgba', $this->default ) ) {`

The only reference to `strpos` in that line is `strpos( 'rgba', $this->default )`

The [strpos](http://php.net/manual/en/function.strpos.php) function in PHP is formatted like 
`strpos ( string $haystack , mixed $needle [, int $offset = 0 ] )`

`$needle` is the 2nd argument, and according to the error, "needle is not a string or an integer".
In line 60, `needle` is `$this->default`.

Conclusion: There is something wrong with the default value defined for a color control. It should be a string or integer (in case of a hue-only color control) and it doesn't exist, or is not properly formatted.

@iamarif I don't have your theme to verify this, but perhaps the color control doesn't have a `default` value, or the value is not formatted as a string? Color controls should have default values formatted as per the examples on https://aristath.github.io/kirki/docs/controls/color.html

Closing this ticket, if however the above is not what's happening then please feel free to reopen it and post an update with more details. A link to download the theme that causes this issue - or at least some code to duplicate the error would be helpful.

**Comment by iamarif** [comment]
Hi i check the color controls that i used.. Some default values are empty i'll totaly remove or enter some hex value there..

After this update, if i don't take any error feedback i'll inform you and close this ticket..

Thanks for now

**Comment by thewax** [comment]
Hello, I fixed the issue and created a pull request. Just check type and ensure it's an int or string on line 60 or strpos will fail.

**Comment by iamarif** [comment]
I keep following.. Thanks you @thewax @aristath
