### ISSUE TITLE
Proposal for breaking changes

### ISSUE THREAD

**Issue by JimmyAppelt** [themeum/kirki#1734]
Q: Would it be possible to only include non-breaking changes into patch releases, in the future?

e.g. New: Converted all filter names to use _ instead of / (WPCS) in 3.0.22

Kind regards

**Comment by aristath** [comment]
Hey there!
The filters may have changed, but the old filters still work. (See https://github.com/aristath/kirki/blob/v3.0.22/deprecated/filters.php). It wasn't a breaking change, nothing should be broken! Are you having an issue with an old filter that no longer works? Which one?

**Comment by JimmyAppelt** [comment]
@aristath no Sir! Overlooked this file 😃 my apologies.

**Comment by aristath** [comment]
😌 glad to hear that.
Happy 2018!

**Comment by JimmyAppelt** [comment]
Best wishes @aristath thank you for the amazing development in 2017!
