### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1740]
Hey there,

I know you are "redoing" your documentation over http://aristath.github.io/kirki/docs/ - however a lot of information is still not available for a lot of the controls.

For example, I need to use the spacing, dimensions and the editor controls, but when I go to check out the docs this is what I get: 
spacing: http://aristath.github.io/kirki/docs/controls/spacing.html
editor: http://aristath.github.io/kirki/docs/controls/editor.html
dimensions: http://aristath.github.io/kirki/docs/controls/dimensions.html

Is there a way you can link to the old docs you had before? Maybe provide that link until you get around to getting your new docs done?

**Comment by Alanimus** [comment]
I agree, but you can get to the old docs here: https://web.archive.org/web/20170613214805/http://aristath.github.io:80/kirki/docs/controls/dimension.html

Also, there is an example file in the plugin, though it doesn't have everything: https://github.com/aristath/kirki/blob/develop/example.php

**Comment by tsquez** [comment]
@Alanimus thank you very much, I didn't even think about that. Good move. Helps a lot.

**Comment by notrealdev** [comment]
`dimensions` type live update with multi property
```Kirki::add_field( 'kirki', array(
    'type'        => 'dimensions',
    'settings'    => 'space',
    'label'       => esc_attr__( 'Space', 'kirki' ),
    'section'     => 'header',
    'default'     => array(
        'padding-top'    => '70px',
        'padding-bottom' => '70px',
        'margin-top'   => '0px',
        'margin-bottom'  => '70px',
    ),
    'transport' => 'auto',
    'output'     => array(
        array(
            'element' => '.header',
            'property' => 'color',
            // also work with 'property' => 'margin' | 'property' => 'padding' | 'property' => 'any_property' although 'dimensions' is 'padding' and 'margin'
        )
    ),
    'active_callback'  => array(
        array(
            'setting'  => 'c_header',
            'operator' => '==',
            'value'    => '1',
        ),
    )
));
```
but not working if no property set

**Comment by aristath** [comment]
@notrealdev are you still having an issue? If yes then please create a separate ticket since what you're describing has nothing to do with the original post.

**Comment by notrealdev** [comment]
Thank you, this issue has been resolved
