### ISSUE TITLE
active_callback no longer works with option_type = option?

### ISSUE THREAD

**Issue by akosipau** [themeum/kirki#1745]
### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by coleh33** [comment]
I also am seeing the same issue after updating to the latest develop branch.  The required argument no longer is working.

**Comment by stylethemes** [comment]
same problem here after updating to the latest wp.org version

**Comment by pagelab** [comment]
Also happening when `option_type` is `checkbox`

**Comment by aristath** [comment]
I just pushed a commit that should fix this, can you please check the develop branch? Thanks!

**Comment by stylethemes** [comment]
I actually did solve it without the develop branch I just did replace the value in the active_callback from on to  1 and it did work

note: I'm working with the last wp.org version
