### ISSUE TITLE
Spacing Control CSS

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1749]
This is a suggestion, not an issue.

When using your `spacing control` this is what it looks like:

https://i.imgur.com/YwIB5jX.png

I adjusted the css for the spacer control to look like this:

https://i.imgur.com/is3xOeT.png

I think it looks better and takes up less real estate. Is there a way you could maybe adjust it in an update to look like the second image?

If you like here is the css I used:

`.customize-control-kirki-dimensions .wrapper{padding:5px 10px 10px 10px!important;}`

Like stated this is just a suggestion, so keep it in mind. If not no biggie

**Comment by aristath** [comment]
Hey again!
I'm afraid I'll have to leave this one as-is... Putting everything on a single row might work on most occasions, but in some cases you might want to use somethink like `calc(4em + 20%)` which wouldn't fit inside the input field if all 4 were in the same row.
Plus not everyone uses all 4 rows... Most scenarios I've seen usually only have top/bottom or left/right. Using all 4 is not that frequent.
