### ISSUE TITLE
Remove Timepicker Option For Date Field

### ISSUE THREAD

**Issue by coleh33** [themeum/kirki#1750]
I updated to the latest develop branch and noticed that an old feature in the customizer has changed when using the date field.  A time choice is now associated with choosing the date, however I do not need that option.  Is there a value that can be passed to disabled the time portion of the date field?  If not, can this feature please be added.

**Comment by aristath** [comment]
Thanks, I missed that part.
Fixed in the develop branch, will be included in the next release.
In the future if someone wants to add time, they can add 
`'choices' => array( 'include_time' => true )`.

**Comment by steve231293** [comment]
Hello @aristath,

I added 'choices' => array( 'include_time' => true ) but date control not show time.

Could you please check it again?
