### ISSUE TITLE
Kirki developer wanted

### ISSUE THREAD

**Issue by romiksk** [themeum/kirki#1753]
### Issue description:

Hi, 

sorry that I post it here, but not able to find anywhere else in forums on the web, but I would need a serious help to convert my existing free wp theme based on Redux to convert to use Kirki for customizer. Is anyone here who could help for a reasonable price? thanks.

**Comment by ghost** [comment]
I can help you, please contact me via vunamhung@gmail.com

**Comment by romiksk** [comment]
I wrote u on your email
