### ISSUE TITLE
Disabling Customize Autosave?

### ISSUE THREAD

**Issue by kodeoagency** [themeum/kirki#1754]
Here is the situation:
I have several controls that are hidden/disabled by active_fallback.
Let's say I have temporarily open these controls while the customizer autosaves the styles. Then I close the customizer without saving. Next time I open the customizer these styles will be applied from the autosaving, even if I don't want to apply them. Now there is no way to get rid of them.
Is there a way to disable the autosave or is there another solution here?

![bildschirmfoto 2018-01-16 um 15 06 50](https://user-images.githubusercontent.com/32045038/34992891-eb6886c2-face-11e7-8607-c3f943369873.png)

**Comment by kodeoagency** [comment]
Seems that autosave revisions were introduced in WP4.9
https://wordpress.org/news/2017/11/wordpress-4-9-release-candidate-3/

**Comment by aristath** [comment]
Yes, I'm afraid this is a feature of WP-Core and we can't change it.

**Comment by kodeoagency** [comment]
Thank you for the feedback
