### ISSUE TITLE
HTML in labels / custom control resulting in strange markup

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1755]
### Issue description:
When you try to use HTML in the labels or custom control it’s resulting in the following markup: 

```
Kirki::add_field( 'options', array(
	'type'     => 'custom',
	'settings' => 'op_post_after_author',
	'label'    => __( '<h3>My HTML</h3><span>Some text</span>' ),
	'section'  => 'post'
) );
```
results in the following markup
```
label
--span
----h3
----span
```
which is kinda not cool (`span` in `span`). Not sure about the solution though.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.17

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
See above

**Comment by aristath** [comment]
## For normal controls:

Kirki follows the same markup as wp-core.
For example the color control in wp-core looks like this: https://github.com/WordPress/WordPress/blob/4.9.2/wp-includes/customize/class-wp-customize-color-control.php#L102-L107 and Kirki does the same thing: https://github.com/aristath/kirki/blob/v3.0.22/controls/views/color.php#L29-L34
If we want to be 100% backwards-compatible and not break styling for everyone - but also be compatible with any styling changes introduced by WP in-core, this will have to stay the same. 

## For custom controls:

You can add whatever markup you want in the `default` argument. Example on https://aristath.github.io/kirki/docs/controls/custom.html
The title still has to remain the same as other controls for visual consistency, so if you need custom markup you can simply remove what you have in the label, leave the label blank, and then add what you want in the `default` argument.
