### ISSUE TITLE
HTML doesn't work anymore in kirki section/field description argument 

### ISSUE THREAD

**Issue by Qodux** [themeum/kirki#1759]
### Issue description:
Hey there,

I use below code in my theme customizer config file and seems to output all HTML tags with HTML entities.  In older versions like 2.3.7, (the one used before) it used to work. 

Also it seems to work if I use the WP native customize_register hook to add sections and controls. I've tested with the latest WP version.

### Version used:
3.0.23

### Code to reproduce the issue (config + field(s))
```
My_Theme_Customizer::add_section( 'my_theme_custom_css', array(
	'title'       => esc_html__( 'Custom CSS', 'my_theme' ),
	'priority'    => 130,
	'description' => sprintf( '%s<br /><a href="%s" class="external-link" target="_blank">%s<span class="screen-reader-text">%s</span></a>',
		esc_html__( 'CSS allows you to customize the appearance and layout of your site with code. Separate CSS is saved for each of your themes.', 'my_theme' ),
		esc_url( __( 'https://codex.wordpress.org/Know_Your_Sources#CSS', 'my_theme' ) ),
		esc_html__( 'Learn more about CSS', 'my_theme' ),
		esc_html__( '(link opens in a new window)', 'my_theme' )
	), 
) );
```

**Comment by aristath** [comment]
Can you please try the develop branch from this repo? I just pushed a commit that should fix this

**Comment by Qodux** [comment]
Thanks a lot, it's working.
