### ISSUE TITLE
All my pulgins got error!!!

### ISSUE THREAD

**Issue by dashpatel21** [themeum/kirki#1766]
The plugin redux-framework/redux-framework.php has been deactivated due to an error: Plugin file does not exist...... and all such all my plugins got stopper working and everything goes in wrong way.

Hope anyone could help me out.

**Comment by aristath** [comment]
And why exactly are you posting an error you got from the redux plugin in the repository for the kirki plugin?
Sounds like perhaps the plugin was deleted via FTP or something like that.
Closing this ticket as invalid since it has nothing to do with this plugin.
