### ISSUE TITLE
Updated Kirki issues

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1769]
Updated Kirki issues. Fonts have become unstable after the recent updates. Can I get an old version of kirli to test things?

**Comment by aristath** [comment]
You can get previous versions of any plugin from their advanced tab in wordpress.org. for kirki that's on https://wordpress.org/plugins/kirki/advanced/
Could you please elaborate on the "Fonts have become unstable" part? That sentence doesn't provide a lot of info to help me understand and fix the issue if an issue exists...

**Comment by fastmarketo** [comment]
Thanks the problem gets fixed as soon as I used an old version of kirki. Is there a way I can send you some private information(Links) to understand what exactly is the issue?

**Comment by aristath** [comment]
Sure, feel free to send. I'll take a look

**Comment by fastmarketo** [comment]
I am creating a GIF to explain the issue and sending you the information on your Gmail.

**Comment by fastmarketo** [comment]
Hi there, I have sent you a GIF you can see that after the update the fonts are not loading correctly. I am using Roboto for all h tags. Some extra boldness is coming. it is also not taking the previous color settings.
For example it is not taking this color → 
![_color_sett](https://user-images.githubusercontent.com/6827222/35276143-60f183dc-0068-11e8-8103-267d9ccd1e28.png)

**Comment by fastmarketo** [comment]
the latest update of version: 3.0.25 seems to have fixed the issue.
