### ISSUE TITLE
Radio button styling when line breaks

### ISSUE THREAD

**Issue by peterhadorn** [themeum/kirki#177]
The radio buttons overlap if they're too long for a line:

![scr1](https://cloud.githubusercontent.com/assets/2341912/7036733/24a56056-dd98-11e4-9221-eecb12b58149.jpg)

![scr2](https://cloud.githubusercontent.com/assets/2341912/7036736/28e9c9d6-dd98-11e4-99b0-e3fe5be2f9af.jpg)

**Comment by aristath** [comment]
Thanks!
