### ISSUE TITLE
typography control error

### ISSUE THREAD

**Issue by S-Harabara** [themeum/kirki#1770]
### Issue description:
kirki typography control error

### Version used:
3.0.24

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'option', [
    'type'        => 'typography',
    'settings'    => 'typo_global',
    'label'       => 'Base theme font',
    'section'     =>'typography',
    'transport'   => 'auto',
    'default'     => [
        'font-family'    => 'Open Sans',
        'variant'        => '700',
    ]
]);
```
Request URL:http://wp-unishop.loc/wp-admin/admin-ajax.php
Request Method:POST
Status Code:400 Bad Request
Remote Address:127.0.0.1:80
Referrer Policy:same-origin

action: kirki_fonts_google_all_get
action: kirki_fonts_standard_all_get

This problem reproduce if kirki directly embed in my theme,  if i use kirki as plugin control typography working normally.

**Comment by aristath** [comment]
Please try v3.0.25 released just a couple of minutes ago.

**Comment by S-Harabara** [comment]
I tested kirki v3.0.25 problem still exist.

**Comment by aristath** [comment]
@S-Harabara I'm still unable to replicate this issue.
Can you please provide some more details? Are you by any chance adding kirki inside an action? Perhaps the fields get added too late?

**Comment by timelsass** [comment]
Hi ari I came across this issue as well.  It appears to work fine if theme is the active theme, but i get the 400 errors when I set another theme(twentyseventeen) as the active theme then preview the theme with kirki embedded in the customizer.  I noticed the nopriv hook had a typo and submitted a PR #1840 for that.  The changes don't appear to fix the issue in re-testing this out though.

**Comment by S-Harabara** [comment]
My problem was that I hid the kiri connection under the is_customize_preview condition. When the request for admin-ajax.php is_customize_preview returns false, the handlers are not registered and wordpress returns an error.
