### ISSUE TITLE
v.3.0.24 $force_load_all_subsets

### ISSUE THREAD

**Issue by Micemade** [themeum/kirki#1771]
### Issue description:
After 3.0.24 update I got this error:
_Fatal error: Uncaught Error: Access to undeclared static property: Kirki_Fonts_Google::$force_load_all_subsets ... _

### Version used:
3.0.24 wp.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
This is function I used to load all subsets:
```
function mytheme_font_add_all_subsets() {
	if ( class_exists('Kirki_Fonts_Google') ) {
		Kirki_Fonts_Google::$force_load_all_subsets = true;
	}
}
add_action('wp', 'mytheme_font_add_all_subsets');
```
Any ideas ? Was the `$force_load_all_subsets` removed for good ?
Thanks

**Comment by aristath** [comment]
> Was the $force_load_all_subsets removed for good ?

Yes, it was. It is no longer necessary.
However I added it back in https://github.com/aristath/kirki/commit/0feec4b39bcdfce857d40ab80d63f3f1245ff7c2 and also pushed that change to the 3.0.25 version on wordpress.org to avoid any issues with users that are updating.

**Comment by Micemade** [comment]
Thanks for quick 3.0.25 release, before I was swamped with "broken theme" support ... ;) 👍
