### ISSUE TITLE
Image field - partial_refresh does not work with save_as => array

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#1774]
### Issue description:
partial_refresh does not work with save_as => array (image field). If I change 'save_as' from 'array' to 'id' - partial_refresh works

### Version used:
Tested 3.0.13 and 3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
	Kirki::add_field('site_logo', array(
		'type'        => 'image',
		'settings'    => 'site_logo',
		'label'       => __('Site logo'),
		'section'     => 'logo',
		'priority'    => 10,
		'transport'	  => 'auto', 
		'choices'     => array(
			'save_as' => 'array',
			),
		'partial_refresh' => array(
			'partial_refresh_site_logo' => array(
				'selector'        => '#main_header',
				'render_callback' => 'header_builder_logo',
				),
			),
			
		));

```

**Comment by rabindratharu** [comment]
Issue description:

js_vars output  does not work with `save_as => 'id'`. If I remove the `'choices'   => array(  'save_as' => 'id' )` and save image as url then js_vars output works fine.

Version used:
Tested up to: 4.9.2
Stable tag: 3.0.14 ( Plugin Files )

Using theme_mods or options?
theme_mods

Code to reproduce the issue (config + field(s))
	/*--------------------------------------------------------------
# Section Background Image Control
--------------------------------------------------------------*/
```
Kirki::add_field( 'the-business_config', array(
    'type'          => 'image',
    'settings'      => 'the-business_homepage_counter_section_bg_image',
    'label'         => esc_attr__( 'Background Image', 'the-business' ),
    'section'       => 'the-business_homepage_counter_section_settings',
    'transport'     => 'postMessage',
    'choices'     => array(
        'save_as' => 'id',
    ),
    'js_vars'       =>  array(
        array(
            'element'   =>  array( '.counters-wrap' ),
            'function'  =>  'css',
            'property'  =>  'background-image'
        )
    ),
    'output'        =>  array(
        array(
            'element'   =>  array( '.counters-wrap' ),
            'function'  =>  'css',
            'property'  =>  'background-image'
        )
    )
));
```

**Comment by DannyCooper** [comment]
@rabindratharu isn't that expected, as you are effectively passing an ID to `js_vars` instead of a background-image URL?

**Comment by mapsteps** [comment]
We have worked on issues related to this recently and this should work fine with the upcoming v4 release.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
