### ISSUE TITLE
Typography Control: Choose 'Sans Serif' as default

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1779]
How could I load the font stack "Sans Serif" as default?

I tried following arguments:

```php
array(
  'type'     => 'typography',
  'settings' => $textdomain . '_typography_body',
  'label'    => __( 'Body', $textdomain ),
  'section'  => $textdomain . '_typography',
  'priority' => 10,
  'default'  => array(
    'font-family' => 'Sans Serif', // Also tried 'sans-serif' keyword as described in documentation.
    'variant'     => '400',
    'font-size'   => '1rem',
    'line-height' => '1.5',
    'color'       => '#333',
  ),
  'output' => array(
    array(
      'element' => 'body',
    ),
  ),
)
```

Kirki creates the styles exactly as I pass them to it. So it ignores the keyword 'Sans Serif' and writes it as-is into the css output.

It would be great to hand over the keyword 'Sans Serif' to load this stack as default – since 'sans-serif' is reserved by CSS.

I use the newest version of Kirki (via Plugin) and WordPress.

**Comment by Khoapq** [comment]
`add_filter( 'kirki/fonts/standard_fonts', 'khoapq_filter_standard_fonts' );

function khoapq_filter_standard_fonts( $standard_fonts ) {
		$standard_fonts = array(
			'serif'      => array(
				'label' => 'Serif',
				'stack' => 'Georgia, Times, Times New Roman, serif',
			),
			'sans-serif' => array(
				'label' => 'Sans Serif',
				'stack' => '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen-Sans, Ubuntu, Cantarell, Helvetica Neue, sans-serif',
			),
			'monospace'  => array(
				'label' => 'Monospace',
				'stack' => 'Monaco, Lucida Sans Typewriter, Lucida Typewriter, Courier New, Courier, monospace',
			),
		);

		return $standard_fonts;
	}`

**Comment by Khoapq** [comment]
Hi,


I found a solution, you can follow these step.

edit and add scripts below to functions.php in your theme:

```
add_filter( 'kirki/fonts/standard_fonts', 'khoapq_filter_standard_fonts'  );

function khoapq_filter_standard_fonts( $standard_fonts ) {
		$standard_fonts = array(
			'serif'      => array(
				'label' => 'Serif',
				'stack' => 'Georgia, Times, Times New Roman, serif',
			),
			'sans-serif' => array(
				'label' => 'Sans Serif',
				'stack' => '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen-Sans, Ubuntu, Cantarell, Helvetica Neue, sans-serif',
			),
			'monospace'  => array(
				'label' => 'Monospace',
				'stack' => 'Monaco, Lucida Sans Typewriter, Lucida Typewriter, Courier New, Courier, monospace',
			),
		);

		return $standard_fonts;
	}
```

**Comment by DannyCooper** [comment]
This is possible without using any filters, but it's not obvious.

You need to use the vales from the 'Standard Fonts' select as the default.
```
<optgroup label="Standard Fonts">
	
		<option value="Georgia,Times,&quot;Times New Roman&quot;,serif">Serif</option>
		<option value="-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif" selected="">Sans Serif</option>
		<option value="Monaco,&quot;Lucida Sans Typewriter&quot;,&quot;Lucida Typewriter&quot;,&quot;Courier New&quot;,Courier,monospace">Monospace</option>
	
</optgroup>
```

So your control would look something like this:

```
'default' => array(
	'font-family' => '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif',
),
```
