### ISSUE TITLE
Dimensions Control: transport 'auto' not updating live preview

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1780]
I added a dimensions control using following attributes. It works well with transport on default value. But with `transport => auto`, the live preview won't update. And it would be nicer to have the control updates it's labels with the `choices` array values. This is what is being created:

<img src="https://user-images.githubusercontent.com/34842497/35474655-bd8d9910-0391-11e8-9538-c6ee502b8bc2.png" width="250">

```php
array(
  'type'      => 'dimensions',
  'settings'  => $textdomain . '_max_width',
  'label'     => __( 'Max Width', $textdomain ),
  'section'   => $textdomain . '_layout',
  'transport' => 'auto',
  'priority'  => 10,
  'choices'   => array(
    'sm' => esc_attr__( 'Small', $textdomain ),
    'md' => esc_attr__( 'Medium', $textdomain ),
    'lg' => esc_attr__( 'Large', $textdomain ),
    'xl' => esc_attr__( 'X-Large', $textdomain ),
  ),
  'output'    => array(
    array(
      'choice'      => 'sm',
      'element'     => '.container',
      'property'    => 'max-width',
      'media_query' => '@media (min-width: 576px)',
    ),
    array(
      'choice'      => 'md',
      'element'     => '.container',
      'property'    => 'max-width',
      'media_query' => '@media (min-width: 768px)',
    ),
    array(
      'choice'      => 'lg',
      'element'     => '.container',
      'property'    => 'max-width',
      'media_query' => '@media (min-width: 992px)',
    ),
    array(
      'choice'      => 'xl',
      'element'     => '.container',
      'property'    => 'max-width',
      'media_query' => '@media (min-width: 1200px)',
    ),
  ),
  'default' => array(
    'sm' => '540px',
    'md' => '720px',
    'lg' => '960px',
    'xl' => '1140px',
  ),
)
```

As always: Latest Kirki plugin and WordPress.

**Comment by wowthemesnet** [comment]
It may be too late , but for anyone seeing this, reverse the order of the output because xl always overrides.

So it should be something like this:

~~~~
'output'    => array(
    array(
      'choice'      => 'xl',
      'element'     => '.article-headline',
      'property'    => 'font-size',
      'media_query' => '@media (max-width: 1800px)',
    ),
          array(
      'choice'      => 'lg',
      'element'     => '.article-headline',
      'property'    => 'font-size',
      'media_query' => '@media (max-width: 992px)',
    ),
          array(
      'choice'      => 'md',
      'element'     => '.article-headline',
      'property'    => 'font-size',
      'media_query' => '@media (max-width: 768px)',
    ),
         array(
      'choice'      => 'sm',
      'element'     => '.article-headline',
      'property'    => 'font-size',
      'media_query' => '@media (max-width: 576px)',
    ),
  ),
~~~~

**Comment by codebygina** [comment]
I used `'transport' => 'refresh',` and reversed the order of the output arrays (xl,lg,md,sm).

It worked for me.

**Comment by aristath** [comment]
@crstnio fixed the bug, it now works OK.
Please test the develop branch, you should no longer have any issues with this.
Keep in mind that the develop branch is a complete rewrite of the postMessage module which handles the `auto` outputs, so please make sure you test all your theme's fields to make sure there are no more issues as this is planned for release next week.

As for the labels, check out the docs on https://aristath.github.io/kirki/docs/controls/dimensions.html
They should be in a `labels` key under `choices`.
