### ISSUE TITLE
Color Palette: Active color before section title

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1782]
A small one.

The `z-index: 99` for `.customize-control-kirki-color-palette .colors-wrapper input:checked + label .color-palette-color` is way too high. It displays before section title: `z-index: 9`.

Since the same issue exists with Iris color picker handle, I suggest setting `#customize-controls .customize-info.is-in-view, #customize-controls .customize-section-title.is-in-view` to a higher `z-index` value to fix both issues.

Color Palette:

<img src="https://user-images.githubusercontent.com/34842497/35480019-94fcaf76-0405-11e8-979e-1d30253104b1.png" width="250">

Iris color picker:

<img src="https://user-images.githubusercontent.com/34842497/35480020-95191d28-0405-11e8-8414-d9ce8d22af9f.png" width="250">

**Comment by aristath** [comment]
Good catch 👍 
Fixed in the develop branch, will be included in v3.0.26
