### ISSUE TITLE
Feature request: Exclude default from output

### ISSUE THREAD

**Issue by michelle-may** [themeum/kirki#1785]
Is there any way, or would it be possible to have a setting where the default option would automatically be excluded from every field with output? 

I am excluding the output on every setting in my customizer as it just creates a duplication of the CSS that is already in my base stylesheet. It would be nice if there was some single setting to tell Kirki to exclude the default on every output.

**Comment by aristath** [comment]
@macaroons There is no constant you can define.
Each output can accept an `exclude` argument, so if you want you can just add the values you want to exclude in there. See https://aristath.github.io/kirki/docs/modules/css.html#exclude for more details.

If you want to automate that, then with some basic PHP you can create a proxy function and do what you want.
I haven't tested this, but just to get an idea of the logic you could use in a proxy function, you could do something like this:

```php
/**
 * Proxy function.
 *
 * @param array $args The field arguments.
 * @return void
 */
my_theme_add_kirki_field( $args = array() ) {
	$config_id = 'my_config';
	if ( isset( $args['output'] ) && isset( $args['default'] ) ) {
		foreach ( $args['output'] as $key => $output ) {
			if ( ! isset( $output['exclude'] ) ) {
				$output['exclude'] = array( $args['default'] );
			}
			$args['output'][ $key ] = $output;
		}
	}
	Kirki::add_field( $config_id, $args );
}
```
