### ISSUE TITLE
FontAwesome JS is being loaded even if you don't need it on front end

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#1786]
In v3.0.25, I found that you include FontAwesome js file on front end. I can find any reason why it is necessary to include FontAwesome js on front end. The script is included even if my pages don't have any FontAwesome elements inside. Why?

**Comment by aristath** [comment]
You're right, this was a bug.
Fixed now in develop branch, icons are only loaded when there's a fontawesome field.
