### ISSUE TITLE
Required arguments don't work (several field types)

### ISSUE THREAD

**Issue by peterhadorn** [themeum/kirki#179]
I tested several field types and could not get the required arguments to work in any of them in 0.8.4 (select, toggle, switch, radio). The fields are always visible no matter which field type or value I try. Not sure if it's the same issue as #171 as that related only to the radio buttons?

Using this example syntax for the required arguments:

```
    'required' => array(
        array(
            'setting'  => 'my_layout',
            'operator' => '==',
            'value'    => 'option_1'
        ),
    ),
```

**Comment by aristath** [comment]
We're working on it now, we should have it working by the end of the day. :)
the `required` argument is still a bit experimental (that's why it's not it the docs too).

**Comment by peterhadorn** [comment]
Great, thanks for the update. Will be happy to test again

**Comment by aristath** [comment]
I believe this has been fixed on the master branch, can you please check it again?

**Comment by peterhadorn** [comment]
works perfectly, thanks :)

**Comment by aristath** [comment]
Awesome!

I'm finally closing this issue. :+1: 
Thanks for checking!
