### ISSUE TITLE
Multiple option for radio-buttonset

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1790]
I don't see anything in your example file or docs about a multiple option for radio-buttonset, is this a thing or can you add this functionality?

I know there is a multicheck field but that is visually unappealing.

E.g. for radio-buttonset multi: http://nimb.ws/sq1uo5

**Comment by aristath** [comment]
That's a great idea! Basically it will be a clone of the multicheck field with just different CSS, so pretty easy to do.
Adding as a feature request and assigning it to the 3.0.26 milestone since I'll probably make this one in time 👍

**Comment by anthonyryanrusso** [comment]
Awesome, looking forward to this as well!

**Comment by aristath** [comment]
I just pushed a commit that makes styling the multicheck control the way you want it.

If you use the development branch you can now add something like this to style the control to look the way you want it:
```php
/**
 * This function adds some styles to the WordPress Customizer
 */
function my_customizer_styles() { ?>
	<style>
	.customize-control-kirki-multicheck ul {
	  display: flex;
	}

	.customize-control-kirki-multicheck ul li {
	  width: 100%;
	}

	.customize-control-kirki-multicheck ul li label {
	  background: rgba(0, 0, 0, 0.1);
	  border: 1px rgba(0, 0, 0, 0.1);
	  color: #555d66;
	  margin: 0;
	  text-align: center;
	  padding: 0.5em 1em;
	  display: block;
	}

	.customize-control-kirki-multicheck ul li label.checked {
	  background-color: #00a0d2;
	  color: rgba(255, 255, 255, 0.8);
	}

	.customize-control-kirki-multicheck ul li input {
	  display: none;
	}
	</style>
	<?php
}
add_action( 'customize_controls_print_styles', 'my_customizer_styles', 999 );
```
Of course you can tweak the CSS above to your liking and make the control look exactly the way you want it to.

**Comment by anthonyryanrusso** [comment]
There is an issue with comparing arrays with required, I have attached two files I had to modify to fix the issue. Can you implement this fix or a similar one please.

The changes that were made have "//Added" by them in each file.

class-kirki-helper.php - https://ufile.io/fhkrm
field-dependencies.js - https://ufile.io/5vmly

**Comment by anthonyryanrusso** [comment]
@aristath Any feedback on this?

**Comment by aristath** [comment]
@anthonyryanrusso can you please check the latest develop branch? Some changes were pushed today from https://github.com/aristath/kirki/issues/1825 that _should_ fix this

**Comment by anthonyryanrusso** [comment]
I don't see any issues with this anymore.

**Comment by aristath** [comment]
Thanks for checking!
