### ISSUE TITLE
Remove button not showing on image control on first image load.

### ISSUE THREAD

**Issue by Alanimus** [themeum/kirki#1792]
### Issue description:
Image control issue: If there is no default image assigned, the first time you load an image with the control the "remove image" button does not appear (it's set to "hidden).
![capture](https://user-images.githubusercontent.com/1911237/35833092-95abf956-0a84-11e8-8549-e619ffc9bd9c.PNG)

### Version used:
Latest dev

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

``` /* Jumbotron Image Upload */
	Kirki::add_field( 'my_child', array(
		'type'        => 'image',
		'settings'    => 'gm_jumbotron_image_upload',
		'label'           => esc_attr__( 'Upload an image for single image background', 'mytheme' ),
		'description' => esc_attr__('Recommended min width 1900 for full, 1200 for boxed layout', 'mytheme'),
		'section'     => 'gm_jumbotron_style',
		'default'     => '',
		'active_callback' => array(
			array(
				'setting'  => 'gm_jumbotron_select',
				'operator' => 'in',
				'value'    => 'image',
			),
		),
	) );
```

**Comment by aristath** [comment]
This is weird....
I can't replicate it using this: https://github.com/aristath/kirki/blob/e21b42e022cd34973eae9ab90e519c361cfa11d0/example.php#L488-L493

Can you please test this by adding in your wp-config.php this line:
```php
define( 'KIRKI_TEST', true );
```
and then test using the develop branch?
It seems to be working fine on my end 😕

**Comment by Alanimus** [comment]
Is there something else that could control the remove button hiding? I commented out all the removeButton.hide() and the conditionals on removeButton.show() but still, the button doesn't show until a page refresh.

I've circled in red how it's fine after the page refresh.

And yea it is doing it on the test version as well: 

![capture](https://user-images.githubusercontent.com/1911237/35884391-6897347e-0b3f-11e8-927f-406023deb8e5.PNG)

**Comment by Alanimus** [comment]
Unfortunately I've never used Underscore (JS) templates but if I remove this: `<# if ( '' === url ) { #> hidden <# } #>` from line 75 in class-kirki-control-image.php the button works properly.

**Comment by aristath** [comment]
Just an update, I still can't replicate this issue in the latest dev version

**Comment by DannyCooper** [comment]
Unable to replicate in `develop` or `master`. The authors implementation may be causing this as a side effect of something else.
