### ISSUE TITLE
Border field

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1793]
Do you have to build your own border field?  I haven't seen anything in the docs that show that type of control.  Is this an upcoming feature?

E.g. http://nimb.ws/hQmazk

**Comment by aristath** [comment]
tbh I think in the 4 years of this plugin this has only been requested once or twice and so it never was a priority.
I'm adding this as a feature request and I'll see if I can squeeze it in a release soon.
For the time being yes, you'd have to build it on your own by adding separate fields.

**Comment by anthonyryanrusso** [comment]
Understandable, looking forward to this control!

**Comment by ArekZw** [comment]
I would also like to use this field.
But I think that border radius should not necessarily be part of this field. Sometimes users do not want a borders, but they want radius background. Webdevs know how it works, but end users sometimes do not know.

**Comment by aristath** [comment]
Just a note, complex fields like this will be easier with Kirki v4.0, so once that is released you can expect all kinds of new things. Building fields using other controls will be pretty easy.
