### ISSUE TITLE
Spacing Control: live preview not working when there are two items only (4 items is good)

### ISSUE THREAD

**Issue by themenow** [themeum/kirki#1798]
### Issue description:

A spacing control contains 2 items ('top' and 'bottom' in my case) wouldn't update live preview,  whether transport is 'auto' or 'postMessage'. I can see changes after saving and refresh though.

At first I thought all spacing controls had issue, then I found those spacing controls with 4 items updates well.

I then changed one of good spacing control from 4 items ( top, bottom, left, right) to 2 items (top, bottom), reloaded the customizer and it stopped updating live preview.

```
Kirki::add_field('theme',  array(
    'section' => $section,
    'settings' => $prefix . '_padding',
    'label' => esc_html__('Sidebar Padding', 'theme'),
    'type' => 'spacing',
    'default'     => array(
        'top'    => '0px',
        'bottom' => '0px',
    ),
    'transport' => 'auto',
    'output' => array(
        array(
            'element' => '.sidebar-1',
            'property' => 'padding',
        ),
    ),
));
```

### Version used:

3.0.25

### Using theme_mods or options?

theme_mods

**Comment by aristath** [comment]
@themenow I just tested this with the develop branch and I can't replicate the issue, can you please try the develop branch from this repository instead of v3.0.25 and let me know if that fixes the issue for you?

**Comment by DannyCooper** [comment]
The `dimensions` control (of which `spacing` is an alias) does seem to be the most inconsistent. Neither of these work in develop:
```
Kirki::add_field(
	'prefix_config',
	array(
		'section'   => 'title_tagline',
		'settings'  => 'header_padding',
		'label'     => esc_html__( 'Header Padding', 'kirki' ),
		'type'      => 'dimensions',
		'transport' => 'auto',
		'default'   => array(
			'padding-top'    => '0px',
			'padding-bottom' => '0px',
			'padding-left'   => '0px',
			'padding-right'  => '0px',
		),
		'output'    => array(
			array(
				'element' => '.site-header',
			),
		),
	)
);
```
```
Kirki::add_field(
	'prefix_config',
	array(
		'section'   => 'title_tagline',
		'settings'  => 'header_padding',
		'label'     => esc_html__( 'Header Padding', 'kirki' ),
		'type'      => 'dimensions',
		'transport' => 'auto',
		'default'   => array(
			'top'    => '0px',
			'bottom' => '0px',
			'left'   => '0px',
			'right'  => '0px',
		),
		'output'    => array(
			array(
				'element'  => '.site-header',
				'property' => 'padding',
			),
		),
	)
);
```

**Comment by aristath** [comment]
I believe this was fixed earlier today in the develop branch with commits https://github.com/kirki-framework/field-dimensions/commit/7d169b131978de91aeafdbfef97a81a079ebbe4f & https://github.com/kirki-framework/field-dimensions/commit/1a634b6c9765703c3a284cf4a7b3420bef5d31b3
