### ISSUE TITLE
Section and Field Adding

### ISSUE THREAD

**Issue by PremalathaKumar** [themeum/kirki#1799]
Is there a way to add a field in Panel without adding sections? 
and I have another problem. While adding inline element in Kirki, (typography, background settings) 
the style couldn't add in the frontend. 

Could you please help me with these.
Thank you!

**Comment by aristath** [comment]
> Is there a way to add a field in Panel without adding sections?

I'm afraid not, the way the customizer is built in WordPress currently doesn't allow adding controls to panels. Controls can only be added to sections.
However, if you want you could try adding a section like this:
```php
Kirki::add_section( 'expanded_section_in_panel_general_settings', array(
	'title' => __( 'General Settings', 'caramelomedia' ),
	'panel' => 'general',
	'type'  => 'expanded',
) );
```

> While adding inline element in Kirki, (typography, background settings)
the style couldn't add in the frontend.

I'm afraid I'll need more info than that

**Comment by DannyCooper** [comment]
Closing as the primary issue is not possible.
