### ISSUE TITLE
Undefined variable: option_name & default after update from 0.8.3 to 0.8.4

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#180]
```
( ! ) Notice: Undefined variable: option_name in C:\wamp\www\wp\wp-content\themes\new\lib\kirki\includes\Helpers\helpers.php on line 78
( ! ) Notice: Undefined variable: default in C:\wamp\www\wp\wp-content\themes\new\lib\kirki\includes\Helpers\helpers.php on line 78
```

why below lines were deleted from lines 93 & 94 of includes\Helpers\helpers.php (ver 0.8.3)?!

``` php
    $option_name  = $fields[$option]['settings'];
    $default      = $fields[$option]['default'];
```

**Comment by aristath** [comment]
Hey there!

Can you please try using the master branch and let me know if this still occurs?
I can't replicate this issue...

Can you also post your configuration here?
Are you using `'option'` as the `'options_type'` in your config?

**Comment by DevelopOnline** [comment]
Hi,
After update to master branch, I still see the following message:

```
 ( ! ) Notice: Undefined variable: default in C:\wamp\www\wp\wp-content\themes\new\lib\kirki\includes\Helpers\helpers.php on line 78
```

I use default `options_type` : `theme_mod`

**Comment by aristath** [comment]
Thanks for checking!

Should be fixed now. :+1:

**Comment by DevelopOnline** [comment]
Nice :+1:
