### ISSUE TITLE
Custom font in typography field

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1800]
Hi Ari!

How can I add custom font in typography field?

**Comment by aristath** [comment]
@vlthemes I'm afraid at the moment this is not possible. It's planned for v3.1 but until then other that custom-coding something I can't offer any easy solutions.
There's another ticket for allowing custom APIs and custom fonts in the typography control so I'll go ahead and close this one as a duplicate.
This will be implemented and is on my to-do list 👍

**Comment by aristath** [comment]
actually check out this one: https://github.com/aristath/kirki/issues/1807#issuecomment-372140472
Just added that implementation a few minutes ago 👍
