### ISSUE TITLE
Can we output CSS to a file? [Question]

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#1803]
### Issue description:
Is it possible to grab the CSS from the output argument and export it to a file? I've been digging through the source and thought it would be faster to ask.

**Comment by ArekZw** [comment]
Look: https://github.com/aristath/kirki/issues/1323#issuecomment-301876440

**Comment by aristath** [comment]
@CaptJiggly you can do it as @ArekZw pointed out using the filter.
However, please note that the filters have been renamed to be consistent with the WordPress Coding Standards, so instead of `'kirki/dynamic_css/method'` you should use `'kirki_dynamic_css_method'`:
```php
add_filter( 'kirki_dynamic_css_method', function() {
    return 'file';
} );
```
