### ISSUE TITLE
How can I use "sortable" between my fontend code

### ISSUE THREAD

**Issue by wowwwai** [themeum/kirki#1804]
I am a beginner of  kirki,
But I don't know how to use  "sortable" to sort the elements at fontend，
Where can I get  a fontend template of   "sortable"  control

Thanks

**Comment by aristath** [comment]
@wowwwai I just added an example on http://aristath.github.io/kirki/docs/controls/sortable.html

**Comment by BeholdPL** [comment]
Hi. Link from above is missing. Can I ask for sample usage of sortable also?

Thanks!
