### ISSUE TITLE
js_vars vs partial_refresh

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1805]
### Issue description:
Should we use js_vars or partial_refresh because both do same thing.

partial_refresh:: It Adds Visual Edit Shortcode but take time to appear setting value

js_vars:: It Does not Add Visual Edit Shortcode but value display quickly.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Latest

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

	<?php

	// It Adds Visual Edit Shortcode but take time to appear setting value
	Kirki::add_field( 'config_id', array(
		'type'        => 'editor',
		'settings'    => 'setting',
		'label'       => esc_attr__( 'Content', 'textdomain' ),
		'section'     => 'section_id',
		'default'     => '',
		'transport' => 'postMessage',
		'partial_refresh' => array(
			'footer_left' => array(
				'selector'        => '.classname',
				'render_callback' => function() {
					return get_theme_mod( 'setting' );
				},
			),
		),
	) );

	// It Does not Add Visual Edit Shortcode but value display quickly.
	Kirki::add_field( 'config_id', array(
		'type'        => 'editor',
		'settings'    => 'setting',
		'label'       => esc_attr__( 'Content', 'textdomain' ),
		'section'     => 'section_id',
		'default'     => '',
		'transport' => 'postMessage',
		'js_vars'   => array(
			array(
				'element'  => '.classname',
				'function' => 'html',
			),
		),
	) );

**Comment by aristath** [comment]
It's really just a matter of preference.... The rule I personally try to follow is this:

* CSS changes: instant (`output` arg + `transport` set to `auto`.
* element classes & attributes changes: instant (`js_vars`)
* If a template-part changes markup: partial-refresh
* If the whole page changes markup: refresh
