### ISSUE TITLE
Extend Kirki to metaboxes

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1806]
Is there a way to extend Kirki to metaboxes for individual page options or have you thought about adding this capability?

**Comment by rinkuyadav999** [comment]
@anthonyryanrusso No, kirki does not have API for Meta Boxes. https://github.com/aristath/kirki/issues/1548

**Comment by anthonyryanrusso** [comment]
I appreciate the issue tag, I searched for something similar but didn't use the correct keyword.
