### ISSUE TITLE
Background control type

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1808]
I think the background control type should output the "background-color" property as just "background" if there is no image.  The reason I say this is if you give the user a choice between two options "regular/gradient" and the gradient uses the "background" or "background-image" property then it will override "background-color" on hover.

**Comment by anthonyryanrusso** [comment]
Disregard this as it was a cache issue in customizer.

**Comment by anthonyryanrusso** [comment]
@aristath Any feedback on this?

**Comment by aristath** [comment]
I don't understand the "2 options" part, could you please elaborate?

**Comment by anthonyryanrusso** [comment]
No problem.  Here is a video showing that if social media icon anchors are set as a gradient which uses "background-image" and you set the anchor hover as a regular "background-color" it doesn't do anything since "background-image" is superior to "background-color".

E.g. http://nimb.ws/d6fi9x

**Comment by aristath** [comment]
Pushed a fix for this.
