### ISSUE TITLE
file_get_contents() is currently block on w.org themes

### ISSUE THREAD

**Issue by grappler** [themeum/kirki#181]
Kirki uses `file_get_contents()` in [FontRegistry.php#L256](https://github.com/aristath/kirki/blob/master/includes/Fonts/FontRegistry.php#L256). The theme checker blocks it as it could be used to load malicious code.

I reported the issue on the issue tracker for the theme checker. https://github.com/Otto42/theme-check/issues/55

I hope to bring this up at the next Theme Review Meeting on the Tuesday 21st April at 19:00 UTC. I thought I would inform you and hope to get some feedback before I do.

**Comment by aristath** [comment]
Well, in this case all we get is the list of GoogleFonts via json...
I suppose we could do it using `$wp_filesystem`

Let me experiment with that a bit, hopefully I'll have it fixed within the hour. :)

**Comment by aristath** [comment]
done. :) Now using $wp_filesystem.

**Comment by aristath** [comment]
I'll include this in the next release in a few days, in the meantime you can instruct that theme author to use the master branch. :+1:

**Comment by grappler** [comment]
Thanks! It not a problem. The theme author just removed the file as they did not need the google fonts. I am surprised how fast you are but I suppose we both work around the same time :smile:

**Comment by aristath** [comment]
Yeah, we probably both work long hours... plus I really want to make this THE best option available out there for extending the customizer.

Your remarks and issues you create are really helpful!
