### ISSUE TITLE
image field inside repeater

### ISSUE THREAD

**Issue by stylethemes** [themeum/kirki#1810]
### Issue description:

hey so im having a problem with image inside the repeater so i have a text a link and an image both text and link work fine but image link doesn't echo well so I'm just asking how to get the output of an image inside a repeater 
im folwing the same codes from the documentation

### Version used:
latest ver from wp.org

### Using theme_mods or options?
theme_mods
### Code to reproduce the issue (config + field(s))
the same code from documentation link and text work fine but image doesn't help is much appreciated

**Comment by stylethemes** [comment]
please guys i really need help

**Comment by stylethemes** [comment]
customizer code
<pre>
stylethemes_Kirki::add_section( 'featured_boxes_section', array(
        'title'      => esc_attr__( 'Featured Boxes', 'consultme' ),
        'priority'   => 4,
        'panel' => 'theme_settings',
        'capability' => 'edit_theme_options',
	));

    stylethemes_Kirki::add_field( 'consultme', array(
        'type'        => 'toggle',
        'settings'    => 'featured_boxes',
        'label'       => esc_attr__( 'Enable Featured Boxes', 'authentic' ),
        'section'     => 'featured_boxes_section',
        'default'     => false,
        'priority'    => 10,
    ) );

    stylethemes_Kirki::add_field( 'consultme', array(
        'type'        => 'image',
        'settings'    => 'featured_boxesimage',
        'label'       => esc_attr__( 'Enable Featured Boxes', 'authentic' ),
        'section'     => 'featured_boxes_section',
        'default'     => '',
        'priority'    => 1,
    ) );
	
    stylethemes_Kirki::add_field( 'consultme', array(
        'type'        => 'repeater',
        'label'       => esc_attr__( 'Featured Boxe', 'consultme' ),
        'section'     => 'featured_boxes_section',
        'priority'    => 3,
        'row_label' => array(
            'type' => 'text',
            'value' => esc_attr__('Featured Boxes', 'consultme' ),
        ),
        'settings'    => 'featured_boxes_repeater',
        'choices' => array(
            'limit' => 3
        ),
        'active_callback' => array(
            array(
                'setting'  => 'featured_boxes',
                'operator' => '==',
                'value'    => true,
                ),
        ),
        'default'     => array(
            array(
                'featured_boxe_title' => esc_attr__( 'Stories', 'consultme' ),
                'featured_boxe_link'  => esc_url('#', 'consultme'),
                'featured_boxe_img' => esc_url('#', 'consultme'),
            ),
            array(
                'featured_boxe_title' => esc_attr__( 'shop', 'consultme' ),
                'featured_boxe_link'  => esc_url('#', 'consultme'),
                'featured_boxe_img' => esc_url('#', 'consultme'),
            ),
            array(
                'featured_boxe_title' => esc_attr__( 'insta', 'consultme' ),
                'featured_boxe_link'  => esc_url('#', 'consultme'),
                'featured_boxe_img' => esc_url('#', 'consultme'),
            ),
        ),
        'fields' => array(
            'featured_boxe_title' => array(
                'type'        => 'text',
                'label'       => esc_attr__( 'Featured Boxe Title', 'consultme' ),
                'default'     => '',
            ),
            'featured_boxe_link' => array(
                'type'        => 'text',
                'label'       => esc_attr__( 'Featured Boxe Link', 'consultme' ),
                'default'     => '',
            ),
            'featured_boxe_img' => array(
                'type'        => 'image',
                'label'       => esc_attr__( 'Featured Boxes image', 'consultme' ),
                'description' => esc_attr__( 'Upload Featured Boxes image', 'consultme' ),
                'default'     => '',
            ),
        )
    ));
</pre>

**Comment by stylethemes** [comment]
output code please click to zoom image
![php3](https://user-images.githubusercontent.com/26869625/36493460-960fd638-1727-11e8-9857-47a1df5f7cd1.png)

**Comment by stylethemes** [comment]
ok so, i did find an answer here's in case someone looking for it use
 
`<?php echo wp_get_attachment_url( $featured_box['featured_boxe_img'] ); ?>`

**Comment by aristath** [comment]
@stylethemes I'm sorry I didn't see this one sooner.
unfortunately images inside repeaters save the ID instead of the URL. I'm glad you managed to find a solution to this... Yes, using `wp_get_attachment_url()` is the way to go 👍

**Comment by besimdauti** [comment]
Hi, I have a same problem echo image from repeater. I have only two fields in my project, image_client field and link_url field. Url field is working fine but image not.
Here is my code, if you can help me I appreciate it

`
my_config_kirki_add_field(

	array(

		'type'        => 'repeater',

		'label'       => esc_html__( 'Repeater Control', 'kcdf' ),

		'section'     => 'clients_section',

		'row_label' => [

			'type'  => 'text',

			'value' => esc_html__( 'Client', 'kcdf' ),

		],

		'button_label' => esc_html__('Add new Client (optional)', 'kcdf' ),

		'settings'     => 'clients_setting',

		'fields' => [

			'image_client' => [

				'type'        => 'image',

				'label'       => esc_html__( 'Client Image', 'kcdf' ),

				'description' => esc_attr__( 'Upload Client Image', 'kcdf' ),

			],

			'link_url'  => [

				'type'        => 'text',

				'label'       => esc_html__( 'Client Link URL', 'kcdf' ),

				'description' => esc_html__( 'This will be the link URL of Client', 'kcdf' ),

			],

		]

	)

);

`
also here is the code i want to display

`

$clients = get_theme_mod( 'clients_setting'); 
        ?>
        <div class="clients-box owl-wrapper">
					
            <div class="owl-carousel">
                <?php foreach( $clients as $client ) : ?>
                <div class="item">
                    <div class="image-holder">
                        <a href="<?php echo $client['link_url']; ?>" target="_blank">
                            <?php echo wp_get_attachment_url( $client['image_client'] ); ?>
                        </a>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
`

**Comment by KlbTheme** [comment]
Try this;


<pre>$image = ! wp_attachment_is_image($client['image_client']) ? $client['image_client'] : wp_get_attachment_url($client['image_client']);</pre>

**Comment by diptonath** [comment]
Check This:

Kirki Repeater Setting
https://postimg.cc/Hr6yFV1d

HTML display setting
https://postimg.cc/2L3jtFhf

**Comment by sumonrst** [comment]
$fields[] = [
        'type'     => 'repeater',
        'label'    => esc_html__( 'Gallery Image', 'dustrilox' ),
        'section'  => 'header_side_setting',
        'row_label'    => [
            'type'  => 'text',
            'value' => esc_html__( 'Select Your Image', 'dustrilox' ),
    ],

    'button_label' => esc_html__( 'Add New Image', 'dustrilox' ),
    'settings'  =>'dustrilox_side_img',
    'fields'    =>[
        'dustrilox_g_img'  =>[
            'type'      =>'image',
            'label'    => esc_html__( 'Gallery Image', 'dustrilox' ),
        ]
    ]

];


=============================
How to show frontend
<div class="sidebar__img d-none d-lg-block mb-20">
                  <div class="row gx-2">
                     <?php foreach($dustrilox_side_img as $image) : ?>
                     <div class="col-4">
                        <div class="sidebar__single-img w-img mb-10">
                           <a class="popup-image" href="<?php echo $image['dustrilox_g_img']; ?>">
                              <img src="<?php echo $image['dustrilox_g_img']; ?>" alt="">
                           </a>
                        </div>
                     </div>
                  <?php endforeach; ?>
                  </div>
               </div>
