### ISSUE TITLE
Possible to add instant preview ( js_vars ) for image type?

### ISSUE THREAD

**Issue by notrealdev** [themeum/kirki#1811]
### Issue description:
Hi, how i can see live preview when using `image` type?
### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Neon_Kirki::add_field( 'neon', array(
    'type'      => 'image',
    'settings'  => 'logo',
    'section'   => 'footer',
    'label' => esc_attr__( 'Logo', 'neon' ),
    'transport' => 'postMessage',
    'js_vars'   => array(
        array(
            'element'  => '.footer-logo',
            'function' => 'html',
            'prefix' => '<img src="',
            'suffix' => '">'
        ),
    ),
));
```

**Comment by aristath** [comment]
If the image is used as a background-image you can do it using `output` and setting `'transport' => 'auto'`.
If you want the image to be used as an element, you may be better off just using a partial refresh.

**Comment by notrealdev** [comment]
Yes, thank you. I will using partial refresh
