### ISSUE TITLE
Is it possible to add CSS class on specific customize control?

### ISSUE THREAD

**Issue by themenow** [themeum/kirki#1812]
Currently the CSS class on a customize control is 

`"customize-control customize-control-kirki-{control type}"`

Is it possible to add some CSS class to a customize control so that changing it to something like 

`"a-special-customize-control customize-control customize-control-kirki-{control type}"`?

**Comment by aristath** [comment]
Why would you want to do that?
You could do it via JS if you enqueue a custom file in the customizer

**Comment by themenow** [comment]
I was trying to create divider lines between controls by CSS,  but I don't want to add them on toggle controls so that they appear closer, still a divider line is needed below the last toggle, a 'last' CSS class is required in this case.

I know divide lines can be created using 'custom' control, which is how I created them before, but I'm avoid doing so now, because when you trying to insert a control with priority, you have to count those existing 'custom' divider lines to figure out the priority needed for insert point, it is weird because they are not actual settings.

**Comment by aristath** [comment]
Why don't you do it via CSS?
You can easily add custom CSS in the customizer using something like this:
```php
add_action( 'customize_controls_print_styles', function() {
	?>
	<style>
		#customize-control-my_setting {
			padding-bottom: 20px;
			margin-bottom: 20px;
			border-bottom: 1px solid #dedede;
		}
	</style>
	<?php
} );
```
