### ISSUE TITLE
Typography line-height normal

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1814]
### Issue description:
Typography control doesn't allow line-height to be set to "normal"

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field($opt_name, array( 
    'label' => esc_html__('H1 heading typography'),
    'section' => 'general_typography_section',
    'settings' => 'h1_heading_typography',
    'type' => 'typography',
    'default' => array(
        'font-family' => 'Open Sans',
        'font-size' => '40px',
        'line-height' => 'normal',
        'text-transform' => 'none',
        'letter-spacing' => '0px',
        'color' => '#777'
    ),
    'output' => array(
        array(
            'element' => 'h1',
            'property' => 'typography'
        )
    )
));
```

**Comment by anthonyryanrusso** [comment]
@aristath Any feedback on this?

**Comment by aristath** [comment]
Isn't normal the same as 1? (Unitless)

**Comment by anthonyryanrusso** [comment]
No unfortunately "1" is not the same as "normal".

> According to the spec, a value of "normal" is not just a single concrete value that is applied to all elements, but rather computes to a "reasonable" value depending on the font size set (or inherited) on the element.

**Comment by aristath** [comment]
Fixed. Problem was with the sanitization function 👍
