### ISSUE TITLE
Nested panels

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1816]
### Issue description:
Having an issue nesting panels.  I am trying to confine my other panels in one global panel but they won't show up unless the 2nd level panel has a section directly attached to it like the "information" panel shown in the video.  If I remove the "information" panel then the global panel does not show up.

e.g. video: http://nimb.ws/IndO2v

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

**Comment by Bdur604** [comment]
If you have idea about Theme Customization API then you can build nested sections using below github link. 
link:  [`Extending WordPress Customizer Panels and Sections to allow nesting`](https://gist.github.com/OriginalEXE/9a6183e09f4cae2f30b006232bb154af)

**Comment by aristath** [comment]
@Bdur604 we already do that. Kirki has nested sections and panels

@anthonyryanrusso I'm afraid that is the only restriction panels and sections have. Panels won't show unless there's a section in them, and sections won't show unless there's a control in them. See https://wordpress.org/support/topic/nested-panels/#post-9906617

You could however just add a dummy section and then hide it via CSS....

**Comment by anthonyryanrusso** [comment]
Yeah that was my next solution, just wanted to hear back from you to know if there was something I was missing.  Thanks.

**Comment by anthonyryanrusso** [comment]
There is an issue with comparing arrays with required, I have attached two files I had to modify to fix the issue.  Can you implement this fix or a similar one please.

The changes that were made have "//Added" by them in each file.

class-kirki-helper.php - https://ufile.io/fhkrm
field-dependencies.js - https://ufile.io/5vmly
