### ISSUE TITLE
[Request] support of post type for dropdown-pages fields

### ISSUE THREAD

**Issue by davidwerks** [themeum/kirki#1820]
### Issue description:

The current dropdown-pages field does not allow us to choose post type. ( wp_dropdown_pages() 's post_type parameter). Any chance that you could possibly add a support for choosing any other post types such as custom post type?

ref: https://aristath.github.io/kirki/docs/controls/dropdown-pages.html
ref: https://codex.wordpress.org/Function_Reference/wp_dropdown_pages
ref: https://github.com/aristath/kirki/blob/7b8c6ffe9c1fe34628d96106cb3487868b471ef3/controls/php/class-kirki-control-repeater.php#L116

### Version used:
Version 3.0.25

**Comment by aristath** [comment]
The `dropdown-pages` control is a verbatim copy of the one from WordPress Core: https://github.com/WordPress/WordPress/blob/4.9.4/wp-includes/class-wp-customize-control.php#L588-L596 so we are not going to add any arguments to that.

If you want to display other post-types you can use a `select` control, and as `choices` use something like this:
```php
`choices` => Kirki_Helper::get_posts( array( 'post_type' => 'my_post_type' ) ),
```
The `Kirki_Helper::get_posts()` method is a simple proxy for the WordPress-Core [`get_posts()`](https://codex.wordpress.org/Template_Tags/get_posts) function, it accepts the same arguments as the `get_posts()` function and all it does is format the results as an `array( 'post-ID' => 'post_title' )` for easier use in controls.

**Comment by kafleg** [comment]
It helped :)
