### ISSUE TITLE
Webfonts memory issue

### ISSUE THREAD

**Issue by sergeysedykh** [themeum/kirki#1822]
### Issue description:

Fatal error: Allowed memory size of 94371840 bytes exhausted (tried to allocate 757760 bytes) in /kirki/modules/webfonts/webfonts.php on line 3

Increasing PHP limits doesn't help :( Any other hints would be greatly appreciated.

Thanks a lot for Kirki!

### Version used:

3.0.16

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Just the default typography fields.

**Comment by aristath** [comment]
@classyentrepreneur hey there!
I see you're using an older version of the plugin... Can you please try updating to the latest stable version (3.0.25 right now)
If that doesn't fix your issue can you try using the develop branch from this repository? There were some improvements there which will be included in v3.0.26

**Comment by sergeysedykh** [comment]
I'll include the later version of Kirki and let you know, if the issue appears again. Many thanks for your efforts!
