### ISSUE TITLE
Don't set variable argument if default value has been set

### ISSUE THREAD

**Issue by emanueljacob** [themeum/kirki#1823]
## What I need:
I need a possibility to dynamically set or unset the "variable" argument of a field. This should depend on wether the default value is set or the value has been manually changed.

## What I Do:
I'am adding some color sections and fields to the wordpress customizer and pass the variables (i.e. '#123456') to a preprocessing compiler (SCSS (Leafo 'scssphp' to be exact)) in order to dynamically create vanilla-css from a frontend css framework like bootstrap (called 'Uikit 3'). I dont use the output argument, and I have written a custom compiler which loops through all variables in order to create SCSS variables and pass them on to the compiler.

I have set the following sections, where the Global Section contains all parent styles, and the Components Section contain all Components Styles. So the Component is prioritized over the Global.

Global colors:
-all fields that store global color values. 
If I set a 'global-link-color', it will have an impact on all child components (ONLY if the child components have NOT been set)

Component colors:
-all fields of a specific component (i.e. [Uikit 3 Section](https://getuikit.com/docs/section)
Even if a Global color has already been set, the Components color has priority.

## The problem:
As soon as I create a components field with a default value this value will be passed on and therefore prioritized over the global value. This should only happen for custom values. 

### This SHOULD happen:
At first the user sets global background to #000000 --> All Backgrounds are black.
At second the user sets the components specific background to #ffffff --> only the background of this component is white, all other backgrounds remain black.

### This ACTUALLY happens:
At first the user sets global background to #000000 --> Some backgrounds are black, but every component with a default value will NOT change because they "think" they have been set. 

## Version used:
Version:       3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_config( 'xite', array(
    'capability'        => 'edit_theme_options',
    'option_type'       => 'theme_mod',
    'disable_output'    => true,
));
```

```php

//****************************************************************************
// Global Backgrounds
//****************************************************************************
Kirki::add_section( 'global_backgrounds', array(
    'title'          => esc_attr__('Background Component', 'xite' ),
    'priority'       => 10,
    'capability'     => 'edit_theme_options',
    'panel'          => 'panel_global_styles',
));

// Fields
// ****************************************************************************
Kirki::add_field( 'xite', array(
    'type'        => 'color',
    'settings'    => 'global_background',
    'label'       => esc_attr__( 'Global Background', 'xite' ),
    'section'     => 'global_backgrounds',
    'default'     => '#EC7A5C',
    'priority'    => 10,
    'variables' => array(
        array(
            'name'     => 'global-background',
        )
    ),
));



//****************************************************************************
// Component Button
// ****************************************************************************
Kirki::add_section( 'component_button', array(
    'title'        => esc_attr__('Button Component', 'xite' ),
    'priority'     => 10,
    'capability'   => 'edit_theme_options',
    'panel'        => 'panel_component_styles',
) );

// Fields
// ****************************************************************************
Kirki::add_field( 'xite', array(
    'type'        => 'color',
    'settings'    => 'button_primary_background',
    'label'       => esc_attr__( 'Button Primary Background', 'xite' ),
    'section'     => 'component_button',
    'default'     => '#ffffff',
    'priority'    => 10,
    'variables'   => array(
        array(
            'name'     => 'button-primary-background',
        )
    ),
));
```

and in my SCSS file, something like that:

```scss
//Button Component
$button-primary-background:    $global-background !default;

.uk-button-primary {
    background-color: $button-primary-background;
}
```

Thanks in advance for your tipps or reviews!

**Comment by aristath** [comment]
@ecksite how are you getting the variables? Are you using `Kirki_Util::get_variables()` to get them? Are you then running a loop of some kind for those variables? One thing that comes to mind without knowing more details about your custom compiler script is that you could add a filter like this:
```php
function my_theme_kirki_values_get_value_filter( $value, $field_id ) {
	// An array of field-IDs and their values that we want to skip.
	$skip_values = array(
		'global_background'         => '#ec7a5c',
		'global_background'         => '#EC7A5C',
		'button_primary_background' => '#ffffff',
		'button_primary_background' => '#FFFFFF',
	);

	// Check if the value of the field is defined in the array defined above.
	foreach ( $skip_values as $key => $val ) {
		if ( $key === $field_id && $val ===$value ) {

			// Set value to null if everything matches.
			$value = null;
		}
	}

	// Return the value.
	return $value;
}
add_filter( 'kirki_values_get_value', 'my_theme_kirki_values_get_value_filter', 10, 2 );
```

This will allow you to check the values, and if it's the default value then the `Kirki_Util::get_variables()` method will return `null` for those fields.
Then in your custom compiler script you can check if `null === $value` to see if it's the default value or not, and it it's null then skip it completely.
I hope the above makes sense... If it doesn't work for you then I'll need more details about your compiler 👍

**Comment by emanueljacob** [comment]
Thank you very much for your quick reply!

Yes, thats exactly what I am doing.

This is actually really smart 😳, I already tried it by doing similar by using a short callback function (the callback should check if the value was default, and in my compiler i wanted to check if its a null value. - that didn't work). Now I see the problem. 

I'll try your approach later. I wanted to create an array of my default values anyway, so this seems to be quite suitable 👍

**Comment by emanueljacob** [comment]
it worked, thank you.

**Comment by emanueljacob** [comment]
@aristath after some tests, I think this is not the best solution.

- all my default variables are already set in the scss file, so i would have to redefine them, which is kind of unnecessary, and actually very time consuming
- i would have to loop through the array of default values n times (where n is the number of my default values), so for each variable (in your filter example)  this would be unnecessarily expensive

I thought, hey, why not setting an empty string as default value and after that hook into 'kirki_values_get_value' in order to skip this variable. And this actually works very well and should be a lot easier. The only problem is, that if I do this, the customizer will not save anymore. 
I think thats because a empty string is not allowed by the color control - am I right here?

Any ideas?

**Comment by aristath** [comment]
> all my default variables are already set in the scss file, so i would have to redefine them, which is kind of unnecessary, and actually very time consuming

You don't have to redefine all your vars, just the ones you override from the customizer. From a quick look at scssphp's docs it looks like you can do that quite easily (http://leafo.github.io/scssphp/docs/#preset-variables)

> i would have to loop through the array of default values n times (where n is the number of my default values), so for each variable (in your filter example) this would be unnecessarily expensive

You could avoid the expensive loop and instead write it like this:
```php
add_filter( 'kirki_values_get_value', function( $value, $field_id ) {
	if ( 'global_background' === $field_id && ( '#ec7a5c' === $value || '#EC7A5C' === $value ) ) {
		return null;
	}
	if ( 'button_primary_background' === $field_id && ( '#ffffff' === $value || '#FFFFFF' === $value ) ) {
		return null;
	}
	return $value;
}, 10, 2 );
```
Of course the above example is impractical if you've got dozens of vars you want to check... However I wouldn't worry so much about the performance part of the loop. After all if it's implemented inside your compiler it's not like it will run on each page load, it will only run when you're saving the customizer options and the compiler is triggered.

> The only problem is, that if I do this, the customizer will not save anymore.
I think thats because a empty string is not allowed by the color control - am I right here?

I just tested this and empty defaults for color controls seem to be working fine on my end.
