### ISSUE TITLE
Intergrated Kirki giving 404 for files

### ISSUE THREAD

**Issue by JakeHenshall** [themeum/kirki#1824]
### Issue description:
I've used the Wordpress.org kirki version within my theme. I seem to be getting lots of 404 issues.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been addressed there)
wordpress.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

Location of Kirki: (app/Kirki)

Location of Kirki Includes: (app/kirki.php)

Contents:
```php
<?php

Kirki::add_config( 'theme_config_id', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

Kirki::add_panel( 'panel_id', array(
    'priority'    => 10,
    'title'       => esc_attr__( 'My Panel', 'textdomain' ),
    'description' => esc_attr__( 'My panel description', 'textdomain' ),
) );

Kirki::add_section( 'section_id', array(
    'title'          => esc_attr__( 'My Section', 'textdomain' ),
    'description'    => esc_attr__( 'My section description.', 'textdomain' ),
    'panel'          => 'panel_id',
    'priority'       => 160,
) );

Kirki::add_field( 'theme_config_id', array(
	'type'        => 'color-palette',
	'settings'    => 'color_palette_setting_0',
	'label'       => esc_attr__( 'Color-Palette', 'textdomain' ),
	'description' => esc_attr__( 'This is a color-palette control', 'textdomain' ),
	'section'     => 'section_id',
	'default'     => '#888888',
	'choices'     => array(
		'colors' => array( '#000000', '#222222', '#444444', '#666666', '#888888', '#aaaaaa', '#cccccc', '#eeeeee', '#ffffff' ),
		'style'  => 'round',
	),
) );
```

Functions.php:
```php
require_once __DIR__ . '/app/Kirki/kirki.php';
require_once __DIR__ . '/app/kirki.php';
```

Issues from Chrome Console:

(anonymous) @ chrome-extension://mpbpobfflnpcgagjijhmgnchggcjblin/content.js:5
selectWoo.css Failed to load resource: the server responded with a status of 404 (Not Found)
kirki.css Failed to load resource: the server responded with a status of 404 (Not Found)
styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
sections.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-migrate.js:23 JQMIGRATE: Migrate is installed with logging active, version 1.4.1
wp-color-picker-alpha.js Failed to load resource: the server responded with a status of 404 (Not Found)
selectWoo.full.js Failed to load resource: the server responded with a status of 404 (Not Found)
script.js Failed to load resource: the server responded with a status of 404 (Not Found)
sections.js Failed to load resource: the server responded with a status of 404 (Not Found)
field-dependencies.js Failed to load resource: the server responded with a status of 404 (Not Found)
icons.js Failed to load resource: the server responded with a status of 404 (Not Found)
tooltip.css Failed to load resource: the server responded with a status of 404 (Not Found)
tooltip.js Failed to load resource: the server responded with a status of 404 (Not Found)
wp-color-picker-alpha.js Failed to load resource: the server responded with a status of 404 (Not Found)
selectWoo.full.js Failed to load resource: the server responded with a status of 404 (Not Found)
script.js Failed to load resource: the server responded with a status of 404 (Not Found)
sections.js Failed to load resource: the server responded with a status of 404 (Not Found)
field-dependencies.js Failed to load resource: the server responded with a status of 404 (Not Found)
icons.js Failed to load resource: the server responded with a status of 404 (Not Found)
tooltip.css Failed to load resource: the server responded with a status of 404 (Not Found)
tooltip.js Failed to load resource: the server responded with a status of 404 (Not Found)
postmessage.js Failed to load resource: the server responded with a status of 404 (Not Found)
kirki-logo.svg Failed to load resource: the server responded with a status of 404 (Not Found)
selectWoo.css Failed to load resource: the server responded with a status of 404 (Not Found)
kirki.css Failed to load resource: the server responded with a status of 404 (Not Found)
styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
sections.css Failed to load resource: the server responded with a status of 404 (Not Found)
tooltip.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by aristath** [comment]
What is the URL it's trying to load and what URL should it be trying to load?
Are you by any chance loading the Kirki files from inside an action instead of directly including the files? If so then that would explain things... Kirki has a filter which runs on `after_setup_theme` which sets up the paths & urls correctly.
If that's not the case then try adding this in your functions.php:

```php
add_action( 'wp_footer', function() {
	var_dump( '
	Theme Path: ' . get_template_directory() );
	var_dump( '
	Theme URL: ' . get_template_directory_uri() );
	var_dump( '
	Kirki Path: ' . Kirki::$path );
	var_dump( '
	Kirki URL: ' . Kirki::$url );
} );
```
The check your footer and paste the results of that here.

**Comment by aristath** [comment]
@JakeHenshall any update on this one?

**Comment by JakeHenshall** [comment]
@aristath I'm using a child theme with a custom WordPress setup that uses 'public->app->themes->theme + (theme-child)'

So I've copied Kirki into the theme-child like the parent theme has it, I can now see the panels but the styling still isn't working.

This is what the files are looking like -> http://framework.local/public/wp/Users/jake/code/theme-child/app/Kirki/assets/vendor/selectWoo/js/selectWoo.full.js?ver=1.0.1

The 'Users/jake/code/' is the directory on my computer.

Pasting in the above code gives me this:

string(71) " Theme Path: /Users/jake/code/framework/public/app/themes/theme-child" string(65) " Theme URL: http://framework.local/public/app/themes/theme-child" string(53) " Kirki Path: /Users/jake/code/theme-child/app/Kirki" string(52) " Kirki URL: /Users/jake/code/theme-child/app/Kirki"

Thanks Jake.

**Comment by DannyCooper** [comment]
@aristath any thoughts based on the output?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
