### ISSUE TITLE
How to style Radio-Image control with width/padding/...

### ISSUE THREAD

**Issue by kevinmamaqi** [themeum/kirki#1827]
### Issue description:
I want to give custom styling to the image-radio control to have a better front-end appearance. For example achieve something like divi theme controls for font: 
![image](https://user-images.githubusercontent.com/972664/37252638-b2f0e868-2524-11e8-866a-425b7d464d5f.png)

### Version used:
Latest from WP

### Using theme_mods or options?
Theme_mods

### Code to reproduce the issue (config + field(s))
basic radio-image control

**Comment by aristath** [comment]
I don't see any radio-image controls in the above screenshots.... the ones in the typography control look more like radio-buttonsets.
If you are familiar with SCSS & compiling that to css, you can find the styles for the controls in https://github.com/aristath/kirki/tree/develop/controls/scss

If you want the compiled CSS you can get it and tweak it from https://github.com/aristath/kirki/blob/develop/controls/css/styles.css

The current styles for radio-buttonset & radio-image controls can be seen on https://github.com/aristath/kirki/blob/314bb4f3330800808d006c2c58457d41f95eaaad/controls/css/styles.css#L249-L302

You can see how to add your own custom CSS to the customizer here: http://aristath.github.io/blog/modifying-wordpress-customizer

**Comment by kevinmamaqi** [comment]
Thank you for your fast reply. The image I uploaded before is an example of what I want to achieve. I am using some svg and this is the appearance I get:

![customizer example](https://user-images.githubusercontent.com/972664/37254731-423ee624-2542-11e8-833f-4f74271df818.png)


I wondered if from the kirki control settings I can set the number of columns or images per row, and so on.

**Comment by aristath** [comment]
No, Kirki does not have option for that. You can do it quite easily via CSS.

Example:
```php
add_action( 'customize_controls_print_styles', function() {
  echo '<style>.customize-control-kirki-radio-image label {width: 40px;}</style>';
} );
```
