### ISSUE TITLE
Kirki_Helper::compare_values contains/in PHP warning if value doesn't exist in array [fix]

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#1828]
### Issue description:
Everything is working great (The simplifying is much more easy on the eyes as well), but there was one little issue I found (One line was needed to be exact).

![array fix](https://user-images.githubusercontent.com/14947514/37254610-08d88cb6-250e-11e8-8211-2d819c3ba192.png)

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

develop-branch

### Using theme_mods or options?

N/A

### Code to reproduce the issue (config + field(s))
The value/default value being an empty array.

**Comment by aristath** [comment]
Good catch, I missed that one! 👍 
Pushed a fix, should be ok now
