### ISSUE TITLE
In fields strings for translation is not translated.

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1829]
### Issue description:
![screenshot_3](https://user-images.githubusercontent.com/32881283/37256118-7b53720c-2567-11e8-9d28-4327a1b37d9c.jpg)

### Version used:
3.0.25 as plugin.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
if ( class_exists( 'Kirki' ) ) {
	Kirki::add_config( 'theme2_kirki', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	) );
}

function theme2_customize_register( $wp_customize ) {
	if ( class_exists( 'Kirki' ) ) {
		Kirki::add_section( 'theme2_footer_info', array(
			'title'          => esc_attr__( 'Footer Info', 'theme2' ),  // IS TRANSLATED
		) );
	};
}
add_action( 'customize_register', 'theme2_customize_register' );

if ( class_exists( 'Kirki' ) ) {
	Kirki::add_field( 'theme2_kirki', array(
		'type'        => 'checkbox',
		'settings'    => 'theme2_display_footer_info',
		'label'       => esc_attr__( 'Display Footer Info', 'theme2' ), // IS NOT TRANSLATED
		'section'     => 'theme2_footer_info',
		'default'     => false,
	) );
}
```

**Comment by aristath** [comment]
I don't think this has anything to do with the Kirki plugin.... Kirki only handles translations for its own strings, not translations for your code.

**Comment by ghost** [comment]
If I create field during 'customize_register' action, translation from .po file is applying, but I see notice about this is incorrect using. If I create field independently, translation from .po file is not applying and notice does not display.
So, how using Kirki plugin can I create fields with titles preparated for translation to different languages?

**Comment by aristath** [comment]
hmmmm.... The only thing I can think of that _might_ cause this is if the fields are added in a plugin, using the textdomain of the theme.

**Comment by ghost** [comment]
Yes, "theme2" is texdomain of my theme. I do something wrong? What texdomain must I use instead of texdomain of my theme?

**Comment by aristath** [comment]
Are you adding those fields in the theme, or in a plugin?
If they are added in the theme there shouldn't be any issues.
I just tested this and when the translations are added in a theme I didn't have any issues.
When I added the translations in a plugin there were a couple of strings that did not get translated.
Adding the fields in the `init` action however fixed it for those few strings that were not getting translated, can you please try that?

**Comment by ghost** [comment]
_Are you adding those fields in the theme, or in a plugin?_
In the theme.
_Adding the fields in the init action however fixed it for those few strings that were not getting translated, can you please try that?_
Yes. It does not work. I did so:
```
function lalala() {
	if ( class_exists( 'Kirki' ) ) {
		Kirki::add_field( 'theme2_kirki', array(
		'type'        => 'checkbox',
		'settings'    => 'theme2_display_footer_info',
		'label'       => esc_attr__( 'Display Footer Info', 'theme2' ), // IS NOT TRANSLATED
		'section'     => 'theme2_footer_info',
		'default'     => false,
	) );
	};
}
add_action( 'init', 'lalala' );
```
Did you mean this?

**Comment by aristath** [comment]
wait.. that can't be... I'm not the only one who uses `lalala`?!?!?!?! 😮 🤣 

Yes that's what I meant. That seemed to work on my example theme...
Can you please send me a copy of your theme so I can test?

**Comment by ghost** [comment]
_wait.. that can't be... I'm not the only one who uses lalala?!?!?!?!_
Yes )))
How can I send copy of my theme to you?

**Comment by ghost** [comment]
Can I use ari*****@gmail.com?

**Comment by aristath** [comment]
Sure

**Comment by ghost** [comment]
We had sent you our theme, but had recieved message "…This message was blocked because its content presents a potential 552-5.7.0 security issue.…". Had you recieved our letter?

**Comment by aristath** [comment]
Sometimes google blocks mails with attachments.
Upload your theme to dropbox/google-drive or something similar and then in your mail just add a link to that so I can get it.
Please also include a link to this ticket so I know what it's for, I get too many emails and it will get lost if a link to this issue is not there

**Comment by ghost** [comment]
We have already sent email. Is all right?

**Comment by aristath** [comment]
I have confirmed that this is indeed an issue, I'm just still looking for a fix. Once I have something I'll post an update here.

**Comment by aristath** [comment]
After spending hours looking for the cause I finally found it.
The problem is in the theme, not the plugin.
You have this:
```php
load_theme_textdomain( 'blogika', get_template_directory_uri() . '/languages' );
```
It should be like this:
```
load_theme_textdomain( 'blogika', get_template_directory() . '/languages' );
```

**Comment by ghost** [comment]
Yes, you are right, but unexpected coincidence had happened while we were waiting for your answer: we had noticed that in theme the translations not related to Kirki are broken. Yesterday and today we were looking for the reason of it and before your answer received we had found the reason (get_template_directory_uri() → get_template_directory()). We also had decided that issue is not in the plugin, but in our theme, but before write you about it, we had checked everything after fixing error. Unfortunately, Kirki still doesn't translate. Had you tried to check Kirki after fixing error in our theme? We appreciate the time you had spent and are confident that time wasn't wasted, because issue1829 is actual. Do you have an example of theme using Kirki, where translation works? Could you send it us for comparison with our theme?

**Comment by ghost** [comment]
I think I understood what the reason is... Do not do anything, just wait until I write, I need to wait for an interpreter.

**Comment by ghost** [comment]
From my side, a complicated story had took place. I had followed your instructions: "Kirki fields should not be added on customize_register." Please add them directly, or on init. ". First, when there was error in our theme (get_template_directory_uri ()), I was adding Kirki fields directly and on init, and the translation did not work.
```
// It does not work directly.
if ( class_exists( 'Kirki' ) ) {
 // fields.
}

// It does not work on init 
if ( class_exists( 'Kirki' ) ) {
 function lalala() {
  // fields.
 }
 add_action( 'init', 'lalala' );
}
```
After fixing error (get_template_directory ()), Kirki fields was still added directly, and the translation did not work still. I did not check on init, because I thought if the first condition from instruction ("directly") is not fulfilled, the second ("on init") will not be fulfilled also.
```
// It does not work directly.
if ( class_exists( 'Kirki' ) ) {
 // fields.
}

// It works on init.
if ( class_exists( 'Kirki' ) ) {
 function lalala() {
  // fields.
 }
 add_action( 'init', 'lalala' );
}
```
There are 2 possible causes:
1. The instruction about "directly" is incorrect, and it is correct about "on init" only.
2. I did not rightly understand what "directly" means.
Please, help to understand what is the reason (item 1 or item 2). Or item 3...?

**Comment by aristath** [comment]
Translations in WordPress become available **after** the textomain gets loaded.
In your `functions.php` the `load_theme_textdomain` function gets added on `after_setup_theme`.
The strings that get added directly are loaded before that action is run, so the translations are not detected.
2 options:
1. Wrap the controls in a function and load it on `init` (which is after `after_setup_theme`) or you can even add them on `after_setup_theme` with a priority like 20.
2. Just take the `load_theme_textdomain` function outside the `after_setup_theme` action and add it directly in your functions.php file. It works fine and is not against the WordPress Best Practices.

Personally I'd go with option 2. It's easier, cleaner and a permanent fix for all text no matter where it's located.

**Comment by ghost** [comment]
Aristeides, thank you very much for your patience and help. We had done as you recommended (opt. 2), and everything is working fine.

We also tried to use "after_setup_theme" and everything was working, but inasmuch as in notice "Kirki fields should not be added on customize_register. Please add them directly, or on init." this event was not mentioned, we did not use this option. We did not even think about to download textdomain directly for solution. Therefore, perhaps, to prevent such situations, you need to supplement this notice and make it like this, for example: "Kirki fields should not be added on customize_register. Please add them directly (if textdomain was loaded directly), or on init or after_setup_theme (if textdomain was loaded on after_setup_theme)."

Thank you again and success to Kirki plugin!

**Comment by aristath** [comment]
Added new ticket on #1835 for new docs about translations. 
Thank you for your feedback and reporting this issue, I'll try to add documentation about this soon 👍
