### ISSUE TITLE
field-dependencies.js issue (fix?)

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#1830]
### Issue description:
The required fields were not working properly in customizer (Everything was visible), so I went digging and found:
`
		var found  = false,
			result = null;
`

IF statements

`
return ( null === result ) ? true : result;
`

I don't see `result` being possibly changed anywhere, so the value will always be the same and return true,

I removed it and replaced it with 

`return value1 == value2;`

Which emulates KrikiHelpers::compare_values

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

develop

### Using theme_mods or options?
N/A

### Code to reproduce the issue (config + field(s))
Any required fields.

**Comment by aristath** [comment]
Makes sense.
I don't remember where that `found` came from, but I pushed the fix. 👍
