### ISSUE TITLE
Editing an existing control

### ISSUE THREAD

**Issue by JeffAspen** [themeum/kirki#1833]
### Issue description:
Is there a way to edit an exiting control? An example would be the Typography control. I want to remove the color picker and add a select field with populated color choices from another field.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.25

### Using theme_mods or options?
theme_mod

**Comment by mapsteps** [comment]
Hey @JeffAspen,

Personally, I use the typography field only for the fonts itself. I've created seperate fields for colors, line-height, etc. for a bit more flexibility.

Hope that helps!

**Comment by niklasp** [comment]
#2026

**Comment by aristath** [comment]
Currently this is not possible, but will probably be after the refactor in v3.1.
Marking as a feature request for the future.
