### ISSUE TITLE
Undefined variable: plugin_install_url in class-kirki-installer-section.php on line 98

### ISSUE THREAD

**Issue by Far-East** [themeum/kirki#1834]

**Comment by aristath** [comment]
Can you please try the version from the develop branch? I just pushed a commit that should fix this.

**Comment by Far-East** [comment]
Thank you, the button appeared, but it does not work. The browser simply updates and nothing happens. The console shows that there is no link on the button.

**Comment by aristath** [comment]
Fixed & tested.

**Comment by Far-East** [comment]
Aristath!!! Great work !!! Thanks for the plugin!
