### ISSUE TITLE
Comma after last item in all arrays

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1836]
### Issue description:
Maybe, it is needed to add a comma, because phpcs always notifies about it and I have to add it by myself.

![screenshot_12](https://user-images.githubusercontent.com/32881283/37559639-70eb9e8e-2a3a-11e8-832f-14f204ca7130.jpg)

### Version used:
Stable tag: 3.0.25

**Comment by aristath** [comment]
I'm assuming you're talking about the docs of the typography field.
Yeah, PHPCS doesn't run for .md files (which is what the docs use) so I missed this.
Pushed a fix 👍

**Comment by ghost** [comment]
Thanks.
