### ISSUE TITLE
Reset to default button no longer available

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#1839]
### Issue description:
Hi Ari, Hope you're well

Did you remove the Reset to default button? or it since WP 4.9.4?

Thanks

### Version used:
v3.0.25

**Comment by anthonyryanrusso** [comment]
Yes it was removed.

https://github.com/aristath/kirki/issues/1600

**Comment by aristath** [comment]
@Serpentsoft what @anthonyryanrusso said above is accurate. reset was removed in v3.0.12.
It wasn't working properly and with changesets it's now obsolete
