### ISSUE TITLE
Embeds Font Awesome automatically

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#1841]
### Issue description:
When I enable the plugin, it adds `fa-events-icons-ready` class to `<html>`. Also it embeds Font Awesome related embeds (css, js) automatically. After disabling the plugin, they all go away.

![screenshot 2018-03-09 08 29 44](https://user-images.githubusercontent.com/1418797/37809851-2481ce0a-2e8c-11e8-974a-e62d9ba42e6b.png)
![screenshot 2018-03-09 08 29 53](https://user-images.githubusercontent.com/1418797/37809853-24b44d30-2e8c-11e8-987e-4dd6e5c6a41f.png)
![screenshot 2018-03-09 08 30 24](https://user-images.githubusercontent.com/1418797/37809854-24dde6ae-2e8c-11e8-80cf-bf667bd06312.png)

### Version used:
3.0.25

**Comment by aristath** [comment]
Did you try the develop branch? I believe this has already been fixed and will be included in the next update

**Comment by minimaluminium** [comment]
Just tried the develop branch and it's been fixed there. Sorry about that. Thanks.
