### ISSUE TITLE
Changing multiple property values in the CSS module 

### ISSUE THREAD

**Issue by eirichmond** [themeum/kirki#1842]
### Issue description:
it seems that there is only 1 property value that can be changed in the "output" parameter, in cases were you might want to change 2 or more property values eg: "background: red; & display: block;" is there a way to do that?

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Sure there is...
The output parameter is an array of arrays. Each array inside the output argument can be a completely different set. It's all in https://aristath.github.io/kirki/docs/modules/css.html
