### ISSUE TITLE
Invalid Value in the Dimension control

### ISSUE THREAD

**Issue by sergeysedykh** [themeum/kirki#1844]
### Issue description:

Even if we provide the correct value, like `100px` there's an alert: `Invalid Value`.

The dimension is however applied correctly on the front-end.

### Version used:

Develop branch.

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Just the basic dimension control with default parameters.

**Comment by aristath** [comment]
I saw that too these past few days, just didn't have time to debug it.
I'll check into this today if I find some free time 👍

**Comment by aristath** [comment]
Fixed
