### ISSUE TITLE
Blank page on Post->edit after installing Kirki Toolkit plugin in WP 4.9.4

### ISSUE THREAD

**Issue by Dazzid** [themeum/kirki#1845]
### Issue description:

I'm using a theme called ThemeMountain Sartre, which needs Kirk 
### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Kirki Toolkit plugin in WP 4.9.4

**Comment by aristath** [comment]
@Dazzid could you enable debugging in your wp-config.php file and let me know if you're getting any specific errors? A blank screen could mean anything.
See https://codex.wordpress.org/Debugging_in_WordPress for details on how to enable debugging using WP_DEBUG

**Comment by niklasp** [comment]
#2026 ?

**Comment by aristath** [comment]
Closing this one due to inactivity.
