### ISSUE TITLE
Typography elements - add inherited option

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#1847]
I do not know how to easy describe it. It will be easier in the code:
We have nav and subnav:
<div id="nav">
<ul>
	<li>El1</li>
	<li>El2
		<ul class="subnav">
		<li>SubEl1</li>
		<li>SubEl2</li>
		</ul>
	</li>
</ul>
</nav>

And two typography fields:
nav_typography, subnav_typography.

nav_typography output selector: #nav 
subnav_typography output selector: #nav .subnav

Let's assume that everything (color, font-family, variant, line-height) should be same, but subnawigation should have a smaller font-size.

Currently, we need set all elements in two fields. 

In my proposition, we can switch off elements in typography field, so undefined values will be inherited

Screenshot for nav and subnav example, it's subnav typography field:
![image](https://user-images.githubusercontent.com/11788346/37979174-2dad75ba-31e8-11e8-9710-2e6f2f0e607b.png)
switch on = possibility to change value
switch off = disable field, value is inherited

It can be very useful. I use a lot of typography fields. Typically, the font-family is the same everywhere as in the "general typography field" (where selector is body). But I have to give my client possibility to change so I don't remove font-family from field. Currently, to change everywhere font-family, client must change font-family in all fields. 

In my proposition, I could set inherited value for all font-family fields, but the client could, if necessary, change it.

it significantly facilitates working with many typography fields.

**Comment by aristath** [comment]
have you tried the develop branch? 
In the font-family you can choose `inherit`, `initial`, or even empty (it's labeled as `Default Browser Font-Family`).
If inherit, it will use the font-family of the parent element.
For font-size you can use `em` instead of `px` This way you just change the parent element and all children change accordingly since `em` is a value relative to the parent instead of absolute like `px`.

**Comment by andrastudio** [comment]
Hi @aristath 
Is this inherit, initial and empty font-family value have been merge to master or still in the develop branch?

**Comment by aristath** [comment]
If I'm not mistaken they are in the stable version on w.org
