### ISSUE TITLE
After save image field with save_as => array, it's not possible to change image 

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#1848]
### Issue description:
After save image field with save_as => array, it's not possible to change image 

### Version used:
3.0.25 and dev branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
`		
Kirki::add_field('image_setting_array', array(
			'type'        => 'image',
			'settings'    => 'image_setting_array',
			'label'       => esc_attr__( 'Image Control (array)', 'kirki' ),
			'description' => esc_attr__( 'Description Here.', 'kirki' ),
			'section'     => 'colors',
			'default'     => '',
			'choices'     => array(
				'save_as' => 'array',
				),
			)
		);
`

**Comment by ArekZw** [comment]
I test it with Kirki 3.0.34, the problem still exists

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
