### ISSUE TITLE
Insert customizer codes into an external file

### ISSUE THREAD

**Issue by altemberg** [themeum/kirki#1849]
I would like to insert customizer codes into an external file, other than the functions.php. I created a file called customizer.php inside the Kirki directory, but it does not work. I could not even make the sample codes work, only if I have within the functions.php.

Do I need to enable anything?

**Comment by aristath** [comment]
@altemberg you only need to include that file.
Typically you would do something like 
```php
include_once get_theme_file_path( 'myfile.php' );
```

**Comment by altemberg** [comment]
@aristath It worked! Before I tried to include but it didn't work, I didn't know the get_theme_file_path.

Thanks!
