### ISSUE TITLE
Demo theme with Kirki installed?

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#185]
Hi Aris,

Are there any themes that are running Kirki out there so I can seethe use of panels and sections? I looked through your repo to see if you had any light weight starter with Kirki already included, but didn't see anything.

Or if you know of a premium or free theme that has this embeded I will like to take a look.

Ciaran

**Comment by aristath** [comment]
Hey there!

I'm working on a simple demo theme based on twentyfifteen...
I should have it finished today and I'll post it here. :)

**Comment by ghost** [comment]
Thanks for that mate. Have decided in my infinite wisdom to start a theme today using underscores bootstrap and Kirki. Been a very long time since I tried Kirki, and finding it intuitive to include/embed. That is until I create the options.php file.

Maybe you can shed light on this so I can keep going.

I have used your Gist for the demo settings from [here](https://gist.github.com/aristath/d778d2592a4a6ce8f640)

Then I get right away the fatal error:

Fatal error: Cannot redeclare kirki_demo_configuration_sample() (previously declared in C:\Users\cmwwebfx\Documents\Websites\www.smartstart.dev\wp-content\themes\smartstart\admin\customizer-kirki.php:9) in C:\Users\cmwwebfx\Documents\Websites\www.smartstart.dev\wp-content\themes\smartstart\admin\options.php on line 602

BTW, I looked at Maera today, looks like an awesome framework to start from, but will be out of my depth.

**Comment by aristath** [comment]
Looks like you have the demo functions in 2 places:
1. wp-content\themes\smartstart\admin\customizer-kirki.php
2. wp-content\themes\smartstart\admin\options.php

Just delete one of them...

As for Maera it's actually simpler than it looks! It does take some getting used to, but it's totally worth it.

**Comment by ghost** [comment]
If there was some videos for Maera to assist in getting started and the workings I would have taken the plunge a few times already. 

Thank you for pointing out the double up, all sorted now and itching to get going.

**Comment by ghost** [comment]
By the way, if there was a video series on Maera, I would gladly buy it for at least $100, then buy into the extensions. Am I right in thinking we can use Maera to build commercial themes for themeforest? Are there any out there with this framework already?

**Comment by aristath** [comment]
I was planning to do some tutorial videos on Maera and I will as soon as possible.
The only reason I haven't done so already is time limitations.

I'll get around to it.... :) and they'll be free.

And yes, you can build commercial themes with it for themeforest.
I haven't seen any yet

**Comment by ghost** [comment]
Awesome, really looking forward to it. And thank you for letting me know I can build a commercial theme with it.

**Comment by aristath** [comment]
Demo on the twentytwelve theme: https://github.com/aristath/twentytwelve-kirki

The only problem right now is not adding the options, but finding what options to add. :)
You can take a look at it if you want.
Just install the Kirki plugin from the repository, activate it, and then activate the theme. 

Any additional requests for that theme please make them on its separate repository.

I'll just go ahead and close this one, trying to clean up the issues list. :+1:

**Comment by ghost** [comment]
Thanks for creating this. I will update the readme.md and Wiki to include this info.
