### ISSUE TITLE
How to refresh/regenerate CSS file via a custom function?

### ISSUE THREAD

**Issue by munirkamal** [themeum/kirki#1853]
### Issue description:

Hi @aristath,

I am using the static file generation method for the CSS. It works fine, but I need to trigger refresh/regenerate the file linked to a certain option in my theme.

Is there a certain function to trigger this? I see currently it happens when we save/publish customizer options. 

TIA,
Munir

**Comment by DannyCooper** [comment]
Kirki no longer generates files for CSS so this can be closed.
