### ISSUE TITLE
Changing static css filename to use page name

### ISSUE THREAD

**Issue by themenow** [themeum/kirki#1855]
### Issue description:

Currently the filename is the same across all pages, when it is cached in user browser, or there is a CDN in front of the server, client will receive always the css for the first page, thus mess up other pages.

### Version used:

3.0.25

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

```
add_filter( 'kirki/dynamic_css/method', function() {
    return 'file';
});
```

**Comment by DannyCooper** [comment]
Kirki now loads the CSS inline so this is no longer an issue.
