### ISSUE TITLE
Kirki Toolkit crash upon plug-in activation

### ISSUE THREAD

**Issue by villa-verde** [themeum/kirki#1856]
### Issue description: 
Upon Kirki Toolkit plug-in activation in Wordpress, the whole screen is covered with the attached error messages
Also the website crashes. II had to deactivate the plug-in

<img width="1233" alt="kirki-crash" src="https://user-images.githubusercontent.com/38298412/38641183-c08775da-3dd6-11e8-9fef-38bb9a3e133d.png">

### Version used:
Kirki Toolkit Version: 3.0.25
Wordpress: Version: 4.9.4 and 4.9.5 
Simple Theme from Nimbus Themes - Powered by WordPress

**Comment by aristath** [comment]
The errors displayed are a clear indication of what went wrong there... The theme is abviously using deprecated syntax for some of its controls.
Please contact the theme author about this, the syntax that should be used is documented on https://aristath.github.io/kirki/docs/controls/color.html#adding-an-rgba-colorpicker

**Comment by srinivas3399** [comment]
i have installed this kirki plugin in my client website [fixpie](https://www.fixpie.com/) its completely crashed.
