### ISSUE TITLE
Fatal error: Class 'Kirki_Init' not found

### ISSUE THREAD

**Issue by abides** [themeum/kirki#1858]
im getting Fatal error: Class 'Kirki_Init' not found in /public_html/wp-content/plugins/kirki/core/class-kirki.php on line 26

when i try to activate plugin, new installation from plugins menu in wordpress.

version 3.0.25
webserver nginx
php 7.0 fpm

**Comment by aristath** [comment]
That's extremely weird... perhaps something went wrong with the plugin installation? I'm using it on nginx+fpm servers without any issues and so are dozens of other people, this has never been reported before.
Any customizations that could possibly affect the paths where plugins get installed or something similar?

**Comment by abides** [comment]
Hello there,

I send you an email with address and username and admin password. I cant believe it either and i just install clean wp for test just for this plugin. I try lots of things, default nginx config, defaul php, fpm config but cant found anything. Somehow autoload module does not load the php files without any errors even on /var/log/ error files and this error is only what i got.

Best regards.

**Comment by medabkari** [comment]
Hello @abides , i'm Currently Facing the same problem as you, Please Can You Tell Me how did you Solve i, so i can move on, actually i tried everything i had on mind and nothing got me out of this .

**Comment by abides** [comment]
I didnt get any help on this channel about this issue, so i try to update that ubuntu server to latest package version then i realized its 16.10 and its not support update anymore so i couldnt update. It seems, person who setup the system get wrong image for production server. I rebuild the system with Ubuntu 16.04.4 LTS and upgrade to latest packages. Then issue gone.

**Comment by niklasp** [comment]
close #2026

**Comment by aristath** [comment]
Closing this one as there have been no recent reports of any issues.
