### ISSUE TITLE
Editor control work with repeater control?

### ISSUE THREAD

**Issue by gordo019** [themeum/kirki#1860]
### Issue description:
Can I use the repeater control with the editor control. In other words, Each instance of my repeater control would have maybe a text field and a editor field. I have been successful creating a repeater control with each instance having a text field and a textarea field but not with a text field and a editor field.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) No

**Comment by ArekZw** [comment]
Currently editor field are not supported in repeater. List of supported fields in repeater is here: #652

**Comment by gordo019** [comment]
Thanks @aristath!
