### ISSUE TITLE
repeater control with HTML field

### ISSUE THREAD

**Issue by gordo019** [themeum/kirki#1861]
### Issue description:
I need a repeating control with at least one field that accepts and will display HTML code. Is this possible with Kirki?

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by ArekZw** [comment]
Currently, it's not possible. Here is list supported fields in repeater: #652
@aristath mentioned that he plans to add support for new fields in future versions of Kirki (#1846)

**Comment by niklasp** [comment]
close #2026
