### ISSUE TITLE
How to display controls before sections?

### ISSUE THREAD

**Issue by applesapples1** [themeum/kirki#1863]
I am using a nested section and would like to output the control before the section panels, but it only seems to be able to output below, and changing the priority doesn't help. Is there any way around this? I am using current version. Thanks! Kate

**Comment by aristath** [comment]
I'm afraid not, the order in which things get rendered in WP is sections first, controls later. Marking this one as a feature request so I can take a look and see if there's a way around it

**Comment by surajv** [comment]
Hi @applesapples1, if you are still looking for the solution, I have found the CSS workaround using flexbox.

You can try this custom CSS:

```
#sub-accordion-section-{parent_section_id} {
    display: flex!important;
    flex-flow: column wrap;
}
#accordion-section-{child_section_id} {
    order: 999;
}
```

**Comment by ariona** [comment]
Just add section without giving panel property. it should be viewed as panel then you can add setting.
```php
Kirki::add_section( 'some_setting', array(
  'title' => esc_html__('Some setting','kirki'),
  'priority' => 103
) );
```
