### ISSUE TITLE
Missing google fonts

### ISSUE THREAD

**Issue by sametakdemir** [themeum/kirki#1864]
### Issue description:

Google fonts are missing some fonts. Could you please update it? For example IBM Plex Serif

### Version used:

3.0.25

### Using theme_mods or options?

theme_mods

Thank you for your support

**Comment by sametakdemir** [comment]
or Is this I need to use the method?

'choices' => array(
            'fonts' => array(
                'google' => array(
                    'IBM Plex Serif',
                    'Roboto',
                    'Open Sans',
                    'Lato',
                    'Roboto Condensed',
                    'Slabo 27px',
                    'Montserrat',
                    'Oswald',
                    'Source Sans Pro',
                    'Raleway',
                    'PT Sans',
                    'Merriweather',
                ),
            ),
        ),

**Comment by aristath** [comment]
If you use the develop branch from this repository I just updated the fonts.
As soon as v3.0.26 is released they will also be available on the wordpress.org version

**Comment by niklasp** [comment]
#2026

**Comment by aristath** [comment]
Closing this one as fonts get updated on each release.
