### ISSUE TITLE
Site Title and Description Error

### ISSUE THREAD

**Issue by pubudu7** [themeum/kirki#1865]
### Issue description:
I updated my theme to the 3.0.25 version recently. All were working fine on WordPress 4.9. I found a huge issue today. It is when using WordPress 4.8 we cannot update the site title and description from the customizer. 

<img width="365" alt="screen shot 2018-04-19 at 3 38 45 pm" src="https://user-images.githubusercontent.com/33783695/38985828-1c3d4488-43e8-11e8-8026-8217bf9ccf2a.png">

This is a big issue because according to WordPress stats still 50% of users are not using 4.9. Although it is good to encourage to upgrade to latest WP version it is not good to block default WordPress controls.

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

Thank You.

**Comment by aristath** [comment]
These are not the default WP controls for site-title and description, are they???
Those notices only show for custom code controls in older WP versions, they shouldn't show for any control other than a `code` control created with Kirki!

**Comment by pubudu7** [comment]
Dear Aristeides,

I am 100% sure that these are default WP controls. When submitting themes to WP.org we cannot write custom code for controls like site title and tagline because they are already there.

I checked it on both 4.7 and 4.8. I applied the 3.0.25 version to another free theme which is using kirki. It also did not work on 4.7 and 4.8.

Thank You.

**Comment by pubudu7** [comment]
Installed Kirki 3.0.25 plugin on 4.7 and 4.8. Checked using Twentyseventeen theme. But the problem remains.

<img width="724" alt="screen shot 2018-04-19 at 9 35 04 pm" src="https://user-images.githubusercontent.com/33783695/39003985-ba0ad41a-4419-11e8-83f5-4ca9964cbb7b.png">

**Comment by aristath** [comment]
Marked as a bug and I'll take a look at this ASAP

**Comment by pubudu7** [comment]
It will be great..! Thank you.

**Comment by aristath** [comment]
fixed, will be included in 3.0.26.
I'm currently reviewing some other tickets and I'll release this version today if there are no other big issues reported.
