### ISSUE TITLE
rgba color picker is being displayed if there's no default color

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1868]
### Issue description:
Minor issue, thought it's worth to report it.

I have some color fields where I haven't specified a default color. The color picker here is rgba by default, even if alpha is not declared and set to true.

Setting alpha to false still shows the rgba color picker.

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'theme_prefix', array(
	'type' => 'color',
	'settings' => 'setting',
	'label' => esc_attr__( 'Color', 'textdomain ),
	'section' => 'section',
	'priority' => 0,
	'transport' => 'postMessage',
	'choices' => array(
		'alpha' => false,
	),
	'default' => '#eeeeee'
) );
```

**Comment by DannyCooper** [comment]
Fixed in `develop` branch.
