### ISSUE TITLE
Out of background color is not getting empty when we click clear button for the Background Control

### ISSUE THREAD

**Issue by rabindratharu** [themeum/kirki#1869]
### Issue description:
In `background control` when I click on the clear button the color field, the output is giving previously selected color. But when i used `color control` and apply the output to same HTML element, the output is correct.

### Version used:
Stable tag: 3.0.25 ( Plugin )

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'grace_config', array(
            'type'        => 'background',
            'settings'    => 'grace_archive_page_header_background_setting',
            'section'     => 'grace_archive_page_header_section',
            'default'     => array(
                'background-color'      => '',
                'background-image'      => '',
                'background-repeat'     => 'repeat',
                'background-position'   => 'center center',
                'background-size'       => 'cover',
                'background-attachment' => 'scroll',
            ),
            'transport'     =>  'postMessage',
            'js_vars'       =>  array(
                array(
                    'element'   =>  array( '.archive .page-header' ),
                    'function'  =>  'css',
                    'property'  =>  'background'
                )
            ),
            'output'        =>  array(
                array(
                    'element'   =>  array( '.archive .page-header' ),
                    'function'  =>  'css',
                    'property'  =>  'background'
                )
            )
        ) );
```

**Comment by JiveDig** [comment]
Confirming I see this bug as well, but with the `multicolor` field. 

Here is a simplified example:
```
Kirki::add_field( $config_id, array(
	'type'      => 'multicolor',
	'settings'  => 'primary_nav_color',
	'label'     => __( 'Primary Nav', 'textdomain' ),
	'section'   => 'primary_nav',
	'transport' => 'auto',
	'choices'   => array(
		'menu_bg'   => esc_attr__( 'Background', 'textdomain' ),
		'item_color' => esc_attr__( 'Item Color', 'textdomain' ),

	),
	'default' => array(
		'menu_bg'   => '',
		'item_color' => '',
	),
	'output' => array(
		array(
			'choice'   => 'menu_bg',
			'element'  => '.nav-primary',
			'property' => 'background-color',
		),
		array(
			'choice'   => 'item_color',
			'element'  => '.nav-primary a',
			'property' => 'color',
		),
	);

) );
```

Here are my steps to reproduce:
1. Save any color value into the Background or Item Color fields.
1. Refresh the page/customizer to confirm it saved and is working.
1. Clear the field so it doesn't save any value for that color.
1. Save and refresh the Customizer
You'll see that the previously saved values are still in there and are used for those fields.

**Comment by aristath** [comment]
Marking as a bug, color controls inside background, multicolor & typography fields have some issues and need to be tweaked anyway for #1942 so this will be done at the same time.

**Comment by JiveDig** [comment]
Just to stay organized... this one is not labeled as a bug in GH, though it's been confirmed here ;)
This one is important IMO so don't want it to get lost.

**Comment by DannyCooper** [comment]
> 

> Confirming I see this bug as well, but with the `multicolor` field.
> 
> Here is a simplified example:
> 
> ```
> Kirki::add_field( $config_id, array(
> 	'type'      => 'multicolor',
> 	'settings'  => 'primary_nav_color',
> 	'label'     => __( 'Primary Nav', 'textdomain' ),
> 	'section'   => 'primary_nav',
> 	'transport' => 'auto',
> 	'choices'   => array(
> 		'menu_bg'   => esc_attr__( 'Background', 'textdomain' ),
> 		'item_color' => esc_attr__( 'Item Color', 'textdomain' ),
> 
> 	),
> 	'default' => array(
> 		'menu_bg'   => '',
> 		'item_color' => '',
> 	),
> 	'output' => array(
> 		array(
> 			'choice'   => 'menu_bg',
> 			'element'  => '.nav-primary',
> 			'property' => 'background-color',
> 		),
> 		array(
> 			'choice'   => 'item_color',
> 			'element'  => '.nav-primary a',
> 			'property' => 'color',
> 		),
> 	);
> 
> ) );
> ```
> 
> Here are my steps to reproduce:
> 
> 1. Save any color value into the Background or Item Color fields.
> 2. Refresh the page/customizer to confirm it saved and is working.
> 3. Clear the field so it doesn't save any value for that color.
> 4. Save and refresh the Customizer
>    You'll see that the previously saved values are still in there and are used for those fields.

Thanks for this breakdown, it made it easy to test.

This is in fact broken in `master` and the plugin. However it's fixed in `develop`. Would you mind testing and confirming @JiveDig?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
