### ISSUE TITLE
Feature Request: Search inside Customizer

### ISSUE THREAD

**Issue by badcat** [themeum/kirki#1870]
Would be nice to have some Search function that looks inside Kirki's control sections.  Something along the lines of this - https://wordpress.org/plugins/customizer-search/

thanks for kirki.

**Comment by niklasp** [comment]
add label feature request #2026

**Comment by aristath** [comment]
@badcat If there's already a plugin for that they why add it in Kirki?

**Comment by badcat** [comment]
Maybe because Kirki affords other "Kirki-specific" items that could be searchable and the Customizer Search doesn't "See" the Kirki-specific items.

**Comment by DannyCooper** [comment]
The 'Customizer Search' plugin looks useful, but this doesn't seem like something that would be suitable for the core Kirki Framework.
