### ISSUE TITLE
Import output element from other settings?

### ISSUE THREAD

**Issue by themenow** [themeum/kirki#1872]
I want to do something like:

```
Kirki::add_field('theme',  array(
    'settings' => 'mycolor',
    'type' => 'color',
    'transport' => 'auto',
    'output' => array(
        array(
            'element' => get_setting('mycolor-element'),
            'property' => 'color'
        ),
    )
));
```

A workaround I leanred here is to manually output custom CSS using wp_add_inline_style, but that works only with Refresh, not ideal for a color option.

I found that WP native API has this feature https://wordpress.stackexchange.com/questions/155867/get-entered-value-of-customiser-field-for-live-preview, just wondering if Kirki can generate script like that already before go to write my own preview js.

**Comment by aristath** [comment]
Kirki already supports generating the CSS and works for live-previews too, it auto-generates all scripts needed. Perhaps I'm missing something? Does it not work for you?

**Comment by themenow** [comment]
Yes it generates scripts as needed on pre-defined elements, as following:

```
Kirki::add_field('theme',  array(
    'settings' => 'mycolor',
    'type' => 'color',
    'transport' => 'auto',
    'output' => array(
        array(
            'element' => 'a', // how to accept value of another settings?
            'property' => 'color'
        ),
    )
));
```

here the **element** is pre-defined when registering the setting, if we want to let user control the element, we can add a setting in the Customizer:
```

Kirki::add_field('theme',  array(
    'settings' => 'mycolor-element',
    'type' => 'text',
    'default' => 'a'
));
```

but the problem is, how to pass the value of `'mycolor-element'` to the output **element** of `'mycolor'`? When we change the value of `'mycolor-element'` from **"a"** to **"a, button"**, we'd like to see the button color changed to` 'mycolor' `in the live preview.

**Comment by aristath** [comment]
OK, I see what you mean now.
Right now there is no support for that so it would have to be custom-coded on your part.
There is support to get values of other controls (see the [`pattern_replace`](https://aristath.github.io/kirki/docs/modules/css.html#pattern_replace) argument), but unfortunately it can't be used in the element, only the value.

**Comment by niklasp** [comment]
close #2026
