### ISSUE TITLE
Control Type Toggle Issue

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1875]
### Issue description:

When click on Toggle button, it scroll section to top. expectation: Keep at same position.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

3.0.26

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

1. Add 3-4 typography fields (to appear scroll bar on section) and then add a toggle field.

2. Click on toggle button, it scroll to top.

**Comment by MrAndreius** [comment]
yes, I also have such a bug

**Comment by aristath** [comment]
Marked as a bug

**Comment by aristath** [comment]
I can't replicate this one... Perhaps it's already been resolved in another commit. Can you please try with the develop branch and let me know if this is still an issue? In the meantime I'll go ahead and close this ticket, if it's still an issue just add a comment here and I'll reopen it. :+1:

**Comment by MrAndreius** [comment]
and in other themes he also has
install the latest version of the WordPress
themes add new -> CustomPress theme
activate
the theme will require installing a kirki plugin from the repository
install, activate
open the customiser
go to the header settings
click on the stick header toggle

p.s Win10, Chrome68

**Comment by rinkuyadav999** [comment]
Hi

It is still issue in 3.0.35.2
