### ISSUE TITLE
Multiple-select inside repeater won't display multiple selected values

### ISSUE THREAD

**Issue by asilcetin** [themeum/kirki#1876]
### Issue description:
In a repeater control if you add a "multiple select" and assign multiple values everything seems okay at first. However after you save and refresh the customizer the "multiple select" field will be displayed empty, even though the assigned values are actually saved to the database.

This issue won't happen if you only select one value. The reason is that the condition statement in kirki/controls/php/class-kirki-control-repeater.php is designed only for a single selected value.

### Version used:
Tested with develop-branch and the WordPress.org version

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
In a repeater control inside the fields array I have a "multiple select", added like this:

```
'blocks_post_category_query' => array(
  'type'        => 'select',
  'label'       => esc_attr__( 'Select Categories to Query', 'kirki' ),
  'description' => esc_attr__( 'You may select multiple categories to query your content from.', 'kirki' ),
  'multiple'    => 12,
  'choices'     => array(
    'option-1' => esc_attr__( 'Option 1', 'kirki' ),
    'option-2' => esc_attr__( 'Option 2', 'kirki' ),
    'option-3' => esc_attr__( 'Option 3', 'kirki' ),
    'option-4' => esc_attr__( 'Option 4', 'kirki' ),
    'option-5' => esc_attr__( 'Option 5', 'kirki' ),
  ),
),
```

This field works fine on the customizer at the first glance:
<img width="244" alt="1" src="https://user-images.githubusercontent.com/25176039/39422139-64cf778e-4c6c-11e8-9c2b-3f9df30a413f.png">

Allowing me to select multiple options:
<img width="246" alt="2" src="https://user-images.githubusercontent.com/25176039/39422152-73f60840-4c6c-11e8-93e4-c7fd170ccfda.png">

However after I save and reopen the customizer, this field shows always empty:
<img width="246" alt="3" src="https://user-images.githubusercontent.com/25176039/39422188-9712992e-4c6c-11e8-8121-d0e44744bc5f.png">

After testing many times I can confirm that this issue happens, when multiple options are selected. If you only select one option, save and refresh the customizer you'll see that selected option in the select field. With multiple selected options you'll get an empty field after refresh.

And I can confirm that this issue exists only INSIDE the repeater, if you have a "multiple select" outside the repeater it works fine.

**Comment by aristath** [comment]
Merged the PR, thank you @asilcetin 
I'll be releasing an update later today with this one and a couple of other fixes.

**Comment by ashrafbd1496** [comment]
Hello,
@aristath Multiple select problem is still alive in repeater field. 

'settings'     => 'price_repeater',
	'fields' => [
			'pricing_item_options' => [
			'type'        => 'select',
			'label'       => esc_html__( 'Pricing Item options', 'ashraf_kirki' ),
			'default'     => array('Business Analyzing', '24/7 Tech Suport', 'Operational Excellence'),
			'multiple'	=>12,
			'choices'     => [
				'business-analyzing' => esc_html__( 'Business Analyzing', 'ashraf_kirki' ),
				'tech-support' => esc_html__( '24/7 Tech Suport', 'ashraf_kirki' ),
				'operational-excellence' => esc_html__( 'Operational Excellence', 'ashraf_kirki' ),
				'business-idea' => esc_html__( 'Business Idea Ready', 'ashraf_kirki' ),
				'database' => esc_html__( '2 Database', 'ashraf_kirki' ),
				'customer-support' => esc_html__( 'Customer Support', 'ashraf_kirki' ),
							],

		],
===================

                <?php if ( ! empty( $price ) ) : ?>
                   <ul class="description">
                    <?php foreach ( $price as $selected_option ) : ?>
                      <li><?php echo $selected_option['pricing_item_options']; ?></li>
                    <?php endforeach; ?>
                  </ul>
                <?php endif; ?>

N.B- using foreach inside foreach
