### ISSUE TITLE
Remove development dependencies from "require" section in composer.json

### ISSUE THREAD

**Issue by vladcosorg** [themeum/kirki#1881]
I'm including the plugin as a composer dependency and I've noticed that Kirki loads `php-coveralls/php-coveralls` and `phpunit/phpunit` as a part of non-development dependencies.
Such dependencies are useless in production env therefore they should be excluded and moved/merged to  the "require-dev" section.

**Comment by aristath** [comment]
Should be ok now...
tbh I only use composer to install PHPCS/WPCS etc, so it's not part of my day-to-day workflow and I never bothered to learn more about them. If there's still an issue let me know - or just submit a PR, I'd be more than happy to merge it. 👍
