### ISSUE TITLE
Preset Option dont work

### ISSUE THREAD

**Issue by arsendovlatyan** [themeum/kirki#1882]
### Issue description:
Hi I have the code in my theme which worked early and for some reason started not to work 

### Version used:
version 3.0.27

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))

` Kirki::add_field( "certy_kirki_config", array(

    "type"        => "preset",
    "settings"    => "color_scheme",
    "label"       => __( "Select Predefined Color Scheme", "certy" ),
    "section"     => "color_options",
    "default"     => "designer",
    "priority"    => 10,
    "multiple"    => 0,
    "choices"     => array(
        "designer" => array(
            "label"    => __( "Designer", "certy" ),
            "settings" => array(
                "primary_color" => "#c0e3e7",
                "primary_text_color" => "#010101",
                "main_text_color" => "#010101",
                "muted_text_color" => "#757575",
                "border_color" => "#e1e1e1",
                "shape_color_left" => "#e1e1e1",
                "shape_color_right" => "#c0e3e7",
                "body_color" => "#f3f3f3",
                "paper_color" => "#fff",
                "default_buttons_color" => "#c0e3e7",
                "default_buttons_text_color" => "#010101",
                "secondary_buttons_color" => "#041f28",
                "secondary_buttons_text_color" => "#fff",
            ),        ),    ),) );Kirki::add_field( "certy_kirki_config", array(
    "type"        => "color",
    "settings"    => "primary_color",
    "label"       => __( "Primary Color", "certy" ),
    "section"     => "color_options",
    "priority"    => 10,
    "default"     => "#c0e3e7",
) );`

**Comment by aristath** [comment]
Marking as a bug and I'll be checking into this as soon as I get some free time 👍
