### ISSUE TITLE
Generic fields don't work in repeater

### ISSUE THREAD

**Issue by applesapples1** [themeum/kirki#1885]
### Issue description:
Generic fields do not output when added within a repeater group—not to mention the attributes that I was hoping to use this field type for. All I want is to be able to add placeholders to fields in a group. Is there no other way to do this? Thank you!

### Version used:
3.0.27

**Comment by aristath** [comment]
Right now the repeater fields are pretty limited in their functionality and there's no straight-forward way to do this.
v3.1 will be a rewrite of all fields and at that point repeaters will be able to be a lot more versatile.
For now unfortunately there's not much that can be done here except you cloning the repeater field as a custom field and hard-coding the changes you need.
