### ISSUE TITLE
in type slider not works exclude

### ISSUE THREAD

**Issue by Victorlerner** [themeum/kirki#1886]
### Issue description:
I need when slider is in 0 or 100 not display css for it. now if i set 0 in slider i not see logo because it 0rem.
in output i also tried to insert and also does not work.

I do something wrong or is it a **bug**?

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
yes
Version 3.0.27 \| By Aristeides Stathopoulos \| View details

### Using theme_mods or options?
theme_mods 

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_config( 'kirki_demo', array(
	'capability' => 'edit_theme_options',
	'option_type' => 'theme_mod',
) );

Kirki::add_field( 'kirki_demo', array(
	'type' => 'slider',
	'settings' => 'color',
	'description' => esc_attr__( 'Logo height', 'vetrov' ),
	'label' =>  esc_html__( 'Logo2', 'vetrov' ),
	'section'     => 'logo_section',
	'default'     => 0,
	**'exclude' => array( '0', '100' ),**
	'choices'     => array(
		'min'  => '0',
		'max'  => '100',
		'step' => '1',
	),
	'output' => array(
		array(
			'element' => '.logo img',
			'property' => 'height',
			'value_pattern' => '$rem',

		),
	),
) );
```

**Comment by aristath** [comment]
I didn't have time to test, but try something like this:
```php
'exclude' => array( 0, '0', 100, '100' )
```
I don't recall if sliders save strings or integers/floats, so that may be the issue?

**Comment by Victorlerner** [comment]
thanks for the answer, it helped

now I found new issue

I use this code
```php
Kirki::add_field( 'vetrov', array(
	'type' => 'typography',
	'settings' => 'vetrov_typography_h1',
	'label' => esc_attr__( 'H1', 'vetrov' ),
	'section' => 'vetrov_typography',
	'default' => array(
		'font-family' => 'Poppins, sans-serif',
		'variant' => '500',
		'font-size' => '36px',
		'color' => '',

	),
	'priority' => 10,
	'output' => array(
		'exclude'   => [
			'font-family' => 'Poppins, sans-serif',
			'variant' => '500',
			'font-size' => '36px',
			'color' => '',
		],
		array(
			'element' => '.blog-info h1',
		),
	),
) );
```

but exclude not works here

it's show me css code
`.blog-info h1{font-family:Poppins, sans-serif;font-size:36px;font-weight:500;}`
but I not need display default  css code, how to solve this issue?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
