### ISSUE TITLE
Filter kirki_control_types bug, new control can't render Underscore template

### ISSUE THREAD

**Issue by pkvillanueva** [themeum/kirki#1887]
### Issue description:
I couldn't find my defined JS template in the HTML document. According to this [post](https://make.wordpress.org/core/2014/11/17/jsunderscore-template-rendered-custom-customizer-controls-in-wordpress-4-1/) that in order to render the JS template it has to be registered via `$wp_customize->register_control_type( $control_type );` and I found out that there's an issue with Kirki_Init class. 

The `kirki_control_types` [hook didn't apply](https://github.com/aristath/kirki/blob/a8c445d6e281218e749849af6095710eb81ef8da/core/class-kirki-init.php#L144) the filter I made and after applying this change (http://take.ms/iEZZT), the JS template is successfully rendered.

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
add_action( 'customize_register', function( $wp_customize ) {
	/**
	 * The custom control class
	 */
	class Kirki_Controls_Notice_Control extends Kirki_Control_Base {
		public $type = 'notice';

		public function render_content() {
			?>
			THE CONTROL CONTENT HERE
			<?php
		}

		public function content_template() {
			?>
			FIND ME SOMEWHERE
			<?php
		}
	}

	// Register our custom control with Kirki
	add_filter( 'kirki_control_types', function( $controls ) {
		$controls['notice'] = 'Kirki_Controls_Notice_Control';
		return $controls;
	} );
} );
```

**Comment by niklasp** [comment]
#2026

**Comment by aristath** [comment]
@pkvillanueva I'm sorry for the delay here, I missed this ticket.
Do you still require assistance on this one?

**Comment by pkvillanueva** [comment]
@aristath No, I have solved my issue. Thank you.
