### ISSUE TITLE
Select field on Repeater not working (returning "Array" word)

### ISSUE THREAD

**Issue by tnchuntic** [themeum/kirki#1888]
### Issue description:
Select field on Repeater not working (returning "Array" word)

### Version used:
WP Latest
Kirki Plugin Latest

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
 Kirki::add_section('dynamic_widgets_section', array(
        'title' => esc_attr__('Dynamic Widgets', TEXTDOMAIN),
        'description' => esc_attr__('Allows you to create widget sections.', TEXTDOMAIN),
        'panel' => '',
        'priority' => 160,
    ));

    Kirki::add_field(THEME_CUSTOMISER_ID, array(
        'type' => 'repeater',
        'settings' => 'dynamic_widgets',
        'label' => esc_attr__('Dynamic Widgets', TEXTDOMAIN),
        'section' => 'dynamic_widgets_section',
        'priority' => 10,
        'row_label' => array(
            'type' => 'field',
            'value' => esc_attr__('Dynamic Widget', TEXTDOMAIN),
            'field' => 'widget_name',
        ),
        'button_label' => esc_attr__('Add Dynamic Widget', TEXTDOMAIN),
        'default' => array(
            array(
                'widget_name' => esc_attr__('Sidebar', TEXTDOMAIN),
                'widget_location' => esc_attr__('sidebar', TEXTDOMAIN),
            ),
            array(
                'widget_name' => esc_attr__('Footer', TEXTDOMAIN),
                'widget_location' => esc_attr__('footer', TEXTDOMAIN),
            ),
        ),
        'fields' => array(
            'widget_name' => array(
                'type' => 'text',
                'label' => esc_attr__('Widget Name', TEXTDOMAIN),
                'description' => esc_attr__('Dynamic Widget Name.', TEXTDOMAIN),
                'default' => '',
            ),
            'widget_location' => array(
                'type' => 'select',
                'label' => __('Widget Location', TEXTDOMAIN),
                'description' => esc_attr__('Dynamic Widget Location.', TEXTDOMAIN),
                'default' => 'option-sidebar',
                'priority' => 10,
                'multiple' => 0,
                'choices' => array(
                    'option-header' => esc_attr__('Header', TEXTDOMAIN),
                    'option-content' => esc_attr__('Content', TEXTDOMAIN),
                    'option-sidebar' => esc_attr__('Sidebar', TEXTDOMAIN),
                    'option-footer' => esc_attr__('Footer', TEXTDOMAIN),
                ),
            ),
        )
    ));

**Comment by asilcetin** [comment]
There are three different problems here:

1) 'multiple' => 0, declaration is causing the "Array" output. Select field is by default non-multiple, so please remove this declaration.

2) #1901 should fix the problem with registered value not showing up with non-multiple selects inside repeaters.

3) Additionally you have "sidebar" and "footer" defined as defaults of widget_location however they are called "option-sidebar" and "option-footer" under choices.
