### ISSUE TITLE
Parse error in last update

### ISSUE THREAD

**Issue by stas-dovgodko** [themeum/kirki#1896]
### Issue description:
PHP Parse error:  syntax error, unexpected 'do' (T_DO), expecting identifier (T_STRING) in /var/www/well_run/shared/wp-content/plugins/kirki/modules/webfonts/class-kirki-fonts-google-local.php on line 83

php 5.6.35

You can't use reserved word "do" as method name

**Comment by szwejko** [comment]
Exactly the same problem after new update

**Comment by aristath** [comment]
In PHP 7+ this is not an issue so I missed it on my tests originally.
Already fixed in v3.0.29 and released in wordpress.org so I'm closing this one as fixed.
