### ISSUE TITLE
md5() expects parameter 1 to be string since latest version.

### ISSUE THREAD

**Issue by kevinmamaqi** [themeum/kirki#1897]
### Issue description:
This message since last update:

`Warning: md5() expects parameter 1 to be string, array given in /home/carlosam/toldosserrano/wp-content/plugins/kirki/modules/webfonts/class-kirki-fonts-google-local.php on line 118
`
### Version used:
Latest

### Using theme_mods or options?
theme_mods, but I think it has to do with the plugin.

### Code to reproduce the issue (config + field(s))
Too many, probably typography for this one.

**Comment by aristath** [comment]
already fixed
