### ISSUE TITLE
Google Fonts Not Working

### ISSUE THREAD

**Issue by spencermcghin** [themeum/kirki#1898]
### Issue description:
Updated to latest version. Updated to PHP 7.1 via host. Body font not changing to designated google font. I saw that you made a change per an earlier update. Do I need to take any further steps to get my chosen font working again?

### Version used: Latest
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by octavioamu** [comment]
Same problem here . The chosen font option is  saved also displayed in the preview but the font is not found when published. Also is not any font inside uploads/webfonts
I had changed the folder permissions to 755 because was 644 but also it didn't solve the problem.

**Comment by notrealdev** [comment]
Same problem when update to version 3.0.30 
```
/wp-content/uploads/webfonts/opensans/mem5YaGs126MiZpBA-UNirk-VQ.ttf 403 (Forbidden)
```
Can you check it? @aristath

**Comment by octavioamu** [comment]
Maybe can save someone. My provisory fix was to manually upload the files of the font to webfonts folder.
You can find and download files from webfont-files.json https://github.com/aristath/kirki/blob/develop/modules/webfonts/webfont-files.json

**Comment by aristath** [comment]
v3.0.31 was just released, this should fix all your google-fonts issues.
