### ISSUE TITLE
Required fields show/hide error

### ISSUE THREAD

**Issue by adamsultan7** [themeum/kirki#19]
Required field target shown when clicking on true value but it don't hide when click on false value.

**Comment by aristath** [comment]
Hey there!
Sorry it took me so long to get back to you on this one...
Are you still having this issue?

**Comment by jamiebrwr** [comment]
I'm also having this problem.

**Comment by aristath** [comment]
Closing this one as a duplicate of #7, we're going to rebuild the way required arguments work.
