### ISSUE TITLE
Mind if I switch out the readme.txt to be README.MD?

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#190]
Hi Aris,

Would you mind if I do a bit of housekeeping on the repo and switch out the readme.txt to be readme.md?

That way the markdown will look and feel like it is Github

**Comment by aristath** [comment]
If you want to create readme.md file then please feel free to do so!

But we need the readme.txt file for wordpress.org so don't switch it out, just add a .md file. :+1:

**Comment by ghost** [comment]
Thanks mate, will clone it down and make a PR in a few mins. Do you get mailed when the PR's are waiting for you?

**Comment by aristath** [comment]
I get a notification, yes :)

**Comment by ghost** [comment]
Done, added new page to Wiki for Changelog and linked to it from the changelog in the readme.md, that way it stays nice and tidy. Possibly I have a small case of OCD :)

**Comment by ghost** [comment]
https://github.com/aristath/kirki/wiki/Changelog

**Comment by aristath** [comment]
:+1:
