### ISSUE TITLE
select not show in repeater

### ISSUE THREAD

**Issue by FairWindCo** [themeum/kirki#1903]
### Issue description:
in version 3.0.28 (and before) select work control in repeater.
In version 3.0.33 select control not show in repeater

### Version used: 3.0.33
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
 theme_mods

### Code to reproduce the issue (config + field(s)) field activity_page not show in repeater
```
fw__add_theme_control($config_name,$section,'my_activities','Activities','repeater', 50, array(
	'row_label' => array(
		'type'  => 'field',
		'value' => fw__theme_text('your custom value'),
		'field' => 'activity_name',
	),
	'fields' => array(
			'activity_name' => array(
				'type'        => 'text',
				'label'       => fw__theme_text( 'activity Name'),
				'description' => fw__theme_text( 'This will be the label for your activity'),
				'default'     => '',
			),	
			'activity_text' => array(
				'type'        => 'text',
				'label'       => fw__theme_text( 'activity Text'),
				'description' => fw__theme_text( 'This will be the text for your activity'),
				'default'     => '',
			),
			'activity_page' => array(
				'type'        => 'select',
				'label'       => fw__theme_text( 'activity page link'),
				'description' => fw__theme_text( 'This will be the activity page link'),
				'default'     => '',	
				'choices'  => Kirki_Helper::get_posts(
					array(
						'posts_per_page' => 10,
						'post_type'      => 'page'
					)),	
			),	
		)
	)
);
```

**Comment by asilcetin** [comment]
Is the whole select field or the choices not visible? 

Do you still have the issue if you remove already existing repeater blocks on the customizer and add new ones?

Can you please paste a screenshot of the problematic repeater area + open the developer tools on chrome and paste a screenshot of console tab if you see any errors there?

Thanks.

**Comment by FairWindCo** [comment]
if item already exist than whole select field not visible.
if add new - visible.

**Comment by asilcetin** [comment]
So, deleting the previous repeater blocks and adding new ones solved your issue? 

Or does this issue persist with the newly added repeater blocks after you save them and refresh the customizer?

**Comment by DannyCooper** [comment]
This is likely related to https://github.com/aristath/kirki/issues/2141, as you don't have any defaults set.

**Comment by DannyCooper** [comment]
Hi @FairWindCo,

I've just pushed a fix to the develop branch which I believe fixes this. Would you mind testing?

Thanks
