### ISSUE TITLE
Apply Alpha Colors in Typography Control

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#1906]
### Issue description:
Hi Ari,

Any chance to change font color's opacity in Typography control? You know in some cases specially on a dark backgrounds we might need font colors to be like **rgba(255, 255, 255, 0.7)**

Thanks bro

### Version used:  3.0.33
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
theme_mods

**Comment by vlthemes** [comment]
Same issue....

**Comment by mapsteps** [comment]
In v4, the typography color picker will default to rgba.
