### ISSUE TITLE
kirki/{$config_id}/styles filter

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1913]
Hi Ari!

This filter does`t work kirki/{$config_id}/styles

Version:
Recent from wp.org

**Comment by aristath** [comment]
I'm sorry for the delay... Time is a bit limited these days.
I marked this as a bug and I'll check it ASAP.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
