### ISSUE TITLE
Kirki compliance with the new Envato Theme Check

### ISSUE THREAD

**Issue by sergeysedykh** [themeum/kirki#1914]
### Issue description:

We're embedding Kirki as a library inside our themes on ThemeForest.

Yes, I know it's not recommended. But there're several major advantages:

* We have full control of the Kirki version.
* Users don't have an extra plugin, that they hardly understand, what it does.

There're a few issues with the Envato Theme Check:

https://github.com/envato/Envato-Theme-Check

Is there a chance, they'll be resolved?

Or should we consider switching to the Kirki plugin instead?

Many thanks, @aristath!

**Comment by aristath** [comment]
Did you submit a theme that got rejected somehow because it includes Kirki?
Kirki is allowed both in wordpress.org and envato themes, I seriously doubt there will be any issues

**Comment by sergeysedykh** [comment]
I have had a few themes approved with Kirki integrated, however Envato now uses a new theme check plugin and there're way more warnings now:

![image](https://user-images.githubusercontent.com/36392769/40790111-bd512ee0-64fc-11e8-8c8e-11b8013acbb8.png)

**Comment by aristath** [comment]
Did you actually submit a theme that got rejected?
I know about those warnings etc, but they are of no concern. Everything gets properly sanitized before it gets echoed.

**Comment by DeoThemes** [comment]
Here is the reply about embedding Kirki into theme from official Envato stuff:

>  If you are embedding Kirki in your theme, you should read the Plugin Inclusion requirements 1 which say that baking plugins into your theme is not allowed and then please consider moving to use it as a plugin.

We've been using Kirki in our themes as well, but after this new rule It should be moved as a plugin.

**Comment by sergeysedykh** [comment]
> Did you actually submit a theme that got rejected?

Haven't submitted any new themes recently, but we'll be adding a few in a while and I'll definitely keep you updated.

**Comment by minimaluminium** [comment]
Just require Kirki as a plugin in TGM Plugin Activation and there will be nothing to worry about.

**Comment by niklasp** [comment]
can be closed probably #2026

**Comment by sergeysedykh** [comment]
This can be closed, as there're no warnings in the latest Kirki versions. Thanks!

**Comment by aristath** [comment]
Thanks for the update @classyentrepreneur!
