### ISSUE TITLE
Using Kirki From My Plugin .

### ISSUE THREAD

**Issue by medabkari** [themeum/kirki#1915]
Hi There, first of All , I Wanna Say Thank You Very Much For Helping all of Us By Developing This Huge Plugin, So From My Experience , I read the documentation, l knew how to add panels, sections, fields, but when i try to , i fall in a fatal error, Class 'Kirki' not Found  .
So My Question is, Should i write the code and hooked it in customize_register or just do it directly without any hook ? .

**Comment by aristath** [comment]
Not on customize_register.
Try adding it in `after_setup_theme` or init, and always check if the class exists before using it.
Example:
```php
add_action( 'after_setup_theme', function() {
	if ( ! class_exists( 'Kirki' ) ) {
		return;
	}
	// Your code here.
} );
```
