### ISSUE TITLE
include-kirki.php File doesn't work in Plugin

### ISSUE THREAD

**Issue by medabkari** [themeum/kirki#1917]
Hello, I'm facing some errors about the file include-kirki.php, i mean i tried everything to make it work in my plugin but nothing works, to explain more: I'm developing a plugin core for a theme, which I will store in all the customizer settings and display them in every theme, so here's what i did.

1- I Integrated the kirki plugin via the TGMPA tool as stated in the documentation.
2- I created a new file which I'll use later for the customizer settings ( panels - sections - fields ... ).
3- I included the file [ include-kirki.php ] which is responsible for the activation and the existence of kirki class.
 finally, when I try to start adding some fields just for testing, i get an error telling me that the class Kirki doesn't Exist.

Actually, there are a lot of include-kirki.php files in the repository, i didn't know which one to use then I tried them both and i couldn't include the kirki .
So what do you think could I have done wrong?
maybe something bad happened or maybe there's a bug in the code.

**Comment by aristath** [comment]
When adding fields from a plugin, you need to make sure that kirki has already been loaded.
I'm assuming you're doing something like this:
```php
include 'path-to-include-kirki.php';
include 'file-with-panels-sections-fields-etc.php';
```
Instead of including the files directly, do something like this:
```php
/**
 * Include files containing customizer sections, fields etc.
 * This is hooked on 'after_setup_theme' 
 * so that it runs after all plugins have been instantiated.
 */
function my_plugin_include_kirki() {
	if ( class_exists( 'Kirki' ) ) {
		include 'path-to-include-kirki.php';
		include 'file-with-panels-sections-fields-etc.php';
	}
}
add_action( 'after_setup_theme', 'my_plugin_include_kirki' );
```

**Comment by medabkari** [comment]
Thank you very much for your help, Happy to have it fixed, I didn't know about the early load. Thank you very much, and happy coding!
