### ISSUE TITLE
Select field inside repeater returns array not the value selected.

### ISSUE THREAD

**Issue by tnchuntic** [themeum/kirki#1919]
### Issue description:
Select field inside repeater returns 'Array' string not the value selected. 

I am trying to use the repeater to dynamically create blocks(link, button, phone, email, etc.) but couldn't make it work because of the select is returning an 'Array' string not the actual value.

### Version used:
Version 3.0.33 - Wordpress Plugin Repo.
WordPress 4.9.6

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
    Kirki::add_panel('header_panel', array(
        'priority' => 160,
        'title' => esc_attr__('Header Settings', TEXTDOMAIN),
        'description' => esc_attr__('Header Settings', TEXTDOMAIN),
    ));

    Kirki::add_section('header_section', array(
        'title' => esc_attr__('Dynamic Blocks', TEXTDOMAIN),
        'description' => esc_attr__('Dynamic Blocks', TEXTDOMAIN),
        'panel' => 'header_panel',
        'priority' => 10,
    ));

    Kirki::add_field(THEME_CUSTOMISER_ID, array(
        'type' => 'repeater',
        'label' => esc_attr__('Blocks', TEXTDOMAIN),
        'section' => 'header_section',
        'priority' => 10,
        'row_label' => array(
            'type' => 'field',
            'value' => esc_attr__('Block', TEXTDOMAIN),
            'field' => 'block_text',
        ),
        'button_label' => esc_attr__('Add Block', TEXTDOMAIN),
        'settings' => 'header_blocks',
        'default' => array(
            array(
                'block_type' => 'opt-phone',
                'block_text' => esc_attr__('123 700 000', TEXTDOMAIN),
                'block_url' => '123 700 000',
            ),
        ),
        'fields' => array(
            'block_type' => array(
                'type' => 'select',
                'label' => esc_attr__('Block Type', TEXTDOMAIN),
                'multiple' => 0,
                'choices' => array(
                    'opt-button' => esc_attr__('Button', TEXTDOMAIN),
                    'opt-link' => esc_attr__('Link', TEXTDOMAIN),
                    'opt-phone' => esc_attr__('Phone', TEXTDOMAIN),
                    'opt-email' => esc_attr__('Email', TEXTDOMAIN),
                ),
            ),
            'block_text' => array(
                'type' => 'text',
                'label' => esc_attr__('Block Text', TEXTDOMAIN),
                'description' => esc_attr__('This will be the label for your block', TEXTDOMAIN),
                'default' => '',
            ),
            'block_url' => array(
                'type' => 'link',
                'label' => esc_attr__('Block URL', TEXTDOMAIN),
                'description' => esc_attr__('This will be the block URL', TEXTDOMAIN),
                'default' => '',
            ),
        )
    ));

### Screenshots
<img width="971" alt="screen shot 2018-06-09 at 12 10 16 pm" src="https://user-images.githubusercontent.com/4864523/41186980-f262635e-6be3-11e8-9245-388c5b756015.png">
<img width="527" alt="screen shot 2018-06-09 at 12 12 27 pm" src="https://user-images.githubusercontent.com/4864523/41186981-f291fdb2-6be3-11e8-9a01-64a3b6a5214a.png">

**Comment by tnchuntic** [comment]
Found the issue, its a bit weird because of just this attribute/option **"'multiple' => 0,"** it will return 'Array' string but when it is commented out it works fine.

**Comment by amitsarkerr** [comment]
Thank you @tnchuntic
