### ISSUE TITLE
Kirki::add_field was called incorrectly

### ISSUE THREAD

**Issue by akramulhasan** [themeum/kirki#1920]
### Issue description:
everything is working fine but when I am enabling WP_Debug: true, I am getting this error
Notice: Kirki::add_field was called incorrectly. Kirki fields should not be added on customize_register. Please add them directly, or on init. Please see Debugging in WordPress for more information. (This message was added in version 3.0.10.)

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.33
### Using theme_mods or options?
theme-mods

### Code to reproduce the issue (config + field(s))
just after creating any field

**Comment by aristath** [comment]
The message is pretty self-explanatory.
You should not add `Kirki::add_field()` inside `customize_register`.
So this is a no-no:
```php
add_action( 'customize_register', function() {
    Kirki::add_field()
} );
```
You don't need to add `Kirki::add_field()` in some hook... All you need to do is this:
```php
Kirki::add_field()
```

If you absolutely must add it to a hook, use `init`
```php
add_action( 'init', function() {
    Kirki::add_field()
} );
```
