### ISSUE TITLE
Link Type is not available yet?

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1924]
http://aristath.github.io/kirki/docs/controls/link.html

This type is not available yet?

**Comment by fastmarketo** [comment]
If we use this → http://aristath.github.io/kirki/docs/controls/dropdown-pages.html

How can we print the selected page in the code as a URL?

**Comment by aristath** [comment]
> http://aristath.github.io/kirki/docs/controls/link.html
> This type is not available yet?

The type is available.
The documentation for that type is not. But it's just like a normal text field... You simply change the type from `text` to `link` and it works.

> If we use this → http://aristath.github.io/kirki/docs/controls/dropdown-pages.html
> How can we print the selected page in the code as a URL?

If your setting is called `my_setting`, then `get_theme_mod( 'my_setting' );` will return the post-ID just like the doc says.
From that point on your can do whatever you want with that ID...
Look at [`get_post()`](https://developer.wordpress.org/reference/functions/get_post/) for examples.

**Comment by fastmarketo** [comment]
How to convert the post ID into the Page URL?

**Comment by aristath** [comment]
google "wordpress get post url from id".

**Comment by fastmarketo** [comment]
$id = get_theme_mod( 'my_setting' );
get_permalink( $id );
