### ISSUE TITLE
https webfont load error

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1925]
Hi!

I have some errors in console log.

Mixed Content: The page at 'https://www.****.com/' was loaded over HTTPS, but requested an insecure font 'http://www.***.com/wp-content/uploads/webfonts/roboto/KFOjCnqEu92Fr1Mu51TLBBc9.ttf'. This request has been blocked; the content must be served over HTTPS.

**Comment by aristath** [comment]
@vlthemes I just pushed a commit in the develop branch that may fix this.
Since I'm unable to replicate your issue could you please test this branch and let me know if it fixes your issue?

**Comment by vlthemes** [comment]
The client has closed access to his site. I can not check this. But I hope that the problem is fixed.

**Comment by aristath** [comment]
Closing this one.
The fix will be included in v3.0.34
