### ISSUE TITLE
Background color field doesn't clear/reload once cleared

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#1928]
### Issue description:

1. I select a color (blue) in the background color field
2. It loads and shows the color fine
3. I click "Clear" but nothing happens, when it should reload and clear the field and go back to no background color

![Issue](https://i.imgur.com/O221bRn.png)

### Version used:
Latest version

**Comment by aristath** [comment]
Can you please share the code you use for that field?
Are you using options or theme-mods?

**Comment by AlxMedia** [comment]
Sent you a mail with a testable theme.

**Comment by JiveDig** [comment]
For clarity, this seems like a duplicate of https://github.com/aristath/kirki/issues/1869

**Comment by niklasp** [comment]
agree to @JiveDig  - close one of these #2026

**Comment by aristath** [comment]
Confirmed. Marked as a duplicate and closing this one. It will be fixed with #1869
