### ISSUE TITLE
I want to move default section on own panel

### ISSUE THREAD

**Issue by aijazsiddique** [themeum/kirki#193]
I want to move default section on own panel

like 
site title and tagline
static front page 
these to section on General panel

Background Image section on 
Background Images panel

color section on
style panel 

please help me

**Comment by aristath** [comment]
Hey there!

You will first have to remove these sections, and then re-add them to your own panel.
to remove a section for example you'd do something like this:

``` php
$wp_customize->remove_control( 'blogdescription' );
$wp_customize->remove_section( 'nav' );
$wp_customize->remove_section( 'static_front_page' );
```

**Comment by DevelopOnline** [comment]
Hi there,
How can I re-add a predefined control or section (e.g. `nav` section) to a new panel?!

**Comment by ghost** [comment]
Great question. I will sit by and watch for the answer as well. I have been wondering the same thing just yesterday. Genesis has a default to have the site name and tag line in Customizer, and wanting to pretty much do the same thing asked above to add to the custom panel of Kirki.

**Comment by aijazsiddique** [comment]
I didn't ask how to remove i asked how to sift it to my own custom panel

**Comment by aristath** [comment]
@aijazsiddique please see my previous reply.
First you will have to remove it, then you will have to add it to your own panel.
The above code will help you remove it.
This will help you add it again where you want it: https://make.wordpress.org/core/2014/07/08/customizer-improvements-in-4-0/#customizer-panels

**Comment by aijazsiddique** [comment]
thankyou so much @aristath
