### ISSUE TITLE
dashicons and fontawesome types are not working in repeater type

### ISSUE THREAD

**Issue by toton333** [themeum/kirki#1932]
### Issue description:
dashicons and fontawesome types are working as individual type, but when they are being used inside a repeater type just  blank space are showing in the customizer.

### Version used:
Latest from github

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_section( 'frontpage_section3', array(
    'title'          => esc_attr__( 'Services', 'airspace' ),
    'description'    => esc_attr__( 'Describe your various services', 'airspace' ),
) );


Kirki::add_field( 'airspace_kirki_config_id', array(
	'type'        => 'repeater',
	'label'       => esc_attr__( 'Social Buttons', 'airspace' ),
	'section'     => 'frontpage_section3',
	'row_label' => array(
		'type' => 'text',
		'value' => esc_attr__('meta', 'airspace' ),
	),
	'settings'    => 'socials',
	'default'=> array(
         array(
            'social_icon' => 'admin-users',
            'social_url'  =>  'http://www.google.com'
         ),

		),
	'fields' => array(
		'social_icon' => array(
			'type'        => 'dashicons',
			'label'       => esc_attr__( 'Social vendor', 'airspace' ),
		),

		'social_url' => array(
			'type'        => 'text',
			'label'       => esc_attr__( 'Social url', 'airspace' ),
		)		
	),	
) );
```

**Comment by aristath** [comment]
These fields are not supported (yet) in repeaters. They were never supported, and though there are plans to add support for them it is currently not a priority since it can only be done after we completely refactor some more basic areas in the plugin.
I'm closing this one as there are already other feature requests in this repository for this.
