### ISSUE TITLE
Feature Request: Custom Color Pallete

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1934]
create a color pallet where the user can define a color pallet with a specific name, define custom colors they want to have available.

These custom defined colors are then available in every instance of the color pallet.

**Comment by DannyCooper** [comment]
Hi @tsquez,

There are many ways you could accomplish this, one solution is to create your own helper function and using that in each control.

```
function my_color_pallete() {
	return array( '#000000', '#222222', '#444444', '#666666', '#888888', '#aaaaaa', '#cccccc', '#eeeeee', '#ffffff' );
}
```

```
'settings'    => 'color_palette_setting_0',
'label'       => esc_html__( 'Color-Palette', 'kirki' ),
'description' => esc_html__( 'This is a color-palette control', 'kirki' ),
'section'     => 'color_palette_section',
'default'     => '#888888',
'choices'     => array(
	'colors' => my_color_pallete(),
	'style'  => 'round',
)
```
