### ISSUE TITLE
Shortcut icon focuses wrongly when using editor type

### ISSUE THREAD

**Issue by toton333** [themeum/kirki#1937]
### Issue description:

When using partial refresh, for editor type, the shortcut icon after clicking leads to "add media" button, instead of focusing on textarea. I think this is a bug.
### Version used:
3.0.33 

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Does the media field by any chance also control the same area?

**Comment by niklasp** [comment]
close? #2026
