### ISSUE TITLE
Nesting Sections or Nesting Panels - possible?

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#194]
Hi Aris,

An interesting idea, and not sure if it is done already, But is there a way to nest Sections in customiser? Say I have a small group of things for Footer, and I already used the panel footer settings, but I have in footer panel Section called Colours, a Section called Footer Widgets.

I would like to group all my colours used for the footer area in one section. So in the section accordion I was thinking to add header titles in each section, and under each header in the section to add my controls to sit under a heading. Same for Footer Widgets, I would like to nest headings in one section, and have everything in controls under that one section to do with footer widgets.

Alternatively, can I have nested Panels? If I could have nested panels, then it would allow me to not worry about making headings in sections as described above.

**Comment by aristath** [comment]
Yup, WordPress core recently introduced Panels: https://make.wordpress.org/core/2014/07/08/customizer-improvements-in-4-0/#customizer-panels
Panels include sections, so won't that do for you?

**Comment by ghost** [comment]
Yes they do the job. Thank you Aris. I was wondering if it was possible to Nest panels within Panels, and have sections in the nested panels. But last night I started building out my panels and sections and thought there is no need for me to try complicate it further.

Thank you for the reply mate.

**Comment by pingram3541** [comment]
I know this is closed because Ciaran found he no longer needed this capability but I came here searching for the same thing so I'm sure others will as well eventually.  Could we have the following capability?

My Theme Options Panel > My Sub-Panels > My Sections > My Sub-Sections > My Fields

Currently I am only able to get:

My Theme Options Panels>  My Sections > My Fields

**Comment by andrasguseo** [comment]
+1 on the question of pingram3541.

**Comment by aristath** [comment]
See https://wordpress.org/support/topic/nested-panels/ 👍
