### ISSUE TITLE
Duplicate array key.

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1940]
### Issue description:
Hello.
I have found a duplicate key in the array. Is it a mistake?

### Version used:
3.0.33

### Code to reproduce the issue (config + field(s))
![screenshot_11](https://user-images.githubusercontent.com/32881283/42302002-1c12b2e8-8021-11e8-909a-bcc7596e4a5a.jpg)

**Comment by JimmyAppelt** [comment]
Was fixed on `develop` in #1954
