### ISSUE TITLE
Typography: Downloading font-family to server loads all variants

### ISSUE THREAD

**Issue by traian-s** [themeum/kirki#1941]
### Issue description:
With typography control if you choose a google font and a specific variant it will load all possible variants of the font, not just the variant selected. Is this intended?
https://www.screencast.com/t/IcCrqR6a
https://www.screencast.com/t/28eDPUOedihK

### Version used:
development branch

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
any typography field

**Comment by aristath** [comment]
Marking this one as a bug and adding to the 3.0.34 milestone 👍

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
