### ISSUE TITLE
Cannot hide media buttons for editor control

### ISSUE THREAD

**Issue by dave-green-uk** [themeum/kirki#1947]
### Issue description:

I cannot hide media buttons by passing in the `media_buttons` parameter when registering the field. This is hard coded into `scripts.js` at the moment.

### Version used:
3.0.33 (plugin from .org)

### Using theme_mods or options?
`options`.

### Code to reproduce the issue (config + field(s))

I would expect to be able to implement this like this in my codebase...

```
\Kirki::add_field( $config_id, array(
	'type'     => 'editor',
	'settings' => $section_id . '_legal',
	'label'    => __( 'Legal Information', 'xxx' ),
	'section'  => $section_id,
	'priority' => 12,
	'media_buttons' => false
) );
```

...or like this...

```
\Kirki::add_field( $config_id, array(
	'type'     => 'editor',
	'settings' => $section_id . '_legal',
	'label'    => __( 'Legal Information', 'xxx' ),
	'section'  => $section_id,
	'priority' => 12,
	'options'  => array(
		'media_buttons' => false
	),
) );
```
```

**Comment by DarkoDonnie** [comment]
@davetgreen  While we are waiting for those options, there's a solution to hide the media button with CSS.

#### 1. Create additional CSS file inside your theme

for example inside: your_theme_dir/assets/css/
and name it "admin-custom-styles.css"

#### 2. Enqueue custom admin CSS file inside your theme functions

```
function my_admin_custom_styles() {
    wp_enqueue_style( 'admin-custom-styles', get_template_directory_uri(). '/assets/css/admin-custom-styles.css' );
}
add_action( 'admin_enqueue_scripts', 'my_admin_custom_styles' );
```
If you're using child theme use `get_stylesheet_directory_uri()` instead.

#### 3. Edit your CSS to hide the button

```
#customize-control-your_editor_settings_id .wp-media-buttons .insert-media {
    display: none;
}
```

**Comment by DannyCooper** [comment]
I've created a PR to include this upstream - https://github.com/kirki-framework/control-editor/pull/1
