### ISSUE TITLE
active_callback base on function

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1948]
### Issue description:
active_callback works base on setting. if setting_value == manual_defined_value, field will display otherwise not. but i want to display fields base on function like if function_value == manual_defined_value, field should display otherwise not.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Code to reproduce the issue (config + field(s))

```
	'active_callback'  => array(
		array(
			'setting'  => 'function_name',
			'operator' => '==',
			'value'    => 1,
		),

	)
```

**Comment by rinkuyadav999** [comment]
Also if there is two conditions like 

```
'active_callback'  => array(
	array(
		'setting'  => 'setting_one',
		'operator' => '==',
		'value'    => 1,
	),
	array(
		'setting'  => 'setting_two',
		'operator' => '==',
		'value'    => 1,
	),
)
```

It works using && condition like if( first_condition && second_condition ) display field otherwise not, here how to use or ( || ) condition, like if( first_condition || second_condition ) display field otherwise not,

Expected

```
'active_callback'  => array(
	array(
		'setting'		=> 'setting_one',
		'operator' 		=> '==',
		'value'    		=> 1,
		'condition'    	=> '||', // to do if( this_condition || next_condition ) { display this field }. right now it use && and not change able.
	),
	array(
		'setting'  => 'setting_two',
		'operator' => '==',
		'value'    => 1,
	),
)
```

**Comment by MoBadawy** [comment]
Just put the function name in active_callback like this
`
'active_callback'  => 'is_setting',
`

Then make the function return true like this

`
function is_setting(){
	if (condition ) {
		return true;
	}
}
`

>

**Comment by rinkuyadav999** [comment]
@MoBadawy Thanks
