### ISSUE TITLE
kirki version 3.0.33 seems to disable Live Preview

### ISSUE THREAD

**Issue by Leaps777** [themeum/kirki#1953]
### Issue description:
After upgrading Wordpress to Version 4.9.7, now even when all other plug-ins are deactivated if kirki 3.0.33 is activated I am unable to use live preview. I get the following option only: 

![image](https://user-images.githubusercontent.com/41970996/43482942-26c5e1f8-94d8-11e8-96c5-2cee060cb540.png)

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

No

### Using theme_mods or options?

Problem occurs either with my usual enabled or all disabled.

**Comment by Leaps777** [comment]
Update - This does not seem to happen in Safari. I was previously using Chrome, which is still happening in.

**Comment by niklasp** [comment]
still relevant? 
#2026

**Comment by DannyCooper** [comment]
Closing this as it doesn't seem to be an issue with the latest versions and there have been no similar reports.
