### ISSUE TITLE
Required logic - a small addition tutorial

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#196]
Hi Aris,

I notice that Required is available for us to now use. However I cannot see any way that I should use it in the kirki.org tutorials. Could you please show one control of grouped radio with conditional logic to display another control if one radio of the grouped radio is selected. This will allow me to continue building out the project.

Additionally, can the required rule be used in one panel and set the conditional logic of a complete section to display based on a selection of either a toggle switch or radio group field?

Ciaran

**Comment by aristath** [comment]
See https://github.com/reduxframework/kirki/wiki/required

At this point it's not possible to use the `required` argument for sections & panels but it's on the to-do list (see #240) however you can custom-code this using the tutorial on http://ottopress.com/2015/whats-new-with-the-customizer/
