### ISSUE TITLE
Override get_theme_mod for custom page, post etc.

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1962]
Hello! Sorry for spam, maybe.

Perhaps someone has a solution for overwriting fields for pages. How can this be done?

I mean like set_theme_mod but not global.

**Comment by vlthemes** [comment]
Maybe there is a possibility to add override to Kirki Helper?

**Comment by dellesparks** [comment]
i need help with a parse error blocking me from accessing my website;

Parse error: syntax error, unexpected 'do' (T_DO), expecting identifier (T_STRING) in /home3/joemugendi/twistytwenties.com/wp-content/plugins/kirki/modules/webfonts/class-kirki-fonts-google-local.php on line 83

**Comment by aristath** [comment]
@vlthemes you could use default WP filters to do that. See notes in https://codex.wordpress.org/Function_Reference/get_theme_mod#Notes about the filter you can use.

for example:

```php
add_filter( 'theme_mod_my_setting', function( $value ) {
	global $post;
	if ( $post && isset( $post->ID ) && $post->ID ) {

		// Check if the post-ID is the one we want.
		if ( 42 === $post->ID ) {

			// Return modified value.
			return 'NEW VALUE';
		}
		return $value;
	}
} );
```

@dellesparks That error was fixed q long time ago, can you please update your installation to the latest version of Kirki? That should fix any issues you have.
