### ISSUE TITLE
Spacing control does not update properly after entering values (video)

### ISSUE THREAD

**Issue by kevinmamaqi** [themeum/kirki#1964]
### Issue description:
When adding values to the spacing control it updates just the first time, then you can't modify them and save again. The value output is correct though once you get out the customizer. https://streamable.com/5lzzo

### Version used:
Latest from wordpress.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
		Kirki::add_field('mytheme',  array(
		    'section' => 'header_general_style',
		    'settings' => 'centered_logo_spacing',
		    'label' => esc_html__('Logo padding', 'mytheme'),
		    'type' => 'spacing',
		    'priority'    => 40,
		    'default'     => array(
		        'top'    => '0px',
		        'bottom' => '0px',
		    ),
		    'transport' => 'auto',
		    'output' => array(
		        array(
		            'element' => '.basic-centered .logo_wrapper',
		            'property' => 'padding',
		        ),
		    ),
		    'active_callback'    => array(
				array(
					'setting'  => 'header_type',
					'operator' => '==',
					'value'    => 'basic_centered',
				),
			),
		));

**Comment by aristath** [comment]
This is weird... I was unable to replicate it on a test site.

Does this only happen if you have multiple spacing controls? Or can you also replicate if there's a single spacing control in the customizer too?
Are there any errors in the console?
Can you please try the develop branch and check if this still happens there? It may have already been fixed elsewhere

**Comment by kevinmamaqi** [comment]
Thanks for the fast reply.

There are 4 console errors, two I really don't know where they come from and other two appeared since I started using the spacing control. Below you have an image and the code.

<img width="524" alt="screen shot 2018-08-25 at 14 22 51" src="https://user-images.githubusercontent.com/972664/44618236-6049fd80-a872-11e8-99f6-33e2b4c83f1b.png">

```
script.js?ver=3.0.33:1278 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Object.cssValue (script.js?ver=3.0.33:1278)
    at script.js?ver=3.0.33:1788
    at Function.m.each.m.forEach (underscore.min.js?ver=1.8.3:5)
    at Function.<anonymous> (script.js?ver=3.0.33:1787)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith (jquery.js?ver=1.12.4:2)
    at Function.set (customize-base.js?ver=4.9.8:225)
    at Function.d [as set] (jquery.js?ver=1.12.4:2)
    at child.saveValue (script.js?ver=3.0.33:1769)
    at HTMLInputElement.<anonymous> (script.js?ver=3.0.33:1753)
cssValue @ script.js?ver=3.0.33:1278
(anonymous) @ script.js?ver=3.0.33:1788
m.each.m.forEach @ underscore.min.js?ver=1.8.3:5
(anonymous) @ script.js?ver=3.0.33:1787
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
set @ customize-base.js?ver=4.9.8:225
d @ jquery.js?ver=1.12.4:2
saveValue @ script.js?ver=3.0.33:1769
(anonymous) @ script.js?ver=3.0.33:1753
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
```

**Comment by aristath** [comment]
I just pushed commit https://github.com/aristath/kirki/commit/2bc84826acb8d0044c378dbd71489c0d8c959ff9 that _should_ fix this, can you please try with the develop branch now?

**Comment by kevinmamaqi** [comment]
Hi @aristath since the last update it works fine, but now upload image fields and slides don't work as expected. I get the following message:

```
underscore.min.js?ver=1.8.3:5 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Function.m.template (underscore.min.js?ver=1.8.3:5)
    at wp-util.js?ver=4.9.8:35
    at Object.template (script.js?ver=3.0.34:527)
    at Object.init (script.js?ver=3.0.34:503)
    at child.initKirkiControl (script.js?ver=3.0.34:1640)
    at Object.<anonymous> (script.js?ver=3.0.34:1569)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Object.e.(/wp-admin/anonymous function) [as resolve] (http://kmframework.km/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:29192)
    at child.actuallyEmbed (script.js?ver=3.0.34:1617)
```
Once the error appears, the only thing you can do is to log-out of the customizer.


<img width="1280" alt="screen shot 2018-09-15 at 19 11 46" src="https://user-images.githubusercontent.com/972664/45588818-72700680-b91b-11e8-871c-2b1665abffd3.png">

**Comment by aristath** [comment]
Can you send me a copy of your theme so that I may install it locally and test it?
Which fields on your theme cause this? (will help me debug faster if I know)

**Comment by aristath** [comment]
Finxed in https://github.com/aristath/kirki/issues/1982#issuecomment-421639801
