### ISSUE TITLE
Updating the variant list based on the font family of another Typography field

### ISSUE THREAD

**Issue by ekapobc** [themeum/kirki#1966]
### Issue description:
Hello!

I am wondering would it be possible to update the variant list of Typography fields after changing the font family of another Typography field?

For example, I would like to have one field for selecting a primary font (field A), and other fields (field B and C) for adjusting heading and text styles. For field B and C, the 'font-family' is hidden, so the user can adjust only the font properties including variants.

So, it would be ideal for the variants of field B and C to be automatically updated based on the selected font in A.

Could you please advise if it's possible to do?

Thank you!
Paul

### Version used:
3.0.33

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Hey there!

I'm afraid that no, this won't be possible with Kirki unless you custom-code it yourself.
