### ISSUE TITLE
Which branch should I be working with for extending? [Question]

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#1967]
### Issue description:
I've been working on extending the project to add some new controls and additional functionality, but I'm unsure which branch I should be forking.

I initially worked in develop, but I am also working with extending postMessage for said controls, so I'm not sure if I should be working with develop or postMessage-refractor.

Can you give some insight?

Thanks

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
N/A

### Using theme_mods or options?
N/A

### Code to reproduce the issue (config + field(s))
N/A

**Comment by aristath** [comment]
the `postMessage-refactor` branch **will be merged**, so ideally you'd work on that one. The more people test it and provide feedback/suggestions the sooner it will be merged and improve overall performance.
However, if you already have a working solution for your control in the `develop` branch, could you please share what you're using? If I have a sample of code then I can try to add compatibility with that in the new branch.

**Comment by CaptJiggly** [comment]
Ah, I see. Yeah, after I got most of the controls working and after making the edits to class-kirki-modules-postmessage.php, I remembered the postMessage-refractor branch.

I forked the project and once I have everything working/cleaned up to match or somewhat match the coding style of the project, I was planning on doing a pull request for you to overlook.

I've been adding a few more controls to the project such as: border, slider-advanced (users can select different suffixes with media queries for multiple devices. Similar to Elementor), etc. I'm working on typography advanced which allows media queries for line height, etc.

**Comment by niklasp** [comment]
can this be closed? #2026

**Comment by aristath** [comment]
> can this be closed?

Nope, I'm keeping it open as a reminder to contact @CaptJiggly and ask about his customizations, implementation etc :+1:

**Comment by aristath** [comment]
Closing this one, the `postMessage-refactor` branch was merged
