### ISSUE TITLE
Customizer Preview is not working

### ISSUE THREAD

**Issue by notrealdev** [themeum/kirki#1969]
### Issue description:
Hi, customizer not working on my https site

Video:
https://youtu.be/Iq-WUWJChCc

Can i know the causes of this issue?

### Version used:
Kirki: 3.0.33
WP: 4.9.8
PHP: 5.6.37
MySQL: 10.2.15-MariaDB-log-cll-lve

**Comment by niklasp** [comment]
Maybe it has to do with cross sity scripting prevention in your browser? is the domain the customizer is loading different? 

id close this issue as its probably not kirki related #2026

**Comment by DannyCooper** [comment]
The video doesn't show an obvious reason why it's not working. A copy of the theme would probably need to be provided to debug this properly.
