### ISSUE TITLE
Strange error with Google fonts

### ISSUE THREAD

**Issue by peterhadorn** [themeum/kirki#197]
I get a strange error on a test site where I had tested earlier versions of kirki and now updated to the current version. For some reason it doesn't load the Google fonts correctly from the json file, i get these errors in the FE

Warning: Invalid argument supplied for foreach() in .../kirki/includes/Fonts/FontRegistry.php

Obviously in the customizer it doesn't show the Google fonts, only the 3 standard fonts.

This does not happen on our other test sites running the same kirki version and the same config. Any advice on what could cause this and how to fix it?

**Comment by peterhadorn** [comment]
Never mind, please close this, could fix it in the hosting config

**Comment by DevelopOnline** [comment]
I have the same problem.
How did you fix this issue?
