### ISSUE TITLE
How to add section inside a section?

### ISSUE THREAD

**Issue by nazim848** [themeum/kirki#1972]
### Issue description:
How we can add section inside a section like we add section inside a panel.?

Panel > Section > Section > Control

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Code to reproduce the issue (config + field(s))

**Comment by aristath** [comment]
Already replied here https://twitter.com/aristath/status/1036684485159477250

**Comment by nazim848** [comment]
### Issue description:

When I am trying to nest a panel it's not working.
Please see the codes.

### Version used:

3.0.33

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Kirki::add_panel('ipage_topbar_panel', array(
	    'priority'  => 90,
	    'title'     => esc_attr__('Topbar Main', 'ipage'),
	));

Kirki::add_panel('ipage_topbar_sub_panel', array(
	    'priority'  => 12,
	    'title'     => esc_attr__('Topbar Sub', 'ipage'),
	    'panel'     => 'ipage_topbar_panel',
	)); 

Kirki::add_section('ipage_topbar_section', array(
	    'priority'  => 118,
	    'title'     => esc_attr__('Topbar setting', 'ipage'),
	    'panel'     => 'ipage_topbar_sub_panel',
    ) );

Kirki::add_field( 'ipage-config', array(
	'type'     => 'text',
	'settings' => 'email',
	'label'    => __( 'Email', 'ipage' ),
	'section'  => 'ipage_topbar_section',
	'default'  => esc_attr__( 'info@domain.com', 'ipage' ),
	'priority' => 13,
) );

**Comment by aristath** [comment]
It's all in https://wordpress.org/support/topic/nested-panels/#post-9906617

> Note though that a panel without sections will not appear. So you must have at least 1 section in the parent panel as well.
> 
> Similarly, you can nest a section inside another section simply by adding to the child section 'section' => 'parent_section_id'.
> But again, a section without controls will not work, so you should have at leat 1 control in the parent section.

**Comment by nazim848** [comment]
Oh got it...

I am really sorry for my mistake.
