### ISSUE TITLE
Made the Footer Widget Title Color to White and footer logo invisible.

### ISSUE THREAD

**Issue by Vinclement** [themeum/kirki#1976]
### Issue description:
Dear Team,

Thank you for the user-friendly Kirrki toolkit.

1. The Kirki toolkit which I had updated recently Version: 3.0.33 is causing the footer widget title colour default to White. Even after changing it to a different color leads to no +ve impact. It also had made the footer logo invisible (i.e). Though the logo is enabled it does not show up in the footer.

Deactivating this plugin had made the title colour as expected but the deactivation takes away the customize tab in the Appearance. I don't want to lose customize tab hence, I am forced to enable a dark background colour in the footer to make the title visible. (refer screenshot 6)

2. The Additional CSS code window is blank. I am not sure whether Kirki had caused this. But, the functionalities in the website are working fine. Please advise on how to make the code visible like how it was before. (refer screenshot 5)

Site URL: https://ptmadras.com

### Version used: Version: 3.0.33 
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
Marketo Wordpress Theme from Envanto

### Code to reproduce the issue (config + field(s))

![screenshot 6](https://user-images.githubusercontent.com/43057231/45199484-8e273d00-b289-11e8-8c3a-c48ae3613cc6.jpg)
![screenshot 5](https://user-images.githubusercontent.com/43057231/45199486-92ebf100-b289-11e8-9592-de4f2d7b53b9.jpg)

**Comment by DannyCooper** [comment]
This is likely an issue with your theme (Marketo) and you would probably get a faster resolution by raising it with them.
