### ISSUE TITLE
Control Tabs

### ISSUE THREAD

**Issue by mrtieutien90** [themeum/kirki#1977]
### Issue description:

I want to use the control tabs in the customizer, but I don't know how to create it. I very need it.
Looks like the kirki doesn't have control tabs.
Thanks

**Comment by aristath** [comment]
I'm afraid that no, Kirki doesn't have tabs.
You could custom-code it if you want, but I don't think we'll be adding tabs in kirki-core anytime soon.

**Comment by mrtieutien90** [comment]
Yes, I understand. 
Tabs are really a need. It will sort the setting and the group setting together
Kirki will not perfect without it.
