### ISSUE TITLE
How to calculate CSS values?

### ISSUE THREAD

**Issue by dhuyvetter** [themeum/kirki#1978]
### Issue description:
I am trying to calculate a `max-height` of an element using two variables set in Kirki. I have gotten this far that using `partial_refresh` I can get the value the max-height is supposed to be set to, is rendered as the content of the element it is supposed to apply to. 

I see on http://aristath.github.io/kirki/docs/controls/typography.html that there is an example of doing the calculation like I need in PHP using `output` instead of `partial_refresh` like I am using, but it is unclear to me where the PHP is supposed to go and how it should be linked to the field.

I understand `render_callback` does a render, as the name suggests. Is there a way to trigger PHP to instead of render, manipulate the CSS?

### Version used:
Kirki Version 3.0.33

### Using theme_mods
Getting the values using `get_theme_mod()`

### Code to reproduce the issue

```
Kirki::add_field('tf_kirki', array(
    'settings' => 'post_list_excerpt_length',
    'label' => __('Excerpt length (number of lines)'),
    'section' => $tf_post_list_section_id,
    'type' => 'number',
    'default' => 4,
    'choices' => array(
        'min' => 1,
        'max' => 20,
        'step' => 1,
    ),
    'partial_refresh' => [
        [
            'selector' => '.tf-post-list-post p',
            'property' => 'max-height',
            'render_callback' => function () {
                $excerpt_length = get_theme_mod('post_list_excerpt_length', 4);
                $body = get_theme_mod('body', []);
                $line_height = $body['line-height'] ?? 1.5;
                return $excerpt_length * $line_height . 'em';
            },
        ],
    ],
    'priority' => 9,
));
```

**Comment by DannyCooper** [comment]
You could do something like this:
```
Kirki::add_field(
	'prefix_config',
	[
		'type'            => 'number',
		'settings'        => 'excerpt length',
		'label'           => esc_html__( 'Number Control', 'kirki' ),
		'section'         => 'title_tagline',
		'default'         => 10,
		'priority'        => 10,
		'output' => [
			[
				'element'  => '.site-header',
				'property' => 'max-height',
				'value_pattern' => 'calc(lineHeightem * $)',
				'pattern_replace' => array(
					'lineHeight'    => 'line_height',
				),
			],
		],
	]
);
```

That would output:

```
.site-header {
    max-height: calc(20em * 10);
}
```

Where `excerpt_length` is 10 and `line_height` is 20.
