### ISSUE TITLE
Update css live without refreshing.

### ISSUE THREAD

**Issue by humanagent** [themeum/kirki#1979]
Can't code fields with css editor behave as the custom css customizer option?

If i write in a code field with css, the preview gets refreshed with the kirki pig, its not live.

http://aristath.github.io/kirki/docs/controls/code.html

Instead, in custom css at the bottom which is a native field, the css is live as you write, no need to refresh

**Comment by DannyCooper** [comment]
Have you tried this? 

https://kirki.org/docs/modules/postmessage
