### ISSUE TITLE
Image field type - store ID of attachments to db

### ISSUE THREAD

**Issue by vaclavgreif** [themeum/kirki#198]
Hi,
for some of our functions we really need to have the attachment ID. What about changing the way the image is stored to db to the same way Redux uses:

``` php
'main_image' => 
  array (
    'url' => 'http://mydomain.com/wp-content/uploads/2015/04/dummy.jpg',
    'id' => '8',
    'height' => '1300',
    'width' => '1600',
  ),
```

**Comment by vaclavgreif** [comment]
As I can see, the default Wordpress customizer image field is used for that

https://codex.wordpress.org/Class_Reference/WP_Customize_Image_Control

in the new WP versions, there’s a WP_Customize_Media_Control

https://core.trac.wordpress.org/ticket/29215

but that won’t work in older versions of WP, so maybe we can use https://developer.wordpress.org/reference/functions/attachment_url_to_postid/ to get the attachment ID?

**Comment by dovy** [comment]
Some news for you: http://redux.io

Kirki is now part of the Redux team. We'll be modifying the output to be the same across both frameworks as well as making a API like the new Redux API so converting from Redux to Kirki is a snap.  ;)

**Comment by vaclavgreif** [comment]
This is cool! What is the expected release date?

**Comment by dovy** [comment]
As soon as I can get it done? hah. We have to check each field and compare output.  ;)

**Comment by vaclavgreif** [comment]
I did that for you already #199 :) Is that of any help? 

I mean, if the updated Kirki will get released during one month, it would make sense to wait for that instead of hacking it ourselves..:)

**Comment by dovy** [comment]
Can you get on skype? DovyDigital. That helps very much!  :)

**Comment by ghost** [comment]
Aris is joining redux team?

**Comment by dovy** [comment]
http://redux.io   :)

**Comment by aristath** [comment]
@cmwwebfx Kirki and its philisophy will not change, it will remain a lightweight customizer-only framework, but It can no longer be a 1-man project.

We're joining forces to achieve greatness. :)

Especially with WordPress's announcement yesterday we'll both need it.

**Comment by kprovance** [comment]
"There is power in unity and there is power in numbers." - MLK

**Comment by ghost** [comment]
Sigh. Does this mean you have plans to monetise kirki in the future by turning every big feature of kirki into a payment upgrade?

**Comment by aristath** [comment]
@cmwwebfx The things that kirki has will always be free, and we'll keep evolving them.

**Comment by dovy** [comment]
@cmwwebfx We'll do the best we can. If you care to donate funds to compensate for the development of said features, then by all means do so. Please don't be upset when we still need to feed our families.  :)

**Comment by dovy** [comment]
And Redux has always been free and we'll keep evolving it as well. As we continually do.

**Comment by ghost** [comment]
Is it going to get the same treatment and have statistics tracking added somewhere in the code? Is it going to get some kind of dashboard widget or tools dashboard that is plastered with redux links and redux extensions in the future? If so, I may as well drop support of kirki from my project now.

**Comment by dovy** [comment]
@cmwwebfx How about we take your personal concerns to email or some other form.  :) You're welcome to email me directly. dovy@reduxframework.com

**Comment by aristath** [comment]
@cmwwebfx some of the features that Redux has and Kirki does not have will at some point be built as premium addons.

The reason behind this is simple... I would never have been able to do it on my own anyways.
The core will remain minimalistic and clean just like it is now.
But some extra advanced fields that will be built by the Redux team will probably be premium and not free.

As for widgets etc no, nothing will be added.
Kirki is not redux, that's not the point of this cooperation.
The point of this cooperation is to grow stronger.
It's not a front for monetization, it's a way to join forces and work together to achieve a better community.
Redux has the developers, kirki has the customizer.
They target different audiences and they don't compete.

**Comment by ghost** [comment]
removed for vulgar language

**Comment by aristath** [comment]
@cmwwebfx so being able to work on this project with more developers is bad?
How is more devs working on a project a bad thing?

**Comment by ghost** [comment]
@aristath I get your point.

**Comment by cmwwebfx** [comment]
Oops sorry Dovy. I didn't realize I was commenting in ReduxFramework repo. Apologies.  I am on my mobile and didn't see the top of the page. My bad.

**Comment by dovy** [comment]
@cmwwebfx can you please be a bit more respectful please? I have done nothing to anger you. Thank you and have a great day.

**Comment by aristath** [comment]
@vasikgreif I'll close this one.

We now have a new API but I don't want to break compatibility with everyone that was using Kirki for the past year.
The settings will be saved in the db the way they are now, and IF the user adds this line somewhere:

``` php
define( 'KIRKI_REDUX_COMPATIBILITY', true );
```

then the output of

``` php
Kirki::get_option()
```

will return a format compatible with redux.

The new docs are available on https://github.com/aristath/kirki/wiki
