### ISSUE TITLE
Choices order of the Multicheck field

### ISSUE THREAD

**Issue by ekapobc** [themeum/kirki#1981]
### Issue description:
I have been using the Multicheck field with the "Kirki_Helper::get_terms()" helper for retrieving the portfolio categories in my themes. I noticed that the field always sorts the choices using the key in the array, not the label. So, the category output seem to be displayed randomly when users see it in the customizer.

In my opinion, the field should display the choices alphabetically using the label. What do you think?

### Version used:
3.0.34

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'uxbarn_theme', array(
	'settings' => 'theme_settings_portfolio_categories',
	'label' => esc_attr__( 'Select Categories', 'domain' ),
	'description' => '',
	'type' => 'multicheck',
	'section' => 'theme_settings_portfolio',
	'default' => array(),
	'choices' => Kirki_Helper::get_terms( array( 
                              'taxonomy' => 'portfolio_terms', 
                              'hide_empty' => false, 
                              'parent' => 0, 
                              'orderby' => 'name', 
                              'order' => 'ASC' ) ),
	'transport' => 'auto',
) );
```
Here is the returned array from the "get_terms()" helper:
```php
array(
 8 => 'Building',
 202 => 'Featured',
 9 => 'Houses',
 10 => 'Interiors',
 11 => 'Others',
)
```
But when it displays in the customizer, it displays like this:
```
Building
Houses
Interiors
Others
Featured
```

**Comment by aristath** [comment]
if you want to change the order of items in your array you're free to do so.
You just have to write a proxy function , convert the keys from integers to strings, and then order by value.
