### ISSUE TITLE
Straight up Borked

### ISSUE THREAD

**Issue by tannercampbell** [themeum/kirki#1983]
Don't know what you all did with this last update, changelog doesn't show anything that would be immediately obvious as the culprit, but it has removed some fields within some sections of the customizer. For me, specifically, within the ttfb.io theme Minimall.

Here's the console error (log file): [https://drive.google.com/file/d/1bEg-8-KB9abRd1CDWUjEqfMY6d0dpWT6/view?usp=sharing](https://drive.google.com/file/d/1bEg-8-KB9abRd1CDWUjEqfMY6d0dpWT6/view?usp=sharing)

Just put me in a work-stop state. Really hoping you can push out a fix sooner rather than later.

**Comment by aristath** [comment]
I suspect this is due to the image control refactor.
Is the theme you're using a free theme I can install and check locally? Or is it a premium one?

**Comment by aristath** [comment]
hmmm can you send me a copy of that theme so I can install it on my localhost and check this out?
With a test theme I'm using I can't find anything wrong, so it must be something I'm overlooking

**Comment by aristath** [comment]
If you want to get back in business you can download the previous version from [https://downloads.wordpress.org/plugin/kirki.3.0.33.zip](https://downloads.wordpress.org/plugin/kirki.3.0.33.zip), but I'd really appreciate a copy of your theme so I can debug this and release an update ASAP

**Comment by tannercampbell** [comment]
Sure can, Aristath. I'm not a regular github user so I don't know the etiquette - is this something I can attach here in the thread or something you'd like a link to. It's a $150 theme so I'd rather not publicize a download link to it - out of respect for the developer.

**Comment by tannercampbell** [comment]
And thank you, yes, I did find 3.0.3.3 on the Worpdress repository, rolled it back almost immediately after writing this ticket and realizing I could.

Let me know what you find!

**Comment by aristath** [comment]
you can just email it to aristath at gmail com.
I'm sure the developers of the theme wouldn't mind in this case since it's for the purposes of debugging kirki with their theme... :+1:

**Comment by tannercampbell** [comment]
I mean linking it here in the thread. I have emailed it over to you with a link to to file on my server. Good luck! And thanks again!

**Comment by aristath** [comment]
@tannercampbell thank you for sending the theme.

Fixed the issue, problem was that on wordpress.org one of the files didn't get uploaded when the plugin was updated.
If you used the github version it was working fine, only difference was a missing file on w.org :face_with_head_bandage: 

I'm uploading a new version on wordpress.org as we speak, should be available in about 10 minutes.

**Comment by tannercampbell** [comment]
Hey bud, I appreciate your work on this. Thanks. Means a lot when devs actively support their works this aggressively. Thanks for being one of the good ones.
