### ISSUE TITLE
A way to use standard font as default font?

### ISSUE THREAD

**Issue by hello-luke** [themeum/kirki#1986]
### Issue description:
I'm trying to set "Sans Serif" standard font as a default font for the Typography field, but can't make it work. The "Font family" field is empty. It populates after selecting and saving/publishing the field. Works smoothly for Google fonts though. Tried to use put both label and stack as a "font-family" value, but with no luck. Any ideas on how to solve it?

### Version used:
3.0.34.1 && develop

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'theme_config', array(
	'type'        => 'typography',
	'settings'    => 'body_font',
	'label'       => esc_attr__( 'Control Label', 'textdomain' ),
	'section'     => 'body_typography_1',
	'default'     => array(
		'font-family'    => 'Sans Serif',
		'font-size'      => '18px',
		'color'          => '#333333',
	),
	'priority'    => 10,
	'output'      => array(
		array(
			'element' => 'body',
		),
	),
) );
```

**Comment by DannyCooper** [comment]
The default needs to be the full value of 'Sans Serif', which is:

`		'font-family'    => '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif',`

**Comment by aristath** [comment]
Or `sans-serif`, that also works :wink:
