### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1990]
Hi Ari!

Is it possible to add add reset button for section / panel only for developers (like old version of Kirki)

**Comment by aristath** [comment]
No, I'm afraid there's no way I'm bringing that back in any form. It had way too many bugs to even consider...
If you want to quickly reset your theme-mods for development/testing purposes you could easily add something like this in your functions.php file, or even in a php file inside your mu-plugins folder:
```php
if ( isset( $_GET['reset-theme-mods'] ) && '1' === $_GET['reset-theme-mods'] ) {
    remove_theme_mods();
}
```

Then you can just add `reset-theme-mods=1` to a URL and your theme-mods will get deleted.
