### ISSUE TITLE
How to use Kirki Module remove_module?

### ISSUE THREAD

**Issue by regenrek** [themeum/kirki#1993]
### Issue description:

I'm wondering how I could remove a module with
the static function remove_module?

The key seems to be removed but the output is still there.
Do I need to wrap some wp hook around it?

### Version used:
3.0.34.1

### Using theme_mods or options?
yes

### Code to reproduce the issue (config + field(s))

functions.php

```
global $kirki;
$kirki->modules::remove_module('Kirki_Modules_CSS_Vars');
```

**Comment by aristath** [comment]
You can use the `kirki_modules` filter from https://github.com/aristath/kirki/blob/v3.0.34/core/class-kirki-modules.php#L60

```php
function my_custom_remove_kirki_module( $modules ) {
	unset( $modules['icons'] );
	return $modules;
}
add_filter( 'kirki_modules', 'my_custom_remove_kirki_module' );
```
