### ISSUE TITLE
Unable to access website on Apple devices

### ISSUE THREAD

**Issue by NaomiDorland** [themeum/kirki#1994]
### Issue description:
I have an odd situation that I am looking for advice on.

I am on Primrose theme and this uses the Kirki plugin.

Last month users started telling me they could not access my site. Basically it wont load. No error comes up, it just won't load.

After a lot of investigation we have narrowed it down to only Apple Users. And then it depends on if they are using chrome or safari and also if they are with Telstra or not!!

I deactivated the Kirki plugin and they can access it again. However, this 'ruins' the layout of my site. Apparently there is a css file from that plugin that isn't loading

Does anyone have any idea what this could be??

My website is www.twinfo.com.au

Many thanks.
Naomi

### Version used:
Version: 3.0.34.1

**Comment by aristath** [comment]
@NaomiDorland unfortunately Primrose is a premium theme I don't have access to.
Can you please try contacting the theme author for this issue? Kirki is just a framework that themes use to build their customizer options. From that point on it all depends on the theme's integration, what options they use and so on.
I would be happy to work with the theme developers on this issue, however without knowing what they do, how they do it, and the actual code they use in their theme, there's not much I can do to help here.

I'll close this ticket for now, but if there are any news from the theme developers please do let me know and I'll gladly reopen it.
