### ISSUE TITLE
Default css output when Kirki is not loaded

### ISSUE THREAD

**Issue by shaylash** [themeum/kirki#1995]
### Issue description:
The spacing default property are not correctly applied when Kirki is not loaded.
```
My_Theme_Kirki::add_field(
	$config_id, array(
		'type'     => 'spacing',
		'settings' => 'btn_spacing',
		'label'    => esc_attr__( 'Spacing', 'text_domain' ),
		'section'  => 'buttons_section',
		'default'  => array(
			'top'    => 'XX',
			'bottom' => 'XX',
			'left'   => 'XX',
			'right'  => 'XX',
		),
		'priority' => 1,
		'output'   => array(
			array(
				'element' => array(
					'.my-button'
				),

				'property' => 'padding',
			),
		),
	)
);
```
Default css applied to .my-button : 
```
.my-button {
   top: XX;
   bottom: XX;
   left: XX;
   right: XX;
}
```
It seems to me that in the class-my-theme-kirki.php in the get_styles method at line 307 
the code should be : 
```
$property = $output['property'] . '-' . $key; 
```
instead of 
```
$output['property'] = $output['property'] . '-' . $key;
```

My question: 
Will Applying the above change break something else I am not aware of or is it safe to apply ?

### Version used:
3.0.34
Yes I am using the develop branch from github

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

Using the class-my-theme-kirki.php, add a spacing field with default as such do not load Kirki Core : 
```
My_Theme_Kirki::add_field(
	$config_id, array(
		'type'     => 'spacing',
		'settings' => 'btn_spacing',
		'label'    => esc_attr__( 'Spacing', 'text_domain' ),
		'section'  => 'buttons_section',
		'default'  => array(
			'top'    => 'XX',
			'bottom' => 'XX',
			'left'   => 'XX',
			'right'  => 'XX',
		),
		'priority' => 2,
		'output'   => array(
			array(
				'element' => array(
					'.my-button'
				),

				'property' => 'padding',
			),
		),
	)
);
```

Thanks for your time and effort on this awesome tool.
Have a good day.

**Comment by niklasp** [comment]
submit a pull request that devs can change it more easily @shaylash

**Comment by DannyCooper** [comment]
Hi @shaylash,

Your defaults should use the full CSS properties. You have:

```
		'default'  => array(
			'top'    => 'XX',
			'bottom' => 'XX',
			'left'   => 'XX',
			'right'  => 'XX',
		),
```

It should be:
```
		'default'  => array(
			'padding-top'    => 'XX',
			'padding-bottom' => 'XX',
			'padding-left'   => 'XX',
			'padding-right'  => 'XX',
		),
```

That way you can remove the `property` from `output` and everything will work.
