### ISSUE TITLE
Import/Export?

### ISSUE THREAD

**Issue by jloft** [themeum/kirki#20]
Are there plans to add a feature for the import/export of Kirki theme customizer options?

**Comment by aristath** [comment]
This is still underconsideration.
However we currently have a solution that sits in an admin page and allows you to import/export customizer theme mods.
See here: https://github.com/wpmu/maera/blob/master/lib/admin-page.php

**Comment by agusmu** [comment]
There is a Customizer Export Import plugin right now, so you can export/import settings directly in your Customizer page.

https://github.com/fastlinemedia/customizer-export-import

**Comment by aristath** [comment]
Closing this one since there's a plugin for that :)
