### ISSUE TITLE
Add "prefix", "suffix" & "calc" arguments to the output array for fields

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#200]
This will allow more complex logic and handling most cases.

Prefix: for example to make the output part of a media query
Suffix: for !important etc
calc: so that the value can be calculated based on a user function before output

**Comment by ghost** [comment]
Pure awesome
thanks Aris

**Comment by aristath** [comment]
Example:

``` php
        'output'      => array(
            'element'  => 'body #page',
            'property' => 'color',
            'prefix'   => '@media ( max-width: 1200px ) {',
            'suffix'   => '}',
            'callback' => 'kirki_twentytwelve_alter_color',
        )
```

and then a dummy callback function could look like this:

``` php
/**
 * Darkens the color a bit
 */
function kirki_twentytwelve_alter_color( $color ) {
    return Kirki_Color::adjust_brightness( $color, -50 );
}
```

**Comment by MikeiLL** [comment]
This looks promising! Going to try using for font-sizing in media queries.

**Comment by MikeiLL** [comment]
NOTE: See [this post](https://github.com/aristath/kirki/issues/585) for updated approach.
