### ISSUE TITLE
CSS output of  `dimensions` field isn't correct with the fallback class

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#2003]
CSS output of  `dimensions` field isn't correct with the fallback class  https://github.com/aristath/kirki/blob/master/docs/files/class-my-theme-kirki.php.

For `padding` it's
```CSS
top: 10px;
right: 10px;
bottom: 10px;
left: 10px;
```

For `border width` it's
```CSS
top-width: 10px;
right-width: 10px;
bottom-width: 10px;
left-width: 10px;
```

For `border radius` it's
```CSS
top-left-radius: 10px;
top-right-radius: 10px;
bottom-left-radius: 10px;
bottom-right-radius: 10px;
```

**Comment by DannyCooper** [comment]
Hi @rahulvermadev,

Could you please clarify what the issue is here?

**Comment by rahulv3a** [comment]
I apologize for a delayed reply.

In the section "A word of caution for themes on wordpress.org" on https://kirki.org/docs/integration, it is recommended to use the fallback class https://github.com/aristath/kirki/tree/master/docs/files/class-my-theme-kirki.php. That class loads webfonts and CSS output when the Kirki is not installed.

If the theme is using fallback class and Kirki is not installed, it adds wrong CSS output for `dimensions` field.

For padding, it adds 
```
top: 10px;
right: 10px;
bottom: 10px;
left: 10px;
```
when it's supposed to add:
```
padding-top: 10px;
padding-right: 10px;
padding-bottom: 10px;
padding-left: 10px;
```
It behaves in a similar way for other CSS properties such as `border width`, `border radius`, etc.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
