### ISSUE TITLE
The fallback class doesn't load Font Awesome

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#2004]
The fallback class (https://github.com/aristath/kirki/blob/master/docs/files/class-my-theme-kirki.php) doesn't load Font Awesome even if the `font-awesome` field is being used.

**Comment by DannyCooper** [comment]
Kirki will no longer be loading FA, ref: https://github.com/aristath/kirki/commit/0bc7f4b93af85e949fe12f9d0c522473ca27a286
