### ISSUE TITLE
Typography color not updating on clear [Fix]

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#2005]
### Issue description:
I noticed the fix for the "clear" button in the color control, but its missing from typography.

I found this in kikri-input.js under color:

				// Tweaks to make the "clear" buttons work.
				setTimeout( function() {
					clear = jQuery( '.kirki-input-container[data-id="' + control.id + '"] .wp-picker-clear' );
					if ( clear.length ) {
						clear.click( function() {
							kirki.setting.set( control.id, '' );
						} );
					}
				}, 200 );

I added this to typography.js:

		// Color.
		if ( 'undefined' !== typeof control.params.default.color ) {
			picker = this.container.find( '.kirki-color-control' );
			picker.wpColorPicker( {
				change: function() {
					setTimeout( function() {
						control.saveValue( 'color', picker.val() );
					}, 100 );
				},
				//Added clear
				clear: function (event) {
					setTimeout( function() {
						control.saveValue( 'color', '' );
					}, 100 );
				}
			} );
		}

Seems to of fixed it for me.

Just thought I'd give a heads up.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Latest

### Using theme_mods or options?
N/A

### Code to reproduce the issue (config + field(s))
N/A

**Comment by DannyCooper** [comment]
@CaptJiggly Is this still an issue in the latest version?

**Comment by CaptJiggly** [comment]
@CaptJiggly At a glance, it looks like you guys have it covered.
