### ISSUE TITLE
how do I add new google fonts?

### ISSUE THREAD

**Issue by aydinvivik** [themeum/kirki#2007]
### Issue description:

Hello,

How do I add new google fonts? for example Niramit : http://prntscr.com/lax6hm

http://prntscr.com/lax6ok

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
**3.0.34.1**

### Using theme_mods or options?
**get_theme_mod**

**Comment by aristath** [comment]
I'm guessing that's a new font that's why it's not yet in the plugin.
If you're using the develop branch you can do `grunt googlefonts` to get the latest fonts.
Otherwise you'll have to wait a bit for the next update since I always update the fonts with each new release.
