### ISSUE TITLE
Kirki specific hook / after to interact with

### ISSUE THREAD

**Issue by craigiswayne** [themeum/kirki#2010]
### Issue description:
Would love the ability to hook into a kirki specific action / hook  that prevents the need for `class_exists` checks

### Version used:
3.0.34.1

### Using theme_mods or options?
n/a

### Code to reproduce the issue (config + field(s))
Was thinking that you could maybe add something along the lines of

```php
//       Snippet from: /kirki/core/class-kirki-init.php:123

/**
* Helper function that adds the fields, sections and panels to the customizer.
*/
public function add_to_customizer() {
  $this->fields_from_filters();
  do_action( 'kirki-hook' ); //this new hook here
  add_action( 'customize_register', array( $this, 'register_control_types' ) );
  add_action( 'customize_register', array( $this, 'add_panels' ), 97 );
  add_action( 'customize_register', array( $this, 'add_sections' ), 98 );
  add_action( 'customize_register', array( $this, 'add_fields' ), 99 );
}
```

Then we could do something along the lines of:

```php
add_action( 'kirki-hook', function(){
         //all kirki stuff here
}
```

Additionally, you could enhance the way you detect how people interact with kirki

I see that in `/core/class-kirki.php:225`

you have this detection: 

```php
if ( doing_action( 'customize_register' ) ) {
   _doing_it_wrong( __METHOD__, esc_attr__( 'Kirki fields should not be added on customize_register. Please add them directly, or on init.', 'kirki' ), '3.0.10' );
}
```

you could essentially change it to the following (if this suggestion is implemented)

```php
if ( !doing_action( 'kirki-hook' ) ) {
   _doing_it_wrong( __METHOD__, esc_attr__( 'Kirki fields should not be added on customize_register. Please add using the "kirki-hook"', 'kirki' ), '3.0.10' );
}
```

Would be happy to submit a PR if this is something worth while,

**Comment by niklasp** [comment]
👍 for pull request

**Comment by aristath** [comment]
tbh I don't see why this would need to be in Kirki.
If that workflow works best for you, then adding the action in your theme is no more than a couple of lines. But there's no reason to force that workflow to everyone... I agree that it would be best practice to do that, but every dev has their own workflow and they are all valid.

**Comment by craigiswayne** [comment]
Appreciate the feedback :) , and you are 100% correct. Wouldn't want to force that sort of workflow upon anyone. Apologies for it coming across that way.

Will be closing off this PR shortly.
