### ISSUE TITLE
Output based on choices

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#2011]
### Issue description:
Is there a way to output based on choices?

For e.g. using the code below would like to have different values outputted.

'square' would output 0px
'rounded' would output 4px
'pill' would output 20px

### Version used:
3.0.34

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Kirki::add_field($opt_name, array(
	'label' => esc_html__('Form input and select style', 'opty'),
	'section' => 'forms_section',
	'settings' => 'form_field_style',
	'type' => 'radio-buttonset',
	'choices' => array(
		'square' => esc_html__('Square', 'opty'),
		'rounded' => esc_html__('Rounded', 'opty'),
		'pill' => esc_html__('Pill', 'opty')
	),
	'default' => 'square',
	'output' => array(
		array(
			'element' => 'input, textarea, select',
			'property' => 'border-radius',
		),
	),
	'transport' => 'auto'
));

**Comment by aristath** [comment]
Sure you can :)

```php
Kirki::add_field( $opt_name, array(
	'label'     => esc_html__('Form input and select style', 'opty'),
	'section'   => 'forms_section',
	'settings'  => 'form_field_style',
	'type'      => 'radio-buttonset',
	'default'   => 'square',
	'transport' => 'auto',
	'choices'   => array(
		'square'  => esc_html__('Square', 'opty'),
		'rounded' => esc_html__('Rounded', 'opty'),
		'pill'    => esc_html__('Pill', 'opty')
	),
	'output'    => array(
		array(
			'element'       => 'input, textarea, select',
			'property'      => 'border-radius',
			'value_pattern' => '0',
			'exclude'       => array( 'rounded', 'pill' ),
		),
		array(
			'element'       => 'input, textarea, select',
			'property'      => 'border-radius',
			'value_pattern' => '4px',
			'exclude'       => array( 'square', 'pill' ),
		),
		array(
			'element'       => 'input, textarea, select',
			'property'      => 'border-radius',
			'value_pattern' => '20px',
			'exclude'       => array( 'square', 'rounded' ),
		),
	),
) );
```
