### ISSUE TITLE
Exclude issue with post message.

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#2015]
### Issue description:

Post message exclude seem to be a little glitchy.

For example:
```
Kirki::add_field( $opt_name, array(
	'label'     => esc_html__('Form input and select style', 'opty'),
	'section'   => 'forms_section',
	'settings'  => 'form_field_style',
	'type'      => 'radio-buttonset',
	'default'   => 'square',
	'transport' => 'auto',
	'choices'   => array(
		'square'  => esc_html__('Square', 'opty'),
		'rounded' => esc_html__('Rounded', 'opty'),
		'pill'    => esc_html__('Pill', 'opty')
	),
	'output'    => array(
		array(
			'element'       => 'input, textarea, select',
			'property'      => 'border-radius',
			'value_pattern' => '0',
			'exclude'       => array( 'rounded', 'pill' ),
		),
		array(
			'element'       => 'input, textarea, select',
			'property'      => 'border-radius',
			'value_pattern' => '4px',
			'exclude'       => array( 'square', 'pill' ),
		),
		array(
			'element'       => 'input, textarea, select',
			'property'      => 'border-radius',
			'value_pattern' => '20px',
			'exclude'       => array( 'square', 'rounded' ),
		),
	),
) );
```
This works perfectly fine with CSS output, but with post message output, the first two options are blank and the final option will output. Eg:

Square and Rounced output:
```
<style id="kirki-postmessage-form_field_style"></style>
```

While Pill outputs:

```
<style id="kirki-postmessage-form_field_style">input, textarea, select{border-radius:0;}input, textarea, select{border-radius:4px;}input, textarea, select{border-radius:20px;}</style>
```

This is only with postmessage. Refresh/CSS output is fine.

Now I'm working on extending Kirki with several new controls in a fork ( color gradient, slider-advanced, typography-advanced, border, sortable w/ text or checkbox and spacing-advanced, toggle-tabs (grouping) ), so I thought I may of broken something, but I uploaded the current kirki/develop to the test project and ran into the same issue.

Any insight on the fix?

Also on another note, once I feel the controls are completed, I'll do a pull request.

**Comment by anthonyryanrusso** [comment]
@aristath Is this something that you could look into today?

**Comment by aristath** [comment]
Can you please try with this branch? https://github.com/aristath/kirki/tree/postMessage-refactor
It's a complete refactor of the postMessage module that I'm working on...

**Comment by CaptJiggly** [comment]
I tried the refactor and it seems to be working fine. I'm working on rewriting the PHP postmessage processors for the custom controls to work with the refactor.

This is quite cleaner too, btw. Nice.

Now question. Since I've been working on the develop branch, should I make a new fork for the postMessage refactor, or is that the only piece of the code that is being worked on? I remember you mentioning it will be merged into Kikri once you feel its right, so should I stay working on develop and collaborate with you once I feel the controls are ready for merging?

Thanks.

**Comment by aristath** [comment]
Closing this one, the `postMessage-refactor` branch was merged.
