### ISSUE TITLE
Typography works on Customizer, but not on the Frontend.

### ISSUE THREAD

**Issue by pupungbp** [themeum/kirki#2016]
### Issue description:
The typography works on the customizer, but when I save and preview it on real page, the fonts don't load. I see the css line is empty on the page I created: <style id="kirki-css-vars">:root{}</style>. I've changed the theme with standard theme just to test, but the result persist.

### Version used:
3.0.34 and Development

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
`Kirki::add_field( 'gracilis_typography', array(
	'type'        => 'typography',
	'settings'    => 'gracilis_typography_body',
	'label'       => esc_attr__( 'Global font for Website', 'gracilis' ),
	'section'     => 'gracilis_cust_typograhpy',
	'default'     => array(
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left',
	),
	'priority'    => 10,
	'choices' => array(
		'fonts' => array(
			'google' => array(
				'Roboto',
				'Open Sans',
				'Lato',
				'Roboto Condensed',
				'Slabo 27px',
				'Montserrat',
				'Oswald',
				'Source Sans Pro',
				'Raleway',
				'PT Sans',
				'Merriweather',
			),
		),
	),
	'output'      => array(
		array(
			'element' => array('body', 'p', '.g-container'),
		),
	),
	'transport'   => 'auto',
	'choices' => array(
		'fonts' => array(
			'google' => array( 'popularity', 30 ),
		),
	),
) );
`

Thanks,

**Comment by aristath** [comment]
Is that by any chance added inside a hook instead of directly? Maybe you're adding it on `customize_register`?

**Comment by pupungbp** [comment]
Thanks for your reply, 
No, this is directly coded. 

Any clue?

**Comment by niklasp** [comment]
is the issue still existing? i think you have to check your css. analyze with browser debugger inspector to see if styles are overridden by custom css values #2026

**Comment by pupungbp** [comment]
No font applied to the text actually, here's the [working demo](http://demo.pupungbp.com/gracilis/), I can provide you a login if you want. Thanks.

**Comment by pupungbp** [comment]
Guys, I finally solved the issue, the issue was seems a bad code on my end, sorry.

**Comment by BeholdPL** [comment]
Hi

I have te same issue. In customizer everything is ok, but after update no fonts are loaded. This is my Kirki code:

```
Kirki::add_field('behold-basic', [
    'type' => 'typography',
    'settings' => 'hero_h1_bigger_typography',
    'label' => esc_html__('Tekst nagłówka większego', 'behold-basic'),
    'section' => 'block_hero',
    'choices' => [
        'fonts' => [
            'standard' => ['Nunito Sans', 'Lato', 'Open Sans', 'Roboto Slab', 'Exo']
            ]
        ],
    'default' => [
        'variant' => '800',
        'font-size' => '48px',
        'line-height' => '1.2',
        'letter-spacing' => '0',
        'color' => '#ffffff',
        'text-transform' => 'uppercase',
    ],
    'priority' => 10,
    'transport' => 'auto',
    'output' => [
        [
            'element' => 'h1.c-header-1 span.c-header-1-big'
        ]
    ]
]);
```

I'm using theme_mods. Also, In console I see this errors like` https://randena.pl/wp-content/uploads/2019/04/pe0qMImSLYBIv1o4X1M8cfe5-8.woff net::ERR_ABORTED 404 (Not Found)`.

Site: [https://randena.pl/](https://randena.pl/)

pls help :)


_**EDIT**_

Ok, now I see that this issue is only when I choose Nunino Sans with variant 700.  I don't know why...
