### ISSUE TITLE
[question] TF compatibility

### ISSUE THREAD

**Issue by danyj** [themeum/kirki#202]
Hello and props for the great simplicity! 
Question , do you know anyone on TF that is using Kirki? Will theme with kirki integrated pass TF requiremants i mean. 

I ran a test on your demo and only issue it came with is  this 

```
REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
```

I guess it is coming from not using sanitize_callback in options on the demo. Other than that looks fine.

**Comment by aristath** [comment]
all controls are properly sanitized, the demo data is just a bit messed-up. :)

**Comment by danyj** [comment]
I did not doubt that , saw you mentioned it somewhere in docs that we can use it if we want to. 
But what about TF?

**Comment by aristath** [comment]
There's a couple themes there that use it, so you should be ok. :)
