### ISSUE TITLE
Kirki-develop file contained virus? 

### ISSUE THREAD

**Issue by ppulpipatnan** [themeum/kirki#2022]
Guys,

I got reported from multiple users about virus alert when including kirki file package. So I made a new download from Github and make full scan here https://www.virustotal.com/#/file-analysis/YTE4OTY1OTUxYzMyY2QxNGRiNWVkZmE3NGMyN2E2YzY6MTU0MjI1NjQwNg==

You can see that it has 1 infected "Trojan/Downloader.vbs".

Is this known issue?

**Comment by niklasp** [comment]
Kaspersky does not report virus and unfortunately virustotal does not tell which file they assume the virus contains. can you help?

**Comment by aristath** [comment]
There is no virus.
This is the version from wordpress.org: https://www.virustotal.com/#/file/6d44d727e812c2502d4e69b4557de7a10764e9f411135d46b2f7189c20cecbda/detection
If you see an error it's just a false positive.
