### ISSUE TITLE
kirki_modules filter broken

### ISSUE THREAD

**Issue by regenrek** [themeum/kirki#2023]
### Issue description:

Hi,

I can't remove a module from kirki_modules. 

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
3.0.34.1

### Code to reproduce the issue (config + field(s))

functions.php
```php
add_filter( 'kirki_modules', function($modules) {
	unset( $modules['css-vars'] );
	return $modules;
});
```

![grafik](https://user-images.githubusercontent.com/5182020/48606166-2f63fb00-e97f-11e8-824a-2a2a0327af0a.png)

**Comment by aristath** [comment]
This was a timing issue.
The methods (and filter) were done on `plugins_loaded` so it was only possible to change them from a plugin, or `mu-plugins`.
I changed their priority and now the modules are loaded on `after_setup_theme`, so it's possible to use the filter from a theme.
