### ISSUE TITLE
Uncaught ReferenceError: WebFont is not defined

### ISSUE THREAD

**Issue by wilrevehl** [themeum/kirki#2025]
### Issue description:
Currently the WebFont init is being called in the head via \kirki\modules\webfonts\class-kirki-modules-webfonts-async.php::136 wp_add_inline_script('webfont-loader', 'WebFont.load...

when we concat and push JS down to the bottom of body, to be deferred, we get the error of Uncaught ReferenceError: WebFont is not defined

Please wrap it in a window/doc.load enclosure if it needs to be in the head. Thanks!

### Version used: 
3.0.34.1
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options? 
mods

### Code to reproduce the issue (config + field(s)) 
Frontend, http://www.therogersco.com/our-work/custom-exhibits/

**Comment by niklasp** [comment]
can you submit a tested PR?

**Comment by timelsass** [comment]
I'm not sure what you have going on in your environment, but the purpose of the async webfont loader is to defer loading of fonts anyways, it can be placed in head or bottom of body and work as intended.

In the file you cited:
https://github.com/aristath/kirki/blob/develop/modules/webfonts/class-kirki-modules-webfonts-async.php#L69-L70

You can see the priorities that are being set for the enqueue - webfont loader followed by the webfont script.

This is the output from the page you referenced:

![image](https://user-images.githubusercontent.com/11907254/48880898-6d7a7800-ede0-11e8-8d8f-52a552d9e66c.png)

The file there 4e8a1e7...js looks like it contains all of the stuff you've concatenated.  You just need to adjust the priority so the inline script added that calls ` WebFont.load` happens afterwards, make it a dep of the concatenated file, or add it to the stuff you're concatenating.

AFAIK an alternative would be loading via the global config ie a global in the window `WebFontConfig`.  The only downside I could see to that is if multiple plugins are using the global config - you might not get the fonts you expected, so using the load method is more reliable in that way.

**Comment by wilrevehl** [comment]
Thanks for the feedback, guys. I'll look into unhooking it from Kirki and
then an enqueue at the bottom. If that's not possible, maybe we'll omit the
Kirki Webfont JS from the compiler/minification.

**Comment by aristath** [comment]
Yead, `remove_action` and then `add_action` would be your safest bet if you want to do that.
Keep in mind however that I'm planning to write a new, custom, lighter implementation for the webfontloader.
Right now it uses the industry-standard library from typekit: https://github.com/typekit/webfontloader
That library is not well-maintained and contains a lot of things that we do not need.
It shall be done, but I don't have an ETA

**Comment by Micemade** [comment]
@aristath : Hi, I'm having the same issue with WebFont Loader. The issues actually popped up just recently (not sure when, but after one of the latest Kirki updates).
Any news on this?
Big thanks.

**Comment by DannyCooper** [comment]
This is no longer an issue as `webfontloader` isn't used on the frontend in the latest versions.
