### ISSUE TITLE
Kirki add html

### ISSUE THREAD

**Issue by niklasp** [themeum/kirki#2027]
What is the correct way to add some arbitrary text to the customizer "main" view?
Currently I am using the code that produces:

```
//Intersection
Kirki::add_section( 'intersection', array(
	'title'          => __( '' ),
	'description'    => __( '' ),
	'type' => 'expanded'
) );

//Needed to show that section?
Kirki::add_field( 'artist_theme_config', array(
	'type'        => 'custom',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'intersection',
	'default'     => esc_html__( 'You can enter custom markup in this control and use it however you want', 'my_textdomain' ),
	'priority'    => 10,
) );
```

taken from some other issue.

<img width="300" alt="bildschirmfoto 2018-11-21 um 15 41 46" src="https://user-images.githubusercontent.com/1685139/48848383-0ccd4a00-eda4-11e8-9201-78866949b373.png">

**Comment by aristath** [comment]
I don't think there's a "right" way to do this... But a couple of times that I needed to do something similar I did what you posted above.
