### ISSUE TITLE
Google Fonts Validation Error

### ISSUE THREAD

**Issue by DeoThemes** [themeum/kirki#2028]
### Issue description:
Kirki is generating validation error, if I set checkbox to load fonts from server instead of CDN.

```
Element style not allowed as child of element body in this context. (Suppressing further errors from this subtree.)

From line 1710, column 1; to line 1710, column 34

↩</main>↩↩<style id="kirki-local-webfonts-">@font-

Contexts in which element style may be used:
Where metadata content is expected.
In a noscript element that is a child of a head element.
Content model for element body:
Flow content.
```

### Version used:
3.0.34.1

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Have you tried the development version from this repository?

**Comment by DeoThemes** [comment]
Hello,
Sorry for late reply. Yes, I've tried, it still shows the same validation error.
