### ISSUE TITLE
Include Auto CSS Output to wp_die / wp-login.php

### ISSUE THREAD

**Issue by Radzio1615** [themeum/kirki#2029]
Hi! Is there a way to include auto CSS output to wp_die function and wp-login.php page?

**Comment by aristath** [comment]
No, but you can easily just get the `theme_mod` values and generate the CSS yourself to enqueue them wherever you want :)

**Comment by JiveDig** [comment]
I needed this too, and was able to do this pretty easily like this:

```
add_action( 'login_head', function() {
	$css = Kirki_Modules_CSS::get_instance();
	$css->print_styles_inline();
});
```

I was hoping to do fonts just as easily but it seemed too tricky so I bailed on it for now.
