### ISSUE TITLE
Repeater field type to support 'active_callback' parameter

### ISSUE THREAD

**Issue by arl1nd** [themeum/kirki#2030]
### Issue description:
I saw this issue is opened before, however I wanted to know if you are planing to implement this feature because it really makes sense!

Thank you a lot.

**Comment by aristath** [comment]
Yes, it makes sense and yes, it will be implemented. But only after v3.1 as this requires a complete refactor of some sub-systems, and a complete rewrite of the repeater control using a new structure.
Right now the repeater is a container for cusotom `<input>` fields. With the new implementation repeaters will be containers for customizer controls so we'll be able to do a lot more stuff with them.
I'll go ahead and close this one as there's nothing special that will have to be done for this to work.
When the refactor is complete this will be automatically taken care of. :+1:

**Comment by sergeysedykh** [comment]
I'd love to have the `active_callback` working in repeaters too. Any details, when the v3.1 might get released? Thanks!

**Comment by aristath** [comment]
Unfortunately there's no ETA yet. 3,1 is a rewrite that I've working on for a while and parts of it are already in all 3.0.x versions, I'm doing it in increments to ensure things get properly tested and there are no backwards-compatibility issues.
In the meantime you could always write your own custom active_callback functions just like you would do for any other WordPress customizer control. :+1:

**Comment by sergeysedykh** [comment]
Thanks for the update! Looking forward to 3.1. Kirki is ❤.
