### ISSUE TITLE
Question about using Multisite and a central Kirki setup over multiple themes...

### ISSUE THREAD

**Issue by bahia0019** [themeum/kirki#2031]
First... am I stupid for attempting this?
Am I going to have issues with Theme Settings and Options?

Context:
I have a multisite setup with multiple users, and they have their choice of themes.
I'd like to keep things as DRY as possible, so where I can, I'd prefer not to duplicate sections that are used on all themes. 
I was thinking about adding all the settings into a central plugin I use for all the core functionality I use over all sites.

Am I tempting fate by doing this? Is there a better solution to what I'm attempting?
Or, am I bound to duplicating things for every single theme I have?

Thanks! And thank you for the product!

**Comment by timelsass** [comment]
That should work fine - the customizer API can be used by themes and plugins, and is what kirki is extending.  You could have all shared logic inside of a plugin, and even have theme specific logic/controls in the themes.  In kirki it supports multiple configurations loading, so just make sure you refer to the right configs when you're trying to reference them (if you need).  In terms of theme mod vs option - it just depends on what you want to do.  A plugin or theme can set either theme mods or options.  Usually anything you want shared between your themes - you'll save those as options, and anything theme specific you save those as theme mods.
