### ISSUE TITLE
Latest version results in syntax error on older PHP versions

### ISSUE THREAD

**Issue by sergeysedykh** [themeum/kirki#2032]
### Issue description:

```
Parse error: syntax error, unexpected ‘::’ (T_PAAMAYIM_NEKUDOTAYIM) in /kirki/modules/gutenberg/class-kirki-modules-gutenberg.php on line 249
```

I know, it's not recommended to use PHP 5 in any way, but there're still so many hosts with the older PHP version.

Would be grateful, if you could check it for compatibility. Many thanks!

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Develop branch

**Comment by sergeysedykh** [comment]
Thanks a lot for fixing it so quickly.

**Comment by suhashininithy** [comment]
Hi., 

i met the same issue , but i met this error on line number 175 KIRKI ver 3.0.36 Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /wp-content/plugins/kirki/modules/gutenberg/class-kirki-modules-gutenberg.php on line 175 http://prntscr.com/mni4rm . Plz rly ASAP !! quite urgent

**Comment by aristath** [comment]
I assume you're using PHP 5.2?
If you check the plugin you'll see that it requires PHP 5.3 and above.
Please update your sever's PHP version, after April not even WordPress will be able to run on anything below PHP 5.6!

**Comment by suhashininithy** [comment]
Hi., 

OK ,Thank you
