### ISSUE TITLE
color-alpha controls don't work unless there's another "color" control in the customizer

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#204]
If we don't have a simple "color" control in the customizer and we add a "color-alpha" control, then the control shows up as a simple text field.

**Comment by marcwiest** [comment]
Yasou aristath, any idea what's causing the issue? I just discovered the bug but couldn't figure it out so far.

**Comment by aristath** [comment]
This has been fixed in the latest dev version. :+1:
