### ISSUE TITLE
typography control js error

### ISSUE THREAD

**Issue by timelsass** [themeum/kirki#2041]
### Issue description:

I could've sworn I just saw something @aristath had noted about an error with the typography control and fonts that didn't have a variant selected, but I can't seem to find it now to reference as it may be related.

If you are using `transport => 'auto'` on the typography field (untested for others) - I get a console error if I have a font and variant selected, and change to one that does not have a variant.

To reproduce:
1 "Open Sans 800" was my default set using auto transport.
2 I switched to "Nothing You Could Do"

```
webfontloader.js?ver=3.0.28:1 GET https://fonts.googleapis.com/css?family=Nothing+You+Could+Do:800&subset=cyrillic,cyrillic-ext,devanagari,greek,greek-ext,khmer,latin,latin-ext,vietnamese,hebrew,arabic,bengali,gujarati,tamil,telugu,thai net::ERR_ABORTED 400
```
^ it looks like the variant is carrying over to the request - as Nothing You Could Do doesn't have a variant specified.  Despite the console error - everything does display correctly even though the response is empty w/ 400.

### Version used:
develop, and 3.0.35.1
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by DannyCooper** [comment]
Confirmed bug and known issue. Also applies when you choose a 'Standard Font' which doesn't need to (and shouldn't) query fonts.googleapis.com.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
