### ISSUE TITLE
Issue with Kirki_Fonts_Google::$force_load_all_variants = true; 

### ISSUE THREAD

**Issue by incify** [themeum/kirki#2046]
### Issue description:
I have set $force_load_all_variants = true;
But it's not load all font variants. Just some variants show http://prntscr.com/lurlye

### Version used:
3.0.35.2

**Comment by DannyCooper** [comment]
Hi @incify,

If this is still an issue, could you please provide your full code so we can try to reproduce the issue.

**Comment by aristath** [comment]
Keep in mind that "all variants" means all variants that exist for the fonts you have selected.
If a font-family doesn't support the `300` font-weight, then of course `300` won't be loaded.

**Comment by DannyCooper** [comment]
The screenshot does look like something is wrong though, as it’s loading 7
italic variants and 1 non-italic for Poppins.

**Comment by DannyCooper** [comment]
This does appear to be working in the most recent versions. If you are experiencing something different please post your code so we can debug.
