### ISSUE TITLE
Color fields - CSS variables

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#2048]
### Issue description:
It would be great if the color fields allows to save colors as CSS variables (which could be chosen like currently selecting from the palette).

**Comment by rahulv3a** [comment]
You could use `output` of `multicolor` field to alter css variables like explained here #2019

**Comment by ArekZw** [comment]
Pay attention to the content in brackets - I would like to be able to choose the color (representing the variable) from the palette under the color picker.
