### ISSUE TITLE
how to disable select2 for select field?

### ISSUE THREAD

**Issue by cloudinstone** [themeum/kirki#2049]
Sometimes, or most times, we don't need select2 for select field, how to disable it?

**Comment by aristath** [comment]
Right now there's no option to disable these. If however you don't need select2, then why not simply use the default WordPress-Core select field?

**Comment by cloudinstone** [comment]
> Right now there's no option to disable these. If however you don't need select2, then why not simply use the default WordPress-Core select field?

why not simply use? because it's not simply. Kirki need to hook to `init` instead of `customize_register`, add control via different hook to same section?  it will make code structure confused and messed.

**Comment by DannyCooper** [comment]
select2 (selectWoo) is already loaded and accessible. So you may as well use it.

Closing this as there doesn't appear to be any interest from the developer or from other users to implement this option.
