### ISSUE TITLE
Front end default value output for the value_pattern of automatic CSS output

### ISSUE THREAD

**Issue by rabindratharu** [themeum/kirki#2052]
### Issue description:
The default values of value_pattern and pattern_replace are not outputting in the front end but its working fine through customizer(back end). Even I tried of your [article](http://aristath.github.io/wordpress/customizer/2017/07/04/customizer-output-part-2.html) for button linear-gradient background. This has the same issue too until and unless you set the new values for the control.

Customizer Output Screenshot:- https://imgur.com/a/q0ADA1p
Front End Output Screenshot:- https://imgur.com/a/kIQlFSA

Likewise, I want to implement box-shadow properties and getting the same issue. The default value is not rendering in the front page until and unless you set new values through customizer.

### Version used:
Plugin Version ( 3.0.34.1)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

       mytheme_add_field(
            array(
                'type'          => 'slider',
                'settings'      => 'mytheme_header_box_shadow_h_offset',
                'section'       => 'mytheme_header_settings_section',
                'label'         => esc_html__( 'Box Shadow', 'mytheme' ),
                'description'   => esc_html__( 'h-offset', 'mytheme' ),
                'default'       => 0,
                'choices'       => array(
                    'min'       => 0,
                    'max'       => 50,
                ),
                'transport'     => 'refresh',
                'output'        =>  array(
                    array(
                        'element'           => array( '.site-header .nav-bar' ),
                        'property'          => 'box-shadow',
                        'value_pattern'     => '$px v-offsetpx blurpx spreadpx color',
                        'pattern_replace'   => array(
                            'v-offset'      => 'mytheme_header_box_shadow_v_offset',
                            'blur'          => 'mytheme_header_box_shadow_blur',
                            'spread'        => 'mytheme_header_box_shadow_spread',
                            'color'         => 'mytheme_header_box_shadow_color',
                        ),
                    ),
                ),
            )
        );
        mytheme_add_field(
            array(
                'type'          => 'slider',
                'settings'      => 'mytheme_header_box_shadow_v_offset',
                'section'       => 'mytheme_header_settings_section',
                'description'   => esc_html__( 'v-offset', 'mytheme' ),
                'default'       => 0,
                'choices'       => array(
                    'min'       => 0,
                    'max'       => 50,
                ),
                'transport'     => 'refresh',
                'output'        =>  array(
                    array(
                        'element'           => array( '.site-header .nav-bar' ),
                        'property'          => 'box-shadow',
                        'value_pattern'     => 'h-offsetpx $px blurpx spreadpx color',
                        'pattern_replace'   => array(
                            'h-offset'      => 'mytheme_header_box_shadow_h_offset',
                            'blur'          => 'mytheme_header_box_shadow_blur',
                            'spread'        => 'mytheme_header_box_shadow_spread',
                            'color'         => 'mytheme_header_box_shadow_color',
                        ),
                    ),
                ),
            )
        );
        mytheme_add_field(
            array(
                'type'          => 'slider',
                'settings'      => 'mytheme_header_box_shadow_blur',
                'section'       => 'mytheme_header_settings_section',
                'description'   => esc_html__( 'blur', 'mytheme' ),
                'default'       => 0,
                'choices'       => array(
                    'min'       => 0,
                    'max'       => 50,
                ),
                'transport'     => 'refresh',
                'output'        =>  array(
                    array(
                        'element'           => array( '.site-header .nav-bar' ),
                        'property'          => 'box-shadow',
                        'value_pattern'     => 'h-offsetpx v-offsetpx $px spreadpx color',
                        'pattern_replace'   => array(
                            'h-offset'      => 'mytheme_header_box_shadow_h_offset',
                            'v-offset'      => 'mytheme_header_box_shadow_v_offset',
                            'spread'        => 'mytheme_header_box_shadow_spread',
                            'color'         => 'mytheme_header_box_shadow_color',
                        ),
                    ),
                ),
            )
        );
        mytheme_add_field(
            array(
                'type'          => 'slider',
                'settings'      => 'mytheme_header_box_shadow_spread',
                'section'       => 'mytheme_header_settings_section',
                'description'   => esc_html__( 'spread', 'mytheme' ),
                'default'       => 0,
                'choices'       => array(
                    'min'       => 0,
                    'max'       => 50,
                ),
                'transport'     => 'refresh',
                'output'        =>  array(
                    array(
                        'element'           => array( '.site-header .nav-bar' ),
                        'property'          => 'box-shadow',
                        'value_pattern'     => 'h-offsetpx v-offsetpx blurpx $px color',
                        'pattern_replace'   => array(
                            'h-offset'      => 'mytheme_header_box_shadow_h_offset',
                            'v-offset'      => 'mytheme_header_box_shadow_v_offset',
                            'blur'          => 'mytheme_header_box_shadow_blur',
                            'color'         => 'mytheme_header_box_shadow_color',
                        ),
                    ),
                ),
            )
        );
        mytheme_add_field(
            array(
                'type'          => 'color',
                'settings'      => 'mytheme_header_box_shadow_color',
                'section'       => 'mytheme_header_settings_section',
                'description'   => esc_html__( 'color', 'mytheme' ),
                'default'       => 'rgba(0,0,0,.05)',
                'choices'       => array(
                    'alpha'     => true,
                ),
                'transport'     => 'refresh',
                'output'        =>  array(
                    array(
                        'element'           => array( '.site-header .nav-bar' ),
                        'property'          => 'box-shadow',
                        'value_pattern'     => 'h-offsetpx v-offsetpx blurpx spreadpx $',
                        'pattern_replace'   => array(
                            'h-offset'      => 'mytheme_header_box_shadow_h_offset',
                            'v-offset'      => 'mytheme_header_box_shadow_v_offset',
                            'blur'          => 'mytheme_header_box_shadow_blur',
                            'spread'        => 'mytheme_header_box_shadow_spread',
                        ),
                    ),
                ),
            )
        );

**Comment by aristath** [comment]
Are you by any chance adding these inside a callback on `customize_register` or something like that?

**Comment by pierreamgabriel** [comment]
Did you solve this? I'm facing the same problem. The default values of value_pattern are outputting correctly but I can't say the same for pattern_replace.

**Comment by pierreamgabriel** [comment]
~~Since it will output in the front end ONLY when one of the default values have been changed in the customizer, the solution I found was to create a function to check if the values remain the same and so use wp_head to print the necessary CSS in the head.~~

**Comment by pierreamgabriel** [comment]
~~Well, the above solution won't work because the problem is with the first control. Let me explain what I'm trying to do. I'm trying to implement a radial gradient, so it has two colors. I follow your guide where you say:~~

> As you can see in the example above, the output argument for all the fields in similar.

~~That's the problem. With two controls outputting the same element, only the second color (second control) is being outputted UNTIL the default color of the first control is changed. So the solution is simply outputting the element in only one control, like this:~~

```
Kirki::add_field( 'theme_config', [
	'type'        => 'color',
	'settings'    => 'home_header_top_bg3_color1',
	'label'       => __( 'Gradient background 03: primary color', '' ),
	'description' => esc_html__( '', '' ),
	'section'     => 'home_header_color',
	'default'     => '#2f2e34',
	'output'    => array(
	array(
			'element'  => '.home-header-background3',
			'property' => 'background',
		),
	array(
		'element'         => '.home-header-background3',
		'property'        => 'background',
		'value_pattern'   => '-moz-radial-gradient(circle, $ 0%, bg3second 50%)',
		'pattern_replace' => array(
			'bg3second'    => 'home_header_top_bg3_color2',
		),
	),
	array(
		'element'         => '.home-header-background3',
		'property'        => 'background',
		'value_pattern'   => '-webkit-radial-gradient(circle, $ 0%, bg3second 50%)',
		'pattern_replace' => array(
			'bg3second'    => 'home_header_top_bg3_color2',
		),
	),
	array(
		'element'         => '.home-header-background3',
		'property'        => 'background',
		'value_pattern'   => 'radial-gradient(circle, $ 0%, bg3second 50%)',
		'pattern_replace' => array(
			'bg3second'    => 'home_header_top_bg3_color2',
		),
	),
	array(
		'element'         => '.home-header-background3',
		'property'        => 'filter',
		'value_pattern'   => 'progid:DXImageTransform.Microsoft.gradient(startColorstr=" $ ",endColorstr=" bg3second ",GradientType=1)',
		'pattern_replace' => array(
			'bg3second'    => 'home_header_top_bg3_color2',
		),
	),
),
] );
Kirki::add_field( 'theme_config', [
	'type'        => 'color',
	'settings'    => 'home_header_top_bg3_color2',
	'label'       => __( 'Gradiente background 03: secondary color', '' ),
	'description' => esc_html__( '', '' ),
	'section'     => 'home_header_color',
	'default'     => '#16151a',
] ); 
```

**Comment by pierreamgabriel** [comment]
Oh well I gave up. The second solution I posted here won't work either. Now, only the first color is being outputted, until the default second color is changed. Somehow, pattern_replace isn't working with default values.

**Comment by aristath** [comment]
@rabindratharu @pierremacedo I pushed a commit that seems to fix the issue on my test installation, if you want you can test the version from this repository. :+1:
