### ISSUE TITLE
Switch class with toggle control

### ISSUE THREAD

**Issue by viet34tqc** [themeum/kirki#2053]
### Issue description:
I'm trying to switch class named 'sticky-header' using your code from this issue: https://github.com/aristath/kirki/issues/1679, but it seems doesn't work. Is this code deprecated?

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'my-config', array(
	'type'        => 'toggle',
	'settings'    => 'sticky_header',
	'label'       => esc_html__( 'Sticky Header', 'blogz' ),
	'description' => esc_html__( 'Always show the main navigation when scroll down pages.', 'blogz' ),
	'section'     => 'general',
	'default'     => '1',
	'transport' => 'postMessage',
	'js_vars'     => array(
		array(
			'element'  => 'body',
			'function' => 'toggleClass',
			'class'    => 'sticky-header',
			'value'    => true,
		),
	),
) );
```

**Comment by aristath** [comment]
@viet34tqc the code was not deprecated, but it was on a separate branch (one where I was refactoring the `postMessage` module) and it was only merged a few days ago - it will be included in version 3.0.36
Can you try it now using the develop branch? It _should_ be working

**Comment by viet34tqc** [comment]
Thank you for your information, I will give it a try. I'm developing a theme using Kirki, hope that will be updated soon on WordPress.org.

**Comment by DannyCooper** [comment]
@viet34tqc Did it work when you tried the more recent version?

**Comment by DannyCooper** [comment]
Confirmed working in https://github.com/aristath/kirki/issues/1679
