### ISSUE TITLE
Can I use 'settings' argument of a field (control) as an array?

### ISSUE THREAD

**Issue by tisu19021997** [themeum/kirki#2056]
### Issue description:
I am trying to use `settings` argument as an array and it returns an error.
```
Warning: strtolower() expects parameter 1 to be string, array given in C:\xampp\htdocs\mytheme\wp-includes\formatting.php on line 1870

Warning: Illegal offset type in C:\xampp\htdocs\mytheme\wp-content\plugins\kirki\core\class-kirki-field.php on line 331
```
As I have tried, I could add `settings` as an array when using traditional way like: `$wp_customize->add_control` .
### Version used:
3.0.34.1 
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
Theme_mods

### Code to reproduce the issue (config + field(s))
**My field**
```
Kirki::add_field('mytheme', array(
    'type' => 'text',
    'settings' => array('example-text','example-2-text'),
    'section' => 'mytheme_section',
    'label' => esc_html__('Example', 'mytheme),
    'description' => esc_html__('Example description.', 'mytheme'),
    'priority' => 10,
    'default' => '',
));
```
**My config**
```
Kirki::add_config('mytheme', array(
    'capability' => 'edit_theme_options',
    'option_type' => 'theme_mod'
));
```

**Comment by aristath** [comment]
@tisu19021997 no, currently you can't use `settings` as an array.
This has never been requested before... If I may ask why do you want this as an array? What is the scenario?

**Comment by tisu19021997** [comment]
I wanna make a custom field that looks much like Kirki's`typography` field. The only difference is that it uses **Typekit** instead of **Google Font**. I am currently stuck at creating multiple `input` in one **Customize Control** via **Kirki**. Therefore, I am trying to split it into multiple `settings` that I can use as an array when rendering into html `input`, `select`, ....

I have read the source code of `class-kirki-control-typography.php` and tried to use `content_template()` function to do such thing, but It didn't work.

Is there any document to create such field like `typography`? If not, and if you have time, can you show me the way to create one? Many thanks, @aristath .

**Comment by aristath** [comment]
Steps to easily clone the typography control as a custom control you can then tweak:

1. copy the `controls/php/class-kirki-control-typography.php` file somewhere. Let's say you call it `class-kirki-control-my-custom-typography.php`
2. Open the file and rename the class. For this example I'll rename `Kirki_Control_Typography` to `Kirki_Control_My_Custom_Typography`.
3. rename the control type in the control's class from `kirki-typography` to `my-custom-typography`.
4. Register the new control in Kirki:
```php
if ( ! function_exists( 'register_my_custom_control' ) ) {
	/**
	 * Registers the control with Kirki.
	 * 
	 * @since 1.0
	 * @param array $controls An array of controls registered with the Kirki Toolkit.
	 * @return array
	 */
	function register_my_custom_control( $controls ) {

		// Require the PHP class.
		if ( ! class_exists( 'Kirki_Control_My_Custom_Typography' ) ) {
			require_once 'class-kirki-control-my-custom-typography.php';
		}

		// Add control.
		$controls['my-custom-typography'] = 'Kirki_Control_My_Custom_Typography';
		return $controls;
	}
}
add_filter( 'kirki_control_types', 'register_my_custom_control' );
```
Notice that `my-custom-typography` is the name I defined earlier inside the control's class.
5. Make the control eligible for JS templating:
```php
if ( ! function_exists( 'register_my_custom_control_type' ) ) {
	/**
	 * Registers the control type and make it eligible for
	 * JS templating in the Customizer.
	 * 
	 * @since 1.0
	 * @param object $wp_customize The Customizer object.
	 * @return void
	 */
	function register_my_custom_control_type( $wp_customize ) {

		// Require the PHP class.
		if ( ! class_exists( 'Kirki_Control_My_Custom_Typography' ) ) {
			require_once 'class-kirki-control-my-custom-typography.php';
		}

		// Register the control in the WordPress Customizer.
		$wp_customize->register_control_type( 'Kirki_Control_My_Custom_Typography' );
	}
} 
add_action( 'customize_register', 'register_my_custom_control_type' );
```
6. Copy the control's JS from `controls/js/src/typography.js` and enqueue it in your custom-control's class.
7. In the JS file remember to rename the field-type in the 1st line from `wp.customize.controlConstructor['kirki-typography']` to `wp.customize.controlConstructor['my-custom-typography']`

I think these are the basics... Let me kknow if you have any issues.
