### ISSUE TITLE
3.0.35.3 color control in repeater issues

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#2059]
### Issue description:
When updating from 3.0.33 to 3.0.35.3 the color field breaks inside of a repeater.

With the color field set to empty as default:
- The field auto-sets to #ffffff even though it should be set to nothing
- When you select a color in the color control it changes, but when you try to empty the field it doesn't reload and the color stays
- The color field says "Hex Value" in the color field when nothing is set 
- When saving all repeater color items ends up with #ffffff as set color

### Version used:
Version 3.0.35.3

### Code to reproduce the issue (config + field(s))
I've emailed you the theme and code where you can test it. If you need any other information, please tell.

**Comment by aristath** [comment]
> The field auto-sets to #ffffff even though it should be set to nothing

fixed

> The color field says "Hex Value" in the color field when nothing is set

fixed

> When saving all repeater color items ends up with #ffffff as set color

fixed

> When you select a color in the color control it changes, but when you try to empty the field it doesn't reload and the color stays

This will be an issue. Unfortunately I can't fix this with the current repeater structure, this will have to wait for the repeater rewrite - at which point it will be automatically fixed

**Comment by AlxMedia** [comment]
Nice! Well the last one isn't that big of a deal as long as the other ones are fixed :-) When do you think this fixed version will be released? Should I wait for it or simply apply the fixes you've done for now?

Edit: Updated and tested the code with your fix and it works. Thanks.

**Comment by aristath** [comment]
> When do you think this fixed version will be released?

v3.0.36 contains a complete rewrite of the postMessage module. I've been working on it for about a year and I believe it's OK. If Kirki were not so popular probably wouldn't hesitate to release it right now, however I think I'll leave it in the develop branch for at least another week, see if any theme developers report any bugs etc with the new implementation :+1:

**Comment by AlxMedia** [comment]
Awesome 👍

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
