### ISSUE TITLE
Automatic output of CSS 

### ISSUE THREAD

**Issue by DanyDD** [themeum/kirki#2060]
Hi! Thank you for the amazing plugin.

I noticed that as soon as I add typography controls, the CSS is outputted automatically. 

I was wondering if there was a way of doing it only if the user changes the default setting because right now it's just duplicate of the same code.

I found that it worked if I add a "switch" or a "toggle" and make the typography conditional to the switch being activated but that would mean adding switches to everything.

Thanks!

**Comment by DanyDD** [comment]
Also, is there a reason why my "publish" button gets activated as soon as I go on a section with a typography control even if no changes were made? Like I have to publish every time.

**Comment by aristath** [comment]
By default the output would look like this:
```php
'output' => [
	[
		'element' => 'body',
	],
],
```

It is possible to exclude css for default values, but you'd have to separate each property in the output and write something like this:

```php
'output' => [
	[
		'element'  => 'body',
		'property' => 'font-family',
		'choice'   => 'font-family',
		'exclude'  => [ 'Roboto' ],
	],
	[
		'element'  => 'body',
		'property' => 'font-size',
		'choice'   => 'font-size',
		'exclude'  => [ '1em' ],
	],
	[
		......
	]
]
```

**Comment by DanyDD** [comment]
Perfect, exactly what I needed. Thanks!
