### ISSUE TITLE
phpcs no longer executes

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2062]
This has baffled me for quite some time now.
PHPCS no longer runs. Both on local (ubuntu) and on travis it doesn't seem to actually be running.
I've tried everything I can think of and though it's probably something simple I just can't find it.
@jrfnl any ideas on what might be going on here? I'm asking since you did a lot of the work in the cs files and all related areas here

To test:
* clone the repo
* composer install
* `vendor/bin/phpcs -v`

It doesn't throw any errors, but even this doesn't do anything `vendor/bin/phpcs --help` and that is certainly weird. :thinking:

**Comment by jrfnl** [comment]
@aristath I've had a quick look and found the following:
1. Your `composer.lock` file is out of sync.
2. You need to update your dependencies: `composer update --with-dependencies phpcompatibility/phpcompatibility-wp wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer`
3. And this is the real cause (and don't ask me why, I didn't dig any deeper): your `autoload` directive in your `composer.json` file is blocking PHPCS from loading. If you remove that `autoload` directive, everything starts working again.
So, I suggest you read up on configuring that better: https://getcomposer.org/doc/04-schema.md#autoload

**Comment by aristath** [comment]
thank you for taking a look, I appreciate it!

**Comment by jrfnl** [comment]
Oh and I just realize that you can ignore the first two points as the `composer.lock` file is not committed, but I still had an old one hanging around in my local clone ;-)

**Comment by aristath** [comment]
Brilliant, it was the `autoload`. Thanks!
