### ISSUE TITLE
Number Field accept text as input as well.

### ISSUE THREAD

**Issue by viet34tqc** [themeum/kirki#2064]
### Issue description:
As you can see in this [picture](https://i.imgur.com/u1zrCKw.png), I can put some text into number field and save it. Do I have any configuration errors?
When I put number into that field then var_dump the value, the type of that value is String. Is this normal behaviour? Do I have to use any sanitization callback function? https://i.imgur.com/5pXpQAd.png

And another question, I want to validate the field using validate_callback argument from WordPress Customizer, but it's not working. Does Kirki support it?

### Version used:
I'm using the latest version from WordPress.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field(
	'blogz',
	array(
		'type'     => 'number',
		'settings' => 'excerpt_length',
		'label'    => esc_html__( 'Excerpt Length', 'blogz' ),
		'section'  => 'homepage',
		'default'  => 24,
		'choices'  => array(
			'min'  => 0,
			'max'  => 40,
			'step' => 1,
		),
                'validate_callback' => function ( $validity, $value ) {
			if ( 0 !== $value % 2 ) {
				$validity->add( 'not_valid', __( 'Please use an even number' ) );
			}
			return $validity;
		}
	)
);
```

**Comment by aristath** [comment]
Fixed.
Thank you for reporting this :+1:
