### ISSUE TITLE
required conditions inline style when hidden

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#2065]
### Issue description:
I am adding some additional styling to a couple of controls and one of them requires a display property change.  If I add a display property it gets overridden by the inline style.

To fix this if you could change the inline style of hidden required fields from "display: none;" to "display: none !important;" --- this shouldn't cause any other issues on your side but it would definitely fix the issue I am having.

**Comment by aristath** [comment]
Kirki doesn't actually change the CSS for hidden fields... We use the WordPress Customizer's API to [activate and deactivate controls contextually](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#contextual-panels-sections-and-controls) so these `display:hidden` are coming from WordPress Core's JS.

Is there no other way to achieve what you need besides changing the display styles?
