### ISSUE TITLE
How to load a javascript event handler on a radio buttonset button

### ISSUE THREAD

**Issue by moonsoup** [themeum/kirki#2066]
### Issue description:
I need to optionally load a button set based off of the input of another buttonset. If one radio buttonset is set to "Banner" I need the second radio buttonset section (add_field) to appear.
.... using jQuery 
Maybe I need to use a callback somewhere...how do I...um...what...? Got a document I can read?

### Code to reproduce the issue (config + field(s)) 
// (loaded via customize_controls_print_footer_scripts hook)...(and it works when I load it after the page is loaded ...as if the event handler is being overwritten on page load)
jQuery(document).ready( function(){
if( !jQuery("#input_fp-banner-toggle .switch-label:contains('Banner')").prev(".switch-input").is(":checked") ){
 jQuery("#customize-control-header-size").css({"display":"none"});
} 
jQuery("#input_fp-banner-toggle .switch-label").click( function(){   
	console.log(jQuery(this).text());
if(jQuery(this).text() == 'Banner' ) { 
 jQuery("#customize-control-header-size").slideDown(); 
	
}else{
 jQuery("#customize-control-header-size").slideUp(); 
}
});
	
});

**Comment by aristath** [comment]
If all you need is fields cross-dependencies then you can use the `active_callback` argument in your fields: https://aristath.github.io/kirki/docs/arguments/active_callback.html

For your purposes this should do just fine.

Generally though you can listen for changes to controls using the code from here: https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#preview-js-and-controls-js
and to show/hide controls https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#contextual-panels-sections-and-controls

**Comment by entity-framework-corebio** [comment]
@aristath https://carstensecretion5.github.io/zxNnHF30jkGD_uP-F5v5UueiW97Yl3uipt4hWcpV7sNY3nPzUE0IXHeyCw/
