### ISSUE TITLE
Live preview feature applies changes permanently without pressing the Publish button, and other bugs

### ISSUE THREAD

**Issue by pierreamgabriel** [themeum/kirki#2069]
### Issue description:
So, I can't get live preview to work properly, I'm even thinking about disabling if it's possible. First problem I noticed is that some changes are permanently applied in the Customizer side. For example, I have a text field to store Font Awesome icon names and it has a "lightbulb" value in it. In the front end, the lightbulb icon is showing correctly, but in the Customizer I see a "quote-left" icon that I had previously tested. Refreshing the page doesn't work, the "quote-left" is still there. Another problem is changes being applied in the front end without pressing the Publish button. For this one, I share detailed code below.

So, there are areas in my theme where it's possible to enter either text or HTML code. To enable/disable each one, I use Kirki checkbox and an if statement in the appropriate files.

```
Kirki::add_config( 'my_theme_config', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );
Kirki::add_field( 'my_theme_config', [
	'type'     => 'textarea',
	'settings' => 'about_s1_text',
	'label'    => esc_html__( 'Text', '' ),
	'section'  => 'about_s1',
	'default'  => esc_html__( '', '' ),
	'priority' => 10,
	'active_callback' => [
		[
			'setting'  => 'about_s1_html_enable',
			'operator' => '==',
			'value'    => false,
		]
	],
] );
Kirki::add_field( 'my_theme_config', [
	'type'        => 'code',
	'settings'    => 'about_s1_html',
	'label'       => esc_html__( 'Text/HTML', '' ),
	'description' => esc_html__( '', '' ),
	'section'     => 'about_s1',
	'default'     => '',
	'choices'     => [
		'language' => 'html',
	],
	'active_callback' => [
		[
			'setting'  => 'about_s1_html_enable',
			'operator' => '==',
			'value'    => true,
		]
	],
] );
Kirki::add_field( 'my_theme_config', [
	'type'        => 'checkbox',
	'settings'    => 'about_s1_html_enable',
	'label'       => esc_html__( 'Insert arbitrary HTML code.', 'valhalla' ),
	'description' => esc_html__( 'Check this option if you want the above field to be able to accept HTML code.', 'valhalla' ),
	'section'     => 'about_s1',
	'default'     => false,
] );
```
```
<?php if ( true == get_theme_mod( 'about_s1_html_enable', true ) ) : ?>
   <?php echo get_theme_mod( 'about_s1_html', '' ); ?>
<?php else : ?>
   <p><?php echo esc_html( get_theme_mod( 'about_s1_text', '' ) ); ?></p>
<?php endif; ?>
```
When I check the checkbox "Insert arbitrary HTML code", everything works properly in the Customizer previewer, but what should be temporary changes, are applied in the front end as well, like I said, without pressing the Publish button. To solve this, I need to check/uncheck the checkbox and then press publish. 
### Version used:
3.0.35.3

### Using theme_mods or options?
theme_mods

**Comment by sebrosen** [comment]
In your add_field for "about_s1_html_enable" you set the default to false but in your get_theme_mod you set the default to true. That's why you have to check/uncheck.. if the default should be false then change get_theme_mod to:

`<?php if ( true == get_theme_mod( 'about_s1_html_enable', false) ) : ?>`

**Comment by aristath** [comment]
I can confirm that what @sebrosen posted above is the cause of the issue.
@pierremacedo if you change that one thing on your code everything works fine :+1:
