### ISSUE TITLE
[suggestion] Add optional input option to sliders

### ISSUE THREAD

**Issue by danyj** [themeum/kirki#207]
Current range slider allow  only drags without user input , 
http://prntscr.com/6xo1p6

something like this comes in handy when user knows the value he/she wishes to input 

http://prntscr.com/6xo0uw

**Comment by ghost** [comment]
#Dan you hit the nail on the head mate.  I was trying to find this option only lay night in the docs and in the examples since it is easier to sometimes simply put the value and yet still have the slider.  Nice mockup BTW

**Comment by danyj** [comment]
thnx but i cant take props for the look 
http://ionden.com/a/plugins/ion.rangeSlider/en.html

I enhanced default unyson option and added input on the side

**Comment by LuisAlejandre** [comment]
I´m following this. I´d also thought that the ability to directly type in the value you want was a missing feature.

**Comment by aristath** [comment]
Have you found any scripts that allow something like this?
I'd love to add this, but so far couldn't find any scripts that allow it

**Comment by LuisAlejandre** [comment]
Hi, Aris.

No, unfortunately I have no idea about how to do it (otherwise I would have suggested it).

By the way, do you have a donate button? I´m willing to give something back for all your hard and awesome work.

Thanks,

Luis
