### ISSUE TITLE
Empty Kirki Stylesheet by default

### ISSUE THREAD

**Issue by ather16** [themeum/kirki#2071]
### Issue description:
There seems a bug in kirki latest stable version. when a theme is install first time the kirki stylesheet is blank its get updated only when the user edit something via customizer then it generates the styles.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Not yet

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
add_filter( 'kirki/dynamic_css/method', function() {
    return 'file';
});

**Comment by aristath** [comment]
Try the develop branch.

**Comment by ather16** [comment]
Yes its work in Develop Version. 

Does it also prefix the css for gutenberg blocks like ".editor-styles-wrapper .editor-writing-flow" it does not seems working for me

**Comment by DannyCooper** [comment]
Closed as the original issue has been solved. For further issues please create a new issue as that makes them easier to manage and reference.
