### ISSUE TITLE
Add ability to change css output slug

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#2073]
### Issue description:
I like the new css output, however I would like to change the slug from "kirki-styles" to something else.  Is it possible for you to add a filter so this is possible?

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
dev

### Using theme_mods or options?
n/a

### Code to reproduce the issue (config + field(s))
n/a

**Comment by aristath** [comment]
Done, you an now use the `kirki_styles_action_handle` filter. :+1:

**Comment by CaptJiggly** [comment]
Hey @aristath , I noticed while the URL slug is changed, the stylesheet ID is the same.

```
		// Enqueue the dynamic stylesheet.
		wp_enqueue_style(
			'kirki-styles',
			add_query_arg(...),
			array(),
			KIRKI_VERSION
		);
```

Instead of 

```
		// Enqueue the dynamic stylesheet.
		wp_enqueue_style(
			apply_filters( 'kirki_styles_action_handle', 'kirki-styles' ),
			add_query_arg(...),
			array(),
			KIRKI_VERSION
		);
```
