### ISSUE TITLE
Pattern_replace and transport auto not working

### ISSUE THREAD

**Issue by sebrosen** [themeum/kirki#2074]
### Issue description:
I have two fields, one for box shadow color and another for the shadow size. When using pattern replace and transport auto, the color doesn't change until I change the shadow size as well.

### Version used:
Version 3.0.35.3

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'sitka_config', array(
	'type'        => 'color',
	'settings'    => 'sitka_colors_header_shadow',
	'label'       => esc_html__( 'Header Box Shadow Color', 'sitka' ),
	'section'     => 'sitka_section_colors_header',
	'priority' => 10,
	'default'     => 'rgba(0,0,0,.09)',
	'choices'     => array(
		'alpha' => true,
	),
	'output'    => array(
		array(
		  'element'       => '#header',
		  'property'      => 'box-shadow',
		  'value_pattern' => '0 0 shadow_size $',
		  'pattern_replace' => array(
				'shadow_size'    => 'sitka_colors_header_shadow_size',
			),
		),
	),
	'transport' => 'auto'
) );
```

```
Kirki::add_field( 'sitka_config', array(
	'type'        => 'number',
	'settings'    => 'sitka_colors_header_shadow_size',
	'label'       => esc_html__( 'Header Box Shadow Size', 'sitka' ),
	'section'     => 'sitka_section_colors_header',
	'description' => esc_html__( 'Default: 30px', 'sitka' ),
	'default'     => 30,
	'choices'     => array(
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	),
	'output'      => array(
		array(
		  'element'       => '#header',
		  'property'      => 'box-shadow',
		  'value_pattern' => '0 0 $px shadow_color',
		  'pattern_replace' => array(
				'shadow_color'    => 'sitka_colors_header_shadow',
			),
		),
	),
	'transport' => 'auto',
	'priority'    => 15,
) );
```

**Comment by aristath** [comment]
Can you please try the version from this github repository? If I'm not mistaken I pushed a fix for this a couple of days ago

**Comment by sebrosen** [comment]
Unfortunately the issue is still there

**Comment by sebrosen** [comment]
Any updates on this one? The issue is especially apparent when trying to use two color settings to make a gradient.

Example:

```
Kirki::add_field( 'sitka_config', array(
	'type'        => 'color',
	'settings'    => 'sitka_colors_post_style5_bg_top',
	'label'       => esc_html__( 'Style 5: Header BG Gradient (Top Color)', 'sitka' ),
	'section'     => 'sitka_section_colors_post_header',
	'default'     => '#f8f8f8',
	'priority'    => 37,
	'output'    => array(
		array(
		  'element'       => '.bg-color-header',
		  'property'      => 'background',
		  'value_pattern' => 'linear-gradient(to bottom, $ 0%, bottom_color 100%)',
		  'pattern_replace' => array(
				'bottom_color'    => 'sitka_colors_post_style5_bg_bottom',
			),
		),
	),
	'transport'	  => 'auto'
) );
Kirki::add_field( 'sitka_config', array(
	'type'        => 'color',
	'settings'    => 'sitka_colors_post_style5_bg_bottom',
	'label'       => esc_html__( 'Style 5: Header BG Gradient (Bottom Color)', 'sitka' ),
	'section'     => 'sitka_section_colors_post_header',
	'default'     => '#e9e9e9',
	'priority'    => 38,
	'output'    => array(
		array(
		  'element'       => '.bg-color-header',
		  'property'      => 'background',
		  'value_pattern' => 'linear-gradient(to bottom, top_color 0%, $ 100%)',
		  'pattern_replace' => array(
				'top_color'    => 'sitka_colors_post_style5_bg_top',
			),
		),
	),
	'transport'	  => 'auto'
) );
```

**Comment by DannyCooper** [comment]
> Any updates on this one? The issue is especially apparent when trying to use two color settings to make a gradient.
> 
> Example:
> 
> ```
> Kirki::add_field( 'sitka_config', array(
> 	'type'        => 'color',
> 	'settings'    => 'sitka_colors_post_style5_bg_top',
> 	'label'       => esc_html__( 'Style 5: Header BG Gradient (Top Color)', 'sitka' ),
> 	'section'     => 'sitka_section_colors_post_header',
> 	'default'     => '#f8f8f8',
> 	'priority'    => 37,
> 	'output'    => array(
> 		array(
> 		  'element'       => '.bg-color-header',
> 		  'property'      => 'background',
> 		  'value_pattern' => 'linear-gradient(to bottom, $ 0%, bottom_color 100%)',
> 		  'pattern_replace' => array(
> 				'bottom_color'    => 'sitka_colors_post_style5_bg_bottom',
> 			),
> 		),
> 	),
> 	'transport'	  => 'auto'
> ) );
> Kirki::add_field( 'sitka_config', array(
> 	'type'        => 'color',
> 	'settings'    => 'sitka_colors_post_style5_bg_bottom',
> 	'label'       => esc_html__( 'Style 5: Header BG Gradient (Bottom Color)', 'sitka' ),
> 	'section'     => 'sitka_section_colors_post_header',
> 	'default'     => '#e9e9e9',
> 	'priority'    => 38,
> 	'output'    => array(
> 		array(
> 		  'element'       => '.bg-color-header',
> 		  'property'      => 'background',
> 		  'value_pattern' => 'linear-gradient(to bottom, top_color 0%, $ 100%)',
> 		  'pattern_replace' => array(
> 				'top_color'    => 'sitka_colors_post_style5_bg_top',
> 			),
> 		),
> 	),
> 	'transport'	  => 'auto'
> ) );
> ```

This code is tested and working in both the current `master` and `develop` branches.
