### ISSUE TITLE
Feature request: Accordions

### ISSUE THREAD

**Issue by sebrosen** [themeum/kirki#2075]
It would be really nice if we could have fields inside accordions. Here's an example:

![accordion](https://user-images.githubusercontent.com/2302270/52151197-1e925f80-2627-11e9-9f9c-a40aed1ae0e2.png)

What do you guys think?

Maybe an idea for a premium control :-)

**Comment by aristath** [comment]
This feature is planned, but only after v4.0 is released so it can be built as a separate package. The v4.0 rewrite is already underway on https://github.com/aristath/kirki/pull/2083 and is scheduled for the end of April.

**Comment by sebrosen** [comment]
Great news, thank you
