### ISSUE TITLE
Repeater default row is unusable

### ISSUE THREAD

**Issue by pierreamgabriel** [themeum/kirki#2076]
When we add the repeater control, a default row appears in the Customizer, e.g. "row 1". The problem is this default row simply disappears as soon as we refresh the Customizer.  Also, data entered in the fields inside this row isn't saved in the database.

### Version used:
3.0.35.3

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
please post the code you're using. It seems to be working fine for everyone else and is very usable.

**Comment by pierreamgabriel** [comment]
Sample code from your website. Maybe everyone else don't test their projects hard enough. I don't think I can't trust Kirki for a professional project. It has many bugs. I posted an important one 4 days ago and no feedback from you till now. I was thinking about buying one of your premium controls, but the wisest decision is to drop Kirki completely from my project.

**Comment by sebrosen** [comment]
Based on your previous post from 4 days ago you might want to be careful with throwing around words such as "bugs", "everyone don't test their projects hard enough" and "can't trust Kirki"... just saying.

**Comment by aristath** [comment]
@pierremacedo the code seems to be working fine on my end...
the data is properly saved in the database, the default row is there, perhaps you're not including the defaults in your get_theme_mod call?

**Comment by DannyCooper** [comment]
Closed unless more information can be provided.

**Comment by egemenerd** [comment]
I had a similar issue. It seems like we must define default values for the repeater even if there is no default value.

`Kirki::add_field( 'theme_config_id', [
	'type'        => 'repeater',
	'label'       => esc_html__( 'Repeater Control', 'kirki' ),
	'section'     => 'section_id',
        'default'     => array(),
	...
] );`
