### ISSUE TITLE
[question] Is there any way to extend image manager ?

### ISSUE THREAD

**Issue by danyj** [themeum/kirki#208]
OK , I have several background images sets
http://prntscr.com/6xpxms
that I usually give users to choose from and they consist from about 20 bg images and 50 patterns. Now My background options will be able to set bg on header, footer, sections, you name it . So if I create an option to list those from 

```
theme/images/patterns
theme/images/posters
```

and use the option only 5 times in customizer that is already an overload

Something like this is what I have now
http://prntscr.com/6xpvs1
http://prntscr.com/6xpvvw

but I rather do all that trough wp media manager 

like this
http://prntscr.com/6xpx06

so is there any way that we can extend this and add 2 new tabs to media manager with list of images from theme/images folder?
This does not work for me since it only sets side tab in Add media window  and not in Select Image

```
add_filter( 'media_upload_tabs', 'thz_media_tab' );
function thz_media_tab( $tabs ) {
    $tabs['patterns'] = __( 'Patterns', 'patterns' );
    return $tabs;
}
add_filter('media_upload_default_tab', 'thz_default_tab');
function thz_default_tab($tab)
{
    return 'patterns';
}
```

You solve this and I am buying beers again :)

**Comment by aristath** [comment]
Hey again!

I've been looking into this but I couldn't figure anything out...
Did you have any luck?

**Comment by aristath** [comment]
Closing this one as it's not directly related to the customizer and there has not been any activity in a long time here.

However if you do manage to figure this out I'd be more than happy to implement something relevant in the customizer...
