### ISSUE TITLE
Switch conflict with value_pattern

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#2081]
### Issue description:
Trying to use switch to output css based on if the option is on/off.  Off it would do nothing, if it's on it should output "max-width: 100%;" but instead it's ouputting "max-width: true;"

**Note: This could be user error on my part just not sure if I am missing something.**

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) Yes

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
    Kirki::add_field($opt_name, array(
	'label' => esc_html__('Title bar width 100%', 'textdomain'),
	'section' => 'title_bar_setup_section',
	'settings' => 'title_bar_width_100',
	'type' => 'switch',
	'required' => array(
		array(
			'setting' => 'title_bar_visibility',
			'operator' => '==',
			'value' => true
		),
		array(
			'setting' => 'site_layout', 
			'operator' => '==', 
			'value' => 'wide'
		)
	),
	'default' => false,
	'output' => array(
		array(
			'element' => '#title-bar > .container',
			'property' => 'max-width',
			'value_pattern' => '100%',
			'exclude' => array(false)
		)
	),
	'transport' => 'auto'
));

**Comment by CaptJiggly** [comment]
@aristath I discovered the issue in `postmessage.js` was:

```
			if ( 'string' !== typeof value ) {
				_.each( value, function( subValue, key ) {
					value[ key ] = self.processValue( output, subValue );
				} );
				return value;
			}
```

Instead of:

```
			if ( 'object' === typeof value ) {
				_.each( value, function( subValue, key ) {
					value[ key ] = self.processValue( output, subValue );
				} );
				return value;
			}
```

So the boolean for the switch was being swallowed by ` 'string' !== typeof value` check instead of it checking for an `object` before running through the keys/values.

PHP output seems fine however.

**Comment by aristath** [comment]
@CaptJiggly perfect!!
Thank you for debugging this... these things are easy to miss and sometimes hard to find :+1: 

Pushed a fix
