### ISSUE TITLE
Is it ok to not specify default for styling options?

### ISSUE THREAD

**Issue by DanyDD** [themeum/kirki#2082]
Hi, sorry if this is obvious. 

I have some styling options that I want to use only as an override for the original color specified in the main CSS. When I am using defaults (which is the same one as the main CSS) I have to use this so that it doesn't output the CSS : 'exclude'  => [ '#000000' ] 

Then, when I'm using the same code for another site, if the color change in the main CSS I have to also go and change all my defaults to fit. 

I tried removing the default option from the color option and it seems to work fine for this since it only output if something is specified and it override the original styling.

Is it ok to do it? I just want to be sure because in the documentation it says we should always have some defaults but I wasn't sure if it is for every options or just options that would be use in the templates. 

Thanks!

**Comment by aristath** [comment]
instead of omitting the `default` argument, use `'default' => ''`
Empty arguments don't get a CSS output :wink:
