### ISSUE TITLE
Different CSS for each choices?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2085]
Hi!

First of all I want to say that you did amazing job with Kirki. Bravo!

I want ask about _radio-buttonset_ . In my case below I have buttonset with two choices. Is there any way do add different CSS values for each choice, but not for thoses selectors in output array? For example, I add "row-reverse" for "div.l-article-page" and then other CSS is applied to container or other selector.

```
Kirki::add_field( 'universal', [
	'type'        => 'radio-buttonset',
	'settings'    => 'single_pages_posts_sidebar_align',
	'label'       => esc_html__( 'Pokazuj pasek boczny po stronie', 'kirki' ),
	'section'     => 'single_pages_posts',
	'default'     => 'row',
	'priority'    => 10,
	'choices'     => [
		'row-reverse'   => esc_html__( 'lewej', 'kirki' ),
		'row' => esc_html__( 'prawej', 'kirki' ),
	],
    'transport'   => 'auto',
    'output'    => array(
		array(
			'element'         => 'div.l-article-page',
			'property'        => 'flex-direction',
			'media_query'     => '@media (min-width: 1024px)',
			),
		),
] );
```

Thanks!

**Comment by aristath** [comment]
You can add multiple output items and then use the [`exclude`](https://aristath.github.io/kirki/docs/modules/css.html#exclude) argument on each of them.
Example:
```php
'output' => [
	[
		...
		'exclude' => [ 'row' ], // Makes the css apply ONLY if value is NOT "row".
	],
	[
		...
		'exclude' => [ 'row-reverse' ], // Makes the css apply ONLY if value is NOT "row-reverse".
	],
]
```

**Comment by BeholdPL** [comment]
I see, but I think this is not what I'm looking for. For example, if I choose '_row-reverse_' option, then for example I want add _background-color: red_ for _body_.

**Comment by aristath** [comment]
Then you can also add the `value_pattern` argument :smile: 

```php
'output' => [
	[
		'element'       => '.something',
		'property'      => 'background-color',
		'exclude'       => [ 'row' ], // Makes the css apply ONLY if value is NOT "row".
		'value_pattern' => 'red',
	],
	[
		...
		'exclude' => [ 'row-reverse' ], // Makes the css apply ONLY if value is NOT "row-reverse".
	],
]
```

**Comment by aristath** [comment]
`value_pattern` allows you to define a custom value, and you can use the dollar (`$`) character as a placeholder. It's on https://aristath.github.io/kirki/docs/modules/css.html#value_pattern right below the `exclude` argument

**Comment by BeholdPL** [comment]
Great! I did what I need, thanks!
