### ISSUE TITLE
Kirki 3.0.36 breaks Font Awesome icons

### ISSUE THREAD

**Issue by pierreamgabriel** [themeum/kirki#2088]
I had already finished my theme but I saw a new version was available so I decided to test it. And the result was it breaks font awesome icons. I'm using FA Shims in order to make FA V5 to work with the "fa" prefix and it's working 100% with Kirki 3.0.35.3. But I also tested it with FA v4.7.0 and the result was the same, broken icons. 

I'm just reporting the issue. I wont' be able to test anything because I decided to stick to Kirki 3.0.53.

**Comment by aristath** [comment]
> I wont' be able to test anything because I decided to stick to Kirki 3.0.53.

Could you please send me a copy of your theme so that **I** may test it?

**Comment by DannyCooper** [comment]
Closing as no further information has been provided and also https://github.com/aristath/kirki/commit/0bc7f4b93af85e949fe12f9d0c522473ca27a286
