### ISSUE TITLE
Not able to add clientside components in a site page using @pnp/sp

### ISSUE THREAD

**Issue by UdayaMS** [themeum/kirki#2090]
### Issue description:

I am not able to add spfx webpart programatically to a site page using @pnp/sp library, it was working before, now the same code is not working.

### Version used:
1.2.9

I am not getting any error, the program executing fine but when i open the page it is not displaying anything.

**Comment by aristath** [comment]
@UdayaMS are you sure you opened this ticket on the right repository? I don't understand what the Kirki WordPress plugin has to do with pnp/sp, and we never had a version 1.2.9

**Comment by UdayaMS** [comment]
Sorry for that, i can close this ticket.
