### ISSUE TITLE
Minor spacing issue for link type button position

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#2097]
### Issue description:
There is a small difference between the buttons position depending on if it's inside of a panel or on the main page. Ideally both should look like the first example (customizer main page).

Example: https://i.imgur.com/YywsdCc.png - see the red line

Tiny thing I know, just thought I'd report it anyway :-)

**Comment by DannyCooper** [comment]
Fixed upstream - https://github.com/kirki-framework/module-custom-sections/commit/e571684b9290895a60cb343990519db2b52691de
