### ISSUE TITLE
Error when modifying choses for the sortable field

### ISSUE THREAD

**Issue by ahorndesign** [themeum/kirki#210]
We have the following situation. We are using a sortable field to allow users to activate and rearange term-based filters for the frontend. 

The problem is that if the user removes a term which had a non-default value, a placeholder is displayed for it in the sortable field even though the choice is not available any longer. The placeholder remains even when the options are saved, meaning the output is not being sanitised in order to remove non-existing options.

The way this should work is to only display an option if it is being defined in the "choises" array. If it does not exist, the order index of all items following this one should shift accordingly.

**Comment by aristath** [comment]
Hey there!

I'm sorry for the delay here, I missed this issue.
Do you still require assistance on this one?
