### ISSUE TITLE
Problem using "kirki-helpers"

### ISSUE THREAD

**Issue by DanyDD** [themeum/kirki#2100]
Hi,

I really don't understand why the CSS isn't only outputted when the user actually makes a change in the options since the style is already specified in my style.css for my theme so like you suggested I only use empty defaults like this : 'default'     => '' so that the only CSS that the plugin output is if the user decides to override my initial styling.

Now I want those changes to remain even if the plugin is disabled so I added the helpers but now it renders ALL the defaults options (even the empty one) when the plugin is disabled and adds huge chunks of CSS that take a long time to load. Why isn't it only saving the option that the user changed? Am I missing something here?

Thanks!

**Comment by aristath** [comment]
Which helpers are you referring to? If you're referring to this one: https://github.com/aristath/kirki/blob/ff0f7256749a1b9e509da7719d5cda60f2798dca/docs/files/class-my-theme-kirki.php then that file is an example of how you can do it. It is not meant to be used as-is, most times themes need to tweak it for their own use-case.
If I understand correctly what you want to do, then you can replace this line: https://github.com/aristath/kirki/blob/ff0f7256749a1b9e509da7719d5cda60f2798dca/docs/files/class-my-theme-kirki.php#L349
with this:
```php
$final_css .= ( '' !== $value ) ? $property . ':' . $value . ';' : '';
```
ideally though you'd use that file as an example, get rid of all the parts that don't make sense for your theme, add ones that you want. For example if you're using theme_mods and not options there's a lot of code you can just trash.

**Comment by DanyDD** [comment]
Ok I will try removing everything I don't need. 

Ideally I just want Kirki to only output CSS for styling options that is different from the main styling, isn't it how it is supposed to be? I've seen a lot of themes with huge inline CSS for no reason since the CSS is already specified in style.css.

Do people use Kirki to output all their styling?

**Comment by aristath** [comment]
>  isn't it how it is supposed to be?

Not always.

> Do people use Kirki to output all their styling?

Some themes do, yes. Other themes use the `exclude` argument in their fields to skip defaults. Other themes use the `kirki_styles_array` filter to tweak whatever they want. Other themes do their own custom thing.

**Comment by DanyDD** [comment]
I understand. I am using the exclude but when I use the wrapper class, it doesn't mind and just output everything. What would I need in that wrapper to only store and output the options like it does when I have the plugin activated?

**Comment by DanyDD** [comment]
I just tried adding the wrapper class and same thing happens even with the changes you suggest.

Basically, when the plugin is deactivated, the pages loads for 5-6s each .. it load instantly if I remove this : 

		// Add google fonts.
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_fonts' ) );

But then the fonts change doesn't remain there. Also, all options which I use "exclude" are now showing up and is messing the whole site.

I really love the plugin and I would really like my user to be able to keep their changes if they turn off the plugin but I can't have it as it is. 

Any suggestions?

I totally understand if you can't help me.

**Comment by aristath** [comment]
Have you considered embedding the plugin in your theme instead of recommending it as a plugin?
There are many themes that do that. both on wordpress.org and on Envato/ThemeForest.

**Comment by DanyDD** [comment]
I think it's not allowed to have any plugin embedded with themes at Themeforest anymore but I can try.

Does everybody experience a performance issue with the wrapper class and google fonts?
