### ISSUE TITLE
Frontend Performance.

### ISSUE THREAD

**Issue by steve231293** [themeum/kirki#2101]
### Issue description:
Hi aristath,
I have a problem with performance in Front-end. I think many people faced with this problem, too.

Could you tell me properly hook to register Kirki fields?

If i use hook "init" to register fields, then front-end is very slow when you have many fields that used query from database.
For eg:
`add_action( 'init', 'load_customizer_fields' );`

Then i have some select fields with categories (post or anything query from database):

`$categories_list   = get_terms( array( 'taxonomy'   => 'category', ) );`

```
Kirki::add_field( 'theme', array(
    'type'        => 'select',
    'settings'    => 'post_categories',
    'label'       => esc_html__( 'Filter By Cats', 'text-domain' ),
    'section'     => 'blog_settings',
    'priority'    => 1,
    'multiple'    => 1000,
    'choices'     => $categories_list,
) );
```

This is okay in Customize preview but it will run these queries in all front-end pages & admin pages, too.

If i use hook 'customize_register'. Then all fields with 'output' is not working.
For eg:

`add_action( 'customize_register', 'load_customizer_fields' );`

...

```
Kirki::add_field( 'theme', array(
	'type'        => 'color',
	'settings'    => 'body_color',
	'label'       => esc_html__( 'Body Color', 'text-domain' ),
	'section'     => 'color_settings',
	'priority'    => 2,
	'transport'   => 'auto',
	'default'     => '#ff0000',
	'output'      => array(
		array(
			'element'  => 'body',
			'property' => 'color',
		),
	)
) );
```

Is there any way to make Field Output working properly with 'customize_register' hook

### Using theme_mods or options?
theme_mod

**Comment by aristath** [comment]
Hmmmm if you have some heavy queries then you should be able to do something like this:

```php
global $wp_customize;
Kirki::add_field( 'theme', array(
    'type'        => 'select',
    'settings'    => 'post_categories',
    'label'       => esc_html__( 'Filter By Cats', 'text-domain' ),
    'section'     => 'blog_settings',
    'priority'    => 1,
    'multiple'    => 1000,
    'choices'     => $wp_customize ? $categories_list : array()
) );
```
That way if you're on the customizer the queries run, and in the frontend they don't.
