### ISSUE TITLE
Typography Control: Text font size flicker when changing color

### ISSUE THREAD

**Issue by sebrosen** [themeum/kirki#2104]
I'm using the typography control and I have found that if you change the font size and then change the color, the text size will flicker going from big to small.

This doesn't happen if you don't change the font size first.

Here's a gif of the issue in action:

![fvigbfytel](https://user-images.githubusercontent.com/2302270/53566934-89de2d00-3b12-11e9-837b-248eeb7ba841.gif)

**Comment by sebrosen** [comment]
I realized it's pretty hard to see the issue on that GIF, so I did a screen recording with a better example: https://cl.ly/b0974f890aa5

**Comment by sebrosen** [comment]
Am I the only one with this issue? Maybe something is wrong on my end

**Comment by aristath** [comment]
@sebrosen I can see the issue on your gif but could never replicate it...

**Comment by sebrosen** [comment]
I tested it on a fresh install of TwentyNineteen and the same thing happens. It only flickers when you drag your mouse around the color box

**Comment by aristath** [comment]
Can you please post your code here so that I may investigate later today when I have some free time?

**Comment by sebrosen** [comment]
In TwentyNineteen I have the following test code:

```
Kirki::add_field( 'theme_config_id', [
	'type'        => 'typography',
	'settings'    => 'my_setting',
	'label'       => esc_html__( 'Control Label', 'kirki' ),
	'section'     => 'section_id',
	'default'     => [
		'font-family'    => 'Roboto',
		'variant'        => '700',
		'font-size'      => '2.25em',
		'line-height'    => '1.2',
		'letter-spacing' => '0',
		'color'          => '#1e73be',
		'text-transform' => 'none',
	],
	'priority'    => 10,
	'transport'   => 'auto',
	'output'      => [
		[
			'element' => '.entry-title',
		],
	],
] );
```
In order to see the flicker, I first have to change font size or letter-spacing, after that I click and hold the mouse button down while I drag around the color box. Sometimes it can take a few seconds to start flickering and other times it happens immediately.

Here's a gif of it happening in TwentyNineteen:

![Image of flicker](https://thumbs.gfycat.com/NeglectedDimwittedHoiho-size_restricted.gif)

**Comment by DannyCooper** [comment]
I'm also seeing this, it's as if the entire auto-generated CSS is being removed and recreated each time the colorpicker value changes.

It's even easier to visualize if you make a considerable change. For example changing the alignment of titles.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
