### ISSUE TITLE
Option value as media query

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2109]
I would like to know if it is possible to implement the next feature

i would like to use the value of one option inside other as media_query

Example:

`Kirki::add_field( 'config_cc', array(
	'type'        => 'slider',
	'settings'    => 'main_value',
	'label'       => esc_html__( 'Custom value', 'textdomain' ),
	'section'     => 'my_section',
	'default'     => 992,
	'choices'     => array(
		'min'  => '0',
		'max'  => '1000',
		'step' => '1',
	),
) );

Kirki::add_field( 'config_cc', array(
	'type'        => 'slider',
	'settings'    => 'font_size',
	'label'       => esc_html__( 'Font size', 'textdomain' ),
	'section'     => 'my_section',
	'default'     => 100,
	'choices'     => array(
		'min'  => '0',
		'max'  => '300',
		'step' => '1',
	),
	'output' => array(
		array(
			'element' => 'h2',
			'property' => 'font-size',
			'units' => '%',
			'media_query' => '@media (min-width:'.Kirki::get_option( 'main_value' ).'px)'
		),
	),
) );`

**Comment by DannyCooper** [comment]
What is the use-case for this? Wouldn't it be easier to output the media query on the first control?

**Comment by Stas0238** [comment]
@DannyCooper I would like to minimize code. Thats why i am interested in this feauture. Could it be implemented in any of updates ?

**Comment by DannyCooper** [comment]
In your example you haven’t minimized your code, you’ve just moved it from one control to another..

**Comment by Stas0238** [comment]
@DannyCooper Yeah, really but if i could use your Kirki 'side' of output i would not write my own php code to show the output including this media query. And also it won't be on live ( i mean the window will be refreshing on preview :( )
In simple words if i could use this feature then all my css from output and this one will be in one place shown step by step in Kirki output style tag. But when there is no such option yet then i can do next steps:
1) get the media option (for example 992px)
2) get the value of option for this media (font_size = 20)
3) add new style tag with text ( @media (min-width: $my_media ) {
h2 {
font-size: $font_size;
}
} );
The second way as you can see has more actions to check, load and write in. It is normal if you refuse me to add this option but this is such a good way to use value of one option inside another on live view ! which is looks amazing 👍. And neither Redux nor others plugins have this feature. So i would like to see it in your plugin which i really like to use for months :) 
Thanks for your best support :)

**Comment by DannyCooper** [comment]
‘pattern_replace’ can be used to pull in other setting values - https://github.com/aristath/kirki/issues/1978#issuecomment-506011450

**Comment by kodeoagency** [comment]
Hello @DannyCooper 
I have the same requirement as Stas0238.
I noticed you closed the ticket as resolved by using pattern_replace method
I check the method but it's not clear to me how to use it for media query.
Could you please give me a hint.
Thank you very much!

**Comment by aristath** [comment]
@kodeoagency you can't use a value directly in a media query, you'll need to write that with some custom PHP and use `'transport' => 'refresh'` instead of `postMessage`.

**Comment by kodeoagency** [comment]
Thank you for the hint. Will see if we can manage this.
