### ISSUE TITLE
Google Fonts with different subsets loaded incorrectly

### ISSUE THREAD

**Issue by dedalx** [themeum/kirki#2110]
### Issue description:
I found and fixed issue with function that check different subsets (if enabled to load ALL subsets in Kirki config). This is important issue and it's remove some fonts subsets from loading. I made a pull request with fix, but it's was rejected by auto checker because (as I understand) code changes % is not so big as allowed by auto checker. Please check my pull request and help to approve it and add to next Kirki update, it's important:
https://github.com/aristath/kirki/pull/2106 

### Version used:
Latest

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Enable loading all subsets for Google fonts. Not all subsets will be loaded.

**Comment by aristath** [comment]
merged
