### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Kirki_Fonts_Google' not found when using Kirki as plugin (works fine when embedded in theme)

### ISSUE THREAD

**Issue by dedalx** [themeum/kirki#2111]
### Issue description:
**Fatal error: Uncaught Error: Class 'Kirki_Fonts_Google' not found** - error displayed when using Kirki as plugin (works fine when embedded in theme).

Error displayed because of this theme code (code located in file with Kirki theme options configuration):
**Kirki_Fonts_Google::$force_load_all_variants = true;**

This code works fine if I embed Kirki in theme, and give error only when I load Kirki as plugin. As I understand Google Fonts classes loaded in another order when I use Kirki as plugin, and not available at the moment of my call. I tried to use my code in some hooks (init, after_theme_setup, etc) but this does not help - I can't access Kirki_Fonts_Google from anywhere.

Please help me what I am doing wrong and how to use my code with Kirki plugin?

### Version used:
Latest

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
**Kirki_Fonts_Google::$force_load_all_variants = true;** with Kirki added as plugin.

**Comment by aristath** [comment]
Could you please send me a copy of your theme so that I may test this?
I can't replicate using other themes

**Comment by dedalx** [comment]
> Could you please send me a copy of your theme so that I may test this?
> I can't replicate using other themes

It's easy to check - install any theme (for ex. WordPress default one), install Kirki plugin. Add this line to the end of functions.php in WordPress theme:

**Kirki_Fonts_Google::$force_load_all_variants = true;**

This will give error as described.

I understand that I need to use "if class_exist()" in code, but I should not get error in any case, since Kirki plugin activated and this class should be available for use in theme functions file. So even if I will add if class exist of course I will get rid of error, but this code will never executed and I will not able to load all fonts variants.

**Comment by dedalx** [comment]
This is default WP theme with this code added to functions.php for test, activate Kirki plugin and then activate this theme to see error:
https://take.ms/QyVfR (download link).

**Comment by dedalx** [comment]
Looks like I found solution. Only this code works fine, with **init** hook (other hooks don't):

```
function theme_font_add_all_variants() {
    if (class_exists('Kirki_Fonts_Google')) {
        Kirki_Fonts_Google::$force_load_all_variants = true;
        Kirki_Fonts_Google::$force_load_all_subsets = true;
    }
}

add_action('init', 'theme_font_add_all_variants');
```
