### ISSUE TITLE
Gutenberg Styling

### ISSUE THREAD

**Issue by DanyDD** [themeum/kirki#2113]
Thanks for the Gutenberg update, works a lot better now.

Some properties need to be a bit more specific for them to work so I'm trying this but it doesn't work. For example it still apply 'font-size' to '.edit-post-visual-editor.editor-styles-wrapper .editor-post-title__input', am I doing something wrong?
```
'output'      => [
		[
			'element' 	=> 'body',
		],
		[
			'element' 	=> '.edit-post-visual-editor.editor-styles-wrapper',
			'context'  => array( 'editor' ),
		],
		[
			'element' 	=> '.edit-post-visual-editor.editor-styles-wrapper .editor-post-title__input',
			'context'  => array( 'editor' ),
			'property' => 'font-family',
		],
				[
			'element' 	=> '.edit-post-visual-editor.editor-styles-wrapper p',
			'context'  => array( 'editor' ),
			'property' => 'font-size',
		],
	],
```
Thanks a lot!

**Comment by DanyDD** [comment]
Hey, if you can just say if it's doable or not it would be really appreciated.

**Comment by DanyDD** [comment]
Answered via email. Closing this.

**Comment by aristath** [comment]
Closing this one, we already resolved it via another channel.
