### ISSUE TITLE
How to add CSS with transport 'auto' when toggle field is 1

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2115]
Hi :)
I want to use toggle field for applying CSS:

```
Kirki::add_field('behold-universal-one', [
    'type' => 'toggle',
    'settings' => 'header_social_media_egual_space',
    'label' => esc_html__('Wyrównaj odległość pomiędzy ikonami ', 'behold-universal-one'),
    'description' => esc_html__('Zaznacz, jeżeli ikony nie będą mieć żadnego obramowania.', 'behold-universal-one'),
    'section' => 'header_social_media_all',
    'default' => '1',
    'priority' => 10,
    'transport' => 'auto',
    'output' => [
        'element'  => '.e-social-media',
        'property' => 'width',
        'value_pattern' => 'unset',
        'suffix'   => 'px !important',
    ]
]);
```

but I do not know how to apply those values from output only when toggle in "1". In other words, when toggle is "1" I want those values works.

Thanks!

**Comment by aristath** [comment]
it should work if you add `'exclude' => [ false, 0, '0', 'false' ]` in the `output`.
And output should be an array of arrays, so instead of `[ args ]` it should be `[ [ args ] ]` so you can use multiple outputs.

**Comment by BeholdPL** [comment]
I see. Great :)

btw: how can I add CSS only when value of slider is for eg. '0'?

**Comment by aristath** [comment]
Again using the `exclude` argument. But this time you'd have to do something like this: `'exclude' => range( 1, 100 ),` (see docs for the PHP `range` function here: https://secure.php.net/manual/en/function.range.php - it allows min, max, step params).

**Comment by BeholdPL** [comment]
Hi

I'm trying to add CSS in toogle field with 'transport' = > 'auto' when it's set to true, but this code doesn't work:

```
Kirki::add_field('behold-universal-one', [
    'type' => 'toggle',
    'settings' => 'hero_full_height',
    'label' => esc_html__('Pokaż HERO na całą wysokość okna', 'behold-universal-one') ,
    'section' => 'block_hero',
    'default' => '1',
    'priority' => 10,
    'transport' => 'auto',
    'output' => array(
        array(
            'element'       => '.l-header-image',
            'property'      => 'min-height',
            'value_pattern' => '100vh',
            'media_query' => '@media all and (min-width: 768px)',
            'exclude' => [ false, 0, '0', 'false' ]
        ),
    ),
]);
```

where is my mistake?

**Comment by aristath** [comment]
@BeholdPL are you using the stable version from wordpress.org, or the develop version from this repository?
Are you using options or theme-mods?
Would it not be simpler to toggle a glass in the element instead?

**Comment by BeholdPL** [comment]
It's stable version form WP repository, I'm uisng theme-mods. Problem is when I toggle switch off this field, then '.l-header-image' still have thoses styles from array.

> Would it not be simpler to toggle a glass in the element instead?

I'm not sure what you mean ;)

**Comment by aristath** [comment]
You can try something like this:

```php
'output' => [
	[
		'element'       => '.l-header-image',
		'property'      => 'min-height',
		'value_pattern' => '100vh',
		'media_query'   => '@media all and (min-width: 768px)',
		'exclude'       => [ false, 0, '0', 'false' ]
	],
	[
		'element'       => '.l-header-image',
		'property'      => 'min-height',
		'value_pattern' => 'auto',
		'media_query'   => '@media all and (min-width: 768px)',
		'exclude'       => [ true, 1, '1', 'true' ]
	],
],
```

**Comment by BeholdPL** [comment]
Ok, that's works :) I don't think about set the styles if toggle value is 0. This is so simple :D Thanks :)
