### ISSUE TITLE
Custom control with multiple text fields

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#2119]
In my theme, I want to add a custom control with three kirki text fields - something similar to typography control.

I went through Kirki's code and documentation (http://aristath.github.io/kirki/docs/advanced/register-control-types.html). I couldn't figure out how can it be done without modifying Kirki itself. Could you point me in the right direction.

**Comment by aristath** [comment]
At the moment this is not possible in Kirki, you'd have to write your own custom control.

**Comment by rahulv3a** [comment]
I want to utilize `transport`, `output`, and `active_callback` from Kirki in my custom control. Is it possible?

**Comment by DannyCooper** [comment]
@aristath Do custom controls have access to all the `arguments` that the core Kirki controls have?

**Comment by aristath** [comment]
It depends on the control's implementation.
If the control extends `Kirki_Control_Base` instead of `WP_Customize_Control` then yes

**Comment by DannyCooper** [comment]
The example in the docs that @rahulvermadev linked to does. That’s useful to know, I will add it to the docs.
