### ISSUE TITLE
Kirki_Helper::get_posts doesn't respect orderby

### ISSUE THREAD

**Issue by blogjunkie** [themeum/kirki#2121]
### Issue description:
In the following code I expect that I will get the 20 most recent posts. Instead I get the 20 oldest posts.

```
Kirki_Helper::get_posts( array(
	'posts_per_page' => 20,
	'post_type'      => 'post',
	'orderby'		 => 'date',
	'order'			 => 'DESC',
) )
```

To achieve what I wanted, I needed to do this instead:

```
// Get the posts.
$args = array(
	'posts_per_page' => 20,
	'orderby'		 => 'date',
	'order'			 => 'DESC',
);
$posts_from_args = get_posts( $args );

// Format the posts array like ( post_id => post_title ).
$get_posts = array();
foreach( $posts_from_args as $post ) {
	$get_posts[ $post->ID ] = $post->post_title;
}
```

### Version used:
v3.0.38 from plugin repo and today's development branch from Github 

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_config( 'sc_kirki', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );

Kirki::add_section( 'soyacincau_featured', array(
    'title'          => esc_html__( 'Featured Content', 'soyacincau' ),
    'description'    => esc_html__( 'Select hero posts to be displayed on the homepage.', 'soyacincau' ),
    'panel'          => 'soyacincau',
    'priority'       => 160,
) );

Kirki::add_field( 'sc_kirki', [
	'type'        => 'repeater',
	'label'       => esc_html__( 'Repeater Control', 'soyacincau' ),
	'section'     => 'soyacincau_featured',
	'priority'    => 10,
	'row_label' => [
		'type'  => 'field',
		'value' => esc_html__('Featured Post', 'soyacincau' ),
		'field' => 'post',
	],
	'button_label' => esc_html__('Add Featured Post', 'soyacincau' ),
	'settings'     => 'sc_hero_posts',
//	'default'      => [
//		[
//			'post'		=> '',
//			'title_override' => esc_html__( 'Kirki Site', 'soyacincau' ),
//			'link_url'  => 'https://aristath.github.io/kirki/',
//		],
//	],
	'fields' => [
		'post' => [
			'type'        => 'select',
			'label'       => esc_html__( 'Post', 'soyacincau' ),
			'description' => esc_html__( 'Select featured post', 'soyacincau' ),
			'default'     => '',
//			'choices'	  => $get_posts,
			'choices'  	  => Kirki_Helper::get_posts( array(
					'posts_per_page' => 20,
					'post_status' 	 => array( 'publish', 'future' ),
					'orderby'		 => 'date',
					'order'			 => 'DESC',
				) ),
		],
		'title_override' => [
			'type'        => 'text',
			'label'       => esc_html__( 'Title override', 'soyacincau' ),
			'description' => esc_html__( 'Optional: override the title of the post', 'soyacincau' ),
			'default'     => '',
		],
	]
] );
```

**Comment by aristath** [comment]
`Kirki_Helper::get_posts()` is just a proxy for the WordPress `get_posts()` function and all it does is what you did in your custom code, it formats the post-array like `[ $id => $name ]`:
https://github.com/aristath/kirki/blob/ec63944decfbf128ead44e7f8653779bbfcbf718/core/class-kirki-helper.php#L192-L215
The only difference I can see is that `Kirki_Helpers::get_posts()` in addition to what you did also adds `suppress_filters` to the query and sets it to true. But that should have any effect in your query... 
Do you see something wrong in the method that I'm missing?

**Comment by blogjunkie** [comment]
I really can't tell if there's something wrong in your method – you're probably much better at this than me Ari. I should test this on a clean install to see if the problem persists. I'll get back to you then :)

**Comment by DannyCooper** [comment]
I've tested this and it works as expected, which it should as Ari explained the `Kirki_Helper::get_posts();` helper is just a wrapper around the core WordPress function.
