### ISSUE TITLE
toggle button refresh customizer

### ISSUE THREAD

**Issue by webhostingsrbijaRS** [themeum/kirki#2123]
### Issue description:
i have toggle button, so when is on i want to user can upload image and option show bellow, but when is off option for upload image should not be visible

> Kirki::add_field( 'theme', [
                    'type'        => 'toggle',
                    'settings'    => 'featired_image_post',
                    'label'       => esc_html__( 'upload image or not', 'theme' ),
                    'section'     => 'general_post',
                    'default'     => '1',
                    'priority'    => 13,
            ] );
         if(Kirki::get_option('featired_image_post')==0):
             Kirki::add_field( 'theme', [
                    'type'        => 'image',
                    'settings'    => 'slika_clanak',
                    'label'       => esc_html__( 'upload featured', 'theme' ),
                    'section'     => 'general_post',
                    'default'     => 'bg-default.jpg',
                    'priority'    => 14,
            ] );
         endif;

is this possible?

**Comment by aristath** [comment]
https://aristath.github.io/kirki/docs/arguments/active_callback.html
