### ISSUE TITLE
Version 3.0.39 color control's default/reset button

### ISSUE THREAD

**Issue by reefki** [themeum/kirki#2130]
### Issue description:
I just upgraded to the latest version (3.0.39) and I found that the color control's default/reset button isn't working properly. Using the config provided below once I changed the color for example from `#ffffff` to `#212121` and reload the page. When I clicked the default/reset button it does revert back to `#ffffff` in the control but in the preview frame, my site's background color is still black `#212121`.

Without refreshing the page, I changed it to another color `#dd3333`, it works both in control and preview the color changed to red `#dd3333` but when I tried again to reset the color I got the same behavior, color in the control is `#ffffff` but in the preview is back to the last color saved `#212121`.

### Version used:
3.0.39

### Using theme_mods or options?
`theme_mods`

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field('my_config', array(
    'type' => 'color',
    'settings' => 'background_color',
    'label' => esc_html__('Background', 'textdomain'),
    'section' => 'colors',
    'transport' => 'auto',
    'default' => '#ffffff',
	'output' => 
        array(
            'element' => array(
                'body',
            ),
            'property' => 'background-color',
        ),
    ),
));
```

**Comment by DannyCooper** [comment]
I've tested this in `master` and `develop` and can't replicate it.

Could you test the latest versions and let me know if it's still an issue please?

**Comment by JiveDig** [comment]
Is this the same or a similar issue to https://github.com/aristath/kirki/issues/1869?

**Comment by aristath** [comment]
> Is this the same or a similar issue to #1869?

Yes, appears to be the same. Closing as duplicate :+1:
