### ISSUE TITLE
Preset & Active Callback

### ISSUE THREAD

**Issue by reefki** [themeum/kirki#2133]
### Issue description:
Let say we have two color mode for the footer light and dark. In the CSS file we defined the background color of light mode `#ffffff` and `#000000` for dark mode.

Using the config below, if you switch footer mode from light to dark while leaving `footer_customize_colors` unchecked, instead of changing background color to `#000000` as defined in the CSS file, the color is changed to the one that defined in preset `#ff0000`. That shouldn't be happen because `footer_background_color` field should be applied only when `footer_customize_colors` is checked.

### Version used:
3.0.39

### Using theme_mods or options?
`theme_mods`

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field('my_config', array(
    'type' => 'radio-buttonset',
    'settings' => 'footer_color_mode',
    'label' => esc_html__('Footer Color Mode', 'textdomain'),
    'section' => 'colors',
    'transport' => 'postMessage',
    'choices' => array(
        'light' => esc_html__('Light', 'textdomain'),
        'dark' => esc_html__('Dark', 'textdomain'),
    ),
    'preset' => array(
        'light' => array(
            'settings' => array(
                'footer_background_color' => '#ffcc00'
        ),
        'dark' => array(
            'settings' => array(
                'footer_background_color' => '#ff0000'
            )
        ),
    ),
));

Kirki::add_field('my_config', array(
    'type' => 'checkbox',
    'settings' => 'footer_customize_colors',
    'label' => esc_html__('Customize colors?', 'textdomain'),
    'section' => 'colors_footer',
    'transport' => 'postMessage',
));

Kirki::add_field('my_config', array(
    'type' => 'color',
    'settings' => 'footer_background_color',
    'label' => esc_html__('Background', 'textdomain'),
    'section' => 'colors_footer',
    'transport' => 'auto',
    'default' => '#ffffff',
	'output' => array(
        array(
            'element' => array(
                '#footer',
            ),
            'property' => 'background-color',
        ),
    ),
    'active_callback' => array(
        array(
            'setting' => 'footer_customize_colors',
            'operator' => '==',
            'value' => true,
        ),
    ),
));
```

**Comment by ghost** [comment]
I'm having the same problem.

**Comment by aristath** [comment]
I didn't have time to test that code yet, but I do notice that it's incomplete, the checkbox control is missing its default parameter.
Did you try adding that?

**Comment by reefki** [comment]
@aristath Added default parameter but unfortunately, that doesn't help.

**Comment by ghost** [comment]
@aristath value.bind of Kirki Preset maybe not working. Please help me check it again.
Thank you so much.

**Comment by reefki** [comment]
This issue might be related to #2130, it seems that both issues are JS related since the problem only occurs on the live preview frame.

**Comment by aristath** [comment]
in v4.0 I completely refactored the colorpickers (still a WIP) so if the problem is with the color controls it will be fixed.
Is the issue only with color controls? Or does it happen regardless of the control-type?

**Comment by reefki** [comment]
So far I found that the issue is only with color controls.

**Comment by mapsteps** [comment]
The colorpicker was again completely refactored.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
