### ISSUE TITLE
Local google fonts loading in http not https

### ISSUE THREAD

**Issue by Shadowsong87** [themeum/kirki#2134]
Hey,

I'm using the Kirki plugin as part of the NK Godlike theme. Using the customizer i've added a couple font's however they try to load over http instead of https for some reason. The font is available via the same path over https. (They load locally)

I've got a URL rewrite in ISS for http to https and the same on cloudflare, but no matter what i do i cannot get them to load over https. My site does not load insecure content which results in no font showing up.

Version: 3.0.39
Site: https://astral-imperium.com

To see the issue, you can load the website and see the mixed content messages in the google chrome console. 

Is this a bug or potential config issue because i'm using local font's? From what i can see if they loaded from google then it would use https no problem, but i'd like to keep them local if possible.

**Comment by aristath** [comment]
@Shadowsong87 I think there may be something improperly set-up on your site...
Kirki uses native WordPress functionality to store the Google Fonts (see [this line](https://github.com/aristath/kirki/blob/v3.0.39/modules/webfonts/class-kirki-fonts-helper.php#L127))
We just use [`wp_handle_sideload`](https://developer.wordpress.org/reference/functions/wp_handle_sideload/). That function in its turn calls [_wp_handle_upload`](https://developer.wordpress.org/reference/functions/_wp_handle_upload/) if you checks its source. That calls [wp_upload_dir](https://developer.wordpress.org/reference/functions/wp_upload_dir/) to get the URL of your uploads folder.
I can think of 3 things that may have caused this:
1. wrong `WP_CONTENT_URL` defined in your `wp-config.php`
2. Wrong URLs set-up in Dashboard > Settings > General
3. perhaps multisite with a domain-mapping plugin which has the wrong domain protocol set-up for that site?

**Comment by Shadowsong87** [comment]
Thanks for the reply, we had recently moved over to multisite which is when we noticed the issue. However for some unknown reason the issue now appears to have gone and no more errors. Wondering if it was cache related or something strange that needed time to update. 

Either way all working so this one can be closed off!

**Comment by pasqualevitiello** [comment]
@aristath Same issue has above. The funny thing is that Lato loads over http and Simonetta over https.  
<img width="1491" alt="Screenshot 2019-05-03 at 19 13 55 PM" src="https://user-images.githubusercontent.com/2683512/57153941-d9bdc680-6dd7-11e9-9fa1-eb7e1f2e00ff.png">

**Comment by vlthemes** [comment]
I have this errors too. I never use http but:

Mixed Content: The page at 'https://wp.vlthemes.com/arquito/wp-admin/post.php?post=75&action=edit' was loaded over HTTPS, but requested an insecure stylesheet 'http://wp.vlthemes.com/arquito/?action=kirki-styles&editor=1&ver=3.0.39'. This request has been blocked; the content must be served over HTTPS.

**Comment by pasqualevitiello** [comment]
Any news on this?

**Comment by DannyCooper** [comment]
The latest update fixed this https://wordpress.org/plugins/kirki/#developers
