### ISSUE TITLE
Toggle set default to false

### ISSUE THREAD

**Issue by webhostingsrbijaRS** [themeum/kirki#2136]
### Issue description:
Hello i can't set toggle to default off. O tried "off", "0", false,"false" but nothing help is it possible to set on default to off?

### Version used:
3.0.38

```

> Kirki::add_field( 'wbtheme', [
>                      'type'     => 'toggle',
>                     'settings' => 'fixed_navbar',
>                     'label'    => esc_html__( 'Fiksiran navbar', 'wbtheme' ),
>                     'section'  => 'general_navbar',
>                     'default'  => '0',
>                     'priority' => 8,
>                     'transport' => 'postMessage',
>                     'js_vars'     => array(
>                             array(
>                                     'element'  => '.header-blue',
>                                     'function' => 'toggleClass',
>                                     'class'    => 'sticky-top',
>                                     'value'    => true,
>                             ),
>                             array(
>                                     'element'  => '.header-blue',
>                                     'function' => 'toggleClass',
>                                     'class'    => 'boxshadowsidebar',
>                                     'value'    => true,
>                             ),
>                     ),
>             ] );

```

**Comment by aristath** [comment]
What doesn't work? Can you please be a little more specific? Does it have the wrong value when you open the customizer? Does it save the changes? Or is the issue related to the `js_vars` argument in your code?

**Comment by webhostingsrbijaRS** [comment]
yes, it save changes, it change but on load customizer don't set toggle button to off 
i need default option that is off(false) and when you want sticky-top you must set that option to on (click on toggle button to make it blue).

**Comment by aristath** [comment]
I don't know what you're doing to print the header in the template itself, but it should be something like this:

```php
<?php
$header_classes = [
	'header-blue'
];
if ( get_theme_mod( 'fixed_navbar', false ) ) {
	$header_classes[] = 'sticky-top';
	$header_classes[] = 'boxshadowsidebar';
}
?>
<div class="<?php echo esc_attr( implode( ' ', $header_classes ) ); ?>">
	.....
</div>
```
Or like this:
```php
<div class="header-blue<?php echo ( get_theme_mod( 'fixed_navbar', false ) ) ? ' sticky-top boxshadowsidebar' : ''; ?>">
	.....
</div>
```
Do you have something like the above implemented?
`js_vars` will handle changes to values updating the preview via `postMessage`, but it doesn't have any effect on the initial status - or that status outside the customizer. There will have to be a PHP implementation in place as well
