### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by famfam** [themeum/kirki#214]
Is possible add a reset button to default values in sections and/or panels?

**Comment by aristath** [comment]
This is not currently possible.
However it's on our TODO list.
If you're using theme_mods and you want a global reset button then you could use this plugin: https://wordpress.org/plugins/customizer-reset-by-wpzoom/screenshots/

**Comment by DevelopOnline** [comment]
In the ideal situation ,each control should has **a separate reset button**.

**Comment by misfist** [comment]
I agree this would be useful. But, in the meantime, thanks for the tip about the Customizer Reset plugin. It does what I was looking for.

**Comment by aristath** [comment]
Reset buttons are a bit weird.
I mean sure, it's possible...
But the problem is what to reset.
Should you have a reset on each control? On each section? Perhaps on each panel? Or global?
That's why I haven't even touched this one... The nightmare part of this issue is not the technical part, but the usability part.

**Comment by misfist** [comment]
For me, I wanted to reset everything because I'm testing. The Customizer Reset plugin does just that. So, this enhancement doesn't seem like a high priority.

**Comment by Vishal-Deshpande** [comment]
Having used ReduxFramework for quite some time, I am really missing the Reset Button. I would prefer section based reset button.

**Comment by aristath** [comment]
I guess resetting settings on a per-section basis makes sense...
Reset implemented on https://github.com/aristath/kirki/commit/d2d8f1064450d330e68b4871104e1dc78cc37833
Not all control-types can be reset, it's still a work in progress. but most of them work fine.

**Comment by Vishal-Deshpande** [comment]
Reset Button is working nicely except on
1) Repeater
2) Sortable
3) Textarea

**Comment by Vishal-Deshpande** [comment]
@aristath 

I think you missed my above comment. Can you please have a look at it?

**Comment by aristath** [comment]
@PlayerThemes I Created separate issues for those.
