### ISSUE TITLE
Repeater Field without default rows causes issues

### ISSUE THREAD

**Issue by sebrosen** [themeum/kirki#2141]
### Issue description:
I'm trying to create a repeater field with no default rows, however if you don't add a default row it still adds one, and this row doesn't work. If you give the row values and then publish and refresh, the row disappears.

### Version used:
3.0.39

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'theme_config_id', [
	'type'        => 'repeater',
	'label'       => esc_html__( 'Repeater Control', 'kirki' ),
	'section'     => 'section_id',
	'priority'    => 10,
	'row_label' => [
		'type'  => 'text',
		'value' => esc_html__('your custom value', 'kirki' ),
	],
	'button_label' => esc_html__('"Add new" button label (optional) ', 'kirki' ),
	'settings'     => 'my_setting',
	'fields' => [
		'link_text' => [
			'type'        => 'text',
			'label'       => esc_html__( 'Link Text', 'kirki' ),
			'description' => esc_html__( 'This will be the label for your link', 'kirki' ),
			'default'     => '',
		],
		'link_url'  => [
			'type'        => 'text',
			'label'       => esc_html__( 'Link URL', 'kirki' ),
			'description' => esc_html__( 'This will be the link URL', 'kirki' ),
			'default'     => '',
		],
	]
] );
```

As you can see, there's no default rows but when you go to the field there's a default field anyway and if you enter values into this row and publish+refresh, the field will be gone.

Hopefully there's an easy fix to this!
Thank you for your hard work on this wonderful plugin!

**Comment by DannyCooper** [comment]
Confirmed bug.

**Comment by DannyCooper** [comment]
Hi @sebrosen,

I've just pushed a fix to the `develop` branch which I believe fixes this. Would you mind testing?

Thanks
