### ISSUE TITLE
Kirki with Bedrock as mu-plugin - url path leads to 404

### ISSUE THREAD

**Issue by emanueljacob** [themeum/kirki#2144]
### Issue description:
**Prior notices**
I am trying to use Kirki as a dependency of a custom mu-plugin used in a local wordpress installation which uses [bedrock](https://roots.io/bedrock/).

About bedrock:
In short, bedrock is a boilerplate for creating wordpress within a subdirectory.
So basically it moves the wp-content to a separated directory and renames it to app.
This is done by using the wordpress native constants i.e. (WP_CONTENT_DIR, WP_PLUGIN_DIR, WP_PLUGIN_URL, PLUGINDIR). 

*Little notice here: By default it does not seem to use the constant MUPLUGINDIR, but I added it by myself in the bedrock application.php. (which is the preferred way for adding wp-config constants as referenced in their documentation).*

In my specific case I installed Kirki using Composer within my plugin. But even if I use it as a "normal" mu-plugin, by downloading the plugin from the Wordpress Plugin Directory and manually move it into mu-plugins, the following issue will occur.

**The issue**
Panel and sections show up in customizer as intended. But **fields do not**. 
Instead no JS dependencies can be loaded (404 not found), because of the wrong url path.
<img width="640" alt="screenshot_1280" src="https://user-images.githubusercontent.com/28386816/56419494-ae48c100-629a-11e9-9e23-df234d5137d9.png">

After some investigation its the following function of the Class Kirki_Init which seem to cause the issue in context of "is_admin" (in backend customizer only):

```php
//Class Kirki_Init
public static function set_url() {
	if ( Kirki_Util::is_plugin() ) {
		return;
	}
	
	// Get correct URL and path to wp-content.
	$content_url = untrailingslashit( dirname( dirname( get_stylesheet_directory_uri() ) ) );
	$content_dir = wp_normalize_path( untrailingslashit( WP_CONTENT_DIR ) );
	Kirki::$url = str_replace( $content_dir, $content_url, wp_normalize_path( Kirki::$path ) );
	// Apply the kirki_config filter.
	$config = apply_filters( 'kirki_config', array() );
	if ( isset( $config['url_path'] ) ) {
		Kirki::$url = $config['url_path'];
	}

	// Make sure the right protocol is used.
	Kirki::$url = set_url_scheme( Kirki::$url );
}

```

I checked the $url variable in some random scopes and the value mostly seem fine, but when var_dumping the $url value within your "enqueue" function (in class "Kirki_Control_Base") the value is wrong.

### Version used:
3.0.39 installed via Composer
alternatively
3.0.39 downloaded via Wordpress Plugin Directory and manually 

Called via requiring the kirki.php file and then setup (1 demo: Config, Panel, Section, Field) as described in your docs.

**Comment by emanueljacob** [comment]
ok looks like I am blind somethimes... :smirk:

just had to use your filter

```php
/**
 * Configuration sample for the Kirki Customizer
 */
function my_config() {

    $args = array(
        'url_path'      => 'my_path',
    );

    return $args;

}
add_filter( 'kirki/config', 'my_config' );
```


 to set the $config['url_path']

**Comment by aristath** [comment]
Yeah, the filter is the easy way... I was trying to think of a way to accommodate mu-plugin installations but didn't have time to really check this, I'm working on the 4.0 refactors at the time and I had more basic issues to deal with. :yum: 
I opened #2145 just as a reminder to check this when I'm done with the basics of the 4.0 implementation.
In the refactor everything is getting split to separate packages and I have a package dedicated to getting the URLs from paths, you can see it here: https://github.com/kirki-framework/url-getter/blob/master/src/URL.php#L121
Instructions are on the README file on that repo if you're in the mood to test it :+1:
