### ISSUE TITLE
Setting color instead of background-color when previewing Typography

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#2149]
### Issue description:
I am using the the `property` and `choice` arguments to use the **color** from the **Typography** control, like so:

```
Kirki::add_field('mytheme', array(
  'type' => 'typography',
  ...
  'output' => array(
    array(
      'element' => array(
        'nav',
        '.entry-footer',
      )
    ),
    array(
      'element' => array(
        '#site-navigation a',
        '#site-navigation .svg-icon', <----------
      ),
      'property' => 'color', <----------
      'choice'   => 'color'
    ),
    array(
      'element' => array(
        '.mini-cart .cart-notification' <----------
      ),
      'property' => 'background-color', <----------
      'choice'   => 'color'
    )
  )
));
```
As you can see, I'm using the **color** to set the color for `.svg-icon` and `background-color` for `.cart-notification`.

This works well after publishing the customizer changes, but it sets the color instead of the background-color during preview.

See video here:
http://share.hellodetail.com/7b5dcd

### Version used:
Plugin v3.0.39

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
See above.

**Comment by DannyCooper** [comment]
Tested the following in 3.0.42 and it worked as expected:
```
		'type'        => 'typography',
		'settings'    => 'typography_setting_1',
		'label'       => esc_html__( 'Typography Control Label', 'kirki' ),
		'description' => esc_html__( 'The full set of options.', 'kirki' ),
		'section'     => 'typography_section',
		'priority'    => 10,
		'transport'   => 'auto',
		'default'     => [
			'color'           => '#333333',
			'font-family' => 'Roboto',
		],
		'output'      => array(
			array(
				'element' => array(
					'.mini-cart .cart-notification',
				),
				'property' => 'background-color',
				'choice'   => 'color',
			)
		),
```

Please test the latest version and let me know if your issue persists.

**Comment by joakimaglo** [comment]
I actually switched to using a color control instead of typograpghy for setting the background color of my `.cart-notification` (not because of the issue I experienced above but for other reasons).

So this can be closed from my perspective.

But I tested it again for the sake of this issue and still had the same problem. Using plugin version 3.0.44.
