### ISSUE TITLE
Kirki Field::set_partial_refresh was called incorrectly

### ISSUE THREAD

**Issue by Imransdesign** [themeum/kirki#2150]
What I'm doing wrong here?
```php
                              <?php function hero_heading() { ?>
						<h1 class="hero-heading">
                           <?php echo esc_html(get_theme_mod('hero_heading')); ?>
                        </h1>
                        <?php } ?>
```

```php
'partial_refresh' => array(
     'hero_heading' => array(
           'selector'        => '.hero-heading',
            'render_callback' => 'hero_heading',
       ),
),
```

**Comment by aristath** [comment]
is that on the stable version, or did you download from this repository?

**Comment by Imransdesign** [comment]
I'm using it as a plugin from Wordpress.org, I've included it using TGM

**Comment by aristath** [comment]
hmmmm callbacks are supposed to return content, not echo it.
Try this:

```php
'partial_refresh' => [
    'hero_heading' => [
        'selector'            => '.hero-heading',
        'render_callback'     => function() {
            return '<h1 class="hero-heading">' . esc_html( get_theme_mod( 'hero_heading', '' ) ) . '</h1>';
        },
        'container_inclusive' => true,
    ],
],
```

Or even better this:
```php
'partial_refresh' => [
    'hero_heading' => [
        'selector'            => '.hero-heading',
        'render_callback'     => function() {
            return esc_html( get_theme_mod( 'hero_heading', '' ) );
        },
        'container_inclusive' => false,
    ],
],
```

**Comment by Imransdesign** [comment]
Thanks for your help @aristath 
**Noted:** callbacks are supposed to return content, not echo it.

**Comment by Imransdesign** [comment]
Before you close this, Anyway to use attributes (for ex: href) as a selector?
lets say I have a button like this: 
`<a class="btn" href="">......</a>`
How do I target this using selector?

**Comment by aristath** [comment]
> Anyway to use attributes (for ex: href) as a selector?

https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

But `partial_refresh` may not be the best option... It depends on what you want to do. And depending on what you want to achieve, sometimes the `js_vars` argument may be more appropriate.
If for example you just want to change the text of an element, instead of doing this:
```php
'transport'       => 'postMessage',
'partial_refresh' => [
    'hero_heading' => [
        'selector'            => '.hero-heading',
        'render_callback'     => function() {
            return esc_html( get_theme_mod( 'hero_heading', '' ) );
        },
        'container_inclusive' => false,
    ],
],
```
you may want to do this:

```php
'transport' => 'postMessage',
'js_vars'   => [
	[
		'element'  => '.hero-heading',
		'function' => 'html',
	],
],
```

Partial-refreshes make an ajax call and are relatively slow. They are useful when you want to refresh part of your template. But for simple things like what you want to do, `js_vars` will be faster and a lot simpler.
