### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#2151]
Hey,

I'm working on something that requires everything to be an option.

However, it isn't registered as an option, but a theme mod.

Here is my code:

```
Kirki::add_config('global_options', array(
    'capability' => 'edit_theme_options',
    'option_type' => 'option',
));

Kirki::add_section('global-section', array(
    'title' => esc_html__('Global', 'kirki'),
    'priority' => 0,
));

Kirki::add_field('global_options', array(
        'settings' => 'global-bg-color',
        'type' => 'color',
        'label' => esc_attr__('Background color', 'textdomain'),
        'section' => 'global-section',
        'css_vars' => '--global-color',
        'transport' => 'postMessage',
        'choices' => [
            'alpha' => true,
        ],
    )
);

Kirki::add_field('global_options', [
    'type' => 'slider',
    'settings' => 'global-container-width',
    'label' => esc_html__('Container width', 'kirki'),
    'description' => esc_html__('Width of the inside container where all of your content lives.', 'kirki'),
    'section' => 'global-section',
    'default' => 1440,
    'css_vars' => array(
        array('--wrapper-width', '$px'),
    ),
    'transport' => 'postMessage',
    'choices' => [
        'min' => 0,
        'max' => 2560,
        'step' => 1,
    ],
]);

Kirki::add_field('global_options', [
    'type' => 'slider',
    'settings' => 'global-padding',
    'label' => esc_html__('Container padding', 'kirki'),
    'description' => esc_html__('Distance between the start of your content and the edge of the window.', 'kirki'),
    'section' => 'global-section',
    'default' => 4,
    'css_vars' => array(
        array('--global-padding', '$vw'),
    ),
    'transport' => 'postMessage',
    'choices' => [
        'min' => 0,
        'max' => 20,
        'step' => 1,
    ],
]);

Kirki::add_field('global_options', [
    'type' => 'slider',
    'settings' => 'global-margin',
    'label' => esc_html__('Section margin', 'kirki'),
    'description' => esc_html__('Spacing between sections.', 'kirki'),
    'section' => 'global-section',
    'default' => 4,
    'css_vars' => array(
        array('--margin-section', '$em'),
    ),
    'transport' => 'postMessage',
    'choices' => [
        'min' => 0,
        'max' => 10,
        'step' => 1,
    ],
]);
```

Am I missing something?

Best,
Dennis

PS: Thanks for this great plugin!

**Comment by aristath** [comment]
Looks OK to me... After saving I can see the option just fine in my database using phpmyadmin
![Screenshot_2019-05-08 localhost localhost lemonade wp_options phpMyAdmin 4 6 6deb5](https://user-images.githubusercontent.com/588688/57396901-1b81af00-71d4-11e9-913d-ea2c5f0bcb9a.png)

Are you using the stable version from w.org or the develop branch?

**Comment by ghost** [comment]
Hmm I wonder if the tables didn’t update accordingly since I switched all the same settings from a theme_mod.. will check once I am home.

I am including the plugin in my theme (last method on the website), but will likely switch to just activating it via w.org

**Comment by aristath** [comment]
Keep in mind that the dev version from github is unstable, so I'd recommend using the latest stable version from w.org :+1:

**Comment by ghost** [comment]
Hey, I just switched to the w.org version, but my options are still getting saved as theme_mods per theme.

Some background to my setup:

One Parent Theme that has all the Customizer settings in place using Kirki. I am changing the customizer settings via child themes. When I have a look into the DB, this is what I am seeing:

![thememods](https://user-images.githubusercontent.com/39319746/57439884-3ccfb300-7247-11e9-8f54-6d72ec7c2c40.png)

Singular entries for each child theme, what am I missing?

**Comment by ghost** [comment]
I just realised I was requiring the main controls before I setup the config.

```
Kirki::add_config('spx_global_options', array(
    'capability' => 'edit_theme_options',
    'option_type' => 'option',
    'option_name' => 'spx_global_options',
));

require('header.php');
require('global.php');
```

This fixed my issue.
