### ISSUE TITLE
Auto generated CSS works ony on customizer preview

### ISSUE THREAD

**Issue by sachyya** [themeum/kirki#2152]
### Issue description:
While using `type color` with `transport auto`, the auto generated CSS works only on customizer preview. The latest color control which is changed is generated only on frontend. Note that the controls is being shown by `active callback` value of another control. I have been stuck on this for a week now.

### Version used:
3.0.39

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
If you provide me with gitlab username, I can give you the access to the theme.

**Comment by aristath** [comment]
Are you by any chance adding your controls on `customize_register` or something like that?

**Comment by aristath** [comment]
username on gitlab is the same as here: aristath

**Comment by sachyya** [comment]
No. I have loaded it directly into the `functions.php`. 

I have added you on my theme. Please have a look. The issue is another branch: feature/regenerate-bug

**Comment by aristath** [comment]
@sachyya I just cloned your repo and tried it, I don't see an issue... I tried with the `header_bg_color`. Should I try with some other control?

**Comment by sachyya** [comment]
The issue is in the **Advanced Options->Colors->Heading typography:**

**Comment by aristath** [comment]
Still works fine for me...
What is the ID of the setting you have an issue with?

**Comment by sachyya** [comment]
The control is being generated in a loop:
```
foreach ( $heading_typo_defaults as $i => $value ) { 
			$i++;
			$font_size = $value[0];
			$line_height = $value[1];
			$headings_typo[] = array( 
				'type'        => 'typography',
				'settings'    => 'global_h' . $i . '_typo',
				'transport' => 'auto',
				'section'     => 'colors',
				'default'     => array(
			        'color'			 => '#000',
			        'font-size'			=> $font_size,
			        'line-height'	=> $line_height,
			        'letter-spacing'	=> '0px',
			        'text-transform'	=> 'none',
			        'font-family'    => '"Playfair Display", serif',
			        'variant'        => 'regular',
			    ),
				'output' => array(
				    array(
				        'element'  => array( '.entry-content h' . $i, '.sidebar h' . $i, 'footer h' . $i ),
				    ),
				),
				'active_callback'  => array(
			        array(
			            'setting'  => 'global_headings_list',
			            'operator' => '==',
			            'value'    => 'h' . $i,
			        ),
			    ),
			);
		}
```
`h1_color` and `h2_color`

**Comment by aristath** [comment]
Ummmm I don't know if I'm missing something, but I can't find `$heading_typo_defaults` anywhere in your code. Is it on some other branch? Is it on some code you haven't committed to your repository? Some code someplace else?

**Comment by sachyya** [comment]
The issue is another branch: feature/regenerate-bug

**Comment by aristath** [comment]
First of all, instead of this:
```php
foreach ( $heading_typo_defaults as $i => $value ) { 
	$i++;
	$font_size = $value[0];
	$line_height = $value[1];
```
you may want to do this:

```php
for ( $i = 1; $i <= 6; $i++ ) {
	$font_size = $heading_typo_defaults[ $i - 1 ][0];
	$line_height = $heading_typo_defaults[ $i - 1 ][1];
```
Incrementing `$i` on each loop and re-defining it in the loop as a key can get a little confusing. The above solution is easier to understand and leaves no room for error.

In your customizer you have a radio-buttonset that you use as a tab-switcher. Then in the customizer controls you have an `active_callback` to show/hide fields. However, `active_callback` also affects the output of the css... If a field is inactive, its CSS is not printed.
To remove that behaviour and add CSS for fields even if they are hidden, you can add this filter:

```php
add_filter( 'kirki_code_manas_config_css_skip_hidden', '__return_false' );
```

**Comment by sachyya** [comment]
@aristath , this works. Thanks a lot.
