### ISSUE TITLE
Repeater and active_callback

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#2153]
Hi friends . 
I just want to know if the Repeater field type  support 'active_callback' parameter , if yes how ??

**Comment by rray524** [comment]
Please support this active_callback argument on the repeater field by releasing a new updated version.

**Comment by aristath** [comment]
If you are referring to active_callback arguments in fields inside the repeater itself then this will be implemented at some point, but requires a complete rewrite of the plugin. The rewrite is already underway but there is no ETA as it's more complicated than one would suspect.
If you are referring to active_callback arguments in the repeater field (i.e. show the repeater if field A has value X) then you can already do that.

Closing this one as a duplicate, there's another ticket already for repeater sub-fields dependencies.
