### ISSUE TITLE
Text transform field jumps into new row when line height is active

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#2156]
See those two screenshots:

![typo1](https://user-images.githubusercontent.com/39319746/57981421-9ac67c80-7a37-11e9-9b5c-43552e39451a.png)
![typo2](https://user-images.githubusercontent.com/39319746/57981425-9bf7a980-7a37-11e9-98a8-496734bbf08e.png)

The text-transform field seems to jump into a new row when line-height is activated. Is there a reason for this?

**Comment by DannyCooper** [comment]
This is due to the ordering of the fields in `controls/php/class-kirki-control-typography.php`.

It's a simple fix, but the control as a whole is being re-written at the moment.

**Comment by DannyCooper** [comment]
For future reference here is how it looks with all fields in use - 
![image](https://user-images.githubusercontent.com/152804/59962731-1016e880-94e1-11e9-9797-2630215194b7.png)

Marking this as #wontfix - but the design of this control is being reviewed as part of 4.0.
