### ISSUE TITLE
Display CSS variables in color palette control

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#2157]
It would be amazing if we could show CSS variables colours in the palette control. This could give users a huge UX boost when using the customizer to design their sites. What do you think @aristath ?

**Comment by aristath** [comment]
I don't understand what you mean exactly...

**Comment by ghost** [comment]
For example if this would be possible:

```
Kirki::add_field('spx_global_options', [
    'type' => 'color-palette',
    'settings' => 'spx-colours-global-palette',
    'label' => esc_html__('Color-Palette', 'kirki'),
    'description' => esc_html__('This is a color-palette control', 'kirki'),
    'section' => 'spx-colours-section-global',
    'default' => '#888888',
    'choices' => [
        'colors' => ['var(--color-primary)', 'var(--color-secondary)', 'var(--color-tertiary)'],
        'style' => 'round',
    ],
]);
```
![palettes](https://user-images.githubusercontent.com/39319746/57984973-797a8600-7a61-11e9-94fd-c9db4d0c6ee5.png)

For this to work the variables would need to be loaded inside the customizer as well (not just the iframe) and I assume the actual colour control would need to update those two variables (customizer & iframe) at the same time.

**Comment by aristath** [comment]
I see... No, this is not something that I've got planned for the near future.
There's a new color control coming soon that combines the Gutenberg palettes from themes and a colorpicker, but the palettes are defined in the theme and not user-customizable (see https://github.com/kirki-framework/control-color/wiki).
This is something you'll have to custom-code.
