### ISSUE TITLE
Tracking in Font Awesome

### ISSUE THREAD

**Issue by macgyvercy** [themeum/kirki#2161]
### Issue description:
We have to include kirki plugin in our plugin but WP plugin reviewers don't accept it for following reason. Any plan to refactor?

> In 2016, Font Awesome introduced a new way to get their font library, via a URL like https://use.fontawesome.com/CUSTOMCODE.js 
> 
> The problem with it is that it's tied to an individual's email, which means it's actually trackable. That can be a legal issue when it comes to disclosure of data and is something best avoided whenever possible. Not to mention, we don't allow tracking unless it's opt in. 
> 
> We need you to use the font-awesome anonymous CDN - https://www.bootstrapcdn.com/fontawesome/
> 
> Some examples from your plugin:
> 
> /jupiterx-core/includes/customizer/vendors/kirki/controls/php/class-kirki-control-fontawesome.php:38:
> wp_enqueue_script( 'kirki-fontawesome-font', 'https://use.fontawesome.com/30858dc40a.js', array(), '4.0.7' );
> /jupiterx-core/includes/customizer/vendors/kirki/modules/css/class-kirki-modules-css.php:218:
> wp_enqueue_script( 'kirki-fontawesome-font', 'https://use.fontawesome.com/30858dc40a.js', array(), '4.0.7', true );

### Version used:
3.0.33

**Comment by aristath** [comment]
Yes, this will get refactored and a new version uploaded soon.
Do you use the font-awesome field?

**Comment by macgyvercy** [comment]
Since we didn't need that field, we removed it from our custom version.
