### ISSUE TITLE
You need a higher level of permission

### ISSUE THREAD

**Issue by Imransdesign** [themeum/kirki#2166]
In my multisite, I get this warning, "You need a higher level of permission" when try to use customizer setting. But if I removed kirki plugin cutomizer works fine then. so this issue must be coming from kirki. any thoughts?

**Comment by ArekZw** [comment]
I once had such a problem, clearing the cookies helped me. Try in private browser mode. It seems that in multisite mode, especially with single sign-on/domains mapping plugins sometimes something bad happens with cookies.

**Comment by Imransdesign** [comment]
Yes I already did that to fix my problem. Sorry forgot to update here.
Thanks for your reply @ArekZw
