### ISSUE TITLE
Broken 3.0.41 WordPress pakage - autoload

### ISSUE THREAD

**Issue by rrroig** [themeum/kirki#2171]
### Issue description:
When upgrading from WordPress plug-in manager to version 3.0.41 the autoloader isn't found and the plug-in doesn't work. The file class-kirki-autoload.php is missing in the package but referenced as include.

**Comment by DannyCooper** [comment]
I've not been able to replicate this, I've checked the .org version and that file does exist in 3.0.41 - https://plugins.trac.wordpress.org/browser/kirki/tags/3.0.41/class-kirki-autoload.php

**Comment by rrroig** [comment]
Thanks.Yes, you're right, it's listed. Then i don't know why it was missing once installed. I'll try to replay the upgrade in another server and will try to figure out what could happen. Will reopen if required.
