### ISSUE TITLE
transport auto not working after 3.0.36 when saving as option

### ISSUE THREAD

**Issue by JiveDig** [themeum/kirki#2183]
### Issue description:
I tested a basic color and multicolor field and transport auto is not working even though I have valid output setup. It works with transport refresh, and it also works if I change to theme_mods.

### Version used:
Was working in 3.0.36 but just updated to 3.0.42 and not working. I still need to test the in between versions to see when it actually stopped working.

### Using theme_mods or options?
Options. Theme mods work.

### Code to reproduce the issue (config + field(s))
I will get a stripped down version ASAP, but wanted to get the issue posted incase anyone else sees it already, or can confirm it quicker than I can report back.

**Comment by JiveDig** [comment]
Okay I cloned the repo and tested prior to 3.0.36 and it works, but 3.0.36 and after does not work. I'm a bit surprised that i'm the first to report, which makes me think it's my code issue. I'll try to get a basic example together.

**Comment by JiveDig** [comment]
Hmm, I thought updating may have wiped my fix for this https://github.com/aristath/kirki/issues/2128 but the issue was closed, did this get rolled in? I tried the temp fix and it didn't fix my issue now.

**Comment by JiveDig** [comment]
Ahhh I lied. The fix in #2128 works in 3.0.42. I guess it didn't make it into the plugin? Hoping you can add that in to the next update.

**Comment by DannyCooper** [comment]
The fix was merged upstream - https://github.com/kirki-framework/module-postMessage/commit/2e5f1ff7806eb51af083d43910bc4ddc10edbce1

That means as things stand it won't make it into the plugin until 4.0

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
