### ISSUE TITLE
class-kirki-installer-section.php needs to be changed ???

### ISSUE THREAD

**Issue by LebCit** [themeum/kirki#2187]
### Issue description:
Hello @aristath 
I've recently submitted a theme to WP repository.
I have to make some changes so it can be approved.
Among the changes, is the section in the Customizer recommending the installation of kirki because it's not using the [WordPress Customizer's notification API](https://make.wordpress.org/core/2017/11/01/improvements-to-the-customize-js-api-in-4-9/#notification-improvements)
Thanks in advance for your response and your time.
SYA 😃

**Comment by DannyCooper** [comment]
Please link to the .org trac ticket where the changes were requested.

**Comment by LebCit** [comment]
https://themes.trac.wordpress.org/ticket/68028#comment:6

It's the number 8
This section is created by the class-kirki-installer-section.php file

**Comment by DannyCooper** [comment]
Thanks @LebCit, did you use https://github.com/aristath/kirki/blob/master/docs/files/class-kirki-installer-section.php ?

**Comment by LebCit** [comment]
I've used the following one
https://github.com/aristath/kirki/tree/master/docs/files/class-kirki-installer-section.php
It's the same one

**Comment by LebCit** [comment]
Hello,

Since the reviewer didn't respond on wp.org I'm posting here my temporary solution :
In **customizer.php** I've added the following : 
```
function kis_customize_controls() {
	wp_enqueue_script( 'kis-customize-controls', get_template_directory_uri() . '/js/customize-controls.js', array( 'customize-controls' ), filemtime( get_theme_file_path( '/js/customize-controls.js' ) ), true );
	$customizer_settings = array(
		'class_kirki_exists'         => class_exists( 'Kirki' ),
		'install_kirki_notification' => esc_html( 'Please install the Kirki plugin to take full advantage of this theme\'s customizer capabilities.', 'kis' ),
		'install_kirki_button_value' => esc_html( 'Install Now', 'kis' ),
		'install_kirki_admin_url'    => admin_url( 'plugin-install.php?s=mods&tab=search&type=tag' ),
	);
	wp_localize_script( 'kis-customize-controls', 'kis_cc', $customizer_settings );
}
add_action( 'customize_controls_enqueue_scripts', 'kis_customize_controls' );
```
Then, in **customize-controls.js** I've added the following : 
```
(function( api, $ ) {

	api.bind( 'ready', function () {

		if ( !kis_cc.class_kirki_exists ) {
		
			api.notifications.add(
				new api.Notification(
					'kis-customize-controls', {
						dismissible: true,
						message: kis_cc.install_kirki_notification,
						type: 'info',
					}
				)
			);

			var control = new api.Control( 'button_install_kirki', {
				type: 'button',
				section: 'title_tagline',
				settings: {},
				input_attrs: {
					value: kis_cc.install_kirki_button_value,
					class: 'button button-primary',
				},
			} );
			api.control.add( control );

			api.notifications( 'kis-customize-controls', function( Notification ) {
				setTimeout( function() {
					Notification.container.children( 'div' ).append( $( '#customize-control-button_install_kirki' ) );
					$( '.wp-full-overlay-sidebar-content' ).css( 'top', '156px' );
				}, 5000);
			});

			api.control( 'button_install_kirki', function( control ) {
				control.container.find( '.button' ).on( 'click', function() {
					document.location.replace( kis_cc.install_kirki_admin_url );
				} );
			} );

		}

	} );

} ) ( wp.customize, jQuery );
```
It's working fine, I'm just not really convince by assigning the button to `title_tagline` first and waiting for the Customizer to finish loading then appending the button to the notification.
Is their a way to assign this button directly to the notifications area ?
Is their a pattern to wait for the notification's container to be created (rather than using `setTimeout`) ?
