### ISSUE TITLE
Improve styling for slider controls

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2200]
Right now their styles are inconsistent across browsers. Perhaps we should use one of the many JS libraries out there for sliders. If we do that though we'll need to be 100% certain the script we use is accessible.

**Comment by DannyCooper** [comment]
Firefox macOS:

![image](https://user-images.githubusercontent.com/152804/60508255-06039f80-9cc2-11e9-9e8a-aa80500b8596.png)

Chrome macOS:

![image](https://user-images.githubusercontent.com/152804/60508269-0e5bda80-9cc2-11e9-903d-f2d7c60450bf.png)

**Comment by aristath** [comment]
So the only inconsistency is the handle color. I can live with that... Closing.

**Comment by DannyCooper** [comment]
For the sake of completeness I tried in Edge on Windows 10. Here's what I saw:

![image](https://user-images.githubusercontent.com/152804/60540114-4f75de00-9d06-11e9-846d-054494e01607.png)

Re-opening based on the lack of handle.

**Comment by aristath** [comment]
Fixed.
The custom styles were removed and just the basics were kept.
Sliders are now using the default browser styles. They are not consistent across browsers, but if someone is using Chrome/Firefox/Safari/Edge they are used to seeing sliders a certain way, the native way. This changes makes sure that sliders work everywhere.
