### ISSUE TITLE
Background field: check dependencies

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2206]
v4.0 changed this implementation completely, need to check that sub-field dependencies work ok, and also that if the parent field is hidden children also get hidden.

**Comment by ArekZw** [comment]
Works fine

![captured (4)](https://user-images.githubusercontent.com/11788346/63304475-7488d500-c2e3-11e9-90a3-458f3c2af4b7.gif)

**Comment by aristath** [comment]
Perfect, thanks for testing! Closing this one. 👍
