### ISSUE TITLE
Dimensions field: collapse to a single row if possible

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2209]
If the values are top/bottom/left/right or width/height, we should be able to prepend icons to the inputs, hide the labels, and add the inputs inline instead of one on top of the other.

**Comment by DannyCooper** [comment]
Do you have an iconset in mind? Maybe Dashicons?

![image](https://user-images.githubusercontent.com/152804/60506480-cd61c700-9cbd-11e9-8872-19d177d939bf.png)
