### ISSUE TITLE
Typography field: check dependencies

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2211]
v4.0 changed this implementation completely, need to check that sub-field dependencies work ok, and also that if the parent field is hidden children also get hidden.

**Comment by ArekZw** [comment]
There is a problem with the "italics" and "underline" sub-fields.

![2211](https://user-images.githubusercontent.com/11788346/63304116-3ccd5d80-c2e2-11e9-9075-052d6e406477.gif)

**Comment by aristath** [comment]
👍 labeled as bug

**Comment by aristath** [comment]
Turned out to be a CSS issue, fixed.
