### ISSUE TITLE
CSS-Vars module: merge with CSS module

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2212]
With a few tweaks we shouldn't even need a separate module for css-vars... They can be merged in the CSS module.

**Comment by aristath** [comment]
Took a look at this one and it's not as simple as I initially thought.
Moving to v4.1

**Comment by aydinvivik** [comment]
How can we use css var() ?

for example: 

:root {
    --main-bg-color: red;
}

body {
    background-color: var(--main-bg-color);
}

**Comment by aristath** [comment]
In your field:
```php
'output' => [
	[
		'element'  => ':root',
		'property' => '--main-bg-color'
	],
],
```
then in your stylesheet:
```css
body {
  background-color: var(--main-bg-color);
}
```
