### ISSUE TITLE
Option to remove alpha in the Multicolor control per color

### ISSUE THREAD

**Issue by VladNov** [themeum/kirki#2216]
### Issue description:
Is there an option to remove alpha separately per color in the Multicolor control? Currently if we add 'alpha' => false in the main array, the alpha is removed for all colors.

### Version used:
3.0.44

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Regular multicolor control.

**Comment by mapsteps** [comment]
This is not currently supported. If we can get more requests like this one we will consider adding this to our roadmap.
