### ISSUE TITLE
Output Dropdown pages

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#2217]
How should we output the fetched link in the anchor text in the theme → 
`<a href=""></a>`

This page doesn't have that detail→
https://kirki.org/docs/controls/dropdown-pages

**Comment by DannyCooper** [comment]
https://developer.wordpress.org/reference/functions/get_permalink/

**Comment by fastmarketo** [comment]
You didn't get the question. The link will come from get_theme_mod something like this.

**Comment by aristath** [comment]
Oh he got the question. `get_permalink` is the function you'll have to use to get the permalink from the post-ID.
You can use `get_theme_mod` to get the post-ID for your option.

**Comment by fastmarketo** [comment]
This is sample:

`Kirki::add_field( 'theme_config_id', [
	'type'        => 'dropdown-pages',
	'settings'    => 'my_setting',
	'label'       => esc_html__( 'This is the label', 'kirki' ),
	'section'     => 'section_id',
	'default'     => 42,
	'priority'    => 10,
] );`

How can we output the link selected here, for example,
<a href=""></a>

**Comment by fastmarketo** [comment]
my_setting is the key. This has to be enveloped somehow with the permalink, but how?

**Comment by DannyCooper** [comment]
```php
$selection = get_theme_mod( 'my_setting' );
$title = get_the_title( $selection );
$url = get_the_permalink( $selection );

echo '<a href="' . esc_url( $url ) . '">' . $title . '</a>';
```

**Comment by fastmarketo** [comment]
Thanks @DannyCooper

**Comment by aristath** [comment]
@fastmarketo while we try to educate our users on how to use kirki, this has nothing to do with kirki.
This is basic PHP and thought @DannyCooper was kind enough to provide the actual code you should use, this will not always be the case.
Kirki is a framework used by people who want to build themes. As such, it assumes a minimum of PHP knowledge that is required to actually build a WordPress theme.
