### ISSUE TITLE
Override default field in child theme

### ISSUE THREAD

**Issue by kmyn** [themeum/kirki#2220]
### Issue description:
Hi,

I'm trying to override the **_default_** '_**font-family**_' which is set by Kirki:add_field() in the parent theme in the child theme. Wondering if someone can provide me with some pointers? Below is the snippet from the parent theme.

```
Kirki::add_field( 'abcxyz', array(
        'type'        => 'typography',
        'settings'    => 'font_heading_settings',
        'label'       => esc_html__( 'Headings', 'abcxyz' ),
        'section'     => 'google_fonts_section',
        'default'     => array(
                'font-family'    => '"sk-modernist", "Helvetica Neue", Helvetica, Arial, sans-serif',
                'variant'        => 'bold',
                'subsets'        => array( 'latin-ext' ),
        ),  
        'priority'    => 20, 
        'output'      => array(
                array(
                        'element' => 'h1, h2, h3, h4, h5, h6, .entry-content h2 a', 
                ),  
        ),  
) );
```

Thanks.

**Comment by DannyCooper** [comment]
Are you trying to override the setting to customize it to your own needs?

 Or override the value it outputs to change the appearance of your child theme?

**Comment by kmyn** [comment]
Hi @DannyCooper ,

I'm trying to change the default 'font-family' to 'Tahoma, Geneva, sans-serif' so that all the headings are displayed with that font by default. The only option I found was to change the default behavior. If there is any other easier way, I'm more than to explore.

thanks.

**Comment by DannyCooper** [comment]
Is this for a child theme you plan to release, or a single project/website?

**Comment by kmyn** [comment]
@DannyCooper this is for a single project/website. As I had my own customization's, I created a child theme for it.

**Comment by DannyCooper** [comment]
I'm struggling to understand why you can't just change the setting in the Customizer then to achieve your goal?

**Comment by kmyn** [comment]
@DannyCooper the way this theme is, I only find very few system fonts and the rest are google fonts in the customizer. Please take a look at the screen shot. 

<img width="292" alt="Screen Shot" src="https://user-images.githubusercontent.com/18484353/60761256-ea2a3180-a012-11e9-9df1-d9f9eb0dc584.png">

**Comment by DannyCooper** [comment]
There are multiple ways to achieve this, as this is for one project I think the fastest way would be to just add your own CSS override:

```
h1, h2, h3, h4, h5, h6, .entry-content h2 a {
    font-family: Tahoma, Geneva, sans-serif !important
}
```

**Comment by aristath** [comment]
> the way this theme is, I only find very few system fonts and the rest are google fonts in the customizer. Please take a look at the screen shot.

These are just the short names used.
The full stack used in the CSS looks like this:
* Serif: `Georgia,Times,"Times New Roman",serif`
* Sans Serif: `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif`
* Monospace: `Monaco,"Lucida Sans Typewriter","Lucida Typewriter","Courier New",Courier,monospace`

The reason we write them like serif/sans-serif/monospace instead of listing the full stack is simply because it doesn't fit. Each device has different fonts, so we use the same defaults that WordPress Core uses for them to cover all cases, and then use the short names for the dropdown.

**Comment by kmyn** [comment]
@DannyCooper , your solution works. It's simple and clean.

@aristath Thank you for that explanation.

I'm all set now.
