### ISSUE TITLE
Kirki and ACF repeater or flexible fields?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2225]
Hi!
Is there any possibility to use Kirki with ACF Repeater or Flexible fields? For example if I add new Flexible row, then in Kirki automatically is add section or panel with specified controls, like margin, colors, fonts etc. I'm looking some light solution to control basic settings for each section I create with ACF.

Thanks!

**Comment by DannyCooper** [comment]
There's no current examples of that available, but there's no reason you couldn't write code that automatically generates Kirki panels/sections/fields using the values pulled from an ACF repeater.
