### ISSUE TITLE
Kirki with visual composer

### ISSUE THREAD

**Issue by deepakchandra00** [themeum/kirki#2226]
when I m using kirki plugin with visual composer.... its hide or remove visual compose accordion and tab shortcodes element.

**Comment by aristath** [comment]
@deepakchandra00 I don't understand...

**Comment by deepakchandra00** [comment]
its simple ur plugin is a conflict with visual composer...  kindly check... after your plugin installation visual composer accordion is not showing...

**Comment by aristath** [comment]
Please provide some more details. I can't replicate an issue unless I know what you're trying to do... Are you using a theme that includes kirki? If so, which theme? 
Which version of visual composer are you using? 
Where is the accordion? 
Are you talking about an accordion in VC's settings? 
Are you talking about an accordion element from VC?
Does the conflict happen inside the customizer?
If the conflict is outside the customizer then I don't see how kirki could be related.
Are there any errors in your browser's console? 
Any information you can provide would be helpful.
