### ISSUE TITLE
Getting Js erros using the repeator for dropdown pages

### ISSUE THREAD

**Issue by tikarambhandari** [themeum/kirki#2227]
### Issue description:
The error displayed on the console is 
**TypeError: can't assign to property "item" on "": not an object**
The same code worked on the previous version of the plugin but I am getting this error after I started working after some months.  When I select a type from the drop-down, I have set page as a default. Instead of getting add page I get a page 1 repeater with list of drop-down pages and when I try to select a page I get the error as mentioned above. 

### Version used:
3.0.44

### Code to reproduce the issue (config + field(s))
```php
theme_one_config_kirki_add_field( array(
		'settings' => 'theme_one_service_pages',
		'type'     => 'repeater',
		'section'  => 'theme_one_service',
		'priority'    => 10,
		'row_label'  => array(
			'type'  => 'text',
			'value' => esc_attr__( 'Page', 'my_textdomain' ),
		),
		'button_label' => esc_attr__( 'Add Page', 'textdomain' ),
		'fields'   => array(
			'item' => array(
				'type'  => 'dropdown-pages',
			),
		),
		'active_callback' => array(
			array(
				'setting'  => 'theme_one_service_visibility',
				'operator' => '!==',
				'value'    => 'disabled',
			),
			array(
				'setting'  => 'theme_one_service_type',
				'operator' => '===',
				'value'    => 'page',
			),
		),
	) 
);
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
