### ISSUE TITLE
Slider control Not working properly 

### ISSUE THREAD

**Issue by truetesterphp** [themeum/kirki#223]
When i am update slider value, then slider bar not update . Check attached screenshot .
My slider Max value is :100 , i have set it on 60 but green bar Not show .

![customize- masonry gallery - mcqueen 2015-05-11 17-20-30](https://cloud.githubusercontent.com/assets/10518894/7564203/2ad640a6-f799-11e4-82c8-3979c0cc352e.png)

**Comment by aristath** [comment]
Are you by any chance using Kirki embedded in a theme?
Could you please post your configuration here?

**Comment by truetesterphp** [comment]
No I am not change in Kirki embedded in a theme. 
My Configuration is :
$controls[] = array(
    'type'     => 'slider',
    'setting'  => 'vertical_gallery_column_width',
    'label'    => __( 'Column Width', 'Column Width' ),
    'section'  => 'section_galleries_three',
    'default'  => 36,
    'priority' => 1,
    'choices'  => array(
        'min'  => 1,
        'max'  => 100,
        'step' => 1,
    ),
);

**Comment by aristath** [comment]
No, I don't mean the field...
Have you used a configuration like this? http://kirki.org/#configuration
If yes, then have you added a `url_path` in your configuration?
If Kirki is used as a plugin then you should remove that.

**Comment by truetesterphp** [comment]
Actually i am Include "kirki" Plugin directory to my wordpress directory and add code in functions.php

include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
$is_kirki_active = is_plugin_active('kirki/kirki.php');
if(!$is_kirki_active)
{
	include (get_template_directory() . "/kirki/kirki.php");
}


after that using field code:
function custom_customizer( $controls ) {

$controls[] = array(
'type' => 'slider',
'setting' => 'vertical_gallery_column_width',
'label' => __( 'Column Width', 'Column Width' ),
'section' => 'section_galleries_three',
'default' => 36,
'priority' => 1,
'choices' => array(
'min' => 1,
'max' => 100,
'step' => 1,
),
);
}

add_filter( 'kirki/controls', 'custom_customizer' );

**Comment by truetesterphp** [comment]
Thanks Now it's working :)
