### ISSUE TITLE
Problem with CSS output color adjustment

### ISSUE THREAD

**Issue by greathemes** [themeum/kirki#2230]
Hello!

This is my first post on Github, I would like to tell you that a great job with this framework! :)

I have one problem. Well, I have a body_background control and I would like to add a few other shades of color on it.

So the effect is then that the body has the color **body_background** and the other element has, for example, **custom_darken('body_background', 5%)** color.

I test different ideas and unfortunately I can not find a solution :) A bit of code to make it clear what's going on:

```
Kirki::add_field( 'my_theme', [
 'type'        => 'color',
 'settings'    => 'body_background',
 'default'     => '#ffffff',
 'output'      => [
  [
   'element'  => 'body',
   'property' => 'background-color', // So this is body background.
  ],
  // And now what I'm trying to do:
  // Try with value_pattern:
  [
    'element'           => '.body-darken',
    'property'          => 'background-color',
    'value_pattern'  => custom_darken( '$', 5 ), // That would work, but unfortunately the '$' character is not converted to hex, so it does not work :)
   ],
  // Try with sanitize_callback:
  [
    'element'           => '.body-darken',
    'property'          => 'background-color',
    'sanitize_callback' => 'custom_darken', // It works, but unfortunately you can not give an argument to this function, so I have to create functions like darken_5_percent_plus_sanitization(), if then I would like other percentages like 10%, 15%, 20% etc. then I have to create a lot of functions. And btw, the sanitizing function should not be changing colors, and generally for security reasons I would prefer not to touch it;)
   ],
 ],
] );
```

Finally, I found this **kirki_my_theme_dynamic_css** filter and I am trying to solve the problem here, but it would be nice if I could dynamically adjust the colors already in the CSS output module, maybe only I can not write it properly?

Any idea? :)

Thanks very much and once again, great work with this framework!

**Comment by aristath** [comment]
Have you tried something like this?
```php
[
	'element'           => '.body-darken',
	'property'          => 'background-color',
	'sanitize_callback' => function( $value ) {
		return custom_darken( $value, 5 );
	}
]
```
