### ISSUE TITLE
Dimensions output

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2232]
I made some options and noticed that dimensions field type does not work with output (css_module as it is written in your documentation ). Is this field compatible to output some css and if so how to make it work ? 

I attach the code i used for that so that you can tell me if there is smth wrong in code or it is just a bug. The output does not work with no 'transport=>auto' nor 'transport=>refresh'. Thx.

```php
Kirki::add_field( 'theme_config', array(
	'type'        => 'dimensions',
	'settings'    => 'container_padding',
	'label'       => esc_html__( 'Paddings', $domain ),
	'description' => esc_html__( 'Controls the paddings.', $domain ),
	'section'     => 'section_02',
	'transport' => 'refresh',
	'default'     => array(
		'padding-top'    => '',
		'padding-bottom' => '',
		'padding-left'   => '',
		'padding-right'  => '',
	),
	'choices'     => array(
		'labels' => $padding_labels,
	),
	'output'      => array(
		array(
	      'choice'      => 'padding-top',
	      'element'     => '.container',
	      'property'    => 'padding-top',
	    ),
	    array(
	      'choice'      => 'padding-bottom',
	      'element'     => '.container',
	      'property'    => 'padding-bottom',
	    ),
	    array(
	      'choice'      => 'padding-left',
	      'element'     => ' .container',
	      'property'    => 'padding-left',
	    ),
	    array(
	      'choice'      => 'padding-right',
		  'element'     => '.container',
	      'property'    => 'padding-right',
	    ),
	),
) );
```

**Comment by aristath** [comment]
Are you using the stable version from w.org, or the develop branch from this repository?

**Comment by Stas0238** [comment]
@aristath Yes i am using the laster stable version from wordpress.org

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
