### ISSUE TITLE
Image fieild type

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2233]
I want to get all image attributes (most needed are thumbnail and alt) at once smth like this http://prntscr.com/omwgms
but for now all i can get is http://prntscr.com/omwhbn.
Can you tell about any tweaks to get this results ? Thx for support

Using latest version from wp.org

**Comment by aristath** [comment]
The field saves the image-ID, so you could use that to get the results you want.

```php
$image_alt = get_post_meta( $image_id, '_wp_attachment_image_alt', true);
$image_title = get_the_title( $image_id );
$thumb = wp_get_attachment_image_src( $image_id, 'thumbnail' );
```

**Comment by Stas0238** [comment]
@aristath Thx, I just thought about saving that from first load but it's ok for me
