### ISSUE TITLE
Extend the typography 

### ISSUE THREAD

**Issue by JuliaArr** [themeum/kirki#2235]
Hi, 

We need to implement some changes in the typography, and therefore we have made our type of control. We use your font-family, font-variant и download font, but we need to change the file kirki\modules\webfonts\class-kirki-fonts-google.php so that in the generate_google_font ($ args) function the condition also should work for our type of control.

At the moment this condition looks like:
`if ( isset( $args['type'] ) && 'kirki-typography' === $args['type'] ) {`

Looking through the developments of your new version, we have investigated that there is an opportunity to change it that way:

`if ( ( isset( $args['type'] ) && 'kirki-typography' === $args['type'] ) || ( isset( $args['choices'] ) && isset( $args['choices']['parent_type'] ) && 'kirki-typography' === $args['choices']['parent_type'] ) ) {`

Or to make a filter:

`$field_types = apply_filters( 'kirki_typography_field_types', array( 'kirki-typography' ) );
if ( isset( $args['type'] ) && in_array( $args['type'], $field_types, true ) ) {`

Could you please add one of this variants to your next update for version 3?

Thank you!

**Comment by aristath** [comment]
Hello there @JuliaArr 
Could you please elaborate? Where would that filter go?

**Comment by JuliaArr** [comment]
Thanks for your reply!

This filter should be added instead of the condition `if ( isset( $args['type'] ) && 'kirki-typography' === $args['type'] ) {` in file kirki\modules\webfonts\class-kirki-fonts-google.php

The matter is that at the moment this condition works only with 'kirki-typography' field type. And we need to make it work with custom field types.

Thank you!

**Comment by JuliaArr** [comment]
Any update for this issue?

Thanks in advance

**Comment by aristath** [comment]
@JuliaArr I added a new `kirki_generate_google_font` filter in the dev branch (v4.0-dev)
