### ISSUE TITLE
Sponsor link broken

### ISSUE THREAD

**Issue by eugenefvdm** [themeum/kirki#2239]
### Issue description:

The sponsor link in Github is broken complains about YML config issue. 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by aristath** [comment]
Thank you for reporting this. I am aware of the issue, we're still on Github's waiting list for the Github Sponsor's program.
The GitHub Sponsors program is still in beta and apparently there's a pretty long queue 😄 
There's a custom link in there too that can be used until the submission for the beta sponsors program gets approved.
