### ISSUE TITLE
Limit access to customiser Panels/Settings

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#224]
Is there any way to restrict access to a setting or panel created with Kirki.
The goal would be to create options that only admins would be to access, not everyone with access to the customiser. 
Is this possible?

**Comment by aristath** [comment]
Sure it's possible!
Just set `'capability' => 'activate_plugins'` in the field's configuration. :+1:

**Comment by lmartins** [comment]
Cool! Thanks @aristath :)
