### ISSUE TITLE
Background field clear

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2241]
I found an issue with background field type. I am using the latest stable version from WP.org and I also download your custom theme for testing kirki demo. I will attach a gif to show you how to recreate the issue from your side and fix it. Watch this https://gyazo.com/d71d7b9ec2d7d5e8fa621c364859d96e. The settings for this field as simple as it can be http://prntscr.com/orhoia. I also tried to change transport to refresh but the results were the same :(
Waiting for an answer from you and thank for such good support you provide to us. Guys you are working for such cool aims.

**Comment by aristath** [comment]
fixed in v4.0.
Please keep in mind that v4.0 is a complete rewrite so this will take some time to be released.

**Comment by Stas0238** [comment]
@aristath Thanks :) Do you know about the date/time of next update ? I want to have it asap !!!
