### ISSUE TITLE
Get default post_id when using Kirki_Helper::get_posts()

### ISSUE THREAD

**Issue by DeoThemes** [themeum/kirki#2242]
### Issue description:
I'm using **Kirki_Helper::get_posts()** for my select control. The problem that I can't fetch default post id value. I can see the list of my posts and I can specify the default value as a post slug, something like this: 'header-1', but I can't get post id based on that. Only when I select other post in the  dropdown and save the changes, I can retrieve post ID from get_theme_mods. I'm looking for a solution how to fetch default post id without saving in the first time. 

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'deo_config', array(
	'type'        => 'select',
	'settings'    => 'deo_header_template',
	'label'       => esc_html__( 'Header Template', 'emaus' ),
	'section'     => 'deo_header',
	'default'     => 'header-1',
	'choices'     => Kirki_Helper::get_posts(
		array(
			'posts_per_page' => -1,
			'post_type'      => 'custom_header'
		)
	)
) );
```

**Comment by aristath** [comment]
`default` should not be the slug. It should be the post-ID.
It sounds to me like what you need is to get the post-ID from the post-slug.
You can use the [get_page_by_path()](https://developer.wordpress.org/reference/functions/get_page_by_path/) function to do that.
