### ISSUE TITLE
Local fonts filters without effect

### ISSUE THREAD

**Issue by ouun** [themeum/kirki#2245]
### Issue description:
There are two filters available in the webfont downloader which do not seem to have any effect: `kirki_googlefonts_root_path` & `kirki_googlefonts_root_url`.

In a multisite environment I would like to use a "shared" folder for all webfonts. So that if a webfont is already loaded to that folder and used by another site, we do not need to download it again. From the logic it should be possible with the filters above, but the do not have any effect.

### Version used:
3.0.44

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
// Set fonts upload path
add_filter(
	'kirki_googlefonts_root_path',
	function( $path ) {
		return untrailingslashit( wp_normalize_path(wp_upload_dir()['basedir'] . '/MyWebfonts' ) );
	}
);
```

**Comment by aristath** [comment]
If I'm not mistaken, on multisite installations `basedir` contains the site-number, dates etc.
You could try using something like `wp_normalize_path( trailingslashit( WP_CONTENT_DIR ) . 'MyWebfonts' )`

**Comment by ouun** [comment]
Thanks for the answer, @aristath. I can use whatever I want for both filters, they are not used anyways. Same for regular WP and all Kirki versions.

**Comment by aristath** [comment]
You're right. Marking this as a bug and I'll investigate in 4.0

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
