### ISSUE TITLE
active_callback - "not contains" operator

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#2247]
It would be nice if the "not contains" operator existed. It's such an "exclusion array"

**Comment by aristath** [comment]
There currently is no such operator.
I added it in the develop branch so it will become available when version 4.0 is released. 👍 

P.S. The operator is called `does not contain`, with an alias `not in` so you'll be able to use whichever you prefer (just like `contains` has an alias `in`).

**Comment by ArekZw** [comment]
Great, thanks
