### ISSUE TITLE
Custom Site Title

### ISSUE THREAD

**Issue by pkohara** [themeum/kirki#2252]
### Issue description:
I am trying to change the font of my site title to Hesterica, a font I have downloaded and then uploaded to wordpress. My site is https://yogimind.co.uk I am using Di Blog pro as my theme.

I've asked Di Blog and they said they have google fonts and then directed me to this discussion: https://github.com/aristath/kirki/issues/1807#issuecomment-529140510

I have tried the code in there adding it to the additional CSS and I've tried 

```
@font-face {
	font-family: FontName;  
	src: url(public_html/your-site/wp-content/themes/your-theme/fonts/FontName-Regular.ttf);  
	font-weight: normal;  
}

.site-title, .site-description {
    font-family: cinzel;
}
```

Let me know what more information you need! Thanks!

**Comment by aristath** [comment]
You mentioned in the other post that you're getting errors... What kind of errors? Where are you getting them? In the customizer, the browser console, your PHP error log?
How are you adding the font to the control? Are you using a filter in your theme's functions.php file? If so can you post the code for your filter here?

**Comment by pkohara** [comment]
Here are some pictures, the crosses come up on 11 (where the code starts), 13, 15 and 37.
To be honest I don't understand the other questions. Wordpress has a tab to upload the files for the fonts and the code I have put in the additional CSS on the customizer, so I assume I'm not using a filter. Thank-you.

**Comment by pkohara** [comment]
Sorry I realised I forgot the photos.
<img width="904" alt="error1" src="https://user-images.githubusercontent.com/54961742/64488506-ae912b00-d240-11e9-971f-28ab7bdc02e9.PNG">
![error2](https://user-images.githubusercontent.com/54961742/64488508-afc25800-d240-11e9-83a9-b48d7e3c4e62.jpg)

**Comment by aristath** [comment]
It looks like you're trying to paste PHP code in the custom-CSS field?
If that is the case then it won't work, they are different languages.
That code should be added to the `functions.php` PHP file in your child theme, or using a plugin like https://wordpress.org/plugins/code-snippets/

Keep in mind though that you should not work with PHP unless you're certain of what you're doing. Editing PHP has the potential to crash your site.

You don't even need to do anything in Kirki, I don't know why your theme-authors sent you here, this is something that can be done completely using CSS.

The code you posted in your original post is correct.
You just need to make sure that the font-family is the same both when defining the font in `@font-face` and when using it in `.site-title, .site-description`.
You also need to make sure that the file exists, and it should not be formatted like this:
`public_html/your-site/wp-content/themes/your-theme/fonts/FontName-Regular.ttf`
It needs to be like this:
`https://yogimind.co.uk/wp-content/themes/your-theme/fonts/FontName-Regular.ttf` - assuming of course that your font is located on `wp-content/themes/your-theme/fonts/FontName-Regular.ttf`.
