### ISSUE TITLE
Font family name with quote getting escaped with Kirki fallback class

### ISSUE THREAD

**Issue by ariona** [themeum/kirki#2254]
The default font i use is `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif`, Since there is spaced font names, it getting a double quote.

But since the style is being escaped with `esc_textarea` now the quote is being escaped `&quot;Segoe UI&quot;` making the font-family value invalid.

How to solve this issue without removing the escape functionality, i know escaping some value is important.

https://github.com/aristath/kirki/blob/5045850cfdfd319c9354fec46c333a140509b098/docs/files/class-my-theme-kirki.php#L347

**Comment by aristath** [comment]
Try `esc_html` instead of `esc_textarea`. I have no idea why we have `esc_textarea` there...
