### ISSUE TITLE
Background field on LiteSpeed server

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2256]
### Issue description:
I have created some options using your customizer framework which is great. A day before I noticed that on LiteSpeed server your background field gives a 403 page https://prnt.sc/p5al40 in customizer. When I tried to change my code to default one from your documentation the result was the same :( What can you advice in this situation and how can it be fixed ? I would like to know why is it so...

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
WP org version 

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'my_kirki_options', [
			'type'        => 'background',
			'settings'    => 'background_settings',
			'label'       => esc_html__( 'Background Control', 'kirki' ),
			'description' => esc_html__( 'Background conrols are pretty complex - but extremely useful if properly used.', 'kirki' ),
			'section'     => 'styles',
			'default'     => [
				'background-color'      => 'rgba(20,20,20,.8)',
				'background-image'      => '',
				'background-repeat'     => 'repeat',
				'background-position'   => 'center center',
				'background-size'       => 'cover',
				'background-attachment' => 'scroll',
			],
			'transport'   => 'auto',
			'output'      => [
				[
					'element' => 'body',
				],
			],
		] );
```

**Comment by aristath** [comment]
I don't see how Litespeed would make any difference to the background control... Does the issue go away if you remove that specific field?

**Comment by Stas0238** [comment]
@aristath Yes it did really 
I have many options and I tried to disable step by step to find the reason of why the 403 page is showing. So that I did and found that when I remove the background control from the section all is working ok. I removed all options and include one by one to find why it is. I did it with one that had bg control and it showed me (like on screenshot). Then I removed the control and it is ok. So I did it with others and found that the error goes away only when I disable this specific control from each section I use. 

Can you give an assumption of how to fix it ?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
