### ISSUE TITLE
Updating Customizer Code Without Pig Loader / Page Reload

### ISSUE THREAD

**Issue by damienstewart** [themeum/kirki#2258]
### Issue description:
Hi Aristath, 
I'm trying to preview front-end css from a custom code field in the customizer without reloading the page / displaying pig loader icon the most efficient way possible. The current solution I have is setting the custom code field to transport => postMessage

```php
Kirki::add_field( 'example', array(
	'type'        => 'code',
	'settings'    => 'custom_css',
	'label'       => __( 'Custom CSS', 'example' ),
	'description' => __( 'Custom style for across the site', 'example' ),
	'section'     => 'general_section_custom_code',
	'default'     => $example_options['custom_css'],
	'priority'    => 2,
	'transport'   => 'postMessage',
	'choices'     => array(
		'language' => 'css',
		'theme'    => 'monokai',
		'height'   => '500',
	),
) );
```

Then in my customizer-preview.js file I append a <style> tag to the DOM and fill it with the new CSS when the field is updated. This is working for the most part, but feels hacky. Can you point me in the direction of a better solution?

### Version used: Stable tag: 3.0.34
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
theme_mods

**Comment by sahinozek** [comment]
+1 for that. 
Or at least a possibility to use a different loader image would have been awesome. 

Pig is not tolerated in some countries. And we do have to consider twice before using Kirki in premium themes due to the fact not to offend some customers. It's unfortunate but it's a fact, unfortunately.

**Comment by mapsteps** [comment]
Good news regarding the pigs. They're gone with v4 :)

Regarding the original issue, this should be fine. We do some similar custom implementation for postMessage things in our theme adding style tags :)
