### ISSUE TITLE
Some changes are visible only on customizer preview, not on site

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2259]
I have strange issue, I think it appear after last update. Some of changes are visible only in customizer preview. After update, changes aren't show up on site, even after clearing cache etc.

in Kirki settings:
```
Kirki::add_field('behold-basic', [
    'type' => 'toggle',
    'settings' => 'woo__thumbnail--show-new',
    'label' => esc_html__('Pokaż plakieki "nowość"', 'behold-basic'),
    'section' => 'woo__thumbnail',
    'default' => '1',
    'priority' => 10,
]);

Kirki::add_field('behold-basic', [
    'type' => 'slider',
    'settings' => 'woo__thumbnail--news-days',
    'label' => esc_html__('Ilość dni dla nowości', 'behold-basic'),
    'description' => esc_html__('Określ, przez ile dni od umieszczenia produktu ma być uznawany za nowy', 'behold-basic'),
    'section' => 'woo__thumbnail',
    'default' => 7,
    'choices' => [
        'min' => 1,
        'max' => 14,
        'step' => 1
    ]
]);
```

and in code
```
if ( true == get_theme_mod( 'woo__thumbnail--show-new', true ) ) {
  add_action( 'woocommerce_before_shop_loop_item_title', 'bbloomer_new_badge_shop_page', 3 );
  function bbloomer_new_badge_shop_page() {
    global $product;
    $newness_days = get_theme_mod( 'woo__thumbnail--news-days' );
    $newBadge = get_theme_mod( 'woo__thumbnail--news-badge-text');
    $created = strtotime( $product->get_date_created() );
    if ( ( time() - ( 60 * 60 * 24 * $newness_days ) ) < $created ) {
        echo '<span class="itsnew">' . esc_html__( '' . $newBadge . '', 'woocommerce' ) . '</span>';
    }
  }
}
```
In this cace the problem is 'woo__thumbnail--news-days' slider field. Default it has value '7', but I must change that value and possibly back to '7' to see any results on site. So the default value is not "visible" for site... how to prevent that?

**Comment by aristath** [comment]
From what I can see above there is no default value defined in your `get_theme_mod` calls.
When you don't define a default value for `get_theme_mod` if the value is unset in the customizer it returns `false`. 
So instead of this: `get_theme_mod( 'woo__thumbnail--news-days' )` you should be using `get_theme_mod( 'woo__thumbnail--news-days', 7 )`

Same thing goes for all the other `get_theme_mod` calls. You should always define the default value as the 2nd argument in the function. 👍

**Comment by BeholdPL** [comment]
Thank u v.much!
