### ISSUE TITLE
Custom colors + panel focus leads to a visual error

### ISSUE THREAD

**Issue by oagix** [themeum/kirki#226]
I've set a custom color scheme in the Customizer via the color_back and color_accent options and if I open the Customizer title and then close it, moving the mouse out of it will restore the background color to the default Wordpress one.

Demo: https://www.dropbox.com/s/yl6ukhnfgkiqj5t/customizer_error_hover.mov?dl=0

Update: All panels seem to have this issue when using a dark background color.
https://www.dropbox.com/s/534wch9qbynpjqi/customizer_error_hover_2.mov?dl=0

**Comment by aristath** [comment]
Hey there! Can you please try with the latest build?
I believe this was just fixed.
