### ISSUE TITLE
Problems with Typography

### ISSUE THREAD

**Issue by MasterLex18** [themeum/kirki#2260]
### Issue description: Dear valued specialits,
I'm using a theme witch needs kirki plug in.
setting up the new website everything was fine.
After some weeks it appears that set fonts are not shown on the website.
If I disable kirki, the nonts appear as set.
If I activate kirki it is same again. Wrong fonts on website...
Can you help me please???
website is www.handinhand-ev.org
we are a charity and we do not have funds available for proper support. :)
Thank you for your support
Alex

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by aristath** [comment]
Hello @MasterLex18,

I'm afraid the theme you're using is a premium theme we don't have access to.
Have you tried contacting the theme author and ask for their assistance?
From what I can tell you can get support on http://support.wedesignthemes.com/forum/non-profit/wings-charity-multipurpose-wordpress-theme/ using your license.

**Comment by MasterLex18** [comment]
Hi,
thank you.
Will try to get the support from the author.
Best regards
Alex



Am Do., 26. Sept. 2019 um 18:26 Uhr schrieb Aristeides Stathopoulos <
notifications@github.com>:
