### ISSUE TITLE
Sortable do not refresh to adjustment

### ISSUE THREAD

**Issue by paolosax** [themeum/kirki#2261]
### Issue description:
Hello, I'm testing this great customizer framework (great job btw); in particular, I'm working on the sortable ctrl, as I need exactly the "foreach/get-template" functionality available at https://kirki.org/docs/controls/sortable.

Now, after the first implementation, when I edit to add or remove options (both from the "default" and "choices" arrays accordingly), the sortable elements stack doesn't change. Looks like that it do not refresh the settings in the database (but maybe I've missed something).

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
Version: 3.0.45. Develop branch not tried yet

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
- the Config:

```php
Kirki::add_config( CUSTOMIZER_CONFIG, array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );
```
- Control (just like your docs):

```php
Kirki::add_field( CUSTOMIZER_CONFIG, [
	'type'        => 'sortable',
	'settings'    => 'my_sections_stack',
	'label'       => esc_html__( 'SECTIONS STACK', 'kirki' ),
	'description' => esc_html__( 'Desc...', 'kirki' ),
	'section'     => 'section_name',
	'default'     => [
		'option1',
		'option2',
		'option3',
		'option4',
		'option5',
		'option6',
	],
	'choices'     => [
		'option1' => esc_html__( 'Option 1', 'kirki' ),
		'option2' => esc_html__( 'Option 2', 'kirki' ),
		'option3' => esc_html__( 'Option 3', 'kirki' ),
		'option4' => esc_html__( 'Option 4', 'kirki' ),
		'option5' => esc_html__( 'Option 5', 'kirki' ),
		'option6' => esc_html__( 'Option 6', 'kirki' ),
	],
	'priority'    => 21,
] );
```
- The template:

```php
// Get the parts.
$template_parts = get_theme_mod('my_sections_stack', array(
	'option1',
	'option2',
	'option3',
	'option4',
	'option5',
	'option6',
));
// Loop parts, echo just for test.

foreach ($template_parts as $template_part) {
    echo $template_part ;
}
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
