### ISSUE TITLE
Background control and choice

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2262]
### Issue description:
Is there any solutions on the issue from the topic below during the time https://github.com/aristath/kirki/issues/1918#issue-329753202 ?

### Version used:
latest from wp.org

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Could you please elaborate? What is the issue?

**Comment by Stas0238** [comment]
@aristath How can I use only background-color property for other element and use the whole background control (image, color, size) for another ? For now it is working for each of elements as full background control but I need to make them work separately.

**Comment by aristath** [comment]
```php
'output' => [
	[
		'element' => 'body' // Includes everything
	],
	[
		'element'  => '#content',
		'property' => 'background-color',
		'choice'   => 'background-color',
	]
]
```
