### ISSUE TITLE
Css output filter

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2264]
### Issue description:
I want to change the css background for my header only on one page on others leave it as it is from main options

### Version used:
latest from wp.org 

### Using theme_mods or options?
theme_mods

How can I get this result ? I also want to get the answer asap please

**Comment by mapsteps** [comment]
```
/**
 * Filtering Kirki 4 output arguments.
 *
 * @param array $current_output The generated output.
 * @param mixed $value The value.
 * @param array $kirki_output The Kirki output set on field.
 * @param array $kirki_field The Kirki field.
 *
 * @return array
 */
function sample_filter_output_args( $current_output, $value, $kirki_output, $kirki_field ) {

  // modify the $current_output here

  return $current_output;

}

add_filter( 'kirki_output_item_args', 'sample_filter_output_args', 10, 4 );
```

This should do it in the upcoming version 4. Props @contactjavas for the code-snippet :)
