### ISSUE TITLE
'active_callback' option

### ISSUE THREAD

**Issue by SimoneM90** [themeum/kirki#227]
Can someone explain how to use the 'active_callback' option in a kirki field?

**Comment by aristath** [comment]
The `active_callback` argument can be used to determine when a field should be shown or hidden.
There are 2 ways to use it:

Option 1: Write your own custom function:

``` php
function my_custom_callback() {
    return ( is_singular( 'recipe' ) ) ? true : false;
}
```

The above function for example will return true when you're viewing a single post that has post=type = 'recipe'. and it will return false when for example you're seeing an archive or a page.
In this case, you can then call that function in your field like this:

``` php
$fields[] = array(
    'type'        => 'radio',
    'setting'     => 'radio_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'section'     => 'radio_section',
    'default'     => 'option-1',
    'priority'    => 10,
    'choices'     => array(
        'option-1' => __( 'Option 1', 'kirki' ),
        'option-2' => __( 'Option 2', 'kirki' ),
        'option-3' => __( 'Option 3', 'kirki' ),
        'option-4' => __( 'Option 4', 'kirki' ),
    ),
    'active_callback' => 'my_custom_callback',
);
```

This will cause your field to only be displayed when you're seeing a "recipe" in the customizer.

Option 2: If you want your field to be shown depending on the values of other fields in the customizer, then you can use the `required` argument. What we've done is wrote a [function](https://github.com/reduxframework/kirki/blob/b6efb8489d14c5dfdd90656ad50c876a33bd15e3/includes/helpers.php#L183-L248) that parses your arguments and builds a query based on those.
Example:

``` php
$fields[] = array(
    'type'        => 'radio',
    'setting'     => 'radio_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'section'     => 'radio_section',
    'default'     => 'option-1',
    'priority'    => 10,
    'choices'     => array(
        'option-1' => __( 'Option 1', 'kirki' ),
        'option-2' => __( 'Option 2', 'kirki' ),
        'option-3' => __( 'Option 3', 'kirki' ),
        'option-4' => __( 'Option 4', 'kirki' ),
    ),
    'required' => array(
        array(
            'setting'  => 'my_setting',
            'value'    => 'some-value',
            'operator' => '=='
        ),
        array(
            'setting'  => 'another_setting',
            'value'    => 'some-other-value',
            'operator' => '!='
        ),
    )
);
```

The above will make the field dependent on 2 other fields: `my_setting` and `another_setting` and it will make the field be displayed only when `my_setting` has a value of `some-value` and `another_setting` has a value not equal to `some-other-value`.

Please note that the above have not yet been included in the stable version available on w.org and you'd need the version from the github repo in order for them to work.

**Comment by aristath** [comment]
Please note that you can't use both the `active_callback` AND `required` at the same time.
If you use `active_callback` then it will override any `required` arguments you set.

**Comment by SimoneM90** [comment]
Then if I have a field like this:

```
$fields[] = array(
    'type'        => 'radio',
    'setting'     => 'radio_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'section'     => 'radio_section',
    'default'     => 'option-1',
    'priority'    => 10,
    'choices'     => array(
        'option-1' => __( 'Option 1', 'kirki' ),
        'option-2' => __( 'Option 2', 'kirki' ),
        'option-3' => __( 'Option 3', 'kirki' ),
        'option-4' => __( 'Option 4', 'kirki' ),
    ),
);
```

and I want to show:

```
$fields[] = array(
    'type'        => 'text',
    'setting'     => 'text_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'help'        => __( 'This is some extra help.', 'kirki' ),
    'section'     => 'text_section',
    'default'     => 'This is some default text',
    'priority'    => 10,
);
```

if `radio_demo == 'option-1'` the function is:

```
function my_custom_callback() {
   if  ( kirki_get_option( 'radio_demo' ) == 'options-1' )  {
return true;
} else {
return false;
}
```

and set `'active_callback' => 'my_custom_callback'` option in `text_demo` field, right?

If i set the `'active_callback'` option appears this message:
`:call_user_func() expects parameter 1 to be a valid callback, function active_callback not found or invalid function name in on line`

Thanks for the help.

**Comment by aristath** [comment]
You can simply do this:

``` php
$fields[] = array(
    'type'        => 'text',
    'settings'    => 'text_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'help'        => __( 'This is some extra help.', 'kirki' ),
    'section'     => 'text_section',
    'default'     => 'This is some default text',
    'priority'    => 10,
    'required'    => array(
        array(
            'setting'  => 'radio_demo',
            'value'    => 'option-1',
            'operator' => '==',
        ),
    ),
);
```

no need for callback, as I mentioned earlier we already have a custom function that automatically builds it from the `required` argument.

**Comment by towfiqi** [comment]
@aristath Sorry to post here like this... :( The required function doesnt work with `'options_type' => 'option',` and when i tried to use the active_callback instead, I get this:
`:call_user_func() expects parameter 1 to be a valid callback, function active_callback not found or invalid function name in on line`

**Comment by aristath** [comment]
Confirmed. I'm marking this one as a bug and I'll work on it tomorrow. :)

**Comment by aristath** [comment]
Try replacing this file: https://github.com/reduxframework/kirki/blob/6bb5e7558454bdb53e54503b44e30aed575f0c82/includes/helpers.php with this one: https://gist.github.com/aristath/cbdf0c9e16bfc94f6d95 and let me know if that works.

**Comment by towfiqi** [comment]
thanks for the quick response ari :) Replaced the the code with no joy :/

**Comment by aristath** [comment]
@towfiqi Can you please test if this works for you now?
If you can't get it to work, can you test if this implementation works for you https://github.com/reduxframework/kirki/wiki/required ?
We're adding a new API so if you're just starting now I'd advise you to use the new methods described there. Future versions will be using that instead of the filters.
If it does work with that implementation then I'll need to add some logic to back-port it to the previously used methods using the `kirki/fields` filter.

**Comment by towfiqi** [comment]
@aristath  thanks for the response :) I just downloaded the latest version of kirki from github and tested again. doesnt seem to work.

and if I follow the new method, how would my config file look? any example? With what do I replace the 'dummy_config' in this line:
`Kirki::add_config( 'dummy_config' );` 

Let me know

**Comment by aristath** [comment]
If you don't want to use the config then you can just skip it and add your fields like this:

``` php
Kirki::add_field( '', array() );
```

**Comment by randomideas** [comment]
Hello @aristath,

Same here. I got problem with the required argument. 

Here is my code.

$fields[] = array(
        'type'        => 'radio',
        'settings'    => 'htypes',
        'label'       => __( '', 'kirki' ),
        'description' => __( '', 'kirki' ),
        'section'     => 'header_types',
        'priority'    => 10,
        'choices'     => array(
            'widget' => __( 'Widgetized', 'kirki' ),
            'predef' => __( 'Predefined', 'kirki' ),
        ),
    );

```
$fields[] = array(
    'type'        => 'radio-image',
    'settings'    => 'headtype',
    'label'       => __( '', 'kirki' ),
    'description' => __( '', 'kirki' ),
    'section'     => 'header_types',
    'priority'    => 20,
    'default'    => 'htypes1',
    'choices'     => array(
        'htypes1' => __( 'First Option', 'kirki' ),
        'htypes2' => __( 'Second Option', 'kirki' ),
    ),
    'required'  => array(
        array(
            'setting'  => 'htypes',
            'value'    => 'predef',
            'operator' => '==',
        ),
    )
);
```

When you have sometime, please do let me know whats wrong. Why it isn't working and whats the work around?

Thanks much!

**Comment by aristath** [comment]
@towfiqi did you get this one to work?

@randomideas I see you've already created a new ticket for your issue, I have already replied on https://github.com/reduxframework/kirki/issues/237#issuecomment-111719366

**Comment by aristath** [comment]
@towfiqi any news on this one?

**Comment by randomideas** [comment]
Thank you @aristath appreciate your help! You da man!

**Comment by aristath** [comment]
This has been fixed.

**Comment by ghost** [comment]
Adding myself to this issue so I may follow it in the morning and give it another go.  Thanks for the description of the required. 

Active callback looks interesting.
