### ISSUE TITLE
Ajax controls values

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2270]
I would like to know if  I can reload full panel via ajax when I change one option ? This is not your side but it is my customization but what I need is when I click on one button in customizer I have to reload some sections with ajax to set to some options inside those sections other values. Can it be possible ? Also if so i can refresh full customizer left bar section but without reloading page ?

**Comment by aristath** [comment]
I don't think it's possible to reload the left panel of the customizer... 
However you shouldn't have to.
You don't need AJAX to change values in controls from a button or load sections etc, the JS API in WordPress-Core already supports these things.

**Comment by Stas0238** [comment]
Thanks for that but maybe I was not so correct in my question

What I need is kind of presets for pages. The thing is that for all pages i need origin options and their values are ok but if i click on button (it is my custom button in customizer) to configurate other options for this page (i would like for blog only at this time) then my one of customizer panels should reset values for settings inside and I will be able to set it again but I will save it only for page I need which is blog page (saving of it is on my side so don't care about that :)). Now all what I need it how can I set other values for controls in one of sections (or in one panel).

Maybe you know how to retrigger one section or all options one by one or any help in this direction would be good. I found kirkiSetSettingValue variable so maybe it is a first step I can push from ?

Any help will be good :) Thanks

**Comment by aristath** [comment]
most controls get automatically updated when you do something like this:
```js
wp.customize( 'my_setting' ).set( 'my-value' );
```
or 
```js
wp.customize.control( 'my_setting' ).setting.set( 'my-value' );
```

That's basically what the `kirkiSetSettingValue` function does, nothing more.

**Comment by Stas0238** [comment]
But it won't change visual in customizer (the new value it working if iframe but it is not changed good in customizer) :( Only after full refresh

**Comment by aristath** [comment]
which control doesn't change?

**Comment by Stas0238** [comment]
sortable for example and repeater

So do you know any method to ajax reupload one section or panel ?

**Comment by aristath** [comment]
I'm afraid not.
These 2 controls are the few exceptions.
I think it should be possible to destroy the controls and re-render them, but I haven't tried it.

**Comment by Stas0238** [comment]
Can you send me one example of correct destroying and re-rendering ? If you don't have it maybe you know an article for this question ?

**Comment by ulziibat-n** [comment]
Hello @aristath . I have same problem like this. 

if user add correct token, i want to display typekit projets to next select control without refresh. Is it possible with kirki and wp customizer api?

```
Dimative_Kirki::add_field(
    'dimative_customizer',
    array(
        'type'            => 'text',
        'settings'        => 'dimative-typekit-token',
        'label'           => esc_html__( 'Typekit token', 'dt-onli' ),
        /* translators: %1$s: typekit api link */
        'description'     => sprintf( esc_html__( 'To get your API key, go to link ', 'dt-onli' ) . '<a href="%1$s" target="_blank">%1$s</a>', esc_url( 'https://fonts.adobe.com/account/tokens' ) ),
        'section'         => 'dimative-miscellaneous-section',
        'default'         => '',
        'active_callback' => array(
            array(
                'setting'  => 'dimative-typekit',
                'operator' => '==',
                'value'    => true,
            ),
        ),
    )
);

Dimative_Kirki::add_field(
    'dimative_customizer',
    array(
        'type'            => 'select',
        'settings'        => 'dimative-typekit-project',
        'label'           => esc_html__( 'Projects', 'dt-onli' ),
        'description'     => esc_html__( 'Please select your project', 'dt-onli' ),
        'section'         => 'dimative-miscellaneous-section',
        'multiple'        => 1,
        'choices'         => dimative_get_typekit_projects(),
        'default'         => '',
        'active_callback' => array(
            array(
                'setting'  => 'dimative-typekit',
                'operator' => '==',
                'value'    => true,
            ),
            array(
                'setting'  => 'dimative-typekit-token',
                'operator' => '!=',
                'value'    => '',
            ),
        ),
    )
);
```

thanks

**Comment by anteksiler** [comment]
I am also interested in this as I need to update the MailChimp lists when user adds the MC API key.

**Comment by ulziibat-n** [comment]
@anteksiler Maybe we can solve like this. https://wordpress.stackexchange.com/questions/99652/one-button-to-change-all-settings-in-theme-customizer Please try this example. If you got some success, please tell me.
