### ISSUE TITLE
Problems with Image field breaking everything else in Sections

### ISSUE THREAD

**Issue by bahia0019** [themeum/kirki#2271]
### Issue description:
I have a Section within a Panel, and I have an Option for Logo that is saved to Options (as to be available if the theme changes.
I also have a Theme_Mod for the width of the logo in the same section.
Except for the Panel, I have a similar setup on a different theme which is working.

However in this case, when I click through the Panel and the Image field, and nothing else shows. It also freezes the Customizer and doesn't allow me to go back to the previous Panel. 

Happy to provide additional information.

### Version used:
Version 3.0.45

### Using theme_mods or options?
Combination.

### Code to reproduce the issue (config + field(s))

```
keramas_Kirki::add_panel( 'site_identity', array(
	'title' => esc_html__( 'Site Identity', 'kirki' ),
	'icon'  => 'dashicons-tide',
) );

/********************************
 * Add the Menu Options section
******************************* */

keramas_Kirki::add_section( 'identity_logo', [
	'title'      => esc_attr__( 'Logo', 'keramas' ),
	'capability' => 'edit_theme_options',
	'panel'      => 'site_identity',
	'icon'       => 'dashicons-tide',
]);

	keramas_Kirki::add_field( 'keramas', [
		'type'        => 'image',
		'settings'    => 'fsc_logo',
		'option_type' => 'option',
		'option_name' => 'fsc_options',
		'label'       => __( 'Logo', 'keramas' ),
		'description' => __( 'Add or edit your logo here', 'keramas' ),
		'section'     => 'identity_logo',
		'default'     => '',
		'choices'     => [
			'save_as' => 'id',
		],
	]);
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
