### ISSUE TITLE
How to save default option of settings?

### ISSUE THREAD

**Issue by steve231293** [themeum/kirki#2272]
### Issue description:
Hello aristath. 
Could you know any ways to save default options when hit Save button?
Some fields type saved default options, some fields not. I don't know why.

Be default Kirki will not save default value until we change it. It make a problem with WPML plugin not found it in String Translation admin-texts.

When hit save without any change.
[http://prntscr.com/piys7i](http://prntscr.com/piys7i)

When & change to any other value & hit save
[http://prntscr.com/piytr5](http://prntscr.com/piytr5)

### Using theme_mods or options?
theme_mods

```
Kirki::add_field( 'theme', array(
	'type'     => 'textarea',
	'settings' => 'blog_archive_header_title',
	'label'    => esc_html__( 'Blog Title', 'text-domain' ),
	'section'  => 'blog_archive',
	'priority' => 10,
	'default'  => esc_html__( 'Journal.', 'text-domain' ),
) );
```

**Comment by aristath** [comment]
> Be default Kirki will not save default value until we change it. It make a problem with WPML plugin not found it in String Translation admin-texts.

That's not Kirki, that's the WordPress customizer.
Default settings should never be saved.

If WPML has an issue with that, then I can think of 2 scenarios: 
1. You're not using the 2nd argument in your `get_theme_mod` calls (that's where the default value should go)
2. WPML has a bug.

You should never save the defaults.

How is support for these strings added to WPML?

**Comment by steve231293** [comment]
Thanks for your reply.

So do you know why some fields saved default value when i hit save button?
Look like fields with type "Color" or "Multi Color" or "Background" [http://prntscr.com/pjc3r2](http://prntscr.com/pjc3r2).
I don't changed any things. (Even i deleted that option in Database & hit save again.)

**Comment by aristath** [comment]
That's because there's a bug in the colorpicker script which triggers a change on load.
multi-color and background have the same issue because they use the same colorpickers.
