### ISSUE TITLE
Default value of fields

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2273]
How can I get all settings with default values before I made any changes with those settings ? 
I am looking for smth like Kirki::$fields ( with default value ) but this doesn't work as expected 

The problem is when I didn't change the setting then value cannot be written inside export file so that I need to get all Kirki fields and their value and to write in file by my own. For now I am using [Customizer Export/Import](https://uk.wordpress.org/plugins/customizer-export-import/) but the result is not as I need.

**Comment by aristath** [comment]
Why would you need to export unsaved values?
If you export only saved values, then on import only those values will get written to the theme-mods, and all unsaved values will fallback to defaults - as they should.
