### ISSUE TITLE
Cannot read property '_value' of null in field-dependencies.js@127

### ISSUE THREAD

**Issue by hogash** [themeum/kirki#2277]
### Issue description:
Hi Ari. I got this error when trying to attach a custom option to one of WooCommerce's Thumbnail Cropping image option. 

### Code to reproduce the issue (config + field(s))

WooCommerce active. Access Customizer > WooCommerce > Product images.

```
CustomKirki::add_field( 'custom_kirki', [
	'type'        => 'toggle',
	'settings'    => 'custom_image_height',
	'label'       => esc_html__( 'Enable Custom Image Height', '@@textdomain' ),
	'section'     => 'woocommerce_product_images',
	'default'     => false,
	'priority'    => 120,
	'active_callback' => [
		[
			'setting'  => 'woocommerce_thumbnail_cropping',
			'operator' => '==',
			'value'    => 'uncropped',
		],
	],
] );
```

**Comment by aristath** [comment]
Hmmmm it looks like that control in WooCommerce doesn't have a setting.
If you go to the customizer and paste this in the console, you'll see there's no setting defined in the control:
```js
wp.customize.control( 'woocommerce_thumbnail_cropping' );
```

Try replacing this line:
https://github.com/aristath/kirki/blob/5b04091fb6f389be65902bf5a2e41379137805b6/modules/field-dependencies/field-dependencies.js#L127
with this:
```js
wp.customize( requirement.setting ).get();
```

**Comment by hogash** [comment]
@aristath Thanks for looking into it! Yes, saw the `.setting` was null and thought of trying with `.settings` and other combinations but nothing worked. 

The solution you provided fixes the issue and doesn't seem to affect other controls.

Is this tweak going to the next update?

**Comment by hogash** [comment]
@aristath Hmm actually it does affect the CSS output. For example given this control:

```
CustomKirki::add_field( 'custom_kirki', [
	'type'        => 'number',
	'settings'    => 'custom_image_height_size',
	'label'       => esc_html__( 'Image Container Height (px)', '@@textdomain' ),
	'section'     => 'woocommerce_product_images',
	'default'     => '',
	'priority'    => 130,
	'choices'     => [
		'min'  => 50,
		'max'  => 1000,
		'step' => 1,
	],
	'active_callback' => [
		[
			'setting'  => 'woocommerce_thumbnail_cropping',
			'operator' => '==',
			'value'    => 'uncropped',
		],
	],
	'output'  => [
		[
			'element'  	=> ':root',
			'property' 	=> '--custom-image-height',
			'units'    		=> 'px',
		],
	],
] );
```
if i add `active_callback` the CSS isn't outputted.

**Comment by aristath** [comment]
Can you please test this using the `develop` branch from this repository?
The next version is a complete rewrite of many things and I pushed a fix there.

> if i add `active_callback` the CSS isn't outputted.

Is it never outputted, or only generates the CSS when the `active_callback` evaluates to true?

**Comment by ulziibat-n** [comment]
@hogash  you can use filter. Yesterday i got same problem with your issue. Today i found this solution.
```
if ( ! function_exists( 'theme_name_add_filter_kirki_stylesheet' ) ) {
	/**
	 * Add Custom CSS to Kirki Inline CSS file.
	 *
	 * @param string $styles Kirki Compiled CSS file.
	 * @return string Combined CSS file.
	 */
	function theme_name_add_filter_kirki_stylesheet( $styles ) {
		$theme_name_custom_css = '';

		if ( 'uncropped' ===get_theme_mod( 'woocommerce_thumbnail_cropping' ) ) {
			$theme_name_custom_css = $theme_name_custom_css . ':root { --' . esc_attr( get_theme_mod( 'custom_image_height_size' ) ) . 'px; }';
		}

		return $styles . '' . $theme_name_custom_css;
	}
	add_filter( 'kirki_your_theme_config_id_dynamic_css', 'theme_name_add_filter_kirki_stylesheet' );
}
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
