### ISSUE TITLE
Google Fonts - Sans Serif not pulling back sans-serif font stack

### ISSUE THREAD

**Issue by craigpearson** [themeum/kirki#228]
When using Google Fonts and selecting Sans Serif in addition to supplying the output arguments (exactly as documented and using [this exact example](http://kirki.org/#google-fonts-integration)) only the following is output

`font-family: sans-serif`;

As opposed to the expected sans-serif font stack which is configured in `includes/class-kirki-fonts-font-registry.php` on `191`

**Comment by aristath** [comment]
Hey there!

Can you please test if this works now? I believe I just fixed it on https://github.com/reduxframework/kirki/commit/d0c37fabb6802ed3942eed9171bc42f963209db2

**Comment by craigpearson** [comment]
Sorry for the delay on this, thanks for looking into it. When outputting the styles inline in the header this fix has now broken the font stack completely as it's spitting out "Array", this is both for the font stack and the font weight

I might be able to have a look into this tonight and contribute unless you're aware off the top of your head why the array isn't being processed as imagined

**Comment by aristath** [comment]
Hey there!

Did you manage to find what was causing this?
If not then can you please provide a complete sample of your code so that I may try to replicate it?

**Comment by aristath** [comment]
@CraigPearson any news on this one? I can't replicate it so I'll need a sample of the code you're using...

**Comment by aristath** [comment]
@CraigPearson I just tested this with the development version and it seems like this has been fixed. 

I'll just go ahead and close this ticket but if you find it still persists using the dev version please feel free to reopen it!
