### ISSUE TITLE
Dimensions control not working

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2280]
I'm trying to create dimension control with this one:

```
Kirki::add_field( 'behold-basic', [
	'type'        => 'dimensions',
	'settings'    => 'container_padding',
	'label'       => esc_html__( 'Paddings', 'behold-basic' ),
	'section'     => 'header__logo',
	'default'     => array(
		'padding-top'    => '96px',
		'padding-bottom' => '96px',
		'padding-left'   => '96px',
		'padding-right'  => '96px',
	),
	'choices'     => [
		'labels' => [
			'padding-top'  => esc_html__( 'Min Width', 'behold-basic' ),
			'padding-bottom'  => esc_html__( 'Max Width', 'behold-basic' ),
			'padding-left' => esc_html__( 'Min Height', 'behold-basic' ),
			'padding-right' => esc_html__( 'Max Height', 'behold-basic' ),
		],
	],
    'transport' => 'auto',
	'output'      => array(
		array(
	      'choice'      => 'padding-top',
	      'element'     => '.logo',
	      'property'    => 'padding-top',
	    ),
	    array(
	      'choice'      => 'padding-bottom',
	      'element'     => '.logo',
	      'property'    => 'padding-bottom',
	    ),
	    array(
	      'choice'      => 'padding-left',
	      'element'     => '.logo',
	      'property'    => 'padding-left',
	    ),
	    array(
	      'choice'      => 'padding-right',
		  'element'     => '.logo',
	      'property'    => 'padding-right',
	    ),
	),
]);
```

I have two problems:
1. I do not see any default values in my control panel
2. When I type in any values, nothing happen, nothing is working, no CSS is added to element '.logo' class.

Where is my fault?

**Comment by aristath** [comment]
@BeholdPL Are you using the stable version downloaded from wordpress.org? Or are did you download the version from this repository?

**Comment by BeholdPL** [comment]
It's from repository.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
