### ISSUE TITLE
Toggle attr with partial refresh

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2281]
### Issue description:
How can I change my links target with partial refresh. Code which I tried below (I know how to do it with iframe refreshing but I am trying to avoid that refresh)

### Version used:
wp org version

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
		Kirki::add_field( 'my_kirki_options', array(
			'type'        => 'toggle',
			'settings'    => 'socials_target',
			'label'       => esc_html__( 'Open in new window', 'domain' ),
			'section'     => 'header_socials',
			'default'     => 0,
			'transport' => 'postMessage',
			'partial_refresh' => array(
				'socials_target' => array(
					'selector'        => '.header-socials a',
					'attr' => 'target',
					'render_callback' => function() {
						$type = get_theme_mod('socials_target');
						return $type == 1 ? '_blank' : '';
					},
				),
			),
		) );

**Comment by aristath** [comment]
The render callback should return the HTML for the element to be replaced.
So returning the attribute in this case won't work, the callback rerenders the entire element.
So it would have to be something like 
```php
'partial_refresh' => [
    'socials_target' => [
        'selector'            => '.header-socials a',
        'attr'                => 'target',
        'container_inclusive' => true, // Include the container.
		'render_callback'     => function() {
            $type == get_theme_mod( 'socials_target' ) ? '_blank' : '';
            return '<a href="whatever" target="' . $type . '">Something</a>';
        },
    ],
],
```

**Comment by Stas0238** [comment]
@aristath Thanks, but you have to know that I have more than one social link :) And for that reason there is not way to update only one attr for each social links 

For ex. 
for facebook I have to return `'<a href="facebook_link" target="' . $type . '">FB social</a>'`
but for youtube that one is not correct and I should have `'<a href="youtube_link" target="' . $type . '">Youtube social</a>'`

That's why I wrote about the issue I faced with and your solution won't help in that way. Hope you got what I meant

**Comment by aristath** [comment]
Actually you don't even need to update the preview at all for the `target=""` property... You can just set it to `'transport' => 'postMessage'`.
In the preview frame in the customizer external links are disabled no matter what their properties are, so you just need to apply your changes on the frontend and you can safely ignore updating the customizer preview.
