### ISSUE TITLE
Toggle attr with partial refresh

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2282]
Is your feature request related to a problem? Please describe.
In your collection of utilities for js_vars you have css, html, style and toggleClass functions. I have thought about toggleAttr function because in some cases it is needed (ex. below)

Describe the solution you'd like
The same work as you have for toggleClass() but for attr

Describe alternatives you've considered
No alternatives at this time

Additional context
'transport' => 'postMessage',
'js_vars' => array(
array(
'element' => '.header-sticky',
'function' => 'toggleAttr',
'attr' => 'sticky-type',
'attr_value' => 'sticky',
'value' => 'sticky'
),
array(
'element' => '.header-sticky',
'function' => 'toggleAttr',
'attr' => 'sticky-type',
'attr_value' => 'smart',
'value' => 'smart'
),
),

**Comment by aristath** [comment]
You could try something like this:

```php
'type'      => 'radio-buttonset',
'choices'   => [
    ''        => esc_html__( 'Disabled', 'textdomain' ),
    'default' => esc_attr__( 'Default', 'textdomain' ),
    'smart'   => esc_html__( 'Smart', 'textdomain' ),
],
'transport' => 'postMessage', // or 'auto'.
'output'    => [
    [
        'element'  => '.my-element',
        'function' => 'html',
        'attr'     => 'sticky-type',
    ]
]
```
