### ISSUE TITLE
Domain mapping not updated after /?action=kirki-reset-cache

### ISSUE THREAD

**Issue by wilrevehl** [themeum/kirki#2283]
### Issue description:
Hi, Ari! I hope all is well. We have an issue where the option kirki_font_local_filenames is not updated after running ?action=kirki-reset-cache. The problem is we stage with one URL and then when ready, the domain mapping is changed for production. We need the reset cache to clear this object so the URL will match afterward. 

I was able to simply remove the row and your app replaced it with the right info. This means your domain mapping works fine. Thank you for all you do for the WordPress community!

### Version used:
3.0.45

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
?action=kirki-reset-cache

**Comment by aristath** [comment]
Hmmm try deleting the font-files from wp-content (using FTP/SSH/whatever other method is available & convenient).
That should reset any cache that has remained there.

This has been fixed in the develop branch months ago but tbh I don't recall which commit it was that fixed it, there have been literally thousands in the new refactor

**Comment by wilrevehl** [comment]
I know you made updates in the same function set last version, but it
didn't impact this. I'll give that a try next time. Thanks!

**Comment by ktsour** [comment]
Please note that I had the same problem and had to manually delete the entry 'kirki_font_local_filenames' from options in order to make it write again with the correct domain.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
