### ISSUE TITLE
Weird font issue

### ISSUE THREAD

**Issue by egemenerd** [themeum/kirki#2285]
Hi, after the latest Kirki update (3.0.45), I'm having a weird issue with some Google fonts (Maven Pro, Muli, Comfortaa etc.). First, I tought that the problem might related to my theme or one of my 3rd party plugins and I tested it on a fresh WordPress install with a default WordPress theme (Twenty Twenty). Please see the screenshots. The big A looks weird. There isn't any problem when customizer is open. The problem is at the front-end. I tested it on Firefox, Safari and Chrome. The result is the same. Any ideas why this happens?

![font1](https://user-images.githubusercontent.com/7691382/70867097-76f1f780-1f82-11ea-98f0-198ee1bfae56.png)

![font2](https://user-images.githubusercontent.com/7691382/70867098-7e190580-1f82-11ea-8c72-6514061cc399.png)

This is my code;

<pre>$kirki_prefix = "test_";

Kirki::add_config( $kirki_prefix . 'theme_config_id', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod'
));

Kirki::add_panel( $kirki_prefix . 'theme_settings', array(
    'priority'    => 10,
    'title'       => esc_html__( 'Theme Settings', 'test' )
));

Kirki::add_section( $kirki_prefix . 'general', array(
    'title'     => esc_html__( 'General', 'test' ),
    'panel'     => $kirki_prefix . 'theme_settings',
    'priority'  => 1
));

Kirki::add_field( $kirki_prefix . 'theme_config_id', [
	'type'        => 'typography',
	'settings'    => $kirki_prefix . 'my_setting',
	'label'       => esc_html__( 'Control Label', 'kirki' ),
	'section'     => $kirki_prefix . 'general',
	'default'     => [
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left',
	],
	'priority'    => 10,
	'transport'   => 'auto',
	'output'      => [
		[
			'element' => 'h1.entry-title',
		],
	],
] );</pre>

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
