### ISSUE TITLE
ERR_ABORTED 404

### ISSUE THREAD

**Issue by iamarif** [themeum/kirki#2286]
### Issue description:
I'm the owner of this theme: https://themeforest.net/item/lifeband-life-coach-wordpress-theme/20905146 and using Kirki plugin for customizer.. One of the my customer reached me and said that not showing image uplod control.. You can see the screenshot and errors below.. Did you get any feedbacks just kind of this..

### Version used:
Last version 

### Using theme_mods or options?
theme_mods

![Screenshot_10](https://user-images.githubusercontent.com/11271748/71161890-400a3300-225b-11ea-8aa2-5ffaa55c2c0d.jpg)

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
