### ISSUE TITLE
Repeater Image Field disappears when i go back into customizer

### ISSUE THREAD

**Issue by drewlonious** [themeum/kirki#2289]
### Issue description:
Using repeater for a slideshow. Everythings works perfectly, besides that whenever I go back into customizer, I have to reselect the images for each slide, which only then will the images re-appear. Unsure if a duplicate issue
![Screen Shot 2020-01-08 at 11 25 11 AM](https://user-images.githubusercontent.com/47552877/72008864-94288780-3209-11ea-87fe-f5f1ab27758e.png)

**Comment by drewlonious** [comment]
update: text fields, dropdown page, do save. - refreshing the browser when on customizer, or saving and coming back into customizer will erase the image url data

update2: works on regular image controls, problem only existing within repeater filelds

update 3: image seems to be saved, but within the HTML, 
![Screen Shot 2020-01-09 at 1 58 38 PM](https://user-images.githubusercontent.com/47552877/72108316-2737ef00-32e8-11ea-8d27-0d7854e767c6.png)

And I have to reselect the image for it to work again.

Anyone else having this issue?

**Comment by aristath** [comment]
Please post the code you're using to create that repeater.

**Comment by drewlonious** [comment]
creating the repeater fields, appreciate your help! @aristath 

`<?php

// Adding the Slider for Homepage section
Kirki::add_section( 'hp_main_slider_repeater_section', array(
  'title'          => __( 'Homepage - Slider', 'kirki' ),
  'description'    => __( 'This slider will be shown on the front page of your website', 'kirki' ),
  // 'panel'         => 'hp_main_slider_repeater',
  'priority'       => 10,
  'capability'     => 'edit_theme_options',
  // 'theme_supports' => '', // Rarely needed.
) );

    // Adding Repeating Sliders
    Kirki::add_field( 'gbd_starter', array(
      'type'        => 'repeater',
      'label'       => __( 'Add Slides', 'kirki' ),
      'section'     => 'hp_main_slider_repeater_section',
      'priority'    => 10,
      'row_label' => [
        'type'  => 'text',
        'value' => esc_html__( 'Your Slide', 'kirki' ),
        'field' => 'slide_image',
      ],
      'button_label' => esc_html__('"Add new" button label (optional) ', 'kirki' ),
      'settings'     => 'hp_main_slider_repeater_settings',
    	'default'      => [
        [
          'slide_image' => 'Add Image',
          'slide_heading'  => 'Add Heading',
          'slide_subheading'  => 'Add Sub-Heading',
          'slide_cta'  => 'Add CTA',
          'slide_link'  => 'Select Link',
        ],
      ],
        'fields' => [
          'slide_image' => [
            'type'        => 'image',
            'settings'    => 'image_setting_id',
            'label'       => esc_html__( 'Image Control (ID)', 'kirki' ),
            'description' => esc_html__( 'Description Here.', 'kirki' ),
            'default'     => '',
            'choices'     => [
              'save_as' => 'id',
            ],
          ],
          'slide_heading' => [
            'type'        => 'text',
            'label'       => esc_html__( 'Slide Heading', 'kirki' ),
            'description' => esc_html__( 'Slide Heading', 'kirki' ),
            'default'     => '',
          ],
          'slide_subheading' => [
            'type'        => 'textarea',
            'label'       => esc_html__( 'Slide Sub-Heading', 'kirki' ),
            'description' => esc_html__( 'Slide Sub-Heading', 'kirki' ),
            'default'     => '',
          ],
          'slide_cta' => [
            'type'        => 'text',
            'label'       => esc_html__( 'Slide CTA', 'kirki' ),
            'description' => esc_html__( 'Slide CTA', 'kirki' ),
            'default'     => '',
          ],
          'slide_link' => [
            'type'        => 'dropdown-pages',
            'label'       => esc_html__( 'Slide Link', 'kirki' ),
            'description' => esc_html__( 'Slide Link', 'kirki' ),
            'default'     => '',
          ],
        ]
      
    ) );

`

`<?php
$defaults = [
  [
    'slide_image' => esc_html__( 'slide_image', '' ),
    'slide_heading'  => esc_html__( 'Add Heading', 'kirki' ),
    'slide_subheading'  => 'Add Sub-Heading',
    'slide_cta'  => 'Add CTA',
    'slide_link'  => esc_html__( 'Add Link', 'kirki' ),
  ],
];

// Theme_mod settings to check.
$settings = get_theme_mod( 'hp_main_slider_repeater_settings', $defaults );
?>


<section id="section__main-slider">

   
  <div class="swiper-container hp-main-slider">

    <div class="slider-divider">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="96px"
        viewBox="0 0 100 100" version="1.1" preserveAspectRatio="none" class="injected-svg slider-divider-svg"
        data-src="assets/img/dividers/divider-1.svg">
        <path d="M0,0 C40,33 66,52 75,52 C83,52 92,33 100,0 L100,100 L0,100 L0,0 Z"></path>
      </svg>
    </div>
    
    <div class="swiper-wrapper">

    <?php foreach( $settings as $setting ) : ?>

      <div class="swiper-slide d-flex align-items-center" style="background:url('<?php echo wp_get_attachment_url($setting['slide_image']); ?>') 50% 50%;">
        <div class="container"> 
          <div class="hp-slider-inner">
            <h1><?php echo $setting['slide_heading']; ?></h1>
            <span class="mainSlider_text"><?php echo $setting['slide_subheading']; ?></span>

            <div class="cta-wrap"><a class="main-cta" href="<?php echo esc_url( get_permalink($setting['slide_link']) ); ?>"><?php echo $setting['slide_cta']; ?></a></div>      

          </div>
        </div>
      </div>
    <?php endforeach; ?>

    </div>
    
    <div class="swiper-button swiper-button-next"></div>
    <div class="swiper-button swiper-button-prev"></div>
    
    <div class="swiper-pagination"></div>
  </div>

</section>
`

**Comment by aristath** [comment]
Don't save the image as ID and it will work.
Image fields (and any field for that matter) is not the same when used inside a repeater as it is when used outside a repeater.

**Comment by drewlonious** [comment]
@aristath Hey i tried saving as url and array but it's still not saving, any idea?


`Kirki::add_field( 'theme_config_id', [
	'type'        => 'image',
	'settings'    => 'image_setting_url',
	'label'       => esc_html__( 'Image Control (URL)', 'kirki' ),
	'description' => esc_html__( 'Description Here.', 'kirki' ),
	'section'     => 'section_id',
	'default'     => '',
] );`
