### ISSUE TITLE
The latest version of kirki 0.8.4 - issue with image select

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#229]
Hi there,

There is a small issue with the image select field in that it outputs list style radio with the images.
Image attached.

![screenshot 2015-05-22 20 50 29](https://cloud.githubusercontent.com/assets/1312880/7769596/40d9ee82-00c4-11e5-9023-d7bed6e093d2.png)

**Comment by towfiqi** [comment]
Cant reproduce this with version 0.8.4
Are you sure all the stylesheets & js files are loaded?

**Comment by aristath** [comment]
@cmwwebfx hey there!
Is Kirki installed as a plugin, or embedded in a theme?
Can you post your kirki configuration here?

**Comment by ghost** [comment]
Hi Aris
Sorry for the delayed response. I have Kirki embedded in the theme.I will post the radio config in a couple of minutes.

**Comment by ghost** [comment]
This is what I have for the image select

``` php
// General Options - Layout Type
    $controls[] = array(
        'type'        => 'radio-image',
        'setting'     => 'layout_type_boxed_fluid',
        'label'       => __( 'Select Layout', 'isiqalo' ),
        'description' => __( '', 'isiqalo' ),
        'help'        => __( '', 'isiqalo' ),
        'section'     => 'layout_type',
        'default'     => 'option-1',
        'priority'    => 10,
        'choices'     => array(
            'option-1' => get_stylesheet_directory_uri() . '/images/layout_boxed.png',
            'option-2' => get_stylesheet_directory_uri() . '/images/layout_fluid.png',
        ),
    );
```

**Comment by aristath** [comment]
@cmwwebfx Can you please try pulling the latest changes from github and let me know if you're still having this issue?

**Comment by ghost** [comment]
Yes. Will do this tonight. Thanks for reply

**Comment by aristath** [comment]
@cmwwebfx any news on this one?

**Comment by aristath** [comment]
This one seems to have been resolved so I'll go ahead and close it.
@cmwwebfx if you're still having issues then please reopen this and add some more details using the latest build. :+1:

**Comment by ghost** [comment]
Hi Aris,

Appologies mate. Have been so busy getting a site out the door and just came to look at my emails. Yes I have just checked this and it is fixed. Thank you for the follow up.
