### ISSUE TITLE
Some fonts don't work due to broken CSS

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2290]
### Issue description:
The same issue was before and now I am having an Exo 2 font for my client's website but it does not work as should. I found the same tasks years ago https://github.com/aristath/kirki/issues/600 and it really looks like it was not fixed. Maybe you made changes in branch that was not merged then ? I found that this problem exists only with fonts that have number in their names, strange thing btw. 

Here you have some fonts for test:
1) Goudy Bookletter 1911
2) Libre Barcode 39
3) Exo 2

### Version used:
WP latest

### Using theme_mods or options?
Theme_mods

### Code to reproduce the issue (config + field(s))
Select any of these fonts from your options and you will see the problem - http://prntscr.com/qlbzmp

**Comment by aristath** [comment]
In your browser dev tools if you change `Exo 2` to `"Exo 2", (adding the quotes) does it work? If it does then the font gets properly loaded but it needs quotes.
Let me know if that fixes your issue. If it does, then we'll need to wrap fonts in quotes before echoing them.

**Comment by Stas0238** [comment]
@aristath yes, it works when I add quotes.

**Comment by jamesros161** [comment]
@aristath Is there any update on this? I am having this problem as well.

**Comment by tcgunel** [comment]
Hi,

I think the problem still persist so you can use this filter to temporarily fix it, remember to edit YOURCONFIGIDHERE

```
function fix_kirki_font_family($styles_string) {
	$styles_string = preg_replace('/font-family:([^;]+)/i', 'font-family:"$1"', $styles_string);

	return $styles_string;
}
add_filter( 'kirki_YOURCONFIGIDHERE_dynamic_css', 'fix_kirki_font_family', 9999, 1 );
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
