### ISSUE TITLE
How to change defaults colors under picker?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2294]
I've created some based colors for my theme. Now, I would like to set them as default choices in every color picker:

<img width="299" alt="color-hex" src="https://user-images.githubusercontent.com/34622592/72301954-c0f4f880-3668-11ea-97e0-cf7d179a2449.png">

I was trying with multiple choices etc. but nothing works. So how can I replace those defaults colors under picker, that I select in the pic above?

**Comment by aristath** [comment]
In v3.x you can use the `palette` argument. Something like this _should_ work:

```php
'choices' => [
  'palette' => [ '#000000', '#cc0000', '#ffffff' ],
],
```

**Comment by BeholdPL** [comment]
Ok. So I've tried this:

```
Kirki::add_field($textdomain, [
    'type' => 'color',
    'settings' => 'basic_colors_front_color',
    'label' => esc_html__('Kolor frontalny', $textdomain),
    'description' => esc_html__('Np. kolor tekstu', $textdomain),
    'section' => 'basic_colors',
    'default' => '#000000',
    'choices' => [
          'palette' => [ '#000000', '#cc0000', '#ffffff' ],
    ],
    'transport' => 'auto'
]);
```

but it doesn't work... still, default pallet is the same.

**Comment by BeholdPL** [comment]
Hi :) Is there any way do solve that problem? :)

**Comment by primenest** [comment]
For future reference the following code works:
```
Kirki::add_field($textdomain, [
    'type' => 'color',
    'settings' => 'basic_colors_front_color',
    'label' => esc_html__('Kolor frontalny', $textdomain),
    'description' => esc_html__('Np. kolor tekstu', $textdomain),
    'section' => 'basic_colors',
    'default' => '#000000',
    'choices' => [
          'palettes' => [ '#000000', '#cc0000', '#ffffff' ],
    ],
    'transport' => 'auto'
]);
```

`'choices' => [
  'palettes' => [ '#000000', '#cc0000', '#ffffff' ],
],`

The difference is that there must be a letter S at the end of the word palettes
