### ISSUE TITLE
No output for the front end

### ISSUE THREAD

**Issue by aluminagency** [themeum/kirki#2295]
### Issue description:
In the customizer preview is working fine but its not generating the css output for the front end. Did I miss some settings or did I just didnt get it and the output for the front end needs to be added manualy? Im testing it in a clean instalation with twentytwenty

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Yes, Dev branch** Version:4.0-dev

### Using theme_mods or options?
theme-mods

### Code to reproduce the issue (config + field(s))

```
Kirki::add_config( 'wpkit_customizer_kirk', array(
	'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
) );

Kirki::add_field( 'accent_color_primary', [
    'type'        => 'color',
    'settings'    => 'accent_color',
    'label'       => __( 'Main accent color', 'wpkit' ),
    'section'     => 'colors',
    'default'     => '#eeeeee',
    'transport' => 'auto',
    'output'    => array(
        array(
			'element' => '.entry-title',
			'property' => 'color'
        ),
    ),
]);


```

**Comment by aluminagency** [comment]
no help whatsoever, totaly abandoned by myself 😑

**Comment by aristath** [comment]
@aluminagency are you by any chance adding your controls inside a hook?
If for example you add them in `customize_register` then this will happen.
You will need to add your controls *outside` of hooks, just calling the above code directly.
