### ISSUE TITLE
Styling doesn't change 

### ISSUE THREAD

**Issue by HIMA2020-Sam** [themeum/kirki#2297]
### Issue description:
First, I'm gonna say I have NO idea about coding. 
I have a website on wordpress.org with Florain theme. I used the wordpress customiser to change all the stylings. All was working fine until recently I noticed the colours and fonts were wrong. 

When I go into the customiser to change something, nothing happens. 
I'd love if someone can tell me exactly how I fix it.
I deactivated all my plugins to see if there was one causing the issues but there was no change. 

ANY guidance would be great! Thank you! (sorry I'm a bit useless on the info below!) 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

Version 3.0.45 

### Using theme_mods or options?
No clue. 

### Code to reproduce the issue (config + field(s))

Again I have no idea. If I knew which part of the code was causing the issue I'd try and fix it myself.

**Comment by aristath** [comment]
Hello @HIMA2020-Sam 
Have you tried contacting your theme developer?
Kirki is just a framework that themes can use to add their options and make some tasks easier. But the actual implementation depends completely on your theme...
