### ISSUE TITLE
Feature Request : New control 'screen'

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#2299]
First please see this https://i.ibb.co/QvctMgJ/Customize-Travelers-Blog-Just-another-Word-Press-site.gif

I have used "radio-image" control for show/hide fields added some js to resize the screen. It is pretty simple btw to achieve.

If this control is added in kirki, it would be more helpful for the users. The popular themes on the wp.org uses this feature.

**Comment by DannyCooper** [comment]
@ravishakya It sounds like you have already started building this, why don't you try making a pull request?

**Comment by mapsteps** [comment]
Something we're currently looking into with Kirki PRO :)

If you want to stay in the loop on that, please join us on Facebook (https://www.facebook.com/groups/1020376102132534) or join our mailing list (form on the website (https://kirki.org/)
