### ISSUE TITLE
Saving as option doesnt work

### ISSUE THREAD

**Issue by towfiqi** [themeum/kirki#230]
Thanks for creating the excellent framework! Really appreciate the effort. I am having an issue with kirki, although it states in the changelog that saving as option is possible. I cant make it work. Here is my sample config:

``` php
        $controls[] = array(
            'type'        => 'select2',
            'option_type' => 'option',
            'capability'  => 'edit_theme_options',
            'setting'     => 'theme_name[logo_position]',
            'label'       => __( 'Logo Position', 'kirki' ),
            'description' => __( 'Select logo Position', 'kirki' ),
            'section'     => 'layout_section',
            'default'     => '',
            'priority'    => 10,
            'choices' => array(
                'logo_left' => 'Left',
                'logo_right' => 'Right',
                'logo_center' => 'Center (Above Menu)',
                'logo_middle' => 'Center (Inside Menu)',
            ),
        );
```

P.S: I am trying to migrate from redux. I already have options saved as "themename" in the wp_options table. I am trying to overwrite the 'logo_position' array inside the "themename" column. It works well with default customizer markup without kirki..

**Comment by aristath** [comment]
Hey there!

We're currently working on a redux-compatible API so this will soon be possible without changing a lot of code. :)

Could you please post your config so that I may take a look?

**Comment by aristath** [comment]
Try adding this:

``` php
// Add configuration
add_filter( 'kirki/config', function( $args ) {
    'options_type' => 'option',
    'option_name'  => 'theme_name',
    'capability'   => 'edit_theme_options',
} );
```

Then your field should look like this:

``` php
$controls[] = array(
    'type'        => 'select2',
    'settings'    => 'logo_position',
    'label'       => __( 'Logo Position', 'kirki' ),
    'description' => __( 'Select logo Position', 'kirki' ),
    'section'     => 'layout_section',
    'default'     => '',
    'priority'    => 10,
    'choices'     => array(
        'logo_left'   => 'Left',
        'logo_right'  => 'Right',
        'logo_center' => 'Center (Above Menu)',
        'logo_middle' => 'Center (Inside Menu)',
    ),
);
```

**Comment by towfiqi** [comment]
Ari, Thanks for the quick response!! I added this to my existing config.

``` php
    'options_type' => 'option',
    'option_name'  => 'theme_name',
    'capability'   => 'edit_theme_options',
```

I tested 3 fields until now. radio-image, checkbox & the select field. after adding the config you just gave me, the radio-image and the checkbox works fine. But not the select field. It doesnt do anything when I change the select dropdown. I specified transport = 'refresh' to this field. still not responsive. I guess it has something to do with the select2 js. just to be clear the select control code looks exactly like the code you asked me to add.

Thank You :)

**Comment by aristath** [comment]
try using `'type' => 'select'` instead of select2.
The select2 field is still experimental and hasn't been tested yet. :smile: 
We're planning to add a select2 field in the next version so this is more of a draft field for now, it still needs some work.

**Comment by towfiqi** [comment]
Lovely!! Everything's working fine now.. Thank you so much :+1: :ghost:

**Comment by aristath** [comment]
:) I'm glad I could help!
