### ISSUE TITLE
Can't see default button in image type control

### ISSUE THREAD

**Issue by jkolekar** [themeum/kirki#2300]
### Issue description:
I tried to use image for logo in my theme with default option set to "get_template_directory_uri().'/images/logo@2x.png'," but i can't see default button after removing 
log image

### Version used: 3.0.44
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
	$controls[] = array(
        'type'     => 'image',
        'settings'  => 'bt_retina_logo',
        'label'    => esc_html__( 'Retina Logo', 'the-next-blog' ),
        'description' => esc_html__('Retina Ready Image logo. It should be 2x size of normal logo. For example 200x60px logo will displays at 100x30px', 'the-next-blog' ),
        'section'  => 'logo_favicon',
	    'default'  => get_template_directory_uri().'/images/logo@2x.png',
	    'priority' => 2,
    );

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
