### ISSUE TITLE
[Question] repeater control prefix

### ISSUE THREAD

**Issue by ferdysopian** [themeum/kirki#2301]
is there an explanation why the repeater control doesn't use 'kirki-' prefix like the other control?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
