### ISSUE TITLE
Change Section to custom_logo

### ISSUE THREAD

**Issue by mat81black** [themeum/kirki#2304]
### Issue description:
I'm trying to change section to custom_logo, to make it appear not under its standard section, but under my section created with kirki, in a custom panel.

The Custom Logo disappears from its normal section, but is not displayed in the new section.

### Version used:
Versione 3.1.0, integrated into the theme

### Using theme_mods or options?
Yes, custom_logo

### Code to reproduce the issue (config + field(s))
```
function customize_register( $wp_customize ) {
	$wp_customize->get_control( 'custom_logo' )->section = 'logo_section';
}
add_action( 'customize_register',  'customize_register' ), 999);
```
Thank you all in advance

**Comment by nonamich** [comment]
Try setting the correct value for the **instance_number** property.
[screenshot](https://i.imgur.com/4lS1lkt.png)

**Comment by mapsteps** [comment]
Have you tried nonamich's suggestion? I personally went the other way around and added fields to the logo section in the customizer instead of trying to get the custom_logo out of there.

I don't remember if I attempted this though.

I'm closing this issue for now.
