### ISSUE TITLE
Baloo Thambi 2 font issue

### ISSUE THREAD

**Issue by dylan-ngo11** [themeum/kirki#2308]
### Issue description:
Hi! In the latest version, Google updates Baloo Thambi font to Baloo Thambi 2 font.
Now it shows invalid property value on the frontend https://share.getcloudapp.com/X6uO4BkK
How could I fix it?

Thank you!

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
