### ISSUE TITLE
Any Future Plan to add multi-select

### ISSUE THREAD

**Issue by towfiqi** [themeum/kirki#231]
Since you guys already added select2 is there any future plan to add multi-select option group? There is a gpl hybrid theme that already does this. here is the link to the control. I tested it. seem to work fine:
http://jayj.dk/multiple-select-lists-theme-customizer/

After adding the control , I successfully produced a multi-select category list like this: 

``` php
/*GET LIST OF CATEGORIES*/
$layercats = get_categories(); 
$newList = array();
foreach($layercats as $category) {
    $newList[$category->term_id] = $category->cat_name;
}

$wp_customize->add_control(
    new Jayj_Customize_Control_Multiple_Select(
        $wp_customize,
        'multiple_select_setting',
        array(
            'settings' => 'multiple_select_setting',
            'label'    => 'Testing multiple select',
            'section'  => 'section_id', // Enter the name of your own section
            'type'     => 'multiple-select', // The $type in our class
            'choices'  => $newList // Your choices
        )
    )
);
```

hint: the get_categories could be used to list any taxonomy terms.

**Comment by fovoc** [comment]
Hey there,

there's already in place a [multicheck](http://kirki.org/#multicheck-field) and a [sortable](http://kirki.org/#sortable-field) control that can be used in cases like this. Can't tell if a multi-select would be necessary though.

**Comment by towfiqi** [comment]
Yes I know there is, But if you use a multi checkbox, and the site has lots of categories, the list becomes really long, not really best for ux. Most of the theme options framework uses multi-select instead of multi checkbox. :)

**Comment by aristath** [comment]
@fovoc any chance of adding this to the select2 field that you're building?

**Comment by fovoc** [comment]
@aristath sure, merging the multiple selection capability in `select2` type ;)

**Comment by fovoc** [comment]
@towfiqi I just added a new control type `select2-multiple` in 0689f8183f15c8bc6e8a22c55129a5c33bd6bc48 based in https://select2.github.io/examples.html#multiple
