### ISSUE TITLE
overwrite the inline css of the KIRKI plugin for wordpress

### ISSUE THREAD

**Issue by gemon01** [themeum/kirki#2310]
### Issue description:

Hi, how can I do to overwrite the inline css of the KIRKI plugin?

For example I would like to change the background color of the fancybox popup, but also by writing the class
```
.fancybox-overlay {
background: # 282828 !important;}
```

in the theme editor, this is written before kirki’s online style, so even if there is ”!important” it doesn’t work !!! 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

3.1.1

### Using theme_mods or options?
theme_mods

**Comment by mapsteps** [comment]
notice the space you have after the `#`. This might be the reason `!important` is not working for you here.
