### ISSUE TITLE
How to save color from 'color' field to a variable?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2311]
I have a color field like this:

```
Kirki::add_field($textdomain, [
    'type' => 'color',
    'settings' => 'basic_colors__black',
    'label' => esc_html__('Podstawowa czerń', $textdomain) ,
    'section' => 'basic_colors',
    'default' => 'rgba(0, 0, 0, 1.000)',
    'choices' => ['alpha' => true],
    'transport' => 'auto'
]);
```

Now I would like to save color from this field to variable, so that I could use that var in the others fields. Thanks to that I could use this field to control colors globally in a lot of fields at once. How can I do that?

**Comment by DeoThemes** [comment]
I'm not the plugin developer. But have you tried to save it this way?
`$my_color = get_theme_mod( 'basic_colors__black', 'rgba(0, 0, 0, 1.000)' );`
