### ISSUE TITLE
Kirki oustomizer showing blank no option

### ISSUE THREAD

**Issue by talha32022** [themeum/kirki#2312]
### Issue description:
customizer is not working correctly on mine bitnami multi-tier WordPress running on google cloud
it shows tabs but when I click the tabs it shows lank in the customizer

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
I am using latest version
### Using theme_mods or options?
I am using martfury theme

**Comment by keslerm** [comment]
Seeing the same thing, looks like it's trying to pull from
`/bitnami/wordpress/wp-content/plugins/kirki/modules/tooltips/tooltip.css?ver=3.1.3`

Instead of
`/wp-content/plugins/kirki/modules/tooltips/tooltip.css?ver=3.1.3`

Looks like it's probably related to WP_PLUGIN_DIR handling?

**Comment by phoenixgao** [comment]
Having the same issue.
It seems kriki is not respecting customized WP_PLUGIN_DIR, could it be fixed?

**Comment by phoenixgao** [comment]
For anyone who came across this issue because of customized WP_PLUGIN_DIR, for example, if you are using bitnami Wordpress helm chart, could try this workaround:

add a filter to kirki_config:
```
/**
 * Configuration sample for the Kirki Customizer
 */
function my_kirki_config() {
    $args = array(
        'url_path'      => '/wp-content/plugins/kirki', // Or the correct path to kirki in your URL, after your domain
    );

    return $args;
}

add_filter('kirki_config', 'my_kirki_config');
```

It will be applied here and override the default path:
https://github.com/kirki-framework/kirki/blob/v3.1.2/core/class-kirki-init.php#L77

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
