### ISSUE TITLE
Disable Google Fonts

### ISSUE THREAD

**Issue by goldengreath** [themeum/kirki#2315]
Hello!

I found that my "Photo Me" Wordpress Theme ist using Kirki. I have been trying to remove the connection to google fonts because of GDPR Reasons: https://journal.markusthoma.com/

No matter what I tried - I didn't get them out of my loading external ressources. I want to host the fonts locally in my website.

**How can I disable / disconnect / remove the Google Fonts from my website? What code Snippet do I have to paste in my theme's functions.php?**

I just want to completely get rid of the google fonts loading on my site.

With kind regards,
Markus

**Comment by mapsteps** [comment]
Kirki is GDPR compliant and downloads Google fonts to your server + serves them locally. If requests are made directly to the Google server, they're not by Kirki.
