### ISSUE TITLE
Add Multiple New controls without changing the core

### ISSUE THREAD

**Issue by towfiqi** [themeum/kirki#232]
Hi,

I am trying to create new custom controls without changing any core files. I dont want to loose the edits I made in custom.php when uploading the new version of kirki.

With the latest version of kirki, If I want to create a custom control, I have 2 ways:
1. edit the `class-kirki-controls-custom-control.php` file. works fine but with this method I can only create one custom control. The main problem is when I update kirki, the custom control is lost. 
2. I can create a new class in my sample-config.php file. But then, I need to change the `class-kirki-controls.php` file. If I go with this method, when I update kirki, my change is lost too.

Maybe I am missing something. Can you guys please point me to a right direction? I am not seeing any  documentation on Creating Custom Control.

:)
Thanks

**Comment by aristath** [comment]
Hey again!

What controls do you want to add?
Perhaps we could add them in-core?

**Comment by towfiqi** [comment]
@aristath Thanks. But I was talking in general. I was trying to test few controls by following various tutorials. I am trying to create an image slider control , custom typography control and a notice control. The current structure of kirki doesn't allow people to user kirki fields + their own fields. We are limited to use only kirki core fields. It would be great if we could add controls with a custom functions or filters to add custom controls and append the new controls inside the `Kirki_controls` class.

Thanks

**Comment by aristath** [comment]
If you have extra controls then you can add them using the Customizer API, you don't need Kirki for that.
More details about that here: https://developer.wordpress.org/themes/advanced-topics/customizer-api/

However I get your point... I haven't implemented anything that will allow you to add your own controls in Kirki.
I'm marking this as a feature request and I'll work on it later today, hopefully I'll have something ready by the end of the day. :)

**Comment by towfiqi** [comment]
wow! I am overwhelmed! :D Thank you so much. Keep up the good work :+1:

**Comment by aristath** [comment]
I just submitted a commit for this: https://github.com/reduxframework/kirki/commit/96a6ead0bb9191f05a16a566ffe10763032fe372

If I'm not mistaken this should work:

``` php
/**
 * Controls are defined as an array ( 'type' => 'class_name' )
 * so all we have to do is add our custom controls to the default array
 */
function hook_my_custom_controls( $controls ) {
    $controls['custom-type-1'] = 'My_Custom_Control_Class_1';
    $controls['custom-type-2'] = 'My_Custom_Control_Class_2';

    return $controls;
}
add_action( 'kirki/control_types', 'hook_my_custom_controls' );
```

Let me know if that works!

**Comment by towfiqi** [comment]
Just tested it. sad to say its not working. here is my custom class and the action hook, added in my sample-config.php:

``` php
class Kirki_Controls_Notice_Control extends Kirki_Control {
    public $type = 'notice';
    public function render_content() { ?>
        <label>
            <?php $this->title(); ?>
            <?php
                echo '<h4>Here is a Custom Message for ya! :D</h4>';
            ?>
            <?php echo $this->value(); ?>
        </label>
        <?php
    }
}

function my_custom_controls( $controls ) {
    $controls['notice'] = 'Kirki_Controls_Notice_Control';

    return $controls;
}
add_action( 'kirki/control_types', 'my_custom_controls' );
```

and my control:

``` php
        $controls[] = array(
            'type'        => 'notice',
            'setting'     => 'front_upgrade',
            'label'       => __( 'Blah', 'kirki' ),
            'section'     => 'frontpage_section',
            'priority'    => 10,
        );
```

The control returns the Title and a input field.

Thanks

**Comment by aristath** [comment]
Actually it does work!!

Here's the complete code I used to test this with your custom control:

``` php
/**
 * Wrapper function to make sure our control is added where it needs to be added.
 */
function register_my_custom_control( $wp_customize ) {
    /**
     * The custom control class
     */
    class Kirki_Controls_Notice_Control extends WP_Customize_Control {
        public $type = 'notice';
        public function render_content() { ?>
            <label>
                <span class="customize-control-title">
                    <?php echo esc_attr( $this->label ); ?>
                    <?php if ( ! empty( $this->description ) ) : ?>
                        <span class="description customize-control-description"><?php echo $this->description; ?></span>
                    <?php endif;
                    echo '<h4>Here is a Custom Message for ya! :D</h4>';
                ?>
                <?php echo $this->value(); ?>
            </label>
            <?php
        }
    }
}
add_action( 'customize_register', 'register_my_custom_control' );

/**
 * Register our custom control with Kirki
 */
function my_custom_controls( $controls ) {
    $controls['notice'] = 'Kirki_Controls_Notice_Control';
    return $controls;
}
add_action( 'kirki/control_types', 'my_custom_controls' );

// Add config
Kirki::add_config( 'my_config', array(
    'capability'    => 'edit_theme_options',
) );
// Add section
Kirki::add_section( 'my_test_section', array(
    'title'          => __( 'Test Section' ),
) );
// Add the field
Kirki::add_field( 'my_config', array(
    'type'     => 'notice',
    'section'  => 'my_test_section',
    'settings' => 'dummy_setting'
) );
```

Please note the above code makes use of our [new API](https://github.com/reduxframework/kirki/wiki) instead of the previous implementation with the `kirki/config` and `kirki/fields` filters.

**Comment by aristath** [comment]
btw, if all you want to do is add some custom html then you can use our `custom` control: https://github.com/reduxframework/kirki/wiki/custom

**Comment by aristath** [comment]
Actually I just simplified this a bit...
You can now do it like this:

``` php
/**
 * Wrapper function to make sure our control is added where it needs to be added.
 */
function register_my_custom_control( $wp_customize ) {
    /**
     * The custom control class
     */
    class Kirki_Controls_Notice_Control extends WP_Customize_Control {
        public $type = 'notice';
        public function render_content() { ?>
            <label>
                <span class="customize-control-title">
                    <?php echo esc_attr( $this->label ); ?>
                    <?php if ( ! empty( $this->description ) ) : ?>
                        <span class="description customize-control-description"><?php echo $this->description; ?></span>
                    <?php endif;
                    echo '<h4>Here is a Custom Message for ya! :D</h4>';
                ?>
                <?php echo $this->value(); ?>
            </label>
            <?php
        }
    }
    // Register our custom control with Kirki
    Kirki()->controls->control_types['notice'] = 'Kirki_Controls_Notice_Control';

}
add_action( 'customize_register', 'register_my_custom_control' );


// Add config
Kirki::add_config( 'my_config', array(
    'capability'    => 'edit_theme_options',
) );
// Add section
Kirki::add_section( 'my_test_section', array(
    'title'          => __( 'Test Section' ),
) );
// Add the field
Kirki::add_field( 'my_config', array(
    'type'     => 'notice',
    'section'  => 'my_test_section',
    'settings' => 'dummy_setting'
) );
```

The difference is that now you can add your custom control using

``` php
Kirki()->controls->control_types['notice'] = 'Kirki_Controls_Notice_Control';
```

instead of the filter I mentioned previously. :+1: 

I'm marking this issue as resolved.

**Comment by aristath** [comment]
I also added a new page in the WIKI for this: https://github.com/reduxframework/kirki/wiki/Registering-new-control-types

**Comment by towfiqi** [comment]
@aristath  Still couldnt make it work.:( I am placing the whole code in the bottom of my theme's functions.php file. 

**Another thing:** I just downloaded the latest build and looks like there is a big performance issue. My customizer used to load within 4.06 secs. Now it takes 5.56 secs to load.. Same fields. I went back to previous build that I downloaded yesterday and its back at 4.06 again...

**Comment by aristath** [comment]
Can you please make sure you pull the latest commits from the repo?
Are you using Kirki as a plugin or embedded in a theme?

I'm investigating the performance issue you have now.

**Comment by towfiqi** [comment]
Yep! I just downloaded the latest commits 20 mins ago. and I am embedding kirki in a theme.

Thanks

**Comment by aristath** [comment]
Performance-wise:
I just tested adding 10 controls using the WordPress Customizer API with Kirki deactivated, and then adding the same 10 fields using Kirki with its API.
The difference was less than 100ms so nothing serious... (4.66s-> 4.72s)

I still haven't tested using it embedded in a theme though... and it's late so I'll just test it tomorrow and see if that's causing any issues.
