### ISSUE TITLE
Google fonts not loading when activating Kirki plugin

### ISSUE THREAD

**Issue by nevlund** [themeum/kirki#2322]
### Issue description:
Will try to describe the issue as short and clear as possible. When activating the kirki plugin, the google fonts used on the website is not showing. I am using Kameron for headers and Lato for normal text. When deactivating the plugin, the google fonts appears as they should. 

So the problem seems to be related to the kirki plugin, but how to solve this font issue? 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
I am using latest version of WP, all plugins are up to date. 

### Using theme_mods or options?
The theme is hypermart. Elementor is a part of the theme.

**Comment by mapsteps** [comment]
Did you possibly move the site to a different server? If so, try deleting the fonts folder in the wp-content folder on your server. this will update the paths & re-download the fonts.

This is fixed with the upcoming Kirki 4 release.
