### ISSUE TITLE
Load more Google Font variants

### ISSUE THREAD

**Issue by joakimaglo** [themeum/kirki#2327]
### Issue description:
Let's say a user selects a font like so:

![typography](https://user-images.githubusercontent.com/9765146/83939593-8db13280-a7de-11ea-951b-4e24d6402585.png)

Now, `regular` will be the default weight. But how would I go about making sure that more weights are available as well? For example, I might want to make the weight 700 available to use as bold text. Otherwise, only regular will be available with no way of making the text italic or bold, which is really restrictive.

Before I could use the below code snippet to load all variants, but it doesn't work anymore:
```
/**
 * Load all Google Font variants with Kirki
 */
function stephanie_load_all_variants_and_subsets() {
 if( class_exists( 'Kirki_Fonts_Google' ) ) {
		Kirki_Fonts_Google::$force_load_all_variants = true;
 }
}
add_action( 'after_setup_theme', 'stephanie_load_all_variants_and_subsets' );
```
Am I doing something wrong? Is there any way to solve my use case?

Thanks!

### Version used:
Plugin Version 3.1.3

### Using theme_mods or options?
`theme_mods`

**Comment by JiveDig** [comment]
We’re facing the same limitation and considering using Kirki for all settings but doing our own thing for typography. 

The new variable fonts (v2 API) in Google are promising... much smaller file to load the full range. But that likely brings on other issues. 

We’ve hit this font weight issue though, and it’s a real concern.

**Comment by joakimaglo** [comment]
I finally got it to work by hooking it to `'init'` instead of `'after_setup_theme'`:
```
/**
 * Load all Google Font variants with Kirki
 */
function kirki_load_all_font_variants() {
  if (class_exists('Kirki_Fonts_Google')) {
    Kirki_Fonts_Google::$force_load_all_variants = true;
  }
}
add_action('init', 'kirki_load_all_font_variants');
```

**Comment by JiveDig** [comment]
Loading all variants isn't a solution for us, as performance is a major concern. We are currently filtering the google fonts in Kirki and adding bold/italic to the main body font choice, but it's a bit restrictive still. 

At least there's a filter though.

**Comment by joakimaglo** [comment]
> Loading all variants isn't a solution for us, as performance is a major concern. We are currently filtering the google fonts in Kirki and adding bold/italic to the main body font choice, but it's a bit restrictive still.
> 
> At least there's a filter though.

@JiveDig I know, performance is a concern. Do you mind sharing how you’re filtering and adding bold + italic variants?
