### ISSUE TITLE
Styling of switchers is broken

### ISSUE THREAD

**Issue by DeoThemes** [themeum/kirki#2329]
### Issue description:
After recent updates switcher controls look weird. The label is not fully visible and covered by the switcher.

![dinery_customizer_footer](https://user-images.githubusercontent.com/16485360/85253712-59519d80-b491-11ea-88d5-6b4735c5e0e6.jpg)

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
