### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#233]
Hi
Kirki works fine on localhost, but when I transfer it to my webhost ([A2Hosting](http://a2hosting.com)), customizer page shows a blank page containing below error message:

`Fatal error: Class 'Kirki\Controls\CustomControl' not found in /home/downupsh/public_html/wp-content/themes/new/admin/customizer/includes/Controls.php on line 144`

I change PHP version of server (in cPanel) to these versions:
- PHP 5.3.29
- PHP 5.2.17  
- PHP 5.3.8  
- PHP 5.4.0  
- PHP 5.4.13  
- PHP 5.4.8  
- PHP 5.5.0  
- PHP 5.5.0beta2  
- PHP 5.5.13

But, error message appears yet.

Any Solution?!!

**Comment by aristath** [comment]
Are you using the stable version of the plugin from w.org or the dev version from github?

**Comment by DevelopOnline** [comment]
I use latest version (0.8.4) from master branch of github

**Comment by aristath** [comment]
Can you please try updating the plugin using the master branch here?
The master branch is no longer 0.8.4 and the `CustomControl` does not exist anymore, it hasn't existed for a long time. Please delete the version you're currently using and try using the one here.

**Comment by DevelopOnline** [comment]
I update to latest master brach version (alpha 1.0.0), & `Customize preview` takes **too many time** to load!!
and some times it returns this error:
`( ! ) Fatal error: Maximum execution time of 120 seconds exceeded in C:\wamp\www\wp\wp-content\themes\new\admin\kirki\includes\styles\class-kirki-styles-frontend.php on line 111`

**120 seconds!!!** why??!

**Comment by aristath** [comment]
I don't know why, this depends on what you're doing with it.
Is your theme on github so that I may download it and test?

**Comment by DevelopOnline** [comment]
No, it's not on github.

**Comment by aristath** [comment]
I'm afraid I can't help unless I see your code and what you're doing.
