### ISSUE TITLE
kirki customizer framework new update causing ti wish list problems

### ISSUE THREAD

**Issue by ericinthehouse** [themeum/kirki#2334]
### Issue description:
the new update that you guys had on the kirki customizer framework plugin is causing the ti wishlist not to work properly i thought i fixed this issue but i guess its happening again.
### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
