### ISSUE TITLE
Upcoming PRO version, teasers

### ISSUE THREAD

**Issue by hogash** [themeum/kirki#2335]
Hey guys!

Heard about Kirki's new ownership and saw a PRO version is coming soon. I already subscribed to receive news, but i was wondering if you could share some teasers or plans of what you'll introduce.

I'm in a dillema if i should just wait for PRO or develop what i need by myself.

Thanks!

**Comment by mapsteps** [comment]
Hey @hogash,

Here are 2 things we're currently working on. grouping controls into "Tabs" and allowing to make certain fields "responsive".

Please join us on Facebook, we'll announce things here (and on our mailing list) once they're ready.

https://www.facebook.com/groups/1020376102132534
