### ISSUE TITLE
Multicolor Field - Custom Labels Missing

### ISSUE THREAD

**Issue by tajim** [themeum/kirki#2338]
### Issue description:
Labels on Multicolor field is showing the default value now instead of the Label added in choices. 

It used to show labels I have given in the choices array.

![Customizer Screenshot](https://wpmunk.com/wp-content/uploads/2020/07/Screen-Shot-2020-07-24-at-1.55.58-AM.png)

### Version used:
Latest Version from wp.org 3.1.4

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'theme_prefix', array(
		'type'        => 'multicolor',
		'settings'    => 'color_main_nav_ed',
		'label'       => '',
		'section'     => 'layout_site_navigation',
		'priority'    => 10,
		'transport'   => 'auto',
		'choices'     => array(
			'bgcolor' => esc_html__( 'Background Color', 'theme-slug' ),
			'link'    => esc_html__( 'Link  Color', 'theme-slug' ),
			'hover'   => esc_html__( 'Hover  Color', 'theme-slug' ),
		),
		'default'     => array(
			'bgcolor' => '#ffffff',
			'link'    => '#101010',
			'hover'   => '#000000',
		),
		'output'    => array(
			array(
			  'choice'    => 'bgcolor',
			  'element'   => '.site-header .navbar',
			  'property'  => 'background-color',
			),               
			array(
			  'choice'    => 'link',
			  'element'   => '.navbar .navbar-nav .nav-link',
			  'property'  => 'color',
			),
			array(
			  'choice'    => 'hover',
			  'element'   => '.navbar .navbar-nav .nav-link:hover',
			  'property'  => 'color',
			),			
		),		
) );
```

**Comment by tajim** [comment]
Hello

I think i figured out the problem.

You have added "__ = wp.i18n.__;" in the latest version of the wp-color-picker-alpha.js file but 'wp-i18n' as the dependency has not been added in the class-kirki-control-base.php file where you enqueue 'wp-color-picker-alpha'

which is why it now shows an error.

wp-color-picker-alpha.js?ver=3.1.3:21 Uncaught TypeError: Cannot read property '__' of undefined

![Error Screenshot](https://wpmunk.com/wp-content/uploads/2020/07/Screen-Shot-2020-07-26-at-12.19.19-AM.png)

If I add the 'wp-i18n' dependency in array then the error message goes away and the correct labels are showing in Customizer MultiColor field.

Can you please add the dependency and send an update to the plugin.

Regards 
Tajim

**Comment by mapsteps** [comment]
Solved,

thanks for bringing this to my attention! The update will be released asap.

Best,
David

**Comment by BeholdPL** [comment]
Hi, is this have been fixed in any update?

**Comment by BeholdPL** [comment]
Hi, this problem is still in last version!! Any way for fix that??
