### ISSUE TITLE
Image Select Field converts value to array

### ISSUE THREAD

**Issue by towfiqi** [themeum/kirki#234]
@aristath 
When you use `'type' => 'option',` the radio image field doesnt work the way it should. 

Here is what happens: 
When you click the one of the image, the settings update live fine. But when you try to save by clicking the "Save and Publish" button, you will notice, you can click it again. which should not happen. 

when you click it again. the value is saved as: `Array ( [0] => value)` instead of just `value` and when you click the "save" button once. its saved as only `value` which is how it should be.

Please let me know if you find a fix for this. 
Thanks

**Comment by towfiqi** [comment]
Sorry. Just found out it was caused because I set the default to an array.

BUT the other issue remains. After selecting an option, you will have to save the Customizer's "Save and Publish" button twice.

Regards

**Comment by towfiqi** [comment]
Looks like the issue was related to redux. Un-embedded redux and its gone. You can close the ticket :)

**Comment by fovoc** [comment]
+1

**Comment by aristath** [comment]
@towfiqi awesome, thanks for the update!
