### ISSUE TITLE
Kirki/config seems to be broken

### ISSUE THREAD

**Issue by ralphjsmit** [themeum/kirki#2340]
### Issue description:

I wanted to add a configuration to my theme with the `kirki/config` filter, but the filter doesn't seem to work. 

### Version used:
Latest version from the WP org repository
### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
function kirki_demo_configuration_sample_styling( $config ) {

    $config['logo_image']   = 'http://kirki.org/img/kirki-new-logo-white.png';
    $config['description']  = __( 'The theme description.', 'kirki' );
    $config['color_accent'] = '#00bcd4';
    $config['color_back']   = '#455a64';
    $config['width']        = '20%';

    return $config;

}
add_filter( 'kirki/config', 'kirki_demo_configuration_sample_styling' );
```

This is just one example that doesn't work. Logo image doesn't work and colors neither. I already tried emptying the cache of my browsers, but that didn't work. Do you have any idea why this doesn't work?

**Comment by aristath** [comment]
[v3.1.0](https://github.com/kirki-framework/kirki/releases/tag/v3.1.0) removed the branding & styling modules. They were getting heavily abused by theme authors causing a lot of accessibility issues, and additionally they were too messy to maintain without any real benefit to users.
If you want to use them, you can extract them from a version prior to 3.1 and include them on your own. :+1:
