### ISSUE TITLE
Can`t use Font awesome field type inside repeater  

### ISSUE THREAD

**Issue by ahmed1322** [themeum/kirki#2343]
this code does not work for font awesome at all

Kirki::add_field( $theme_config , [
	'type'        => 'repeater',
	'label'       => 'Add Contact Info',
	'section'     => 'footer_contact_info_sec',
	'settings'     => 'footer_contact_info',
	'priority'    => 20,
	'row_label' => [
		'type'  => 'text',
		'value' => 'Your Contact Information',
	],

	'button_label' => 'Add More Info',
	
	'fields' => [

		'info_text' => [
			'type'     => 'textarea',
			'label'    => 'Add Info',
			'default'  => 'Contact Info',
		],

		'info_icon'  => [
			'type'     => 'fontawesome',
			'label'    => 'Choose FontAwesome Icon',
		],

	],

] );

**Comment by mapsteps** [comment]
Only a few fields are currently supported inside the repeater. The FA control in general is deprecated. I'm closing this for now.
