### ISSUE TITLE
After WordPress 5.5 update, only Widget option available

### ISSUE THREAD

**Issue by paolosax** [themeum/kirki#2344]
### Issue description:
After WordPress 5.5 update, only Widget option is available in the Customizer. If I comment out my customizer.php file require (containing all the Kirki settings) and the Kirki inclusion as well, the default customizer come back. Also tried to disable all the plugins, but nope.

### Version used:
Version 3.1.5 (updated through Composer in the theme)

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
none

### Update
I've tried with the plugin version (i.e.: I've disabled the Kirki inclusion from vendor/composer in my theme and installed the plugin version), and now it works! Is it possible that the wpackagist version is not actually updated?

**Comment by mo2menelzeiny** [comment]
I'm facing the same issue, but it only works when I disable powerkit plugin

**Comment by mo2menelzeiny** [comment]
It's now fixed after powerkit patch

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
