### ISSUE TITLE
Muli Google font

### ISSUE THREAD

**Issue by pudelis** [themeum/kirki#2345]
### Issue description:
We have been used google font Muli in theme martfury. After update to version 3.1.5. Font is gone.

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by DannyCooper** [comment]
Muli has been renamed - https://github.com/google/fonts/pull/2504

**Comment by pudelis** [comment]
Thank You for fast respond :)
