### ISSUE TITLE
Typography doesn't load any fonts

### ISSUE THREAD

**Issue by hsehszroc** [themeum/kirki#2350]
### Issue description:
When adding typography field, the dropdown doesn't work at all and doesn't show any option. I used the same code from Kirki docs.

### Version used:
v3.1.5

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
`'type'        => 'typography',
'settings'    => 'font_heading',
		'description' => esc_html__( 'This font will be used for all Heading titles (H1, H2, H3, H5, H6).', 'textdomain' ),
		'label'       => esc_html__( 'Font', 'textdomain' ),
		'section'     => 'typography',
		'default'     => [
			'font-family' => 'Roboto',
			'variant'     => '700',
		],
		'choices' => [
			'fonts' => [
				'google'   => [ 'popularity', 50 ],
				'standard' => [
					'Georgia,Times,"Times New Roman",serif',
					'Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif',
				],
			],
		]`

**Comment by ali-han** [comment]
Hello,
I fixed this problem with "add_config"...

> Kirki::add_config( 'my_typography', array(
    'option_type' => 'theme_mod',
) );

Thanks.

**Comment by hsehszroc** [comment]
It doesn't seem to work for me. Here is the full code.

Config
```
Kirki::add_config(
	'theme_customizer',
	[
		'option_type' => 'theme_mod',
		'capability'=>'edit_theme_options',
                'disable_output' => true, // false also doesn't work
	]
);
```

Panel
```
Kirki::add_panel(
	'theme_style',
	[
		'title' => __( 'Appearance', 'textdomain' ),
	]
);
```

Section
```
Kirki::add_section(
	'theme_typography',
	[
		'title' => __( 'Typography (Fonts)', 'textdomain' ),
		'panel' => 'theme_style',
	]
);
```

Field
```
Kirki::add_field(
	'theme_customizer',
	[
		'type'        => 'typography',
		'settings'    => 'font_heading',
		'description' => __( 'This font will be used for all Heading titles (H1, H2, H3, H5, H6).', 'textdomain' ),
		'label'       => esc_attr__( 'Font', 'textdomain' ),
		'section'     => 'theme_typography',
		'default'     => [
			'font-family' => 'Lato',
			'variant'     => '700',
		],
		'choices' => [
			'fonts' => [
				'google'   => [ 'popularity', 50 ],
				'standard' => [
					'Georgia,Times,"Times New Roman",serif',
					'Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif',
				],
			],
		],
		
	]
);
```

**Comment by ali-han** [comment]
Hello hsehszroc,

1. Please check wp_head() in header.php
2. I thing, you must use add_config part after typography section for default settings... https://github.com/kirki-framework/kirki/issues/2350#issuecomment-695344107

```
Kirki::add_config( 'my_typography', array(
'option_type' => 'theme_mod',
) );
```

I'am not a geek-coder. I'am only kirki fanboy :)

**Comment by hsehszroc** [comment]
That's strange. Other fields are working fine within same file.

I forgot to mention that when I am on this typography section, the back button on top left doesn't work. I have to reload the page to go to other panel/section.

**Comment by ali-han** [comment]
Check the browser console. Most likely jQuery migrate problem or any JS error.

**Comment by hsehszroc** [comment]
Thanks @ali-han for pointing this out. It seems the script is having some issue. below is the console log.

```
Uncaught TypeError: can't access property "popularity", n.fonts.order is undefined
```

Without using google fonts also, there is js issue. It logs like this:
```
Uncaught TypeError: can't access property "serif", this.google.fonts.items is undefined
```
Can't find similar js problem faced by others in this repo issue. I hope I am not doing anything in wrong way.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
