### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2351]
### Issue description:
We faced the 500 error on page when theme contains such code 

```
Kirki::add_config( 'my_options', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	) );
```

without it - everything works ok 

Can you help us ?

### Version used:
Latest wp.org

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
```
Kirki::add_config( 'my_options', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	) );
```

P.S. I can provide you ftp,admin access in private/email message to get involved in that issue deeper. (https://cshobby.com/)

We would be grateful for quick response because it is urgent. Hope for your understanding.

**Comment by mapsteps** [comment]
Simply adding the config should not throw a 500 error. Further debugging on your end is necessary to make any suggestions. You can try enabling debug mode as explained here to see if we get any additional infos - https://wp-pagebuilderframework.com/docs/debugging/
