### ISSUE TITLE
Change file ?action=kirki-styles&ver=3.0.36 to normal .css file

### ISSUE THREAD

**Issue by aviz1** [themeum/kirki#2352]
### Issue description:

I have a wordpress theme (startwp) and it uses
https://mysite.com/?action=kirki-styles&ver=3.0.36

instead of the .css file.
How can I use the simple .css file, so I can minify it or inline or combine with other files?

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by aristath** [comment]
You would need to compile the CSS, then write it to a file.
Kirki provides a lot of hooks you can use, just search the code for `apply_filters` and `do_action` to see what you can do and where you can do it.
The CSS is dynamically generated and minified already, that is why by default compiling to a file is not supported out of the box, it's something you will need to implement yourself.
