### ISSUE TITLE
Can I put "Kirki::add_field" in header.php?

### ISSUE THREAD

**Issue by ducwp** [themeum/kirki#2353]
Can I put "Kirki::add_field" in header.php?

Many thanks.

**Comment by ralphjsmit** [comment]
I don't think you can do this, because the file is (AFAIK) not run when the customizer is opened. It's really a template and not a PHP-file. Anyone tested it?

**Comment by aristath** [comment]
No. You can not.
Fields should be in functions.php or a file called from there. Not in a template file.
