### ISSUE TITLE
Include additional variants for the 'Sans Serif' font family.

### ISSUE THREAD

**Issue by simontomkins** [themeum/kirki#2354]
For additional flexibility it would be great if the standard Sans Serif font family included additional variants such as 300, 500, 600, 800.

At the moment it's only regular, regular italic, 700, and 700 italic.

**Comment by aristath** [comment]
Fonts and their variants get pulled from the Google API and they get updated when a new version of the plugin is released.
Closing this one since it will be automatically taken care of when the next version gets published :+1:
