### ISSUE TITLE
What's the Customizer and Kirki future plans in Wordpress?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2356]
Hi

I'm planning to create a premium theme for ThemeForest, which using Kirki and Customizer. I heard that Customizer may be may be abandoned in near future, in favor of Gutenberg. Is this real possible? Are there any official plans for that?

Thanks!

**Comment by aristath** [comment]
There are no plans in WordPress Core to abandon the customizer.
There are plans for Full-Site-Editing (FSE) themes and global-styles, but these have nothing to do with the customizer so it's not going anywhere :+1: 
In FSE themes, global-styles will provide a way to edit global options for blocks, as well as a couple of global options like the background-color, but nothing that comes close to what the customizer does. They are different interfaces with different purposes and they can live side-by-side.
