### ISSUE TITLE
Typography: Add font-style property

### ISSUE THREAD

**Issue by viet34tqc** [themeum/kirki#2358]
### Issue description:
Typography is lacking font-style

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
Latest version from wordpress.org: 3.1.5
### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
Is there any way to add font-style attribute to the Typography field?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
