### ISSUE TITLE
Filter Google fonts font-display property

### ISSUE THREAD

**Issue by Jaessun** [themeum/kirki#2359]
### Issue description:
Hi,

I would like to be able to change the font-display property in the generated Google fonts css. However the Google fonts url is hardcoded here :
https://github.com/kirki-framework/kirki/blob/a9c4ee53d2fc88ba9bed6b7b508443083a3c2de5/modules/webfonts/class-kirki-modules-webfonts-embed.php#L146

Which makes it seemingly impossible to change the `display=swap` query arg in that url.

I found that there used to be a filter for this called `kirki_googlefonts_font_display` in a past version of Kirki but it has disappeared since. Would it be possible to re-implement that filter ?

### Version used:
This is the same on both the release version (3.1.5) and the master branch

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
