### ISSUE TITLE
Hover state not visible in preview

### ISSUE THREAD

**Issue by antonellaP** [themeum/kirki#236]
Great toolkit.  I've been playing around with the color field to style links, but I couldn't manage to get a preview of the hover state.  Only after saving the color value and leaving the Customizer I see the new hover value applied to the page.

**Comment by aristath** [comment]
Hey there!

Can you please provide some more details and a sample of the code you're using so that I may try to replicate your issue?

**Comment by antonellaP** [comment]
Hi Aristeides,
Thanks for getting back to me.  Here's what I've got:

``` php
$fields[] = array(
        'type'        => 'color',
        'setting'     => 'links_color',
        'label'       => __( 'Links Color', 'textdomain' ),
        'description' => __( 'Description', 'textdomain' ),
        'section'     => 'colors',
        'priority'    => 10,
        'default'     => '#de3495',   
        'output'      => array(
            array(
                'element'  => 'a:hover',
                'property' => 'color',
            ),
        ),
        'transport'   => 'postMessage',
        'js_vars'     => array(
            array(
                'element'  => 'a:hover',
                'function' => 'css',
                'property' => 'color',
            ),
        )
    );
```

If I put 'a, a:active' instead of 'a:hover', everything works fine, both on the preview page and outside of the Customizer.  Regarding the code above, if I hit save and publish I can see that the hover state has taken effect.  In other words, it's a live preview issue regarding the hover state, the hover value is saved and displayed outside of the Customizer preview.

Cheers!

**Comment by aristath** [comment]
Can you please try using `body a:hover` instead of `a:hover` ?
It could simply be that another stylesheet is somehow overriding the Kirki stylesheets if the hover color has also been defined elsewhere... adding the `body` in front of it _should_ fix it if this is the case

**Comment by antonellaP** [comment]
I've tried that but the situation remains unchanged.  Also, I'm testing Kirki on a very basic theme with little to no CSS rules and no rules for the link color.

**Comment by aristath** [comment]
Would it be easy for you to send me your theme via mail so that I may examine this in more detail and see what's wrong? You can find my mail on my profile.

**Comment by antonellaP** [comment]
No problem, sure, thank you!

**Comment by aristath** [comment]
Hey again!

Thanks for sending your theme...
After I spent about an hour examining it, it turns out that jQuery can't detect pseudo-selectors like `:hover`, `:active` etc. (see http://stackoverflow.com/questions/837741/jquery-css-function-changing-a-property-not-ahover-property)
As a result, the `js_vars` argument you've got there can't function properly.
The only thing I can think of would be to simply remove the `transport` and `js_vars` from that control.
If you do, then the field will automatically use `refresh` instead of `postMessage` and the styles will be applied in the customizer via CSS instead of JS.

I hope that helps!

**Comment by antonellaP** [comment]
Thank you so much Aristeides for all your help and for improving my theme considerably!
