### ISSUE TITLE
Preload ibm plex sans. How to preload this ?

### ISSUE THREAD

**Issue by Technobromo** [themeum/kirki#2360]
### Issue description:
I was facing an issue from google pagespeed insights about preloading ibm-plex-sans font
### Version used:
![PageSpeed Insights and 5 more pages - Personal - Microsoft​ Edge 25_11_2020 9_27_35 am](https://user-images.githubusercontent.com/75012196/100201835-8ade0180-2f26-11eb-9c43-c340f9122945.png)
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
Shoptimizer theme

**Comment by mapsteps** [comment]
In my humble opinion, this is caching-plugin territory. wp-rocket for instance I believe allows you to preload fonts.
