### ISSUE TITLE
Typograpgy field throws errors in Kirki 4.0-dev

### ISSUE THREAD

**Issue by ajaxthemestudios** [themeum/kirki#2361]
### Issue description:
When using the Typography field, errors similar to below are displayed sometimes breaking the whole customizer:
<b>Warning</b>:  preg_match() expects parameter 2 to be string, array given in <b>D:\laragon\www\site\wp-includes\class-wp-block-parser.php</b> on line <b>417</b><br>
<b>Warning</b>:  strlen() expects parameter 1 to be string, array given in <b>D:\laragon\www\site\wp-includes\class-wp-block-parser.php</b> on line <b>489</b><br>
<b>Warning</b>:  preg_match() expects parameter 2 to be string, array given in <b>D:\laragon\www\site\wp-includes\class-wp-block-parser.php</b> on line <b>417</b><br>
<b>Warning</b>:  strlen() expects parameter 1 to be string, array given in <b>D:\laragon\www\site\wp-includes\class-wp-block-parser.php</b> on line <b>489</b><br>
<b>Warning</b>:  preg_match() expects parameter 2 to be string, array given in <b>D:\laragon\www\site\wp-includes\class-wp-block-parser.php</b> on line <b>417</b><br>
<b>Warning</b>:  strlen() expects parameter 1 to be string, array given in <b>D:\laragon\www\site\wp-includes\class-wp-block-parser.php</b> on line <b>489</b><br>

### Version used:
Version:       4.0-dev
The problem does not happen with the stable version 3.1.5
 
### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'theme_config_id', [
	'type'        => 'typography',
	'settings'    => 'themenav_font',
	'label'       => esc_html__( 'Top Menu Fonts', 'kirki' ),
	'section'     => 'headerfont_section',
	'default'     => [
		'font-family'    => 'Open Sans Condensed',
		'variant'        => '300',
		'text-transform' => 'uppercase',		
		'letter-spacing' => '0',
		'font-size'      => '14px',
		'line-height'    => '1.4',
		'color'          => '#FFFFFF',		
	],
	'priority'    => 11,
	'transport'   => 'auto',

] );
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
