### ISSUE TITLE
webfont load issue

### ISSUE THREAD

**Issue by gallnomad** [themeum/kirki#2362]
### Issue description:
I was told be the developers of the theme i use (which uses your framework to contact you as they said the below error in google page speed insights is coming from your software. How can this issue be fixed?

Ensure text remains visible during webfont load
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading. Learn more.
URL | Potential Savings
-- | --
…webfonts/fa-solid-900.woff2 | 2,060 ms
…webfonts/fa-regular-400.woff2 | 1,500 ms
…webfonts/fa-brands-400.woff2 | 2,100 ms

### Version used:
Version 3.1.5

### Using theme_mods or options?
Not sure it is Commercegurus Shoptimizer theme, they told me to report here. Honestly not sure why they aren't doing it themselves instead of asking a customer to do it.

**Comment by mapsteps** [comment]
Kirki does not come bundled with FontAwesome. Either the theme or another plugin is loading FontAwesome here.
