### ISSUE TITLE
Multicolor labels are missing!!!

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2363]
Hi everyone
I saw there is a update for Kirki :) But still, there is a bug in multicolor field, I think!

This is my field set:

```
Kirki::add_field( $textdomain, [
    'type'        => 'multicolor',
    'settings'    => 'posts_headers_thumbnails_details_taxonomies_hover_active',
    'label'       => esc_html__( 'Kolor aktywnych taxonomii', $textdomain ),
    'description' => esc_html__( 'na obrazku wyróżniającym', $textdomain ),
    'section'     => 'posts_headers',
    'priority'    => 10,
    'alpha'       => true,
    'choices'     => array(
        'color'         => esc_html__( 'kolor', $textdomain ),
        'border'        => esc_html__( 'obramowanie', $textdomain ),
        'background'    => esc_html__( 'tło', $textdomain ),
    ),
    'default'     => [
        'color'         => '#ffffff',
        'border'        => $GLOBALS['active_color'],
        'background'    => $GLOBALS['active_color'],
    ],
    'transport' => 'auto',
    'output' => [
        // some things
    ],
] );
```
and what I see, labels are missing.
<img width="292" alt="Screenshot 2020-12-09 at 01 59 33" src="https://user-images.githubusercontent.com/34622592/101559836-42aced80-39c2-11eb-87f2-60c2b1d475e8.png">

Is this my fault?

Thanks!

**Comment by BeholdPL** [comment]
Is this issue can be fix?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
