### ISSUE TITLE
After theme copied, customizer set fonts cannot be found

### ISSUE THREAD

**Issue by willsib93** [themeum/kirki#2364]
### Issue description:
I copied my Shoptimizer site but now the fonts assigned in customizer cannot be found. I deactivated and then reactivated all plugins and Kirki was the offending plugin.

### Version used:
Latest version

### Using theme_mods or options?
Using Shoptimizer theme

### Code to reproduce the issue (config + field(s))
This is the offending code:
https://papdev.wpengine.com/nas/content/live/ahccsupplement/wp-content/fonts/ibm-plex-sans/zYXgKVElMYYaJe8bpLHnCwDKhdHeE6xOedc.woff

What we want is:
https://papdev.wpengine.com/wp-content/fonts/ibm-plex-sans/zYXgKVElMYYaJe8bpLHnCwDKhdHeE6xOedc.woff

**Comment by mapsteps** [comment]
This is fixed in v4! :)
