### ISSUE TITLE
Kirki not working when included from a plugin (using options)

### ISSUE THREAD

**Issue by ralphjsmit** [themeum/kirki#2366]
### Issue description:
I want to use Kirki in a plugin to output some styling for Contact Form 7. 

In my plugin.php file I created a function with a hook to `plugins_loaded`. Inside that function I use an  `if`-condition to check whether CF7 is active (`if ( function_exists( 'wpcf7_enqueue_styles' ) )`). If that's true, I include my `customizer.php` file like this:

`require(plugin_dir_path( __FILE__ ) . 'modules/cf7/customizer.php');`

All those things are inside the `plugins_loaded` hook.

I checked that the file is included by adding a var_dump in the `customizer.php` file. 

In my `customizer.php` file, I added the below code, but nothing happens in the customizer. I would be very grateful if anyone has an idea what I'm doing wrong. If you need more information, please ask 🙏
Thanks a lot!

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
The latest plugin via the repository, v 3.1.6. 
No, I didn't use the develop branch. 

### Using theme_mods or options?
Options

### Code to reproduce the issue (config + field(s))
```
//General configuration for Kirki
Kirki::add_config( 'rjs_cf7_cust', [
    'capability'    => 'edit_theme_options',
    'option_type'   => 'option',
	'option_name'   => 'rjs_cf7', // I tried with and without this line.
] );

//add_filter( 'kirki_telemetry', '__return_false' );


//Controls & sections

//ADD THE SECTION

Kirki::add_section( 'rjs_framework_cf7_section', [
    'title'          => esc_html__( 'Contact Form 7', 'rjs-cf7' ),
    'description'    => esc_html__( 'Change the appearance of the contact forms.', 'rjs-cf7' ),
    'priority'       => 400,
] );


//CF7 SECTION

Kirki::add_field( 'rjs_cf7_cust', [
	'type'        => 'custom',
	'settings'    => 'rjs_framework_cf7_docs',
	'section'     => 'rjs_framework_cf7_section',
	'default'     => '<p style="margin-top: 0px;">Customize the appearance of all forms on this website made with Contact Form 7. The form needs to be registered using the specific wrapper classes needed by this plugin.</p>',
	'priority'    => 1,
  ] );
```

**Comment by mapsteps** [comment]
It sounds like the plugin is executed late. You can try to hook things into the `after_setup_theme` hook.
