### ISSUE TITLE
Inserting our own CSS HTML preloader, removing Kirki's spinner!

### ISSUE THREAD

**Issue by Cecile-Lus** [themeum/kirki#2369]
### Issue description:
**_Can anyone help me with this issue please?_**
Hello there,
Thanks for your valuable efforts that produce priceless ease in connecting people with the tech world!
My message would probably be a popular issue everyone at the amateur level of the customization and coding universe –like me- may encounter.

We have a WordPress website theme (Florian) which is using KIRKI as a customizer. We want to change Kirki’s default page loader animation (SVG spinner) with our own animation. We need the both default SVG image (which is Kirki's logo) and the wave type spinner to be removed. 

Please note that our own preloader does not contain an SVG image file. Instead, it has an SVG code inside CSS and HTML files. We don’t know how to remove Kirki’s SVG spinner and where to add our CSS and HTML codes. We need the preloader to show up and disappear before every new page gets loaded. We have an HTML file and a CSS file separately in which the shape and animation of our logo have been defined. The logo is our lab’s logo. 

Would you please guide us on how to add the HTML and CSS codes to our theme through Kirki or any other possible way, to fulfill the above? Kindly explain in a simple and step by step technical language. 

Looking forward to receiving your reply soon.

We appreciate your kind assistance and wish you all the best.
Cécile
Paris, France 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
I couldn't find this!

**Comment by mapsteps** [comment]
The preloader is deprecated and was removed with Kirki v4.
