### ISSUE TITLE
When loading font-family "Noto Serif JP" my server dies

### ISSUE THREAD

**Issue by nonamich** [themeum/kirki#2372]
### Issue description:
Kirki downloads this font in 479 pieces because this server may be stuck for a couple of minutes or until reboot.

How can I get around this loading method for this font?

screenshot: https://i.imgur.com/rz2prPw.png

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
