### ISSUE TITLE
Exclude certain google fonts to load

### ISSUE THREAD

**Issue by imfaisalkh** [themeum/kirki#2373]
I'm using Kirki Typography controls in my theme. My theme is already loading a couple of google fonts and I don't want kirki typography control to load those specific fonts because they are loading twice, once by the theme and once by kirki.

Is there a way to exclude certain fonts to load?

**Comment by TerenceJohnson** [comment]
I have the same issue. It would also be very helpful - speeding up work and ensuring consistency - if the Typography control offered the active theme fonts as an option, or if there was a "settings" page for Kirki to configure the fonts to be made available to page authors and whether or not they should be cached locally.

**Comment by mapsteps** [comment]
There is an option in Kirki to only make specific fonts available in the Google fonts selection dropdown though I'm not 100% sure if that would solve the problem.

Here's an exmaple:

```
/**
 * Manipulate Google Fonts optgroup.
 *
 * @param array $custom_choice The custom choice.
 *
 * @return array The updated custom choice.
 */
function prefix_custom_google_fonts( $custom_choice ) {

	$custom_choice = array(
		'google' => array( 'popularity', 4 ),
	);

	return $custom_choice;

}
add_filter( 'wpbf_kirki_font_choices', 'prefix_custom_google_fonts' );
```

Reference - https://v3.kirki.org/docs/controls/typography/

In an ideal scenario, the fonts should be declared in one place only. We get similar issue with Elementor for instance, if someone defines a font there specifically. This is just the nature of 2 plugins are working on the same website. Both offer the feature to include fonts.
