### ISSUE TITLE
May i know how do i change the loading image Kirki Customizer Framework

### ISSUE THREAD

**Issue by telet-ai** [themeum/kirki#2374]
### Issue description:
Sorry, it is not Issue,
May i know how do i change the loading image Kirki Customizer Framework?
  

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
Version 3.1.6 
### Using theme_mods or options?

theme_mods

**Comment by RMDWebDesign** [comment]
This works:

```PHP
function prefix_your_custom_loading_logo() {
	?>
    <style>
        .kirki-customizer-loading-wrapper {
            background-image: url("https://via.placeholder.com/150");
        }
    </style>
	<?php

}
add_action( 'wp_head', 'prefix_your_custom_loading_logo', 100 );
```

_Source: https://wordpress.org/support/topic/changing-loader-animation-spinner/#post-13649562_

**Comment by mapsteps** [comment]
The custom loading indicatore was removed in Kirki 4.
