### ISSUE TITLE
Repeater radio name

### ISSUE THREAD

**Issue by nervewax** [themeum/kirki#2376]
### Issue description:

If you define two (or more) repeaters that both have a radio field with the same ID, the radio inputs share their `name` attribute across all of the customizer. This means setting the radio to `:checked` in one radio will clear all other options with that name attribute.

https://github.com/kirki-framework/kirki/blob/3f4b68e2b2cbc43d64fa65929316a2f539c20194/packages/kirki-framework/control-repeater/src/Control/Repeater.php#L369

The name field here needs to include something like the parent repeater ID, to make sure the name can not be the same in other places in customizer.

To resolve this in our case, we appended the field priority integer and made sure they are always set to different values. Ideally this would use the parent repeater's ID, but it's not currently accessible in the template.

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

3.0.39

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

<details>
<summary>See full config code 👀👇</summary>

<p>

```php
\Kirki::add_config(
	'test_config',
	array(
		'capability'  => 'edit_theme_options',
		'option_type' => 'theme_mod',
	)
);

\Kirki::add_panel(
	'test_settings',
	array(
		'title'       => esc_html__( 'Settings', 'kirki' ),
	)
);

\Kirki::add_section(
	'dropdown_one',
	array(
		'panel' => 'test_settings',
		'title' => esc_html__( 'Dropdown One', 'kirki' ),
	)
);

\Kirki::add_section(
	'dropdown_two',
	array(
		'panel' => 'test_settings',
		'title' => esc_html__( 'Dropdown Two', 'kirki' ),
	)
);

\Kirki::add_field(
	'test_config',
	array(
		'label'        => esc_html__( 'Dropdown One', 'kirki' ),
		'section'      => 'dropdown_one',
		'settings'     => 'dropdown_menu_one',
		'type'         => 'repeater',
		'default'      => array(),
		'fields'       => array(
			'type'        => array(
				'default'  => 'one',
				'label'    => esc_html__( 'Radio One', 'kirki' ),
				'type'     => 'radio',
				'choices'  => array(
					'one'   => esc_html__( 'One', 'kirki' ),
					'two'   => esc_html__( 'Two', 'kirki' ),
					'three' => esc_html__( 'Three', 'kirki' ),
				),
			),
		)
	)
);

\Kirki::add_field(
	'test_config',
	array(
		'label'        => esc_html__( 'Dropdown Two', 'kirki' ),
		'section'      => 'dropdown_two',
		'settings'     => 'dropdown_menu_two',
		'type'         => 'repeater',
		'default'      => array(),
		'fields'       => array(
			'type'        => array(
				'default'  => 'one',
				'label'    => esc_html__( 'Radio Two', 'kirki' ),
				'type'     => 'radio',
				'choices'  => array(
					'one'   => esc_html__( 'One', 'kirki' ),
					'two'   => esc_html__( 'Two', 'kirki' ),
					'three' => esc_html__( 'Three', 'kirki' ),
				),
			),
		)
	)
);
```

<p>

</details>

- Create two sections, both with repeaters that have radio fields.
- Add a repeater row to each field in customizer and select a radio option.
- Go to the other repeater and see that the radio value is cleared, because normal browser protocol only allows one radio option to be selected among inputs with the same `name` attribute, unless they are enclosed inside a different `form` tag.  
  - Note that the whole customizer is enclosed in one form tag, so the name fields need to be different.
  - Changing the radio field ID would also fix this issue, but it should be possible to add settings to different repeaters and not have this happen too.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
