### ISSUE TITLE
Using Kirki as a composer package in theme

### ISSUE THREAD

**Issue by ponopress** [themeum/kirki#2379]
### Issue description:
I am trying to use Kirki as a composer package but I guess auto-loader is not loading the main Kirki class. 

I get the fatal error of Kirki class not found.

### Version used:
	`"aristath/kirki": "^3.1"
`

**Comment by JiveDig** [comment]
See https://github.com/kirki-framework/kirki/issues/2414

**Comment by mapsteps** [comment]
Hi @JiveDig, I'm closing this because it's pretty much a duplicate. Can you please add the issue description above to the issue you've mentioned? I'm just trying to keep things organized. Thank you!

**Comment by JiveDig** [comment]
@MapSteps Happy to do whatever you need, but can you clarify what you want? I don't have any description above I just posted here to reference the other issue and help keep things organized :)
