### ISSUE TITLE
Google Fonts Not Loading and Slider Control Not Applying Style Values

### ISSUE THREAD

**Issue by tonioSilvestroK** [themeum/kirki#238]
Hi, thanks for this great plugin.  I've been experimenting with it, both the development and stable .org version.  I've been having some issues with loading Google fonts in the Customizer.  I've been using a select box just like the examples I see in the documentation and this post: 
http://aristeides.com/blog/build-wordpress-theme-using-kirki/

However, although the regular font choices like Serif, Sans-serif, and monospace, are displayed and saved, the Google fonts don't get displayed at all (although the style rule is added to the HTML in the preview page). 

Also, I've tried using the slider control for customizing the font-size the same way as the above post, but in the stable version of Kirki I can't get it to work at all while in the development version I get it to work but without any preview in the Customizer. 

I'd appreciate any help for this, thank you!

**Comment by aristath** [comment]
@tonioSilvestroK hey there!

Can you please test this with the development version?
I believe this has been fixed...

**Comment by ghost** [comment]
I updated my kirki last night in the Genesis starter theme and can confirm the slider and fonts work fine in the dev branch.

**Comment by aristath** [comment]
Awesome, thanks for checking @cmwwebfx I'll go ahead and close this one. :+1:

**Comment by tonioSilvestroK** [comment]
Sorry Aristeides, I've tested this and for some reason I can't get the fonts to load.  The font names are in the dropdown box, the local fonts get applied, but the Google fonts not visible, not even outside of the Customizer preview.  I'm sorry I didn't see your message earlier.  Do I need to open another issue for this?

**Comment by aristath** [comment]
@tonioSilvestroK can you please post the code you're using?
If this is part of a theme you're building would you mind sending me your entire theme so that I may check this in more detail and see why you're having trouble?

**Comment by tonioSilvestroK** [comment]
OK.  Just to be more precise, the default Google font gets applied too.  It's the Google font I choose from the customizer that doesn't get applied.

**Comment by aristath** [comment]
@tonioSilvestroK I'll still need to see your code and test it myself in order to understand what goes on.

**Comment by tonioSilvestroK** [comment]
Yes, I'm on it.
Cheers!

**Comment by tonioSilvestroK** [comment]
Here's the theme.  It's a barebones twenty fifteen child theme.

The attachment didn't work.  Can I use your email?

Cheers!

----Messaggio originale----

Da: notifications@github.com

Data: 20-giu-2015 20.24

A: "reduxframework/kirki"kirki@noreply.github.com

Ogg: Re: [kirki] Google Fonts Not Loading and Slider Control Not Applying Style Values (#238)

@tonioSilvestroK I'll still need to see your code and test it myself in order to understand what goes on.

**Comment by tonioSilvestroK** [comment]
Just emailed you the theme.  Thanks!

**Comment by aristath** [comment]
This is not a bug with Kirki, it's just that the style declarations are not specific enough and are overriden by the theme's `style.css` declarations.
Also, `postMessage` won't work with google fonts 'cause it may be able to change the font-family in the css but it can't inject the script necessary for the google fonts without a refresh. You can simply remove it. So overall you currently have this:

``` php
/**
* Add Fields to the sections
*/
function tfc_fields( $fields ) {

    /**
    * Add Google fonts 
    */
    $fields[] = array(
        'type'        => 'select',
        'setting'     => 'tfc_typeface',
        'label'       => __( 'Typeface', 'twenty-fifteen-child' ),
        'description' => __( 'Please choose a typeface for headings and body copy for your site.', 'twenty-fifteen-child' ),
        'section'     => 'tfc_typography',
        'default'     => 'Lato',
        'priority'    => 10,
        'choices'     => Kirki_Fonts::get_font_choices(),
        'output'      => array(
            array(
                'element'  => 'body, h1, h2, h3, h4, h5, h6',
                'property' => 'font-family',
            ),
        ),
        'transport'   => 'postMessage',
        'js_vars'     => array(
            array(
                'element'  => 'body, h1, h2, h3, h4, h5, h6',
                'function' => 'css',
                'property' => 'font-family',
            ),
        ),
    );

    return $fields;

}

add_filter( 'kirki/fields', 'tfc_fields' );
```

Please change it to this:

``` php
/**
* Add Fields to the sections
*/
function tfc_fields( $fields ) {

    /**
    * Add Google fonts
    */
    $fields[] = array(
        'type'        => 'select2',
        'setting'     => 'tfc_typeface',
        'label'       => __( 'Typeface', 'twenty-fifteen-child' ),
        'description' => __( 'Please choose a typeface for headings and body copy for your site.', 'twenty-fifteen-child' ),
        'section'     => 'tfc_typography',
        'default'     => 'Lato',
        'priority'    => 10,
        'choices'     => Kirki_Fonts::get_font_choices(),
        'output'      => array(
            array(
                'element'  => 'body, h1, h2, h3, h4, h5, h6',
                'property' => 'font-family',
                'units'    => ' !important'
            ),
        ),
    );

    return $fields;

}
add_filter( 'kirki/fields', 'tfc_fields' );

```

That makes it completely functional.

**Comment by tonioSilvestroK** [comment]
Hello, Aristeides, thank you now it works as expected.  I see a select2 control, is this a different control type from the one in the code I posted?

Cheers, great support!

**Comment by fovoc** [comment]
@tonioSilvestroK `select2` has a built-in search form, pretty useful for long lists like Google Fonts, I guess that's why Aristeides prefered it ;)

FYI: https://select2.github.io/examples.html#basic

**Comment by tonioSilvestroK** [comment]
Thanks Dimitris.  I changed the code back to the simple select and the functionality was broken again.  Using the select2 control makes it work (besides not using postMessage).  So I think that whatever you've done to select2, that's what makes the difference, at least in my case.  

Great work!
