### ISSUE TITLE
Output in repeater not working

### ISSUE THREAD

**Issue by udarts** [themeum/kirki#2381]
Using output in the repeater is not working. I have been trying to use a text field to add a font-size (not using the typography), but having the value of e.g.: 14px in the field is not change the link element.

I am using the latest version.

In the fields area of the repeater, I added the following:
```` php
'header_left_font_size' => [
    'type'        => 'text',
    'label'       => esc_html__( 'Font size', 'kirki' ),
    'section'     => 'header_left_section',
    'default'     => esc_html__( '14px', 'kirki' ),
    'transport'   => 'auto',
    'output'      => [
        [
            'element'   => '.mini-text-icon',
            'property'  => 'font-size',
        ],
    ],
],
````

**Comment by udarts** [comment]
Can anyone confirm that this is actually the case?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
