### ISSUE TITLE
Is there a way to support custom color in color-palette control?

### ISSUE THREAD

**Issue by cloudinstone** [themeum/kirki#2382]
For example: if I want my clients can input custom color also can pick preset colors?  sure we can provide two fields: one color, another palette. but it will be better that just use one field instead of handle logic in frontend and save unnecessary  two field to database.

**Comment by contactjavas** [comment]
Hi @cloudinstone , thanks for posting the issue.

There are two different controls: 
- `control-color-palette`  ([view doc](https://kirki.org/docs/controls/color-palette/))
-  and `control-palette` ([view doc](https://kirki.org/docs/controls/palette/))

The second one, was missing (well, it was there before I deleted that 😓 ) and we added it back in around January / February.
Regarding your issue, do you mean it is the `control-palette`? If so, could you try that?

Please let me know if that works for you.
Thanks! :)

**Comment by contactjavas** [comment]
Hi @cloudinstone , let us know if this is still an issue for you.
For now, let me close this :)

Thanks
