### ISSUE TITLE
Where do I create the config, in functions.php?

### ISSUE THREAD

**Issue by RyanSacks** [themeum/kirki#2384]
Hi,
I've installed and activated the Kirki Plugin. I don't see anything in the Sidebar, so I'm assuming that I need to now create a Config. Where do we create this Config, in functions.php?

Sidenote: I'm using the latest version of WordPress and it said the Plugin hasn't been tested with this version. So I will keep that in mind.

**Comment by mapsteps** [comment]
Nothing wrong placing the config in the `functions.php` file. Kirki 4 will no longer require you to use a config though. We're updating the plugin & documentation to v4 soon.
