### ISSUE TITLE
Nested panel priority no working

### ISSUE THREAD

**Issue by bhubon** [themeum/kirki#2385]
### Code to reproduce the issue (config + field(s))

I make a nested panel and there has a section with the nested panel.
I want to show the section first and then the nested panel, so I change the panel priority but the panel still in the first but I want to show it after the section

how can I solve these. Please help Me

There is the code

Kirki::add_config( 'novena_config', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );
//Main Panel
Kirki::add_panel( 'novena_home_page', array(
    'priority'    => 10,
    'title'       => esc_html__( 'Home Page Setting', 'novena' ),
    'description' => esc_html__( 'Novena Home Page Setting', 'novena' ),
) );
// Section into main pannel
Kirki::add_section( 'novena_home_page_section', array(
    'title'          => esc_html__( 'Banner Section', 'novena' ),
    'description'    => esc_html__( 'Home Page Banner Section', 'novena' ),
    'panel'          => 'novena_home_page',
    'priority'       => 10,
) );

// Nested panel 
Kirki::add_panel( 'novena_home_page2', array(
    'title'       => esc_html__( 'Home Page Setting', 'novena' ),
    'description' => esc_html__( 'Novena Home Page Setting', 'novena' ),
    'panel' => 'novena_home_page',
    'priority'    => 999,
) );

Kirki::add_section( 'novena_home_page_feature_section', array(
    'title'          => esc_html__( 'Feature Section', 'novena' ),
    'description'    => esc_html__( 'Home Page Feature Section', 'novena' ),
    'panel'          => 'novena_home_page2',
    'priority'       => 161,
) );

![image](https://user-images.githubusercontent.com/54433969/115237657-a13b6280-a13e-11eb-8325-22b4ffe68fce.png)

**Comment by Satlantisy** [comment]
Panel only can be nested in a panel. Change your add_section to add_panel.

**Comment by bhubon** [comment]
Can I add control in pannel?

**Comment by Satlantisy** [comment]
> Can I add control in pannel?

No, you need to add_section after add_panel. 

For example:

`Kirki::add_panel( 'home_page', array(`
`// some code`
`) );`

`Kirki::add_panel( 'home_page_sub_panel', array(`
`// some code`
`'panel' => 'home_page',`
`) );`

`Kirki::add_section( 'section_for_home_page_sub_panel', array(`
`// some code`
`'panel' => 'home_page_sub_panel',`
`) );`

Then you can add control in the section.
