### ISSUE TITLE
Fonts Loader Issue

### ISSUE THREAD

**Issue by darylstone** [themeum/kirki#2387]
### Issue description:
PHP throws endless warnings because the font's can't be loaded correctly. This happens whenever the site is loaded and also of course if you switch to another page. 
I checked the fonts folder and the font's has been downloaded. I did clear also the database kirki google web fonts but it didn't change anything. Reseting Customizer and selecting font's didn't help either. It always throws this warnings. It seems like that the font's are still used via google even though they have been downloaded.

```
Kirki::add_field('ti', array(
    'type'        => 'typography',
    'settings'    => 'footer_links_typography',
    'label'       => __('Footer Links Typography', 'kirki'),
    'section'     => 'footer_typography_section',
    'transport'   => 'auto',
    'default'     => array(
        'font-style'     => array( 'bold', 'italic' ),
        'font-family'    => 'inherit',
        'font-size'      => '14px',
        'text-transform' => 'capitalize',
        'font-weight'    => 'inherit',
        'color'          => 'inherit'
    ),
    'priority'    => 3,
    'choices'     => array(
        'font-style'     => true,
        'font-family'    => true,
        'font-size'      => true,
        'text-transform' => true,
        'font-weight'    => true,
        'color'          => true,
    ),
    'output' => array(
     array(
       'element'  => 'footer.site-footer a'
     )
    )
));
```

### Using theme_mods or options?
theme_mod

  // SETUP KIRKI CONFIGURATOR
    Kirki::add_config('ti', array(
        'capability'  => 'edit_theme_options',
        'option_type' => 'theme_mod',
        'option_name' => 'ti',
    ));

### Code to reproduce the issue (config + field(s))

AH01071: Got error 'PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/josefinsans/v17/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_DjQbMlhKSbpUVz0Eqq2.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/josefinsans/v17/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_DjQbMlhKSbpUVz0Eqq2.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/josefinsans/v17/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_DjQbMhhKSbpUVz0Eqq2.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/josefinsans/v17/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_DjQbMhhKSbpUVz0Eqq2.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/josefinsans/v17/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_DjQbMZhKSbpUVz0Eg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/josefinsans/v17/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_DjQbMZhKSbpUVz0Eg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 45PHP message: PHP Warning: array_keys() expects parameter 1 to be array, string given in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 50PHP message: PHP Warning: array_values() expects parameter 1 to be array, string given in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 51PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDujMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDujMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDuHMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDuHMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDunMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDunMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDubMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDubMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDurMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDurMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDuvMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDuvMQbeS2AopSg.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDuXMQbeS2Ao.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 97PHP message: PHP Warning: Illegal string offset 'https://fonts.gstatic.com/s/opensanscondensed/v15/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff1GhDuXMQbeS2Ao.woff' in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 116PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 45PHP message: PHP Warning: array_keys() expects parameter 1 to be array, string given in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 50PHP message: PHP Warning: array_values() expects parameter 1 to be array, string given in /var/www/vhosts/sitelinkremoved.ch/httpdocs/wp-content/themes/newgentheme/includes/kirki/modules/webfonts/class-kirki-fonts-downloader.php on line 51', referer: https://www.sitelinkremoved.ch/

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing all open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Thank you for your understanding.

Best,
David

**Comment by nowarah** [comment]
im still having this issue using v4
