### ISSUE TITLE
Dimension field shows invalid-value

### ISSUE THREAD

**Issue by udarts** [themeum/kirki#2388]
I using the latest version of Kirki, and trying to use the dimension field.
But when changing it's value, I get the invalid value warning.

The value I change to is: 41px

Using the following code:

     my_config_kirki_add_field(
         array(
             'type'        => 'dimension',
             'settings'    => 'widget_footer_padding',
             'label'       => esc_html__( 'Widget Footer padding', 'kirki' ),
             'section'     => 'footer_section',
             'default'     => '0px',
             'choices'     => [
                 'accept_unitless' => false,
             ],
             'transport'   => 'auto',
             'output'      => [
                 [
                     'element' => '#footer-widgets',
                     'property' => 'padding-top',
                 ],
             ],
             'active_callback' => [
                 [
                     'setting'  => 'footer_widgets_enabled',
                     'operator' => '==',
                     'value'    => '1',
                 ]
             ],
         )
    );

So what is wrong here?

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
