### ISSUE TITLE
Palette Control Implementation

### ISSUE THREAD

**Issue by tonioSilvestroK** [themeum/kirki#239]
Hi there,
I have the palette control in the customizer but I can't find info on how to implement it.  I click on the colors but nothing happens: no changes in the preview and nothing gets saved.  

Thank you in advance for your help.

**Comment by aristath** [comment]
Hey there!

Can you please paste here an example of the code you're using to get the palette and how you're applying the palette colors to your site?

**Comment by tonioSilvestroK** [comment]
Hi aristah,

Here's what I've got:

/**
    \* Define custom palettes
    */
    $fields[] = array(
        'type'        => 'palette',
        'setting'     => 'color_palette_setting',
        'label'       => __( 'Palettes', 'textdomain' ),
        'description' => __( 'Description', 'textdomain' ),
        'section'     => 'color_palette',
        'default'     => 'red',
        'priority'    => 20,
        'choices'     => array(
            'red'  => array(
                '#ef9a9a',
                '#f44336',
                '#ff1744',
            ),
            'pink' => array(
                '#fce4ec',
                '#f06292',
                '#e91e63',
                '#ad1457',
                '#f50057',
            ),
            'cyan' => array(
                '#e0f7fa',
                '#80deea',
                '#26c6da',
                '#0097a7',
                '#00e5ff',
            ),
        ), 
    );

From here I'm quite lost.

Thanks :)

**Comment by aristath** [comment]
That's how you define the field.
The question however, is how are you **using** that field in your theme?

If for example you do this:

``` php
$value = get_theme_mod( 'color_palette_setting', 'red' );
```

then the value you're going to get is `red`, `pink` or `cyan`.
It's up to you how to handle that in your theme...

Example:

``` php
function add_color_palette_to_body( $classes ) {
  $classes[] = get_theme_mod( 'color_palette_setting', 'red' );
}
add_filter( 'body_class', 'add_color_palette_to_body' );
```

The above code will add a class to your `<body>` element and you can then style your theme using CSS.

**Comment by tonioSilvestroK** [comment]
I see, now it's clearer.  I was confused as to how the palette control was supposed to be put to work.  Now it makes sense, thank you!

**Comment by aristath** [comment]
:+1: I'm glad I could help!
