### ISSUE TITLE
Logo error

### ISSUE THREAD

**Issue by muqtada2** [themeum/kirki#2391]
my dear

I have an error in my logo that I cannot change until I deleted the logo image from within the media, but it was not deleted for me, and this problem is old I have. Can you solve it with me because some of my clients will not show them the logo because I told you I removed it from the media Please help me
Thank

The version used: 3.1.6 

![t6_642](https://user-images.githubusercontent.com/33468924/119123326-1947c180-ba38-11eb-87a5-03382c029d59.png)

**Comment by mapsteps** [comment]
We were not able to replicate this issue, if this isn't your own theme, please try to reach out to the developers of the theme and report the issue to them as well.

Thank you.
