### ISSUE TITLE
PHP errors when saving the page with Elementor site builder

### ISSUE THREAD

**Issue by ilearnio** [themeum/kirki#2392]
### Issue description:

The errors never appear on the website, they only appear sometimes after saving the Elementor page builder.

### Version used:

3.1.6

(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

Nope, don't have time for it unfortunately. Thought just to report about a bug I found

```
Warning: Private methods cannot be final as they are never overridden by other classes in /public/wp-content/plugins/kirki/core/class-kirki-settings.php on line 67

Warning: Private methods cannot be final as they are never overridden by other classes in /public/wp-content/plugins/kirki/core/class-kirki-settings.php on line 109

Warning: Private methods cannot be final as they are never overridden by other classes in /public/wp-content/plugins/kirki/core/class-kirki-settings.php on line 133

Warning: Private methods cannot be final as they are never overridden by other classes in /public/wp-content/plugins/kirki/core/class-kirki-control.php on line 65

Warning: Private methods cannot be final as they are never overridden by other classes in /public/wp-content/plugins/kirki/core/class-kirki-control.php on line 101
```

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
