### ISSUE TITLE
Not compatible with latest version of Gutenberg

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#2393]
Hi,

If you have the latest version of the Gutenberg plugin installed with the latest version of kirki. The CSS is not loading properly. See image below

![image](https://user-images.githubusercontent.com/11089018/119948298-6a1b6500-bfb8-11eb-981d-b7405f040fc3.png)

Thank You

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
