### ISSUE TITLE
How add new google font

### ISSUE THREAD

**Issue by nonamich** [themeum/kirki#2394]
Hi! 👋

Some google fonts are not in the selection list, like this [Lexend](https://fonts.google.com/specimen/Lexend?sort=date&category=Sans+Serif), how do I add it to the list custom?

Maybe you can add it with the 'kirki_fonts_google_fonts' filter, but I haven't figured out how. Sorry for the inconvenience there is a question repeating.

Thank You

**Comment by nonamich** [comment]
Corrected in the commit: [updated google fonts](https://github.com/kirki-framework/kirki/commit/0f9d24437665f6d5664da4e12bb4f0ae410815e4)

Thank!

**Comment by JiveDig** [comment]
I was hoping this was possible via filters, like:

```
add_filter( 'kirki_fonts_google_fonts', function( $fonts ) {
	if ( isset( $fonts['Crimson Text'] ) ) {
		return $fonts;
	}

	$fonts['Crimson Text'] = [
		'label'    => 'Crimson Text',
		'category' => 'serif',
		'variants' => [
			'600',
			'600italic',
			'700',
			'700italic',
			'italic',
			'regular',
		],
	];

	return $fonts;
});

add_filter( 'kirki_fonts_google_font_names', function( $fonts ) {
	$fonts = array_unique( array_merge( [ 'Crimson Text' ], $fonts ) );

	return $fonts;
});
```

But it doesn't look like it will work that way. 

Do we need to wait on a Kirki update to add any new/missing fonts?
