### ISSUE TITLE
Issue on wordpress with realtyspace theme

### ISSUE THREAD

**Issue by GaelleHenaf** [themeum/kirki#2395]
### Issue description:
Hello, 

I bought the theme realty space and install less plugins required including kirki. 
This plugin does not work, when I activate it, I can not access my front office and if I deactivate the plugin the shortcodes are displayed.

Do you have a solution? 
Thank you, Gaelle.

### Version used: 
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
Wordpress plugin

### Using theme_mods or options?
??

### Code to reproduce the issue (config + field(s))
Wordpress version : 5.7.2
Kirki version : 3.1.6 
Theme version : Realtyspace Child 1.1

**Comment by mapsteps** [comment]
Please try to reach out to the theme developer. This might be an issue with their implementation or theme. It might also be a 3rd party plugin conflict, please try to disable all other plugins to see if that changes anything.
