### ISSUE TITLE
Translate Issue

### ISSUE THREAD

**Issue by thawtes** [themeum/kirki#2396]
### Issue description:
Translation of Strings in JS files is not working

### Version used:
3.1.7

### Using theme_mods or options?
No

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
