### ISSUE TITLE
Theme Check Warning: WP_Filesystem should not be used

### ISSUE THREAD

**Issue by DarkMG73** [themeum/kirki#2397]
### Issue description:
Hello. Theme Check is giving the two warnings below. This happens with the latest version of Theme Check (v 20210617) updated today on two different installations. I see there was an issue back in 2015 like this and that is when they wanted WP_Filesystem to be used. WP must have changed their requirements again.

> **WARNING: WP_Filesystem was found** in the file inc/plugins/kirki/modules/webfonts/class-kirki-fonts-downloader.php WP_Filesystem should only be used for theme upgrade operations, not for all file operations. Consider using file_get_contents(), scandir(), or glob() Line 275: * @return WP_FilesystemLine 278: wp_filesystem;Line 279: wp_filesystem ) {Line 280: if ( ! function_exists( 'WP_Filesystem' ) ) {Line 283: WP_Filesystem();Line 285: wp_filesystem;

> **WARNING: WP_Filesystem was found** in the file inc/plugins/kirki/core/class-kirki-helper.php WP_Filesystem should only be used for theme upgrade operations, not for all file operations. Consider using file_get_contents(), scandir(), or glob() Line 87: * Initialize the WP_FilesystemLine 91: * @return object WP_FilesystemLine 129: wp_filesystem;Line 131: wp_filesystem ) ) {Line 133: WP_Filesystem( $credentials );Line 136: wp_filesystem;

### Version used:
kirki.3.1.7 (downloaded and installed tonight)
Theme Check v20210617 (downloaded and installed tonight)

### Using theme_mods or options?
n/a

### Code to reproduce the issue (config + field(s))
Run Theme Check with theme bundled with Kirki.

**Comment by mapsteps** [comment]
Those warnings are safe to ignore. WP_Filesystem is required by Kirki and it's okay to use it.
