### ISSUE TITLE
How to do this in the administrator panel http://www.xxx.com/wp-admin/ You can configure kirki? If so, how to configure it?

### ISSUE THREAD

**Issue by szchengmi** [themeum/kirki#2398]
Can I do the same as options framework and Redux framework in the administrator panel http://www.xxx.com/wp-admin/ You can configure kirki? If so, how to configure it?

**Comment by mapsteps** [comment]
If I understand this correctly, this is not possible. Kirki operates solely in the WordPress customizer.
