### ISSUE TITLE
Check box appears while enabling switch control

### ISSUE THREAD

**Issue by jimeepremi** [themeum/kirki#2400]
### Issue description:
Testing Kirki with WP 5.8 RC2 check box appears while enabling switch control

### Version used:
WP 5.8 RC2
![Screenshot (181)](https://user-images.githubusercontent.com/64537189/125582913-0aa0747b-2c7f-4eda-ac26-6c9004688ca0.png)

**Comment by mapsteps** [comment]
Fixed with the latest release.
