### ISSUE TITLE
block_editor_settings depracted in WP 5.8.

### ISSUE THREAD

**Issue by cafesk8** [themeum/kirki#2401]
Since WP 5.8. `block_editor_settings `filter is depracted and has to be replaced with `block_editor_settings_all `

https://github.com/kirki-framework/kirki/blob/3f4b68e2b2cbc43d64fa65929316a2f539c20194/packages/kirki-framework/module-editor-styles/src/Editor_Styles.php#L108

See: https://make.wordpress.org/core/2021/06/16/block-editor-api-changes-to-support-multiple-admin-screens-in-wp-5-8/ for details.

**Comment by addzycullen** [comment]
Any updates on this? It's causing fatal errors in the editor currently

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
