### ISSUE TITLE
CSS error on background control

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#2402]
When you click on the button ( **Background size** and **Background attachment** ) , the radio button is displaying on the top section.

![image](https://user-images.githubusercontent.com/11089018/129158094-a8ae0344-24b3-4d81-93ca-d47889cd8215.png)

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
