### ISSUE TITLE
Kirki 4.0?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2404]
Hi

What are the plans about v 4.0 for now?

**Comment by mapsteps** [comment]
Hey @BeholdPL,

until a few days ago, this was the current state of Kirki - https://kirki.org/blog/the-current-state-of-kirki/

I'm happy to let you know that we have just started to work on Kirki 4! We are digging deep into the code at the moment and fix everything that needs attention.

V4 seems pretty stable from what I can tell. We will have to have it tested by other theme devs in the wild later this year before we actually roll it out.

If you want to stay in the loop, I'd suggest you sign up for our mailing list and keep an eye on the blog - https://kirki.org/blog/.

**Comment by BeholdPL** [comment]
Hi, thanks for the answer!

Can I test V4 also? I'm creating my own theme now and Kirki is an integral part of it, so I would get ready for the final version :D

:)

**Comment by ravishakya** [comment]
Please add the post date on the blog listing and blog detail page. https://kirki.org/blog/

**Comment by mapsteps** [comment]
@ravishakya Done! :)

**Comment by mapsteps** [comment]
Hey @BeholdPL,

absolutely! It lives here in the develop branch - https://github.com/kirki-framework/kirki/.

Keep in mind that we are actively working on it currently so things might not work as expected.
