### ISSUE TITLE
Update Options from Front end Or Plugin

### ISSUE THREAD

**Issue by siddig-sami** [themeum/kirki#2405]
Hi
i’m trying to Update some options values from another plugin, i tried update_option() but it didn’t work

how can i access kirki from  another plugin then updating some options?

**Comment by mapsteps** [comment]
this requires custom work which we are unfortunately not able to help with.

`update_option()` will only work if you have declared in the kirki_config to save as an option, otherwise things will be saved as `theme_mod` by default.
