### ISSUE TITLE
what function is used to generate javascript for kirki 

### ISSUE THREAD

**Issue by mandricmihai** [themeum/kirki#253]
where is the call of the function or what are you using to generate the javascript for the kirki is a filter/action/function or what? 
I talk about this 

![image](https://cloud.githubusercontent.com/assets/5292321/8288994/54fb3486-1922-11e5-9897-6d534dd74561.png)
![image](https://cloud.githubusercontent.com/assets/5292321/8289139/38995c40-1923-11e5-8900-890d9d7aaf85.png)

**Comment by aristath** [comment]
Branding: https://github.com/reduxframework/kirki/blob/master/includes/class-kirki-scripts-customizer-branding.php
postMessage: https://github.com/reduxframework/kirki/blob/master/includes/class-kirki-scripts-customizer-postmessage.php
Tooltips: https://github.com/reduxframework/kirki/blob/master/includes/class-kirki-scripts-customizer-tooltips.php

I hope that helps!
