### ISSUE TITLE
Does 'required' only toggle on refresh?

### ISSUE THREAD

**Issue by teambonzai** [themeum/kirki#258]
I have a checkbox toggling some fields. When 'transport' is set to 'postMessage' (to prevent refresh), the 'required' fields don't toggle. Does toggle depend on a refresh?

<pre>// Logo toggle

  \Kirki::add_field( 'my_theme', array(
    'label'       => __( 'Toggle Checkbox', 'sage' ),
    'section'     => 'my_section',
    'settings'    => 'my_settings_toggle',
    'type'        => 'checkbox',
    'default'     => 0,
    'transport'   => 'postMessage',
  ) );

  // Logo

  \Kirki::add_field( 'my_theme', array(
    'label'       => __( 'Target', 'sage' ),
    'section'     => 'my_section',
    'settings'    => 'my_settings_target',
    'type'        => 'image',
    'transport'   => 'postMessage',
    'required'    => array(
      array(
        'setting'  => 'my_settings_toggle',
        'operator' => '==',
        'value'    => 1,
      ),
    )
  ) );</pre>

**Comment by aristath** [comment]
Hey there!

No, `require` should not depend on whether it's `refresh` or `postMessage`.
Can you please make sure you're using the version from this github repository and NOT the version on WordPress.org?
The previous version had some bugs that we've fixed on this repository and they'll be included in the next release.

**Comment by aristath** [comment]
@starflyer do you still require assistance on this one?

**Comment by aristath** [comment]
Closing this one due to inactivity.

If the issue still persists then don't hesitate to reopen this issue so that we may take a closer look at your issue.
Before you do, please check that you're testing using the latest version from the github repository and not the version on wordpress.org.

Cheers!
