### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by mandricmihai** [themeum/kirki#259]
``` php
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\wp-content\plugins\kirki-master\includes\class-kirki-output.php on line 134
```

Reproduce:Download > Activate> enable dummy data
if this is also related to dummy data you can close it

**Comment by aristath** [comment]
Hello again!
How exactly did you enable the dummy data?
This is probably related to one of the 2 demo files I currently have, I haven't updated them yet...
Thanks for reporting this!

If you disable the demo data you're not getting this error, right?

**Comment by mandricmihai** [comment]
I uncomment this include_once( KIRKI_PATH . '/sample-config.php' ); 

Yes no error with no dummy data

**Comment by aristath** [comment]
Just fixed this, it should be ok now. :)
