### ISSUE TITLE
Is TGM or another class loader required to run it as a plugin on a network install?

### ISSUE THREAD

**Issue by HongPong** [themeum/kirki#260]
In the process of setting this up I saw on aristeides.com that TGM should be used to get it to operate as a plugin. However this is not in the main documentation. Is it required to use this or another class loader (unless you want to embed in the theme)? 

Does building a multisite Wordpress network (in my case a pretty simple one, the themes on the multisites just need different settings) have any bearing on what the best choice is for setting this up? Thanks, it is a very cool tool to have & simplify customized theming.

**Comment by aristath** [comment]
Hey there!

TGM is just what most people use when they want to bundle plugins in their themes.
If you want to use TGM you can simply add it by requiring the wordpress.og version of the plugin. More information on that can be found on http://tgmpluginactivation.com/configuration/
Please keep in mind that the version on w.org is a bit old, I'll be updating it in the next few days.

Other than that, if you want you can simply network-activate the plugin on your network.
I this that's what would make more sense in your current use-case scenario.
Your themes will then be able to automatically detect its presence and use it without any issues. :)
If your themes don't use it then nothing extra will be loaded so there's no overhead.

**Comment by HongPong** [comment]
Hi, thanks for the quick answer. In foundationpress tried adding to my theme-support.php (which is an require_once in functions.php ) a statement with Kirki::add_config and I get Fatal error, call to undefined method. Is there some other kind of bootstrapping required? (on php 5.5.9-1ubuntu4.9 )

**Comment by aristath** [comment]
Can you please make sure you're using the master branch from this repository and NOT the w.org version?
If the plugin is activated it should work without any issues.
However the `Kirki::add_config` method for example does not exist in the 0.8.4 version that's on the wordpress.org repository yet, it will be included there as soon as we release version 1.0 (which will probably be in a few days).

**Comment by HongPong** [comment]
Ah thank you, the master branch helped. For future reference here is a test snippet that shows the class methods have arrived:

``` php
if ( ! function_exists( 'Kirki' ) ) {
    echo 'you has no kirki<br />';
} else {
    $kirki_methods = get_class_methods('Kirki');
    foreach ($kirki_methods as $method_name) {
        echo "$method_name\n";
    }
}

Kirki::add_config( 'mysitename', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'option',
    'option_name'   => 'mysitename',
) );
```

I really appreciate the help today!

**Comment by aristath** [comment]
:) I'm glad I could help!

Thanks for posting that snippet too, I'm sure others will also find it useful.

Cheers!
