### ISSUE TITLE
should use 'option_type' or 'options_type' on add_config?

### ISSUE THREAD

**Issue by HongPong** [themeum/kirki#263]
There is both 'options_type' and 'option_type' properties referenced at different points in the code as well as on the wiki , i.e.
https://github.com/reduxframework/kirki/wiki/Fields
vs 
https://github.com/reduxframework/kirki/wiki/Configuration
it would probably simplify things to only use one or the other exclusively.
(Also I think a name like "machine_name" would be a more logical choice to indicate an element's ID than "settings" but that's my Drupal bias showing.)

[Side note: when i use add_field for a text field, it works correctly but doesn't seem to matter if the config is called or not. Either way the values seem to save correctly - when I add or remove the config choice indicator, it does not seem to make a difference. ]

On the other hand trying to add_field radio-buttonset, I have not been able to get it to save its settings. It only returns the default value. Is it possible to use the radio-buttonset to output a CSS directive? I would like to give three options for color values for a background-color but it doesn't seem to work. I see the value CSS string generated but it never changes.

``` php

Kirki::add_config( 'fp_microsite', array(
    'capability'    => 'edit_theme_options',
    'options_type'   => 'theme_mod',
    //'option_name'   => 'fp_microsite',
) );

Kirki::add_panel( 'mypanel', array(
        'priority'    => 10,
        'title'       => __( 'my settings', 'kirki' ),
    ));

Kirki::add_section('header', array(
        'title'       => __( 'my header options' ),
        'priority'    => 10,
        'panel'       => 'mypanel',

    ));

Kirki::add_field( 'fp_microsite', array(
    'type'        => 'radio-buttonset',
    'settings'     => 'my_header_color',
    'label'       => __( 'my header color?', 'kirki' ),
    'description' => __( 'Select a background color', 'kirki' ),
    'help'        => __( 'Must be 1 of the 3.', 'kirki' ),
    'section'     => 'header',
    'default'     => '',
    'priority'    => 10,
    'choices'     => array(
        '#CC0000' => __( 'my red', 'kirki' ),
        '#795677' => __( 'my purple', 'kirki' ),
        '#F79621' => __( 'my orange', 'kirki' ),
    ),
    'output' => array(
        array(
            'element'   => '#intro-panel',
            'property'  => 'background-color',
            ),
        ),
));
Kirki::add_field( 'fp_microsite', array( // this seems to work correctly with or without fp_microsite referenced
    'type'        => 'text',
    'setting'     => 'text_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'help'        => __( 'This is some extra help text.', 'kirki' ),
    'section'     => 'header',
    'default'     => __( 'This is some default text', 'kirki' ),
    'priority'    => 10,
) );
```

**Comment by aristath** [comment]
Hey there!

You're absolutely tight... I'll take a look at it and use one of them exclusively (I'll add of course fallback to the previous method to whatever changes so we're backwards-compatible).

I'll have this fixed by tomorrow. :)

**Comment by fovoc** [comment]
Hey there,

about the button-set field, can't save its settings due to the sanitation that apply on top of it which halts due to the `#` character. If you still want a button-set, you may need to enqueue the styles with a simple function.

Hope that helps,
Dimitris

**Comment by HongPong** [comment]
thanks for the tip @fovoc and the very quick response @aristath . It seems like the period ( . ) character also gets sanitized out. A little easy control over aggressive sanitization would help. (how to disable the ampersand from turning into an HTML entity, anyone?) Appreciate your help everyone!

**Comment by aristath** [comment]
@HongPong I believe I just fixed the over-jealous sanitization on this one...
And from now on we're consistently using `option_type` and NOT `options_type`, thanks for pointing out I messed up. :+1: 
If you find any more issues then please don't hesitate to create new tickets here so that I may fix them ASAP.
