### ISSUE TITLE
Customizer assets are 404'ing

### ISSUE THREAD

**Issue by colmtroy** [themeum/kirki#264]
Related to https://github.com/reduxframework/kirki/issues/235
Working from 1.0.0-beta 1 https://github.com/reduxframework/kirki/releases/tag/1.0.0-beta1

kirki is embedded as follows:

```
include_once( dirname( __FILE__ ) . '/inc/kirki-1.0.0-beta1/kirki.php' );
function shiopa_kirki_config( $config ) {

    $config['url_path'] = get_stylesheet_directory_uri() . '/inc/kirki-1.0.0-beta1/';
    return $config;

}
add_filter( 'kirki/config', 'shiopa_kirki_config' );
//Load kirki config
require get_template_directory() . '/inc/kirki-config.php';

```

assets are being outputted via
http://foo.dev/wp-content/plugins/srv/www/foo/htdocs/wp-content/themes/shiopa/inc/kirki-1.0.0-beta1/includes/controls/switch/style.css?ver=4.2.2

Any ideas?

**Comment by aristath** [comment]
@edbloom What are the values for your site's urls in WP Dashboard -> Settings -> General?
If you do this, what URL are you getting?

``` php
var_dump( get_stylesheet_directory_uri() );
```

Is kirki installed on a parent theme, or a child theme?
If this is on a parent theme can you please try replacing `get_stylesheet_directory_uri()` with `get_template_directory_uri()` and let me know if that works?

**Comment by aristath** [comment]
@edbloom did you manage to resolve this one?
Do you still require assistance?

**Comment by colmtroy** [comment]
Hey @aristath sorry for the delay - yes this is still an issue. I've included some debug details below.

Let me know what else I can do to assist getting this issue squashed :)

1.) Values of site urls in WP -> Settings -> General

Site Address (URL) http://cgorg.dev
WordPress Address (URL) http://cgorg.dev

2.) URL for get_stylesheet_directoroy_url();
http://cgorg.dev/wp-content/themes/shiopa

3.) Kirki is installed on a parent theme

4.) I've tried calling Kirki via my functions.php as follows:
include_once( dirname( **FILE** ) . '/inc/kirki-1.0.0-beta1/kirki.php' ); //per the docs

include_once( get_template_directory() . '/inc/kirki-1.0.0-beta1/kirki.php' ); // second attempt - assets still 404'ing

I also tried calling kirki.php with both `get_stylesheet_directory_uri()` and `get_template_directory_uri()` but I suspect that's not what you were asking me to do as both of those throw php errors?

**Comment by aristath** [comment]
Would it be possible for you to send me FTP details for your server so that I may login and try to debug this?
It should help us figure out what happens and resolve this issue faster.

You can find my email on my github profile.
This is basically one of the last issues I have to resolve before we can release a stable version. :)

**Comment by colmtroy** [comment]
@aristath - of course :) Just sent you an email there now - thanks for your help!

**Comment by aristath** [comment]
Fixed.

The issues was that in the `inc/kirki-config.php` file there was this:

``` php
/**
 * Configuration sample for the Kirki Customizer.
 */
function kirki_demo_configuration_sample() {

    $args = array(
        //'logo_image'   => 'http://kirki.org/img/kirki-new-logo-white.png',
        'description'  => __( 'This is the theme description. You can edit it in the Kirki configuration and add whatever you want here.', 'kirki' ),
        //'color_accent' => '#00bcd4',
        //'color_back'   => '#455a64',
    );

    return $args;

}
add_filter( 'kirki/config', 'kirki_demo_configuration_sample' );
```

which was overriding the configuration you had in your functions.php file.

I removed that and now it seems to be working fine. :+1:

**Comment by Anydog** [comment]
Sorry for posting after closure. I had similar issue, so I solved it this was (maybe you should add this in doc. about embedding in theme):

``` php
include_once( dirname( __FILE__ ) . '/inc/kirki/kirki.php' );
/**
 * Change the URL that will be used by Kirki
 * to load its assets in the customizer.
 */
function kirki_update_url( $config ) {

    $config['url_path']     = get_stylesheet_directory_uri() . '/inc/kirki/';
    $config['color_accent'] = '#00bcd4';
    $config['color_back']   = '#455a64';
    return $config;

}
add_filter( 'kirki/config', 'kirki_update_url' );
```

Cheers :)
