### ISSUE TITLE
Request: add option to change when inline css is outputted

### ISSUE THREAD

**Issue by colmtroy** [themeum/kirki#265]
Hey, super work on kirki!

I have an output array as follows

```
        'output'      => array(
            array(
                'element'  => 'body, body p, .cg-entry-title',
                'property' => 'font-family',
            )
        )
```

I'm also using a very common css reset in my main theme style.css which contains a css reset for the body font family.

```
body {
  border: 0;
  font-family: inherit;
  font-size: 100%;
  font-style: inherit;
  font-weight: inherit;
  margin: 0;
  outline: 0;
  padding: 0;
  vertical-align: baseline;
}
```

Because the inline style is called BEFORE style.css (containing the reset), my custom Google font is not loaded on body. I actually end up seeing Times New Roman because the inherit value comes after the custom font family.

I can see this being a big issue for anyone who uses css resets (which is probably 99% of all websites). 

I know in Redux this isn't an issue as the inline css is the last thing added before the </head> closes. 

Is there any way to change when the inline css is called?

Colm

**Comment by HongPong** [comment]
I have a suggestion to add a parameter to add !Important to the output array, which would help work around some of these type of issues. I took a spin at implementing this but didn't pull it off.

**Comment by colmtroy** [comment]
@HongPong shouldn't need to use !important for something like this - that's a slippery slope :)

I know I could always just output the value manually myself rather than using the output parameter but I'm hoping there's a way to avoid having to do that.

**Comment by HongPong** [comment]
I sympathize, but I would also like to have a more versatile output command. I noticed there is also a media query parameter undocumented as yet, but I'm not sure of its syntax.

**Comment by aristath** [comment]
I'm planning to add that as well....
Not exactly an argument for !important, but one for prefix and another for suffix.
I'll be working on that after I finish with #262 and #263 which are my priority atm.

**Comment by aristath** [comment]
@edbloom I haven't tested if this works, but theoretically you could simply remove the action that adds the script and then re-add it using a different priority.
Perhaps something like this would work:

``` php
/**
 * This function should remove an action and then add it with a priority of 999
 *
 * The styles are added in the Kirki_Styles_Frontend class.
 * We can access the object using Kirki()->styles['front']
 */
function change_kirki_styles_priority() {
    $styles = Kirki()->styles;
    remove_action( 'wp_enqueue_scripts', array( $styles['front'], 'frontend_styles' ) );
    add_action( 'wp_enqueue_scripts', array( $styles['front'], 'frontend_styles' ), 999 );
}
add_action( 'after_setup_theme', 'change_kirki_styles_priority' );
```

**Comment by colmtroy** [comment]
@aristath thanks for the suggestion - unfortunately I don't think that will work because it's actually the inline styles that are appearing too early

this file: https://github.com/reduxframework/kirki/blob/master/includes/class-kirki-styles-frontend.php
line 30 `add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_styles' ), 150 );`

Would the fact that I'm using kirki as a plugin rather than embedded impact this?
I had to switch to plugin mode because of this https://github.com/reduxframework/kirki/issues/264

**Comment by aristath** [comment]
@edbloom if you change 150 to 999 does it work for you?
Nah, it shouldn't play any role that you're using it as a plugin...

**Comment by colmtroy** [comment]
@aristath nope - tried that too :)

this might not be the cleanest but this kind of works. My main style.css has a handler associated with it (I always set one just in case) so I was able to enqueue your frontend styles to my main style.css as follows)

```
function change_kirki_styles_priority() {
    $styles = Kirki()->styles;
    remove_action( 'wp_enqueue_scripts', array( $styles['front'], 'frontend_styles' ) );
    wp_enqueue_style( 'kirki-styles', trailingslashit( kirki_url() ).'assets/css/kirki-styles.css', array( 'shiopa-style' ), null );
}
add_action( 'after_setup_theme', 'change_kirki_styles_priority' );
```

only problem now is that it's duplicating the values :)

**Comment by colmtroy** [comment]
@aristath actually..

changing the core file as follows does the trick

```
class Kirki_Styles_Frontend {

    public function __construct() {

        add_action( 'wp_enqueue_scripts', array( $this, 'frontend_styles' ) , 999 );
        add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_styles' ), 999 );

    }
```

Both need 999

Might I suggest this gets added to core? 

I think it's logical for css output to come after the themes main stylesheet. :)

**Comment by aristath** [comment]
@edbloom yup, it makes sense.
Can you submit a pull-request?
I'd be more than happy to merge it. :)

**Comment by aristath** [comment]
@edbloom I just added a new `styles_priority` argument to the config, you can use that to use a priority of 999. :+1:

**Comment by colmtroy** [comment]
@aristath excellent stuff! never got around to the pull request - and your solution is much better :)
