### ISSUE TITLE
Static method not work with select

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#267]
Hello,
We use latest version of kirki but select type not working with static method but it work with kirki/fields filter.
This work:

``` php
$fields[] = array(
    'type'        => 'select2',
    'settings'    => 'select_demo_2',
    'label'       => __( 'Select2', 'kirki' ),
    'section'     => 'controls_with_choices',
    'default'     => 'Open Sans',
    'priority'    => 10,
    'choices'     => Kirki_Fonts::get_font_choices(),
    'output'      => array(
      array(
        'element'  => 'body',
        'property' => 'font-family',
      )
    )
  );
```

This not work

``` php
Kirki::add_field('infinity', array(
  'type'     => 'select2',
  'setting'  => 'site_style_body_font_family',
  'label'    => __('Font Family', 'kirki'),
  'section'  => controls_with_choices,
  'priority' => 10,
  'default'  => 'Open Sans',
  'choices'  => Kirki_Fonts::get_font_choices(),
  'output'   => array(
    'element'  => 'body',
    'property' => 'font-family',
  ),
));
```

When I choose new font, only kirki/fields filter work, static method not save the value in customizer
Thanks for looking into it.

**Comment by aristath** [comment]
When you say "latest version", which version do you mean exactly?
Can you please download the master branch from this repository and test again?

**Comment by ghost** [comment]
Yes, I always pull latest change from master branch of this repo but the bug not fix, you can test by yourself

**Comment by aristath** [comment]
Thanks for verifying this, I'll take a look. :)

**Comment by aristath** [comment]
@vunamhung On the static method, I'm also assuming you've added the infinity configuration somewhere too, right?
So you should have somewhere something like `Kirki::add_config( 'infinity', array(.....) );`
Can you please post your configuration here as well so that I may try to replicate your issue?
Thanks.

**Comment by ghost** [comment]
yes, this my config

``` php
Kirki::add_config('infinity', array(
  'options_type' => 'theme_mod',
  'capability'   => 'edit_theme_options',
));
```

**Comment by aristath** [comment]
Hey again, I just tested this:
In the twentyfifteen theme, I added this in the `inc/customizer.php` file:

``` php
Kirki::add_config('infinity', array(
    'options_type' => 'theme_mod',
    'capability'   => 'edit_theme_options',
) );
Kirki::add_field('infinity', array(
    'type'     => 'select2',
    'setting'  => 'site_style_body_font_family',
    'label'    => __('Font Family', 'kirki'),
    'section'  => 'colors',
    'priority' => 10,
    'default'  => 'Open Sans',
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output'   => array(
        'element'  => 'body',
        'property' => 'font-family',
    ),
) );
```

The control was added to the "Colors" section and when I saved it there were no issues.
Everything seems to be working fine...

The only issue I see with your code is that you've defined the section as `controls_with_choices` can you please try with `'controls_with_choices'` (with quotes) and see if that works?

**Comment by ghost** [comment]
Hello,
I detect the problem, the select type is not work but select2 type is work
This work
Kirki::add_field('infinity', array(
    'type'     => 'select2',
    'setting'  => 'site_style_body_font_family',
    'label'    => __('Font Family', 'kirki'),
    'section'  => 'colors',
    'priority' => 10,
    'default'  => 'Open Sans',
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output'   => array(
        'element'  => 'body',
        'property' => 'font-family',
    ),
) );
but this not work
Kirki::add_field('infinity', array(
    'type'     => 'select',
    'setting'  => 'site_style_body_font_family',
    'label'    => __('Font Family', 'kirki'),
    'section'  => 'colors',
    'priority' => 10,
    'default'  => 'Open Sans',
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output'   => array(
        'element'  => 'body',
        'property' => 'font-family',
    ),
) );

I just tested with twentyfifteen theme

**Comment by aristath** [comment]
Fixed in https://github.com/reduxframework/kirki/commit/b404fa378765f01086c5df5c0c7de44b9d317eca
There was an issue with the sanitization of select controls, thank you for reporting this. :)

**Comment by ghost** [comment]
Thank you, it work great again
