### ISSUE TITLE
Kirki::get_option only return default values for background controls

### ISSUE THREAD

**Issue by endcoreCL** [themeum/kirki#269]
``` php
$bo_bg = Kirki::get_option( 'bo_bi' );
print_r($bo_bg);
```

returns

```
Array
(
    [color] => #f0f0f0
    [image] =>
    [repeat] => no-repeat
    [size] =>cover
    [attach] =>fixed
    [position] => left-top
)
```

but there is another color and a image set.

**Comment by aristath** [comment]
So I'm guessing `bo_bi` is a background control?
Have you tried getting the values of its individual sub-fields?
Try for example `$bo_bg = Kirki::get_option( 'bo_bi_color' );`
Are you using options or theme_mods on that field?
Can you pelase post a copy of the code you use to add that field, and also your kirki configuration?

**Comment by endcoreCL** [comment]
hey aristath,

here my configuration

``` php
add_filter( 'kirki/config', 'at_customizer_config' );
function at_customizer_config() {
    $args = array(
        'url_path'          => get_template_directory_uri() . '/library/plugins/kirki/core/',
    );

    return $args;
}
```

and here my field

``` php
$fields[] = array(
        'type'        => 'background',
        'setting'     => 'bo_bi',
        'label'       => __( 'Main Background', 'kirki' ),
        'section'     => 'general',
        'default'     => array(
            'color'    => '#f0f0f0',
            'image'    => '',
            'repeat'   => 'no-repeat',
            'size'     => 'cover',
            'attach'   => 'fixed',
            'position' => 'left-top',
        ),
        'priority'    => 10,
);
```

a quickfix (thx) works

``` php
$bo_bg = Kirki::get_option( 'bo_bi_image' );
```

so im getting the right value.

**Comment by aristath** [comment]
ok, so the problem is focused on the background fields, thanks for checking!

**Comment by endcoreCL** [comment]
thanks for help ;-)

**Comment by aristath** [comment]
Changed the title of this issue to "Kirki::get_option only return default values for background controls" to make this more specific.

**Comment by aristath** [comment]
This was more complicated than I originally thought... But it's fixed now.
You can now use the `Kirki::get_option()` method for background fields as well. :+1:
