### ISSUE TITLE
postMessage for reloading changes asynchronously 

### ISSUE THREAD

**Issue by jovethgallardo** [themeum/kirki#27]
I read in the Customizer API that in order for the JS Handler script for asynchronously reloading to work, the argument:  

```
     'transport' => 'postMessage'
```

needs to be passed when registering a setting.  However, since kirki plugin got rid of the need to register settings, how can I add postMessage reloading so I can get realtime editing to work.  Than you

**Comment by Jursdotme** [comment]
I would like to know this aswell. Passing a transport argument to the controls array doesn't seem to do anything.

**Comment by aristath** [comment]
Hey there! This has just been fixed. :+1: 
You can use transport like you normally would.

**Comment by Jursdotme** [comment]
I understand what you did there but i can't for the life of me not get this to work. This is the right way to do it right?

``` php
$controls[] = array(
          'type'     => 'slider',
          'transport' => 'postMessage',
          'setting'  => 'h' . $value . '_spacing',
          'label'    => __( 'Space below', 'secondthought' ),
          'section'  => 'h' . $value . '_section',
          'default'  => 25,
          'priority' => 1,
          'choices'  => array(
                    'min'  => 1,
                    'max'  => 60,
                    'step' => 1,
          ),
);
```

I have even tried to change your last commit like so:

``` php
'transport'   => isset( $control['transport'] ) ? $control['transport'] : 'postMessage',
```

and even this:

``` php
'transport'   => 'postMessage',
```

But the page still refreshes.

**Comment by aristath** [comment]
That's weird...

Did you also add the necessary js in your theme as per the instructions on [Otto's post on how to leverage the theme customizer](http://ottopress.com/2012/how-to-leverage-the-theme-customizer-in-your-own-themes/)?

Perhaps we should add some more arguments that will automate this somehow and allow automatically generating the script...

**Comment by Jursdotme** [comment]
I have the beginnings of a javascript for the realtime updating. But i was under the impression that using `postMessage` would disable the page refresh whether you add a script or not.

At any rate i have the script loading like so:

``` php
function secondthought_customizer_live_preview() {

  wp_enqueue_script(
  'secondthought-theme-customizer',
  get_template_directory_uri() . '/build/scripts/theme-customizer.js',
  array( 'jquery', 'customize-preview' ),
  '1.0.0',
  false
);

}
add_action( 'customize_preview_init', 'secondthought_customizer_live_preview' );
```

**Comment by aristath** [comment]
ok. Let me experiment with that and debug it a bit...

I'm re-opening this issue.
As soon as I have an update I'll post back here. :smiley:

**Comment by jovethgallardo** [comment]
Actually it worked by adding :  'transport'   => isset( $control['transport'] ) ? $control['transport'] : 'refresh'                     

So here's what you do with your js:
1.  Create a .js file with this in it:

( function( $ ) {

```
    //Update site background color...
wp.customize( 'your_control_id', function( value ) {
    value.bind( function( newval ) {
        $('body').css('background-color', newval );
    } );
} );

    //More of arguments go here
```

} )( jQuery );
1. Open kirki.php and 'wp_enqueue_script()' the .js file you just created with the correct path.

And as soon as you add 'transport' => 'postMessage' to your control it should work.

Cheers!

**Comment by jovethgallardo** [comment]
Seems like I jumped the gun  on this issue... I was testing the color setting and it works... but it only works on the first change of color... I don't know what is happening but it seems that the first time you change color it will do it live, but as soon as the page refreshes, the transport goes back to 'refresh' mode

**Comment by aristath** [comment]
I'm trying to auto-generate the necessary scripts... 
First implementation was just commited on https://github.com/presscodes/kirki/commit/b2f0f0fe60aae9333ad30be3885d4c352dc359af

Though not 100% functional yet, it's a start.

@jovethgallardo did you manage to make any progress with this issue?
So far I was unable to resolve it...

@gad2103 any insights on this issue? We could really use your help here...

**Comment by gad2103** [comment]
hey guys. i haven't looked at the code for kirki in a little while. but @aristath by looking at your code in the commit, i would change some things:

```
<script type="text/javascript">
  jQuery(document).ready(function( $ ) {
  <?php 
    $controls = apply_filters( 'kirki/controls', array() );
    foreach ( $controls as $control ) :
      if ( 'postMessage' == @$control['transport'] && @$control['js_vars'] ) : 
  ?>
     wp.customize("<?php echo $control['setting']; ?>",function( value ) {
         value.bind(function(to) {
                 $("<?php echo $control['js_vars']['element']; ?>").<?php echo $control['js_vars']['type']; ?>("<?php echo $control['js_vars']['property']; ?>", to ? to : '' );
         });
      });
      <?php endif; ?>
  <?php endforeach;?>
});
</script>
```

right now you are adding a new document ready listener for each control. you only need one with all of the controls inside of it. 

what exactly isn't working?

**Comment by gad2103** [comment]
@aristath could you post an example of what the `$control['js_vars']` array would look like? i'm trying to see exactly what the output of this `$("<?php echo $control['js_vars']['element']; ?>").<?php echo $control['js_vars']['type']; ?>("<?php echo $control['js_vars']['property']; ?>", to ? to : '' );` line would be

**Comment by aristath** [comment]
I was thinking something like this example color field:

``` php
$controls[] = array(
    'type'      => 'color',
    'setting'   => 'my_setting',
    'label'     => __( 'My Setting', 'textdomain' ),
    'section'   => 'my_section',
    'default'   => '#1abc9c',
    'priority'  => 1,

    'transport' => 'postMessage',
    'js_vars'   => array(
        'element'  => '#my-div',
        'type'     => 'css',
        'property' => 'color',
    )
);
```

That would have as a result this js:

``` js
jQuery(document).ready(function( $ ) {
    wp.customize("my_setting",function( value ) {
        value.bind(function(to) {
            $("#my-div").css("color", to ? to : '' );
        });
    });
});
```

**Comment by gad2103** [comment]
are you getting console errors? or just nothing working? also is this being loaded with the 'customize_preview_init' hook?

**Comment by aristath** [comment]
No errors, just doesn't work and I'm adding it to `customize_controls_print_footer_scripts`
Sorry for bugging you with this man, I'm just no good when it comes to js.

**Comment by gad2103** [comment]
do you have an install with the latest version of the plugin i can look at? if so, can you shoot me an email with the details and i can do some debugging?

i'm pretty sure you are supposed to hook into the  `customize_preview_init` action.

**Comment by Jursdotme** [comment]
Any update on this?

**Comment by jovethgallardo** [comment]
So I added this:

'transport'   => isset( $control['transport'] ) ? $control['transport'] : '',

after line 66 in controls-init.php file and it seems to work. ..
I also made sure that my controls/settings had the: transport=> 'postMessage' ... and like gad2103 mentioned... you are supposed to hook to "customize_preview_init" action

**Comment by aristath** [comment]
fixed in https://github.com/presscodes/kirki/commit/2cf31494f7de38f54f4cc8031ff6a06ab55f5c35

**Comment by shamimbdpro** [comment]
i'm also fetching same issues for only text. color changing is working fine `
