### ISSUE TITLE
Allowing html in text, textarea and possible bug with editor field type

### ISSUE THREAD

**Issue by colmtroy** [themeum/kirki#270]
Hey there! 
me again :) 

I added a simple link to both a text and textarea field. The markup is not stripped upon saving (cool!) but the frontend output is outputting the link as html. My guess might be that this is appropriate behaviour but that I should wrap the frontend output in some WordPress encoding function - correct?

I then tested the editor fieldtype. I see a potential bug here. The html is stripped upon saving - which I think is a bug, given the editor field allows users to add links via the UI buttons. Is there another parameter required to allow html or is this a bug?

**Comment by aristath** [comment]
If no `sanitize_callback` is defined for the field then we use some sane defaults.
The `text`, `textarea` and `editor` fields all use the `esc_textarea` function for their sanitization. (this is applied on https://github.com/reduxframework/kirki/blob/7b96ee2c5cd4d4d779453175fe083cf17e2a219a/includes/class-kirki-field.php#L683-L687 )

You can use your own function there if a field requires special handling, so adding for example this in your field would make anything you enter be used completely unfiltered:

``` php
'sanitize_callback' => array( 'Kirki_Sanitize', 'unfiltered' ),
```

or use any of the functions listed on https://codex.wordpress.org/Data_Validation
If for example it were a text field where you allow your users to enter a URL, then you could use

``` php
'sanitize_callback' => 'esc_url_raw',
```

**Comment by colmtroy** [comment]
@aristath perfect :) I wrote my own simple sanitizer to allow some basic html - thanks!

**Comment by aristath** [comment]
I'm glad I could help!
Closing this issue. :+1:
