### ISSUE TITLE
Fields not working with the same $config_id

### ISSUE THREAD

**Issue by ghoshnirmalya** [themeum/kirki#274]
I've added the configuration using this code

<pre><code>Kirki::add_config( 'mk', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'option',
    'option_name'   => 'mk',
) );</code></pre>

Now, when I try to integrate <a href="https://github.com/aristath/kirki/wiki/Google-Fonts-Integration">Google Fonts</a> using the code below, the font scripts are not added to the header:

<pre><code>Kirki::add_field( 'mk', array(
    'type'     => 'select',
    'setting'  => 'style_fonts_family_setting',
    'label'    => __( 'Font Family', 'kirki' ),
    'section'  => 'style_fonts',
    'default'  => 'Roboto',
    'priority' => 20,
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output' => array(
        'element'  => '.post-entry-meta h2 a',
        'property' => 'font-family',
        'units'    => ' !important'
    ),
) );</code></pre>

But, when I remove the $config_id which is 'mk' in this case, it works fine i.e. by keeping the $config_id blank or using any other name (like 'kirki_demo').

This same thing happens with <code>'type'=> 'color'</code>.

Everything else which I've used (text, image types) works perfectly with the same $config_id. Working code for an <code>image</code> type is as below:

<pre><code>Kirki::add_field( 'mk', array(
    'settings' => 'layout_front_page_slider_image_one_setting',
    'label'    => __( 'First image of the slider', 'kirki' ),
    'section'  => 'layout_front_page',
    'type'     => 'image',
    'priority' => 10,
    'default'  => '',
) );</code></pre>

**Comment by aristath** [comment]
Hey there!

So this only happens with color controls & when using google-fonts?
When you change the values of these controls, are your settings properly saved?

**Comment by ghoshnirmalya** [comment]
Hi!

I've uploaded the theme on Github. You can have a look at the <a href="https://github.com/ghoshnirmalya/Magnificient_kirki/blob/master/library/theme-options.php#L293-L389">theme-options.php</a> where all the options have been added.

<b>Note:</b>
I have highlighted the lines which are causing the problem.
