### ISSUE TITLE
Type editor not working

### ISSUE THREAD

**Issue by ghoshnirmalya** [themeum/kirki#275]
I am using the <code>editor</code> type using the following code:

<pre><code>Kirki::add_field( 'mk', array(
    'type'        => 'editor',
    'setting'     => 'footer_editor_text_setting',
    'label'       => __( 'Edit the footer editor text', 'kirki' ),
    'section'     => 'footer_editor_text',
    'default'     => __( 'This is some default text', 'kirki' ),
    'priority'    => 10,
) );</code></pre>

I am providing the output using the code below:

<pre><code>if ( Kirki::get_option( mk, footer_editor_text_setting ) ) {
    $footer_editor_text = Kirki::get_option( mk, footer_editor_text_setting );
    echo $footer_editor_text;
}</code></pre>

However, when I am making some changes inside the wysiwyg text editor in the customizer, no changes are occurring. Only the default text is shown which doesn't change on editing from the editor. Also, the <code>save</code> button of the customizer remains in a <strong>disabled</strong> state as if no changes were made in the customizer.

**Comment by aristath** [comment]
Is this the only `editor` field you have in your theme?
There's currently an issue that breaks editors when there's more than 1 present...

**Comment by ghoshnirmalya** [comment]
Hi!

I've uploaded the theme on Github. You can have a look at the <a href="https://github.com/ghoshnirmalya/Magnificient_kirki/blob/master/library/theme-options.php#L267-L275">theme-options.php</a> where all the options have been added.

<b>Note:</b>
I have highlighted the lines which are causing the problem.

<b>Is this the only editor field you have in your theme?</b>
Yes

**Comment by fovoc** [comment]
Hey there,

can you please try pulling and testing again? I think I resolved that in 655fffccadda68eeb0bd58ce5788e1d2ded443a3.

Please advise,
Dimitris

PS. I haven't taken a look of your theme yet

**Comment by ghoshnirmalya** [comment]
Hi,

The <code>save</code> button still remains in a <strong>disabled</strong> state even after I write something inside the editor.

**Comment by fovoc** [comment]
Is this still happening in Visual or Text mode?

I had the same mis-functionality under Visual mode whether the Text mode was working as should be...

**Comment by ghoshnirmalya** [comment]
I've tried both but it's not working in either of them. I had removed the editor type from the theme but you can surely check that by adding that option in the theme.

Thanks.

**Comment by fovoc** [comment]
As I was using the sample configuration to test, can you try adding the field with a filter instead like https://github.com/aristath/kirki/blob/master/sample-config.php#L350-L358
to see if this remains?

**Comment by ghoshnirmalya** [comment]
I will try and let you know.

**Comment by ghoshnirmalya** [comment]
It didn't do anything. You can still see that the <strong>save</strong> button is still <strong>disabled</strong> even if I write something.

![1](https://cloud.githubusercontent.com/assets/6391763/8715116/cc4ad9c6-2b9a-11e5-9f7d-7e12733f4ce6.png)
![2](https://cloud.githubusercontent.com/assets/6391763/8715117/cc4c69b2-2b9a-11e5-8ff6-51ec2fc8d52d.png)

I used the following code:

<pre><code>function kirki_text_controls_fields( $fields ) {  
    $fields[] = array(
        'type'        => 'editor',
        'settings'    => 'wysiwyg',
        'label'       => __( 'Editor', 'kirki' ),
        'default'     => '',
        'section'     => 'footer_custom',
    );  
return $fields;
}
add_filter( 'kirki/fields', 'kirki_text_controls_fields' );</pre></code>

**Comment by fovoc** [comment]
Hey there,

I used your theme and I get lots of errors. Can you try to resolve these and test again Kirki's controls? I'm really unable to replicate it in my end but your theme seems not to save the tinyMCE editor indeed...

Please advise,
Dimitris

**Comment by ghoshnirmalya** [comment]
Hello,

Can you please tell me what errors are you getting while using my theme?

**Comment by aristath** [comment]
set WP_DEBUG to true in your wp-config.php file and you'll see them... 
There are lots of issues!
Example: This line https://github.com/ghoshnirmalya/Magnificient_kirki/blob/master/header.php#L26
Should be

``` php
$custom_css = Kirki::get_option( 'mk', 'style_custom_css_setting' );
```

instead of

``` php
$custom_css = Kirki::get_option( mk, style_custom_css_setting );
```

**Comment by ghoshnirmalya** [comment]
Thanks. I will rectify them asap.

**Comment by ghoshnirmalya** [comment]
Hello,

I've updated the theme at <a href="https://github.com/ghoshnirmalya/Magnificient_kirki">Magnificient_kirki</a>.

I'm still having issues like this one:

<code>Notice: Undefined index: style_fonts_family_setting in C:\Program Files (x86)\Ampps\www\wptheme\wp-content\themes\magnificient_kirki\kirki\includes\class-kirki.php on line 131</code>

I've modified all codes similar to <code>$custom_css = Kirki::get_option( mk, style_custom_css_setting );</code> which should be <code>$custom_css = Kirki::get_option( 'mk', 'style_custom_css_setting' );</code>

Can you please help? (I know that this is not the topic of this issue, still!)

<strong>Please not that I'm using the latest version of Kirki available at the time of posting this comment</strong>.

**Comment by ghoshnirmalya** [comment]
The theme is working perfectly with no errors thanks to Aristath. However, the editor ins't working still!

**Comment by ghoshnirmalya** [comment]
Any update on the editor not-saving issue?

**Comment by aristath** [comment]
Hey there!
Can you try this one again?

I just tested it with the latest commits and this seems to be working fine now.

**Comment by aristath** [comment]
Closing this ticket due to inactivity.
If you pull the latest changes from the master branch it seems to be working.
If it doesn't work for you then please feel free to reopen this and post an update on your current status with as many details as possible.

Cheers,
Ari.

**Comment by ashrafbd1496** [comment]
Hello @aristath , Still editor is not working
