### ISSUE TITLE
WP_ADD_INLINE_STYLE

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#276]
Great work here, thank you for the big effort. I started using Kirki recently, so maybe I'm missing something, but I would like to know how to remove the custom styles from the front end: I don't use the font selector since I developed a different system and I tried to dequeue the styles without success:

``` php
wp_deregister_style('kirki-styles'); 
```

or

``` php
wp_dequeue_style('kirki-styles');
```

or

``` php
remove_action( 'wp_enqueue_scripts', array( 'Kirki_Styles_Frontend', 'enqueue_styles' ) );
```

Nothing seems to work... what's the best way? TIA, Manuel :-)

**Comment by aristath** [comment]
Try this:

``` php
add_action( 'wp_enqueue_scripts', function() {
    remove_action( 'wp_enqueue_scripts', array( Kirki()->styles['front'], 'enqueue_styles' ) );
}, 999 );
```

**Comment by fovoc** [comment]
Hey there,

try using
`remove_action( 'wp_enqueue_scripts', array( $kirki->styles['front'], 'enqueue_styles' ), 150 );`

the action that enqueues the styles: https://github.com/aristath/kirki/blob/master/includes/class-kirki-styles-frontend.php#L32
the class instantiation: https://github.com/aristath/kirki/blob/master/kirki.php#L77

**Comment by pixedelic** [comment]
Thank you, but no way, tried everything. I could leave it there, but it is a non necessary request and, most of all, it prints on the head

``` html
<style id='kirki-styles-inline-css' type='text/css'>
p{background-image:url("Array");}
</style>
```

Don't know, maybe it depends on something I have saved during some tests...

**Comment by aristath** [comment]
hmmm..
Try this then:

``` php
add_action( 'after_setup_theme', function() {
    Kirki()->styles = array(
        'back'  => new Kirki_Styles_Customizer(),
        'front' => null,
    );
} );
```

That should completely disable the `Kirki_Styles_Frontend` class.

**Comment by pixedelic** [comment]
Thank you for the help, really appreciate, but unfortunately it duplicates the output:

``` html
<style id='kirki-styles-inline-css' type='text/css'>
p{background-image:url("Array");}
p{background-image:url("Array");}
</style>
```

**Comment by aristath** [comment]
Is your theme perhaps on github so that I may download it and take a look?

**Comment by aristath** [comment]
I just added 2 new arguments to the configuration:
https://github.com/aristath/kirki/commit/7eb2fc90f15deb6870b1ce2bc6cbf068d4a0e1a7
Please try using these. :)

**Comment by pixedelic** [comment]
Great thank you! I was trying to add the implementation I made to a Tweentyfifteen child theme to let you see, but I'll test the new options. You're a star!

**Comment by pixedelic** [comment]
Ok, tried as you suggested:

``` php
add_filter('kirki/config', 'disable_inline_css');
function disable_inline_css(){
    $args = array(
        'disable_google_fonts'   => true,
        'disable_output'   => true,
    );

    return $args;

}
```

But it only breaks the URL of kirki-styles.css... am I doing something wrong? Here is the customizer I implemented on a Twentyfifteen child theme, thank you in advance if you will have the patience to take a look to it: https://github.com/pixedelic/twentyfifteen-child

**Comment by pixedelic** [comment]
No, my bad, still using kirki 1.0.1!!! Many apologies!

**Comment by pixedelic** [comment]
No way, same error with 1.0.2, it prints both kirki-style.css with a wrong path and the inline style... sorry for the multiple messages

**Comment by aristath** [comment]
Hey again!

This last commit fixes the new args, they're working fine now. :)

**Comment by pixedelic** [comment]
Thank you! They work like a charm! Great work, really.

**Comment by pixedelic** [comment]
Hello, just updated to v.2.0.0... have you removed the fix above? I can't dequeue the css file with the same filter. Thank you.

**Comment by aristath** [comment]
It's still there... https://github.com/aristath/kirki/blob/2.0/includes/styles/class-kirki-styles-frontend.php#L34-L36

hmmmm... can you please try if changing the `!==` to `==` on [this line](https://github.com/aristath/kirki/blob/2.0/includes/styles/class-kirki-styles-frontend.php#L34) fixes this?

**Comment by manuelmoreale** [comment]
Hi there.
Same problem here.
Currently using 2.0.7 and trying to remove both the `kirki-styles-css` and the inline style containing `body.wp-customizer-unloading` among other things that for my understanding should only be loaded in the customizer but for some reason is always present in the `<head>`
I tried, as @aristath suggested, changing the `!==` to `==`without luck. Looks like the `$config['disable_output']` gets completely ignored.
The only way i found to prevent the `kirki-styles-css` from being included is to remove this line completely `add_action( 'wp_enqueue_scripts', array( $this, 'inline_dynamic_css' ), $priority );` which is obviously not ideal.
As for the other inline style I'm still looking for a solution.

**Comment by aristath** [comment]
@pixedelic better late than never...
I just added support for a `KIRKI_NO_OUTPUT` constant. (currently in the `develop` branch, soon in the next release.
So if you want to completely disable CSS output, all you have to do is add this somewhere:

``` php
define( 'KIRKI_NO_OUTPUT', true );
```

@manuelmoreale the `body.wp-customizer-unloading` issue has been fixed in the last release. The next one in a few days will include the `KIRKI_NO_OUTPUT` constant mentioned above.

**Comment by pixedelic** [comment]
@aristath thank you man!

**Comment by aristath** [comment]
Just an update here:
Since I added `KIRKI_NO_OUTPUT` I've been thinking that doing so was a mistake...
I'm not going to remove it, but using it would mean that output from all plugins & themes using Kirki would be disabled in case one of them decided to use it.
So this is going to remain implemented but only used for debugging purposes.
Instead of that, if you want to disable output for your specific product, you can now add the `disable_output` argument in your config:

``` php
Kirki::add_config( 'my_theme', array(
    'capability'     => 'edit_theme_options',
    'option_type'    => 'theme_mod',
    'option_name'    => '',
    'disable_output' => true,
) );
```

We no longer enqueue a `kirki-styles` stylesheet.
Instead, each product has its own stylesheet (in the above example it would be `kirki-styles-my_theme`, but it won't be added 'cause `disable_output` is set to true there).
This way they can act independently and not affect each other.
