### ISSUE TITLE
kirki/config filter stopped working

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#278]
Hey Ary,

Just a heads up, the latest update to Kirki seems to have broken the `kirki/config` filter.
I was just looking back into this to send you the small issue we've discussed last week.

Cheers.

**Comment by aristath** [comment]
Hey there!

I just tested it and it seems to be working fine...
What is it that doesn't work for you?

**Comment by lmartins** [comment]
That's weird.
Im just applying some simple changes:

``` php
function kirky_panels_style( $config ) {

    $config['color_accent'] = '#00bcd4';
    $config['color_back']   = '#475969';
    $config['width']        = '20%';

    return $config;

}
add_filter( 'kirki/config', 'kirky_panels_style' );
```

And the customiser just went to the default style after upgrading Kirki. I was using 1.0.0 before and it was running ok. I'll post it here if I found out why did it stopped working for me.

I'll close this for now.

**Comment by InfinitumForm** [comment]
I have same experience here:

```
function kirki_ge_configuration($config) {
	return wp_parse_args( array(
		'logo_image'   => _GE_THEME_URL . '/assets/images/ge-logo-white-200.png',
		'color_accent' => '#00bcd4',
		'color_back'   => '#455a64',
	), $config );
}

add_filter( 'kirki_config', 'kirki_ge_configuration' );
```

Any idea why?
