### ISSUE TITLE
Feature Request: Presets

### ISSUE THREAD

**Issue by tomtev** [themeum/kirki#279]
Hi there,

Is it possible to create a field that lets you Save and Open 'presets' of all the options.
That would be great for theme developers to include various preset styles of the theme,
or let the user save current options as a preset.

This could also be used by Agencies to display multiple variations of a theme to a client for approval.
I made something quick and dirty based on this that worked:

```
$('img.kirki_image_preset').click(function() {
        var api = wp.customize;
        var data = $( this ).data( 'options' );

        if ( typeof data !== 'undefined' ) {
            $.each( data, function( id, value ) {
                console.log(id);
                console.log(value);
                var setting = api( id );
                if(setting){
                    setting.set( value );
                }
            } );
        }
        api.previewer.refresh();
    } );
```

The img.kirki_image_preset was just a image with a option array inside data-option="".

**Comment by ghost** [comment]
NICE... +1

**Comment by ghost** [comment]
That's nice idea, many developer need it.

**Comment by tomtev** [comment]
Any news? :) I can see that Redux Customizer has this.

**Comment by aristath** [comment]
Hey guys, just an update on this one.
We'll be building a "preset" control pretty soon.
@tomtev do you have something functional? If you do could you please submit a pull request?

**Comment by aristath** [comment]
Hey guys!

Just an update here.

I've started implementing this and it's semi-working.
By semi-working I mean that you can define presets like this:

``` php
Kirki::add_field( 'kirki_demo', array(
    'type'        => 'preset',
    'settings'    => 'preset_demo',
    'label'       => __( 'Preset control', 'kirki-demo' ),
    'description' => __( 'Bulk-changes the value of other controls.', 'kirki-demo' ),
    'section'     => 'select',
    'default'     => '1',
    'priority'    => 10,
    'multiple'    => 3,
    'choices'     => array(
        '1' => array(
            'label'    => __( 'Option 1', 'kirki-demo' ),
            'settings' => array(
                'select_demo'          => 'red',
                'select_multiple_demo' => array( 'option-1', 'option-2' ),
            ),
        ),
        '2' => array(
            'label'    => __( 'Option 2', 'kirki-demo' ),
            'settings' => array(
                'select_demo'          => 'green',
                'select_multiple_demo' => array( 'option-4', 'option-1' ),
            ),
        ),
    ),
) );
```

You can also see it in the demo theme: https://github.com/aristath/kirki/blob/cac7a24fc71308755dcf97c7227c77107a68d2b5/demo-theme/functions.php#L502-L527

When you change the value, the choices are bulk-changed and their values can be previewed.
However, what does not change is the value as seen in the controls themselves.

If someone can help out I'm sure a lot of us can use this control!

NOTE: For the time being this control is a select control, but as soon as we get the basics working I'm sure we'll be able to find a way to make it work with other control types as well.

The JS I used for this is here: https://github.com/aristath/kirki/blob/cac7a24fc71308755dcf97c7227c77107a68d2b5/assets/js/controls/preset.js

Any help is greatly appreciated. :+1:

**Comment by aristath** [comment]
Update: I tried making the control values update using this: https://github.com/aristath/kirki/blob/27e9997a0019d1cfd19492030fdb485f6675a6a8/assets/js/controls/preset.js#L30-L84 and failed miserably.
I feel I'm on the right track but my JS voodoo is pretty limited. :hankey:

**Comment by aristath** [comment]
Closing this one in favour of https://github.com/aristath/kirki/issues/393 so that we may better track the progress there.
