### ISSUE TITLE
Theme Customizer Sanitization

### ISSUE THREAD

**Issue by blackmekemeke** [themeum/kirki#28]
There is a problem with a required setting with the WordPress theme check plugin, this is the error that i get:

REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.

**Comment by venkatraj** [comment]
I second that.

**Comment by mennwebs** [comment]
I found this, too.

![problem](http://mennstudio.com/temp/kirki-1.png)

**Comment by aristath** [comment]
@blackmekemeke @venkatraj @MennStudio I can't replicate this...
Can you please post a code sample of what you're doing that gives you this error?

**Comment by venkatraj** [comment]
Embed 'Kirki' to custom theme and check with 'Theme Check' plugin. That throws the error.
New Theme Review Guidelines requires sanitization for each customizer settings.

The custom theme can be as simple as a child theme of Twenty Fifteen.

**Comment by aristath** [comment]
I just pushed a new commit that should fix this for you...
Can you please check that all your controls are still being saved?
I added sanitization calls and wrote some custom functions where needed.

You can always however write your own sanitization function wherever you want to override the default ones simply by adding

``` php
'sanitize_callback' => 'my_custom_function'
```

to your field definitions.

**Comment by mennwebs** [comment]
Thank you so much @aristath :)

**Comment by joshrcook** [comment]
@aristath - 

Would you mind adding this option to the documentation on kirki.org?

**Comment by aristath** [comment]
Yup, I'm planning to.

I'm working on some major changes as we speak that will fix a lot of bugs.
As soon as I push the new version up, I'll also update the docs. :)
