### ISSUE TITLE
Type background not working

### ISSUE THREAD

**Issue by ghoshnirmalya** [themeum/kirki#280]
I'm trying to implement the <strong>background</strong> type using the following code:

<pre><code>$controls[] = array(
        'type'        => 'background',
        'settings'    => 'foundationbuddy_custom_header_background',
        'label'       => __( 'Custom header background', 'foundationbuddy' ),
        'description' => __( 'Customize your header.', 'foundationbuddy' ),
        'section'     => 'foundationbuddy_custom_header_background_section',
        'default'     => array(
            'color'    => 'rgba(25,170,141,0.7)',
            'image'    => '',
            'repeat'   => 'no-repeat',
            'size'     => 'cover',
            'attach'   => 'fixed',
            'position' => 'left-top',
            'opacity'  => 100
        ),
        'priority'    => 10,
        'output'      => 'body > header.contain-to-grid',
    );</code></pre>

However, it's producing no output.

Moreover, the background field, which is supposed to look like this

![background](https://cloud.githubusercontent.com/assets/6391763/8769567/b2e67ab4-2ebd-11e5-8310-552765a66d06.gif)

looks like this

![untitled](https://cloud.githubusercontent.com/assets/6391763/8769576/dbdaf8b4-2ebd-11e5-91ab-b5c966656606.png)

and it is not providing any output. I'm using the latest version of Kirki.

Theme is present here: https://github.com/ghoshnirmalya/Infiword

**Comment by ghoshnirmalya** [comment]
Any further updates on this issue? Really need this feature.

**Comment by aristath** [comment]
Do you have another normal color control on your customizer (a `color` control and not `color-alpha`)?
If not then perhaps this is the issue (see https://github.com/aristath/kirki/wiki/color-alpha#known-issues)

**Comment by ghoshnirmalya** [comment]
After adding a normal color control, it works. However, the selection portion of the color doesn't show a dropdown to choose any color. 
![untitled](https://cloud.githubusercontent.com/assets/6391763/8851844/6ffe2eb8-316f-11e5-8a4f-70679ef3f398.png)

**Comment by aristath** [comment]
Please post to the github repository issues so that others can help resolve
the issues too, and so that everyone can learn from this.
I do not provide support via email. :)

Cheers,
Ari.

**Comment by ghoshnirmalya** [comment]
Okay :)

**Comment by PinkPandaAU** [comment]
I'm also having issues with the background field. When I try to assign the value to a variable (using the variable function), it only saves the default background-position eg. left-top and nothing else.

Any answers on this one yet?

**Comment by aristath** [comment]
@PinkPandaAU Can you please create a new issue for the variables?
We'll have to look into that... I don't think the background field can handle variables the way it is now... Please create a new ticket so that we may keep things a bit more organized.

**Comment by PinkPandaAU** [comment]
@aristath thanks a lot for getting back to me. Will do now. I tried to take a look at how I could make the value of the variable be a concatenation of each background field but I got lost along the way!

**Comment by aristath** [comment]
@ghoshnirmalya @PinkPandaAU Sorry I missed this ticket...
Do you guys still require assistance on this one?

**Comment by ghoshnirmalya** [comment]
This issue was resolved.
