### ISSUE TITLE
Allowing basic HTML in control description

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#283]
I remember this was possible in earlier versions:

``` php
$controls[] = array(
        'type'        => 'image',
        'settings'    => 'bkg_image',
        'label'       => __( 'Upload a background image', 'epico' ),
        'description' => __( 'You can find more examples <a href="http://site.com/images">here</a>', 'epico' ),
        'help'        => __( '<strong>Note:</strong> Keep size under 100Kb', 'epico' ),
        'section'     => 'basic',
        'default'     => '',
        'priority'    => 1,
    );
```

It's useful for pointing users to an external site or to format the description a little, for example.

**Comment by aristath** [comment]
@pagelab This was possible in previous versions, yes.
However some of our users had issues with the themes they were submitting on the wordpress.org repository and we had to do some aggressive sanitization in order for the themes to be able to go through the themes review process without any issues.
You can manually change it in your own implementation (it's this line: https://github.com/aristath/kirki/blob/67b81801028e9b423bd5f4b46d5808be810e6f21/includes/class-kirki-field.php#L441) but I'm afraid there's not much we can do on the official version...
