### ISSUE TITLE
Serialized options currently do not work.

### ISSUE THREAD

**Issue by briancwelch** [themeum/kirki#286]
As referenced here:
https://github.com/briancwelch/daphnee-maps/blob/master/includes/class-options.php#L38-L47

Setting the option name causes `Fatal error: Call to a member function check_capabilities() on null`

Commenting out the option name fixes it:

``` php
public function add_config() {
    Kirki::add_config( 'daphnee_maps_config', array(
        'option_type'    => 'theme_mod',
        'capability'     => 'edit_theme_options',
    ) );
}
```

**Comment by aristath** [comment]
@briancwelch hey buddy!

Can you please test if this still occurs or if it's been fixed?

**Comment by aristath** [comment]
I just tested all controls, this works perfectly fine now.
I'll go ahead and close this issue. If it persists then by all means feel free to reopen it! :)
