### ISSUE TITLE
Error: Invalid argument supplied for foreach() in wp-content/plugins/kirki/includes/class-kirki-fonts-font-registry.php on line 281 </code>

### ISSUE THREAD

**Issue by Zackio** [themeum/kirki#288]
Had anything experience this error message? its in relation to the code following. It happens intermittently when previewing a page.

<code>
Warning: Invalid argument supplied for foreach() in wp-content/plugins/kirki/includes/class-kirki-fonts-font-registry.php on line 281
</code>

```
kirki::add_field( '', array(
    'type'     => 'select2',
    'setting'  => 'base_typography_font_family',
    'label'    => __( 'Font Family', 'example' ),
    'section'  => 'base_typography',
    'default'  => 'Roboto',
    'priority' => 20,
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output'   => array(
        'element'  => 'body',
        'property' => 'font-family',
    ),
) );
```

**Comment by ghost** [comment]
Hi Zakio
To fix it please open file class-kirki-fonts-font-registry.php and go to line 276 and change
$wp_filesystem->get_contents
to
file_get_contents

**Comment by Zackio** [comment]
Thanks vunamhung,

Not had chance to make the changes yet.

**Comment by aristath** [comment]
@Zackio hey there!

Did you get around to making the above change?
Did it work for you?

Please advise,
Ari.

**Comment by Zackio** [comment]
Hi,

I removed the font options in the end. I've put it in my next project - just to test it but the error has yet to come up with or without the changes but it was very intermittent the error anyway. I'll leave the options in for now whilst I'm working to can see if it comes up again

**Comment by joseph-kuruvilla** [comment]
@aristath - Any update on this to fix the issue. thank you.

**Comment by padalec** [comment]
Hi there,
any update? I have the same notices

**Comment by Zackio** [comment]
I've switched to using easygooglefonts instead

**Comment by aristath** [comment]
Guys I think this has already been fixed...
I can't replicate it anymore.
Can you please verify this?

**Comment by Zackio** [comment]
I think do - it didn't come up when I was testing with or without the fix.

**Comment by aristath** [comment]
Awesome, thanks!
