### ISSUE TITLE
Dynamically adding controls?

### ISSUE THREAD

**Issue by khromov** [themeum/kirki#290]
Is there any way to dynamically add controls, kind of like how the Widget tab in the Customizer works? (ie. having a button called Add Widget, and allowing drag and drop between Widgets).

Something like that would be great to allow users to use the Customizer for page building.

**Comment by aristath** [comment]
Currently there's no way to do that.
I'm exploring ways to make that happen and there's another issue related to this one on https://github.com/aristath/kirki/issues/40
One of the main issues we're having with that is figuring out a way to create controls inside another control, and the format of the saved data.

I'll close this one as a duplicate, feel free to add your opinion and suggestions on #40.

Hopefully we'll figure this one out soon enough. :smile:

**Comment by khromov** [comment]
Thanks, I'll check it out!
