### ISSUE TITLE
Notice: Undefined Index class-kirki.php on line 102

### ISSUE THREAD

**Issue by nomi416** [themeum/kirki#294]
Hi!
I have integrated Kirki into my theme. I got the above mentioned notice when I set WP_DEBUG to true even for those fields where DEFAULT VALUE is set (not all are set).
Do I need to set the default value for all fields or is it a bug(accessing undefined array index without checking beforehand)?

I removed the notice by changing line 102:
    $value = get_theme_mod( $field_id, self::$fields[ $field_id ]['default'] );
to this:
         if(isset(self::$fields[ $field_id ]['default'])){
           $value = get_theme_mod( $field_id, self::$fields[ $field_id ]['default'] );
         }

**Comment by padalec** [comment]
I had the same situation. I fix this for set the default value for all fields. But better idea will be check the default value is set. Somthing like that:

``` php
<?php
$default = isset(self::$fields[ $field_id ]['default']) ? self::$fields[ $field_id ]['default'] : '';
$value = get_theme_mod( $field_id, $default );
?>
```

**Comment by nomi416** [comment]
I have two type of notices. One is
Notice: Undefined index: default 
which I understand is because I have not set default for those fields. And accessing the undefined array index will generate notice.
The second one is
Notice: Undefined index: FIELD_ID
which is strange. Because its says the field itself is not set. Accessing it DEFAULT INDEX comes later in this case.

**Comment by aristath** [comment]
@nomi416 hey there!

Sorry for the delay on this one...
Are you still having the issue above?
If you do could you please provide some more details?

**Comment by aristath** [comment]
All values should have a default value.
Cheers
