### ISSUE TITLE
Undefined index: kirki_test[...]  ===> class-kirki.php ===> line 102 & 108

### ISSUE THREAD

**Issue by hamdan-mahran** [themeum/kirki#296]
Hello Kriki
Thanks for this awesome plugin, i installed inside theme folder, and i follow all the steps, but i get the following errors.

<pre>
Notice: Undefined index: kirki_test[kirki_test[color-alpha_demo_5]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 102

Notice: Undefined index: kirki_test[kirki_test[color-alpha_demo_5]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 108

Notice: Undefined index: kirki_test[kirki_test[color_demo_5]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 102

Notice: Undefined index: kirki_test[kirki_test[color_demo_5]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 108

Notice: Undefined index: kirki_test[kirki_test[color-alpha_demo_2]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 102

Notice: Undefined index: kirki_test[kirki_test[color-alpha_demo_2]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 108

Notice: Undefined index: kirki_test[kirki_test[color_demo_2]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 102

Notice: Undefined index: kirki_test[kirki_test[color_demo_2]] in D:\xampp\htdocs\test1\wp-content\themes\theme_name\theme-admin\options\includes\class-kirki.php on line 108
</pre>

Thanks!

**Comment by aristath** [comment]
No worries, these are just from the dummy test data that you probably enabled.
The plugin itself is fine, the problem is with the script containing the test data.

**Comment by aristath** [comment]
We plan on rebuilding the test data, I just haven't had the time to do that yet.

I'm marking this as a bug and adding it to the tasklist for version 1.1 :+1:

**Comment by aristath** [comment]
fixed. We completely refactored the way demo data is handled.

**Comment by ghost** [comment]
Hi Aris.  I would like to test this.  How should i go about testing so i can post my results here?

**Comment by aristath** [comment]
The new tests work like this:

> To enable the demo theme, just add this line to your wp-config.php file:
> `define( 'KIRKI_CONFIG', true );`
> Once you add that line, you'll see a new theme in your dashboard called "Kirki Demo".
> Activate that theme to test all controls.

(inline docs [here](https://github.com/aristath/kirki/blob/e4b07139f0b732cc43125c1c5db948648778ec3d/kirki.php#L150-L155))
