### ISSUE TITLE
Fatal error: Class 'Kirki_Controls_Slider_Control' not found on line 306

### ISSUE THREAD

**Issue by ZmagoD** [themeum/kirki#299]
Hi arstath!
firstly congratulations for the Kirki toolkit, it is an amazing tool!

But I have a problem! Kirki throws me an error when I insert the slider field in the theme customizer
here is the code:

<pre>
include_once( dirname( __FILE__ ) . '/kirki/kirki.php' );

function my_blog_kirki_configuration( $config ) {
    $config['url_path']     = get_stylesheet_directory_uri() . '/ini/kirki/';
    $config['logo_image']   = get_stylesheet_directory_uri() . '/images/world-map.png';
    $config['description']  = esc_html__( 'The Swallow blog is the best!!', 'tb_blog' );
    $config['color_accent'] = '#00bcd4';
    $config['color_back']   = '#455a64';
    $config['width']        = '20%';

    return $config;
}
add_filter( 'kirki/config', 'my_blog_kirki_configuration' );

function my_blog_add_settings( $wp_customize ){
.....
    $wp_customize->add_setting('img-blur', array(
        'type'              => 'theme_mod',
        'capability'        => 'edit_theme_options',
        'default'           => 0,
        'sanitize_callback' => 'my_blog_sanitize_blur_range',
    ) );
....
}
add_filter( 'customize_register', 'my_blog_add_settings' );

function blog_customizer_controls( $controls ) 
....
    $controls[] = array(
        'type'        => 'slider',
        'section'     => 'favicon_background_img',
        'settings'    => 'img-blur',
        'label'       => esc_html__( 'This is the range control of background image blur.', 'tb-blog' ),
        'help'        => esc_html__( 'Slide to change the background image blur', 'tb-blog' ),
        'priority'    => 30,
        'choices'     => array(
            'min'   => 0,
            'max'   => 100,
            'step'  => 1,
            )
        );

...
}
add_action( 'kirki/fields', 'my_blog_customizer_controls' );

//custom sanitize function
function my_blog_sanitize_blur_range( $input ) {
    if( is_numeric( $input ) && $input >=0 && $input <= 100 ) {
        return intval( $input );
    } else {
        return 0;
    }
}
</pre>

here is the output it throws:
Fatal error: Class 'Kirki_Controls_Slider_Control' not found in /home/ubuntu/workspace/wp-content/themes/tb/ini/kirki/includes/class-kirki.php on line 306

**Comment by aristath** [comment]
That's weird...
Do you have the complete code somewhere on github so that I may try to replicate this?

**Comment by ZmagoD** [comment]
hi @aristath I sent you a mail to access my repo

**Comment by shizhua** [comment]
I am facing the same problem. It gives no error when in local testing environment, but throw the error after uploading to the live site.

Fatal error: Class 'Kirki_Controls_Slider_Control' not found in /path/to/kirki/includes/class-kirki.php on line 306

**Comment by aristath** [comment]
@ZmagoD I just cloned your repository, added kirki in the theme's `ini` folder, and then examined the `ini/traveler-customizer.php` file.
I uncommented lines 416-431 to add the slider field and though I did not get a fatal error, the customizer was not loading.
I noticed that in that field, no `default` value was defined. As soon as I added that, everything started working perfectly fine.

Can you test if that works for you?

**Comment by ZmagoD** [comment]
@aristath I found the source of my problem. Is that I had downloaded Kirki from the WordPress repository and that version make these error occur. Now I have downloaded it from github and all works fine.

**Comment by ghost** [comment]
Hi Aris, did you see the comment in another issue regarding a library that may give more function to the slider?

**Comment by aristath** [comment]
@cmwwebfx I did, and I replied there.

@ZmagoD I'm glad you managed to resolve this issue, I'm closing this thread. As soon as we implement a couple more features we need (see remaining tasks on https://github.com/aristath/kirki/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1) we'll be releasing the next version on w.org

Cheers!
