### ISSUE TITLE
Tooltips not working in WP4.1

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#30]
Now that customizer controls are placed into the DOM with JavaScript – rather than being output directly in PHP – the tooltipsy plugin ceased to work.

More about this: https://core.trac.wordpress.org/ticket/29572

**Comment by aristath** [comment]
I still can't figure this thing out....
I switched to using the default jQuery UI Tooltips and I still can't get this to work... and it really should!
Unless I missed something on that post.

EDIT: The master branch is now using jQuery UI if you want to try this and help out :)

**Comment by aristath** [comment]
@pagelab I switched to using CSS-only tooltips, no more JS. So it looks fine to me now... can you please verify it works ok for you now as well?

**Comment by pagelab** [comment]
@aristath I'll test it, thanks!

**Comment by pagelab** [comment]
@aristath Tooltips working nicely!

**Comment by aristath** [comment]
:+1: Thanks for checking!
