### ISSUE TITLE
Theme Switcher / Changing Themes from the Radio Buttons.

### ISSUE THREAD

**Issue by JakeHenshall** [themeum/kirki#301]
Hi,

Absolutely love this plugin.

Im struggling a little trying to solve this.

in my theme root i have a views folder 
- views

-- theme1
--- full theme

-- theme2
--- full theme

-- theme3
--- full theme

-- theme4
--- full theme

on my index page i have this:

``` php
function action_switch_theme() {

    if ( Kirki::get_option( 'stacks' ) == 'halcyon' ) {
        switch_theme( dirname( __FILE__ ) . '/views/theme1/' );
    } elseif ( Kirki::get_option( 'stacks' ) == 'glacier' ) {
        switch_theme( dirname( __FILE__ ) . '/views/theme2/' );
    } elseif ( Kirki::get_option( 'stacks' ) == 'emerald' ) {
        switch_theme( dirname( __FILE__ ) . '/views/theme3/' );
    } elseif ( Kirki::get_option( 'stacks' ) == 'pebble' ) {
        switch_theme( dirname( __FILE__ ) . '/views/theme4/' );
    } else {
        return 'Seems to Be A Serious Problem!';
    }
}
add_action( 'switch_theme', 'action_switch_theme' );
```

there are no errors present it just isn't setting the theme. Would it better better to write it out as a switch function.

This is my stacks.php file:

``` php
Kirki::add_config( 'stacks_radio_config', array(
    'option_type' => 'theme_mod',
    'capability'  => 'edit_theme_options',
) );

Kirki::add_section( 'stacks', array(
'title'          => __( 'Stacks' ),
'description'    => __( 'Choose a Stack' ),
'panel'          => '', // Not typically needed.
'priority'       => 30,
'capability'     => 'edit_theme_options',
'theme_supports' => '', // Rarely needed.
) );

Kirki::add_field( 'stacks_radio_config', array(
'type'        => 'radio',
'settings'     => 'stacks',
'label'       => __( 'Choose a stack', 'abc123' ),
'description' => __( 'Choose a Different Stack', 'abc123' ),
'help'        => __( 'Click on the radio buttons to easily change the theme layout', 'abc123' ),
'section'     => 'stacks',
'default'     => 'pebble',
'priority'    => 10,
'choices'     => array(
'halcyon' => __( 'Halcyon', 'abc123' ),
'glacier' => __( 'Glacier', 'abc123' ),
'emerald' => __( 'Emerald', 'abc123' ),
'pebble' => __( 'Pebble', 'abc123' ),
),
) );
```

any help would be much appreciated.

Thanks Jake.
##

**Comment by aristath** [comment]
I haven't tried this, but if I were you I'd try to change this line:

``` php
add_action( 'switch_theme', 'action_switch_theme' );
```

I don't think what you have now will work by hooking it to the `switch_theme` action...
That action does not trigger the change of a theme... it is triggered when the user changes a theme.
So perhaps you should try another action like for example `wp` or `init` ?

**Comment by JakeHenshall** [comment]
@aristath Cheers, ill try that a little later on and update here if it works or not.

Much appreciated, Jake.

**Comment by ghost** [comment]
This is brilliant.  Following to see how this turns out.  Could make a good alternative to using defaults.

**Comment by JakeHenshall** [comment]
@aristath Ive tried it using the wp & init and no joy.

I'm also using this script -> https://wordpress.org/plugins/wp-conditional-themes/ which is in

Kirki -> customizer -> theme-switcher.php ive renamed it.

its then included like this 

$theme_switcher = include_once('theme-switcher.php');
if(isset($theme_switcher));

in a file called customizer.php which is then brought into the functions.php file like below.

include_once( dirname( **FILE** ) . '/kirki/customizer/customizer.php' );

ive moved the views folder containing just a index.php & style.css linked together with just a <link rel="stylesheet" href="style.css"> but do i need to add a functions.php file and add in the enqueue the style.css

still no luck with it,

again, any help would be really appreciated.

Thanks Jake.

**Comment by aristath** [comment]
Well, the first thing I can think of is that when in the customizer, the theme is pre-loaded. What that means is that even if you change the theme from an option in the customizer, you won't be able to see the changes take effect. Not until you save the options and reload the page. Did you try that?

**Comment by JakeHenshall** [comment]
@aristath Yes i did the ideal thing would be for it to live load the theme without it having to be saved, would you like me to send the theme files to your gmail account?

Thanks Jake.

**Comment by aristath** [comment]
@JakeHenshall Hey there!

I'm sorry but I can't recall if we fixed this or not... Do you still require assistance here?
