### ISSUE TITLE
slider field

### ISSUE THREAD

**Issue by mahdi-alavi** [themeum/kirki#306]
in slider field, 
if insert the number in input attribute, slider handle not change ...

**Comment by aristath** [comment]
I'm sorry but I don't understand what you mean...

**Comment by salam-mahdinasiri** [comment]
(:
anyway, see this [demo](http://refreshless.com/nouislider/examples/#section-keypress)
slider handle change with keypress

**Comment by ghost** [comment]
Hi Aris. This looks like a good library to add. I remember a couple of months ago we were looking for a useful script to add for the slider class.

**Comment by aristath** [comment]
We are now using HTML5 "range" fields, so this is no longer an option.
