### ISSUE TITLE
(WP4.1) default values are not automatically recognized on activation

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#31]
To make them work again, it's necessary to trigger each control manually. 

After that, the controls work correctly in subsequent theme activations. 

Tested with a clean WordPress 4.1 instalation, without aditional plugins.

**Comment by pagelab** [comment]
I solved this by hardcoding the default values in the get_theme_mod call, like this:

```
<?php $logoWidth = get_theme_mod( 'logo_width', 300 ); ?>

```

**Comment by aristath** [comment]
I'm afraid that's the default WordPress behaviour... Nothing we can do about it here!
`get_theme_mod` should always have a default value.
