### ISSUE TITLE
Textarea/text/editor sanitize_callback issue?

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#312]
Hi

Have problem with textarea/text - frontend output is outputting the link/html as text. 

sanitize_callback not work

Trying everything and nothing...
https://wordpress.org/support/topic/how-can-i-use-the-textarea-to-display-google-adsense?replies=3#post-6675410

https://github.com/aristath/kirki/issues/270

**Comment by aristath** [comment]
I don't get it...
Seems to be working fine for me!

**Comment by x-bull** [comment]
Hi
Thanks for quick reply.
last 2 days nothing works. Today after reuploading kirki files everything works fine. Still dont know why...

Sorry for this post, I was desperate :-)

You can close it

**Comment by aristath** [comment]
@x-bull no problem, I'm glad you managed to get this working.
I'll just go ahead and close this issue... If you have any other issues don't hesitate to create a new ticket.

Cheers!
