### ISSUE TITLE
Modify webfonts.json to include Helvetica Neue.

### ISSUE THREAD

**Issue by mikedidthis** [themeum/kirki#313]
Firstly, thanks for the awesome framework.

Is there a simple way to modify `webfonts.json`? I would like to include Helvetica Neue, as it seems Google Web Fonts is now supporting this family?

http://fonts.googleapis.com/css?family=Helvetica+Neue

Thanks

**Comment by aristath** [comment]
@mikedidthis I just updated the json myself on https://github.com/aristath/kirki/commit/b322d044164520cb87eeaa4f857ba7565a6b1c27

You should now have all new fonts.
Thanks for reminding me! :+1:
