### ISSUE TITLE
Is it possible to manipulate a value that is output inline?

### ISSUE THREAD

**Issue by mikedidthis** [themeum/kirki#316]
Again, wonderful work on kirki! I am trying to figure out the best way to manipulate a value and still use the inline CSS option:

```
Kirki::add_field( 'redacted', array(
  'type'        => 'color',
  'settings'    => 'color_text_1',
  'label'       => __( 'Anchor', 'wp_redacted' ),
  'description' => __( 'Color used for anchor.', 'wp_redacted' ),
  'section'     => 'color',
  'default'     => '#444444',
  'output'      => array( 
    array(
      'element'  => 'a',
      'property' => 'color',
    ),
    array(
      'element'  => 'a:hover',
      'property' => 'color',
    ),
  ),
) );
```

For `'element'  => 'a:hover'` I want to take the current value and adjust the brightness, using `Kirki_Color::adjust_brightness( $color, $steps );`. 

I looked through the issues, found [#200](https://github.com/aristath/kirki/issues/200) and [64f7a95
](https://github.com/aristath/kirki/commit/64f7a9559f11d3c4ffc4f409e784fedf6ffbf1b2) commit. I have added the code exactly like the example, but nothing seems to happen.

Thanks

**Comment by aristath** [comment]
Try this and let me know if it works:

``` php
Kirki::add_field( 'redacted', array(
    'type'        => 'color',
    'settings'    => 'color_text_1',
    'label'       => __( 'Anchor', 'wp_redacted' ),
    'description' => __( 'Color used for anchor.', 'wp_redacted' ),
    'section'     => 'color',
    'default'     => '#444444',
    'output'      => array(
        array(
            'element'           => 'a',
            'property'          => 'color',
            'sanitize_callback' => 'my_custom_color_changes',
        ),
        array(
            'element'  => 'a:hover',
            'property' => 'color',
        ),
    ),
) );

function my_custom_color_changes( $value ) {
    return Kirki_Color::adjust_brightness( $value, 80 );
}
```

**Comment by mikedidthis** [comment]
Yep, that makes sense. Just to clarify, does using `sanitize_callback` still use the built in sanitize functions or would I need to roll my own?

Thanks

**Comment by mikedidthis** [comment]
Works great, happy to close. Again thanks for the hard work! 
:+1:
