### ISSUE TITLE
if use option_name, help argument not work

### ISSUE THREAD

**Issue by mahdi-alavi** [themeum/kirki#317]
if use `option_name` in configuration, help argument not work

```
Kirki::add_config( 'mc', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'option',
  'option_name' => 'mc'
) );

Kirki::add_field( '', array(
    'type'        => 'checkbox',
    'settings'     => 'checkbox_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'help'        => __( 'This is some extra help text.', 'kirki' ),
    'section'     => 'my_section',
    'default'     => '1',
    'priority'    => 10,
) );
```

if don't use `option_name` help argument work, but 
Undefined index: default in \kirki\includes\class-kirki.php on line 157

```
Kirki::add_config( 'mc', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'option'
) );
```

line 157: `$value = get_option( $field_id, self::$fields[ $field_id ]['default'] );`

& Undefined index: default in \kirki\includes\class-kirki.php on line 102

```
Kirki::add_config( 'mc', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod'
) );
```

line 102: `$value = get_theme_mod( $field_id, self::$fields[ $field_id ]['default'] );`

**Comment by aristath** [comment]
That's weird... DO you think you could give me access to your theme so that I may try to replicate this and see what goes on exactly?

Thanks,
Ari.

**Comment by salam-mahdinasiri** [comment]
@aristath [here](https://github.com/mahdi-alavi/twentyfifteen-kirki-test) is twentyfifteen theme like my settings theme

**Comment by salam-mahdinasiri** [comment]
Anyone ?

**Comment by aristath** [comment]
@mahdi-alavi hey there!

I just tested this with the latest commits in the master branch and it looks like this has been resolved.
I'll go ahead and close this ticket, if however you can still replicate it after you pull the latest commits then please feel free to reopen this and provide as many info as possible. :+1:
