### ISSUE TITLE
"color-alpha" appear as input field instead of color field (fixed)

### ISSUE THREAD

**Issue by AdelDima** [themeum/kirki#319]
:octocat: Hello i using **Kirki** for the first time ,i wanna use [color-alpha](https://github.com/aristath/kirki/wiki/color-alpha) field , i create field using  [Static method calls](https://github.com/aristath/kirki/wiki/Fields).

``` php
        Kirki::add_field( '-DIMA-', array(
                  'type'        => 'color-alpha',
                   'settings'    => $control[0],
                   'label'       => $control[2],
                    'help'        => __( 'This is some extra help text.', 'kirki' ),
                    'section'     => $control[3], 
                    'default'     => 'rgba(34,85,100,.4)',
                    'priority'    => $priority,
             ) );
```

And here the output 
![Image of Yaktocat](http://s18.postimg.org/q3qk2nswp/image.jpg)

**Note** : when i change the 'type'  => 'color-alpha', into 'type'  => 'color', and i remove default value, it work but without opacity ( hex code ).

Thanks.

**Comment by mikedidthis** [comment]
As stated in the [docs](https://github.com/aristath/kirki/wiki/color-alpha): 

> This field requires that another, normal color control exists in your customizer. If not, then it will not work as it requires some objects loaded when the default color is loaded.

Do you have a normal `color` control set up?

**Comment by AdelDima** [comment]
@mikedidthis Thanks for your reply, yes i use normal color and it work smoothly,   

``` php
 $wp_customize->add_control(
                    new WP_Customize_Color_Control(
                        $wp_customize, 
                        $control[0], 
                        array(
                            'label' => $control[2], 
                            'section' => $control[3], 
                            'settings' => $control[0], 
                            'priority' => $priority)
                        )
                    );
```

**Comment by mikedidthis** [comment]
Sorry, to clarify, you are using a `color` control (elsewhere) and `color-alpha` control ?

**Comment by AdelDima** [comment]
I am using **color** in some sections and in other place i use **color-alpha**.<br>
i know if i use **color-alpha** with Hex will work fine as the doc say , but it not work with 'type' => 'color-alpha' .<br>i hope the you understand me, thanks.

**Comment by mikedidthis** [comment]
Yep, that makes sense. I was just confirming the issue wasn't down to the missing `color` control.

**Comment by AdelDima** [comment]
I fixed the problem thanks for your help , i make color-alpha class extends from **WP_Customize_Color_Control** instead of **WP_Customize_Control**

**Comment by aristath** [comment]
@AdelDima do you think you could [submit a pull-request](https://help.github.com/articles/using-pull-requests/) for this?

**Comment by mikedidthis** [comment]
I believe this can be closed, the issue was caused by a typo.

**Comment by aristath** [comment]
@mikedidthis in your case yes... but I'm not sure about @AdelDima so if there is indeed an issue I'd like to keep this one active until we fix it.

Cheers!

**Comment by mikedidthis** [comment]
@aristath Sorry I may be confusing everyone here. I never had an issue, I was trying to help @AdelDima with their issue . The last message states that the issue is resolved. :tada:

**Comment by aristath** [comment]
the control class now extends `WP_Customize_Color_Control` as suggested in the comments above. :+1:
