### ISSUE TITLE
Notice: Undefined index: default in wp-content/themes/swish/inc/kirki/includes/deprecated.php on line 91

### ISSUE THREAD

**Issue by amitmishrg** [themeum/kirki#325]
Hi, I am using the latest version of Kirki and included it on my theme and I get this

Notice: Undefined index: default in 
wp-content/themes/swish/inc/kirki/includes/deprecated.php on line 91

Any suggestion plz
Thanks.

**Comment by aristath** [comment]
Just cleaning up... :) The issue in this case was that a `default` value was not defined in some controls.
