### ISSUE TITLE
Chosen - "select2" performance issue

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#326]
Don't know if this issue has been already discussed or if I'm missing something (very probably), but after removing

``` javascript
jQuery(document).ready(function($) {
    $('.select2').select2();
});
```

from [class-kirki-controls-select2-multiple-control.php](https://github.com/aristath/kirki/blob/80bd4ae4366c750dc757d3d4877dad6a437da536/includes/controls/select2-multiple/class-kirki-controls-select2-multiple-control.php) and [class-kirki-controls-select2-control.php](https://github.com/aristath/kirki/blob/80bd4ae4366c750dc757d3d4877dad6a437da536/includes/controls/select2/class-kirki-controls-select2-control.php) and calling the function only once in an enqueued js file the performance has incredibly improved and I passed from 20/30 seconds to load the customizer to about 7 seconds.

Thank you for your effort. Manuel :-)

**Comment by aristath** [comment]
I don't know how I missed that...
Thanks man, I'll fix this ASAP.

**Comment by aristath** [comment]
@pixedelic can you please check if this is fixed now?

**Comment by pixedelic** [comment]
Just checked, everything's fine now, thank you very much!

**Comment by aristath** [comment]
Awesome! Thanks for checking.

**Comment by pixedelic** [comment]
Thank you too... I contacted you through LinkedIn, hope you don't mind. Thank you in advance :-)
