### ISSUE TITLE
Sanitize_callback notice

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#329]
Hi again, found this issue:

Notice:  Undefined index: type in .../kirki/includes/class-kirki-field.php on line 582

I fixed on my end by editing the function sanitize_callback in this way:

``` php
    public static function sanitize_callback( $field ) {

        if ( isset( $field['sanitize_callback'] ) && ! empty( $field['sanitize_callback'] ) ) {
            return $field['sanitize_callback'];
        }
        // Fallback callback
        if ( !isset($field['type']) )
            $field['type'] = '';
        return self::fallback_callback( $field['type'] );

    }
```

Don't know whether it is the right way, though, just to report the issue. Thank you as always for the great work.

Manuel :-)

**Comment by aristath** [comment]
Well... perhaps you have a control that doesn't have a `type` defined?
If that's the case, then the control will not function no matter what you do...
If you add the type, does that notice disappear?

**Comment by pixedelic** [comment]
Wow, what a jerk I am :D Sorry, my bad, I missed two text fields, you're right. Many apologies.

**Comment by aristath** [comment]
:smile: no problem buddy, I'm glad it worked!

Closing this issue. 
If you find any more issues don't hesitate to create new tickets for them... We need all the feedback we can get in order to improve the plugin. 

Closing this issue.
