### ISSUE TITLE
Adding some of the code to a features as plugin for core?

### ISSUE THREAD

**Issue by paaljoachim** [themeum/kirki#33]
Hey

What about adding some of the features to a core plugin?
https://make.wordpress.org/core/2015/01/13/feature-plugins-in-4-2-and-beyond/

Or adding some of the code/take part in the Customizer project going on for core right now.

Have a great day!

**Comment by aristath** [comment]
Hey there!

That decision is up to the WordPress Core development team, not us.
IF the core team decides they want to focus on a feature for a future release then a new feature plugin is created.
I can't submit my plugin as a feature core suggestion as I understand it.

**Comment by paaljoachim** [comment]
Anyone can suggest their plugin as a feature core plugin. 

The bottom line is that the Core group will discuss various feature plugins in a development chat (probably tonight). Some might be continued as core plugins, others might just be added as a trac ticket, others they might say that this will not fit into core but can be a separate plugin. So you are right in the end it is up to the Core development team, but it starts out as a suggestion from whomever made it. There have been very few Core plugins for a while now and the thread link I gave you it is nice to see a bunch of projects suggested.

There is a Weekly Developer Meeting - Wednesdays @ 21:00 UTC. Where various projects will likely be discussed. One can suggest a plugin for core anytime.

**Comment by aristath** [comment]
I'm afraid that I'll have to decline.

I love using Kirki for my own projects, and it does simplify a lot of things!
It's a lot easier to create new settings etc with it than using the default WordPress methods.
However, it's still important that users know how to do things the WordPress way.
If something like this were to be merged in-core then devs would no longer deal with the default API and they wouldn't know what to do to do the stuff they want.
Kirki extends the WordPress Customizer API, it does not (nor would I want it to) replace it.

Besides that however, I don't think a lot of people would want it in-core.
Perhaps we could suggest adding a couple more controls to WP-Core, but other than that no, I don't think so.
WordPress core should be minimalistic and not bloated with 3rd-party stuff like this.
Installing a plugin if you want to take advantage of certain features is not a bad thing... it's the joy of WordPress's modularity!
