### ISSUE TITLE
Not able to remove panels, sections, fields

### ISSUE THREAD

**Issue by patrickedqvist** [themeum/kirki#332]
## The Problem

The WordPress way of removing panels, sections, settings and controls does not work with panels, sections or fields added with the kirki framework.
### Background

I am using a set of panels, sections and fields for several themes but i want to remove certain fields for a specific theme. By overriding them with a function in the specifics theme function.php file. 
#### Example

The file used in every theme

``` php
function my_customize_register( $wp_customize ) {

Kirki::add_panel( 'theme_event_panel', array(
 'priority'    => 20,
 'title'       => __( 'Event Information', 'textdomain' ),
));

Kirki::add_section( 'theme_event_registration_section', array(
 'title'          => __( 'Registration Button', 'textdomain' ),
 'panel'          => 'theme_event_panel',
 'priority'       => 20,
 'capability'     => 'edit_theme_options',
));

Kirki::add_field( 'theme_config', array(
 'type' => 'text',
 'settings' => 'event_registration_text',
 'label' => __( 'Button text', 'textdomain' ),
 'description' => __('Write what the button should say. Default message is "Register Now".', 'textdomain'),
 'default' => __('Register Now', 'textdomain'),
 'section'  => 'theme_event_registration_section',
 'priority' => 10,
));

}
add_action('customize_register', 'my_customize_register');
```

Function in a specific theme

``` php
function theme_slug_customize_register( $wp_customize ) {
 $wp_customize->remove_panel('theme_event_panel');
 $wp_customize->remove_section('theme_event_registration_section');
 $wp_customize->remove_setting('event_registration_text');
 $wp_customize->remove_control('event_registration_text');
}
add_action('customize_register', 'theme_slug_customize_register');
```

**Comment by aristath** [comment]
Can you please try adding a priority > 99?
So instead of this:

``` php
add_action('customize_register', 'my_customize_register');
```

try this:

``` php
add_action( 'customize_register', 'my_customize_register', 100 );
```

The reason I'm saying you should do this is because in order to remove something it must first exist.
We add panels/sections/fields with a priority of 99, so it should work if you use a greater number than that.

Let me know if that works!

**Comment by patrickedqvist** [comment]
Sadly it did not work. Instead everything registered with kirki vanished from the customizer.

**Comment by aristath** [comment]
@patrickedqvist I completely missed this ticket...
Do you still require assistance on this one?

**Comment by aristath** [comment]
@patrickedqvist do you still require assistance on this ticket? Have you managed to solve this?
I'll go ahead and close the ticket due to inactivity, if however you're still having an issue then please don't hesitate to post an update here so that we may take another look at this.

Cheers!
