### ISSUE TITLE
Get registered post types and taxonomies in select

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#341]
Hi,
I'm trying to populate select field with list of all registered post types and taxonomies (used for filtering in theme), but I get only BUILT IN post types and taxes, without custom types ... I have a lot of registered types (WooCommerce).
Is it possible that theme customizer is performing before registration of CPT and CT's ?
Here'a a filter I created (which works fine when called in other admin page):

``` php
function registered_post_tax_types() {

    $filter_array = array(
        'search' => 'search'
    );

    $args_post_types = array(); 
    $post_types = get_post_types( $args_post_types, 'objects', 'and' );
    if ( $post_types ) {
        foreach ( $post_types  as $post_type ) {
            $filter_array[$post_type->name] = $post_type -> name;
        }
    }

    $args_tax = array(); 
    $taxonomies = get_taxonomies( $args_tax, 'objects', 'and' );
    if ( $taxonomies ) {
        foreach ( $taxonomies  as $taxonomy ) {
            $filter_array[$taxonomy->name] = $taxonomy -> name;
        }
    }

    return $filter_array;
}
add_filter('registered_types','registered_post_tax_types',10 );
```

Any ideas ?

Thanks

**Comment by Anydog** [comment]
Anyone ?

**Comment by aristath** [comment]
Hey there!

To get an array of post types that can be used in a `<select>` control for example you can use this:

``` php
Kirki_Helper::get_post_types();
```

To get an array of taxonomies, use this:

``` php
Kirki_Helper::get_taxonomies();
```

To get an array of posts from a post type you can use this:

``` php
// For a full list of arguments see https://codex.wordpress.org/Template_Tags/get_posts
Kirki_Helper::get_posts( array( 'post_type' => 'post' ) );
```

Is this what you wanted? Or did I misunderstand the question?

**Comment by Anydog** [comment]
Thank you very much for adding these two methods. :+1: 
Unfortunately I get only built in post types (post, page, media) and built in taxonomies (categories, tags, format ), and no custom post types : products (WooCommerce), portfolio, or custom taxonomies: product categories, product tags, portfolio categories, product variations etc.

So this works well but only returns built in (default WP) post types and taxes, no custom ... :(

**Comment by igmoweb** [comment]
Are you using any hook to add Kirki fields?

You should test something like this:

``` php
add_action( 'init', 'my_function', 500 );

function my_function() {
  // Add all the Kirki fields here.
}
```

**Comment by Anydog** [comment]
Yeeeah ! It works !  :sparkles: :star2: :sparkles: ...  :relieved:
It's like, essential WP ... how dumb of me. Thanks a million !

EDIT: I was just including separate php files containing various Kirki::add_field methods without hook ... thanks again.

**Comment by everaldomatias** [comment]
@igmoweb great.. very thanks!
