### ISSUE TITLE
implement a CSS-only solution for switches & toggles

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#342]
See https://proto.io/freebies/onoff/ for an example

**Comment by aristath** [comment]
Also interesting:
http://codepen.io/JohnTheCat/pen/azbRpM
http://codepen.io/andreasstorm/pen/ZGjNwZ
http://www.cssflow.com/snippets/toggle-switches
http://cssdeck.com/labs/6zwfstcu
http://www.cssscript.com/ios-7-style-animated-switch-control-with-javascript-and-css3/

**Comment by salam-mahdinasiri** [comment]
http://callmenick.com/post/css-toggle-switch-examples
https://ghinda.net/css-toggle-switch/
http://www.htmllion.com/css3-toggle-switch-button.html

**Comment by ghost** [comment]
The nicest ones from these are the callmenick ones.

**Comment by aristath** [comment]
Well... for toggles I went for material-design. For switches, I chose none of the above. I went for zurb's foundation implementation: http://zurb.com/building-blocks/switches-with-lables
It's more generic and will suit most use-cases.
Plus the other implementations had a lot of issues with the labels....
