### ISSUE TITLE
Not  Able to see panel and fields in 'Twenty Thirteen' 

### ISSUE THREAD

**Issue by burhandodhy** [themeum/kirki#344]
The fields and panel are disappear after the 1 second 

![screenshot_1](https://cloud.githubusercontent.com/assets/7139602/9842638/1027cc2c-5aca-11e5-9e75-296665ca3385.png)

found the reason by default the display of new add fields and panels are 'None'

![screenshot_2](https://cloud.githubusercontent.com/assets/7139602/9842889/cd72cb4e-5acd-11e5-89af-20b150c383b1.png)

**Comment by aristath** [comment]
Do you have that theme on github perhaps so that I may take a look?

**Comment by burhandodhy** [comment]
I already implement Kirki in other theme like twenty-fourteen and twenty-fifteen but still same problem occurs. 

https://github.com/burhandodhy/Twenty-Thirteen-Error-344/

**Comment by JohEngstrom** [comment]
~~I have exactly the same issue when using the Underscores theme (https://github.com/automattic/_s)~~

Never mind worked it out. Must have had some issue with the syntax. Copied from the sample file and all working now.

**Comment by aristath** [comment]
@burhandodhy I'm still unable to replicate your issue... It all seems to be working fine for me!
As soon as I add some fields to a section, it appears. So does its parent panel.
Did you by any chance not add any fields?

**Comment by burhandodhy** [comment]
the issue is still there, every time i try to implement in underscores theme the bug will occur ...

**Comment by aristath** [comment]
@burhandodhy can you please send me the exact theme you have with the issue so that I may try to debug this?

**Comment by aristath** [comment]
@burhandodhy I've been trying to replicate this issue for some time now without any success.
It looks to me like this has been resolved so I'll go ahead and close the ticket due to inactivity.

If you're still having an issue with this then please don't hesitate to post an update here and reopen the ticket so that we may take another look at it.
