### ISSUE TITLE
editor field problem with html entities

### ISSUE THREAD

**Issue by maciekkus** [themeum/kirki#345]
Hi,

After saving changes to editor field and reloading page with customizer I get html code encoded like below:
![editor problem](https://cloud.githubusercontent.com/assets/87817/9846299/8288a492-5ad1-11e5-837d-3c2cc5972794.png)

This is from example in this repo.

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/32336287b89064576da4036c996c89b26d2841c1
