### ISSUE TITLE
editor problem - when using custom config setting

### ISSUE THREAD

**Issue by maciekkus** [themeum/kirki#346]
I found that using editor field attached to custom config is causing a problem with 'Save and publish' button on customizer panel. It simply doesn't update to be clickable.
Everything works as expected when using "" or "global" as $config_id

Probably it related to https://github.com/aristath/kirki/issues/275
##

**Comment by aristath** [comment]
@maciekkus can you please post the code for your config and this field so that I may try to replicate your issue and debug it?

**Comment by aristath** [comment]
Fixed.
