### ISSUE TITLE
Missing JS - Formstone

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#347]
Hi,
I pulled latest version, and got this 404 errors:
... /kirki/includes/controls/switch/formstone-touch.js?ver=4.3  customize.php?return=%2Fmy_pretty_theme%2Fwp-admin%2F:97 GET
... /kirki/includes/controls/switch/formstone-core.js?ver=4.3  customize.php?return=%2Fmy_pretty_theme%2Fwp-admin%2F:99 GET
... /kirki/includes/controls/switch/formstone-checkbox.js?ver=4.3

Should I pull later when you remove enqueuing (or add files), or ... ? ;)

Thanks

**Comment by Anydog** [comment]
Anyone ... ? pls

**Comment by aristath** [comment]
Hey there!

Perhaps it was an incomplete pull? You'd only get this error if the `includes/controls/switch/class-kirki-controls-switch-control.php` file was not pulled...
These were being enqueued here: https://github.com/aristath/kirki/blob/93e6c598901632733a93f94b56d9870b2a01494a/includes/controls/switch/class-kirki-controls-switch-control.php#L27-L29 but in the latest commits (as you can see on https://github.com/aristath/kirki/blob/master/includes/controls/switch/class-kirki-controls-switch-control.php we no longer enqueue these

**Comment by Anydog** [comment]
Hi, thanks for getting back.
Yes, it must have been that (I did fresh clone and it's ok now), sorry for taking your time with this ... : /
