### ISSUE TITLE
Uncaught TypeError: Cannot read property 'frame_button' of undefined

### ISSUE THREAD

**Issue by pavelrich** [themeum/kirki#35]
Hello,

firstly thanks for your fantastic work, really enjoying the Kirki ;-)

I found an error with an "Upload Control" (type => 'upload'). I get this error message:

```
Uncaught TypeError: Cannot read property 'frame_button' of undefined
```

This happens on WordPress 4.1.

Please can you help me with that?

Thanks

Pavel

**Comment by keeneyemedia** [comment]
I'm receiving the same error.

**Comment by peterhadorn** [comment]
Had this same error too, but my upload controls now work fine in 0.7! Thanks for your awesome job, aristath & co!

**Comment by aristath** [comment]
Awesome, thanks for the update @peterhadorn
