### ISSUE TITLE
How to make sections open below in the same window

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#350]
How to make sections open below in the same window??

like this
https://github.com/aristath/kirki/wiki/select2-multiple

NOTE: My Section open like Panels in another window on the right

Thanks.

**Comment by aristath** [comment]
@Serpentsoft hey there!
This was changed in recent WordPress versions, I'm afraid it's no longer possible to have them open below. :(

**Comment by Serpentsoft** [comment]
Yes, Thanks for your help
