### ISSUE TITLE
Switch values not being saved

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#354]
Hi,
sorry, it's me again :confused:
It seems that "switch" field is not saving values. Every other field I used are being saved, only "switch" isn't ...
Any ideas ?

**Comment by aristath** [comment]
Hey there!

I'm currently in the process of rebuilding the fields and converting them to use the new JS API of the customizer...
I must have messed-up somewhere in that control, taking a look now. :)

**Comment by aristath** [comment]
They seem to be working fine for me... Are you using theme_mods, single options, or serialized options?

**Comment by Anydog** [comment]
I'm using theme mods. The switch is getting default values properly, but changing the state is not being saved ... It just brings back default value ...

**Comment by aristath** [comment]
found the bug and fixed it.

Thanks for reporting this, I really appreciate it!

**Comment by Anydog** [comment]
Thank you for fixing it. And I really appreciate your work with Kirki. It really saved me a lot of time. I migrated totally from theme options framework and I'm very satisfied with that .
