### ISSUE TITLE
Select2 Sortable

### ISSUE THREAD

**Issue by tomtev** [themeum/kirki#357]
Hi,

Could you integrate this?
https://github.com/reduxframework/select2-sortable

**Comment by aristath** [comment]
I replaced select2 with this one: http://brianreavis.github.io/selectize.js/
It supports sortables by default, so it's now integrated.
Please note however that there's currently a bug with the implementation:
The options are saved properly, but when they are displayed they are swon in the default order. I'll fix that soon. :)
