### ISSUE TITLE
Checkbox checked regardless of default value.

### ISSUE THREAD

**Issue by mikedidthis** [themeum/kirki#359]
With no value in the DB, checkbox's rendered checked even when setting `default` to `0`.

**customizer.php**

```
Kirki::add_field( 'wp_theme', array(
  'type'     => 'checkbox',
  'settings' => 'post_tags',
  'label'    => __( 'Enable Tags', 'wp_theme' ),
  'help'     => __( 'Enable the blog posts tags', 'wp_theme' ),
  'section'  => 'post',
  'default'  => '0',
) );
```

**Customizer**

![http://i.imgur.com/QCe8zVD.png](http://i.imgur.com/QCe8zVD.png)

The checkbox renders checked / unchecked once a value is saved to the DB. 

It's worth mentioning that both `toggle` and `switch` are off when the `default` is `0` and there is no value in the DB, so I presume this is an issue with `checkbox`.

**Comment by aristath** [comment]
Right now you have the default  value set as `'0'`
Have you tried setting it to `0` (without the quotes) or `false` ?

**Comment by mikedidthis** [comment]
`0` is acts the same, but `false` works as desired.

The output when using `get_options` is now `true` or `false`. If this is a documentation / wiki issue, let me know I am happy to update them.
