### ISSUE TITLE
Add a sortable control

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#36]

**Comment by ghost** [comment]
Awesome update, thank you Aristeides

**Comment by aristath** [comment]
You can see it in action here: https://www.youtube.com/watch?v=-H6cLI2xabE&feature=youtu.be&t=1m28s
This opens up new horizons... :) But actually a lot of the code here is not my own, most of it was done by @bfintal for the [Titan Framework](https://github.com/gambitph/Titan-Framework)

**Comment by ghost** [comment]
Yes Benjamin has done some lovely coding on the framework. What you have displayed in this example is simply WOW, and really stunning on how you have made this work.
