### ISSUE TITLE
path not loaded correctly at Customizer

### ISSUE THREAD

**Issue by yogasukma** [themeum/kirki#364]
i have installed wp 4.3.1 and kirki master from this github, i have included kirki on my themes.  

when i open customizer, data not saved correctly, and when i see on console log, it showing some error like this. It seems path not loaded correctly, it load on plugins dir, and using absolute path. 

![screen shot 2015-09-20 at 9 05 59 am](https://cloud.githubusercontent.com/assets/1949957/9978735/2e113884-5f77-11e5-960c-a8440f81d95c.png)

**Comment by aristath** [comment]
Did you read the wiki on how to embed Kirki in your theme? https://github.com/aristath/kirki/wiki/Embedding-in-a-theme

**Comment by yogasukma** [comment]
hi @aristath i've re-read again, and yes, i miss about adding filter 'kirki_update_ur', i have added it just now and yes the path loaded correctly now,  thanks 

But the data still not saved, when i changes value on field, the loading-spiner-icon showing forever at the preview site. feels like on progress to showing data but never happened

**Comment by aristath** [comment]
Can you enable WP_DEBUG and check if there are any PHP errors in your theme?
You can see how to enable WP_DEBUG here: https://codex.wordpress.org/WP_DEBUG

This usually happens when there a PHP notice/warning or something else that prevents WordPress's ajax calls and as a result the customizer fails to save the data.

**Comment by yogasukma** [comment]
ah, i think i always set my default wp instalation in debug mode for development before, but it looks i missed about this ones. after debug true, then the error showing up and give me idea why customizer not saved. thanks very much

**Comment by aristath** [comment]
:) I'm glad I could help!
