### ISSUE TITLE
multi-select elements don't work properly.

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#366]
Since we deprecated select-2 controls, we changed the templates from PHP to JS.
We merged the `select`, `select2` and `select2-multiple` controls to a single `select` control.
Now all `<select>` controls use [selectize](http://brianreavis.github.io/selectize.js/) and when we want to define a select element as multi-select, we add `'select' => 7` for example in the field's array.
The number 7 in the above example is the maximum number of choices a user can select.
So if we don't want to limit the number we just enter 999.

The JS (undercore.js) template that is responsible for the control can be seen [here](https://github.com/aristath/kirki/blob/274e54590db26ebcd7350236f7b41e2b73d3a7fe/includes/controls/select/class-kirki-controls-select-control.php#L43-L61) and the script we're using for that control [here](https://github.com/aristath/kirki/blob/274e54590db26ebcd7350236f7b41e2b73d3a7fe/includes/controls/select/script.js)

I've been trying to figure this out for 2 days and I'm probably just blind at this point missing something obvious. If anyone can assist I'd greatly appreciate it.

To test/duplicate the issue:
- Pull a fresh copy of Kirki from the master branch on this repository and activate the plugin
- copy the [demo-theme](https://github.com/aristath/kirki/tree/master/demo-theme) folder from the plugin to your themes directory and activate the new theme
- Visit the customizer and go to the "select" section. You'll see all the select options there... The one with the bug is the last one that allows us to select multiple elements. (the control's code is [here](https://github.com/aristath/kirki/blob/274e54590db26ebcd7350236f7b41e2b73d3a7fe/demo-theme/functions.php#L418-L433)

**Comment by Anydog** [comment]
Hi,
I just tested this and I cannot see what is the problem ? I would like to help. I'm not great coder, but maybe I can see something ...

Console log is returning correct data `Object {0: "option-1", 1: "option-3"}˛` when I selected Option 1 and 3, as well as in demo theme ...
It seems you figured it out, sorry .. I forgot I'm in "Closed issues"  ...:flushed:

**Comment by aristath** [comment]
@Anydog yeah, I figured it out...
The problem was with the control's sanitization call. I was treating it like a normal select so I was sanitizing it like a string instead of an array. ;)
