### ISSUE TITLE
do not enqueue separate files for each control

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#367]
We should compile all JS to a single file and serve that instead.
This has already started being implemented (via Grunt), it just needs some more testing.

**Comment by igmoweb** [comment]
We just need Grunt to minimize the customizer.js.
- By default, customizer.min.js will be enqueued
- SCRIPT_DEBUG = true will enqueue customizer.js
- KIRKI_DEBUG = true will not enqueue customizer.js but it will enqueue separate scripts for each control.

We should document the KIRKI_DEBUG const.
