### ISSUE TITLE
kirik and less

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#37]
Hi, 
great framework!! I thinking about to integrate "kirik" with wp-less plugin. So I need to remove "inline style" after "save" and add configuration for wp-less plugin but I don't know which method should I change? Can you help me?

Regards

**Comment by aristath** [comment]
Hey there!

Kirki will only add the inline styles if you add the `output` arguments to your controls.
If you don't add that, then nothing will be added and you can add your own implementation for LESS. :smile:

**Comment by padalec** [comment]
Thanks for your reply but when I removed the output argument from background I have a lot of notices:

<pre>
Notice: Undefined index: output in ../kirki/includes/class-Kirki_Style_Background.php on line 35
</pre>

And live preview doesn't work too :/
Regards

**Comment by aristath** [comment]
Thanks for reporting this!

Can you please try pulling the latest changes and test this again!
I think I just fixed this a couple of seconds ago. :+1:

**Comment by padalec** [comment]
Ok no more notices but when I remove output argument live preview doesn't work :(

**Comment by aristath** [comment]
Well, since you removed the `output` argument Kirki no longer adds the inline CSS, that's why the live preview does not work.
Now you'll have to do your LESS implementation and use the wp-less plugin however you like.

**Comment by padalec** [comment]
Ok thanks. How to get value from controls?

**Comment by aristath** [comment]
You can get the settings using [get_theme_mod()](http://codex.wordpress.org/Function_Reference/get_theme_mod)
If you're using a background control, it creates some additional settings that you can see here: http://kirki.org/#background

**Comment by padalec** [comment]
ok thanks. I need to run inline style ONLY for preview. Right now I created some "test" function and I fired it only when 'customize_messenger_channel' $_POST is sending. But I don't know how to connect to Yours controls objects. Method $controls = $kirki->get_controls(); return only array with all fields but I need fire 'control_css()' method.
