### ISSUE TITLE
Strange escape issue

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#387]
Hi,
I found strange issue with escaping codes for icon font, it seems that double escaping helps.
When I save and refresh TC page, the "\" turns to "\" and when I start to edit (anything in "code" field), automatic refresh un-escapes the icon font code.
You'll see this in presentation bellow:
![escape_css](https://cloud.githubusercontent.com/assets/1732234/10118522/64f17794-647a-11e5-86f9-ab3f0d52c7e1.gif)

Not a big issue to, but still ... any ideas ?

**Comment by aristath** [comment]
That's weird indeed.... I was able to replicate it, but I still don't know why it happens.
I searched the ACE editor's documentation and couldn't find anything, and the default `sanitize_callback` for code controls lets the data go in completely untouched!
:confused:

**Comment by aristath** [comment]
Huh... found the bug. It's the default behavior of the ACE editor...
http://ace.c9.io/#nav=higlighter&api=editor (on the "Defining Regular Expressions" section)

**Comment by Anydog** [comment]
Woow, you're really fast ... :)

**Comment by aristath** [comment]
Fast in identifying the issue, yes...
Still unable to find a solution though. :(

**Comment by Anydog** [comment]
Yeah, this seems to me as a tough one ... And I'm also fast ... to find the issue ..but my wife is even faster :D

**Comment by aristath** [comment]
LOL

If you find a solution to this one I'm all ears!

**Comment by Anydog** [comment]
...oh, I believe this is beyond my capabilities, but I'l try ... stay tuned ;)

Regular expressions are really not my specialty, and it seems this is "not a bug, but a feature" ... I guess I'll stick with double escaping ...

**Comment by aristath** [comment]
I'm afraid there's not much we can do on this one...
I'll close this ticket and keep an eye on ace in case they fix it.
