### ISSUE TITLE
Categories into wp_query

### ISSUE THREAD

**Issue by sahinozek** [themeum/kirki#396]
Hi,

Thanks for the awesome toolkit. We do really appreciate it very much. 
I have a rather simple question. 
I have the categories

``` php
$options_categories_obj = get_categories();
$options_categories = array();
foreach($options_categories_obj as $category) {
    $options_categories[$category->term_id] = $category->cat_name;
}
```

And an option for that

``` php
Kirki::add_field( '', array(
    'type'        => 'select',
    'settings'    => 'featurecat',
    'description' => __( 'Select a category', 'gabfire' ),
    'section'     => 'homepage',
    'priority'    => 10,
    'choices'     => $options_categories,
    'multiple'    => $multiple,
    'required' => array(
        array(
            'setting' => 'featured-base',
            'operator' => '=',
            'value' => 'base-cat'
        )
    ),
) );
```

While calling that featurecat option into wp_query, should I call it as below?

``` php
$feaCat           = implode(",", get_theme_mod( 'featurecat'));
$args = array(
  'cat' => $feaCat,
  'posts_per_page' => 4
);
```

Thanks in advace

**Comment by aristath** [comment]
@sahinozek hey there!
Looks good to me...
If it doesn't work for you then try `category` instead of `cat`:

``` php
$feaCat           = implode(",", get_theme_mod( 'featurecat'));
$args = array(
  'category' => $feaCat,
  'posts_per_page' => 4
);
```

**Comment by aristath** [comment]
Hey there!
Did you manage to resolve this one?
If yes can we please close this ticket?
If no could you please provide some more details so that we may try to figure this out?

Thanks!

**Comment by sahinozek** [comment]
Hi,
I am sorry for not following up. I just logged in back and noticed your message.

Yes, It worked just fine :)

**Comment by aristath** [comment]
Awesome, thanks for letting me know!

Closing this ticket. :+1:
