### ISSUE TITLE
Issues with the slider control in latest version

### ISSUE THREAD

**Issue by JohEngstrom** [themeum/kirki#41]
I've just updated to the latest version of the plugin and I've noticed that there's an issue with the slider control.

I have a slider control to control the alpha channel of a RGBa value. See below.
In the latest version the slider now only goes up to 0.9 instead of 1 and the value is always saved as 0.

If I change the max setting to a value above 1.0 then when the slider is on anything 1 and above it saves as that value but anything below 1 is treated as 0.

```
$controls[] = array(
            'type'     => 'slider',
            'setting'  => 'banner_main_heading_alpha',
            'label'    => __( 'Main heading background opacity.', 'HN' ),
            'section'  => 'banner_homepage_section',
            'default'  => 0.5,
            'priority' => 4,
            'choices'  => array(
                'min'  => 0,
                'max'  => 1,
                'step' => 0.1,
            ),
            'subtitle' => __( 'Set the opacity of the main heading background colour.', 'HN' ),
        );
```

**Comment by aristath** [comment]
Hey there!

Can you please try the latest version from this repository?
I was unable to replicate this issue, so I assume this has already been fixed...
Can you please confirm?

**Comment by aristath** [comment]
Fixed in the develop branch
