### ISSUE TITLE
required broken?

### ISSUE THREAD

**Issue by reshogun** [themeum/kirki#416]
My own testing with required operators and demo-theme shows what should be hidden still is loaded on page load and it will not have effect if you try to change and save new value. What is the problem with this 1.0.2 version?

**Comment by aristath** [comment]
Hey there!

Are you using the version from wordpress.org, or are you using the one from this github repository?

This has already been fixed a few days ago and I just tested it works fine...

If you're having an issue using the latest version from github then could you please tell me how you did your tests and what code you used?

**Comment by reshogun** [comment]
Hey! I used kirki from github rep and i installed it as plugin and activated it. It have tried give examples from https://github.com/aristath/kirki/wiki/required and these did not work.

**Comment by reshogun** [comment]
Little bit background knowledge if it helps: current system windows 8.1 64. Latest version chrome, stable xampp and wordpress.

**Comment by reshogun** [comment]
I do not know root of this problem but it seems there is some configuration problems as it now give this kind of error message: Warning: array_unique() expects parameter 1 to be array, boolean given in C:\xampp\apps\wordpress\htdocs\wp-content\themes\e-theme\kirki\includes\class-kirki-scripts-frontend-google-fonts.php on line 196 
Warning: array_unique() expects parameter 1 to be array, boolean given in C:\xampp\apps\wordpress\htdocs\wp-content\themes\e-theme\kirki\includes\class-kirki-scripts-frontend-google-fonts.php on line 196

Warning: array_unique() expects parameter 1 to be array, string given in C:\xampp\apps\wordpress\htdocs\wp-content\themes\e-theme\kirki\includes\class-kirki-scripts-frontend-google-fonts.php on line 197

Warning: array_unique() expects parameter 1 to be array, string given in C:\xampp\apps\wordpress\htdocs\wp-content\themes\e-theme\kirki\includes\class-kirki-scripts-frontend-google-fonts.php on line 198 as well as it does not render elements right ie radiobuttons

**Comment by aristath** [comment]
@reshogun can you please try using the develop branch from https://github.com/aristath/kirki/tree/develop?
Let me know if that solves your issue..

**Comment by reshogun** [comment]
It did not have any effect. Radiobuttonset still shows up as normal radio buttons and required does not work. Same "Warning: array_unique() expects parameter.." is also there

**Comment by reshogun** [comment]
Some peculiar notice here: I cannot save created kirki settings

**Comment by aristath** [comment]
Can you please send me the config & fields you're using so that I may try to replicate your issue?

**Comment by reshogun** [comment]
Your basic example of required option also has this effect. https://github.com/aristath/kirki/wiki/required

It gives me those warnings of array_unique() as well as i cannot save those options when i try to change them. 

I think it is possible that it is some configuration problem on xampp/apache side. I will try to upload and try this example on some real server.

**Comment by reshogun** [comment]
Should i email my own theme to you as well screenshots from customizer when i have added fields?

**Comment by reshogun** [comment]
I shall close this and open new as i found solution to one of those problems i have described.
