### ISSUE TITLE
customizer options do not load right

### ISSUE THREAD

**Issue by reshogun** [themeum/kirki#429]
![background](https://cloud.githubusercontent.com/assets/3878710/10335393/0a564940-6cf9-11e5-843e-8ee2442ba760.png) As you can see from picture i have got solution to unique array problem but this unable to save kirki options or these options do not load right (like this background property) . Do you have advice how to get this off.

**Comment by aristath** [comment]
@reshogun probably related to https://github.com/aristath/kirki/issues/427
Could you please open this with Chrome, and then look for any errors in the console in dev tools?

**Comment by reshogun** [comment]
I am testing infiword (from here github) now and this is what it gave me these warnings
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…nt/themes/infiword/kirki/includes/controls/radio-image/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…nt/themes/infiword/kirki/includes/controls/color-alpha/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…content/themes/infiword/kirki/includes/controls/slider/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…nt/themes/infiword/kirki/includes/controls/color-alpha/script.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…themes/infiword/kirki/includes/controls/number/formstone-core.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…content/themes/infiword/kirki/includes/controls/number/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/css/select2.min.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…ent/themes/infiword/kirki/includes/controls/multicheck/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…/infiword/kirki/includes/controls/multicheck/kirki-multicheck.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/js/kirki-tooltip.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…emes/infiword/kirki/includes/controls/number/formstone-number.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/js/serialize.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/js/select2.full.min.js?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/css/customizer.css?ver=0.5 Failed to load resource: the server responded with a status of 404 (Not Found)
customize.php:4 Uncaught TypeError: $(...).number is not a function
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/css/kirki-styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…nt/themes/infiword/kirki/includes/controls/radio-image/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/css/select2.min.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…content/themes/infiword/kirki/includes/controls/number/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…content/themes/infiword/kirki/includes/controls/slider/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…ent/themes/infiword/kirki/includes/controls/multicheck/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdoc…nt/themes/infiword/kirki/includes/controls/color-alpha/style.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/css/kirki-styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/wordpress/wp-content/plugins/C:/xampp/apps/wordpress/htdocs/wp-content/themes/infiword/kirki/assets/css/customizer.css?ver=0.5 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by aristath** [comment]
Looks like it's the same issue as #427 

I'll close this one in favor of the other ticket.
Can you please head over there and provide as much info about your server setup as possible?
I'm still unable to replicate this one, so I'll try to see if you and the others with the same issue have something in common so that I may figure out what goes on.

Thanks!
