### ISSUE TITLE
_s theme's Site Title & Tagline not live update.

### ISSUE THREAD

**Issue by mennwebs** [themeum/kirki#43]
When I use it with [_s theme](http://underscores.me/)'s Site Title & Tagline, such as this code in /inc/customizer.php ,

```
$wp_customize->get_setting( 'blogname' )->transport         = 'postMessage';
$wp_customize->get_setting( 'blogdescription' )->transport  = 'postMessage';
```

I think it conflicts with Kirki. It's not live update as other inputs.

Is this a bug, or do you recommend me to NOT using _s's customizer code and use just Kirki instead?

PS. I put it to my GPL theme - [Blogberry](https://github.com/SeedThemes/Blogberry).

Thank you so much

![kirki-2](https://cloud.githubusercontent.com/assets/4017086/6317440/8b56aeb2-ba85-11e4-95ed-851b671c8bd3.png)

**Comment by mennwebs** [comment]
Very sorry, the latest version of Kirki already fixed this problem. Thank you so much.

**Comment by aristath** [comment]
:+1:
