### ISSUE TITLE
Add new control

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#44]
Hi,
how can I add a new control? I need a H2 tag with label between tags.
Regards

**Comment by aristath** [comment]
Have you tried using the `group-title` control?

**Comment by aristath** [comment]
Hey again.
We just added a `custom` control that you can use to add whatever you want: https://github.com/aristath/kirki/commit/d9943ef22f313cb634df3725074f4a4dd2f4ef78 :+1:

**Comment by padalec** [comment]
Hi, 
yes I used group-title and works excellent. Thanks for added custom control!
Regards
