### ISSUE TITLE
Google fonts for new Typography control

### ISSUE THREAD

**Issue by sigaev-pro** [themeum/kirki#441]
Hi guys!

First of all, I want to express to you my admiration for an excellent tool that you do!

Please tell me, I can not understand how I can use Google Fonts and subsets in new typography control?

I learned the code of control and demo theme, but did not understand how I can use Google Fonts and subsets.

**Comment by BoweFrankema** [comment]
Here's an example of how to add a new setting that automatically loads Google Fonts and gives your users the option to control the font styles.

``` php
Kirki::add_field( 'kirki_demo', array(
    'type'        => 'typography',
    'settings'    => 'base_typography_font_family',
    'label'       => __( 'Typography Control', 'kirki' ),
    'description' => 'Customize the font style...',
    'section'     => 'wf_plus_typography_body_section',
    'default'     => array(
        'font-style'     => array( 'bold', 'italic' ),
        'font-family'    => 'Lato',
        'font-size'      => '16',
        'font-weight'    => 'inherit',
        'letter-spacing' => 'inherit',
    ),
    'priority'    => 10,
    'choices'     => array(
        'font-style'     => true,
        'font-family'    => true,
        'font-size'      => true,
        'font-weight'    => true,
        'line-height'    => true,
        'letter-spacing' => true,
    ),
) );
```

You don't have to do anything special for Google Fonts integration :-)

**Comment by sigaev-pro** [comment]
Thank you, but also how I can add subsets support?

**Comment by reshogun** [comment]
@mrnull  https://github.com/aristath/kirki/wiki/Google-Fonts-Integration there is example how to add subset support.

**Comment by JakeHenshall** [comment]
@BoweFrankema Nice piece of code how do i get it to only work on one element? how would i attach output to that

Thanks

**Comment by aristath** [comment]
@JakeHenshall https://github.com/aristath/kirki/wiki/Automating-CSS-output
