### ISSUE TITLE
 Background type not working?

### ISSUE THREAD

**Issue by reshogun** [themeum/kirki#442]
Background type does not work as it is shown in wiki, also background size does not seem to at least cover all the body element or covers it in wrong(y-size overflow.). 
![bg](https://cloud.githubusercontent.com/assets/3878710/10567071/6edd1e6e-7601-11e5-9da4-2131bcc91962.png)
Another possible win8,1 xampp bug?

**Comment by Anydog** [comment]
Are you testing this with Kirki plugin / demo-theme ? Because, I don't have such issues with embedded Kirki in theme.
Aristath, are you here ? Haven't heard from you a while :) :

**Comment by reshogun** [comment]
as plugin and demo. edit. now it seems to work again. Possible load problem on my end. But i still have not got integration working.

**Comment by aristath** [comment]
@reshogun the color-alpha control used there has a bug...
Color-alpha controls don't work unless you have a normal color control somewhere.
I still haven't been able to figure out why this happens but I'm guessing this is what was causing your issue.
I already have an open ticket for that so I'll go ahead and close this one. :+1:

**Comment by sigaev-pro** [comment]
Sorry for offtopic, but please tell me where to find this control? Neither the master branch nor develop branch, do not contain this control.

**Comment by aristath** [comment]
There is no "background" control...
When you create a background field it creates other sub-fields using their own controls.
So if you're looking for the color-alpha control, you'll find it in the includes/controls/color-alpha folder.
