### ISSUE TITLE
Provide Font Fallback for Typography control

### ISSUE THREAD

**Issue by BoweFrankema** [themeum/kirki#443]
Currently when a Font is set by the Typography control it has no default fallback. This means if the Google Font is not available for whatever reason it has no fallback which leads to ugly results. 

My suggestion would be to set "sans-serif" as the default fallback. Like:

```
 font-family: "Lato", sans-serif;
```

**Comment by themepunch** [comment]
Hello,

thanks for the feedback. We will add this as an option to our update list.

Cheers, ThemePunch

On Thu, Oct 22, 2015 at 8:40 AM, Bowe Frankema notifications@github.com
wrote:

> Currently when a Font is set by the Typography control it has no default
> fallback. This means if the Google Font is not available for whatever
> reason it has no fallback which leads to ugly results.
> 
> My suggestion would be to set "sans-serif" as the default fallback. Like:
> 
>  font-family: "Lato", sans-serif;
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aristath/kirki/issues/443.

## 

Cheers from your Team @ ThemePunch

http://www.codecanyon.net/user/themepunch?ref=themepunch
http://www.twitter.com/themepunch
http://www.youtube.com/user/ThemePunch

**Comment by aristath** [comment]
@BoweFrankema interesting thought....
In the json file containing the google fonts, google also defines a "category".
I guess we could code something that would convert those to fallbacks as categories are "sans-serif", "serif", "handwriting" and a couple others.

I'll investigate further and try to come up with something. :)

**Comment by aristath** [comment]
@BoweFrankema I just implemented this on the develop branch.
I added some default fallbacks and there's a filter you can use if you want to customize them like this:

``` php
function my_custom_fallback_fonts() {
    $backup_fonts = array(
        'sans-serif'  => 'Helvetica, Arial, sans-serif',
        'serif'       => 'Georgia, serif',
        'display'     => '"Comic Sans MS", cursive, sans-serif',
        'handwriting' => '"Comic Sans MS", cursive, sans-serif',
        'monospace'   => '"Lucida Console", Monaco, monospace',
    );
    return $backup_fonts;
}
add_filter( 'kirki/fonts/backup_fonts', 'my_custom_fallback_fonts' );
```
