### ISSUE TITLE
Sortable "default" attribute not working

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#457]
When using sortable field, the given default values are not working. When you first visiting the Customizer, all choices are selected even you have set the default attribute as empty array. The order is also not working.

I tried your sortable example snippet from the wiki page, and not working. And the "settings" attribute should be "setting" by the way.

If you inspected the element, I know you stored the selected keys into a hidden input, inside the "value" attribute. If you haven't save any change to the field, the value is "option3,option1,option4", comma separated format. But when you make a change (sort or show/hide) the value is in serialized format. Please check this issue.

Thanks,
David
##

**Comment by aristath** [comment]
@daviedR hey there!

I'm marking this as a bug and will look into it ASAP.

> And the "settings" attribute should be "setting" by the way.

Actually I wanted it to be pretty much the same as the WordPress core API for the customizer, that's why it's `settings` and not `setting`. :smile:

**Comment by daviedR** [comment]
Hi @aristath, thanks for checking out :)

Do you have any idea, when you will push a new version to WordPress plugin repository? The last version was 3 months ago and I see a lot of features has been added since then, the code editor field, repeater, typography, etc. Can't wait to see them in the plugin.

Anyway, I just donated a small amount of money to your paypal. Thanks for updating this awesome framework!

**Comment by aristath** [comment]
@daviedR I believe this has been fixed since this ticket was originally posted...
Can you please confirm it and if everything's alright close this?
If it's still an issue please let me know so that I may fix this ASAP.

Thanks!
