### ISSUE TITLE
HTML showing on theme

### ISSUE THREAD

**Issue by yogasukma** [themeum/kirki#460]
- so i use textarea control
- insert some html (in this case <b>)
- on preview and on real site, it showing that HTML tag showing up, 

is there i miss something on configuration? or it was by purpose?

![screen shot 2015-10-29 at 1 08 12 pm](https://cloud.githubusercontent.com/assets/1949957/10810690/6d8666e8-7e3e-11e5-8021-744d6e95ca2c.png)

**Comment by aristath** [comment]
That's why I build the demo theme...
To show how some things can be done.
Look here: https://github.com/aristath/kirki/blob/master/demo-theme/index.php#L126
