### ISSUE TITLE
When using EDITOR control, save button can't click

### ISSUE THREAD

**Issue by yogasukma** [themeum/kirki#461]
- so i use editor control
- i changes the value on editor
- it doesn't effect to preview site (so live preview not work)
- and button save goes disable. (so i can't click the save button)

i use latest wordpress (4.3.1) with latest version of kirki (using packagist) and just using 1 editor at customizer

![screen shot 2015-10-29 at 1 13 24 pm](https://cloud.githubusercontent.com/assets/1949957/10810754/1b155b8e-7e3f-11e5-8ea3-de11f1c012fe.png)

**Comment by aristath** [comment]
Can you please try git-pulling the latest master branch (without using packagist) and let me know if it works for you there?

**Comment by aristath** [comment]
@ysupr do you still have this issue with the latest commits on the master branch?

**Comment by yogasukma** [comment]
Ah sorry i will checked this day

On Sunday, 15 November 2015, Aristeides Stathopoulos <
notifications@github.com> wrote:

> @ysupr https://github.com/ysupr do you still have this issue with the
> latest commits on the master branch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aristath/kirki/issues/461#issuecomment-156742884.

## 

## 

yoga sukma (@ysupr)
freelance web developer
ysupr.net

**Comment by yogasukma** [comment]
Sorry @aristath got no time to check it, i have download zip version from this repository, and replacing the old ones at vendor directory, but it showing little error 

```
Warning: Illegal offset type in isset or empty in /wp-includes/class-wp-customize-manager.php on line 1205
```

i know it must be something wrong with my own framework, and got no time to fix and check it, so i will report later.
