### ISSUE TITLE
Path issue?

### ISSUE THREAD

**Issue by pingram3541** [themeum/kirki#466]
Works on one server but not on another, any advice would be appreciated.

I've tried the following in my frontend.php:
include_once( dirname( **FILE** ) . '/helpers/kirki/kirki.php' );
and
include_once( get_stylesheet_dir() . '/helpers/kirki/kirki.php' );

But Kirki does not load the proper urls for its assets on the front end, its adding the server path to my url.

console in chrome shows:

GET Error: http:/mydomain.com/var/www/mydomain.com/htdocs/wp-content/themes/mytheme/functions/frontend/helpers/kirki/assets/js/customizer.min.js?ver=1.0.2

The /var/www/mydomain.com/htdocs/ added to the path is coming from something after inclusion of kirki.php

If it helps to know, the first server was an apache build and works just fine, the second is nginx.

**Comment by pingram3541** [comment]
Ok, so I found a fix that seems to work for me.  In another thread I saw a way to pass the url path to Kirki but never came across this in the documentation and feel this might be considered an "older" way of doing things?

The docs lead one to believe all of this is automatically figured out by Kirki but it seems there is still some need in some environments to provide this filter to Kirki.

```
function my_customizer_configuration( $config ) {
  $config['url_path']     = get_stylesheet_directory_uri() . '/functions/frontend/helpers/kirki/';
  return $config;
}
add_filter( 'kirki/config', 'my_customizer_configuration' );
```

**Comment by aristath** [comment]
The docs are currently being rewritten and a couple of things are missing...
Can you share some more info on the server that had these issues?
Was it a live server or local?
If local, was it on windows or a unix system? And what were you using to setup that local environment? (MAMP/LAMP/WAMP/XAMPP/Vagrant/Other)

**Comment by aristath** [comment]
oh, nevermind... I found your comment on #427.
I'll close this one and reopen the other ticket 'cause there's more info there. :+1:
