### ISSUE TITLE
Additional suffix param js_vars for inline css

### ISSUE THREAD

**Issue by pingram3541** [themeum/kirki#467]
Like https://github.com/aristath/kirki/issues/200

Would be nice to specify a suffix for adding !important to inline rules as well as calc and callback.

```
Kirki::add_field( 'my_theme', array(
  'type'        => 'color-alpha',
  'settings'    => 'color-one',
  'label'       => __( 'One Color', 'kirki' ),
  'section'     => 'one_style_colors',
  'default'     => '#2991D6',
  'priority'    => 10,
  'transport'   => 'postMessage',
  'js_vars'     => array(
    array(
      'element'  => $one_style_color,
      'function' => 'css',
      'property' => 'color',
      'suffix'   => '!important',
      //'calc'   => '',
      //'callback' => '',
    ),
    array(
      'element'  => $one_style_bg_color,
      'function' => 'css',
      'property' => 'background-color',
      'suffix'   => '!important',
      //'calc'   => '',
      //'callback' => '',
    ),
  ),
) );
```

**Comment by pingram3541** [comment]
I just found out using target *::selection and *::-moz-selection as an 'element' for some reason cause an error in the console.

Thinking further on this enhancement, a refresh callback is important for situations where one cannot provide media queries (prefixes) for inline styles, we could use the refresh callback to inject the proper css property to an existing style tag, such as by id.

Also just thought about in the case of color where the theme applies an opacity for a specific look, i.e.

```
color: <?php hex2rgba( my_opts_get( 'color-subheader', '#888888' ), .6, true ) ?>;
```

**Comment by aristath** [comment]
@pingram3541 using pseudo-selectors is now possible using the `style` argument introduced by @doitmax in this brilliant commit: https://github.com/aristath/kirki/pull/489

**Comment by aristath** [comment]
This has been fixed.
