### ISSUE TITLE
Repeater Control

### ISSUE THREAD

**Issue by tomcollom** [themeum/kirki#469]
Is the wordpress Plugin version as up to date as what is on Git as cannot seem to get the repeater controller working using the plugin and i appreciate this is a fairly new addition. Currently having followed the instructions and using demo code i just get a text box populated with "object Object. object Object" Thanks a lot and apologies if this is the incorrect channel to ask this question, Tom

**Comment by aristath** [comment]
No, the version on wordpress.org is far behind the one on github.
On github we're actively developing the plugin so there's a lot of new features here.
As soon as we resolve a few bugs we'll be releasing a stable version on w.org

The documentation is for the version on github and is currently undergoing a major rewrite pending the release of the next stable version.

**Comment by tomcollom** [comment]
Thanks a lot - all working beautifully now.
