### ISSUE TITLE
Newest kirki version problems

### ISSUE THREAD

**Issue by reshogun** [themeum/kirki#470]
I installed again my windows to computer and downloaded latest kirki from github server and i got this kind of error message list: 
![errors](https://cloud.githubusercontent.com/assets/3878710/10940410/d52794e6-830e-11e5-9d9e-23735c35b6e4.png)
Previous version did have hickups with win 8

**Comment by reshogun** [comment]
These "errors" render all previously valid code non-valid like in previous 427 issue

**Comment by peazz** [comment]
I wrote a few lines using the wordpress repo version then switched to the version here on Github and had to make several changes including the way required arrays were written.

**Comment by reshogun** [comment]
mark this as solved. It seems my previous download was corrupted.

**Comment by aristath** [comment]
:+1:
