### ISSUE TITLE
Slide element not work

### ISSUE THREAD

**Issue by peazz** [themeum/kirki#472]
Hi,

Trying to use the slider element from this repo here (v1.2) and its not refreshing the UI nor outputting any css to the dynamic file despite correct settings.

Peazz

**Comment by aristath** [comment]
Can you please post the code you're using for the slider field?

**Comment by peazz** [comment]
Hey,

Great plugin mate. its making my life much easier to develop this theme.

I have tried my own code, but also copied and pasted your working code from your demo-theme and it doesn't work which leads me to think that its a JS conflict somewhere.

I have checked console and nothing at all.
