### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by dejanmarkovic** [themeum/kirki#475]
Hi, 
I love Kirki a lot!

I am looking for an "default/reset" option for a slider control. For example my default font size is 14px and my user can change the size to any size they want but if they don't like what they see they can press default/reset button and my slider will load the 14px value.

Please advise.
Thank you so much for the great work you are putting in for this project!

**Comment by aristath** [comment]
hey there!

Have you tried the dev version from github?
This has already been implemented...
