### ISSUE TITLE
Typography control does not working after saving customzier.

### ISSUE THREAD

**Issue by sigaev-pro** [themeum/kirki#476]
I'm testing typography control on Demo Theme.

When I'm changing some typography settings they are applying to text on page. Then, after saving customizer settings I'm trying to change typography setting, and it is not applying to anything. Customizer 'Save' button is disabled, and changing any typography setting neither changing text on page, nor making 'Save' button enabled.

No Javascript errors are appear in console. All scripts are loaded well.

**Comment by aristath** [comment]
@mrnull can you please test the develop branch now and let me know if you're still having this issue?

**Comment by aristath** [comment]
A lot has changed in the past 1-2 months...
Since there has been no more activity on this one I'm assuming it no longer occurs so I'm closing this ticket
@mrnull If you're still having this issue then please don't hesitate to reopen this and post an update on your current status.
