### ISSUE TITLE
Color type firing previous settings on preset click

### ISSUE THREAD

**Issue by lukesalter** [themeum/kirki#477]
I'm struggling with this issue. Changing things on the color picker only fires the 'wp.customize' script on the second click on the 'preset colors' on the left of the picker. Dragging the 'rainbow' around and moving the sliders is firing the 'wp.customize' script fine and works well.

I've noticed that clicking on a preset is changing the value in the input field but it's still selected (in focus) and the text cursor is still in there so it's not firing the wp.customize script. Should this be the case or am I doing something wrong?

I've tried both using the kirki js_vars and writing my own postMessage and I get the same issue with both. I'm also hitting this issue with presets too. As soon as I change to a new multi-option preset all of my colors are delayed by one preset causing chaos!

Hopefully this gif will help...http://www.saltnlight.co.uk/demosite/files/2015/11/Error.gif

Notice how editing the opacity manually in the input field will fire the script but just changing the bracket at the end won't do it?! Weird. Pressing Enter doesn't fire it either which I was expecting, perhaps just an update button would be good to refire the wp.customize script.

**Comment by pingram3541** [comment]
Same here.  I was wondering if mine was specific to not having a "color" field as it mentions something about alphas not working unless there is at least 1 color field, which I am not using in my project.  I just didn't look into it any further to see if that was the issue.

**Comment by lukesalter** [comment]
I've been looking into this and I've noticed that there's a script firing to sanitize the input field (turning it from rgb to rgba to regular #). Is the wp.customize script firing before the sanitize script causing it not to work?

Perhaps the wp.customize script needs to fire as a callback to it?! I'm only guessing with this stuff. I'm new to kirki but loving it.

**Comment by pingram3541** [comment]
I truly haven't looked at it but I can say, for my alpha fields, I am using js_vars to update my preview vs the wp.customize refresh, using postMessage transport and still seeing the same quirk from the color picker exactly as you provided in your gif.

**Comment by aristath** [comment]
Hey guys,
To be honest I've been struggling with this one for a long time.
It's a minor nuisance so I haven't spent a lot of time debugging it, but I'm afraid my JS skills are a bit lacking...
The code I used is derived from http://pluto.kiwi.nz/2014/07/how-to-add-a-color-control-with-alphaopacity-to-the-wordpress-theme-customizer/ and it suffers the same quirks:
- changes don't fire properly
- the control doesn't work unless there's a default color control in the customizer

I've been thinking that I'll probably have to rebuild the control from the ground up and find a better solution, but so far I've been unable to do that.

If one of you can come up with a solution I'd be more than happy to merge any pull requests...

**Comment by pingram3541** [comment]
For now, wrapping the change event in a 100ms delay seems to do the trick in /assets/js/customizer.js.  Of course for this to work on a live site remember to add this to the minified version.

```
$control.wpColorPicker({ // change some things with the color picker
    clear: function(event, ui) {
        // TODO reset Alpha Slider to 100
    },
    change: function(event, ui) {
        //send ajax request to wp.customizer to enable Save & Publish button
        setTimeout(function(){
            var _new_value = $control.val();
            var key = $control.attr('data-customize-setting-link');
            wp.customize(key, function(obj) {
                obj.set(_new_value);
            });
            // change the background color of our transparency container whenever a color is updated
            var $transparency = $control.parents('.wp-picker-container:first').find('.transparency');
            // we only want to show the color at 100% alpha
            $transparency.css('backgroundColor', ui.color.toString('no-alpha'));
        },100);
    },
    palettes: palette // remove the color palettes
});
```

The change event is firing just slightly before the value in the input is actually being updated from the click event.

**Comment by aristath** [comment]
@pingram3541 brilliant!
That was the piece I was missing...
I just finished rebuilding the color-alpha control and used https://github.com/23r9i0/wp-color-picker-alpha
Can you please pull the master branch again and test it? It seems to be working fine now. :)

**Comment by pingram3541** [comment]
I'm trying to figure out how to grab the event object's target value which is the correct color we need to update with vs setting the _new_value to the dom node's value which is always slightly before the input value attribute is actually updated.  You'll see in the inspector w/ console.log(event) that its there but look at the DOM inspection of the input field, its value att is still the previous value.  Everytime I try to the get event object's target value it results in the DOM node's value instead.

**Comment by aristath** [comment]
@pingram3541 did you try it with the new commits?

**Comment by pingram3541** [comment]
@aristath Yep, works beautifully.

**Comment by aristath** [comment]
Awesome!
Thanks for the help man, it would have taken me hours to figure out it needed a delay. :+1: 

Closing this ticket as resolved.

**Comment by lukesalter** [comment]
Loving this. Works great for me this end.
