### ISSUE TITLE
Notice: Undefined index: capability 

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#480]
After update Kirki to master ver. from github I have this notices:
Notice: Undefined index: capability in kirki/includes/class-kirki-config.php on line 61
Notice: Undefined index: option_type in kirki/includes/class-kirki-config.php on line 62
Thanks!

**Comment by aristath** [comment]
That makes no sense...
How are you adding your config?
Can you please post your code here?

**Comment by padalec** [comment]
Nevermind I found what was wrong in older version of this plugin configuration was setup by:
add_action( 'kirki/config', array( $this, 'init' ) );
when I removed this code everything is OK

**Comment by aristath** [comment]
:+1: ok, great!

Closing this ticket.
