### ISSUE TITLE
Kirki not working when not logged in

### ISSUE THREAD

**Issue by lukesalter** [themeum/kirki#481]
Here's a fun one for you to wrap your brains around...

When logged in as a the super admin on a network site I'm seeing the kirki dynamic css fine. I can also see the site as intended when I'm in the customizer. Great for me...

When I log in as an admin of one of the network sites the dynamic css can't generate properly. Safari seems to think it's having an issue with 'strict mode' but this can't be the case some of the time and not others can it?! It's claiming that CSS MIME types are not allowed in strict mode.

Any thoughts you guys have got to get my closer to cracking this would be awesome. I'm loving the plugin and keen to get it working well on my multi-site for my clients.

Why would the log in status affect how the stylesheet is created?

**Comment by lukesalter** [comment]
Here's the site: http://www.saltnlight.co.uk/ If it's grey and white then you've seeing the same issue that I am.

**Comment by aristath** [comment]
The CSS can be seen here: http://www.saltnlight.co.uk/wp-admin/admin-ajax.php?action=kirki_dynamic_css

From what I can see there are some PHP errors there...
Can you please try deactivating all other plugins? Perhaps this is a conflict of some sort...

OR there's another issue with your theme. See this http://aristeides.com/blog/wordpress-headers-already-sent-by/ for a possible cause and check your theme's functions.php file as well as your wp-config.php file.
If you have closing PHP tags `?>` at the end, remove them.
In fact, if you have **any** php file in your theme with `?>` at the end, remove that closing PHP tag.

Let me know if that helps!

**Comment by aristath** [comment]
Your dynamic-css seems to be working fine now, I don't see any errors there.
I'll just go ahead and close this ticket.
If however this is not resolved then please feel free to reopen this and post an update on your current status. :+1:
