### ISSUE TITLE
Google Font output when using defaults

### ISSUE THREAD

**Issue by doitmax** [themeum/kirki#482]
Hi,

first thank you guys for this fantastic tool. I am just about to start working with it but already love the functionality and simplicity to create things :)

I have a little question about using Google Fonts and using default values for a font-family select field.

So basically my setup for a font-family dropdown with Google Fonts looks like the example from the Wiki:

``` php
Kirki::add_field( '', array(
    'type'     => 'select',
    'settings' => 'my_setting',
    'label'    => __( 'Font Family', 'example' ),
    'section'  => 'base_typography',
    'default'  => 'Roboto',
    'priority' => 20,
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output' => ( 'Roboto' != Kirki::get_option( 'dummy_config', 'my_setting' ) ) ? array(
        'element'  => 'body',
        'property' => 'font-family',
   ) : null,
) );
```

In the code example above i am checking for the default value in addition to not generate the output when the option matches the default value. But when using Google Fonts this is of course not outputting the Google Font link in the `<head>`.

The idea is to keep generating dynamic css at a minimum and avoid unnecessary output by using the default CSS values from the styles.css as much as possible.

Now my question is how to handle such a situation best?

Should i check for the default value in my theme and include the the Google Font link on my own or is there any other way Kirki can handle such a situation?

Of course i can loop any other font-family in my set of customizer options and prevent double output in the head. Not really a big problem, but i would like to keep it as simple as possible and stick with any build in solution, if there is any :)

Cheers,
Dennis

**Comment by aristath** [comment]
I think I've got it wrong in the docs...
Try it like this:

``` php
Kirki::add_field( '', array(
    'type'     => 'select',
    'settings' => 'my_setting',
    'label'    => __( 'Font Family', 'example' ),
    'section'  => 'base_typography',
    'default'  => 'Roboto',
    'priority' => 20,
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output' => ( 'Roboto' != Kirki::get_option( 'dummy_config', 'my_setting' ) ) ? array(
        array(
            'element'  => 'body',
            'property' => 'font-family',
        ),
   ) : null,
) );
```

Let me know if that works so that I may change it in the docs as well. :+1:

**Comment by aristath** [comment]
oh, and btw I would advise against using the `Kirki::get_option()` method.
Try using `get_option()` or `get_theme_mod()` instead, depending on what you're using: https://github.com/aristath/kirki/wiki/Getting-the-values-of-your-fields

**Comment by doitmax** [comment]
Thank you for the answer. I have adjusted my code as you have suggested by adding the missing <code>array()</code> in the <code>output</code> and replaced the <code>Kirki::get_option()</code> method. But unfortunately there is still no output of the default google font in the head.

``` php
Kirki::add_field( '', array(
    'type'     => 'select',
    'settings' => 'my_setting',
    'label'    => __( 'Font Family', 'example' ),
    'section'  => 'base_typography',
    'default'  => 'Roboto',
    'priority' => 20,
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output' => ( 'Roboto' != get_theme_mod( 'my_setting', 'Roboto' ) ) ? array(
        array(
            'element'  => 'body',
            'property' => 'font-family',
        ),
    ) : null,
) );
```

Checking for <code>get_theme_mod()</code> output with <code>var_dump()</code> gave me the correct output of <code>string(6) "Roboto"</code> in this case.

I also set up a test environment locally with the demo theme installed and added a google font select. Then i removed the demo typography field in order to avoid conflicts.

The result was that there also was no output of the google font link and the default browser font was showing for the demo page.

**Comment by aristath** [comment]
@doitmax I'm sorry for the delay here....

> Should i check for the default value in my theme and include the the Google Font link on my own or is there any other way Kirki can handle such a situation?

No, I'm afraid there's no way Kirki can handle this... 
You'll have to check the value of the theme_mod and manually add the google-font link to your head if the value equals your default value....

Something like this should do the trick:

``` php
function google_fonts() {
    $query_args = array(
        'family' => 'Roboto'
        'subset' => 'latin,latin-ext',
    );
    if ( 'Roboto' == get_theme_mod( 'my_setting', 'Roboto' ) ) {
        wp_register_style( 'google_fonts', add_query_arg( $query_args, "//fonts.googleapis.com/css" ), array(), null );
    }
}
add_action( 'wp_enqueue_scripts', 'google_fonts' );
```

**Comment by doitmax** [comment]
That is closely to my approach after I had examined the Kirki code more closely. Anyway, thanks for having a look.
