### ISSUE TITLE
Question: Is the CSS only output to the Head?

### ISSUE THREAD

**Issue by bahia0019** [themeum/kirki#485]
Going through the documentation, I see that the CSS can be output to head. Is there an option to send out to an actual CSS file to keep the code semantic?

Thanks in advance.

**Comment by pingram3541** [comment]
For semantic purposes it's the theme's job to determine where the css will be loaded for site visitors but for the purpose of the customizer and it's preview functionality, you'll likely want to retain the inline css for the live preview capability otherwise that goes out the door.

**Comment by aristath** [comment]
@bahia0019 the CSS is no longer added inline, instead we're enqueing it like a file using a format like `domain.com/wp-admin/admin-ajax.php?action=kirki_dynamic_css` so it's pretty semantic.. :+1:
