### ISSUE TITLE
Dynamic CSS slowing down page load

### ISSUE THREAD

**Issue by doitmax** [themeum/kirki#487]
When checking the network tab in my developer tools the <code>kirki_dynamic_css</code> action from admin-ajax.php is really slowing down the page load massively.

![image](https://cloud.githubusercontent.com/assets/241255/11363737/ff55e64a-929b-11e5-84f2-6e3fbcb62d84.png)

I have only 5 Styles in the output of this file and things are that slow already. I do not want to imagine how long it would take to load the page with a lot of styles in the output.

Is this a known issue?

Edit: 

Just two more options changed in the customizer and + 0.76 seconds:

![image](https://cloud.githubusercontent.com/assets/241255/11367656/5bdd3de6-92b5-11e5-841d-af89df365367.png)

**Comment by aristath** [comment]
@doitmax that's weird... I'm working on a theme with 920 options and never had an issue like that.
Can you please post a link to your site so that I may examine it?

**Comment by doitmax** [comment]
Hi, thanks for the answer. Actually i am working on a localhost. Could that be the problem? I will test it with an online WordPress installation and get back to you.

**Comment by aristath** [comment]
@doitmax any news on this one?

**Comment by doitmax** [comment]
Hi, sorry, actually not. I haven't tested it yet. I will get back to you when I've done it.

**Comment by RonalddeRooij** [comment]
Hi @aristath I'm having the same problem. I have like 30 options with dynamic css and the loading time has been increased to 8 seconds up to 28 seconds sometimes. Could I send you my theme based on _tk combined with your awesome plug-in!!?

**Comment by aristath** [comment]
@RonalddeRooij sure thing, that would really help me understand what goes on.

**Comment by RonalddeRooij** [comment]
Thanks! I have made a dropbox link to my theme: https://www.dropbox.com/s/17n611ghafml6vn/_rdr.zip?dl=0 I couldn't upload it here.

**Comment by RonalddeRooij** [comment]
Update: I have found out that it had something to do with our development server. Our live server made the load time to 0.7 second instead of 28 seconds.

**Comment by doitmax** [comment]
@RonalddeRooij is this development server on a localhost?

**Comment by RonalddeRooij** [comment]
@doitmax Our development server is a local network.

**Comment by doitmax** [comment]
@RonalddeRooij ok thanks, i will check this now with an online version too.

**Comment by doitmax** [comment]
Ok, it turns out it seems to be a problem when using Kirki on a localhost development environment like MAMP. So closing it since this doesn't seem to be a problem of Kirki at all that needs to be solved.
