### ISSUE TITLE
Is it possible to associate an existing setting with a Kirki control?

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#491]
I would like to replace the default blog tagline/description field with a wysiwyg editor. I can easily replace the control or change its type using the Customizer API, but how would I achieve this with Kirki when the setting and control functions are tied to each other?

**Comment by aristath** [comment]
First you'll have to remove the control and then add it normally.
So something like this:

``` php
add_action( 'customize_register', function( $wp_customize ) {
    $wp_customize->remove_control( 'blogdescription' );
} );
Kirki::add_config( 'single_settings', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'option',
) );
Kirki::add_field( 'single_settings', array(
    'settings' => 'blogdescription',
    ............
    ............
) );
```
