### ISSUE TITLE
Not able to register new control type

### ISSUE THREAD

**Issue by jiteshjk** [themeum/kirki#492]
Hello, i am trying to define/register new control type using this sample code but
https://github.com/aristath/kirki/wiki/Registering-new-control-types

but its throwing this warning
<b>Warning</b>:  array_key_exists() expects parameter 2 to be array, null given in <b>E:\xampp\htdocs\free-themes\wp-content\plugins\kirki\includes\class-kirki-control.php</b> on line <b>79</b><br />

**Comment by aristath** [comment]
@jiteshjk I'm sorry about that... the code on the docs was missing a line, that's why you were getting these errors.
Please check the docs again, I fixed them (the missing line was `return $controls;`)

**Comment by jiteshjk** [comment]
Thanks @aristath
