### ISSUE TITLE
Fatal error after update kirki framework

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#50]
Hi, 
today I upgrade kirki framework from github repository and after that I got fatal error below:
Fatal error: Class 'Kirki_Customize_Radio_Control' not found in ..\kirki\includes\class-kirki-controls.php on line 19

**Comment by aristath** [comment]
Hey there!

Please make sure you delete your previous nstance of kirki first and then try re-pulling everything... perhaps something went wrong and not all files were properly pulled?
I can't replicate this...

**Comment by padalec** [comment]
I deleted old version and get newest by "clone on desktop" and fatal error still is displayed. I try to added field radio image. This is my field array:

<pre>Array
(
    [type] => radio
    [setting] => header_style
    [section] => header
    [mode] => image
    [label] => Select header style
    [choices] => Array
        (
            [image] => http://localhost/igniter/wp-content/themes/igniter/assets/img/admin/layout/header_image.png
            [slider] => http://localhost/igniter/wp-content/themes/igniter/assets/img/admin/layout/header_slider.png
            [titlebar] => http://localhost/igniter/wp-content/themes/igniter/assets/img/admin/layout/header_titlebar.png
            [without] => http://localhost/igniter/wp-content/themes/igniter/assets/img/admin/layout/header_without.png
        )
    [priority] => 1
    [default] => without
)
</pre>

Regards

**Comment by aristath** [comment]
What is the code you're using? Do you have it somewhere on github?

**Comment by padalec** [comment]
No I don't :( I create my own theme.
I think the problem is Kirki::include_customizer_controls() method  this code: 

<pre>$controls = $this->get_controls();</pre>

return empty array

**Comment by aristath** [comment]
...why?
How did you come to that conclusion?
It works fine for me... What PHP version are you using? Can you please make sure you're using at least 5.3?

**Comment by padalec** [comment]
I var_dump $controls variable and is empty array. My PHP version is 5.5.12

**Comment by padalec** [comment]
Ok I think I found where problem is. In  code below you use 1 priority but in my code I use 10 and 11 priority number so your code is rune before mine:

<pre>add_action( 'customize_register', array( $this, 'include_customizer_controls' ), 1 );</pre>

**Comment by aristath** [comment]
That action is added on the `customize_register`.
Where do you add your own??
The Kirki fields should be added on the `kirki/controls` hook like this:

``` php
<?php

/**
 * Create the setting
 */
function my_custom_setting( $controls ) {

    $controls[] = array(
        'type'     => 'text',
        'setting'  => 'my_setting',
        'label'    => __( 'My custom control', 'translation_domain' ),
        'section'  => 'my_section',
        'default'  => 'some-default-value',
        'priority' => 1,
    );

    return $controls;
}
add_filter( 'kirki/controls', 'my_custom_setting' );
```

**Comment by padalec** [comment]
Yes I know but in my theme I add panel by $wp_customize->add_panel( );  and I have two place when I used

<pre>
add_action( 'customize_register', array( $this, 'init' ), 10 ); 
add_action( 'customize_register', array( $this, 'init' ), 11 );
</pre>

action hooks. First is in class for register panels and second in class for register sections. 
So I need to priority this.

**Comment by aristath** [comment]
No, you don't.
I'm also using panels, sections etc.

Take a look at this: https://github.com/presscodes/maera-bootstrap/blob/master/customizer.php

Cheers! :smile:

**Comment by padalec** [comment]
This is not fix my problem. You have only one class but in my framework I have a little more complex abstraction so I need to priority customize_registe action hook

**Comment by aristath** [comment]
Perhaps if you could share some more details about your current implementation I would be able to assist....
It doesn't matter how many classes or functions you have, it could be 1 or 100. The point is that you will have to use a _separate method_ to register your panels/sections like on [lines 55-118](https://github.com/presscodes/maera-bootstrap/blob/master/customizer.php#L55-L118) of the link I posted above, and add that to `customize_register` like on [line 7](https://github.com/presscodes/maera-bootstrap/blob/master/customizer.php#L7).
Then your settings will be on a different function (for example [lines 120-164](https://github.com/presscodes/maera-bootstrap/blob/master/customizer.php#L120-L164), added to [`kirki/controls`](https://github.com/presscodes/maera-bootstrap/blob/master/customizer.php#L9)

If there's something I don't understand about your current implementation then please share some more details so that I may figure out what goes on...

**Comment by padalec** [comment]
Hi there,
Perhaps my classes diagrams can helps you to understand my class structure? 

Controls: http://biznes-dynamit.pl/test/michal/controls.png
Panels: http://biznes-dynamit.pl/test/michal/panel.png
Sections: http://biznes-dynamit.pl/test/michal/section.png
Customizer: http://biznes-dynamit.pl/test/michal/customizer.png

I just need from you to change priority in Kirki class constructor line 47 from 1 to 12 or greater than 10
From:

<pre>add_action( 'customize_register', array( $this, 'include_customizer_controls' ), 1 );</pre>

To

<pre>add_action( 'customize_register', array( $this, 'include_customizer_controls' ), 12 );</pre>

**Comment by aristath** [comment]
Are you still having this issue?

**Comment by aristath** [comment]
Due to inactivity and the fact that noone else has reported it I'm assuming this has been fixed.

**Comment by padalec** [comment]
Hi, 
after updating kirki my problem was resolved thanks!
