### ISSUE TITLE
Fatal Error on upgrade to v2

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#503]
Hi Aris, 

I had a fatal error upgrading from the beta version to the final release of version 2:

```
Fatal error: Class 'Kirki_Google_Fonts_Registry' not found in /Users/luismartins/Sites/webipack.dev/wp-content/plugins/kirki/kirki.php on line 39
```

Something with my install?

**Comment by developerzinan** [comment]
I got this error also. Really upset to get this error from a better toolkit. Hopefully developer will take care it as soon as possible.

**Comment by lmartins** [comment]
How about beying responsible and help the developer test during the beta period? Geez, I don't get what makes you feel entitled to demand anything from someone who is giving you his hard work in the first place.

**Comment by aristath** [comment]
Can you guys try moving the files from `includes/google-fonts/` to the `includes/` folder?
Let me know if that fixes the issue!
It seems to be working fine for me so I assume this has something to do with the PHP versions and the setup environment in general... The autoloader should be picking these up without any issues!!

**Comment by lmartins** [comment]
Weirdly I don't have that `google-fonts` folder you mention after upgrading to v2 final:
https://www.dropbox.com/s/aq2x4c21ec2ov4o/Screenshot%202015-12-06%2014.40.49.png?dl=0

**Comment by andreabazerla** [comment]
I've the same problem, and I try to comment row 39 in /kirki.php

```
$kirki->font_registry = new Kirki_Google_Fonts_Registry();
```

But it doesn't work, another error:

```
Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'Kirki_Init' not found in /var/www/html/wp-content/plugins/kirki/includes/class-kirki.php on line 25
```

Absurd because the file class-kirki.php in /includes there is!
So I try to change permissions of plugin as 777 but nothing.
I'm confused.

**Comment by aristath** [comment]
Can you try pulling the develop branch from https://github.com/aristath/kirki/tree/develop and let me know if that works for you?
If yes, then I'll release a new version immediately.

**Comment by lmartins** [comment]
Works here.

**Comment by aristath** [comment]
@lmartins thanks for checking so quickly buddy...
OK, I just released version `2.0.1`

Closing this ticket :+1:

**Comment by lmartins** [comment]
It seems that `2.0.1` shows the same problem. It probably something related to my system.
Im testing in a local environment, running MAMP on OSX with PHP 5.6.10 and Xdebug enabled. Besides that im also running WordPress beta 4.4 and a bunch of plugins. 

Heres the full stack trace:

```
[06-Dec-2015 18:18:19 UTC] PHP Fatal error:  Class 'Kirki_Google_Fonts_Registry' not found in /Users/luismartins/Sites/webipack.dev/wp-content/plugins/kirki/kirki.php on line 39
[06-Dec-2015 18:18:19 UTC] PHP Stack trace:
[06-Dec-2015 18:18:19 UTC] PHP   1. {main}() /Users/luismartins/Sites/webipack.dev/wp-admin/network/plugins.php:0
[06-Dec-2015 18:18:19 UTC] PHP   2. require_once() /Users/luismartins/Sites/webipack.dev/wp-admin/network/plugins.php:11
[06-Dec-2015 18:18:19 UTC] PHP   3. require_once() /Users/luismartins/Sites/webipack.dev/wp-admin/network/admin.php:13
[06-Dec-2015 18:18:19 UTC] PHP   4. require_once() /Users/luismartins/Sites/webipack.dev/wp-admin/admin.php:31
[06-Dec-2015 18:18:19 UTC] PHP   5. require_once() /Users/luismartins/Sites/webipack.dev/wp-load.php:37
[06-Dec-2015 18:18:19 UTC] PHP   6. require_once() /Users/luismartins/Sites/webipack.dev/wp-config.php:97
[06-Dec-2015 18:18:19 UTC] PHP   7. include_once() /Users/luismartins/Sites/webipack.dev/wp-settings.php:219
[06-Dec-2015 18:18:19 UTC] PHP   8. Kirki() /Users/luismartins/Sites/webipack.dev/wp-content/plugins/kirki/kirki.php:57
```

**Comment by aristath** [comment]
OK, I was able to replicate the issue.
It only occurs when a site has version 1.0.2 installed, and it's updating to version >= 2.0 using the WordPress updater.
Is that correct?
If you delete the plugin and then re-upload it, it works perfectly fine.
Can you please verify that?
It's a conflict between the previous and the current autoloaders.
Version 1.0.2 required PHP 5.3 and was using features like namespaces etc.
The new version got rid of all those goodies in order to be compatible with PHP 5.2 as well, and as a result the autoloader also changed.

**Comment by developerzinan** [comment]
Hi aristath,
I delete my previous version and then install the latest 2.0.1 from WordPress plugin repository but after that i got that Fatal error:  Class 'Kirki_Google_Fonts_Registry' ........ and after that when i install kirki from  https://github.com/aristath/kirki/tree/develop then its working fine . So is there any reason behind that ? Sorry if i asked an ordinary question ...

**Comment by aristath** [comment]
Working on a fix as we speak, I'll have it ready in a few minutes. :)

**Comment by developerzinan** [comment]
WOW ! thanks aristath. Kirki is awesome. It saves my time a lot, just love it . :)

**Comment by aristath** [comment]
Can you guys try this again?
I just released 2.0.2 and in my tests it seems to be working fine & updating without any issues.
[The solution was fugly](https://github.com/aristath/kirki/blob/master/kirki.php#L30-L67), but at least it works....

**Comment by andreabazerla** [comment]
```
Warning: include_once(/var/www/html/wp-content/plugins/kirki/includes/class-kirki-active-callback.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/kirki/kirki.php on line 34
```

**Comment by lmartins** [comment]
Im getting a lot of warnings now, but what it breaks is the final one:

```
Fatal error: Class 'Kirki_Field_Sanitize' not found in /Users/luismartins/Sites/webipack.dev/wp-content/plugins/kirki/includes/class-kirki-explode-background-field.php on line 3
```

**Comment by aristath** [comment]
Lets try this again.... 2.0.3 should be available in a couple of minutes

**Comment by andreabazerla** [comment]
Ok I try, plugin can be activated now! :+1: Thank you!

**Comment by lmartins** [comment]
Installed from github to recover from previous crash, which pulled 2.0.3 so isn't asking for upgrade anymore as it is running the latest. All working fine here too.

**Comment by aristath** [comment]
:relieved: finally...
My apologies for the inconvenience to all of you. This was a really huge update which took 4 months of development and almost everything changed internally. At least it got fixed within a few hours...
If you find any more bugs/issues please create new tickets so that I may fix them ASAP. :+1:

**Comment by lmartins** [comment]
Amazing work Aris, many thanks for all the help.

**Comment by abides** [comment]
version 3.0.25 and im getting Fatal error: Class 'Kirki_Init' not found in /public_html/wp-content/plugins/kirki/core/class-kirki.php on line 26

edit: when i try to activate plugin, new installation.
