### ISSUE TITLE
Kirki & Customizer API

### ISSUE THREAD

**Issue by andreabazerla** [themeum/kirki#505]
Hi, can I use Kirki with Customizer API?

For example, I want to include in a section created with Kirki a my custom button to execute a my script in JavaScript. So I need to get the section's slug to include my custom button, it is possible?

Thanks

**Comment by aristath** [comment]
@AndreaBazerla 
To be honest I didn't understand 100% what it is that you're trying to achive, but yes. You can use the customizer API with Kirki...
Kirki is nothing but a wrapper to the customizer control that simplifies adding new controls & settings, and also adds some controls & helpers for styling etc.
Other than that, it's 100% customizer.
