### ISSUE TITLE
L85 - class-kirki-customizer-scripts-postmessage.php

### ISSUE THREAD

**Issue by pingram3541** [themeum/kirki#507]
Thought maybe this was a typo from likely a copy/paste.  In the js_vars array the suffix key has the same value as prefix.

```
$js_vars = array(
    ...
    'suffix'   => ( isset( $js_vars['prefix'] ) ) ? esc_js( $js_vars['prefix'] ) : '',
);
```

**Comment by aristath** [comment]
You're right, this was a typo.
I just released 2.0.1 a couple of minutes ago so this one will be on 2.0.2 :+1: 
Fixed in the develop branch.
I'll probably just wait a few hours and see if any more issues come up so that I include all fixes in 1 update.

**Comment by pingram3541** [comment]
Curious, would you prefer I pm you direct, ie skype if I run across small stuff like this vs and issue here in git?  Tbh I haven't fully adopted git and suppose I could look up a pull request write up somewhere, is that lazy? =)

**Comment by aristath** [comment]
LOL if you can't create PRs then creating new tickets is the way to go. :+1:

**Comment by aristath** [comment]
If you PM me directly I will probably get the message while working on my day job in which case I won't deal with it immediately and by the time I finish work I won't remember it.
So creating new tickets is safer. At least this way they are here and I can deal with them 1-by-1. :)

**Comment by pingram3541** [comment]
Thanks for the clarity on this.  I'm reading up on PR's right now.
