### ISSUE TITLE
Customizer default style and reload after updating not working in theme embed.

### ISSUE THREAD

**Issue by developerzinan** [themeum/kirki#511]
Hi, I am using kirki 2.0.3 but customizer default style and function not working in theme embed mode. But working fine as plugin. Could you please look after it ?

**Comment by developerzinan** [comment]
Well got the solution at last ... 

``` php
function imax_customizer_config( $args ) {

    $args['url_path'] = get_template_directory_uri() . '/inc/kirki/';
    return $args;

}
add_filter( 'kirki/config', 'imax_customizer_config' );
```

thanks for the awesome toolkit

**Comment by aristath** [comment]
@developerzinan I just saw this ticket now...
I'm glad you managed to figure this one out!
