### ISSUE TITLE
Notice messages, little "mess" in the look and missing features

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#515]
I have those notice since I moved to 2.0.3:

Notice: Undefined index: capability in /home/.../inc/kirki/includes/class-kirki-config.php on line 61
Notice: Undefined index: option_type in /home/.../inc/kirki/includes/class-kirki-config.php on line 62
Notice: Undefined index: option_name in /home/.../inc/kirki/includes/class-kirki-config.php on line 63
Notice: Undefined index: compiler in /home/.../inc/kirki/includes/class-kirki-config.php on line 64
Notice: Undefined index: capability in /home/.../inc/kirki/includes/class-kirki-config.php on line 61
Notice: Undefined index: option_type in /home/.../inc/kirki/includes/class-kirki-config.php on line 62
Notice: Undefined index: option_name in /home/.../inc/kirki/includes/class-kirki-config.php on line 63
Notice: Undefined index: compiler in /home/.../inc/kirki/includes/class-kirki-config.php on line 64

And some strange look/behaviours:

![screen shot 2015-12-06 at 23 57 40](https://cloud.githubusercontent.com/assets/527057/11616168/bf3a5a4e-9c75-11e5-9ffe-f99a8cdba6df.png)

Is that on my end only? TIA

**Comment by aristath** [comment]
It was probably due to the way the filter was added on your theme....
I made it a bit more bulletproof now. :+1:
