### ISSUE TITLE
New "selectize" script

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#516]
Hello, in version 1.0.2 I created my custom fields to manage custom Google and Typekit fonts, and I assigned the class "select2" to enable chosen for those fields (also discussed here #326). Is there a class to enable "selectize" on version 2.0+ or have I to inititialize the script personally on my JS file? I don't want to risk the bad performance like in the issue above.

Thank you.

**Comment by pixedelic** [comment]
Ah, and the SCSS of selects doesn't render "optgroup" header, they have the same look of the other options.

**Comment by pixedelic** [comment]
Just discovered Selectize completely removes any data-attributes of the original select options, definitely not a big deal, how can I retrieve original data... may I ask you why have you decided to abandon Chosen? Chosen allowed to work with selects via javascript and only rendered their look, with selectize the original select box seems disappeared and unreachable, I have to manipulate via selectize only. Am I right?

**Comment by aristath** [comment]
The problem with select2 was that there were lots of conflicts with other plugins that were also using it (for example ACF),  it's more difficult to style than selectize, and also selectize is a lot lighter.
Selectize has a pretty good API too! https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md

**Comment by aristath** [comment]
oh, and also it has the ability for multi-selects as well as reordering the selected items out of the box. ;)

**Comment by pixedelic** [comment]
I see... thank you for your precious time
