### ISSUE TITLE
Class Kirki_Sanitize not working

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#517]
With the new update, class Kirki_Sanitize is not working. The file only contains:

```
class Kirki_Sanitize extends Kirki_Customizer {}
```

perhaps it should be:

```
class Kirki_Sanitize extends Kirki_Field_Sanitize {}
```

I have some released themes have been using Kirki_Sanitize for unfiltered sanitize. Is there any specific reason why you change the classname?

**edit: I used the Kirki_Sanitize::unfiltered function in some `sanitize_callback` attributes. After digging to your codes I found the functions is moved to Kirki_Sanitize_Values class.

**Comment by aristath** [comment]
Kirki_Sanitize was a pretty generic classname and renaming it was part of a larger restructuring of the plugin.
The base class will remain empty and it will simply act as a parent class for other classes like for example the `Kirki_Sanitize_Values`, `Kirki_Field_Sanitize` and in the future more.

The `Kirki_Sanitize::unfiltered()` method that we had in previous versions is pretty simple to replicate...
All you have to do is create something like this:

``` php
function my_unfiltered_callback( $value = '' ) {
    return $value;
}
```

and then just `my_unfiltered_callback` as a `sanitize_callback`
