### ISSUE TITLE
Import external file JavaScript/jQuery

### ISSUE THREAD

**Issue by andreabazerla** [themeum/kirki#518]
Hi, I use underscores.me and I try this but it doesn't work.
It works only if i put onclick="alert("ok");" inline in div of default field.
I want know where and how I can import my js files to invocate my functions.
Thanks 

/wp-content/themes/test/inc/customizer.php

```
Kirki::add_field( 'test', array(
    'type'        => 'custom',
    'settings'    => 'setting',
    'label'       => __( '', 'test' ),
    'description' => __( '', 'test' ),
    'help'        => __( '', 'test' ),
    'section'     => 'test',
    'default'     => '<div id="test" class="button">+</div>',
    'priority'    => 0,
) );
```

/wp-content/themes/test/js/customizer.js

```
( function( $ ) {
      $("#test").click(function() {
            alert("ok");
      });
} )( jQuery );
```

**Comment by andreabazerla** [comment]
I think that I found the right file to include external functions .js: wp-content/plugins/kirki-master/assets/js/kirki-tooltip.js is right? Because if I include a function in customizer.js it doesn't work. Why?

**Comment by pingram3541** [comment]
With jQuery, any elements added to the DOM after doc.ready don't provide events such a "click" however using the "on" method you can delegate from a parent element that did exist in the DOM on initial page load, such as "body" or even the customize preview div if the customize.js script is loading in the parent window.  The following should work.

```
( function( $ ) {
      $("body").on("click", "#test", function() {
            alert("ok");
      });
} )( jQuery );
```

or 

```
( function( $ ) {
      $("#customize-preview iframe").contents().find("body").on("click", "#test", function() {
            alert("ok");
      });
} )( jQuery );
```
