### ISSUE TITLE
Are text type fields working?

### ISSUE THREAD

**Issue by pingram3541** [themeum/kirki#520]
I'm seeing the list-item in the customizer DOM but no input being generated.  When I change to textarea, code, slider... it works.  I haven't tested all types.  v2.0.3

This only happens when defining 'type' => 'text' but I found if I elect to provide a type (which text is default) the field works.

**Comment by aristath** [comment]
Using this it seems to be working fine... https://github.com/aristath/kirki/blob/master/demo-theme/functions.php#L116-L125
What code are you using that doesn't render the input?

**Comment by pingram3541** [comment]
Thanks for checking.  I just tested using the following but nothing shows up until I comment out:

``` php
'type' => 'text',
```

Must be something with my setup/theme or another plugin as the following code is my test base but I just wanted to be sure it was on my end only.

This is my test page using a require_once line in my themes functions.php

``` php
/**
 * Include Kirki toolbox
 */
if ( ! class_exists( 'Kirki' ) ) {
    include_once( dirname( __FILE__ ) . '/includes/kirki/kirki.php' );
}

/**
 * Add config for types
 * use wp_options table, key 'pmitheme'
 */  
Kirki::add_config( 'pmi_theme', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'option',
    'option_name'   => 'pmitheme',
) );

/**
 * Add panels
 * create "Theme Options" panel
 */
Kirki::add_panel( 'pmi_frontend', array(
    'priority'    => 10,
    'title'       => __( 'Theme Options', 'pmi-opts' ),
    'description' => __( 'Edit theme options', 'pmi-opts' ),
) );

/**
 * Add sections
 * Create "Test Section"
 */    
Kirki::add_section( 'pmi_test_section', array(
    'title'          => __( 'Test Section' ),
    'description'    => __( 'Test test', 'pmi-opts' ),
    'panel'          => 'pmi_frontend',
    'priority'       => 160,
    'capability'     => 'edit_theme_options',
    'theme_supports' => '',
) );

/**
 * Add fields
 * add "text" type field to "Test Section"
 */    
Kirki::add_field( 'pmi_theme', array(
    'type'        => 'text', //this only works if I remove this line
    'settings'    => 'text_demo',
    'label'       => esc_attr__( 'Text Control', 'pmi-opts' ),
    'help'        => esc_attr__( 'This is a tooltip', 'pmi-opts' ),
    'default'     => esc_attr__( 'This text is entered in the "text" control.', 'pmi-opts' ),
    'section'     => 'pmi_test_section',
    'default'     => '',
    'priority'    => 10,
) );
```

**Comment by aristath** [comment]
I just pasted the code above in a blank theme and it seems to be working fine so there must be some kind of conflict...
Do you have the theme available on a github repository perhaps so that I may download it and debug?
Have you tried deactivating all other plugins to see if perhaps there's a conflict there?

**Comment by pingram3541** [comment]
Hmm, must be something server side, tested with twentyfifteen theme and no plugins active, no caching.

-When I comment out the 'type' option it works but I get errors in my php log about a missing type parameter.
-When I set it to anything random like 'type' => 'some-type' it works but I get a generic input vs the kirki styled one.
-When I set 'type' => 'kirki-text' it works as I would expect it to with just 'text' defined and no php errors so this is what I'm using now.

I'll shoot you an email with the creds.  This really isn't a big deal for me I just wanted to help if it was something others may run into.

**Comment by aristath** [comment]
@pingram3541 are you still having an issue with this if you use the latest develop branch? (not master)

**Comment by pingram3541** [comment]
@aristath works perfectly thank you.

**Comment by aristath** [comment]
Great! Closing this one. :+1:
