### ISSUE TITLE
Update of text field value from js

### ISSUE THREAD

**Issue by pingram3541** [themeum/kirki#521]
When I update a text field value from js such as:

```
$('#customize-control-my-text-field input').val('some value');
//or
$('#customize-control-my-text-field input').attr('value', 'some value');
//and
$('#customize-control-mt-text-field-input').trigger('change'); //force change event
```

I immediately see the customizer input field showing the new value however when I save and update and refresh the page, the old value remains.  If I click in the input field and manually update it, it saves the new value even if it's simply an edit of the js injected value.

How can I update the input value from js?

On an added note, I also do this successfully from the code field type however I use codemirror's utility function cm.setValue to update it's value.  There must be some other event listener on the normal text field type input that I need to fire...hopefully it's not something like 'keyup'.  Any ideas?

**Comment by aristath** [comment]
You'll have to use the Customizer's JS API for this...
All fields in Kirki use the Customizer's JS templating engine, and each field has a `.js` file responsible for getting and saving the values.
Take a look at this line: https://github.com/aristath/kirki/blob/2.0.3/assets/js/controls/text.js#L8
This is what changes the setting's value.

In the code field, we're getting the value from the codemirror API and then pass that on to the customizer API which is probably why you can get this to work with that control: https://github.com/aristath/kirki/blob/2.0.3/assets/js/controls/code.js#L17

**Comment by pingram3541** [comment]
Hmm, I wonder why my injected "change" event is not firing the update.  Maybe something to do with lacking an original event object or maybe I just need to delay it slightly.  I'll play around with this thanks for the references, really big help.
