### ISSUE TITLE
Is it possible to use image field under repeater field?

### ISSUE THREAD

**Issue by web2feel** [themeum/kirki#524]
Trying to create an image slider setup with repeater fields. But the image fields are not working. Any workaround?

**Comment by aristath** [comment]
Not yet.
Image fields are not currently supported, since this is the 1st implementation of the repeater field we first wanted to build the basic control types and we'll be adding more field types as we go.
Adding image fields there is high on our to-do list.

**Comment by mohdsayed** [comment]
I have added the image filed in repeater by extending the repeater in my theme for Slider settings. https://wordpress.org/themes/supernova/ . Waiting for Aristeides to add that in kirki.

**Comment by aristath** [comment]
@sayedwp hey there!

Think you could submit a PR to this repository with your modifications? I'd love to add these! :+1:

**Comment by mohdsayed** [comment]
Sure , I sent a pull request.

**Comment by aristath** [comment]
@sayedwp everything seems to be working fine here, Thanks for the PR! Great work!

**Comment by mohdsayed** [comment]
Thanks, but I think it needs a little more improvement, I think we should save attachment id instead of image url, so its easier to get any image size we want on the front. WordPress default image field returns just full size image url so I did not do it for the sake consistency. Whats your thoughts?

**Comment by aristath** [comment]
I think that saving the URL is the safest way to handle this (I like consistency...)
I'll add some functions that will help getting the attachment ID & different image sizes from the URL though... I already have those ready, along with a custom image-resizing class that will make creating custom image sizes (& handling retina images) a piece of cake.
I'll be commiting those as soon as I finish writing some inline docs for them. ;)

**Comment by mohdsayed** [comment]
Great, looking forward to it.
