### ISSUE TITLE
Adding text-transform to typography control

### ISSUE THREAD

**Issue by beshoydawood** [themeum/kirki#526]
Is there is anyway to add text-transform (uppercase,lowercase,capitalize) to typography control ?

**Comment by aristath** [comment]
Yes, this is still under construction and currently it's just commented-out in the control's code: https://github.com/aristath/kirki/blob/master/includes/controls/class-kirki-controls-typography-control.php#L74-L103
We'll be implementing this for a future version, we wanted to first release the control with the functioning parts and we'll be adding stuff as we go. :+1:

**Comment by aristath** [comment]
Closing this one.
We completely rebuilt the typography control, but unfortunately adding upper/lowercase was not included.
You can always add a simple radio-buttonset below your typography control... upper/lowercase are things not often used, so including them didn't make muck sense when refactoring the control.

**Comment by rahulv3a** [comment]
@aristath Could you please re-consider including `text-transform` in the `typography` field, if it doesn't complicate things. This would make the `typography` field complete.

I have a `select` field below each `typography` field for `text-transform` that has 4 options:

``` php
'none'       => 'None',
'capitalize' => 'Capitalize',
'uppercase'  => 'Uppercase',
'lowercase'  => 'Lowercase',
```

I developer would not add `text-transform` to the `default` of `typography` field.

I don't know about any of your projects other than Kirki and even I can figure out that you have a lot on your plate right now. So this could be, of course, at the bottom of your priorities. But just let us know if you are planning to add this to the `typography` field. :)

**Comment by Vishal-Deshpande** [comment]
@rahulnever2far  +1 

I second this request. Text transform would certainly be handy.

**Comment by aristath** [comment]
I see a lot more people are requesting for this now... so I just added it (along with `text-align`)
