### ISSUE TITLE
Code Type Field, HTML Language

### ISSUE THREAD

**Issue by tcgunel** [themeum/kirki#527]
Hi,

I'm building options with Kirki. So far so good but when I try to use code type field with HTML language ( Actually htmlmixed or htmlembedded since there is no html ) the Chrome console throws javascript errors. I can use CSS type without any problem. I wonder if it is just me or a bug.

Thank you for this great project, by the way.

**Comment by aristath** [comment]
This was a tough one....
But I think I got it.
Try pulling the latest commits from the [develop branch](https://github.com/aristath/kirki/tree/develop) (or just download it from https://github.com/aristath/kirki/archive/develop.zip

Set the language to `html`. NOT `htmlmixed` or `htmlembedded`, Kirki should now get the dependencies and use the correct mode automatically.

Let me know if it works for you!

**Comment by tcgunel** [comment]
It worked, Thanks!
