### ISSUE TITLE
Transport postMessage for dimensions, spacing, typography...

### ISSUE THREAD

**Issue by lumberman** [themeum/kirki#528]
Hi,
First of all I want to say that this plugin rocks. Amazing organization and structure!

I can't figure out if controls like dimensions, spacing, typography and probably some others do not support live feedback without page reload ( transport = postMessage )?
##

**Comment by aristath** [comment]
To be honest there's still some work to be done on these control types... 
We just introduced them and postMessage is something I did not work on for those.
We'll get it fixed... I just had a lot of work on my day job so some things got left behind here. :)

**Comment by aristath** [comment]
postmessage for dimension controls works as expected using the js_vars argument.
dimensions and typography not yet, I'll see if I can build those now.

**Comment by lumberman** [comment]
Thanks for quick answers to all my questions!

**Comment by beshoydawood** [comment]
@aristath any news about this ?

**Comment by peazz** [comment]
Too many controls are not updating the live view when being used with theme_options.

**Comment by aristath** [comment]
@peazz could you please be a bit more specific?

**Comment by aristath** [comment]
typography fields now work when `transport` is set to `auto`.

**Comment by peazz** [comment]
Nice work.

Regarding the earlier issue. For some reason alot of fields were not working but I have since rebuilt the entire panel and use the latest documentation. 

Everything is working as expected.
