### ISSUE TITLE
Change the way kirki output CSS 

### ISSUE THREAD

**Issue by lumberman** [themeum/kirki#530]
Hi there,

I'm wandering if there is a way for developers to overload/change the way kirki output CSS. I do want to give the users option to output CSS as inline style in the head and as a separate CSS file.

Can you please point me to the filters that I can use to change the way CSS outputs?

Thank you!

**Comment by aristath** [comment]
I just committed a change on the develop branch that should take care of this.
CSS output now defaults to inline and if you set `inline_css` to `false` in the config then it uses the ajax method.
it will be included in the next version, but for now if you want to use it feel free tyo just pull the branch from https://github.com/aristath/kirki/tree/develop
