### ISSUE TITLE
"Number" field arrows are not visible and page reload or field save is not triggered on change

### ISSUE THREAD

**Issue by vladcosorg** [themeum/kirki#534]
![selection_005](https://cloud.githubusercontent.com/assets/467230/11918186/97ae934a-a72f-11e5-9fce-5aff59214f74.png)

Wordpress 4.4, Kirki 2.0.4

**Comment by aristath** [comment]
Did you download the plugin from wordpress.org, or from github?
If you downloaded it from wordpress.org could you please try the version from github?
If it works with the github version and not the w.org version then perhaps there's something wrong with the SVN repository so I'll have to re-upload it there...

**Comment by vladcosorg** [comment]
I just tried both, no difference.

**Comment by aristath** [comment]
Are you using Kirki as a plugin, or embedded in a theme?
If in a theme,could you please post your config (`Kirki::add_config()`) call here so that I may try to replicate this?

**Comment by vladcosorg** [comment]
It is installed as a plugin,  but i'm using it for a theme that i'm working
on.

Here's the code

\Kirki::add_config('my_theme', [
'capability' => 'edit_theme_options',
'option_type' => 'theme_mod',
]);

\Kirki::add_section('testimonials', [
'title' => 'Testimonials list',
'priority' => 160,
'active_callback' => function () {
return is_post_type_archive('testimonial');
}
]);

\Kirki::add_field('my_theme', [
'type' => 'number',
'settings' => 'testimonials_per_page',
'label' => 'Number of testimonials per page',
'section' => 'testimonials',
'default' => 10
]);

**Comment by aristath** [comment]
I think this was just fixed in the "develop" branch.
Can you please download it from https://github.com/aristath/kirki/tree/develop and let me know if that fixes it for you?

**Comment by vladcosorg** [comment]
Good enough! Just minor styling issue with arrows. 
![selection_007](https://cloud.githubusercontent.com/assets/467230/11978750/94aa7fba-a996-11e5-8618-1403574222fd.png)

Thank you!

**Comment by aristath** [comment]
Yeah, I'm having some difficulty with those styles.... 
If you can help out with those I'd appreciate it, otherwise I'll keep trying to pretify them a bit. :+1:
