### ISSUE TITLE
Very long loading time since 2.0.4

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#535]
Hi

Since 2.0.4 version, I have very long loading time in customizer 30+ seconds (both - load or update settings) Customizer settings panel is loading fine, but the site (theme) have this problem.

Using kirki as plugin and version 2.0.3 works fine.

Do you have anybody same problem?

**Comment by x-bull** [comment]
Hi

Made some tests and loks like Kirki load the css styles many times... In the attachement is demo-theme from kirki. All styles are loaded more than 15x
![style-github](https://cloud.githubusercontent.com/assets/14072537/11933947/5499b622-a7ff-11e5-9332-6ac6b2788eb5.jpg)

**Comment by doitmax** [comment]
Yep, can confirm this problem on backend and frontend as well. With Kirki 2.0.3 loading times are around 2secs with Kirki 2.0.4 they increasing massively to 20secs and up.

**Comment by aristath** [comment]
@x-bull @doitmax Can you guys please try using the develop branch and let me know if that fixes your issue?

**Comment by x-bull** [comment]
The problem is fixed and the loading speed is better than in 2.0.3 :-). Hope you release this update as soon as possible

Good job

**Comment by aristath** [comment]
Excellent!

Yes, I'm just going through the tickets and looking for anything major.
I'll try to release this today. If not today then tomorrow :+1: 

Closing this ticket.

**Comment by doitmax** [comment]
@aristath checked it too and it is working now. No more loading delay when using Kirki :+1:
