### ISSUE TITLE
Append to existing controls vs overwrite?

### ISSUE THREAD

**Issue by beatelite** [themeum/kirki#536]
I have a theme that already has a set of controls that I'd simply like to style and add to. when I activate Kirki, I notice it removes all existing controls. Is there a way to simply append to existing customizer controls or simply use kirki to style everything that's already there?
##

**Comment by aristath** [comment]
@beatelite hey there!

Which theme is that?
I've never encountered this issue before... Can you please let me know which theme it is so that I may try to replicate this issue and fix it?

**Comment by beatelite** [comment]
this theme here: https://www.wpbeaverbuilder.com/knowledge-base/theme-installation/

**Comment by aristath** [comment]
I'm afraid that's a premium theme I don't have access to... Could you please send me a copy so that I may test and replicate the issue?

**Comment by beatelite** [comment]
sure: Sending a dl link to your gmail account.

**Comment by aristath** [comment]
@beatelite Did you ever send that email? Did I reply? Do you still require assistance with this one?

**Comment by beatelite** [comment]
Hey, just getting back to this. Yes, I sent the mail. Did you not get it? I'll try and IM you on here. Would really love to use this if possible.

**Comment by aristath** [comment]
I'm terribly sorry, I completely forgot about this ticket!
Do you still require assistance on this one?

**Comment by aristath** [comment]
I just installed the theme you sent on my mail.

> when I activate Kirki, I notice it removes all existing controls.

I can't replicate this using the develop branch. I haven't tried this with older versions of Kirki, but if it was indeed an issue, that is no longer the case.

> Is there a way to simply append to existing customizer controls

I was able to add a control to the "Presets" section for example by doing this:
```php
Kirki::add_config( 'my_child_theme', array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );
Kirki::add_field( 'my_child_theme', array(
	'type'        => 'textarea',
	'settings'    => 'my_child_theme_dummy_textarea',
	'label'       => esc_attr__( 'Textarea Control', 'kirki-demo' ),
	'description' => esc_attr__( 'Control Description', 'kirki-demo' ),
	'section'     => 'fl-presets',
	'default'     => 'text',
));
```
If you want to find the section-ID used by the theme so you can add your own controls to them you can simply search the theme files for `add_section`.
