### ISSUE TITLE
Are there any special instructions for use with Underscores.me?

### ISSUE THREAD

**Issue by w33zy** [themeum/kirki#541]
I think Kirki has been included properly because I am not getting any Chrome Dev console errors and I can see the included JS and CSS files in the page source. I followed the GH wiki page plus other online tutorials. How when I tried adding test settings they do not show up, I only see the default customizer options. 

Am I missing something? Here are the last lines of my `functions.php` file

```
             /**
             * Load Kirki config file.
             */
            include_once( dirname( __FILE__ ) . '/inc/kirki/kirki.php' );

            add_filter( 'kirki/config', function() {
                return array( 'url_path' => get_stylesheet_directory_uri() . '/inc/kirki/' );
            } );

            //require get_template_directory() . '/inc/kirki-init.php';


            Kirki::add_config( 'my_janet', array(
                'capability'    => 'edit_theme_options',
                'option_type'   => 'option',
                'option_name'   => 'my_theme',
            ) );

            Kirki::add_field( 'my_janet', array(
                'settings' => 'my_setting',
                'label'    => __( 'My custom control', 'translation_domain' ),
                'section'  => 'my_section',
                'type'     => 'text',
                'priority' => 10,
                'default'  => 'some-default-value',
            ) );
```

**Comment by x-bull** [comment]
Hi

You have field but no section:

Kirki::add_section( my_section', array(
        'title'       => __( 'Custom Section', 'translation_domain' ),
        'priority'    => 10,
        'description' => __( 'Customizer custom section', 'translation_domain' ),
    ) );

**Comment by w33zy** [comment]
@x-bull Thanks for the assist. After looking at your code I realized what I was missing.
