### ISSUE TITLE
File location errors

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#542]
I am creating options for the Wordpress Theme Customizer using Kirki and although I can select colors and see the change in the preview, I can not get text changes to show up, and although I can get the text function to work in the sample theme that comes with Kirki;

Adding the field

```
Kirki::add_field( 'kirki_demo', array(
    'type'        => 'text',
    'settings'    => 'text_demo',
    'label'       => esc_attr__( 'Text Control', 'kirki-demo' ),
    'help'        => esc_attr__( 'This is a tooltip', 'kirki-demo' ),
    'default'     => esc_attr__( 'This text is entered in the "text" control.', 'kirki-demo' ),
    'section'     => 'text',
    'priority'    => 10,
) );
```

Calling the field

```
<div class="text demo">
    <h4><?php _e( 'text:', 'kirki-demo' ); ?></h4>
    <?php echo esc_html( get_theme_mod( 'text_demo', esc_attr__( 'This text is entered in the "text" control.', 'kirki-demo' ) ) ); ?>
</div
```

When I use this in my theme the field and control is created but entering any text does not show a change in the live preview nor does the 'Saved' button turn to 'Save and Publish. Does anyone know why?

UPDATE: I was getting a lot of javascript error messages in the browser, after a couple of searches I added the following lines of code, which seemed to resolve the issue. 

```
function kirki_update_url( $config ) {

    $config['url_path']     = get_stylesheet_directory_uri() . '/inc/kirki/';
    return $config;

}
add_filter( 'kirki/config', 'kirki_update_url' );
```

**Comment by aristath** [comment]
@livingwandsworth yeah, that was my fault...
I had not added that in the wiki.
It's not added on https://github.com/aristath/kirki/wiki/Embedding-in-a-theme
