### ISSUE TITLE
Valid Callback error

### ISSUE THREAD

**Issue by tomcollom** [themeum/kirki#544]
Really cannot work out why this error is being thrown ; 

Warning: call_user_func() expects parameter 1 to be a valid callback, function 'b' not found or invalid function name in /home/entodev/public_html/wp-content/themes/sliced_enterprise/kirki/includes/class-kirki-styles-output-css.php on line 165

Any suggestions would be very helpful

**Comment by aristath** [comment]
Could you please post the code you're using for your fields here?

**Comment by aristath** [comment]
@tomcollom I'm closing this ticket due to inactivity.
If you're still having an issue with this then please feel free to reopen this and post an update on your current status.
