### ISSUE TITLE
Problem field Sortable

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#549]
![pep](https://cloud.githubusercontent.com/assets/7602983/12150777/02866196-b4ac-11e5-9217-d0df255c44e2.gif)

Hi guys, still very large for the wonderful product :)

I found a bug in the field sortable.

The values saved not maintained and every time you have to replace it all over again.
I am attaching a screenshot gif for a greater understanding of the error

**Comment by sododesign** [comment]
Hi @aristath you've got to check out the problem :)

**Comment by daviedR** [comment]
+1 for this. I think we found the bug. Line 58:

```
if ( is_array( $values && ! empty( $values ) ) ) {
```

should be

```
if ( is_array( $values ) && ! empty( $values ) ) {
```

@aristath please do something about this.

**Comment by sododesign** [comment]
Thank yout @daviedR . Where is the file?

**Comment by sododesign** [comment]
Ok, i find :+1: 

in includes/controls/class-kirki-controls-sortable-control.php

line 58

Now work perfect. Please @aristath, check this problem :)

**Comment by daviedR** [comment]
@sododesign your welcome :)

**Comment by aristath** [comment]
great catch!

Thanks guys, fixed it in the develop branch, this will be included in the next release.
