### ISSUE TITLE
Multiple property outputs

### ISSUE THREAD

**Issue by dmgawel** [themeum/kirki#55]
Sometimes it's required for one control (i.e. color) to produce output for many properties (i.e. color and border-color).

To not break the existing API my proposition is to declare this as following:

``` php
$controls[] = array(
    'type'     => 'color',
    'setting'  => 'color_accents',
    'label'    => __( 'Accents Color', 'goodyear' ),
    'section'  => 'colors',
    'default'  => '#3498db',
    'priority' => 2,
    'output' => array(
        array(
            'element'  => '.btn',
            'property' => 'color'
        ),
        array(
            'element'  => '.btn-primary',
            'property' => 'border-color'
        )
    )
);
```

What do you think?

**Comment by aristath** [comment]
I like it! :+1: 
I'll start working on it tomorrow if not later today.

Right now I'm pissed at wordpress.org & the fact that they're using SVN and make my life living hell.

**Comment by dmgawel** [comment]
Check out this one, I use it all the time: https://github.com/pdclark/deploy-plugin-to-wordpress-dot-org

**Comment by aristath** [comment]
I attempted to do this here: https://github.com/aristath/kirki/pull/56
Can you test and let me know if that works for you?
Any suggestions are welcomed :smile: 

I think I covered all possibilities there, but I there's always a chance i missed something.

**Comment by dmgawel** [comment]
It works! Great.
