### ISSUE TITLE
Including in a theme, file size issue

### ISSUE THREAD

**Issue by leanda** [themeum/kirki#550]
This might be a stupid question, but is there any way to reduce the size of kirki by removing unnecessary files? Other than removing the demo theme I'm not sure what else I can remove safely.

A zipped up version of my theme including the kirki library is 2.2mb just slightly too large to be uploaded by zip using the Wordpress dashboard without changing the default upload limit, which most users won't do. Without the library my theme weighs in at 610kb.

Thanks

**Comment by aristath** [comment]
Well... it actually depends on the fields you're using!
If you're not using any `code` fields, you can remove the `assets/js/vendor/codemirror/` folder.
If you want  to keep it completely minimal, here's what you can do:
1. From the `/assets/js/controls` delete the files that correspond to fields you're not using
2. If you're not using a "code" field delete the `assets/js/vendor/codemirror/` folder
3. Feel free to delete any control types you're not using from `includes/controls`
4. If you deleted JS files on step 1, run grunt to re-create the compiled JS. After this step you can completely remove the `/assets/js/controls/` folder.

:+1:

**Comment by leanda** [comment]
Thanks! I'll give this a whirl at the weekend and report back.

**Comment by AshiqKiron** [comment]
@aristath  Hi there, I deleted the codemirror also commented out the enqueue function. In case I update kirki I guess I have to do that again. Is there any elegant solution( like a dequeue function) for this ? so that regardless of update, Code mirror will always be dequeued.

**Comment by aristath** [comment]
@AshiqKiron codemirror will only be enqueued when you add a code control so you don't even have to dequue anything. :)

**Comment by AshiqKiron** [comment]
Hi there, you already answered this on another thread I opened on GitHub. Thank you. By the way, any plans on adding new controls/settings for kirki ?

**Comment by aristath** [comment]
> any plans on adding new controls/settings for kirki ?

Definitely...
