### ISSUE TITLE
Sharp Tag

### ISSUE THREAD

**Issue by meetawahab** [themeum/kirki#551]
Hi Support

I'm checking the kirki code & find the tag

![sharp](https://cloud.githubusercontent.com/assets/13060362/12215109/12e103ae-b6d0-11e5-96f0-68e6ebec89dd.png)

I'm bit confusing on this tag <# #>
Can you tell me What's the tag mean & what it does ?

**Comment by aristath** [comment]
The WordPress customizer uses the [underscore.js](http://underscorejs.org/) templating engine.
You can read a great introduction post on http://justintadlock.com/archives/2015/06/05/javascript-templating-in-the-wordpress-customizer :+1:
