### ISSUE TITLE
Kirki Customizer take space from left

### ISSUE THREAD

**Issue by Rohit120** [themeum/kirki#552]
I have created new customizer using kirki and add new panel, section on it but their are issue that it's take some space on right like this screenshot:-

I ahve upload my function.php with this please implement this in your theme use theme name is "webg"

http://awesomescreenshot.com/0175i6re20
[functions.zip](https://github.com/aristath/kirki/files/85595/functions.zip)
##

**Comment by aristath** [comment]
@Rohit120 I've been unable to replicate this issue...
Are you still having this problem? If you do, could you please provide some more info? from your functions.php file I see you're loading a bunch of other things, have you tried disabling those 1-by-1 to check if this is a conflict of some sort?

**Comment by aristath** [comment]
This is a WordPress core issue, this still happens even with Kirki disabled.
Closing this ticket. 👍
