### ISSUE TITLE
No styles / js when embed in a theme.

### ISSUE THREAD

**Issue by getbowtied** [themeum/kirki#554]
Hi,

the styles and javascript are not loaded when the plugin is embed in a theme.

**Comment by getbowtied** [comment]
...but it works when is installed like a regular plugin.

**Comment by ragzor** [comment]
Hey!

Have you updated kirki URL?

``` php
function kirki_update_url( $config ) {
    $config['url_path'] = get_stylesheet_directory_uri() . '/inc/customizer/';
    return $config;
}
add_filter( 'kirki/config', 'kirki_update_url' );
```

`/inc/customizer/` is the directory where kirki lives.

**Comment by getbowtied** [comment]
It works, thank you!

**Comment by Thomas-A-Reinert** [comment]
Solved my RGBA problem when embedded into theme, too. Thanks ragzor!
