### ISSUE TITLE
html CodeMirror 2.0.5

### ISSUE THREAD

**Issue by tcgunel** [themeum/kirki#556]
Hi,

I updated my Kirki to 2.0.5 and tried to use html code field type. You pointed out "FIX: HTML mode for CodeMirror now functional" at 2.0.4 version but however It is not working. I can use other types tho like css.

Regards.

**Comment by aristath** [comment]
@tcgunel could you please post the code for your field here so that I may try to replicate this?

**Comment by tcgunel** [comment]
```
Kirki::add_field( 'sweipe_footer', array(
        'type'        => 'code',
        'settings'    => 'sweipe_custom_html',
        'label'       => esc_html__( 'Custom HTML', 'sweipe' ),
        'section'     => 'sweipe_footer_section',
        'default'     => '',
        'priority'    => 25,
        'choices'     => array(
                'language' => 'html',
                'theme'    => 'monokai',
                'height'   => 450,
        ),
) );
```

**Comment by aristath** [comment]
@tcgunel I just tested this by changing this line https://github.com/aristath/kirki/blob/2.0.5/demo-theme/functions.php#L159 from `css` to `html` and it seems to be working fine....
Do you have your theme on guthub pephaps so that I may take a closer look? It could be something else interfering...

**Comment by aristath** [comment]
Closing this one due to inactivity.
If you're still having an issue then please feel free to reopen this and post an update on your current status.
