### ISSUE TITLE
Trouble with color output

### ISSUE THREAD

**Issue by alfgago** [themeum/kirki#558]
Hi, I must say I absolutely love this library, but I'm having a little trouble though.
I'm trying to set a color property with auto generate CSS, but it's not working for me. Can you help me here?

I have the following:

```
Kirki::add_field( 'elias', array(
    'type'        => 'color',
    'settings'    => 'header_text_color',
    'label'       => __( 'Text Color', 'elias' ),
    'section'     => 'header_background',
    'default'     => '#ffffff',
    'priority'    => 1,
    'output'   => array(
        'element'  => '#masthead site-title, #masthead site-title a, #masthead site-description, #masthead .main-navigation a',
        'property' => 'color',
    ),
) );
```

This almost works, it shows in the customizer, but when I change the value, the output is not generated and it does nothing. What am I doing wrong? I got this from Ornea demo theme.

I also tried changing the output to just '#masthead site-title, #masthead site-title a, #masthead site-description, #masthead .main-navigation a' instead of the array, but it doesn't work either.

**Comment by aristath** [comment]
Try it like this:

``` php
Kirki::add_field( 'elias', array(
    'type'        => 'color',
    'settings'    => 'header_text_color',
    'label'       => __( 'Text Color', 'elias' ),
    'section'     => 'header_background',
    'default'     => '#ffffff',
    'priority'    => 1,
    'output'   => array(
        array(
            'element'  => '#masthead site-title, #masthead site-title a, #masthead site-description, #masthead .main-navigation a',
            'property' => 'color',,
        ),
    ),
) );
```

**Comment by alfgago** [comment]
Thank you, that worked perfectly!
