### ISSUE TITLE
Google Fonts Integration

### ISSUE THREAD

**Issue by getbowtied** [themeum/kirki#559]
Hi,

I tried to integrate Google font with subsets as described here:
https://github.com/aristath/kirki/wiki/Google-Fonts-Integration

but the output does nothing. What sholud I do to use Google fonts with subsets?

**Comment by aristath** [comment]
Can you please post the code you're using here?

**Comment by aristath** [comment]
There was an error on the format of the `output` argument on that wiki page.
I fixed that now so please check it again. :+1:

**Comment by getbowtied** [comment]
Thank you, it's working now.
