### ISSUE TITLE
Class 'Kirki_Controls_Textarea_Control' not found

### ISSUE THREAD

**Issue by xizon** [themeum/kirki#560]
Fatal error: Class 'Kirki_Controls_Textarea_Control' not found in ~/kirki/includes/class-kirki-control.php on line 98.
Fatal error: Class 'Kirki_Controls_Text_Control' not found in ~/kirki/includes/class-kirki-control.php on line 98.

An error occurred on different servers.

Kirki Version: 2.0.5
WP Version: 4.4.1
PHP Version: 5.4~5.6

I do not know how to solve it. Thanks! 
Server problem?

**Comment by aristath** [comment]
Can you please try re-downloading the plugin?
There was an error in the repository on wordpress.org

**Comment by xizon** [comment]
OK,thanks. I Try It.

**Comment by xizon** [comment]
At last i successfully solved the problem.There are times you'll find folder's spell check may lead to erroneous.
You can also correct spelling errors. I changed the folder name "Controls" to "controls". :) 

Directory path: kirki -> includes -> Controls.

**Comment by aristath** [comment]
This has already been fixed in the WordPress repository on https://github.com/aristath/kirki/issues/557#issuecomment-172096720
