### ISSUE TITLE
Several issues with Google fonts

### ISSUE THREAD

**Issue by Digital-Odyssey** [themeum/kirki#565]
Hi,

I am running into a few issues with the Kirki framework.

Issue 1:
Google fonts are not fully loading on my localhost (slider controls do not fully work)

Issue 2:
Google font controls are functioning correctly on my live server but it is not applying any CSS to the theme

I am following along with the docs and i have integrated the code demonstrated on this page:
https://github.com/aristath/kirki/wiki/Google-Fonts-Integration

Is there something wrong with the code listed in your documentation?

**Comment by aristath** [comment]
Hey there!
I think I had an error on that wiki page...
Take a look at it now.
The format of the `output` argument is now correct.

**Comment by Digital-Odyssey** [comment]
Thanks man, its working now.
