### ISSUE TITLE
Transport postMessage is not working in v 2.0.6

### ISSUE THREAD

**Issue by luanvuvt** [themeum/kirki#567]
Hi,
Thanks for your work! It seems that we can use transport message for settings which have :before, :after, :hover in selectors in the version 2.0.6. But transport postMessage is not working now. I see that you commented this line

```
Kirki_Customizer_Scripts_PostMessage::generate_script( $this->args );
```

in file class-kirki-field.php.
Could you please recheck this problem?
Thank you!

**Comment by aristath** [comment]
Thanks for reporting this...
I had 2 lines commented-out 'cause I was debugging some things and I forgot to uncomment them before releasing 2.0.6.

Fixed, I'll release a new bugfix version in a couple of hours that will include this.

**Comment by aristath** [comment]
2.0.7 released, this should be fixed now.

**Comment by luanvuvt** [comment]
Thank you :)
