### ISSUE TITLE
Color control for google fonts?

### ISSUE THREAD

**Issue by Digital-Odyssey** [themeum/kirki#568]
Hey,

How do i apply a color control for google fonts?

**Comment by Digital-Odyssey** [comment]
Im trying the following but doesnt seem to work:

<pre>
Kirki::add_field( 'viennalite', array(
        'type'        => 'color',
        'settings'    => 'paragraph_font_color',
        'label'       => __( 'Color', 'kirki' ),
        //'description' => __( 'This is the control description', 'kirki' ),
        //'help'        => __( 'This is some extra help text.', 'kirki' ),
        'section'     => 'body_font',
        'default'     => '#000000',
        'priority'    => 10,
        'output'   => array(
            'element'  => 'p',
            'property' => 'color',
        ),
    ) );
</pre>

I took that code from the Ornea theme.

**Comment by Digital-Odyssey** [comment]
Nevermind, got it working. The output was wrong - you should update the code in the Ornea theme so its using the latest version of the framework with the most up to date code.

It should be like this:

<pre>
Kirki::add_field( 'viennalite', array(
        'type'        => 'color',
        'settings'    => 'paragraph_font_color',
        'label'       => __( 'Color', 'kirki' ),
        //'description' => __( 'This is the control description', 'kirki' ),
        //'help'        => __( 'This is some extra help text.', 'kirki' ),
        'section'     => 'body_font',
        'default'     => '#000000',
        'priority'    => 10,
        'output'   => array(
            array(
                'element'  => 'p',
                'property' => 'color',
            ),
        ),
    ) );
</pre>

Cheers!

**Comment by aristath** [comment]
Change it so that it looks like this:

``` php
Kirki::add_field( 'viennalite', array(
    'type'        => 'color',
    'settings'    => 'paragraph_font_color',
    'label'       => esc_html__( 'Color', 'viennalite' ),
    'section'     => 'body_font',
    'default'     => '#000000',
    'priority'    => 10,
    'output'      => array(
        array(
            'element'  => 'p',
            'property' => 'color',
        ),
    ),
) );
```
