### ISSUE TITLE
Separator between fields

### ISSUE THREAD

**Issue by getbowtied** [themeum/kirki#572]
Hi,

we want to add separators between fields. This is our code:

``` php
add_action( 'customize_register', 'kirki_custom_control_separator' );
function kirki_custom_control_separator( $wp_customize ) {
    class Kirki_Control_Separator extends WP_Customize_Control {
        public $type = 'separator';
        public function render_content() { ?>
            <hr />
            <?php
        }
    }
    add_filter( 'kirki/control_types', function( $controls ) {
        $controls['separator'] = 'Kirki_Control_Separator';
        return $controls;
    } );
}

Kirki::add_field( 'our_theme', array(
        'type'        => 'separator',
        'settings'    => 'separator_1',
        'section'     => 'header',
    ) );
```

The question is: there a better way to do that? The problem here is that we have to set different id's for every separator ('settings'    => 'separator_1'). We just need a <hr /> between fields...

**Comment by getbowtied** [comment]
... the grey like is in fact a "hr".

**Comment by aristath** [comment]
You could try using a "custom" field, which basically allows to to enter whatever HTML you want:

``` php
Kirki::add_field( '', array(
    'type'        => 'custom',
    'settings'    => 'custom' . rand(),
    'label'       => '',
    'section'     => 'my_section',
    'default'     => '<hr>',
    'priority'    => 10,
) );
```

**Comment by getbowtied** [comment]
That's great! Thank you!

**Comment by getbowtied** [comment]
Hi,

there is a issue with settings' => 'custom' . rand(). When we use rand(), the field disappear. There's a "display:none" injected inline by javascript: 

http://screencast.com/t/sfFc3DsG

This is not happening if we use a number instead of rand().
