### ISSUE TITLE
Warning error on all pages in v2.0.6

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#573]
Since updated to the new version, all pages got a warning like this.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Kirki_Customizer_Scripts_Loading' does not have a method 'customizer_scripts' in ......\wp-includes\plugin.php on line 525

Can you fix this soon, some of users enable WP_DEBUG mode, so the warning is shown on all their pages.

Thanks!

**Comment by vladcosorg** [comment]
can confirm

**Comment by aristath** [comment]
2.0.7 released, this should be fixed now.
