### ISSUE TITLE
Google fonts on localhost

### ISSUE THREAD

**Issue by Digital-Odyssey** [themeum/kirki#575]
Hey,

The google fonts are still not working on my localhost environment - here is a video demonstrating my situation: http://screencast.com/t/2NHLfr1BBH

It works perfectly on my live server but not on my localhost. Is there something i need to configure on my localhost to get it working?

Thanks.
##

**Comment by aristath** [comment]
Is this by any chance on a windows server?
It looks to me like the kirki assets are not getting properly loaded... the styling of those controls doesn't look right.
Take a look at this and make sure you add the function mentioned there (renaming it of course using your theme's prefix): https://github.com/aristath/kirki/wiki/Embedding-in-a-theme

**Comment by Digital-Odyssey** [comment]
Yup its a windows machine. 

I have that code in my functions.php file but it doesn't seem to work on my localhost. Aside from the css styles not getting applied the functionality of the sliders dont work either.

Strangely enough everything works perfectly on my live server. I am using XAMPP for my localhost environment if that helps at all.

Any other ideas?

**Comment by aristath** [comment]
> Aside from the css styles not getting applied the functionality of the sliders dont work either.

That's because since the URL of Kirki can't be properly determined on your setup, not CSS **or JS** files can be properly enqueued.
Since the JS can't be enqueued the scripts handling the controls can't run.
I'm betting if you take a look at your console you'll see 404 errors where the Kirki assets were supposed to be.
Can you tell me the URLs it's trying to load? Perhaps it's a matter of `\` vs `/` (Windows systems are messy and XAMPP has the worst implementation ever when it comes to properly handling paths)

**Comment by Digital-Odyssey** [comment]
Yea looks like its a path issue, here is what i am getting in the source window:

http://localhost/viennalite/wp-content/themes/viennalite-themeC:xampphtdocsviennalitewp-contentthemesviennalite-themeincludeskirki/assets/js/vendor/selectize.js?ver=4.4.1

All of the kirki assets in the source code have C:xampphtdocsviennalitewp-contentthemesviennalite-themeincludeskirki inserted into them.

Any idea how to fix this for localhost environment running on XAMPP?

**Comment by aristath** [comment]
Can you please post the code you're using to define the URL of kirki assets in your functions.php?

**Comment by Digital-Odyssey** [comment]
Yea sure.

Im using the following to activate Kirki:

<pre>
if ( ! class_exists( 'Kirki' ) ) {
    include_once(get_template_directory() . "/includes/kirki/kirki.php");
}
</pre>

And the following for the update URL

<pre>
add_filter( 'kirki/config', 'pm_ln_kirki_update_url' );
if ( ! function_exists( 'pm_ln_kirki_update_url' ) ) {
    function pm_ln_kirki_update_url( $config ) {
        $config['url_path'] = get_stylesheet_directory_uri() . '/includes/kirki/';
        return $config;
    }
}
</pre>

**Comment by aristath** [comment]
sorry for this back-and forth but I don't have a windows machine to test XAMPP so I'll have to rely on you for some testing if you don't mind...

If you add this at the end of your functions.php, what are you getting on your screen?

``` php
var_dump( get_stylesheet_directory_uri() );
```

**Comment by Digital-Odyssey** [comment]
no worries, i am getting the following:

<pre>
string(62) "http://localhost/viennalite/wp-content/themes/viennalite-theme" 
</pre>

**Comment by Digital-Odyssey** [comment]
Hey anyone there?

**Comment by edulelis** [comment]
Hey guys,
Just to point out it's useful to use the native Wordpress function `wp_normalize_path` to correct these directory separator issues. 
You could try:
`$config['url_path'] = wp_normalize_path(get_stylesheet_directory_uri() . '/includes/kirki/');`

**Comment by aristath** [comment]
@PulsarMedia I'm really sorry, I completely missed this ticket!!
Did you manage to resolve it? Do you still require assistance on this one?
If you do, can you please try using the develop branch and let me know if there's any change?

**Comment by aristath** [comment]
@PulsarMedia I believe this was fixed in the latest releases 'cause a lot of things got completely rebuilt.
I can no longer replicate this...
