### ISSUE TITLE
Hot to get shortcode in from text fields in php files. ?

### ISSUE THREAD

**Issue by truetesterphp** [themeum/kirki#578]
I have create a text field using kirki. where i want to add shortcode is like: this 
 "[contact-form-7 id='165' title='Custom']" please solve hot to get this value in php files: i have tried using this: - 
<?php $shortcode = "get_theme_mod('shortcode');"?>
<?php echo do_shortcode($shortcode); ?>

It does not get showing any result..

**Comment by ragzor** [comment]
Remove the `" "` from

`"get_theme_mod('shortcode');"`

**Comment by aristath** [comment]
Hey there @truetesterphp 
Did @ragzor's advice resolve this one for you?

**Comment by x-bull** [comment]
Looking for something similar and it works perfect!

**Comment by truetesterphp** [comment]
i have remove "" from this but it's not to be work.

**Comment by allysonsouza** [comment]
I had a problem to display shortcodes from text field, so I used html_entity_decode:

```
$contact_form = get_theme_mod( 'contact-form' );
echo do_shortcode( html_entity_decode( $contact_form ) );
```

And also set the sanitize_callback like that to have this working on customizer view:
`'sanitize_callback' => 'wp_kses_post',`
