### ISSUE TITLE
Can I place the <style id='kirki-styles-inline-css' type='text/css'> in a CSS file?

### ISSUE THREAD

**Issue by RonalddeRooij** [themeum/kirki#579]
1. Is it possible to put the automatic output in a CSS file? Instead of the standard way between the  style id='kirki-styles-inline-css' type='text/css' tags in the header?
2. Or do I need to create a CSS file where I declear all my options with get_theme_mod?
3. Is there an easy way to turn off the output to the header so I can copy the ouput to a CSS file myself if it's not possible to put the output in a CSS file?

Thanks in advance!

**Comment by RonalddeRooij** [comment]
I have solved my issue by changing the file: class-kirki-styles-frontend.php

**Comment by aristath** [comment]
@RonalddeRooij could you please let me know you did exactly?
I'll be implementing something similar soon, so it would be nice to see how you did that

**Comment by RonalddeRooij** [comment]
The "issue" that we had was that the output was visible in the souce code (ctrl + u). I made some changes, which you had commented in the following file: class-kirki-styles-frontend.php. The ouput isn't visible anymore when i'm looking in the source. It's generatting the following CSS file when inspecting the elements that have been affected by kirki: admin-ajax.php?action=kirki_dynamic_css

I made those changes in the following website: http://acheron.staging.caramelo-media.nl/
URL to the dynamic CSS: http://acheron.staging.caramelo-media.nl/wp-admin/admin-ajax.php?action=kirki_dynamic_css

I'm guessing that you are trying to do something else. If needed let me know then will I send you my changed class-kirki-styles-frontend.php

**Comment by aristath** [comment]
oh! ok, gotcha. 
The ajax method is still a work in progress, that's why it's not (yet) the default method. :)
You shouldn't have any issues with that though.

**Comment by RonalddeRooij** [comment]
Nope, I didn't have any issues yet! Looking forward for the default method, this is really an awesome feature. Good luck with future development!!

**Comment by enkota** [comment]
Hey @RonalddeRooij , would you be able to share what you done with the class-kirki-styles-frontend.php file? Would like to use the ajax method before releasing my theme! Many thanks.

**Comment by aristath** [comment]
@scopeak since this is a work in progress, I've simply commented-out these methods.
You can uncomment these lines if you want to try it:
https://github.com/aristath/kirki/blob/2.0.8/includes/class-kirki-styles-frontend.php#L36-L47
https://github.com/aristath/kirki/blob/2.0.8/includes/class-kirki-styles-frontend.php#L59-L66

**Comment by enkota** [comment]
@aristath I did uncomment those but was still receiving the inline option after a cache refresh. Is there anything else I need to do to default ajax?

Edit: I see the ajax has been disabled for now due to the long load times. I may wait out until the method is complete :+1:

**Comment by aristath** [comment]
Yes, change [line 41](https://github.com/aristath/kirki/blob/2.0.8/includes/class-kirki-styles-frontend.php#L41) from this:

``` php
if ( ! $wp_customize && ( isset( $config['inline_css'] ) && false == $config['inline_css'] ) ) {
```

to this:

``` php
if ( ! $wp_customize || ( isset( $config['inline_css'] ) && false == $config['inline_css'] ) ) {
```

**Comment by aristath** [comment]
Please keep in mind that a few things may change there by the time we release this feature...
This is a very early version of what we want to implement.

**Comment by enkota** [comment]
Okay, i'll do some testing and keep that in mind. Cheers!

**Comment by RonalddeRooij** [comment]
@aristath Thanks for helping Scopeak !!
