### ISSUE TITLE
Multiple js errors in customizer page

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#58]
Hi,
when I'm in customizer page in firebug console I see a lot of errors:

<pre>
ReferenceError: jQuery is not defined
jQuery(document).ready(function($) {"use strict";  
</pre>

When take a look on the source You will see that the kirki JS is before doctype.

**Comment by fovoc** [comment]
Hey there,
can you pull the latest commit and test if this remains? I think this finally resolved in dc0bae601154387b0be16b53d156a1f53079f29b

Please advice,
Dimitris

**Comment by padalec** [comment]
Hi,
great! Thanks!
Regards
Michal

**Comment by fovoc** [comment]
Good to hear about it! :)

Have a good one,
Dimitris
