### ISSUE TITLE
Problem with apostrophe s in panel description

### ISSUE THREAD

**Issue by mohdsayed** [themeum/kirki#580]
When I use an intverted comma "" or apostrophe 's' in panel description of kirki , it converts that into `&quot;`
I was trying to use it in add_panel

```
'description' => __(  'Works on page where the page template is "home".' ,  'lesse-lite'  ),
```

![screen shot 2016-01-23 at 10 25 34 am](https://cloud.githubusercontent.com/assets/6297436/12528453/0627a04a-c1bc-11e5-8f91-4579e4d53184.png)

Its weird because I see you have not altered the description except for esc_textarea 

```
    public function add_panel( $args ) {
        // Add the panel using the customizer API
        $this->wp_customize->add_panel( sanitize_key( $args['id'] ), array(
            'title'           => esc_textarea( $args['title'] ),
            'priority'        => esc_attr( $args['priority'] ),
            'description'     => esc_textarea( $args['description'] ),
            'active_callback' => $args['active_callback'],
        ) );

```

I don't understand why it is happening. However when I remove esc_textarea() from description or do this

`html_entity_decode( esc_textarea( $args['description'] ), ENT_QUOTES, get_bloginfo( 'charset' ) )`

it outputs the apostrophe properly.

I tried to test it with esc_textarea() to WordPress default $wp_customize->add_panel description, but this does not create this problem.

**Comment by daveromsey** [comment]
I'm having the same issue on both the master and develop branches. Seems like `esc_textarea` is not the best way of escaping the description or the title fields in this context. 

How about replacing `esc_textarea` with `esc_html`, or if some HTML is allowed, `wp_kses_post` in kirki/includes/class-kirki-section.php?

**Comment by aristath** [comment]
test the develop branch now (will be merge in master in a few hours)

**Comment by daveromsey** [comment]
> test the develop branch now 

Tested in develop branch and the apostrophes are displayed correctly. Thank you!

`'description'     => $args['description'], // already escaped in WP Core`
Good lookin' out!
