### ISSUE TITLE
The options declared inside customize_register hook are not working properly

### ISSUE THREAD

**Issue by vladcosorg** [themeum/kirki#581]
The wiki shows examples where fields are not declared inside the `customize_register` hook, however the examples in Customizer handbook do have field declaration inside this hook.

Now there's a problem, that if i declare the fields outside this hook, everything works well however the performance impact is noticeable, because some `select` choices are built from the database and on every page load lots of extra queries are made which are not necessary.

If if place field declarations inside the hook, the option defaults are not available on the frontend before first save and the stylesheet from the output is not generated because the hook does not run unless the customizer is enabled.

Any ideas how to handle this?
##

**Comment by aristath** [comment]
Internally all fields, sections etc are added on `customize_register` (see https://github.com/aristath/kirki/blob/2.0.7/includes/class-kirki-init.php#L51-L54)

> Now there's a problem, that if i declare the fields outside this hook, everything works well however the performance impact is noticeable, because some select choices are built from the database and on every page load lots of extra queries are made which are not necessary.

Have you tried adding them on `after_setup_theme` for example?
Perhaps you could use a proxy function to get these select elements that would cache the results (maybe using transients?)

**Comment by vladcosorg** [comment]
Thanks for a suggestion! Indeed using transients is one way to do it. What about adding support for a callback/callable support for choices field?

Smth like

```
'choices' => function(){
   return  $wpdb->get_results('SELECT ...');
}
```

I could give a try implementing this.

**Comment by aristath** [comment]
@chetzof hey again!

Just going through old issues here, trying to figure out if I have any outstanding issues.
Is this still a problem or have you managed to resolve it?

**Comment by vladcosorg** [comment]
Hi, 

I've created a field class wrapper that adds support for closures. So i guess this issue is fixed for me :)
