### ISSUE TITLE
Separator between fields

### ISSUE THREAD

**Issue by getbowtied** [themeum/kirki#582]
Hi,

https://github.com/aristath/kirki/issues/572

there is a issue with settings' => 'custom' . rand(). When we use rand(), the field disappear. There's a "display:none" injected inline by javascript:

http://screencast.com/t/sfFc3DsG

This is not happening if we use a number instead of rand().

**Comment by aristath** [comment]
Then don't use `rand()`!
I just did it as an example, mostly to show that you'll have to use a unique ID, nothing more than that.
It can even be `kjlhgahgsa`, as long as it's unique.
