### ISSUE TITLE
style and html are not working in js_vars

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#583]
First of all thank you for putting together such an awesome plugin. It makes managing Customizer so much easier,

I'm facing a bit of a problem. I can't seem to make `style` and `html` functions work in `js_vars`. `css` function works perfectly fine.

Here's my code for `style`.

``` PHP
Kirki::add_field( THEME_PREFIX . 'config', array(
  'settings'  => THEME_PREFIX . 'accent_color',
  'type'      => 'color',
  'label'     => esc_html__( 'Accent Color', 'avocet' ),
  'section'   => THEME_PREFIX . 'section_colors',
  'default'   => '#e53b55',
  'transport' => 'postMessage',
  'js_vars'   => array(
    array(
      'element'  => '.block-title:after',
      'function' => 'style',
      'property' => 'background-color',
    ),
  ),
  'output'    => array(
    array(
      'element'  => '.block-title:after',
      'property' => 'background-color',
    ),
  ),
) );
```

I'm using the following code for `html`

``` PHP
Kirki::add_field( THEME_PREFIX . 'config', array(
  'settings' => THEME_PREFIX . 'copyright_statement',
  'type'     => 'textarea',
  'label'    => esc_html__( 'Copyright Statement', 'avocet' ),
  'section'  => THEME_PREFIX . 'section_copyright_statement',
  'default'  => esc_html__( 'Copyright 2015 All Rights Reserved.', 'avocet' ),
  'js_vars'  => array(
    array(
      'element'  => '.copyright',
      'function' => 'html',
    ),
  ),
) );
```

Please help!

Thank you!

**Comment by rahulv3a** [comment]
I don't how but `style` just started working. I didn't make any change in my code. It could be due to some browser related problem.

I figured out what was wrong with my `html`. I forgot to add `'transport' => 'postMessage'`. Now I feel stupid for posting this issue.

**Comment by aristath** [comment]
> I figured out what was wrong with my html. I forgot to add 'transport' => 'postMessage'. Now I feel stupid for posting this issue.

You can't even imagine how many times I've done that.... I'm glad you managed to figure this one out!
