### ISSUE TITLE
Conditional CSS is not output until customizer save

### ISSUE THREAD

**Issue by mikedidthis** [themeum/kirki#584]
Kirki works great with the theme I am currently working on, but there is one issue. Font properties are not output via the inline css when the theme is first activated. It is output via the inline css when the customizer is saved. 

The theme supports two font foundries. I duplicated the font options and assign a set to each font foundry. Below is the code to select between the two foundries:

``` PHP
  Kirki::add_field( 'wp_theme', array(
    'label'       => __( 'Font Foundry', 'wp_theme' ),
    'type'        => 'select',
    'settings'    => 'type_foundry',
    'section'     => 'type_source',
    'default'     => 'google',
    'choices'     => array(
      'google'  => 'Google',
      'typekit' => 'Typekit',
    ),
  ) );
```

The following logic is to make sure the inline css contains properties for the selected foundry above. It seems `required` only toggles the controllers visibility not output:

``` PHP
  Kirki::add_field( 'wp_theme', array(
    'description' => __( 'Font Family', 'wp_theme' ),
    'type'        => 'select',
    'settings'    => 'body_google_font_family',
    'section'     => 'type_site',
    'default'     => 'Domine',
    'choices'     => Kirki_Fonts::get_font_choices(),
    'required'    => array(
      array(
        'setting'  => 'type_foundry',
        'operator' => '==',
        'value'    => 'google',
      )
    ),
    'output'      => ( get_theme_mod( 'type_foundry', 'typekit' ) == 'google' ) ? array(
      array(
        'element'  => 'body',
        'property' => 'font-family',
      ),
    ) : array(),
  ) );
  Kirki::add_field( 'wp_theme', array(
    'description' => __( 'Font Family', 'wp_theme' ),
    'type'        => 'text',
    'settings'    => 'body_typekit_font_family',
    'section'     => 'type_site',
    'default'     => 'Droid Serif',
    'required'    => array(
      array(
        'setting'  => 'type_foundry',
        'operator' => '==',
        'value'    => 'typekit',
      )
    ),
    'output'      => ( get_theme_mod( 'type_foundry', 'typekit' ) == 'typekit' ) ? array(
      array(
        'element'  => 'body',
        'property' => 'font-family',
        'callback' => 'get_typekit_font_family',
      ),
    ) : array(),
  ) );
```

It maybe the logic, but I can't see anything obvious. Everything else is output via the inline css when the theme is activated, all that is missing is the output from the code above.

Any help is appreciated.

**Comment by aristath** [comment]
In your fields above the conditional looks like this:

``` php
( get_theme_mod( 'type_foundry', 'typekit' ) == 'typekit' )
```

so by default, the `body_typekit_font_family` setting should be applied.
in your `get_typekit_font_family` function, do you have a fallback in case the setting is empty?
If not, can you please try adding one so that when the setting is empty, it will fallback to using `'Droid Serif'`?

Let me know if that works!

**Comment by mikedidthis** [comment]
``` PHP
  function get_typekit_font_family( $value ) {
    return strtolower( str_replace( ' ', '-', $value ) );
  }
```

The function changes `Droid Serif` to `droid-serif` as that is the naming convention for `typekit` font families.

To clarify if `$value` is empty, I should send back `default`? Is that possible?

Thanks

**Comment by aristath** [comment]
Try this:

``` php
function get_typekit_font_family( $value = false ) {
    // If the value is empty or undefined (false), return a default value
    if ( ! $value || empty( $value ) ) {
        return 'droid-serif';
    }
    // convert to lowercase and spaces to dashes
    $value = strtolower( str_replace( ' ', '-', $value ) );
    // return the escaped value
    return esc_attr( trim( $value ) );
}
```

**Comment by mikedidthis** [comment]
Thanks. In theory this works, however the default may not always be `droid-serif`. I would need to write a function per font family name. Unless I can pass in the default value to the callback.

You mention, by default, the `body_typekit_font_family` setting should be applied. Is there any reason that Kirki is not outputting this into the inline css when the theme is first activated.

Everything works as expected once the customizer is saved. Just to clarify, this issue still happens with `google` as well:

``` PHP
  Kirki::add_field( 'wp_theme', array(
    'description' => __( 'Font Family', 'wp_theme' ),
    'type'        => 'select',
    'settings'    => 'body_google_font_family',
    'section'     => 'type_site',
    'default'     => 'Domine',
    'choices'     => Kirki_Fonts::get_font_choices(),
    'required'    => array(
      array(
        'setting'  => 'type_foundry',
        'operator' => '==',
        'value'    => 'google',
      )
    ),
    'output'      => ( get_theme_mod( 'type_foundry', 'google' ) == 'google' ) ? array(
      array(
        'element'  => 'body',
        'property' => 'font-family',
      ),
    ) : array(),
  ) );
```

**Comment by aristath** [comment]
OK, I found the issue and I'm afraid it's not something that can be fixed.
I realize I had something similar in the wiki, that's my bad. I have removed it from the docs.

The problem is that output arguments are parsed when the setting + control are created.
So the state of the setting at the time the customizer loads is what determines if the customizer will be able to detect the output argument or not.

I tried switching the hooks that Kirki uses etc, but unfortunately there's a hole in the logic there...
So perhaps this workaround would do the trick for you:

``` php
  global $wp_customize;
  Kirki::add_field( 'wp_theme', array(
    'description' => __( 'Font Family', 'wp_theme' ),
    'type'        => 'select',
    'settings'    => 'body_google_font_family',
    'section'     => 'type_site',
    'default'     => 'Domine',
    'choices'     => Kirki_Fonts::get_font_choices(),
    'required'    => array(
      array(
        'setting'  => 'type_foundry',
        'operator' => '==',
        'value'    => 'google',
      )
    ),
    'output'      => ( $wp_customize || 'google' == get_theme_mod( 'type_foundry', 'google' ) ) ? array(
      array(
        'element'  => 'body',
        'property' => 'font-family',
      ),
    ) : array(),
  ) );
```

What this does is basically force the output to be on when in the customizer, and the conditional will continue to work as expected when not in the customizer.

It's the best I could do.

**Comment by mikedidthis** [comment]
Hi @aristath 

Makes sense and the workaround is more than enough.

Thank you again!

**Comment by aristath** [comment]
Update: Read this https://github.com/aristath/kirki/issues/697#issuecomment-190379812
In 2.2.0 I added an "exclude" argument that will do just what you need. :+1:
