### ISSUE TITLE
Kirki_Customizer_Scripts_Loading only in customizer preview

### ISSUE THREAD

**Issue by sebastianpisula** [themeum/kirki#589]
In constructor I can see register hooks:

```
add_action( 'wp_footer', array( $this, 'add_loader_to_footer' ) );
add_action( 'wp_head', array( $this, 'add_loader_styles_to_header' ), 99 );
$this->remove_default_loading_styles();
```

I think that should be:

```
if(is_customize_preview()){
     add_action( 'wp_footer', array( $this, 'add_loader_to_footer' ) );
     add_action( 'wp_head', array( $this, 'add_loader_styles_to_header' ), 99 );
     $this->remove_default_loading_styles();
}
```

And in add_loader_to_footer method is bug in <div>:
`<div class="kirki-customizer-loading-wrapper"/><span class="kirki-customizer-loading"></span></div>`

And should be:
`<div class="kirki-customizer-loading-wrapper"><span class="kirki-customizer-loading"></span></div>`

**Comment by aristath** [comment]
This has already been fixed in the develop branch and will be pushed in the next plugin release: https://github.com/aristath/kirki/blob/develop/includes/class-kirki-customizer-scripts-loading.php#L6-L9
