### ISSUE TITLE
Output doesn't seem to inline any css

### ISSUE THREAD

**Issue by Chocksy** [themeum/kirki#59]
I tried to use the output method but it seems there is no result. I added this line of code in the config.php file that i use to configure kirki:

```
wp_enqueue_style( 'style_name', get_template_directory_uri().'/css/style_name.css' );
```

I have the above css file in `css/style_name.css`.
After this i set the `stylesheet_id => 'style_name'` and set the output of a select element like so:

```
...
'output' => array(
   'element' => '#page',
   'property' => 'max-width',
   'units' => 'px'
)
```

Nothing happens the iframe refreshes but there is nothing happening. Also even if i save nothing happen. 

Should i expect something?

**Comment by aristath** [comment]
Hey there! 
Can you please test if this still occurs if you use the master branch?

**Comment by Chocksy** [comment]
@aristath nope it seems using the github master it all works. Thanks!! Closing it.

**Comment by lmartins** [comment]
Was the WordPress version updated with this resolved yet?
Not getting any CSS on my site...

Update: 
I've installed the github version but still not getting any css outputted. 

Im declaring the control like this:

``` php
function my_custom_setting( $controls ) {

    $controls[] = array(
        'type' => 'select',
        'setting' => 'body-font',
        'label'    => __( 'Body Font', 'wip' ),
        'section' => 'my_section',
        'choices' => Kirki_Fonts::get_font_choices(),
        'output'      => array(
            array(
                'element'  => 'body',
                'property' => 'font-family',
            ),
            array(
                'element'  => 'p',
                'property' => 'font-family',
            ),
        ),
        'help'        => __( 'This will create a "more info" questionmark on the right of the field, displaying this text when the user hovers over it', 'wip' ),

    );

    return $controls;
}
add_filter( 'kirki/controls', 'my_custom_setting' );
```

**Comment by aristath** [comment]
That's weird... is that on a publicly available repo I can download to test?
