### ISSUE TITLE
Kirki makes themes x3 slower, narrowed it down to get_google_fonts

### ISSUE THREAD

**Issue by Zackio** [themeum/kirki#590]
using grindcache I've found a very expensive function running multiple times, that's json encode in Kirki_Google_Fonts_Registry::get_google_fonts

It's running every time the style function is running which seems to be for every field that has styles.  My quick hack is to simply to not run it if it's not a typography field

`if( self::$field_type == 'typography' ) {
            $google_fonts_array = Kirki()->font_registry->get_google_fonts();
            $backup_fonts = Kirki()->font_registry->get_backup_fonts();
}`

Looking at the code though I think that it's only supposed to run once.

`if ( null == $this->google_fonts )` 

As I'm not familiar with the code base I'm not sure what's going wrong here. But it's making a massive impact on overall speed and the more options the worse it gets. But by limiting it to just typography fields makes a big difference

**Comment by aristath** [comment]
@Zackio thank you for reporting this one!
Can you please try pulling the latest changes from the [develop](https://github.com/aristath/kirki/tree/develop) branch?

Let me know if that fixes it for you. :+1:

**Comment by Zackio** [comment]
Tested it. The function only runs once now and I tested the typography function in the backend and front end and everything working perfectly. The customiser loads really quick now too, it was quite slow loading the preview before.

Thanks :)
