### ISSUE TITLE
Image uploader inside repeater not working on Firefox

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#594]
As stated in the title, the image uploader doesn't work in firefox when placed inside the repeater.
The repeater itself works perfectly but the three buttons (Add Image,  Change Image and Remove) don't.
Looks like commenting this line `if ( wp.customize.utils.isKeydownButNotEnterEvent( event ) ) return;` inside both `openFrame` and `removeImage` functions (lines 171 and 221 inside repeater.js ) fixes the issue but I have no idea why.
@sayedwp I think you're the one who have developed this part so maybe you have an idea of what's going on here. Also calling @aristath since is the man in charge :)
##

**Comment by mohdsayed** [comment]
Yes I see, I forgot to pass the event in function which is throwing error in firefox, Will send a pull request.

**Comment by manuelmoreale** [comment]
@aristath This one has been fixed so I think we can close it.
