### ISSUE TITLE
Sortable question

### ISSUE THREAD

**Issue by michellomp** [themeum/kirki#595]
Hi
I wonder if we can add fields to the sortable element for example add text area or checkbox 
the user could customize the sortable element 
or in reverse add sortable control on section 
Is something like that possible ?
Or the only option is to use widget ?

**Comment by aristath** [comment]
the sortable field currently only supports checkboxes. Adding more field types has been in my todo list for quite some time now, but it's not a priority.
Have you tried using the repeater control instead?

**Comment by michellomp** [comment]
Thanks for your quick reply 
Works great

**Comment by michellomp** [comment]
Your repeater control is great however is it possible to customize it
I mean if i want my taxonomies in the select option 
Is it possible to  inject taxonomies in the option ? : 

     `    $arr=Kirki_Helper::get_taxonomies();
              foreach ($arr as $value) {
               echo "choice' => $value<br />\n";
              }

          'subsetting' => array(
            'label'       => 'A selector',
            'type'        => 'select',
            'description' => 'lalala',
            'default'     => '',
           'choices'     => array(
                ''         => 'None',
                'choice_1' => 'Choice 1',
                'choice_2' => 'Choice 2'
            )
        ),`
