### ISSUE TITLE
js_vars doesn't work when units are used and function is style

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#598]
I'm using Kirki 2.2.4.

`js_vars` doesn't work when `units` are used and `function` is `style`. It works okay when the `function` is `css`.

The following code won't work unless we change `function` in `js_vars` to `css`.

``` php
Kirki::add_field( 'config_config', array(
  'settings'          => 'field_test',
  'type'              => 'number',
  'label'             => esc_html__( 'Field Label', 'nighthawk' ),
  'section'           => 'section_test',
  'default'           => 20,
  'sanitize_callback' => 'absint',
  'transport'         => 'postMessage',
  'js_vars'           => array(
    array(
      'element'  => '.element',
      'function' => 'style',
      'property' => 'padding-right',
      'units'    => 'px',
    ),
  ),
  'output'            => array(
    array(
      'element'  => '.element',
      'property' => 'padding-right',
      'units'    => 'px',
    ),
  ),
) );
```

Thus currently there is no way using `js_vars` with `units` for psuedo elements. Hopefully this would be the next version. :)

EDIT: Updated version number to 2.2.4.

**Comment by aristath** [comment]
That's weird....
`$prefix` is added on https://github.com/aristath/kirki/blob/2.0.7/includes/class-kirki-customizer-scripts-postmessage.php#L114 so it _should_ be working fine!

**Comment by aristath** [comment]
@rahulnever2far I just noticed you said in the original post you're using v2.0.7...
Can you please try using the latest stable version (2.1.0.1) or even better the [develop branch](https://github.com/aristath/kirki/tree/develop)?

**Comment by rahulv3a** [comment]
@aristath The issue persists in v2.1.0.1 and develop branch.

**Comment by rahulv3a** [comment]
Just wanted to confirm that this issue exists in 2.2.4 as well.

**Comment by aristath** [comment]
@rahulnever2far can you please try again using the develop branch?
I just refactored the way `postMessage` works in Kirki so we should be ok now

**Comment by rahulv3a** [comment]
@aristath Just tried the develop branch. It works now. Thank you so much for fixing this.

**Comment by aristath** [comment]
Awesome, thanks for testing!
