### ISSUE TITLE
kirki-styles.css 404 error since latest dev branch version

### ISSUE THREAD

**Issue by doitmax** [themeum/kirki#599]
I am getting a 404 error when using the latest version from the dev branch. The path to the kirki-styles.css file seems to be wrong. The server URL is added twice. This is how it looks like:

<pre>http://127.0.0.1/invictus_wphttp://127.0.0.1/invictus_wp/wp-content/themes/invictus/inc/kirki-master/assets/css/kirki-styles.css</pre>

Am i doing something wrong, although i haven't changed anything, or is it a bug? Additionally the kirki-styles.css is empty but custom CSS code inserted in the `<head>` section.

**Comment by aristath** [comment]
can you please pull the latest commit from the develop branch and test again?

**Comment by doitmax** [comment]
Fixed. Thanks :+1:
