### ISSUE TITLE
Js vars doesn't change anything

### ISSUE THREAD

**Issue by Chocksy** [themeum/kirki#60]
@aristath i'm having the following control and i was wondering why the postMessage doesn't seem to do anything.

```
$controls[] = array(
           'type'     => 'color',
           'setting'  => 'header_background',
           'label'    => __( 'Header Background Color', 'bargain' ),
           'section'  => 'colors',
           'default'  => '#1abc9c',
           'priority' => 1,
           'transport'=> 'postMessage',
           'js_vars' => array(
                 'element'  => '#masthead',
                 'type'     => 'css',
                 'property' => 'backround-color'    
                 )     
         );
```

I tried to modify the code in `class-kirki-scripts.php` and i was able to see that the `to` parameter is valid so a color and if i stop the execution with debugger i'm able to set the color. I also tried to change the method for selecting to this: 

```
$script .= '$("#customize-preview iframe").contents().find("' . $control['js_vars']['element'] . '").css("' . $control['js_vars']['property'] . '", to ? to : "" );';
$script .= '});';
```

I'm running wp 4.1.1 and using the already present `$("'.$control['js_vars']['element'].'")` does not seem to select it as it's in an iframe.

Is this something you guys are aware of?? If it is i might try to make a pull request if not maybe someone can guide me in the right direction.

**Thanks for the awesome plugin!!**

**Comment by aristath** [comment]
Hey there!

The `js_vars` argument is still an incomplete concept, it's far from complete and definitely not production-ready...
To be honest I haven't worked on that for quite a while now, the current implementation is mostly a reminder that we have to complete it.

Try this:
On this line: https://github.com/aristath/kirki/blob/e1c0f77a70b4f5a49030a4e613f99a43aceafe08/includes/class-kirki-scripts.php#L12 change `customize_controls_print_footer_scripts` to `customize_preview_init` and let me know if that works. :)

**Comment by Chocksy** [comment]
@aristath thanks for the response. I did try that but i get a jQuery is not defined error in the console. I'll definitely have a look at this and if i come up with a solution i'll make a pull request.

**Comment by aristath** [comment]
Fixed in the `develop` branch.

Please note that `js_vars` have to be defined as an array of arrays.
Example:

``` php
    $controls[] = array(
        'type'        => 'color',
        'setting'     => 'color_demo',
        'label'       => __( 'This is the label', 'kirki' ),
        'description' => __( 'This is the control description', 'kirki' ),
        'help'        => __( 'This is some extra help. You can use this to add some additional instructions for users.', 'kirki' ),
        'section'     => 'color_section',
        'default'     => '#0088cc',
        'priority'    => 10,
        'output'      => array(
            array(
                'element'  => 'a, a:visited',
                'property' => 'color',
                'units'    => ' !important'
            ),
            array(
                'element'  => '#content',
                'property' => 'border-color'
            ),
        ),
        'transport' => 'postMessage',
        'js_vars'   => array(
            array(
                'element'  => 'a, a:visited',
                'function' => 'css',
                'property' => 'color',
            ),
            array(
                'element'  => '#content',
                'function' => 'css',
                'property' => 'background-color',
            ),
        )
    );
```

If we want this to be change the HTML instead of the CSS then we'll have to change `'function'` to `'html'` and delete the `'property'`
