### ISSUE TITLE
Preview of pseudo-classes

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [themeum/kirki#606]
Hi aristath, first again, let me thank you for your great tool!

I experienced a little annoyance setting up my current theme. Nearly everything will be configurable via the customizer. This goes also for links and their hover-state as well as some ::before insertions. They don´t show up in the customizers preview. It needs to be saved and viewed on the frontpage or you´ll need to get out of the customizer and get into it again to see the changes.

Example code:

```
Kirki::add_field( 'lathom', array(
        'type'        => 'color-alpha',
        'settings'    => 'topbar_menu_hover_color',
        'label'       => __( 'Menu Text Hover Color', 'lathom' ),
        'description' => __( '', 'lathom' ),
        'help'        => __( '<strong>Notice:</strong> This works - but is kinda buggy.<br>Needs reload of the Customizer or to be viewed on the frontpage..', 'lathom' ),
        'section'     => 'topbar_color_settings',
        'default'     => 'rgba(' . hex2rgb($text_light) . ',1)',
        'priority'    => 110,
        'output'      => array(
            array(
                'element'  => 'a.nav-expander:hover',
                'property' => 'color',
            ),
        ),
        'transport'   => 'postMessage',
        'js_vars'     => array(
            array(
                'element'  => 'a.nav-expander:hover',
                'function' => 'css',
                'property' => 'color',
            ),
        ),
    ) );
```

**Comment by Thomas-A-Reinert** [comment]
Addon - same goes for the following configuration:

I want to set up a background color for older browsers who do not support gradients and a gradient for those who do.
Background ist set first in CSS so it shouldn´t be a stacking problem and shows up correctly when saved and viewed on frontpage anyway. Backgroundcolor shows up in preview at once.
But the gradients (set up after the background color) don´t.
Again - they do when saved and viewed on the frontpage.

**Comment by aristath** [comment]
Instead of `'function' => 'css',` try using `'function' => 'style',`
pseudo-elements are a bit weird so this is a workaround.

**Comment by Thomas-A-Reinert** [comment]
Works for both, the pseudo´s as well as the gradient.

Thumbs up! Thanks for not only solving this but for your constant and superfast support! One of the most enjoyable Gits here..

**Comment by aristath** [comment]
Thanks for your kind words, I really appreciate it! :+1:
I'm glad I could help
