### ISSUE TITLE
Checkbox is always checked

### ISSUE THREAD

**Issue by vladcosorg** [themeum/kirki#608]
All checkboxes, regardless of the actual values, are always rendered as checked. I've spot the issue in the following line

```
<input type="checkbox" value="{{ data.value }}" {{{ data.link }}}<# if ( data.value !== 'false' ) { #> checked<# } #> />
```

The 

```
data.value !== 'false'
```

should be 

```
data.value !== false
```

because the data.value is an actual boolean not a string.

**Comment by aristath** [comment]
Thanks for reporting this!

Fixed in the `develop` branch, I'll release a new version in a fe minutes and merge this in master.

**Comment by vladcosorg** [comment]
Thank you!
