### ISSUE TITLE
Feature Request: Show/Hide panels and sections using 'required'

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#611]
It would be great if had 'required' attribute for panels and sections. This would allow us to show/hide panels and sections according to a value of a certain option.

Use case scenario: My customizer is as follows:

```
Header (Panel)
|- Type (Section)
   |- Type (Type 1 | Type 2 | Type 3)
|- Logo (Section)
   |- Various logo options
|- Topbar (Section)
   |- Various topbar options
|- Main navigation (Section)
   |- Various main navigation options
|- Call to Action (Section)
   |- Various call to action options
|- Adverts (Section)
   |- Various Google Adsense options
```

On the website:
Header Type 1: Logo and Main Navigation.
Header Type 2: Logo, Topbar, Main Navigation and Call to Action.
Header Type 3: Logo, Topbar, Main Navigation, Call to Action and Adverts.

When Header Type 1 is selected, sections for Topbar, Call to Action and Adverts are useless. Hiding them would result in a better experience for the end user in my opinion.

We can show/hide panels and sections easily using CSS just like show/hide fields. What do you think?

**Comment by aristath** [comment]
I already have a ticket for that... https://github.com/aristath/kirki/issues/240
It will be implemented, right now it's just not a priority, there are issues more important that this. :smile: 

If I'm not mistaken you can add dependencies to all settings inside a panel/section. If a section does not have any active settings, WP _should_ automatically hide them (I haven't tried it though, it's just an assumption).

Closing this one as a duplicate :+1:

**Comment by rahulv3a** [comment]
I confirm that adding dependencies to all settings inside a section hides it :+1:
