### ISSUE TITLE
WP 4.5 Adding new customiser refresh, breaks kirki.

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#613]
Hey @aristath I just checked out a new feature that's rolling out in 4.5. Partial Refresh. 

Article - http://wptavern.com/customizer-responsive-preview-and-selective-refresh-to-be-merged-into-wordpress-4-5

Plugin - https://wordpress.org/plugins/customize-partial-refresh/

I've got the plugin activated and nothing happens when I try make live changes. Thought i'd give a heads up!

**Comment by aristath** [comment]
> I've got the plugin activated and nothing happens when I try make live changes.

Could you please elaborate? By "nothing happens", do you mean that when both Kirki & selective refresh plugins are activated, the Kirki output does not function anymore? Or that you don't see any partial refreshes on your page and everything works the way it did before?

**Comment by enkota** [comment]
Sure sorry, whenever I make a change in the customiser with both activated nothing changes live. For instance; change the font colour, nothing appears to change in the live preview. If I save changes the option will change as normal.

**Comment by scopeak** [comment]
I just tested with the twenty sixteen theme and it appears to be doing the same. Maybe the plugin is still in testing, will keep an eye on it!

**Comment by aristath** [comment]
WP 4.5 is scheduled to be released in mid-April and it still has some bugs that need to be resolved...
We'll be ready for it by the time it comes out. :+1:

**Comment by aristath** [comment]
@scopeak I just tested this one again and it looks like it's working fine now...
partial refreshes have been merged in WP Core, and from what I can tell this was a bug/WIP in the plugin that has since been fixed.
Can you please confirm?

**Comment by enkota** [comment]
@aristath awesome! I will do some testing soon and let you know.

**Comment by pagelab** [comment]
It's working fine now for me after updating WordPress to 4.5-alpha-36652

**Comment by enkota** [comment]
Yup same here! Great work.

**Comment by aristath** [comment]
Awesome!

btw I also added an implementation for partial refreshes in Kirki...
You can add something like this in your field:

``` php
'partial_refresh' => array(
    'header_site_title' => array(
        'selector'        => '.site-title a',
        'render_callback' => function() {
            return get_bloginfo( 'name', 'display' );
        },
    ),
    'document_title' => array(
        'selector'        => 'head > title',
        'render_callback' => 'wp_get_document_title',
    ),
),
```

The above code will do exactly the same as the code in https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/

**Comment by enkota** [comment]
Nice!

**Comment by pagelab** [comment]
Awesome! Thanks for the hint.
