### ISSUE TITLE
Field "editor" is still not working in firefox 

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#626]
editor is working in chrome but not working in firefox 

my code 

`Kirki::add_field( 'safreen', array(
    'type'        => 'editor',
    'settings'    => 'safreen_welcome',
    'label'       => esc_attr__( 'Home Page welcome section', 'safreen' ),
    'help'        => esc_attr__( 'This is a tooltip', 'safreen' ),
    'section'     => 'safreen_callout',
    'default'     => esc_attr__( 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.', 'safreen' ),
    'priority'    => 1,
) );` 
##

**Comment by aristath** [comment]
can you please test the new develop branch?
The editor fields were completely refactored.

**Comment by Imonthemes** [comment]
generate Js error and have a issue in css overflow screen not working dropdown control link h2 h1 and text color

`TypeError: c is not a constructor`

**Comment by aristath** [comment]
Fixed.
