### ISSUE TITLE
Update to 2.1.0 caused Undefined index

### ISSUE THREAD

**Issue by dameer** [themeum/kirki#627]
Hi!

Everything was workin right until the latest update to 2.1.0
Now all the fields defined as 
Kirki::add_field( 'field_name_xx', array( ...... ) );
...end up with 
"Undefined index ... ..wp-content/plugins/kirki/includes/class-kirki-customizer-scripts-postmessage.php on line 56"

Any idea what happened?

**Comment by aristath** [comment]
Thanks! I just missed adding a check... it's fixed now in the master branch, I'll push the modification to w.org ASAP.
