### ISSUE TITLE
typography control won't apply after settings are saved

### ISSUE THREAD

**Issue by qerrapress** [themeum/kirki#629]
When I change a font with Typography fonts control second time nothing happens. I mean, the first time I change the font, it works, then I save it, and after changing it again, nothing happens.(Firefox)

**Comment by aristath** [comment]
Yeah, this is a known bug.
I still haven't been able to figure out why this happens, but as you said the typography control works fine until you save the options. Once you save, you have to refresh to get it working again.
I completely refactored and rebuilt the typography field in the `develop` branch but this still happens.
Not sure why yet

**Comment by aristath** [comment]
Closing in favor of #717 where I also set up a bounty.
