### ISSUE TITLE
Fatal error with Kirki and Bootstrap shell.

### ISSUE THREAD

**Issue by briancwelch** [themeum/kirki#63]
Warning: Illegal string offset 'body' in E:\Web\wp-content\plugins\kirki\includes\class-kirki-style.php on line 140

Fatal error: Cannot use string offset as an array in E:\Web\wp-content\plugins\kirki\includes\class-kirki-style.php on line 140

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/1bbd9db6fd399c40a82150f1eb0805dbfc22162d
