### ISSUE TITLE
Remove Button don't remove Image in Image Repeater Field

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#631]
Hi @aristath, @sayedwp

I've been using Kirki for my project. I like the Image Repeater Field. But there seems to be an issue when we remove the image in repeater field. When the image is removed the customizer "Saved" button doesn't change to "Save & Publish". Also if we make changes in other field and remove the image and hit "Save & Publish" button and we refresh customizer, the other field is updated but the image remains there
![remove image not working in image repeater field](https://cloud.githubusercontent.com/assets/16412478/13138957/1206bdc4-d652-11e5-8083-01b4a849c55c.png)
. Can you please look at this. 

Thanks

**Comment by aristath** [comment]
@manandharsudin thank you for reporting this!
I just merged a commit submitted by @sayedwp that fixes this issue so we'll include this in the next release.
