### ISSUE TITLE
Warnings on latest Update

### ISSUE THREAD

**Issue by doitmax** [themeum/kirki#638]
I am getting warnings for background fields on the latest version:

<pre>Missing argument 2 for Kirki_Field::sanitize_id(), called in 
{PATH}/kirki-master/includes/class-kirki-explode-background-field.php on line 98 
and defined in {PATH}/kirki-master/includes/class-kirki-field.php on line 466</pre>

Of course "only" warnings and could be removed with `define( 'WP_DEBUG', false );` but just wanted to let you know.

**Comment by enkota** [comment]
+1 getting these too.

Latest develop fixed! Thanks for the quick fix @aristath

**Comment by aristath** [comment]
:+1: thanks for reporting this guys!
I just updated the master branch too.

**Comment by enkota** [comment]
Getting a couple more warnings today @aristath on latest branch. 

`Warning: Invalid argument supplied for foreach() in /kirki/includes/googlefonts/class-kirki-googlefonts-field-processor.php on line 64`

**Comment by aristath** [comment]
@scopeak can you please test this again? I believe it was fixed in the latest master branch

**Comment by enkota** [comment]
Yup all sorted. Cheers!

**Comment by enkota** [comment]
Hey @aristath just testing the beta 2. There's a few warnings up again if you aren't aware - 

`Warning: Invalid argument supplied for foreach() in /kirki/includes/class-kirki-field.php on line 360`

**Comment by aristath** [comment]
@scopeak I just finished refactoring that class, can you please check again?

**Comment by aristath** [comment]
Tested, and fixed the last remaining notice just now.

**Comment by enkota** [comment]
Brilliant! Cheers @aristath

**Comment by RonalddeRooij** [comment]
I'm getting the following warning: Warning: Invalid argument supplied for foreach() in /kirki/includes/class-kirki-field.php on line 172

**Comment by enkota** [comment]
@RonalddeRooij Yes, getting them here too now - 

`Notice: Undefined index: exclude in /kirki/includes/output/class-kirki-output.php on line 74`
