### ISSUE TITLE
Panel bug on Firefox

### ISSUE THREAD

**Issue by qerrapress** [themeum/kirki#641]
When there are enough sections to make scrollbar appear in panel, the sections kinda -margin-left to the side, when I click on any of the sections and then go back to panel page itself, everything goes back to normal.

Tried to fix it for a few hours now but it's too tricky.

**Comment by aristath** [comment]
@qerrapress hey there!

I tried to rteplicate this but couldn't so far.
Do you have any styling applied to the customizer via Kirki? (for example the width or its colors?)
What version of WP are you using?

**Comment by qerrapress** [comment]
I have custom color accent and color back. Wp version 4.4.2. When I make any kind of refresh, it goes back to normal (click right mouse button, go to section, open/close "inspect element" bar)

**Comment by aristath** [comment]
This is a WordPress Core bug.

To test it I deactivated the Kirki plugin and in my theme's `functions.php` file I added this:

``` php
function aristath_custom_test_settings( $wp_customize ) {

    $panels_nr   = 10;
    $sections_nr = 5;
    $fields_nr   = 2;

    // Create panels
    for ( $panel_id = 0; $panel_id <= $panels_nr; $panel_id++ ) {

        $wp_customize->add_panel( 'panel_' . $panel_id, array(
            'title'      => sprintf( __( 'Panel %s', 'my_theme' ), $panel_id ),
            'capability' => 'edit_theme_options',
        ) );

        // Create sections
        for ( $section_id = 0; $section_id <= $sections_nr; $section_id++ ) {
            $wp_customize->add_section( 'panel_' . $panel_id . '_section_' . $section_id, array(
                'title'      => sprintf( __( 'Panel %1s Section %2s', 'my_theme' ), $panel_id, $section_id ),
                'capability' => 'edit_theme_options',
                'panel'      => 'panel_' . $panel_id,
            ) );

            // create fields
            for ( $field_id = 0; $field_id <= $fields_nr; $field_id++ ) {
                $setting = 'panel_' . $panel_id . '_section_' . $section_id . '_field_' . $field_id;
                $wp_customize->add_setting( $setting, array(
                    'default'    => '',
                    'type'       => 'theme_mod',
                    'capability' => 'edit_theme_options',
                ) );
                $wp_customize->add_control( $setting, array(
                    'label'    => sprintf( __( 'Panel %1s Section %2s Field %3s', 'my_theme' ), $panel_id, $section_id, $field_id ),
                    'section'  => 'panel_' . $panel_id . '_section_' . $section_id,
                    'settings' => $setting,
                    'type'     => 'text',
                ) );
            }
        }
    }
}
add_action( 'customize_register', 'aristath_custom_test_settings' );
```

The above code will create 10 panels, inside each panel 5 sections, and inside each section 2 fields using the WordPress Customizer API.

I was able to replicate your issue without Kirki, so you may want to [report this bug in WP Core](https://make.wordpress.org/core/handbook/testing/reporting-bugs/) instead. :+1:

**Comment by carasmo** [comment]
Confirmed, happens w/o Kirki too.
