### ISSUE TITLE
Negative numbers on number field

### ISSUE THREAD

**Issue by allysonsouza** [themeum/kirki#644]
Hi, I'm having problems when I set a negative number to my number field. The customizer just stop to be loaded. Here's my field:

```
Kirki::add_field( '', array(
    'type'        => 'number',
    'settings'    => 'my_number',
    'label'       => __( 'My label.', 'textdomain' ),
    'section'     => 'my_section',
    'default'     => 0,
    'priority'    => 10,
    'choices'     => array(
        'min'  => -9999,
        'max'  => 9999,
        'step' => 1
    ),
    )
);
```

The slider field works normally, but my range is too big (-9999 to 9999), so the slider lost their precision. I tried to look into the code but I don't get what's wrong, any idea?

Thanks

**Comment by aristath** [comment]
Thank you for reporting this!

It was a typo in the JS file, fixed now in the develop branch. :+1:
