### ISSUE TITLE
Fatal error: Access to undeclared static property: Kirki_GoogleFonts_Manager

### ISSUE THREAD

**Issue by mikedidthis** [themeum/kirki#655]
```
Fatal error: Access to undeclared static property: Kirki_GoogleFonts_Manager::$font_weights in E:\WebMatrix\wp-base\wp-content\plugins\kirki\includes\googlefonts\class-kirki-googlefonts-field-processor.php on line 74
```

Maybe a typo? Should it be `Kirki_Google_Fonts_Manager`. Sorry I couldn't be more helpful.

**Comment by aristath** [comment]
Hey there! This should be fixed now, can you please try pulling the master branch again and testing?
We completely rewrote the googlefonts implementation yesterday, so if you find any more bugs please do let us know (no matter how small)

**Comment by mikedidthis** [comment]
Hi @aristath !

Master seems to be fixed. Will there be a version bump for this fix or just retro fitted into `v2.1.0.1`?

Thanks

Mike

**Comment by aristath** [comment]
this will be 2.2.0 when released :+1:

**Comment by mikedidthis** [comment]
Magic, thank you again for this and all the hard work!

:cake:
