### ISSUE TITLE
'transport' => 'postMessage',

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#656]
How i add 'transport' => 'postMessage', when typing in text,textarea,editor ?

Please help me !!!

**Comment by aristath** [comment]
https://github.com/aristath/kirki/wiki/Automating-postMessage-scripts

**Comment by Imonthemes** [comment]
sorry man bothering you 

but what i am puting when 'type'      => 'textarea', ?

`'element'  => '',
            'function' => '',
            'property' => '',`

what is the function here ? 
Please help

**Comment by Thomas-A-Reinert** [comment]
https://github.com/aristath/kirki/wiki/Text-Controls#creating-a-textarea-control

**Comment by aristath** [comment]
function: `html`
element: the css identifier of the element whose contents you wish to modify
property: leave empty.
