### ISSUE TITLE
Color control doesn't clear

### ISSUE THREAD

**Issue by WebTrooper** [themeum/kirki#66]
I just discovered that once a color is selected it does not clear or revert to the default color. When clicking the "Clear" button it does clear the color from the control, temporarily, but it does not clear the setting -- the theme still has the color applied and, when opening the customizer again, the color is still selected. 

I tried with a set default and an empty default, the clear button just doesn't work. Sorry for not providing any technical details as I'm just the end user, not a coder. Let me know if you need a var_dump or debug info.

**Comment by briancwelch** [comment]
Hello,

I was able to replicate this yesterday internally and spent a bit of time trying to track down the issue.    We will have this resolved as soon as possible.

**Comment by aristath** [comment]
Fixed in #74 :+1:
