### ISSUE TITLE
VR 2.2.0 ( textarea filed blank )

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#661]
After reload the customize  page or enter again from dashboard  textarea filed appear blank  !!!

but it was works in 2.0.8 after update this issue appear  

Please help

**Comment by aristath** [comment]
can you please post your config and the code for your field?

**Comment by Imonthemes** [comment]
Kirki::add_field( 'safreen', array(
    'type'        => 'textarea',
    'settings'    => 'safreen_footertext',
    'label'       => esc_attr__( 'Footer Text.', 'safreen' ),
    'section'     => 'layout_front_page',
    'priority'    => 10,
    'transport' => 'postMessage',

) );

Just write something in textarea field then click save option.go back your dashboard or reloaded customize page . Then again go to section and check textarea filed blank all text gone

**Comment by aristath** [comment]
> can you please post your config and the code for your field?

You did not include your config... Can you please post what the `safreen` config looks like?

Also, when posting code on github please make sure it's properly formatted... it makes life a lot easier if we can see code formatted like actual code: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by aristath** [comment]
nvm, found the bug.
I'll merge it in the master branch in a few minutes (after it passes the tests on https://github.com/aristath/kirki/pull/662)

**Comment by Imonthemes** [comment]
Thank you very much ,you are grate
