### ISSUE TITLE
Add url( [^link^] ) when use background-image as property in js_vars

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#673]
Hi pal,

I discovered an issue when use js_vars with upload control, When assign 'background-image' in property field it prints only the url like [ background-image: ^link^ ] but it must be [ background-image: url ( [^link^] ) ].

Thanks for your awesome project.

**Comment by aristath** [comment]
Wow, I don't know how I missed that!

Thank you for reporting this, I'll have it fixed asap. :)

**Comment by Serpentsoft** [comment]
A lot of code you must miss some lol, Good Luck

**Comment by aristath** [comment]
I believe this has now been fixed in the master branch, I would appreciate it if you tested it though to confirm it works :+1:
