### ISSUE TITLE
Radio-image doesn't work in IE11

### ISSUE THREAD

**Issue by dameer** [themeum/kirki#674]
Hi,
is there anyone capable/willing to confirm that radio-image select doesn't work in IE11? It's all right in IE9 and IE10 but for some strange reason I can't get it work in IE11. 
Debugger / console shows no error or whatsoever and I'm pullin my hair off for the past couple of hours. 
Radio-image is just not clickable at my end. Also checked in FF, Safari and Chrome on MacOS and everything seems to be fine.

Thanks!

**Comment by aristath** [comment]
@dameer hey there!

The only problem here is that I don't have a windows machine so I can't test this... I'll have to just take your word for it!
If you do manage to figure this one out though, please do let us know what's wrong exactly so that we may fix it (or better yet, you can submit a pull request against the `develop` branch with a fix)

**Comment by dameer** [comment]
Basically, I'm using VirtualBox on Mac to test websites in Internet Explorer which doesn't let me resolve the problem cause. Developer tools for IE is the only choice I've got. Beside, none of my comrades and coworkers is Windows user. Strange how come everyone abandoned Windows. Tho, I don't wonder why.

So, I'm 100% sure that radio-image select doesn't work in IE11. No matter what I do (considering limited resources) takes no improvement.
I'll just switch from radio-image to the "regular" select because it works all right.
Hopefully there will be someone capable to puzzle out what's going on with radio-image in IE11.

**Comment by dameer** [comment]
OK, I think I've got it. The most probably solution is here : http://madebyted.com/blog/using-images-as-labels-inside-forms-in-internet-explorer-11/
Hopefully someone can give it a shot and eventually submit a pull request...

**Comment by aristath** [comment]
Thanks for your research!
I'm really surprised this issue came up... 'cause I do remember it in the "old days".

I'm currently working on refactoring the typography control, this one is next on my list. :+1:

**Comment by aristath** [comment]
I believe this was just fixed...
Can you please checkout the [develop branch](https://github.com/aristath/kirki/tree/develop) and let me know if the issue is fixed for you there?
(don't test from the master branch, master has been reset to 2.1.0.1. The develop branch where work on version 2.2.0 is being done)

**Comment by dameer** [comment]
I'm not quite skilled here at GitHub but I guess we are talking about this file: https://github.com/aristath/kirki/blob/7d2f4e86212aaa1a26746f7ce17176b45a173781/assets/css/customizer.css

Unfortunately, I can't confirm it works, the problem still persists in IE11. I'll try something else and let you know the result.

**Comment by dameer** [comment]
OK, here's why it didn't work...

There's actually no _checked_ input in HTML for non-selected radio-image:
`.customize-control-radio-image input:checked + label .image-clickable { ... }`

...however, if we just use:
`.customize-control-radio-image input + label .image-clickable { ... }`

things are back to normal in IE11. So, this one worked fine on : 
MacOS - FF (latest), Chrome (latest), Safari (latest)
Windows 7 (VirtualBox) - IE9, IE10, IE11 (edge)

Hopefully it helps, thanks for sorting this out!

**Comment by aristath** [comment]
Excellent!

Fixed, thank you for your assistance! :+1:
