### ISSUE TITLE
Number control within repeater control

### ISSUE THREAD

**Issue by biswajit-saha** [themeum/kirki#675]
I am trying to add a number control within a repeater control but it is not showing. I have tried the following code within the repeater control.

```
'fields' => array(
    'category_section_post_count' => array(
        'type'        => 'text',
        'label'       => esc_attr__( 'Number of Post', 'textdomain' ),
        'description' => esc_attr__( 'How many post you want to show', 'textdomain' ),
        'default'     => 4,
    ),
)
```

I have checked and then tried to add number control within **class-kirki-controls-repeater-control.php** file but I have not succeeded. Here is the code I have tried.

```
<# } else if ( field.type === 'number' ) { #>

    <label>
        <# if ( field.label ) { #>
            <span class="customize-control-title">{{ field.label }}</span>
        <# } #>
        <# if ( field.description ) { #>
            <span class="description customize-control-description">{{ field.description }}</span>
        <# } #>
        <div class="customize-control-content">
            <input type="text" {{{ data.link }}} data-field="{{{ field.id }}}" value="{{{ field.default }}}" />
        </div>
        </div>
    </label>

<# } #>
```
##

**Comment by aristath** [comment]
Number controls require some additional JS to properly work... You can see how they're implemented here: https://github.com/aristath/kirki/blob/master/assets/js/controls/number.js
In addition to the aboive things you've already done you'll also have to implement number controls in the repeater.js file on https://github.com/aristath/kirki/blob/master/assets/js/controls/repeater.js and then run `grunt` from a terminal to compile the customizer.js file with your changes. :+1: 

We'll include number controls in repeaters at some point, right now it's just not our first priority...
If you get it working I'd be more than happy to merge your modifications if you submit a pull request against the `develop` branch :smile: 
If not, then you'll have to wait a while before we address other issues and get back to the repeater

**Comment by biswajit-saha** [comment]
Thank you very much for your reply. I am new on this. I will try to make it work. If it works then I will submit a pull request. If I can't then I will use text field instead of number in my theme for now and will wait for it. :)

For now can it be used?

```
<input type="number" data-field="{{{ field.id }}}" value="{{{ field.default }}}" />
```

**Comment by piperhaywood** [comment]
Just wanted to give a +1 to this particular issue. (and also, thanks for creating such a great tool for WP!)

**Comment by aristath** [comment]
Closing this one as it's part of #837
