### ISSUE TITLE
Bug textarea field when text is set to default

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#679]
When you set a default value for textarea field in customizer appear several empty white space before. This prolblema the feedback with the current version on github. I include photos.
Davide
![senza-titolo-2](https://cloud.githubusercontent.com/assets/7602983/13350961/bc271f2e-dc83-11e5-8c8b-c10557df49d3.jpg)

**Comment by sododesign** [comment]
I just wanted to update the current version of WordPress does not have this problem of the field that leaves white spaces

**Comment by aristath** [comment]
fixed in the master branch. :+1: Can you please confirm that it's ok for you too?

**Comment by sododesign** [comment]
Yes @aristath now work perfect :)
