### ISSUE TITLE
Registering new control types

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#683]
Sorry, is this documentation still valid: https://github.com/aristath/kirki/wiki/Registering-new-control-types

I see you use Kirki_Customize_Control class instead of WP_Customize_Control.

**Comment by aristath** [comment]
hmmm... I forgot about that filter, I'll make some modifications in a couple of hours and get this one working again :+1:

**Comment by pixedelic** [comment]
Thank you! The old filter works anyway... maybe you'll interrupt to support it in the future, so I asked you

**Comment by aristath** [comment]
nope, this one is really useful to a lot of people so it stays. :+1: 
I just have to make sure the sanitization in the `Kirki_Field` class doesn't interfere, that's all.

**Comment by aristath** [comment]
Seems to be ok, no further steps need to be taken in `Kirki_Field` :+1:

**Comment by pixedelic** [comment]
:+1:
