### ISSUE TITLE
New Theme for Kirki.org

### ISSUE THREAD

**Issue by mohdsayed** [themeum/kirki#688]
This is not an issue, but since I could not find any way of contacting @aristath  I am posting it here. I noticed that kirki.org is not on WordPress so I created a WordPress theme for it just to say thanks to @aristath  for creating such wonderful toolkit for us. 
I have uploaded the demo here on http://taqui.in/kirki/ and of course I will remove it once @aristath sees it.

**Comment by aristath** [comment]
Hey there buddy!

Sorry for not seeing this sooner, this is just a really busy period both in my day job in with the on-progress refactoring of Kirki.

The theme looks great! I see you also sent me a copy on an email, thank you!
There are plans to migrate kirki.org on a new WordPress site that will include many tools, so this will surely come in handy! :+1: 
(If you're wondering about the "tools" I mentioned above, checkout [kirki.io](http://kirki.io))

**Comment by mohdsayed** [comment]
Oh I see that's great, looking forward to the tools you are going to create. All the best. :+1:

**Comment by danyj** [comment]
You might want to center that mid section , this is what I see 

http://prntscr.com/a8nl4a
