### ISSUE TITLE
Repeater field - default rows with unique values?

### ISSUE THREAD

**Issue by gustafguner** [themeum/kirki#690]
Hey. How do you add default values to a repeater field? The closest I have gotten is to set the `default` value to the following

``` php
'default'     => array(
        array(
             'test'
        )
    ),
```

This, however, only adds one empty row by default. What I would like to achieve is to by default have 3 rows filled with unique information. Is this possible?

**Comment by aristath** [comment]
Hey there!

I think I had this one working a couple of months back... Check out this sample code:
https://github.com/aristath/kirki-demo/blob/3aad83dd98dea7aa3a228824c58b87e722f989c3/functions.php#L462-L494

Let me know if that works for you!

**Comment by gustafguner** [comment]
@aristath Works like a charm, thank you!
