### ISSUE TITLE
Font issue. Blured font.

### ISSUE THREAD

**Issue by slipets-a** [themeum/kirki#691]
Hello.
I have a theme with Kirki plugin in it. And font is blured.
![1z17og3 1](https://cloud.githubusercontent.com/assets/16901280/13378314/856b1dda-de0b-11e5-8388-bab408a2d329.jpg)
Its work fine at main page, but looks blured in the posts.
[Example](http://gavrilenko.eu/blog/2016/02/25/%D0%B1%D0%B8%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F-%D1%85%D1%83%D0%B4%D0%BE%D0%B6%D0%BD%D0%B8%D0%BA%D0%B0-%D1%82%D0%B0%D1%82%D1%8C%D1%8F%D0%BD%D1%8B-%D0%B3%D0%B0%D0%B2%D1%80%D0%B8%D0%BB%D0%B5/)

**Comment by rahulv3a** [comment]
Kirki toolkit has anything to do with this.

`transform: translateX(171.5px);` on `<div id="page" class="hfeed site 2_column_lor">` is causing the blurriness. Removing it fixes the issue.

**Comment by aristath** [comment]
Nope, Kirki has nothing to do with this. It must be coming from someplace else...

**Comment by slipets-a** [comment]
Actually when I disable Kirki this problem disappears.

**Comment by aristath** [comment]
@49h4DhPERFECT is this a premium theme?
It may disapear when you're disabling Kirki, but it's not caused by Kirki.
Have you contacted the theme author about this?
Can you please send me a copy of that theme so that I may examine what goes on?

**Comment by slipets-a** [comment]
@aristath  Here it is - http://qerrapress.com/quidus-theme/#comment-457

**Comment by aristath** [comment]
Can you please send me a copy of your theme?

**Comment by slipets-a** [comment]
Here it is - http://www.ex.ua/712222868269

**Comment by aristath** [comment]
The issue is in your theme.
File: `js/functions.js`
Lines 47-51 look like this:

``` js
    if ((wwidth >= 1088)) {

        $('.2_column_lor').css('transform', 'translateX(' + ttlw / 2 + 'px)');

    }
```

Please contact your theme author... `translateX` and all similar functions are notorious for causing blurred typography.

**Comment by slipets-a** [comment]
Thx a lot.
