### ISSUE TITLE
Color clear

### ISSUE THREAD

**Issue by Ontegor** [themeum/kirki#697]
Hello!
My code 

```
Kirki::add_field( 'pt_theme', array(
    'type'        => 'color', 
    'settings'    => 'pt_header_color',
    'label'       => __( 'Background', '' ),
    'section'     => 'header_general',
    'default' => '',
     'output' =>  array(
          array(
              'element'  => '.header-inner',
              'property' => 'color',
         )
    ),
) );
```

When I select a color, then all is well. When I click the "Clear" button, nothing happens. How do I happened to update previews and property "color" is not excreted in the css?
Thank you

**Comment by aristath** [comment]
This is something I've been working on and I just pushed a commit to the develop branch.
I added an "exclude" argument.
Your code was like this:

``` php
Kirki::add_field( 'pt_theme', array(
    'type'        => 'color', 
    'settings'    => 'pt_header_color',
    'label'       => __( 'Background', '' ),
    'section'     => 'header_general',
    'default'     => '',
    'output'      =>  array(
        array(
            'element'  => '.header-inner',
            'property' => 'color',
        )
    ),
) );
```

you will have to modify your code and write it like this:

``` php
Kirki::add_field( 'pt_theme', array(
    'type'        => 'color', 
    'settings'    => 'pt_header_color',
    'label'       => __( 'Background', '' ),
    'section'     => 'header_general',
    'default'     => '#FFFFFF',
    'output'      =>  array(
        array(
            'element'  => '.header-inner',
            'property' => 'color',
            'exclude'  => array(
                '#FFFFFF',
                '#DEDEDE',
            ),
        ),
    ),
) );
```

Note the differences:
- The default value is NOT empty, it has a color in it... say for example the default color for your header background. If you don't want to use a background by default on that, then just set the default value to `rgba(255,255,255,0)` which is transparent.
- an `exclude` argument was added and it's formatted as an array of elements. In this example, the field will not output any CSS if the value is equal to `#FFFFFF` OR `#DEDEDE`.

This will be included in the next release, but if you want to test it out you can get the latest develop branch from here: https://github.com/aristath/kirki/archive/develop.zip

**Comment by RonalddeRooij** [comment]
I'm trying to use the exclude for the spacing element, but it seems to be not working:

`Kirki::add_field(  'caramelomedia', array(
    'type'      => 'spacing',
        'settings'  => 'footer_padding_top_bottom',
        'section'   => 'footer_margin_padding',
        'label'     => esc_html__( 'Padding top & bottom', 'caramelomedia' ),
        'default'   => array(
            'top'    => '0',
            'bottom' => '0',
            ),
        'transport' => 'auto',
        'output'    => array(
            array(
                'element'  => 'footer',
                'property' => 'padding',
                'exclude' => array(
                    '0',
                    ),
                )
            ),
        ) );`

However I get this working on a number element:

`Kirki::add_field( 'caramelomedia', array(
        'type'      => 'number',
        'settings'  => 'footer_padding_top_top',
        'section'   => 'footer_margin_padding',
        'label'     => esc_html__( 'Padding top', 'caramelomedia' ),
        'default'   => '0',
        'transport' => 'auto',
        'output'    => array(
            array(
                'element'  => 'footer',
                'property' => 'padding-bottom',
                'exclude' => array(
                    '0',
                    ),
                )
            ),
        ) );`

Could you please help me out to exclude values from a spacing element.

Somehow the code won't be displayed properly (excuse me)

**Comment by aristath** [comment]
The value in the exclude argument should have the same format as the control itself. So similar to the default value...

If you want to exclude top:0 & bottom: 0, then you should use it like this:

``` php
'exclude' => array(
    array(
        'top'    => '0',
        'bottom' => '0',
    ),
)
```

I almost missed this comment... Next time please create a new ticket instead of commenting on an old unrelated & already closed ticket to make sure someone sees it. 👍

**Comment by RonalddeRooij** [comment]
Thank you very much!!

I was thinking about that, creating a new topic but I was like I will 
post it here because it had something to do with it.
In the future I will create a new ticket.

Met vriendelijke groet,

Ronald de Rooij

E-mail: r.derooij@caramelo-media.nl mailto:r.derooij@caramelo-media.nl
Telefoon: 013 711 5172
Website: www.caramelo-media.nl http://www.caramelo-media.nl

Op 23/08/2016 om 02:53 schreef Aristeides Stathopoulos:
