### ISSUE TITLE
Order of Google Fonts

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#698]
Google Fonts are sorted by popularity I guess. Is it possible to change its sort order to alphabetical? If yes, how can I do it?

**Comment by aristath** [comment]
Actually this is something I wanted to do for quite some time now and I was always forgetting it.
Google fonts now use alpha order by default. (fixed in the develop branch on commit https://github.com/aristath/kirki/commit/a458705d20498e3082922ca728e957a9fe8e0e47)

**Comment by rahulv3a** [comment]
@aristath Thank you :)
