### ISSUE TITLE
adding new section types

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#703]
WordPress recently added the ability to register new panel & section types.
What that means is we can add our own templates that will be used for rendering templates.

I already added an "expanded" section type, and now I would like some ideas about what other section & panel types we may add.

The "expanded" section-type is a section that is always visible.
I've had numerous requests to add controls inside panels instead of nested in sections that are inside the panels, so you can - visually - achieve this using the expanded section.
To make a section expanded, all you have to do is add `'type' => 'expanded'` when registering a section with Kirki like this:

``` php
Kirki::add_section( 'text', array(
    'title'          => esc_attr__( 'Text Controls', 'kirki-demo' ),
    'priority'       => 2,
    'capability'     => 'edit_theme_options',
    'type'           => 'expanded',
) );
```

And in case you were wondering what it looks like to have a section expanded in the middle of a panel, here's a screenshot:

![customize](https://cloud.githubusercontent.com/assets/588688/13417202/11aef85e-df72-11e5-8906-766c98403f10.png)

As you can imagine, if you use primarily expanded sections inside a panel, you can treat a panel as a section, with sections being used as sub-sections with pretty titles inside the panel, and normal sections can be used for secondary/not-so-often-used options.

So... any ideas on what panel/section types to add on Kirki 2.2.0?

**Comment by pixedelic** [comment]
Great! I can't wait to try it. Are now possible nested panels as well?

**Comment by rahulv3a** [comment]
Love the idea of `'type' => 'expanded'`. I was already looking for something similar :+1:

**Comment by aristath** [comment]
> Great! I can't wait to try it. Are now possible nested panels as well?

I just added expanded panels as well. Though I'm not sure exactly how those would be used... The only use I can see for them is as titles to separate sections.

**Comment by aristath** [comment]
Adding a screenshot.
This is what I have here:
On the top there's a normal section in the customizer, followed by an expanded panel.
The expanded panel contains a section, and after that section you'll see there's a small margin... that's where the expanded panel ends (margin acts as a visual/contextual separator).
After that, there's an expanded section and a normal section:

![customize](https://cloud.githubusercontent.com/assets/588688/13442388/a925443a-e004-11e5-969b-f757104773ce.png)

**Comment by Rayken** [comment]
Would it be possible to have these sortable?

The idea here is to have a panel called "Front Page Sections". Each sub-section would be a set of multiple fields such as background image/color and such. These sections would be created by looping each post in a custom post type called 'sections'. This would give me a way of setting up each section of the front page (using the check for front page). Basically having these sub-sections sortable would correspond to which order the sections appear on the front page. Drag and drop would be intuitive just like menus and widgets are sortable.

Would this feature be suitable? Could it be extended?

**Comment by rahulv3a** [comment]
@Quaked Why not use a [repeater field](https://kirki.org/docs/controls/repeater.html) for this? It also has an `Add Row` button which eliminates the need to create sections using a post type called 'sections'. Plus, it has a drag n drop interface as you want.

Even if you need to do it using a post type called `sessions`, you could populate rows using a simple WP_Query.

**Comment by Vishal-Deshpande** [comment]
@Quaked  As rightly said by @rahulnever2far repeater field can do the trick. I managed to build a simple home page builder with Kirki by using repeater field, select drop down, radio image control and helper methods mentioned below.
https://kirki.org/docs/advanced/helper-methods.html

**Comment by aristath** [comment]
I agree 100% with what was said above.
Sections & panels are meant to organize settings.
Their order is not saved anywhere, so it would technically be impossible to do this.
You can use a repeater, or a sortable field to achieve what you need.
