### ISSUE TITLE
PHP error 2.2.0

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#704]
PHP error  class-kirki-fonts.php in line : 141,142 etc

**Comment by aristath** [comment]
details please.
what does the error say?

**Comment by Imonthemes** [comment]
notice: undefined offset 

check the screen shot 
![screenshot](https://cloud.githubusercontent.com/assets/10571385/13436009/6088db8a-e007-11e5-8329-19c52ee5bb9e.jpg)

**Comment by aristath** [comment]
It looks like this only happens on Windows servers because for some reason windows can't differentiate a string from an integer in PHP.

Have you tried it on a real server?
I'll get this fixed, it's just weird... What are you using for development? WAMP? XAMPP? Something else?

**Comment by Imonthemes** [comment]
I was tested in xampp ,wamp ,mamp also tested in Windows and Mac  but not test in real sever .

Thanks

**Comment by Imonthemes** [comment]
And other issue is editor some time work in mac Firefox some time not

**Comment by Imonthemes** [comment]
error is still showing : 

`[05-Mar-2016 14:50:25 UTC] PHP Notice:  Undefined variable: element in C:\xampp\htdocs\wordpress\wp-content\themes\safreen\inc\kirki\includes\class-kirki-field.php on line 821
`

I was found it in debug.log and one php notice 

![screen](https://cloud.githubusercontent.com/assets/10571385/13548199/c952477c-e314-11e5-95d7-2d5e64e033da.png)

**Comment by aristath** [comment]
Fixed.
Thank you for reporting this, I really appreciate it!

Please do not put all the errors you find in a single ticket... They are different issues, and when a ticket is closed I rarely see updates to it. It was by pure chance that I saw your message...

**Comment by Imonthemes** [comment]
sorry for that . I new in GitHub :(
