### ISSUE TITLE
Set a limit of repeater rows?

### ISSUE THREAD

**Issue by gustafguner** [themeum/kirki#705]
Hey,

Is it possible to set a limit of how many repeater rows you can add? And maybe even a lower limit? So that you, for example, can't remove fields so that the amount is less than 2 and can't add so that the amount is higher than 6.

**Comment by aristath** [comment]
Hey there!

Unfortunately this is not something we considered when building this control...
Everything's possible, so I'm marking this one as a feature request for a future version. :+1:

**Comment by x-bull** [comment]
I am missing this feature too :+1:

**Comment by BeFiveINFO** [comment]
Hello!

I have a question, I am trying to use the repeater and I just encountered with the following warning:

> Notice: Undefined index: limit in ...wordpress/wp-content/plugins/kirki/includes/controls/class-kirki-controls-repeater-control.php on line 95
> Limit: rows

Is this related to the change above perhaps?

**Comment by aristath** [comment]
Yes, it's still a work in progress...
I'm currently working on a bugfix for that, I'll push it in a few minutes. :)

**Comment by aristath** [comment]
@BeFiveINFO try pulliing the develop branch now, this should be fixed.

**Comment by BeFiveINFO** [comment]
Thank you :) 
P.S. I hope that I did not disturb you.

**Comment by aristath** [comment]
> P.S. I hope that I did not disturb you.

No bother... I was working on it anyway. :+1: 
I really appreciate any bug reports... It's what helps this plugin get better every day.

@gustafguner @x-bull @BeFiveINFO This has now been implemented and I'm about to release version 2.2.4 that will include it.
To add a limit to repeater controls, you can add the following:

``` php
'choices' => array(
    'limit' => 3
),
```

3 being of course the number of rows you want to allow.

**Comment by BeFiveINFO** [comment]
Thank you :) . :+1:
