### ISSUE TITLE
Exclude Kirki styles from Widgets in Customizer

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#706]
All Kirki styles currently apply to Widgets in the customizer. I have checkboxes in widgets which are styled similar to toggles in Kirki. They look and work fine at `WordPress Dashboard > Appearance > Widgets`. But they are messed up at `WordPress Dashboard > Appearance > Customizer > Widgets`  because they pick up Kirki's styles for a checkbox.

Is there any way to limit the scope of Kirki styles so that they don't apply to Widgets in the Customizer? Or I will have to add custom CSS to Customizer in order to fix my custom fields in Widgets.

Not a big issue. Just letting you know about it :)

PS: 400 closed issues... Yay!

**Comment by aristath** [comment]
Hey there!

Can you download a fresh copy and check if this has been fixed for you?

**Comment by rahulv3a** [comment]
Just tried v2.2.0.beta.2. The issue has been fixed.

Thank you for developing Kirki so active. We all appreciate the time and effort you put into this :)
