### ISSUE TITLE
Dropdown for category ids?

### ISSUE THREAD

**Issue by regan008** [themeum/kirki#708]
I may just be missing this in the documentation, but I don't see it. Is there a way to generate a select list of category ids with Kirki? 

Thanks so much for this library -- it is making my life so much easier with the new theme directory requirements!

**Comment by aristath** [comment]
@regan008 Hey there!

Id depends... Are you using the stable version from wordpress.org, or are you using the beta version from this repository?

On the stable version we did not have that functionality, on the beta version here we added it a couple of days ago:

``` php
$categories = Kirki_Helper::get_terms( 'category' );
```

Cheers!

**Comment by regan008** [comment]
Awesome! I am indeed using the github version.  So, will that turn the categories into key value pairs for me so I can include them in a dropdown? Sorry trying to figure out how to integrate that.  Can I just do: 

``` php
$categories = Kirki_Helper::get_terms( 'category' );

Kirki::add_field( '', array(
    'type'        => 'select',
    'settings'    => 'select_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'help'        => __( 'This is some extra help text.', 'kirki' ),
    'section'     => 'my_section',
    'default'     => 'option-1',
    'priority'    => 10,
    'choices'     => array($categories),
) );
```

**Comment by aristath** [comment]
>  So, will that turn the categories into key value pairs for me so I can include them in a dropdown?

Yup!
key = category ID
label = category name

As for the code, you can do it like this:

``` php
Kirki::add_field( '', array(
    'type'        => 'select',
    'settings'    => 'select_demo',
    'label'       => __( 'This is the label', 'kirki' ),
    'description' => __( 'This is the control description', 'kirki' ),
    'help'        => __( 'This is some extra help text.', 'kirki' ),
    'section'     => 'my_section',
    'default'     => 'option-1',
    'priority'    => 10,
    'choices'     => Kirki_Helper::get_terms( 'category' ),
) );
```

Just use the `Kirki_Helper::get_terms( 'category' )` method directly in the `choices` argument.

**Comment by regan008** [comment]
Amazing -- thank you so much for your help!
