### ISSUE TITLE
Direct child of a selector doesn't work anymore.

### ISSUE THREAD

**Issue by RonalddeRooij** [themeum/kirki#714]
Hi,

I had the following field:

``` php
array(
    'element'  => '.navbar-nav > li > a',
    'property' => 'padding-top',
    'units'    => 'px',
),
```

This was working properly until I downloaded the latest Kirki. 

I looks like there is no output when i'm using the > sign in any of my "fields elements".

To fix this I had to remove the > sign like so:

```
array(
    'element'  => '.navbar-nav li a',
    'property' => 'padding-top',
    'units'    => 'px',
),
```

Greets Ronald

Keep up the good work!!

**Comment by aristath** [comment]
Thank you for reporting this!
I believe it was just fixed, can you pelase test this and let me know if you're still having an issue?

**Comment by RonalddeRooij** [comment]
Thanks! This solved my issue!

**Comment by RonalddeRooij** [comment]
Hi, it looks like it isn't working anymore in 2.3.1.

When i'm in the customizer the class is working properly. After saving my changes the class isn't outputted as before.

**Comment by aristath** [comment]
Hey again!

I just tested this in the develop branch and it seems to be working fine...
Can you please verify it works for you?
If it doesn't, can you let me know the exact control you're using that has an issue and paste here the complete code for that example control?

**Comment by RonalddeRooij** [comment]
Hey,

i'm using the following code:

// Background color menu item hover 
    Kirki::add_field( 'caramelomedia', array(
        'type'        => 'color-alpha',
        'settings'    => 'background_color_menu_item_hover',
        'label'       => esc_attr__( 'Achtergrondkleur hover ', 'caramelomedia' ),
        'section'     => 'header_menu',
        'default'     => 'rgba(0,0,0,0)',
        'output'      => array(
            array(
                'element'  => '.navbar-nav > li:hover > a',
                'property' => 'background-color',
            ),
        ),
    ) );

Everything works fine editing in the customizer but after saving it's gone.

**Comment by aristath** [comment]
I just tested your code with the latest version of Kirki released yesterday and it's working fine.
This is the CSS that Kirki outputs when not in the customizer: 
`.navbar-nav > li:hover > a{background-color:rgba(129,215,66,0.71);}`

**Comment by RonalddeRooij** [comment]
Thanks! It's working fine right now!
