### ISSUE TITLE
Get value from array Repeater

### ISSUE THREAD

**Issue by NickHeurter** [themeum/kirki#715]
Hi Aristeides, hope you are doing well. I was wondering if it's possible to get both the key as the value from a repeater setting? I've got a repeater where the user can add their other languages from the same website:

``` php
$controls[] = array(
    'type'        => 'repeater',
    'label'       => __( 'Countries Links', 'onm_textdomain' ),
    'help'        => __( 'On the first place you should choose the country of the current website.', 'onm_textdomain' ),
    'section'     => 'countries_languages_section',
        'priority'    => 30,
    'settings'    => 'countries',
    'default'     => array(),
    'fields' => array(
        'code' => array(
                'type'        => 'select',
            'label'       => __( 'Country', 'onm_textdomain' ),
                    'choices'     => array(
                'af' => 'Afghanistan',
                'zw' => 'Zimbabwe',
                    ),
        ),
        'url' => array(
                'type'        => 'text',
            'label'       => __( 'Link URL', 'onm_textdomain' ),
            'default'     => 'https://www.theleansixsigmacompany.'
        ),
    )   
);
```

And I was hoping that I could get both the value as the key from the code array? 

Thanks already for your help!

**Comment by gustafguner** [comment]
If I understand your question right, this can be done in the following way. Set up a field:

``` php
Kirki::add_field( 'config', array(
    'settings' => 'test_settings',
    'label'    => __( 'Buttons', 'theme_slug' ),
    'section'  => 'test_section',
    'type'     => 'repeater',
    'priority' => 10,
    'default' => array(
        array(
            'label' => esc_attr__( 'Example', 'kirki-demo' ),
        )
    ),
    'fields' => array(
        'label' => array(
            'type'        => 'text',
            'label'       => esc_attr__( 'Label', 'kirki-demo' ),
        )
    ),
) );
```

After values have been added to this repeater you can reach its value like this

``` php
$my_repeater = Kirki::get_option( 'config', 'test_settings' );
```

To visualize its value, just var dump it:

``` php
var_dump($my_repeater);
```

There you can see the keys and the values. Hope this helped?

**Comment by aristath** [comment]
@NickHeurter hey there!

First of all, make sure you're properly adding your field: https://github.com/aristath/kirki/wiki/Getting-Started#adding-fields

Then, the simplest method would be to try this in your `functions.php`:

``` php
var_dump( get_theme_mod( 'countries', array() ) );
```

This way you'll get an idea of the structure the saved values have.
You can then get then however you like. :+1: 

Please note that before adding the above line to your functions.php you'll have to go to your customizer and enter some sample data in that control so that you have something to see.

**Comment by NickHeurter** [comment]
Hi @gustafguner and @aristath, thanks a lot for your help guys. Awesome!

**Comment by fakrulislam** [comment]
Can anyone help me to get the values from a repeater field group for displaying on the frontend?
I am trying to add a repeater field group for slider & using image, textarea, text & url field types. Can't find any docs which describe how to display repeater field groups on frontend.

Hi @NickHeurter did you figured it out? Could you please paste the code here in case you get the fields values successfully.

My repeater fields code:

```
    my_theme_Kirki::add_field( 'mytheme_config', array(
        'type'        => 'repeater',
        'label'       => esc_attr__( 'Add Slides', 'my_theme' ),
        'description' => __( 'You can add unlimited slides, so add as much slides as you want.', 'my_theme' ),
        'section'     => 'my_theme_front_page_section',
        'priority'    => 10,
        'settings'    => 'my_theme_slide_option',
        'default'     => array(),
        'fields' => array(
                'ol_slide_image'        => array(
                'type'                  => 'image',
                'label'                 => esc_attr__( 'Upload image', 'my_theme' ),
                'default'               => '',
            ),
                'ol_slide_retina_image' => array(
                'type'                  => 'image',
                'label'                 => esc_attr__( 'Upload 2x image', 'my_theme' ),
                'description'           => esc_attr__( 'retina devices required 2x (double) size image for displaying HD view.', 'my_theme' ),
                'default'               => '',
            ),
                'ol_slide_text'         => array(
                'type'                  => 'text',
                'label'                 => esc_attr__( 'Slide title', 'my_theme' ),
                'default'               => '',
            ),
                'ol_slide_short_desc'   => array(
                'type'                  => 'textarea',
                'label'                 => esc_attr__( 'Slide short description', 'my_theme' ),
                'default'               => '',
            ),
                'ol_slide_button_text'  => array(
                'type'                  => 'text',
                'label'                 => esc_attr__( 'Button text', 'my_theme' ),
                'default'               => '',
            ),
                'ol_slide_button_link'  => array(
                'type'                  => 'url',
                'label'                 => esc_attr__( 'Button link', 'my_theme' ),
                'default'               => '',
            ),                                              
        )
    ) );
```

I am getting this values with the **var_dump( get_theme_mod( 'my_theme_slide_option', array() ) );** . But can't figure out how to display them in frontend.

`array(1) { [0]=> array(6) { ["ol_slide_image"]=> string(2) "37" ["ol_slide_retina_image"]=> string(2) "35" ["ol_slide_text"]=> string(19) "This is slide title" ["ol_slide_short_desc"]=> string(24) "Slide short description." ["ol_slide_button_text"]=> string(10) "learn more" ["ol_slide_button_link"]=> string(17) "http://google.com" } }`

Any help will be appreciated. Thanks

**Comment by aristath** [comment]
Let me just format your `var_dump` so it's easier to see the structure:

```
array(1) {
    [0]=> array(6) {
        ["ol_slide_image"]        => string(2) "37"
        ["ol_slide_retina_image"] => string(2) "35"
        ["ol_slide_text"]         => string(19) "This is slide title"
        ["ol_slide_short_desc"]   => string(24) "Slide short description." 
        ["ol_slide_button_text"]  => string(10) "learn more" 
        ["ol_slide_button_link"]  => string(17) "http://google.com" } }
```

So you'l have to do something like this:

``` php
$my_theme_slide_option_value = get_theme_mod( 'my_theme_slide_option', array() );

foreach ( $my_theme_slide_option_value as $item ) {
    echo '<p>Image: ' . $item['ol_slide_image'] . '</p>';
    echo '<p>Retina Image: ' . $item['ol_slide_retina_image'] . '</p>';
    echo '<p>Text: ' . $item['ol_slide_text'] . '</p>';
    echo '<p>Description: ' . $item['ol_slide_short_desc'] . '</p>';
    echo '<p>Button Text: ' . $item['ol_slide_button_text'] . '</p>';
    echo '<p>Button Link: ' . $item['ol_slide_button_link'] . '</p>';
}
```

This of course is a bit over-simplified, but I'm sure you'll get the point.

**Comment by fakrulislam** [comment]
Awesome! thanks @aristath , it seems quite simple. I got the clue, will let you know it works or not.

**Comment by fakrulislam** [comment]
It worked! 

As you can see I have used two image fields but they're returning numeric values **37**, **35** not image urls . Could you please help me how can I get the urls instead of numeric values. 

image fields

```
$item['ol_slide_image']
$item['ol_slide_retina_image']
```

output
**37**
**35**

Thanks, appreciate your help.

**Comment by aristath** [comment]
See the [`wp_get_attachment_image_src`](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/) function.

**Comment by fakrulislam** [comment]
Thanks for the help @aristath it worked!

**Comment by NickHeurter** [comment]
Hi @fakrulislam, sorry for the late response. I see that @aristath already helped you figuring out how to solve your problem. Awesome!
