### ISSUE TITLE
Select box is not properly displayed in Expanded panels

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#718]
### Issue description:

![untitled-1](https://cloud.githubusercontent.com/assets/3503359/13521268/3daf59b0-e20d-11e5-89ec-f9897606d249.png)
### Version used:

2.2.0.beta.2
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_section( 'section_header_type', array(
  'title' => esc_html__( 'Header Type', 'kirki' ),
  'type'  => 'expanded',
  'panel' => 'panel_header',
) );

Kirki::add_field( 'config', array(
  'settings' => 'header_type',
  'type'     => 'select',
  'label'    => esc_html__( 'Type', 'kirki' ),
  'section'  => 'section_header_type',
  'default'  => 'type-1',
  'choices'  => array(
    'type-1' => esc_html__( 'Type 1', 'kirki' ),
    'type-2' => esc_html__( 'Type 2', 'kirki' ),
    'type-3' => esc_html__( 'Type 3', 'kirki' ),
    'type-4' => esc_html__( 'Type 4', 'kirki' ),
  ),
) );
```

**Comment by aristath** [comment]
Thanks for all the details! They really help fix bugs quicker (I'm beginning to like these github issue templates... :+1:

**Comment by rahulv3a** [comment]
Thank you for fixing it in a matter of hours :)

Anything to make your life easier :+1:
