### ISSUE TITLE
Latest dev branch issues.

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#719]
### Issue description:

Hey @aristath, I updated to the latest dev branch today to test it out and it seems to have broken a few things with my theme. Some of my panels are gone now, not too sure what's causing that. I have a lot of php notices but mostly just undefined indexes. Do you think it could be related to this? The theme was running good on the main branch, so it could just be something that's still needing to be completed?

`Notice: Array to string conversion in /kirki/includes/output/class-kirki-output.php on line 80`

`Notice: Undefined index: exclude in /kirki/includes/output/class-kirki-output.php on line 98`

Did the way background images output change too since the master version?
### Version used:

Latest develop branch
### Using theme_mods or options?

options

**Comment by enkota** [comment]
Okay I sourced back through the commits and everything breaks on this commit. 

https://github.com/aristath/kirki/tree/97d40d980bee90392a9dee5138340ccfd8d1b7d4

https://github.com/aristath/kirki/commit/97d40d980bee90392a9dee5138340ccfd8d1b7d4

`allow HTML in descriptions`

Was this around the time the background field changed? The panels are there in that commit so will continue tracing back for that bug!

**Comment by enkota** [comment]
The panels seem to break around this commit.

https://github.com/aristath/kirki/commit/8a4e46f2888bb0ba86e3b67ab69c090aa6cc9ff1

https://github.com/aristath/kirki/tree/8a4e46f2888bb0ba86e3b67ab69c090aa6cc9ff1

`Kirki_Field rewrite - 1st pass`

Hope that helps! Trying to do some more debugging myself.

**Comment by aristath** [comment]
Can you please send me a copy of your theme?

**Comment by enkota** [comment]
Yes sure, i'll email it to you now!

**Comment by aristath** [comment]
Thanks for sending me your theme, it really helped me understand why you were getting notices & warnings and why things were not working for you. :+1: 

I pushed a couple of commits a few minutes ago, things should be working for you now so I'm closing this one.

If you have any more trouble open a new ticket :smile:

**Comment by enkota** [comment]
Thanks @aristath. Not a problem, will be going through the changes now and making adjustments :)
