### ISSUE TITLE
Multiple css properties output on a single color?

### ISSUE THREAD

**Issue by giathinh910** [themeum/kirki#72]
Firstly, thank for your great product.
I 'd like to ask that can we generate multiple css properties on a single color declaration. For example, for a color, can I generate color and background-color css output.

**Comment by briancwelch** [comment]
Kirki now supports multiple output elements, all you have to do now is define them in an array, like so:

```
'output' => array(
                    array(
                        'element'  => '.element',
                        'property' => 'color',
                    ),
                    array(
                        'element'  => '.element',
                        'property' => 'background-color',
                    ),
```

**Comment by giathinh910** [comment]
Thank you so much.
