### ISSUE TITLE
Issue when using double quotes inside textarea

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#721]
### Issue description:

Hi pal, Thanks for your support for old issues i had written and sorry because i'm very busy now and cannot test it.

When using Shortcodes inside Textarea and after save you encode all double quotes i think you using [esc_textarea] but when retrieving value you have to decode it again to be  " **double quotes** " 

Now every time i want to modify shortcode text i have to convert encoded into normal double quotes.

Thanks for you support.
### Version used:

2.1.0.1

**Comment by aristath** [comment]
@Serpentsoft hey there!

Textarea fields are now sanitized using `wp_kses_post` so it should be fine in the latest beta... Please let me know if you have the same issue on 2.2.0.beta.3 from this repository.

**Comment by misfist** [comment]
I'm not able to get my shortcodes to render when put into the text area; they just appear as entered ([year]  [site_name]  [site_description] , etc ). They render when put in a text widget, so I know they work...

Do I need to do something in order for shortcodes to rendered?

Any guidance is appreciated.
