### ISSUE TITLE
Color-alpha not live updating.

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#722]
Hey @aristath I know you mentioned working on the JS vars auto updating but the Colour-alpha output isn't live updating currently. Not sure if this is related to https://github.com/aristath/kirki/issues/694 ?

Cheers! :)

**Comment by aristath** [comment]
Can you post the field's configuration please?

**Comment by enkota** [comment]
Sure, just to clarify; the overlay color updates after saving and closing but the live changes aren't visible :+1: 

```
//Image Background Color
Kirki::add_field( 'kirki', array(
    'type'        => 'color',
    'settings'     => 'kirki_img_color',
    'label'       => __( 'Image Background Color', 'kirki' ),
    'description' => __( 'Pick the image background color.', 'kirki' ),
    'priority'    => 20,
    'default'     => '#222',
    'active_callback' => '__return_false',
    'section'     => 'kirki_image_options',
) );

//Image Overlay Color
Kirki::add_field( 'kirki', array(
    'type'        => 'color-alpha',
    'settings'    => 'color_alpha_options',
    'label'       => esc_attr__( 'Overlay Color/Opacity', 'kirki' ),
    'description' => esc_attr__( 'Change the overlay color and opacity for background images', 'kirki-options' ),
    'section'     => 'kirki_image_options',
    'default'     => 'rgba(0,0,0,0.3)',
    'priority'    => 20,
    'output'      => array(
        array(
            'element'  => array(
                '.layer',
                '.layer-2',
            ),
            'property' => 'background-color',
        ),
    ),
) );
```

**Comment by aristath** [comment]
Why do you have `'active_callback' => '__return_false',` in there???

**Comment by aristath** [comment]
@scopeak I disabled the automatic `js_vars` generation from the `output`, it's not yet mature enough for production.
Test it again and let me know if it works for you now that I disabled it...

**Comment by enkota** [comment]
Sure thing and I have that in as I don't need the first colour field. I thought we needed it for the alpha one to work?

Edit: Just downloaded latest version, there's a parse error in there I believe :+1: 
`Parse error: syntax error, unexpected 'return' (T_RETURN) in /kirki/includes/class-kirki-explode-background-field.php on line 157`

**Comment by aristath** [comment]
> I thought we needed it for the alpha one to work?

Nope, not anymore... that was last year. Since then I was able to fix that issue :+1:

**Comment by enkota** [comment]
Nice! I'll just remove that then, thanks again :+1:

**Comment by enkota** [comment]
@aristath You had a `;` missing in `class-kirks-explode-background-field.php` on line `157`

`$i18n = Kirki_l10n::get_strings();`

Cheers!
