### ISSUE TITLE
Using Kirki with Child Theme

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#723]
When using Kirki with a child them I lose the ability to make changes to text/code/dropdowns and the Save and Publish button is inactive. I can continue to make changes to colors and styling though.

The child theme is simply a child theme folder with a style.css file in it.

Do you know how I can resolve this?

**Comment by enkota** [comment]
I have child theme support with my theme currently and don't appear to have that problem. How are you enqueuing it in the child theme?

**Comment by ghost** [comment]
I haven'y enqued it in the child theme, I though as long as it is in the Parent theme it should be fine otherwise I thought you would be adding it twice.

Can I ask how it should be enqued in the child theme?

**Comment by enkota** [comment]
I had made a post about it a few weeks back - https://github.com/aristath/kirki/issues/610#issuecomment-184178976 Hope that helps :+1:

**Comment by dameer** [comment]
Are you using Kirki as a plugin or just include it to the parent theme? If used as a plugin (which is preferred method) then everything works just right down the inheritance line.

**Comment by ghost** [comment]
@scopeak I had a look at this but it seems more to be related to the CSS rather than text values.

@dameer I'm embedding it in theme.

**Comment by aristath** [comment]
@livingwandsworth can you please send me a copy of your theme & child theme so that I may replicate the issue and understand what the bug actually is? It's the only way I'll be able to actually understand this and fix it...

**Comment by ghost** [comment]
@aristath Sure I will e-mail you shortly.

**Comment by aristath** [comment]
Resolved via email, was not a bug :+1:

**Comment by leanda** [comment]
Hi @aristath 

I'm having the same issue. Child theme and styles are working as they should except kirki fields are not working and the Save and Publish button is inactive. Any help much appreciated. Thanks.

**Edit:** I looks like the kirki styles are not loading in the child theme and I've getting a 404.

**Comment by aristath** [comment]
@leanda Can you please create a new ticket instead?
This one was due to an error in the theme and it's highly unlikely you have the same issue.
Thanks!

**Comment by leanda** [comment]
Did I not already do that with this ticket number  #1500? Or do you mean open a ticket somewhere else?

Thanks

**Comment by aristath** [comment]
Sorry, I missed that ticket 👍
