### ISSUE TITLE
Undefined index letter-spacing...

### ISSUE THREAD

**Issue by wilrevehl** [themeum/kirki#724]
### Issue description:

Undefined index: letter-spacing in includes\controls\class-kirki-controls-typography-control.php on line 115. Tried using the Typography composited field but it throws an undefined index error which breaks the JS output. I removed all use of letter-spacing from the field param choices, but it still throws the error. Thanks for your hard work.

**Comment by aristath** [comment]
Thanks for reporting this!
Fixed. :+1:
