### ISSUE TITLE
Empty number fields set to zero when emptying. Desire empty = unset.

### ISSUE THREAD

**Issue by wilrevehl** [themeum/kirki#725]

**Comment by aristath** [comment]
`number` fields are sanitized as numbers. When you leave the value empty, the PHP sanitization call will automatically convert it to `0`.

You could try adding this function:

``` php
/**
 * Sanitize numbers, allowing empty values
 *
 * @param $value string|int|float
 * @return string|int|float
 */
function my_theme_sanitize_numbers( $value ) {
    if ( '' == $value ) {
        return $value;
    }
    return Kirki_Sanitize_Values::number( $value );
}
```

and then add this in your field:
`'sanitize_callback' => 'my_theme_sanitize_numbers',`

**Comment by wilrevehl** [comment]
Ah, great to know. Thanks a lot for the tip!
