### ISSUE TITLE
Kirky() function called after  after_theme_setup causing kirki/config filter functionality to be undone

### ISSUE THREAD

**Issue by rnlmedia** [themeum/kirki#732]
### Issue description:

The Kirky() function is called after after_theme_setup in numerous places and causing issues where setting $config['url_path'] using the kirki/config filter is needed. 

As this Kirky() function eventually ends up calling set_url() in class-kirki-init.php, it resets Kirky::url, undoing the work of the filter.

A possible fix is to run the config filters in set_url?

Workaround is to comment out $kirki->api   = new Kirki(); I can't see anywhere this is implemented yet?
### Version used:

2.1.0.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` php
if ( ! function_exists( 'my_theme_kirki_update_url' ) ) {
    function my_theme_kirki_update_url( $config ) {
        $config['url_path'] = get_stylesheet_directory_uri() . '/inc/foobar/';
        return $config;
    }
}
add_filter( 'kirki/config', 'my_theme_kirki_update_url' );

```

This function is run, but Kirky::url eventually gets overwritten as described above.

**Comment by aristath** [comment]
Hey there!

Can you please test this with the version from this repository?
I think this has already been fixed, though I'd appreciate a confirmation.
You can get the new (beta) version from https://github.com/aristath/kirki

**Comment by rnlmedia** [comment]
@aristath Yes, works perfect, apologies, I really should have double checked that first, great work, thanks!
