### ISSUE TITLE
Illegal offset type error with typography

### ISSUE THREAD

**Issue by qerrapress** [themeum/kirki#735]
### Issue description:

I get error when using latest version - Warning: Illegal offset type in plugins\kirki\includes\output\control\class-kirki-output-control-typography.php on line 19
### Using theme_mods or options?

Theme mod

**Comment by aristath** [comment]
@qerrapress Can you please download the plugin from this repository and test if that fixes your issue?
I'll be releasing an update later today and I'd appreciate a confirmation that this has been fixed :+1:

**Comment by qerrapress** [comment]
It's fixed.
