### ISSUE TITLE
Alpha Color always enabled

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#737]
### Issue description:

Hi my friend, Congratulations for the latest update...

Unfortunately Alpha Color control has alpha enabled always with alpha property true and false the both values make alpha enabled and you know sometimes we need the background of control to be solid to use :after and :before pseudo classes without appear from behind of the control.

*\* Ref. Documentation [https://kirki.org/docs/controls/color.html](url) you use 'alpha' => true outside 'choices' array.

Sorry for inconvenient and Thanks for your support.

Best
### Version used:

2.2.0
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( CONFIGKIRKIPREFIX, array(
    'type'        => 'color',
    'choices'     => array( 'alpha' => false ),
    'settings'     => (DB_CUSTOMIZER_CONTROL . '_theme_main_color'),
    'label'       => __( 'Theme\'s Main Color', THEMETEXTDOMAIN ),
    'description' => '',
    'help'        => '',
    'section'     => 'sec_maincolor',
    'default'     => THEMEMAINCOLOR,
    'transport'   => 'postMessage',
    'priority'    => 10,
```

**Comment by aristath** [comment]
I don't know how I missed that... thank you for reporting this!
Fixed, will be included in the next release (today or tomorrow)
