### ISSUE TITLE
Typography color

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#742]
### Issue description:

Hi

I am testing new color option in typography field. Doesent work (tested on localhost and live site...)
error:
customizer.js:1430 Uncaught ReferenceError: compiled_value is not defined
### Version used:

2.2.2.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'eleganto_settings', array( 
    'type'        => 'typography',
        'settings'    => 'content_typography_font',
                'label'       => __( 'Site content font', 'eleganto' ),
        'section'     => 'colors_section',
        'default'     => array(
            'font-family'    => 'Oswald',
            'font-size'      => '14px',
            'variant'        => '300',
            'line-height'    => '1.8',
            'letter-spacing' => '0px',
                        'color'          => '#ffffff',
        ),
        'priority'    => 10,
        'output' => array(
            array(
                'element'  => 'body, .fa.menu-item a, .home-header .page-header a',
              ),
        ),
   ) );

```

![typography](https://cloud.githubusercontent.com/assets/14072537/13897909/f63c5e46-edc1-11e5-8472-4d36b7e63c12.jpg)

**Comment by aristath** [comment]
Thank you for reporting this!

Fixed in the develop branch, will be included in the next release :+1:
