### ISSUE TITLE
Toggle description styling/customizer styling

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#743]
### Issue description:

Find some small styling bugs
1. The toggle field description not fit.
2. If you style the customizer width and try to collapse the customizer he never fully collapse
`$config['width']        = '25%';`
### Version used:

2.2.2.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

![toggle](https://cloud.githubusercontent.com/assets/14072537/13898534/f979678a-edd4-11e5-9100-17255de56d58.jpg)
![collapse](https://cloud.githubusercontent.com/assets/14072537/13898535/0431ca50-edd5-11e5-8cdf-a07e60f5faf8.jpg)

**Comment by aristath** [comment]
good catch!
Fixed in the develop branch, will be included in the next release. :+1:

**Comment by x-bull** [comment]
Sorry for reopening

The toggle is now similar like switch. In previous versions was the toggle button positioned inline after title on the right side. I was using it as "place saver" ...

**Comment by aristath** [comment]
ok, this took some creative CSS thinking but I think we're ok now. :+1:
