### ISSUE TITLE
Kirki utility functions producing unexpected results

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#749]
### Issue description:

I have been using Kirki color functions for a while and have noticed since the last update the colors being generated are substantially different from what they were before. 

Here's how I usually use them:

```
.woocommerce-checkout-review-order
            {
                background: <?php echo Kirki_Color::adjust_brightness($page_bg, 15); ?>;
            }
```

The goal here is to take the bg color and brighten up a bit to ensure contrast to the background. What im getting now is the exact opposite, im getting a much darker color than the original im modifying.
### Version used:

2.2.3
### Using theme_mods or options?

theme_mod
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_field( 'kirki_options', array(
    'type' => 'color',
    'section' => 'colors_generic',
    'settings' => 'page_bg',
    'default' => '#f2f3f0',
    'label'    => __( 'Page Background', 'wip' ),
    'description' => __( 'Sets the main background for entire page.', 'wip' ),
    'output' => array(
        array(
            'element'  => '
                .site-container
                ',
            'property' => 'background-color'
        ),
    ),

) );


function mw_dynamic_colors_css() {

    $page_bg          = kirki_get_option('page_bg');

?>

<style type="text/css">
.woocommerce-checkout-review-order
            {
                background: <?php echo Kirki_Color::adjust_brightness($page_bg, 15); ?>;
            }
}
</style>

    <?php

}

add_action( 'wp_head', 'mw_dynamic_colors_css' );

```

**Comment by aristath** [comment]
@lmartins can you pelase try replacing the `class-kirki-color.php` file with this one and let me know if that fixes your issue? https://gist.github.com/aristath/8126c745e1ea908bdd05

**Comment by lmartins** [comment]
It does change something, but still getting weird results.
For example, I would expect that the following code to brighten the `$page_bg` substantially:

```
background: <?php echo Kirki_Color::adjust_brightness($page_bg, 230); ?>;
```

Instead it gets darker. I was under the impression the amount passed as the second parameter was a 0..100 value, tried with values under 100 and still not the results expected.

**Comment by aristath** [comment]
In the old implementation steps were from -255 (darken) to 255 (lighten).
In the new implementation I switched to a new colors-calculation class for greater versatility and performance (see https://aristath.github.io/ariColor/) and the new class uses values 0-100 for brightness values - just like the previous one _should_ do, but it was ill-conceived when I started Kirki 2 years ago... so now I just have to make some conversions to make sure the old implementation will still accept values ranging from -255 to 255, then convert them to the right brightness level for the new class, and then pass them on to the new class.
It's not hard... just something I did not think of originally.
Can you please try again? I just updated the gist with a couple more changes... should be better now.

P.S. Sorry for using you as a lab-rat here, but some things I can't do without help.

**Comment by lmartins** [comment]
@aristath no need to be sorry, really. Thank you so much for your help here.

The weird thing about it is that this line:
https://www.dropbox.com/s/ztypvobsn775xta/Screenshot%202016-03-20%2016.08.27.png?dl=0

now outputs a dramatic change to the original color:
https://www.dropbox.com/s/356swj0yydvl7ei/Screenshot%202016-03-20%2016.09.16.png?dl=0

The original color being passed to the function is what defines the main background. The function is changing the color of the table now displaying black.

**Comment by aristath** [comment]
OK, I believe I just fixed this.
I tested the old implementation and the new one with random colors side-by-side and they return the exact same results now. :+1: 
Can you please verify it?
I just pushed a commit to the develop branch.

**Comment by lmartins** [comment]
It might be a problem on my end, but im seeing a strange behaviour:

With both:

``` php
background: <?php echo Kirki_Color::adjust_brightness($page_bg, 100); ?>;
```

or:

``` php
background: <?php echo Kirki_Color::adjust_brightness($page_bg, -10); ?>;
```

I get the same output on the front-end:
https://www.dropbox.com/s/7ftg52is7l48s1i/Screenshot%202016-03-20%2016.28.57.png?dl=0

Considering that $page_bg has the light grey visible in the page background, I would expect the first one to output white and the second one a slightly darker grey.

The `$page_bg` variable is created with:

``` php
$page_bg          = kirki_get_option('page_bg');
```

Can this have any relation with the problem?

**Comment by aristath** [comment]
Can you try using this instead?

``` php
$page_bg = get_theme_mod( 'page_bg', '#ffffff' );
```

replacing `#ffffff` with your default value

**Comment by lmartins** [comment]
It behaves the same way.

**Comment by aristath** [comment]
Can you send me a copy of your theme? It'll be easier for me to debug that way

**Comment by aristath** [comment]
Reverted the Kirki_Color class to its previous implementation.
I'll leave the new implementation for the future...

**Comment by lmartins** [comment]
Ok, pulling from dev makes things work as expected again.
If you want help testing the new class please let me know.

**Comment by aristath** [comment]
:+1: thanks, I'll definitely take you up on that when the time is right.
