### ISSUE TITLE
New Field request - Links Color

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#750]
I know you have lot of work now with new version. It is not totally important but I am missing one field.

Customizer is not ideal for lot of options I am missing something like this: https://docs.reduxframework.com/core/fields/link-color/ (sorry for the link to redux). This field is perfect for links and buttons, save lot of space in customizer and it is user friendly.

**Comment by aristath** [comment]
@x-bull Redux is on the dashboard and they have a lot of space to build their fields... 
How exactly would this work in the customizer?
I mean visually, the only way I can see this working in such a limited width is if the color fields are verically aligned, one on top of the other.
But if we place them like that, it's pretty much the same thing as adding them separately.
I don't know if you understand my dilemma... I wouldn't mind adding a field like that, but it would have to be reaaally well-built visually!
Any ideas?

**Comment by aristath** [comment]
We now have a multicolor control you can use for that.

Example:

``` php
Kirki::add_field( 'my_config', array(
    'type'        => 'multicolor',
    'settings'    => 'my_setting',
    'label'       => esc_attr__( 'Label', 'my_textdomain' ),
    'section'     => 'color',
    'priority'    => 10,
    'choices'     => array(
        'link'    => esc_attr__( 'Color', 'my_textdomain' ),
        'hover'   => esc_attr__( 'Hover', 'my_textdomain' ),
        'active'  => esc_attr__( 'Active', 'my_textdomain' ),
    ),
    'default'     => array(
        'link'    => '#0088cc',
        'hover'   => '#00aaff',
        'active'  => '#00ffff',
    ),
) );
```

And to get the colors and use them:

``` php
$my_setting_value = get_theme_mod( 'my_setting' );
$link_color   = $my_setting['link'];
$hover_color  = $my_setting['hover'];
$active_color = $my_setting['active'];
```
