### ISSUE TITLE
Section under Panel and Controls under corresponding Section doesn't expand in Firefox

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#752]
Hi @aristath, 
### Issue description:

> > I have attached a screenshot for better explanation. This issue seems to happen only in Firefox browser. When expanding panel, the list of section doesn't expand and corresponding section. It is fine with Section without panel. Can you please have a look.
> > ![customizer](https://cloud.githubusercontent.com/assets/16412478/13915771/c2f0b67c-ef7e-11e5-9136-c9bfe6047eb7.jpg)
### Version used:

> > Kirki 2.2.4
> > Firefox 45.0.1
### Code to reproduce the issue (config + field(s))

> > function configuration_sample_styling( $config ) {

```
$config['logo_image']   = get_template_directory_uri() . '/images/logo.png';
$config['description']  = __( 'The theme description.', 'kirki');
$config['color_accent'] = '#FD6F79';
$config['color_back']   = '#EFEFEF';
$config['width']        = '20%';

return $config;
```

}
add_filter( 'kirki/config', 'configuration_sample_styling' );

Thanks
##

**Comment by aristath** [comment]
I'm afraid that's a Firefox rendering issue...
All the CSS is correct, all the JS is correct... and if you try to inspect the elements for example you'll see that it jumps to its proper position.
If you don't need to change the width of the panel, I would advise you to simply remove that line from your config until we figure out how to fix this using a JS hack of some sort.

**Comment by manandharsudin** [comment]
Thanks, ll do that.
