### ISSUE TITLE
Typography Control Not Outputting

### ISSUE THREAD

**Issue by regan008** [themeum/kirki#754]
### Issue description:

I'm attempting to use the typography control and it doesn't seem to be outputting the css in the development branch. (I downloaded it this morning). It generates the google url but not the css code. Am I missing something? Do I need to include anything other than the option code (see below)?

Thanks so much, I hope this isn't a redundant question. I feel like I'm missing something super simple but I can't seem to pinpoint it.
### Version used:

The development branch as of 10am (est) this morning.
### Using theme_mods or options?

options
### Code to reproduce the issue (config + field(s))

```
  Kirki::add_panel( 'typography', array(
      'priority'    => 10,
      'title'       => __( 'Typography', 'theme_slug' ),
      'description' => __( 'This panel will provide all the options of the header.', 'theme_slug' ),
  ) );  
Kirki::add_section( 'fontcontrol', array(
      'title'          => __( 'font control' ),
      'description'
         => __( 'Edit the content and appearance of the fourth block on the homepage.' ),
      'panel'          => 'typography', // Not typically needed.
      'priority'       => 160,
      'capability'     => 'edit_theme_options',
      'theme_supports' => '', // Rarely needed.
  ) );
  Kirki::add_field( 'my_config', array(
    'type'        => 'typography',
    'settings'    => 'my_setting',
    'label'       => esc_attr__( 'Control Label', 'kirki' ),
    'section'     => 'fontcontrol',
    'default'     => array(
        'font-family'    => 'Roboto',
        'variant'        => '400',
        'font-size'      => '14px',
        'line-height'    => '1.5',
        'letter-spacing' => '0',
        'color'          => '#333333',
    ),
    'priority'    => 10,
    'output'      => array(
        array(
            'element' => 'body, h1',
        ),
    ),
) );
```

**Comment by aristath** [comment]
Hey there!

I believe what you're missing is the 1st step: Adding your configuration.
See, in this line:

``` php
Kirki::add_field( 'my_config', array(
```

You're telling the plugin to add a field using the `my_config` configuration, but you don't have that defined anywhere.

If you simply add this, it will work fine:

``` php
Kirki::add_config( 'my_config', array(
    'option_type' => 'theme_mod',
) );
```

More details can be found on https://kirki.org/docs/getting-started/config.html
Though if this is a project you're working on, I would advise you to change `my_config` to something more unique (lowercase and underscores only) and keep it consistent everywhere.
Whatever you use for the `Kirki::add_config()` will also have to be used in the `Kirki::add_field()` calls to ensure consistency.

Let me know if that works for you!

**Comment by regan008** [comment]
Ah, yes that did work. Thanks so much, I knew it had to be something very simple!
