### ISSUE TITLE
Update docs proposal: load Kirki only in the Customizer

### ISSUE THREAD

**Issue by jubstuff** [themeum/kirki#758]
Hello,

First of all, thank you for this great plugin, it has saved us a lot of hours of development.

I was reading the [documentation about embedding Kirki in the theme](https://kirki.org/docs/advanced/integration.html#embedding). 

Quoting:

> Include the main plugin file in your theme's functions.php file:
> `include_once( dirname( __FILE__ ) . '/includes/kirki/kirki.php' );`

Using this snippet, Kirki is loaded on every request. 

Maybe I'm wrong and I'm not considering all the cases: would the following work better?

```
if( is_customize_preview() ) {
  include_once( dirname( __FILE__ ) . '/includes/kirki/kirki.php' );
}
```

This would load Kirki only in the Customizer, where is needed.

**Comment by jubstuff** [comment]
Replying to my own issue, it wouldn't load any configuration if loaded this way.

So it wouldn't work.

**Comment by aristath** [comment]
@JustB also google fonts and any styles generated by Kirki would also not be loaded on the site ;)
Loading it everywhere is the safest bet.
You could do this however:

``` php
global $wp_customize;
if ( $wp_customize || ! is_admin() ) {
    include_once( dirname( __FILE__ ) . '/includes/kirki/kirki.php' );
}
```

This way it won't be loaded in other admin pages, though it wouldn't make any difference 'cause everything is loaded using actions & filters that don't apply to the admin pages anyway. :+1:
