### ISSUE TITLE
How to add sanitize_callback for the text field for valid URL in repeater field?

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#760]
Hi @aristath 
### Issue description:

Is there any way to add sanitize_callback for the repeater field for valid URL. I've copied the code below that I'm using. Can you please explain, how to add sanitize_callback for valid URL to label Link. 
### Version used:

> > 2.2.5
### Using theme_mods or options?

> > theme_mods 
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_field( 'my_config', array(
        'type'        => 'repeater',
        'settings'    => 'slider_slides',
        'label'       => __( 'Add Slides', 'my_textdomain' ),
        'section'     => 'slider_contents',
        'default'     => '',
        'fields'     => array(
            'thumbnail' => array(
                'type'  => 'image', 
                'label' => __( 'Add Image', 'my_textdomain' ),                
            ),
            'title'     => array(
                'type'  => 'text',
                'label' => __( 'Title', 'my_textdomain' ),
            ),
            'link'     => array(
                'type'  => 'text',
                'label' => __( 'Link', 'my_textdomain' ),
            )
        ),
        'choices' => array(
            'limit' => 5
        ),
    ) );
```

Thanks
##

**Comment by aristath** [comment]
Repeater fields require custom sanitization functions if you want to use URLs etc.
You will have to add a custom function like this one:

``` php
function my_repeater_sanitize( $value ) {

    $sanitized_value = array();
    // Make sure the value is an array.
    // If it's not, then return an empty array
    if ( ! is_array( $value ) ) {
        return array();
    }

    // start going through all our rows
    foreach ( $value as $key => $subvalue ) {
        $sanitized_value[ $key ] = $subvalue;
        // check that link is defined.
        // If it is, escape it.
        if ( isset( $sanitized_value[ $key ]['link'] ) ) {
            $sanitized_value[ $key ]['link'] = esc_url_raw( $sanitized_value[ $key ]['link'] );
        }
    }

    return $sanitized_value;

}
```

then in your field add the above function using the [`sanitize_callback`](https://kirki.org/docs/arguments/sanitize_callback.html) argument.

**Comment by manandharsudin** [comment]
Thanks @aristath

**Comment by manandharsudin** [comment]
Hi @aristath 

It's not working. Can you please look at what I'm doing wrong.
First, I added your sanitize function and added the sanitize_callback like this

Kirki::add_field( 'my_config', array(
        'type'        => 'repeater',
        'settings'    => 'slider_slides',
        'label'       => __( 'Add Slides', 'my_textdomain' ),
        'section'     => 'slider_contents',
        'default'     => '',
        'sanitize_callback' => 'my_repeater_sanitize',
        'fields'     => array(
            'thumbnail' => array(
                'type'  => 'image', 
                'label' => __( 'Add Image', 'my_textdomain' ),  
            ),
            'title'     => array(
                'type'  => 'text',
                'label' => __( 'Title', 'my_textdomain' ),
            ),
            'link'     => array(
                'type'  => 'text',
                'label' => __( 'Link', 'my_textdomain' ),
            )
        ),
        'choices' => array(
            'limit' => 5
        ),
    ) );

The blank array is saving. Then I added the sanitize callback to link field like this, the value is not sanitized.

 'link'     => array(
                'type'  => 'text',
                'label' => __( 'Link', 'my_textdomain' ),
                'sanitize_callback' => 'my_repeater_sanitize',
            )

Can you please point me, what I'm doing wrong?

Thanks

**Comment by aristath** [comment]
`sanitize_callback` should not be in the `link` field, it should be in the `repeater` field.
When the options are saved, the value of `link` is sanitized using [`esc_url_raw`](https://codex.wordpress.org/Function_Reference/esc_url_raw)

The function I posted was just to show the principle of how you should write the sanitization callback function for repeaters, that's why I used `esc_url_raw` for the `link` field.

**Comment by manandharsudin** [comment]
Hi @aristath 

Do I need to sanitize all the fields besides links in repeater to work, because this code is not working and its saving blank array.

```
function my_repeater_sanitize( $value ) {

    $sanitized_value = array();
    // Make sure the value is an array.
    // If it's not, then return an empty array
    if ( ! is_array( $value ) ) {
        return array();
    }

    // start going through all our rows
    foreach ( $value as $key => $subvalue ) {
        $sanitized_value[ $key ] = $subvalue;
        // check that link is defined.
        // If it is, escape it.
        if ( isset( $sanitized_value[ $key ]['link'] ) ) {
            $sanitized_value[ $key ]['link'] = esc_url_raw( $sanitized_value[ $key ]['link'] );
        }
    }

    return $sanitized_value;

}
```

Thanks

**Comment by manandharsudin** [comment]
HI @aristath 

Can you take a look at this issue please, since you have reopened it.

Thanks

**Comment by ghost** [comment]
I have this problem too, so I ended up by hooking to [sanitize_option_theme_mods_$theme](https://themeshaper.com/2013/04/29/validation-sanitization-in-customizer/) and didnt use `sanitize_callback` inside the repeater field.

Example code:

``` php
function theme_prefix_sanitize_customizer( $value ) {

    if ( !is_array( $value ) ) {
        $value = array();
    }

    foreach ( $value['slider_slides'] as $key => $subvalue ) {

        if ( isset( $value['slider_slides'][ $key ]['link'] ) ) {
            $value['slider_slides'][ $key ]['link'] = esc_url_raw( $value['slider_slides'][ $key ]['link'] );
        }

    }

    return $value;

}
add_action( 'sanitize_option_theme_mods_theme_name', 'theme_prefix_sanitize_customizer' );

```

**Comment by manandharsudin** [comment]
Thanks @AyoThemes  it worked.

**Comment by allysonsouza** [comment]
I had a problem to display shortcodes from text field, so I used [html_entity_decode](http://php.net/manual/pt_BR/function.html-entity-decode.php):

```
<?php 
$contact_form = get_theme_mod( 'contact-form' );
echo do_shortcode( html_entity_decode( $contact_form ) );
?>
```
