### ISSUE TITLE
Adding new control : category list

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#764]
### Issue description:

can you please help me to add this control like page-dropdown 
or 
can you please tell me where i can find page-dropdown codes in kirki ?

Thanks 
### Version used:

2.2.5

**Comment by aristath** [comment]
add a `select` control, and in the `choices` argument use `Kirki_Helper::get_terms( 'category' )`

**Comment by Imonthemes** [comment]
thank you so much 

there is any Helper call post like category ?

**Comment by aristath** [comment]
You can take a look at these to do what you need: https://github.com/aristath/kirki/blob/2.2.5/includes/class-kirki-helper.php#L108-L171

**Comment by Imonthemes** [comment]
Hi,
thank you i was find it but the problem is my coding knowledge :-1: 

```
Kirki::add_field( 'safreen', array(
    'type'        => 'select',
    'settings'    => 'category_show',
    'label'       => __( 'This is the label', 'safreen' ),
    'section'     => 'layout_front_page',
    'default'     => 'option-1',
    'priority'    => 10,
    'multiple'    => 0,
    'choices'     => Kirki_Helper::get_terms( 'category' )
) );
```

what i am put instead of category ?

**Comment by aristath** [comment]
Added documentation on https://kirki.org/docs/advanced/helper-methods.html
