### ISSUE TITLE
Need to select Image twice to upload image in Image Field. Same issue in Image repeater field as well.

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#767]
Hi @aristath 
### Issue description:

The issue is we can't choose and upload image in single select. The first time when we choose images and choose select button nothing happens. We have to choose again and click on choose image button then only image get selected. Can you please look at this.

![image field 1](https://cloud.githubusercontent.com/assets/16412478/14038855/21d39504-f27e-11e5-9738-157820efcf78.jpg)
![image field 2](https://cloud.githubusercontent.com/assets/16412478/14038859/26e165d0-f27e-11e5-8012-3cbf02608192.jpg)
![image field 3](https://cloud.githubusercontent.com/assets/16412478/14038860/2883fc22-f27e-11e5-9af9-fe71637e5321.jpg)
### Version used:

2.2.5
### Using theme_mods or options?

theme_mods 
### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'my_config', array(
        'label'     => __( 'Background Image', 'my_textdomain' ),
        'help'      => __( 'Upload your own custom background image or pattern.', 'my_textdomain' ),
        'section'   => 'styling_settings',
        'settings'  => 'bg_image',
        'type'      => 'image',
        'default'   => '',
        'required'  => array(
            array(
                'setting'  => 'body_bg',
                'operator' => '==',
                'value'    => 'image',
            )
        )
    ) );

Thanks

**Comment by aristath** [comment]
I'm afraid that's not from Kirki, it's a standard WordPress Core media field and we have no control over it.
Kirki doesn't even include a control for these, we access the control that WP Core already has.
