### ISSUE TITLE
German translation files

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [themeum/kirki#774]
Hi aristath,
I thought you´d maybe interested in german translation files..

[languages.zip](https://github.com/aristath/kirki/files/190519/languages.zip)

**Comment by aristath** [comment]
Hey there!

Translations for Kirki are handled via the WordPress translation system and we are no longer allowed/advised to bundle language files in plugins, so if you want you can translate Kirki directly from https://translate.wordpress.org/projects/wp-plugins/kirki/stable/de/default

This way it will be available to everyone... :+1:
