### ISSUE TITLE
Background control is missing some helpful labeling.

### ISSUE THREAD

**Issue by briancwelch** [themeum/kirki#78]
Reference:
![capture](https://cloud.githubusercontent.com/assets/3002855/6642097/823230b6-c978-11e4-87fe-2d85cbf8a49c.PNG)

**Comment by aristath** [comment]
I believe this was fixed on https://github.com/aristath/kirki/commit/4df7ccea221b2e9e372e9883d0c3dd06a4816a22

Let me know if you're still having an issue!
