### ISSUE TITLE
Question: `output` and `js_vars` for a complex CSS property value

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#781]
This is not an issue or feature request. I just want to know if the following is possible using Kirki :)

I'm using an effect which requires the following CSS on an anchor tag:

``` css
background-color: #222;
box-shadow: 10px 0 0 #222, -10px 0 0 #222;
color: #fff;
```

I have added fields for color and background color using Kirki. There is no `box-shadow-color` property in CSS. So right now, I'm using `js_vars` and `output` only for `color` and `backgorund-color`. For box-shadow, I have added my custom `<style>` in `<head>` using `do_action` on `wp_head`.

Is it possible to use `output` and `js_vars` for such `box-shadow` using Kirki? If it is not possible, I don't thing we need this in Kirki's core because these type of requirements rarely come into light :)

**Comment by aristath** [comment]
In the field:

``` php
'output' => array(
    array(
        'element'  => '#my-div',
        'property' => 'background-color',
    ),
    array(
        'element'           => '#my-div',
        'property'          => 'box-shadow',
        'sanitize_callback' => 'my_box_shadow',
    ),
),
```

Sanitize_callback:

``` php
function my_box_shadow( $value ) {
    return '10px 0 0 ' . $value . ', -10px 0 0 ' $value;
}
```

I also just pushed another commit in the develop branch that should allow you to do it like this:

``` php
'output' => array(
    array(
        'element'  => '#my-div',
        'property' => 'background-color',
    ),
    array(
        'element'           => '#my-div',
        'property'          => 'box-shadow',
        'sanitize_callback' => '10px 0 0 $, -10px 0 0 $',
    ),
),
```

But I'm not so sure I'll keep it that way. It's not a sanitize_callback, so I'm considering what the best name for that would be. `value_replace`? `value_pattern`? `value_something`

Opinion?

**Comment by rahulv3a** [comment]
`value_pattern`  makes sense.

As always, thank you for a prompt solution.

**Comment by aristath** [comment]
I agree, `value_pattern` makes sense.
OK, pushed. You can start using it now if you want from the develop branch and it will be included in the next stable release. :+1:

**Comment by rahulv3a** [comment]
I just tried it, `value_pattern` works with `output`.

If you could also add it to `js_vars`, it would perfect. :)

**Comment by aristath** [comment]
Implemented for js_vars too, and confirmed that it also works using `'postMessage' => 'auto'`.

**Comment by rahulv3a** [comment]
It doesn't seem to be working for me.

I'm using I'm using [dc9bf08](https://github.com/aristath/kirki/commit/dc9bf083b464f02dab8462cd415547853a2468da) and here's my test code

``` php
Kirki::add_config( 'config_1', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );

Kirki::add_panel( 'panel_1', array(
  'title' => esc_html__( 'Panel 1', 'test' ),
) );

Kirki::add_section( 'section_1', array(
  'title' => esc_html__( 'Section 1', 'test' ),
  'panel' => 'panel_1',
) );

Kirki::add_field( 'config_1', array(
  'settings'  => 'field_1',
  'section'   => 'section_1',
  'label'     => esc_html__( 'Field 1', 'test' ),
  'type'      => 'color',
  'default'   => '#fff',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => '.test a',
      'property' => 'color',
    ),
  ),
) );

Kirki::add_field( 'config_1', array(
  'settings'  => 'field_2',
  'section'   => 'section_1',
  'label'     => esc_html__( 'Field 2', 'test' ),
  'type'      => 'color',
  'default'   => '#222',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'       => ".test a",
      'property'      => 'background-color',
    ),
    array(
      'element'       => '.test a',
      'property'      => 'box-shadow',
      'value_pattern' => '10px 0 0 $, -10px 0 0 $',
    ),
  ),
) );
```

It is updates only background color in my case. However, output works fine.

**Comment by aristath** [comment]
I believe this was just fixed...
In JavaScript the `.replace()` function replaces only the 1st occurence instead of all of them, and in your value_pattern you were using 2.
In my initial tests I was using a slider with `'value_pattern' => 'calc(2em - $)` which is why it looked like it was working fine :+1:

**Comment by rahulv3a** [comment]
Something isn't still quite right. It doesn't work when the field value is changed for the first time. If the value is changed again it works like it should.

Please use the following code to test. I have used `'transport' => 'postMessage'` with `'function' => 'style'` intead of `'transport' => 'auto'`, just to remove a layer of complexity.

``` php
Kirki::add_config( 'config_1', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );

Kirki::add_panel( 'panel_1', array(
  'title' => esc_html__( 'Panel 1', 'test' ),
) );

Kirki::add_section( 'section_1', array(
  'panel' => 'panel_1',
  'title' => esc_html__( 'Section 1', 'test' ),
) );

Kirki::add_field( 'config_1', array(
  'settings'  => 'field_1',
  'section'   => 'section_1',
  'label'     => esc_html__( 'Field 2', 'test' ),
  'type'      => 'color',
  'default'   => '#eeee22',
  'output'    => array(
    array(
      'element'       => ".test a",
      'property'      => 'background-color',
    ),
    array(
      'element'       => '.test a',
      'property'      => 'box-shadow',
      'value_pattern' => '10px 0 0 $, -10px 0 0 $',
    ),
  ),
  'transport' => 'postMessage',
  'js_vars'   => array(
    array(
      'function' => 'style',
      'element'  => ".test a",
      'property' => 'background-color',
    ),
    array(
      'function'      => 'style',
      'element'       => '.test a',
      'property'      => 'box-shadow',
      'value_pattern' => '10px 0 0 $, -10px 0 0 $',
    ),
  ),
) );
```

When I change the value for the first time, Chrome's code inspector shows the following:
![untitled-2](https://cloud.githubusercontent.com/assets/3503359/14104644/d1234214-f5c3-11e5-877d-5deff302016a.jpg)

**Comment by aristath** [comment]
OK, I believe this was the final fix. :+1:
