### ISSUE TITLE
Background image outputs CSS even if its empty

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#783]
### Issue description:

CSS output for background image is `background-image:url("")` if no image is selected. It should not output anything in that case.

Not a biggie. Just wanted to report this.
### Version used:

Latest develop branch as of now [ebcd06f](https://github.com/aristath/kirki/commit/ebcd06f48203af1ebed21e13785bfd4be0f51cfe) 
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_config( 'config', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );

Kirki::add_panel( 'test_panel', array(
  'title' => esc_html__( 'Test Panel', 'test' ),
) );

Kirki::add_section( 'test_section', array(
  'title' => esc_html__( 'Test Section', 'test' ),
  'panel' => 'test_panel',
) );

Kirki::add_field( 'config', array(
  'settings' => 'test_field',
  'type'     => 'image',
  'label'    => esc_html__( 'Test field', 'test' ),
  'section'  => 'test_section',
  'output'   => array(
    array(
      'element'  => '.test',
      'property' => 'background-image',
    ),
  ),
) );
```

**Comment by rahulv3a** [comment]
It still outputs `background-image:`, property with an empty value.

**Comment by aristath** [comment]
All empty values are now skipped.

**Comment by rahulv3a** [comment]
Thank you for fixing it :)

**Comment by iliman** [comment]
I have this issue in 2.3.1. Output is "background-image:;"
