### ISSUE TITLE
Checkbox default value

### ISSUE THREAD

**Issue by Ontegor** [themeum/kirki#785]
### Issue description:

Checkbox is checked ( if default value == false )
### Version used:

2.2.5
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_config( 'pt_theme', array(
        'capability'    => 'edit_theme_options',
        'option_type'   => 'theme_mod',
) );
Kirki::add_field( 'pt_theme', array(
        'type'        => 'checkbox',
        'settings'    => 'pt_footer_custom',
        'label'       => __( 'Custom footer', 'PT_TEMPLATE_LANG' ),
        'section'     => 'footer_general',
        'default'     => false,
) );
```

**Comment by aristath** [comment]
Try using `'0'` instead (formatted as a string).
I just updated the docs on https://kirki.org/docs/controls/checkbox.html#field-arguments too to include that

**Comment by Ontegor** [comment]
Hi, aristath!

Thanks for your reply.

I installed develop version.
My code

```
Kirki::add_field( 'pt_theme', array(
        'type'        => 'checkbox',
        'settings'    => 'pt_footer_custom',
        'label'       => __( 'Custom footer', 'PT_TEMPLATE_LANG' ),
        'section'     => 'footer_general',
        'default'     => '1',
) );
```

Now checkbox is not checked...
