### ISSUE TITLE
Problem with Embedding in theme

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#786]
### Issue description:

Hi @aristath  i have a problem when try embedding your plugin in my theme. All path file is wrong.

My URL is simil this: 
http://localhost/wedding/wp-content/themes/italian-wedding-dayC:Program%20Files%20(x86)Amppswwwweddingwp-contentthemesitalian-wedding-daykirki/assets/css/customizer.css

With my old version of Kirki 2.1.0.1 i not have this problem. 

![senza-titolo-1](https://cloud.githubusercontent.com/assets/7602983/14093319/4c2a93c6-f54d-11e5-91af-c379281fc8bc.jpg)

Thank you very much,
Davide
### Version used:

2.2.6
### Using theme_mods or options?

theme_mods 
### Code to reproduce the issue (config + field(s))

``` php
<?php
include_once( dirname( __FILE__ ) . '/kirki/kirki.php' );
if ( ! function_exists( 'my_theme_kirki_update_url' ) ) {
    function my_theme_kirki_update_url( $config ) {
        $config['url_path'] = get_template_directory_uri() . '/kirki/';
        return $config;
    }
}
add_filter( 'kirki/config', 'my_theme_kirki_update_url' );
?>
```

**Comment by aristath** [comment]
did you try simply removing that function from your theme?

**Comment by aristath** [comment]
try this instead:
```php
$config['url_path'] = wp_normalize_path( get_template_directory_uri() . '/kirki' );
```

**Comment by aristath** [comment]
Can you please try this using the latest develop branch?
I believe this was just fixed in https://github.com/aristath/kirki/commit/8e666574b48a38611d98794f6378c2d562eb8948 but I'd appreciate a confirmation

**Comment by sododesign** [comment]
Yes, now work perfect. Thank you very much :)

**Comment by aristath** [comment]
:+1: I'm glad I could help!
This will be included in the next release in a few days
