### ISSUE TITLE
How to change the label of "Add new row" text on repeater fields

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#787]
Hi @aristath 
### Issue description:

I've added  'button_label'=> __( 'Add New Slides', 'my_textdomain' ), in repeater field to change the label of add new row button but it didn't work. Could you please take a look at this.
### Version used:

2.2.6
### Using theme_mods or options?

theme_mods 
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'my_config', array(
        'type'        => 'repeater',
        'settings'    => 'slider_slides',
        'label'       => __( 'Add Slides', 'my_textdomain' ),
        'section'     => 'slider_contents',
        'button_label'=> __( 'Add New Slides', 'my_textdomain' ),
        'default'     => '',
        'fields'     => array(
            'thumbnail' => array(
                'type'  => 'image', 
                'label' => __( 'Add Image', 'my_textdomain' ),                
            ),
            'title'     => array(
                'type'  => 'text',
                'label' => __( 'Title', 'my_textdomain' ),
            ),
            'link'     => array(
                'type'  => 'text',
                'label' => __( 'Link', 'my_textdomain' ),

            )
        ),
        'choices' => array(
            'limit' => 5
        ),    
    ) );
```

Thanks

**Comment by aristath** [comment]
See https://github.com/aristath/kirki/issues/762#issuecomment-200918005

**Comment by Vishal-Deshpande** [comment]
Nope the above does not work. Here is the [working solution](https://github.com/aristath/kirki/issues/762#issuecomment-231277973)

**Comment by aristath** [comment]
If someone can spare a few minutes to update the docs on https://kirki.org/docs/controls/repeater.html that would be great...
Sorry I'm not doing it myself, time is a luxury right now. 😞
