### ISSUE TITLE
multicolor: a field that allows selecting multiple colors

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#789]
I'm a premium WordPress theme author. I usually need to add a lot of fields for colors and typography for each section of the theme. `typography` solved one of my major by merging fields for all font related properties into a single compound field. I was looking for something similar for colors in Kirki's new documentation but sadly we don't seem to have anything like that as yet.

When I was still browsing through the documentation, I stumbled upon `palette` field. An idea shoots through my mind. How about adding a new field that based on `palette` that allows users to select the color of the palette.

Right now even for a simple button we usually need to add 6 `color` fields.
![colors-current](https://cloud.githubusercontent.com/assets/3503359/14105392/ef761d36-f5c8-11e5-8328-947fc1f26e02.jpg)

I imagine the new field to be similar to the current `palette` field, except it would not have multiple palettes.
![multi-colors](https://cloud.githubusercontent.com/assets/3503359/14105393/ef7af3d8-f5c8-11e5-8cbf-b9611b7bb6c2.jpg)

On hover, it could reveal label/purpose for that color.
![multi-colors-hover](https://cloud.githubusercontent.com/assets/3503359/14105792/54695cba-f5cb-11e5-839f-f99a035e5b72.jpg)

On click, it could open the usual color picker.
![multi-colors-expanded](https://cloud.githubusercontent.com/assets/3503359/14105794/5ae40a0e-f5cb-11e5-9257-30d566a4983d.jpg)

I would like to clear that, I'm not suggesting to replacing the current `palette` field because I assume many of us are using it. I'm suggesting to add a whole new field that borrows UI of the `palette` field. Maybe we could call this `multi-color`?

What do you think?

**Comment by rahulv3a** [comment]
This would also help with #750

**Comment by aristath** [comment]
I actually started working on something similar a few days ago... still buggy which is why nothing has been committed yet, but yes once done it will have lots of applications :+1:

**Comment by aristath** [comment]
Control created.
Usage:

``` php
Kirki::add_field( 'config', array(
    'settings'  => 'lalalala',
    'section'   => 'my_section',
    'label'     => esc_html__( 'MultiColor field', 'my_textdomain' ),
    'type'      => 'multicolor',
    'transport' => 'auto',
    'default'   => array( '#ffffff', '#000000', ),
    'choices'   => array(
        'colors' => 2,
        'labels' => array(
            esc_attr__( 'Start', 'my_textdomain' ),
            esc_attr__( 'End', 'my_textdomain' ),
        ),
    ),
) );
```

Styling is not good yet, and of course don't expect things like `output`, `js_vars` etc to work.
This is just a basic implementation (which admittedly was not that easy) so we may explore how to handle its presentation.
PHP & JS are done, now all that remains is the CSS. :+1:

**Comment by aristath** [comment]
You may also be interested to know that we have a `color-palette` control (implemented and working 100%, just still undocumented).
Give this a try while you're at it:

``` php
Kirki::add_field( 'kirki_demo', array(
    'type'        => 'color-palette',
    'settings'    => 'color_palette_demo',
    'label'       => esc_attr__( 'Color Control', 'kirki' ),
    'section'     => 'color',
    'default'     => '#81d742',
    'priority'    => 10,
    'choices' => array(
        'colors' => Kirki_Helper::get_material_design_colors(),
        // 'size'   => 25,
    ),
    'output'      => array(
        array(
            'element'  => 'a',
            'property' => 'color',
        ),
    ),
    'transport'   => 'auto',
) );
```

The `Kirki_Helper::get_material_design_colors()` method used in the `choices['colors']` argument returns an array of material colors.

Usage for that method:

``` php
// primary colors
Kirki_Helper::get_material_design_colors( 'primary' );
// or
Kirki_Helper::get_material_design_colors();
// all colors
Kirki_Helper::get_material_design_colors( 'all' );
// all reds
Kirki_Helper::get_material_design_colors( 'red' );
// all "100" colors
Kirki_Helper::get_material_design_colors( '100' );
```

You can see the palette on http://www.materialui.co/colors
you can use in its argument horizontal labels (50/100/200/.../A700) or vertical labels (red/pink/purple/.../blue-grey) or `all` to get all colors, or `primary` to get all primary colors + white/black.

Of course you can add a custom array of colors too, using the material-design colors is just a personal favorite so I added those shortcuts. 

oh, and you can also change the size of these colors... (see commented-out line). Pretty useful if you're using many colors there.

**Comment by rahulv3a** [comment]
I think we need an associative array to save colors. This would enable us to reference any particular color selected in a multi-color and use it our theme.

How about creating the field like this:

##### Type A

``` PHP
Kirki::add_field( 'config_test', array(
  'settings' => 'field_color',
  'section'  => 'section_test',
  'label'    => esc_html__( 'Color', 'test' ),
  'type'     => 'multicolor',
  'default'  => array(
    'text'       => '#222',
    'background' => '#fff',
    'border'     => '#222',
  ),
  'choices'      => array(
    'text'       => esc_html__( 'Text', 'test' ),
    'background' => esc_html__( 'Background', 'test' ),
    'border'     => esc_html__( 'Border', 'test' ),
  ),
) );
```

The above is simple and easy to understand. But on the other hand we need to repeat array keys two times. This inscreases chances of mistakes if keys are mismatched. Plus, I'm not a big fan of repeating myself in code.

##### Type B

``` php
Kirki::add_field( 'config_test', array(
  'settings' => 'field_color',
  'section'  => 'section_test',
  'label'    => esc_html__( 'Color', 'test' ),
  'type'     => 'multicolor',
  'choices'  => array(
    'text' => array(
      'default' => '#222',
      'label'   => esc_html__( 'Text', 'test' ),
    ),
    'background' => array(
      'default' => '#fff',
      'label'   => esc_html__( 'Background', 'test' ),
    ),
    'border' => array(
      'default' => '#222',
      'label'   => esc_html__( 'Border', 'test' ),
    ),
  ),
) );
```

Chances of mistakes in the above code are less. But I feel it may seem a bit complicated to some. Also, if `default` is not explicitly defined, it should be an autometic associate array created by using the multi-dimentional array in `choices` like the following:

``` php
'text'       => '#222',
'background' => '#fff',
'border'     => '#222',
```

This means more challanges, complications and time for you with this field :P

##### Type C

``` php
Kirki::add_field( 'config_test', array(
  'settings' => 'field_color',
  'section'  => 'section_test',
  'label'    => esc_html__( 'Color', 'test' ),
  'type'     => 'multicolor',
  'choices'  => array(
    'text'       => array( '#222', esc_html__( 'Text', 'test' ) ),
    'background' => array( '#fff', esc_html__( 'Background', 'test' ) ),
    'border'     => array( '#222', esc_html__( 'Border', 'test' ) ),
  ),
) );
```

This is where **Type A** meets **Type B**. The only difference between this one and **Type B** is that the 2nd level of array in `choices` is not an associative array. This one is easier to write and understand like **Type A**. But the challanges for you would be the same as **Type B**.

**Comment by aristath** [comment]
went with A.
default values belong in the `default` argument, not in `choices`.

**Comment by aristath** [comment]
Field ready (except for output/js_vars. Not sure if it can be implemented for this particular field...)
Example:

``` php
Kirki::add_field( 'my_config', array(
    'type'        => 'multicolor',
    'settings'    => 'my_setting',
    'label'       => esc_attr__( 'Label', 'my_textdomain' ),
    'section'     => 'color',
    'priority'    => 10,
    'choices'     => array(
        'link'    => esc_attr__( 'Color', 'my_textdomain' ),
        'hover'   => esc_attr__( 'Hover', 'my_textdomain' ),
        'active'  => esc_attr__( 'Active', 'my_textdomain' ),
    ),
    'default'     => array(
        'link'    => '#0088cc',
        'hover'   => '#00aaff',
        'active'  => '#00ffff',
    ),
) );
```

And to get the colors and use them:

``` php
$my_setting_value = get_theme_mod( 'my_setting' );
$link_color   = $my_setting['link'];
$hover_color  = $my_setting['hover'];
$active_color = $my_setting['active'];
```

**Comment by rahulv3a** [comment]
@aristath Shall I open a new issue for each bug I find in the `multicolor` field or comment in this thread? How do you prefer it?

**Comment by rahulv3a** [comment]
Regarding the output/ja_vars for these type of fields, I have absolutely no idea about how `output` works in kirki. So I'm gonna throw any wild idea that comes to mind to implement these. Maybe they spark an actual that works :wink:

I think we need to provide an associate array in `output` as well in order to accomplish it as following:

``` PHP
Kirki::add_field( 'config_1', array(
  'settings'  => 'field_1',
  'section'   => 'section_1',
  'label'     => esc_html__( 'Field 2', 'test' ),
  'type'      => 'multicolor',
  'default'   => array(
    'link'   => '#0088cc',
    'hover'  => '#00aaff',
    'active' => '#00ffff',
  ),
  'choices'   => array(
    'link'   => esc_attr__( 'Color', 'my_textdomain' ),
    'hover'  => esc_attr__( 'Hover', 'my_textdomain' ),
    'active' => esc_attr__( 'Active', 'my_textdomain' ),
  ),
  'transport' => 'auto',
  'output'    => array(
    'link' => array(
      'element'  => ".test a",
      'property' => 'color',
    ),
    'hover' => array(
      'element'  => ".test a:hover",
      'property' => 'background-color',
    ),
    'active' => array(
      'element'  => ".test a:active",
      'property' => 'border-color',
    ),
  ),
) );
```

Let's assume that `kirki_output()` is the function that outputs CSS

Then in Kirki core, we need to add a new function called `kirki_output_wrapper()` that acts as a wrapper for `kirki_output()`. So everything calls `kirki_output_wrapper()` instead of `kirki_output()`.

`kirki_output_wrapper()` could perform a check for depth of the array provided in `output` (with simple function as [here](http://stackoverflow.com/questions/262891/is-there-a-way-to-find-out-how-deep-a-php-array-is)).

``` PHP
function kirki_output_wrapper( array $output_input ) {
  $output_depth = array_depth( $output_input )

  if( $output_depth == 3 ) :
  foreach( $output_input as $output_element ) {
      kirki_output( $output_element );
    }
  else :
    kirki_output( $output_input );
  endif;
}
```

Or we chould check if the field is `multicolor`, if it's possible.

``` PHP
function kirki_output_wrapper( array $output_input ) {
  $current_field = current_kirki_field( $output_input );

  if( $current_field == 'multicolor' ) :
  foreach( $output_input as $output_element ) {
      kirki_output( $output_element );
    }
  else :
    kirki_output( $output_input );
  endif;
}
```

**Comment by aristath** [comment]
I'm not worried about how I'm going to write the function to handle those... that's actually the easy part.
The hard part is figuring out the syntax that will be used in the output argument.
Something like this would probably work:

``` php
'output'    => array(
    'link' => array(
        array(
            'element'  => ".test a",
            'property' => 'color',
        ),
        array(
            'element'  => ".test2 a",
            'property' => 'color',
        ),
    ),
    'hover' => array(
        array(
            'element'  => ".test a:hover",
            'property' => 'background-color',
        ),
        array(
            'element'  => ".test2 a:hover",
            'property' => 'background-color',
        ),
    'active' => array(
        array(
            'element'  => ".test a:active",
            'property' => 'border-color',
        ),
        array(
            'element'  => ".test2 a:active",
            'property' => 'border-color',
        ),
    ),
),
```

However, that's just too long... writing a custom function to take care of the CSS would be preferable if it were not for js_vars and we were only talking about CSS.

But I don't like the above for one simple reason: It's just not the same as other fields. Using 1 syntax for all fields and then another syntax for a specific field-type seems just wrong.
I'll probably do it though 'cause the benefits outweigh my personal feelings.

> Shall I open a new issue for each bug I find in the multicolor field or comment in this thread? How do you prefer it?

New issue please
