### ISSUE TITLE
Write a converter for Redux

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#8]
When redux is detected, add an admin panel with Kirki's options

**Comment by shaneholloman** [comment]
nice Ari...

**Comment by aristath** [comment]
We now have an API that allows this to work: https://gist.github.com/aristath/6d91f49357dc7546433f

**Comment by Basilakis** [comment]
Hey @aristath sorry fro popping in here.
If I enable Kirki - and have the Redux configuration ( without enabling redux ) Kirki will detect fields automatic and convert?

Thank you very much and again, sorry for hijacking.

**Comment by aristath** [comment]
@Basilakis hey there!

No, unfortunately this was never properly implemented and was abandoned.
Writing a converter though should be fairly easy... I've done it for a couple of premium themes and works fine, but it's better if it's implemented on a per-use-case basis.
