### ISSUE TITLE
Generic family is empty in Typography's CSS

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#804]
### Issue description:

Generic family (serif, sans-serif, monospace, etc) is empty in the CSS output of `typography` field.

``` CSS
font-family:"Open Sans", ;
```

This is causing to Google Fonts to not work at all. 
### Version used:

Latest develop branch, [d2c63b8](https://github.com/aristath/kirki/commit/d2c63b8e89f032609f90f7197d43bdbc6f2234b3)
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_config( 'my_config', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );
```

``` php
Kirki::add_field( 'my_config', array(
  'settings' => 'my_typography',
  'section'  => 'my_section',
  'label'    => esc_html__( 'Typography', 'example' ),
  'type'     => 'typography',
  'default'  => array(
    'font-family'    => 'Open Sans',
    'variant'        => 'regular',
    'subset'         => array( 'latin-ext' ),
    'font-size'      => '11px',
    'letter-spacing' => '0',
    'text-transform' => 'uppercase',
  ),
  'output'   => array(
    array(
      'element'  => '.my-element',
    ),
  ),
) );
```

**Comment by fovoc** [comment]
Hey there,

could you please try re-pulling from the develop branch to test if this continues? I believe that was from a typo that was reverted.

Thanks,
Dimitris

**Comment by rahulv3a** [comment]
Just tired the latest commit. Now it works :+1: 

Thank you for fixing it quickly :)
