### ISSUE TITLE
Something going wrong with typography..

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [themeum/kirki#811]
### Issue description:

Well, somehow Google Web Inspector shows that fonts cannot be loaded. This still worked just like some days ago. No changes on the config made.

![kirki-font](https://cloud.githubusercontent.com/assets/5886977/14206161/6c2ef5b0-f811-11e5-9a8e-ee811c2fe327.jpg)
### Version used:

Version 2.2.6 from Wordpress, integrated as plugin. 
### Using theme_mods or options?

theme_mods.
### Code to reproduce the issue (config + field(s))

```
Kirki::add_config( 'understrap', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
) );
```

Kirki::add_field( 'understrap', array(
        'type'        => 'typography',
        'settings'    => 'base_typography_config',
        'label'       => esc_attr__( 'Base Typography', 'understrap' ),
        'description' => esc_attr__( 'Configures the overall Font for the whole Site.', 'understrap' ),
        'section'     => 'typography',
        'default'     => array(
            'font-family'    => 'Open Sans',
            'variant'        => 'regular',
            'font-size'      => '16px',
            'line-height'    => '1.5',
            'letter-spacing' => '-0.004',
        ),
        'priority'    => 10,
        'output'      => array(
            array(
                'element' => 'body',
            ),
        ),
    ) );

Kirki::add_field( 'understrap', array(
        'type'        => 'typography',
        'settings'    => 'headline_typography_config',
        'label'       => esc_attr__( 'Headline Typography', 'understrap' ),
        'description' => esc_attr__( 'Configures Headline Fonts for the Site.', 'understrap' ),
        'section'     => 'typography',
        'default'     => array(
            'font-family'    => 'Titillium Web',
            'variant'        => 'bold',
            'letter-spacing' => '0.125',
        ),
        'priority'    => 20,
        'output'      => array(
            array(
                'element' => 'h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6',
            ),
        ),
    ) );

Any clues?

**Comment by aristath** [comment]
Chrome uses the `ERR_BLOCKED_BY_CLIENT` error when an extension installed on your browser blocks the URL you're trying to get.
Perhaps a super-aggressive adblocker?

**Comment by Thomas-A-Reinert** [comment]
Uh, thx for the insight. That´s still super-odd though, cos I really didn´t consciously activate any new browser-plugin and it worked some days ago. 

But yes, it works like a charm in firefox and doesn´t throw up any console errors too.

Sorry for bugging you and thanks (again) for the help!
