### ISSUE TITLE
Server Requirements for Kirki

### ISSUE THREAD

**Issue by dillonbailey** [themeum/kirki#814]
### Issue description:

When working with the [LetsBlog](http://themeforest.net/item/lets-blog-responsive-blog-wordpress-theme/12340419) theme on local environment, kirki-style.css writes as styles are changed in customizer. When working on the server, the stylesheet is not written.
### Version used:

Stable tag: 0.8.2
### Using theme_mods or options?

n/a
### Code to reproduce the issue (config + field(s))

n/a

We would chase this up with the theme authors, but as it's working on local environment but not our production server we feel it's probably more likely an issue with Kirki itself?

We've checked error/server logs to look for any conflicts when Kirki attempts to write to write a new stylesheet, nothing is apparent. We've tried opening up the file permissions to 777, no luck.

We've tried allowing and disallowing file mods without any luck.

<img width="1008" alt="front-end" src="https://cloud.githubusercontent.com/assets/1067872/14229987/fd9c8e4e-f989-11e5-803d-9cfc1c1bdc03.png">
<img width="1075" alt="editing" src="https://cloud.githubusercontent.com/assets/1067872/14229988/fd9cce0e-f989-11e5-93cd-34a8b5492a14.png">
##

**Comment by aristath** [comment]
Hey there!

Kirki does not write anything to your filesystem.
Is your theme perhaps using a compiler of some sort?

**Comment by dillonbailey** [comment]
Ok, interesting!

The reported behaviour on local development is that a file "kirki-style.css" is updated each time the theme customiser options are changed with the updated styles. 

It does appear composer (php) is being used by the theme developer, but no front end compilers. 

What else can I provide that may be helpful?

**Comment by aristath** [comment]
can you please send me a copy of your theme?

**Comment by dillonbailey** [comment]
I've just sent you an email with the theme zip!

Thanks again!

DB

**Comment by aristath** [comment]
The version of the theme you sent me is 1.1.7. From what I can see on the theme's page they are currently on version 1.2
Perhaps this has already been fixed in a more recent version of the theme?

The Kirki version included in there is 0.8.4 and the theme author has modified the `enqueue_styles` method (you can see the original one here: https://github.com/aristath/kirki/blob/0.8.4/includes/Styles/Frontend.php#L16-L18 to look like this:

``` php
    public function enqueue_styles() {

        // Early exit if we're not using output
        if ( ! $this->uses_output() ) {
            return;
        }

        if(is_writable(get_template_directory() . '/modules/kirki/assets/css/kirki-styles.css'))
        {
            //Writing into file instead
            global $wp_filesystem;
            $wp_filesystem->put_contents(
              get_template_directory() . '/modules/kirki/assets/css/kirki-styles.css',
              $this->styles_parse(),
              FS_CHMOD_FILE
            );
        }
        else
        {
            wp_add_inline_style( Kirki::config()->getOrThrow( 'stylesheet_id' ), $this->styles_parse() );
        }

    }
```

You can simply revert the changes to that file and make it the way it originally was:

``` php
    function enqueue_styles() {
        wp_add_inline_style( Kirki::config()->getOrThrow( 'stylesheet_id' ), $this->styles_parse() );
    }
```

I would strongly advise you to contact the theme author though and inform them about this... checking with `is_writable()` is not enough for the `$wp_filesystem`.

I guess something like this would be better and would work:

``` php
    public function enqueue_styles() {

        // Early exit if we're not using output
        if ( ! $this->uses_output() ) {
            return;
        }

        global $wp_filesystem;
        // Instantiate the Wordpress filesystem.
        if ( empty( $wp_filesystem ) ) {
            require_once( ABSPATH . '/wp-admin/includes/file.php' );
            WP_Filesystem();
        }

        $path   = wp_normalize_path( get_template_directory() . '/modules/kirki/assets/css/kirki-styles.css');
        $styles = $this->styles_parse()

        if ( is_writable( $path ) ) {
            // Try writing to the file
            if ( ! $wp_filesystem->put_contents( $path, $styles, FS_CHMOD_FILE ) ) {
                // write failed, add inline.
                wp_add_inline_style( Kirki::config()->getOrThrow( 'stylesheet_id' ), $this->styles_parse() );
            }
        }
    }
```

Please note I did not test the above function, but it _should_ work a lot better than the existing one.

**Comment by Vishal-Deshpande** [comment]
@aristath could have just said that its not kirki issue and closed the ticket. But the amount of time and effort  he has put in investigating and explaining the issue for which he is not going to receive any monetary return is really amazing. I always wonder how some guys in open source community are so passionate about their work and travel that extra mile easily while the  premium theme and plugin authors struggle to do it. @aristath and for open source community  +1

**Comment by dillonbailey** [comment]
@aristath the solution of reverting the module to the original intended design as per https://github.com/aristath/kirki/blob/0.8.4/includes/Styles/Frontend.php#L16-L18 fixed it without any stress.

Thank you sincerely for your help, this saved me big time!

**Comment by aristath** [comment]
@PlayerThemes @dillonbailey always a pleasure to help!
