### ISSUE TITLE
Announcement: Changes in 0.7

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#82]
Version 0.7 changed some things so this is the quickest way to document these changes in case someone looks them up.
## Changes in the naming of field arguments:
- `setting` is now `settings`
- `description` is now `help`.
- `subtitle` is now `description`.

These 2 changed because WP Core introduced descriptions in its core... and what WordPress calls "description" was called "subtitle" in Kirki, while "description" in Kirki was something completely different. The new syntax helps us be inline with the way WordPress Core calls things.
## Changes in the background control

On the background controls we can now disable part of the controls simply by removing values from the defaults (for example the repeat control can be removed by not including a default for that).  
IF for some reason you see that part of your controls disappeared (for example the background image control) then please make sure you're defining default values for them, even if they are empty.
## Control types instead of modes.

we no longer have "modes" for our controls. Everything is separate. In previous versions, buttonsets and radio-images were pare of the radio control and we defined them by using `'type' => 'radio', 'mode' => 'buttonset'`  
Now, this has become `'type' => 'radio-buttonset'

Of course all of those changes are backwards-compatible so your old syntax will still work. :)

**Comment by vpratfr** [comment]
Maybe that kind of announcement should get in your WIKI rather than cluttering the issues board?

**Comment by vpratfr** [comment]
See: https://github.com/aristath/kirki/wiki/Breaking-changes

**Comment by aristath** [comment]
Hah!
Nice... tbh I just didn't think of it.

Thanks for the wiki page!
