### ISSUE TITLE
number controller min is undefined

### ISSUE THREAD

**Issue by guillaumemolter** [themeum/kirki#822]
### Issue description:

I'm getting this error:
![screen shot 2016-04-05 at 10 14 28](https://cloud.githubusercontent.com/assets/1478527/14286109/f4a77f86-fb1b-11e5-9995-355101910859.png)
![screen shot 2016-04-05 at 10 14 19](https://cloud.githubusercontent.com/assets/1478527/14286108/f49f51bc-fb1b-11e5-9860-f2d8ada28770.png)

Further digging shows that control.params.choices is actually undefined.
### Version used:

2.6 and 2.7
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

I'm not using any number control and I didn't find any other number in other customizer panel. I'm only adding one section, with 1 repeater field containing 3 text fields and an image field.

This was not appearing on my local dev env, as well as not appearing on a empty test website in the production env.

Adding an if statement around the issue solve the error but I'm not sure what are the repercutions:

```
        if ( control.params.choices ) {

            // set minimum value
            if ( control.params.choices.min ) {
                jQuery( element ).spinner( 'option', 'min', control.params.choices.min );
            }

            // Set maximum value
            if ( control.params.choices.max ) {
                jQuery( element ).spinner( 'option', 'max', control.params.choices.max );
            }

            // Set steps
            if ( control.params.choices.step ) {
                if ( 'any' === control.params.choices.step ) {
                    jQuery( element ).spinner( 'option', 'step', '0.001' );
                } else {
                    jQuery( element ).spinner( 'option', 'step', control.params.choices.step );
                }
            }

        }
```

Any idea?!?

**Comment by guillaumemolter** [comment]
I created a PR with my fix...feel free to close it if it's not relevant

**Comment by aristath** [comment]
Good catch...
I'm checking if `min`, `max` & `step` are all defined before adding the options now.
Adding one without the other is meaningless anyway :+1:
