### ISSUE TITLE
Repeater field is not working on v2.2.8

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#830]
### Issue description:

After updating to v2.2.8 the repeater field doesn't seem to work. The saved values don't show on the field, when click "add new row" the Customizer page reloads.
### Version used:

2.2.8
### Using theme_mods or options?

the issue occurs on both modes.
### Code to reproduce the issue (config + field(s))

add a new repeater field and try.

**Comment by guillaumemolter** [comment]
Are you using the WordPress plugin or Kirki as a library? Do you have WP_DEBUG and SRIPT_DEBUG set to true?

@aristath I notice since this morning that Wordpress is trying to load : \/wp-content/plugins/kirki/assets/js/controls/repeater.js but the control folder is not included in the plugin

**Comment by guillaumemolter** [comment]
Found it!

**Comment by aristath** [comment]
2.2.9 is going live in a few minutes containing this bugfix

@guillaumemolter 2.2.9 contains just your commits btw... :+1:

**Comment by daviedR** [comment]
Hi guys,

After updating to 2.2.9 or even 2.2.10, the repeater fields still doesn't work.

I have a repeater fields with default values. On the Customizer, the fields doesn't show the default values, just blank. I tried to click the "Add New Row" button but it reloads the page. I inspected the console and found these errors:

http://pasteboard.co/1wzTYhH.png

**Comment by daviedR** [comment]
I would create a separate issue for this.

**Comment by guillaumemolter** [comment]
@daviedR this is definitely related to #847
