### ISSUE TITLE
Assign control values to specific posts

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#84]
Is there a way to setup controls so that they can have values associated with specific posts?
Let's say I need to add a control to set the page layout, and that each post/page could have a different setting. Currently im doing this with custom fields but would really if we could do this right in the customiser.
Thanks.

**Comment by aristath** [comment]
You could try appending the current post ID to the control ID...
So for example something like this should work:

``` php
function my_custom_setting( $controls ) {
    global $post;
    if ( isset( $post->ID ) ) {
        $controls[] = array(
            'type'     => 'text',
            'setting'  => 'my_setting_' . $post->ID,
            'label'    => __( 'My custom control', 'translation_domain' ),
            'section'  => 'my_section',
            'default'  => 'some-default-value',
            'priority' => 1,
        );
    }

    return $controls;
}
add_filter( 'kirki/controls', 'my_custom_setting' );
```

Please note though that I haven't tested it... The concept just seems solid. :)

**Comment by lmartins** [comment]
Oh, nice, but wouldn't that become inefficient along the way?
I mean I this assumption, probably wrong, that a large number of theme options will cause the queries to slowdown.

**Comment by aristath** [comment]
I guess it depends on the number of posts you will be customizing...
The setting will only be saved in the db if you change it for a specific post. So it won't matter if you have 1000 posts on your site.
The setting for the custom layout will be saved on a per-post basis, only for posts that you actually customize.
The rest of them will inherit the default layout that you're using.

Yeah, it's not the most efficient way to do it and performance-wise it would be preferable to use custom fields. On the other hand the settings are basically nothing more but an array that gets serialized when saved in the db, and theme_mods that Kirki uses are one of the first things that get loaded when your site loads.
If you don't plan to have thousands upon thousands of posts with a custom layout defined then it shouldn't be an issue!

**Comment by lmartins** [comment]
Thanks again Aristeides, im going with this approach :+1:

**Comment by lmartins** [comment]
After a few atempts I think this will not work as the customiser loads in the homepage context and doesn't seem to be updating at each page load. Going to study this further and post here if I find a solution.
