### ISSUE TITLE
Updating to version 2.2.8 and 2.2.9 breaks everything

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#840]
Hello, @aristath 

I'm having a problem when upgrading to version 2.2.8 or 2.2.9. Since, there was a issue #820 with multi select in 2.2.7 I am trying to upgrade to latest version. But when I upgraded to 2.2.9 the fields that I have added using Kirki doesn't work. 

The Multi select field looks like this
![multiselect](https://cloud.githubusercontent.com/assets/16412478/14342974/921be00c-fcbd-11e5-97c9-270068651e70.png)

And the Color field has changed to text field like this
![color](https://cloud.githubusercontent.com/assets/16412478/14342988/a3d53ce4-fcbd-11e5-8b37-afeed149e776.png)

Also there are no option to select in typography field
![typography](https://cloud.githubusercontent.com/assets/16412478/14343001/b19d19c8-fcbd-11e5-96e8-91953e728b34.png)

And all the fields doesn't trigger save and publish button. So I've reverted back to ver 2.2.6, in which there aren't above mentioned issues. Can you please have a look.

Cheers

**Comment by iliman** [comment]
@manandharsudin, are you using a method integrating the Kirki into the theme?
I have the same problems with this method. If use integrating Kirki as a plugin, all works well.

Also I tryed to use the my_theme_kirki_update_url() function to fix it, but it didn't help.

Part of customizer.php:

``` php
/**
 * Include Kirki Toolkit.
 */
include_once( dirname( __FILE__ ) . '/kirki/kirki.php' );

/**
 * Kirki configuration
 */
Kirki::add_config( 'my_theme', array(
    'option_type' => 'theme_mod',
    'capability'  => 'edit_theme_options',
) );

if ( ! function_exists( 'my_theme_kirki_update_url' ) ) {
    function my_theme_kirki_update_url( $config ) {
        $config['url_path'] = get_stylesheet_directory_uri() . '/inc/kirki/';
        return $config;
    }
}
add_filter( 'kirki/config', 'my_theme_kirki_update_url' );
```

File structure:

```
theme/style.css
theme/inc/customizer.php
theme/inc/kirki/
```

**Comment by manandharsudin** [comment]
@iliman Yes you're right. I'm using Kirki embedding in my theme. As you have said, I've checked using Kirki as a Plugin and it works. Maybe @aristath can shed some light on this.

**Comment by rahulv3a** [comment]
I'm experiencing the exact same issue.

**Comment by aristath** [comment]
Fixed.
2.2.10 will be online on w.org in a couple of minutes

**Comment by rahulv3a** [comment]
@aristath, I have just tried v2.2.10. If Kirki is included in the theme, it still break most of the fields.

v2.2.7 works fine.
