### ISSUE TITLE
Default unit of Letter Spacing in Typography field

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#842]
### Issue description:

Default unit of Letter Spacing in `typography` field is always `px`.

Its worth noting that CSS output always uses the correct unit. So its the field in customizer that displays units incorrectly. However, after save Customzier always displays the correct unit.
- `'letter-spacing' => '1'` is displayed as `1px`.
- `'letter-spacing' => '1px'` is displayed as `1pxpx`.
- `'letter-spacing' => '1em'` is displayed as `1empx`.
- Interestingly, `'letter-spacing' => '0.5em'` is displayed correctly as `0.5em`.
### Version used:

v2.2.7
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` PHP
Kirki::add_config( 'my_config', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );
```

``` PHP
Kirki::add_field( 'my_config', array(
  'settings' => 'my_typography',
  'section'  => 'my_section',
  'label'    => esc_html__( 'Typography', 'example' ),
  'type'     => 'typography',
  'default'  => array(
    'font-family'    => 'Open Sans',
    'variant'        => 'regular',
    'subset'         => array( 'latin-ext' ),
    'font-size'      => '16px',
    'letter-spacing' => '1px', // or 1em
    'text-transform' => 'uppercase',
  ),
  'output'   => array(
    array(
      'element'  => '.my-element',
    ),
  ),
) );
```

**Comment by aristath** [comment]
WTH... this makes absolutely no sense at all!
The code used to sanitize the value for letter-spacing looks like this:

``` php
$value['letter-spacing'] = Kirki_Sanitize_Values::css_dimension( $value['letter-spacing'] );
if ( $value['letter-spacing'] == Kirki_Sanitize_Values::filter_number( $value['letter-spacing'] ) ) {
    $value['letter-spacing'] .= 'px';
}
```

So first it sanitizes the value and we get a valid CSS value
Then, it checks if the numeric value is the same as the returned value from the CSS-dimensions sanitization.
If it is the same, then that means there is no unit included and it's simply a numeric value.
In that case, it adds the `px` suffix.

I'm confused...

**Comment by aristath** [comment]
re-reading your original post and trying to understand.

> Its worth noting that CSS output always uses the correct unit.

ok, so my previous comment is invalid.
Since CSS is properly displayed, the sanitization works fine.

> So its the field in customizer that displays units incorrectly. However, after save Customzier always displays the correct unit.

I was able to replicate the issue, but still can't understand why it happens.
`<# console.log( data.default ); #>` inside the control shows `1px` but `<# console.log( data.value ); #>` shows `1pxpx`

**Comment by rahulv3a** [comment]
If it helps, all default units (`px`, `em`, `rem` and `%`) are displayed correctly in `font-size` and `line-height` fields. So it's just `letter-spacing` that displays an extra `px` in the end.

**Comment by aristath** [comment]
I think this last commit should fix this.
Can you please check?

**Comment by aristath** [comment]
@carasmo can you please also test if the latest `develop` branch fixes this for you? Thanks!

**Comment by carasmo** [comment]
It works great! Thank you so much.

**Comment by aristath** [comment]
awesome, thanks for checking!

**Comment by rahulv3a** [comment]
Now the`typography` field is perfect. Thank you for fixing this :+1:
