### ISSUE TITLE
Repeater Image Field Bug in ver 2.2.10

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#849]
Hello @aristath 

After updating to ver 2.2.10 the image repeater field is saving object array instead of image id.
![repeater image bug](https://cloud.githubusercontent.com/assets/16412478/14378383/57e2bd48-fd94-11e5-8544-bbb3af11c92a.png)

Here, is the steps how it occurred.
1. First you choose image and the image id is being saved.
2. Now you logout from WP and re-login and navigate to customizer. Here if you have var-dump the field array you'll see that the image-id is change to object array.
3. You don't see image in customizer preview but frontend. And if you make some change on other field and save it. Now the object array is saved in place of image id.
Somehow in customizer preview the value of image id is being replaced by object array. Could you please look into this.

Thanks

**Comment by guillaumemolter** [comment]
@manandharsudin sorry about that! I'll look into this today and have a patch ready for @aristath tonight.

**Comment by guillaumemolter** [comment]
@manandharsudin I think I have a working patch.
