### ISSUE TITLE
Any plans for filtering Google fonts made available?

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#85]
The complete Google fonts catalogue can be a bit overwhelming, not to mention the atrocities some users will make given that possibility. Is there a way, or any plans for adding filtering capability of the available fonts?

**Comment by aristath** [comment]
That would require you to add a multicheck control for font types (serif, sans-serif, display, handwriting, monospace), and then 3 more slider controls for thickness, slant & width.
Then, we'd have to load the filtered list of fonts in a 4th select control etc...

It's possible.... but instead of 1 control we'd then have 5 and a lot of extra functionality that is not really necessary...

Instead, you can simply add a description to the field that will instruct users to visit http://www.google.com/fonts/ in order to preview and select the font they want. :)

**Comment by lmartins** [comment]
I see your point, although im not sure if I explained my self clearly.
The ideia was to just output the font list available to user, not make that list dependable on multiple factors such as types and weights.

That is, imagine that for body copy I say the theme supports "Lato", "Open Sans" and "Merryweather". Then only those would be listed.

Maybe im being too strict about what to allow users, anyway I feel this could be useful.

**Comment by aristath** [comment]
Oh!

Sorry, I misunderstood what you meant!

Yeah, you can do that already.....
Right now to add all fonts you do this:

``` php
    $controls[] = array(
        'type'     => 'select',
        'setting'  => 'base_typography_font_family',
        'label'    => __( 'Font Family', 'minishop' ),
        'section'  => 'base_typography',
        'default'  => 'Roboto',
        'priority' => 20,
        'choices'  => Kirki_Fonts::get_font_choices(),
        'output' => array(
            'element'  => 'body',
            'property' => 'font-family',
        ),
    );
```

if you want to add specific fonts, you could simply define a custom array:

``` php
    $controls[] = array(
        'type'     => 'select',
        'setting'  => 'base_typography_font_family',
        'label'    => __( 'Font Family', 'minishop' ),
        'section'  => 'base_typography',
        'default'  => 'Roboto',
        'priority' => 20,
        'choices'  => array(
            'Lato'          => 'Lato'
            'League Script' => 'League Script'
            'Leckerli One'  => 'Leckerli One'
            'Ledger'        => 'Ledger'
        ),
        'output' => array(
            'element'  => 'body',
            'property' => 'font-family',
        ),
    );
```

You can see the full list of fonts here: https://gist.github.com/aristath/1f01fa624bede53464a9 (I just did `print_r( Kirki_Fonts::get_font_choices() );` to get those :wink: )

**Comment by lmartins** [comment]
Ohh nice!!! Kirki just keeps getting better and better :D
