### ISSUE TITLE
In version 2.2.10 the customizer is fully broken

### ISSUE THREAD

**Issue by vladcosorg** [themeum/kirki#857]
![selection_003](https://cloud.githubusercontent.com/assets/467230/14390564/69cb47e2-fdc0-11e5-87a2-df90d2f03947.png)

Using theme_mods only
Enabled as plugin

Downgrading to 2.2.9 solves the problem

**Comment by vladcosorg** [comment]
Related or dupe of #847 ?

**Comment by guillaumemolter** [comment]
@chetzof yes duplicate of #847
