### ISSUE TITLE
Custom Iris Palette works everywhere but the Kirki Customizer

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#863]
### Issue description:

The default Iris palette has crayon colors. I added the following to my functions.php file and in widgets and elsewhere in the theme this replaces the default colors, but I can't figure out anything to make it work in Kirki. I looked everywhere in the docs and this repo and can't find how to do this.

```
jQuery(function($) {
    if (typeof $.wp !== 'undefined' && typeof $.wp.wpColorPicker !== 'undefined') {
        $.wp.wpColorPicker.prototype.options = {
            // add your custom colors here
            palettes: [
                '#556270',
                '#4ecdc4',
                '#c7f464',
                '#ff6b6b',
                '#c44d58',
                '#ecca2e',
                '#bada55'
            ]
        };
    }
});
```

```
/**
 * Custom Iris Palette (??? works everywhere but Kirki powered customizer)
 */
function sidewave_admin_scripts() {

    wp_register_script( 'custom-iris-palette', CHILD_URL . '/assets/js/palettes.js', null, true );

    wp_enqueue_script( 'custom-iris-palette' );

}
add_action('admin_enqueue_scripts', 'sidewave_admin_scripts');

```
### Version used:

2.10.0
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

See above.

**Comment by aristath** [comment]
Hey there!

In Kirki you can simply pass the Iris options as parameters in the field's `choices` argument.
So to add your palette you can simply add this to your field:

``` php
'choices' => array{
    'palettes' => array(
        '#556270',
        '#4ecdc4',
        '#c7f464',
        '#ff6b6b',
        '#c44d58',
        '#ecca2e',
        '#bada55',
    ),
),
```
