### ISSUE TITLE
spacing field ignores transport => auto

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#871]
### Issue description:

`spacing` field ignores `'transport' => 'auto'` and `'transport' => 'postMessage'`. It always refreshes the whole page. But CSS output works.
### Version used:

Latest develop branch, [155ba49](https://github.com/aristath/kirki/commit/155ba4952e8a11cd83a6fa268755e8cc319e5ae2)
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` PHP
Kirki::add_config( 'my_config', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );
```

``` PHP
Kirki::add_field( 'my_config', array(
  'settings'  => 'my_spacing',
  'section'   => 'my_section',
  'label'     => esc_html__( 'Spacing', 'example' ),
  'type'      => 'spacing',
  'default'   => array(
    'top'    => '5px',
    'right'  => '10px',
    'bottom' => '5px',
    'left'   => '10px',
  ),
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => '.test a',
      'property' => 'padding',
    ),
  ),
) );
```

**Comment by aristath** [comment]
This is proving to be more complicated that I originally though, so I'll leave it to forced refresh for now (it's a nuisance, I agree... but bugs bugs have a priority.

**Comment by rahulv3a** [comment]
This can surely wait as it doesn't break any functionality. Full page refresh is okay for the time being :+1:

**Comment by aristath** [comment]
Fixed
