### ISSUE TITLE
Spacing field causes fatal error

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#881]
### Issue description:

Just tested the new spacing field into my theme, but it causes fatal error. It seems the `validate-css-value.js` is not enqueued, while the `spacing.js` needs `kirkiValidateCSSValue` function from the `validate-css-value.js`.
### Version used:

2.3.0
### Using theme_mods or options?

tested on both modes

**Comment by aristath** [comment]
did you try the develop branch? I believe this has already been fixed, I just haven't releases 2.3.1 yet.

**Comment by aristath** [comment]
Confirmed, this has been fixed in the develop branch a couple of days ago.
Marking as a duplicate and closing.

If using the develop branch you're still having this issue please feel free to reopen this and post an update so that I may see it. :+1:
