### ISSUE TITLE
Problem with Front page displays Customizer

### ISSUE THREAD

**Issue by sododesign** [themeum/kirki#883]
### Issue description:

With the version 2.3 of Kirki the section to set the main page (CUSTOMIZER) does not work anymore. I can not set home page to the main page and post. The selectors drop down pages do not appear to be set. See screenshot
### Version used:

2.3
### Using theme_mods or options?

theme_mods

![senza-titolo-5](https://cloud.githubusercontent.com/assets/7602983/14479734/d6d28abc-0121-11e6-81f7-abd0906b54d0.jpg)

**Comment by aristath** [comment]
there was a conflict with WP Core's `dropdown-pages` control.
Renamed ours internally to `kirki-dropdown-pages` and now everything works fine. :+1: 

Thanks for reporting this!

**Comment by sododesign** [comment]
Now work perfect. Thanks @aristath :)
