### ISSUE TITLE
Transport auto not working on 'option' mode

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#884]
### Issue description:

If your config is set to `option` mode, the transport `auto` feature is not working. Tried it using the `color` field.
### Version used:

2.3.0
### Using theme_mods or options?

`option`. It works on `theme_mod` mode.

**Comment by daviedR** [comment]
I think the problem is when your `postmessage.js` trying to create the style tag.

When on `option` mode. Your localized `jsvars`'s keys has format like this: `option_name[option_key]`. This caused issue when your script trying to create the style tag:

```
jQuery( '#kirki-customizer-postmessage' + setting )
```

jQuery would accept the selector as `#kirki-customizer-postmessageoption_name[option_key]`. And you would never found that element.

Can you simply replace the brackets (`[` `]`) with dash (`-`). OR you change how you localize the settings into `jsvars`. Perhaps by striping the `option_name` and only use the `option_key`.

**Comment by aristath** [comment]
:+1: fixed.
