### ISSUE TITLE
Bug with Color Output and Required

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#886]
### Issue description:

Looks like that the `required` attribute prevents kirki from generating the relative css via the output function.

I have this field that's not working

```
Kirki::add_field( 'currl', array(
    'type'        => 'color',
    'settings'    => 'currl_bg_color',
    'section'     => $section,
    'default'     => CURRL_DEFAULT_BG_COLOR,
    'priority'    => 10,
    'transport'   => 'postMessage',
    'js_vars'   => array(
        array(
            'element'  => '.currl-background',
            'function' => 'css',
            'property' => 'background-color',
        ),
    ),
    'output' => array(
        array(
            'element'  => '.currl-background',
            'property' => 'background-color',
        ),
    ),
    'required'  => array(
        array(
            'setting'  => 'currl_bg_style',
            'operator' => '==',
            'value'    => 'color',
        ),
    ),
));
```

The live preview inside the customizer is working perfectly and the value gets stored perfectly in the db but the only way to get the correct css output is to get rid of the `required`
### Version used:

2.3.1
### Using theme_mods or options?

options

**Comment by aristath** [comment]
It's probably a pull request that got recently merged... (see https://github.com/aristath/kirki/pull/853)

I'll try to debug it later today and hopefully have a fix for this.

**Comment by aristath** [comment]
Can you please try pulling the latest develop branch and let me know if that fixes your issue?

**Comment by manuelmoreale** [comment]
@aristath nope, sadly the bug is still there.

**Comment by manuelmoreale** [comment]
After more testing I say you can close this one because it's related to the #879.
For some reason sometimes a value that is evaluated as true inside the customizer is not evaluated as true once we reach the frontend and viceversa. I think is related to the mix of boolean and string values.
I'll try to dig a bit more and see if I can spot where the problem is.
