### ISSUE TITLE
Check box default value

### ISSUE THREAD

**Issue by mohamadelmi** [themeum/kirki#887]
Hey Aristeides Stathopoulos,
### Issue description:

The default value of check box does not apply in backend.
Note: with pressing reset button this issue does not appear and it happens when new option is created by checkbox. Your support is highly appreciated in this regard.
### Version used:

2.3.0
### Using theme_mods or options?

I am using kirki-demo to examine this issue and also I use Reset WP plugin to reset the theme to run default values of customizer.
By activating the kirki-demo theme and going to Appearance> customize > checkbox controls >checkbox demo (first filed) the checkbox displays true default value correctly but if you check function.php and set default value of this element on => false , 0 or '0' as you’ll see the default value does not change and stays true.

Thanks.

**Comment by aristath** [comment]
can you please check using the develop branch?

**Comment by mohamadelmi** [comment]
Sorry for late response. The truth is I have no idea how to do it :)
One more thing, reset button does not work.

**Comment by aristath** [comment]
> The truth is I have no idea how to do it :)

You can download the under-development version from here: [https://github.com/aristath/kirki/archive/develop.zip](https://github.com/aristath/kirki/archive/develop.zip)

Let me know if it works for you there!

**Comment by mohamadelmi** [comment]
Yes, the issue has been fixed thoroughly and default value is working correctly.

Thank you so much :)

**Comment by aristath** [comment]
Great! Closing this issue.
