### ISSUE TITLE
Set inline_css to false so it outputs through Ajax

### ISSUE THREAD

**Issue by RonalddeRooij** [themeum/kirki#888]
### Issue description:

In the past I changed a certain file to accomplish my issue. The CSS generated by Kirki gets outputted in the header. However I want to output the CSS in a dynamic file.
### Version used:

2.3
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

I have found the part that I have to set inline_css to false in the config however it's not working what am I doing wrong?

I have added the following part to config.php and fields.php but neither work.

Kirki::add_config( 'caramelomedia', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
    'inline_css'    => false,
) );

Update:

I also tried the following code without succes:

function configuration_sample_styling( $config ) {
    $config['inline_css']   = false;
    return $config;
}

Extra information: I have been trying to find if some one asked this question before but I couldn't.

**Comment by aristath** [comment]
Method is currently getting rebuilt, that's why you can't find it anywhere. :)
Once I finish recoding some stuff I'll re-upload it.

**Comment by RonalddeRooij** [comment]
Thanks man, great to here! You made some awesome improvements the last versions keep up the VERY GOOD work!

**Comment by RonalddeRooij** [comment]
Thank You!!

Kind regards,

Ronald de Rooij

Op 17/04/2016 om 12:46 schreef Aristeides Stathopoulos:
