### ISSUE TITLE
Checkbox default value doesn't work properly

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#891]
### Issue description:

Hi Pal,

The checkbox control seems doesn't affect with default value, the both values '1' and '0' make checkbox checked BUT the hidden value is correct all if statements working properly.

Otherwise Switch and Toggle working good with TRUE and FALSE .. can you make checkbox default values accept TRUE and FALSE values rather than '1' and '0' ??

P.S. I test it in a fresh wordpress copy without saving.

Thanks for your support.
### Version used:

2.3
### Using theme_mods or options?

theme_mods

**Comment by Serpentsoft** [comment]
File: class-kirki-controls-checkbox-control.php

`<input type="checkbox" value="{{ data.value }}" {{{ data.link }}} <# if ( '1' == data.value ) { #> checked<# } #> />`

-- Instead Of --

`<input type="checkbox" value="{{ data.value }}" {{{ data.link }}} <# if ( data.value ) { #> checked<# } #> />`

**Comment by aristath** [comment]
fixed, can you please check using the develop branch?

**Comment by Serpentsoft** [comment]
Ok Thanks man
