### ISSUE TITLE
js_vars changing only the values of last array item

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#892]
### Issue description:

I think something really bad happened with js_vars it changes only the values of last array item, it was working good until update to version 2.3

Thanks
### Version used:

2.3
### Using theme_mods or options?

theme_mods

**Comment by aristath** [comment]
did you try the `develop` branch? I think this was fixed yesterday...

**Comment by Serpentsoft** [comment]
No i didn't .. i'll try again

**Comment by Serpentsoft** [comment]
Fixed in developer version.

**Comment by aristath** [comment]
Thanks for checking!
