### ISSUE TITLE
Bug with value_pattern in js_vars

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#896]
### Issue description:

`value_pattern` seems to have some issue when used inside js_vars where multiple elements are present in the array.

I have the following field

```
Kirki::add_field( 'currl', array(
    'settings'  => 'currl_typography_bio_size',
    'type'      => 'slider',
    'section'   => $section,
    'priority'  => 10,
    'label'     => esc_attr__('Bio Font Size', 'currl'),
    'transport' => 'postMessage',
    'default'   => 2,
    'js_vars'   => array(
        array(
            'element'  => '.currl-bio',
            'function' => 'style',
            'property' => 'font-size',
            'units'    => 'rem'
        ),
        array(
            'element'       => '.currl-text-content',
            'property'      => 'max-width',
            'function'      => 'style',
            'value_pattern' => 'calc(($rem * 40) + 10rem)'
        ),
    ),
));
```

With this configuration the value of the second element is the one expected but for the first element I get a combination of `value_pattern` and `units`.
Something like this `calc((3rem * 4o0) + 10rem)rem`

If I try to hack the problem and change the 'units' property with something like `'value_pattern' => '$rem'` this gets completely ignored and I get the result of this one `'value_pattern' => 'calc(($rem * 40) + 10rem)'` for both elements.

This only happens with `postMessage`.
Everything works fine using `auto`
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.1 (latest available in the dev branch)
### Using theme_mods or options?

options

**Comment by aristath** [comment]
I believe this last commit fixes the issue, can you please verify?

**Comment by manuelmoreale** [comment]
Working perfectly although the last commit has introduced a bug in the repeater field.
`repeater.js?ver=4.5:759 Uncaught TypeError: Cannot read property 'palettes' of undefined`
Should I open a new Issue for this one?
Let's mention @guillaumemolter since I think he's the one who's working on the repeater.

**Comment by aristath** [comment]
already fixed in https://github.com/aristath/kirki/commit/2f880082b5f636d247ab44e1752384280641e0ae :+1:

**Comment by guillaumemolter** [comment]
@aristath @manuelmoreale thank you guys.
