### ISSUE TITLE
Help texts don't display for color fields

### ISSUE THREAD

**Issue by peterhadorn** [themeum/kirki#90]
My color fields don't show the "help" texts anymore, the ? tooltip button doesn't get displayed. I think this is only since 0.7.1? "Description" texts work fine.

**Comment by aristath** [comment]
Hey there!
I believe we fixed this in the [develop](https://github.com/aristath/kirki/tree/develop) branch so I'll just go ahead and close this issue.

If it still persists when you use that branch then please comment back here and reopen this! :+1:
