### ISSUE TITLE
Customizer update sections and field in new url

### ISSUE THREAD

**Issue by PayteR** [themeum/kirki#900]
### Issue description:

Hi, i'm currious, if there is some way how can i update customizer sections "from inside of iframe".

For example, when i'm in customizer, and have some field, for example "Homepage sidebar visible" checkbox, i want to have this field just on homepage in customizer and when i click to some post in iframe, i want this field disapear, and vice versa... can i somehow achieve this? thx
### Version used:

2.3.0
### Using theme_mods or options?

no matter
### Code to reproduce the issue (config + field(s))

it's just question

**Comment by guillaumemolter** [comment]
@PayteR This is not really the right place to ask questions. This is a place to report bugs or feature requests for Kirki, websites like Stackoverflow, etc... are more appropriate for this kind of requests. 

Regarding your question, yes it is possible, look into [active callbacks](http://blog.josemcastaneda.com/2015/07/23/using-active-callbacks-in-the-customizer/)

Please close this issue! Thanks

**Comment by PayteR** [comment]
thx, i know about active callback, but they are not sufficient for me, i want to have it fully contextional, will ask somewhere else

**Comment by guillaumemolter** [comment]
@PayteR the customizer is not really aware of the context into witch it is displayed/previewing. So the current options to show/hide sections and panels are limited. You can pass custom functions to the active callback, so custom feedback is the way to go. However you are going to have a hard time figuring out the context into which you are.

**Comment by PayteR** [comment]
Discussion will continue here 

https://wordpress.org/support/topic/customizer-content-specific-controls?replies=1

or

http://stackoverflow.com/questions/36665022/wordpress-customizer-content-specific-controls
