### ISSUE TITLE
Error caused after update from ver 0.6.2 to 0.7.1

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#91]
Hi there
I updated my kirki (master branch, not wordpress plugin version!) from version 0.6.2 to 0.7.1, and now I get:

Notice: Undefined index: stylesheet_id in C:\wamp\www\wp\wp-content\themes\new\lib\kirki\includes\class-kirki-style.php on line 175

and also my panels, sections and controls don't load :(

I put var_dump($config) on line No. 174 of class-kirki-style.php (after $config = $kirki->get_config();) and it returnes:
array (size=0)
  empty

Any solutions?!

Thanks in advance

**Comment by aristath** [comment]
Hey there!

Can you please replace line 173
`$config = $kirki->get_config();`
with this:
`$config = Kirki()->get_config();`

let me know if that works!

**Comment by DevelopOnline** [comment]
I did you your recommendation, and the result is:

 Fatal error: Function name must be a string in C:\wamp\www\wp\wp-content\themes\new\lib\kirki\includes\class-kirki-style.php on line 173

Do you have other solution?

Thanks

**Comment by aristath** [comment]
Hey there!

Can you please try pulling the master branch from github and let me know if that fixes your issue?

**Comment by DevelopOnline** [comment]
Hi dear Aris
Thanks for your fast bug-fix & reply.
It works perfect now :)
