### ISSUE TITLE
Field type number : Cannot read property 'min' of undefined

### ISSUE THREAD

**Issue by shaylash** [themeum/kirki#910]
### Issue description:

Hi guys,

I added a field type number as shown in the documentation and a js error is raised by number.js
the error "Uncaught TypeError: Cannot read property 'min' of undefined number.js?ver=4.5"
 I don't get what's wrong, any idea?

doc url : https://kirki.org/docs/controls/number.html
### Version used:

I tried version 2.3.0, 2.3.1 and develop.
### Using theme_mods or options?

using theme_mods
### Code to reproduce the issue (config + field(s))

Kirki::add_field( $theme_name, array(
    'type'        => 'number',
    'settings'    => 'logo_width',
    'label'       => esc_attr__( 'Logo width in px', 'neko' ),
    'section'     => 'logo_section',
    'default'     => 42,
    'priority'    => 1
) );

**Comment by aristath** [comment]
Hey there!

The docs were missing the `choices` argument, thank you for pointing that out.
Updated https://kirki.org/docs/controls/number.html :+1:

**Comment by shaylash** [comment]
Hi aristath,

Thanks a lot for the quick reply.

**Issue description**
I have tried this also seeing this bug report https://github.com/aristath/kirki/issues/644 but adding the choices array does not fix it for me. I get the same error with number.js and min being not defined 

**Version used:**
( re tried with develop (2.3.1) and 2.3.0 )

**Code to reproduce the issue (config + field(s))**

Kirki::add_field( 'my_theme', array(
    'type'        => 'number',
    'settings'    => 'test_setting',
    'label'       => esc_attr__( 'This is a test', 'neko' ),
    'section'     => 'test_section',
    'default'     => 25,
    'priority'    => 1,
    'choices'     => array(
        'min'  => 0,
        'max'  => 30,
        'step' => 1,
    ),
) );

Kirki::add_section( 'test_section', array(
    'title'          => esc_html__( 'Test', 'neko' ),
    'description'    => '',
    'panel'          => '', // Not typically needed.
    'priority'       => 20,
    'capability'     => 'edit_theme_options',
    'theme_supports' => '' // Rarely needed.
));

Kirki::add_config( 'my_theme', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
));

error : "Uncaught TypeError: Cannot read property 'min' of undefined  number.js?ver=4.5"

Just in case the field type slider does work (which as a very similar structure)

Thanks again for this great plugin and the hard work ;) .
