### ISSUE TITLE
Field type number : Cannot read property 'min' of undefined

### ISSUE THREAD

**Issue by shaylash** [themeum/kirki#911]
### Issue description:

Thanks a lot for the quick reply.

Issue description
I have tried this also seeing this bug report #644 but adding the choices array does not fix it for me. I get the same error with number.js and min being not defined
### Version used:

develop (2.3.1), 2.3.0
### Using theme_mods or options?

theme_mods 
### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'my_theme', array(
'type' => 'number',
'settings' => 'test_setting',
'label' => esc_attr__( 'This is a test', 'neko' ),
'section' => 'test_section',
'default' => 25,
'priority' => 1,
'choices' => array(
'min' => 0,
'max' => 30,
'step' => 1,
),
) );

Kirki::add_section( 'test_section', array(
'title' => esc_html__( 'Test', 'neko' ),
'description' => '',
'panel' => '', // Not typically needed.
'priority' => 20,
'capability' => 'edit_theme_options',
'theme_supports' => '' // Rarely needed.
));

Kirki::add_config( 'my_theme', array(
'capability' => 'edit_theme_options',
'option_type' => 'theme_mod',
));

error : "Uncaught TypeError: Cannot read property 'min' of undefined number.js?ver=4.5"

Just in case the field type slider does work (which as a very similar structure)

Thanks again for this great plugin and the hard work ;) .

**Comment by aristath** [comment]
fixed

**Comment by shaylash** [comment]
Ok cool thanks. 
I found what was going on on my side.
Have a good day
