### ISSUE TITLE
custom image size for Upload or image field

### ISSUE THREAD

**Issue by thatvideowebguy** [themeum/kirki#912]
### Issue description:

Hi everyone, Is there a way to get a custom size for the output of the image field ? 

Thanks
### Using theme_mods or options?

theme_mods

**Comment by rahulv3a** [comment]
The following code should work:

``` PHP
$image_url = get_theme_mod( 'your_image_field' );
$image_id = attachment_url_to_postid( $image_url );
if( $image_id ) {
  $image_url = wp_get_attachment_image( $image_id, 'your-custom-image-size' ); 
}
```

**Comment by thatvideowebguy** [comment]
Great ! Thanks

**Comment by rahulv3a** [comment]
Please close the issue if its resolved :)
