### ISSUE TITLE
exclude and value_pattern arguments

### ISSUE THREAD

**Issue by iliman** [themeum/kirki#913]
### Issue description:

I want to use a toggle control to show or hide some element via css property `display: none;`.
The logic is simple: if the toggle is on -> show the title(disable css output), if is off -> hide(enable css output with `display: none;` property). See the code below.
### Version used:

2.3.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_config( 'my_theme123', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
) );

Kirki::add_field( 'my_theme123', array(
    'type'        => 'toggle',
    'settings'    => 'title_display123',
    'label'       => __( 'Display Site Title123', 'my_textdomain123' ),
    'section'     => 'title_tagline',
    'default'     => '1',
    'priority'    => 9,
    'output'      => array(
        array(
            'element'       => '.site-title',
            'property'      => 'display',
            'exclude'       => array( '1' ), //if toggle is on -> disable css output(show the title)
            'value_pattern' => 'none',
        ),
    ),
) );
```

But it outputs css in any case.
After some tests I found that the `exclude` argument depends on `value_pattern` argument. For example, if `'value_pattern' => 'none$'`, then we should use `'exclude' => array( 'none1' )` to work the condition.
I think that the main problem in this. But if we will use the example above without `value_pattern` argument, then with any toggle position, css will not output:

``` php
Kirki::add_config( 'my_theme123', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
) );

Kirki::add_field( 'my_theme123', array(
    'type'        => 'toggle',
    'settings'    => 'title_display123',
    'label'       => __( 'Display Site Title123', 'my_textdomain123' ),
    'section'     => 'title_tagline',
    'default'     => '1',
    'priority'    => 9,
    'output'      => array(
        array(
            'element'       => '.site-title',
            'property'      => 'display',
            'exclude'       => array( '1' ), //if toggle is on -> disable css output(show the title)
            //'value_pattern' => 'none',
        ),
    ),
) );
```

**Comment by aristath** [comment]
good catch! Marking as a bug and I'll try to fix this later today.

**Comment by aristath** [comment]
fixed.
