### ISSUE TITLE
background type doesn't work

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#915]
### Issue description:

Hi i don't know if background type still support but it doesn't output and opacity isn't show
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.1 develop branch
### Using theme_mods or options?

option
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_field( 'mik', array(
        'type'        => 'background',
        'settings'    => 'header_background',
        'label'       => __( 'Choose your header background', 'kirki' ),
        'description' => __( 'The header background you specify here will apply to the header area, including your menus and your branding.', 'kirki' ),
        'section'     => 'header_advertisement',
        'default'     => array(
            'color'    => 'rgba(255,0,255,0.3)',
            'image'    => '',
            'repeat'   => 'no-repeat',
            'size'     => 'cover',
            'attach'   => 'fixed',
            'position' => 'left-top',
            'opacity'  => 100
        ),
        'priority'    => 10,
        'output'      => 'header',
) );
```

**Comment by aristath** [comment]
The current implementation for the background field is **awful**.
There's another ticket on https://github.com/aristath/kirki/issues/741 and the background field will soon be completely rebuilt.
