### ISSUE TITLE
Toggle not working - 2.3.1

### ISSUE THREAD

**Issue by RonalddeRooij** [themeum/kirki#921]
### Issue description:

Hi, I tried to update from 2.3 to 2.3.1 however my toggle doesn't work in 2.3.1
### Version used: 2.3.1

WordPress plug-in version
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

It should output this code when I change the toggle:

<?php if (get_theme_mod('layout_fullwidth_boxed', 'off' ) == 'on') { ?> 
    <div class="boxed-layout">
<?php } ?>

My field to add the toggle

Kirki::add_field( 'caramelomedia', array(
    'type'        => 'switch',
    'settings'    => 'layout_fullwidth_boxed',
    'label'       => __( 'Boxed?', 'caramelomedia' ),
    'section'     => 'general_full_boxed',
    'default'     => 'off',
    'priority'    => 0,
    'choices'     => array(
        'off' => __( 'Uit', 'caramelomedia' ),
        'on'  => __( 'Aan', 'caramelomedia' ),
    ),
) );

This code works fine in 2.3 but it doesn't work when I use kirki 2.3.1

**Comment by aristath** [comment]
Toggles are essentially checkboxes and their values are either `0` or `1`.
`on` & `off` are not values, they are only used to set the labels.

What exactly is it that does not work? 'Cause "doesn't work" is pretty vague.

**Comment by RonalddeRooij** [comment]
Thank you, I changed  == 'on' to == '1' which fixed my issue. What I ment was that the code within the if didn't work when I toggle on/off.
