### ISSUE TITLE
Problem with new link popup in WYSIWYG Editor

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#922]
### Issue description:

There's a problem with the new modal introduced in WP 4.5.
Actually there are 2 bugs.

One is related to the z-index and is an easy fix. The modal has a z-index value of `100100` while the main div containing the content of the customizer has a z-index value of `500000`

The second bug is a bit more tricky. The popup is displayed using absolute positioning relative to the selected word in the editor and has 4 different alignments. Top and bottom are not a problem since there's always some space on top or on the bottom of the editor. Left aligned is also not a problem since on the right there's the entire screen to work with. The problem is the right aligned. Here's a screen that shows the issue:
<img width="322" alt="screenshot 2016-04-22 14 06 16" src="https://cloud.githubusercontent.com/assets/1738077/14741205/eef12296-0894-11e6-8c95-852e74b595a4.png">
As you can see the modal goes out the screen on the left side. The modal is quite wide (almost 400px) so using a wider sidebar is not a solution.
Haven't had time to look into the new link modal to see if there's a way to fix this one.

**Comment by aristath** [comment]
I hate the WYSIWYG editor...

**Comment by aristath** [comment]
Can you please try the develop branch now?
`editor` fields were completely refactored trying to resolve #140 and I think this one was also resolved with it :+1:

**Comment by aristath** [comment]
Closing this one. :)
According to the comment on https://github.com/aristath/kirki/pull/914#issuecomment-215342563 it has been resolved.
