### ISSUE TITLE
Get custom terms return an empty array

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#923]
### Issue description:

I was trying to get woocommerce terms for the `select` type but return an empty array.
Is working fine if want to get normal wp terms (category and tags).
### Version used:

2.3.1
### Using theme_mods or options?

both
### Code to reproduce the issue (config + field(s))

Custom terms always return an empty array

``` php
Kirki::add_config( 'my_settings', array(
    'capability'  => 'edit_theme_options',
    'option_type' => 'theme_mods',
) );

Kirki::add_field( 'my_settings', array(
    'type'        => 'select',
    'settings'    => 'my_setting',
    'label'       => __( 'This is the label', 'my_textdomain' ),
    'section'     => 'title_tagline',
    'default'     => '',
    'priority'    => 10,
    'choices'     => Kirki_Helper::get_terms( 'product_cat' ),
) );
```

Use normal customizer without kirki is working fine.

``` php
$wp_customize->add_setting( 'my_setting',
    array(
        'default'        => '',
        'type'           => 'theme_mod',
        'capability'     => 'edit_theme_options',
    )
);
$wp_customize->add_control( 'my_setting',
    array(
        'label'         => esc_html__('Display Layout', 'my_textdomain'),
        'section'       => 'title_tagline',
        'description'   => '',
        'type'          => 'select',
        'choices'       => Kirki_Helper::get_terms( 'product_cat' )
    )
);
```

![](https://cldup.com/tyMTkQOrp7.gif)
The first select field is using normal wp customizer
The second select field is using kirki

**Comment by aristath** [comment]
I just tested this on normal categories and it seems to be working fine there...
Can you please check if the issue is with that particular taxonomy?

**Comment by ghost** [comment]
Yes is working fine if want to get WP built-in taxonomy such as `category` and `post_tag`.

It seem almost all custom taxonomy. I have try [woocommerce](https://wordpress.org/plugins/woocommerce/), [easy-digital-downloads](https://wordpress.org/plugins/easy-digital-downloads/), [custom-content-portfolio](https://wordpress.org/plugins/custom-content-portfolio/) and also register some custom taxonomy just for testing purpose. But still return an empty array.

I rewrite some helper function with the new [get_terms](https://developer.wordpress.org/reference/functions/get_terms/) arguments and still not working too.

``` php
function prefix_get_terms( $taxonomy ){

    $term_item = array();

    $terms = get_terms( array(
        'taxonomy'      => $taxonomy,
        'hide_empty'    => false
    ) );
    foreach ( $terms as $term ) :
        $term_item[$term->term_id] = $term->name;
    endforeach;

    return $term_item;

}
```

**Comment by aristath** [comment]
The issue is that custom taxonomies are registered from WooCommerce on `init`, so when you're trying to call the `Kirki_Helper::get_terms( 'product_cat' )` method directly the taxonomies have not been registerd yet, so there's nothing to retrieve.
When using the WordPress Customizer API you're adding your controls in the `customize_register` action which is later than `init` so by that time the taxonomies are properly found.

A solution would be to add your field on `init` like this:

``` php
add_action( 'init', function() {
    Kirki::add_field( 'my_settings', array(
        'type'        => 'select',
        'settings'    => 'my_setting',
        'label'       => __( 'This is the label', 'my_textdomain' ),
        'section'     => 'title_tagline',
        'default'     => '',
        'priority'    => 10,
        'choices'     => Kirki_Helper::get_terms( 'product_cat' ),
    ) );
});
```

**Comment by ghost** [comment]
Ahhh, didn't notice that part.
Thanks a lot for your awesome work.
