### ISSUE TITLE
color picker question in repeater

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#924]
I'm trying to use repeater's color picker result with wp_add_inline_style
but since the principle of repeater is to add multiple repeatable blocks of fields i don't see how style differently this repeatable blocks of fields. For example in my repeater  i have a title field and a color picker 

``` javascript
<?php
function my_styles_method() {
    wp_enqueue_style(
        'custom-style',
        get_template_directory_uri() . '/css/custom_script.css'
    );
        $repeater_value = get_theme_mod( 'my_repeater', array() );
        $color = $repeater_value[0]['background_color'];
        $custom_css = " 
            .titlecolor{
                        background-color: {$color};
                }";
        wp_add_inline_style( 'custom-style', $custom_css );
}
add_action( 'wp_enqueue_scripts', 'my_styles_method' );
?>
```

In this example the title color of the different section will have the same color

**Comment by robbisy** [comment]
I'm new in kirki i've seen an array of arguments which says output no required  [here](https://kirki.org/docs/controls/repeater.html) does it means that output is not supported in repeater and that we had to take value with theme_mods ?

**Comment by Rayken** [comment]
You can use the array keys as unique identifiers for the rows, see: https://github.com/aristath/kirki/issues/908#issuecomment-212731813

Basically each repeater row gets its own unique index in the array returned by `get_theme_mod()` so to target one section individually you'd want to add a class or ID to that element containing the key.

**Comment by robbisy** [comment]
Thanks
