### ISSUE TITLE
Double prefix and suffix in js_vars

### ISSUE THREAD

**Issue by voidlz** [themeum/kirki#943]
### Issue description:

When I use `transport => postMessage` and `js_vars` with `function => html` and `prefix`, `suffix`
I get double output prefix and suffix
### Version used:

2.3.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field(` 'test_kirki', array(
    'settings'    => 'test',
    'label'       => __( 'label', 'boroboro' ),
    'section'     => 'test_section',
    'type'        => 'text',
    'priority'    => 1,
    'default'     => 'text',
    'transport'   => 'postMessage',
    'js_vars'     => array(
        array(
            'element'  => 'h1.test',
            'function' => 'html',
            'prefix'   => 'prefix-',
            'suffix'   => '-suffix',
        ),
    ),
) );
```

output: `prefix-prefix-text-suffix-suffix`

**Comment by aristath** [comment]
Thank you for reporting this!

Fixed.
