### ISSUE TITLE
Question: Is it possible to show a field only if values of two other fields are same?

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#945]
Is it possible to set the 'required' in such a way that it shows only if values of two other fields are same? For instance, I have 3 `select` fields, A, B, and C. I would like to show field C only if values of field A and B are same.

I tried the following:

``` PHP
'required' => array(
  array(
    'setting'  => 'field_a',
    'operator' => '==',
    'value'    => get_theme_mod( 'field_b' ),
  ),
),
```

This works but it requires Customizer to be reloaded in order to show/hide field.

Is there a better way to accomplish the same without writing custom js script?

PS: Thank you @aristath and everyone else who is contributing in Kirki. Your work makes lives of many WordPress developers so much easier :)

**Comment by aristath** [comment]
I'm afraid not...
custom-coding it would be the only solution here

**Comment by rahulv3a** [comment]
jQuery is not one my strong suits. If you could guide me through this, I would be very greateful.

I came up with the following to hide field C:

``` javascript
jQuery(document).ready(function($) {

  "use strict";

  $( '#customize-control-field_a select, #customize-control-field_b select' ).change( function() {
    if( $( '#customize-control-field_a select' ).val() == $( '#customize-control-field_b select' ).val() ) {
      $( '#customize-control-field_c' ).css( 'display', 'list-item' );
    } else {
      $( '#customize-control-field_c' ).css( 'display', 'none' );
    }
  } ).trigger( 'change' );

});
```

This works but it seems a bit funky to me. Is this a correct way of doing this?

**Comment by aristath** [comment]
It has to be done via PHP, not JS.
Take a look at Otto's post on http://ottopress.com/2015/whats-new-with-the-customizer/ in the "Fun with Active Callbacks" section.

Otto explains things better than anyone I've ever seen so that will hopefully be helpful.. 👍

**Comment by rahulv3a** [comment]
I read your conversation about with other about replacing `required` with `active_callback`. But I had no idea what `active_callback` was all about. I bookmarked that thread to google about it in my free time. In hindsight, I should have searched for it right away because it is insanely useful.

The best part is this works with sections and panels too (just tested it). I was looking this feature since quite a while. I think we can close #240 now for good. :+1: 

PS: Thank you so much for sharing the tutorial! You're fucking awesome! :100:
