### ISSUE TITLE
repeater select 

### ISSUE THREAD

**Issue by samitava** [themeum/kirki#947]
I've seen from previous question here that we can add woocommerce categories in a select type #923 
I try it with repeater

``` javascript
add_action( 'init', function() {


Kirki::add_field( 'my_config', array(
                      'type'        => 'repeater',
                     'label'       => esc_attr__( 'Repeater Control', 'textdomain' ),
                    'section'     => 'hea',
                    'priority'    => 10,
                    'settings'    => 'rep',
               /* some code*/

         'woo' => array(
                    'type'        => 'select',
                 'settings'    => 'select_woo',
            'label'       => __( 'WOOCOMMERCE', 'kirki' ),
                 'priority'    => 3,
                 'choices'     => Kirki_Helper::get_terms( 'product_cat' ),
           ),
           /* rest of the code*/
) );

});
```

it's display in the repeater but say Notice: Undefined index: woo and when i do
var_dump( get_theme_mod( 'rep' ) ); every repeater field is correctly display except this one.
Is there a way to make it work with repeater ?

**Comment by aristath** [comment]
Please post the complete code, including the `/* some code*/` and `/* rest of the code*/`.
I see no repeater in your code there....

`Can you please post something that I can just toss in a functions.php and see what you're talking about?

**Comment by samitava** [comment]
You're right the code was quiet long and i reduce it too much . Anyway i made a stupid mistake no problem with the repeater select. 
Cheers
