### ISSUE TITLE
Possible variable $l10n found in translation function

### ISSUE THREAD

**Issue by Hujjat** [themeum/kirki#949]
Hi
### Issue description:

I have included kirki in my theme. Everything is almost done. I have checked the theme using theme checker. It's giving some recommended errors. here is how it looks like

Possible variable $l10n found in translation function

`Line 446: <button type='button' class='button upload-button' data-label='<?php esc_attr_e( $l10n['add-file'] ); ?>' data-alt-label='<?php esc_attr_e( $l10n['change-file'],'upplanet' ); ?>' >`

Actually, I can solve the problem by not using variable $l10n, but I want to know, will it not break my any of the code?. If I do that, will everything work fine?

thank's :)

**Comment by aristath** [comment]
Hey there!

That was a bug, I believe this has already been fixed in the develop branch here on github.
It should be `esc_attr` instead of `esc_attr_e`

**Comment by Hujjat** [comment]
Hey bro, 
Thanks, The dev version is working perfectly, :)

**Comment by liveweb22** [comment]
Hello there. I use L10n.php for custom domain - Kirki for my theme, but i don't know how to load in theme. Can anyone help me?
