### ISSUE TITLE
Issue Kirki integration in theme

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#954]
### Issue description:

Parse Error: unexpected T_DOUBLE_ARROW
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

When i use **=>** it gives error but when i use **=** then no.

```
add_filter( 'kirki/my_config/l10n', function( $l10n ) {

    $l10n['background-color']      **=>** esc_attr__( 'Background Color', my_textdomain );
    .....
    .....
    .....

    return $l10n;

} );
```

**Comment by aristath** [comment]
That's the way arrays are defined in PHP, not an issue.
