### ISSUE TITLE
Editor field covering the content

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#955]
### Issue description:

@aristath correct me if I'm wrong but while I was testing the new editor you had already implemented something to correct the problem of the editor covering part of the content in the preview. I think was a negative margin (or something else, I don't quite remember).
Was now working on a new theme and seems the fix is no longer there and the text area covers part of the preview (in my case the footer).
### Version used:

Latest available in the dev branch

**Comment by aristath** [comment]
Nope, it wasn't implemented... I never even considered that.
Good point, marking this as a bug, hopefully I'll have a fix for this one soon.

**Comment by aristath** [comment]
fixed in the develop branch. 👍
