### ISSUE TITLE
postMessage and image field

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#957]
### Issue description:

Not sure this is technically a bug but would be useful to have the image field to output the url of the image inside the `src` attribute when the transport is set to `postMessage`
Currently is outputting something like this `<img src=''>imagePath</img>` which is not helpful 😊
### Version used:

2.3.2

**Comment by aristath** [comment]
have you tried using the `value_pattern` argument in `output`?

**Comment by manuelmoreale** [comment]
Isn't the value pattern available only with the output argument? The output itself is working fine, I'm just talking about the live preview

**Comment by aristath** [comment]
If you're currently online we can talk about this in detail on gitter... easier that way: https://gitter.im/aristath/kirki

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/kirki/commit/c505bad991dae2766a900f1ad22440fb31129a84 by adding a new `attr` argument:

``` php
Kirki::add_field( 'the', array(
    'settings'    => 'the_logo',
    'type'        => 'image',
    'section'     => $section,
    'priority'    => 50,
    'label'       => __( 'Content : Logo or Avatar', 'the' ),
    'description' => 'This image will be displayed at the top of the hidden about section on the right-hand side of the screen.',
    'tooltip'     => 'You should put a nice image of yourself or a rad logo.',
    'default'     => THE_DEFAULT_LOGO,
    'transport'   => 'postMessage',
    'js_vars'     => array(
        array(
            'element'  => '.the-logo',
            'function' => 'html',
            'attr'     => 'src',
        ),
    )
));
```

**Comment by rinkuyadav999** [comment]
Cool but it is missing in docs @ https://kirki.org/docs/arguments/js_vars.html
