### ISSUE TITLE
Version 2.3.2 use $l10n For Translation.

### ISSUE THREAD

**Issue by Hujjat** [themeum/kirki#960]
### Issue description:

I have just download the version 2.3.2 version of kikri. The previous had checkbox unchecked problem. Now check box is working but when I check my theme with theme checker, it gives the old error of $l10n variable for theme translation text. 
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
Yes I use the latest version.
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

`RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.`

thank's :)

**Comment by aristath** [comment]
👍 fixed in the latest develop branch.

**Comment by Hujjat** [comment]
Thank's hero, 
one line remaining, :)
class-kirki-controls-repeater-control.php line 411. The Text-domain for Hex Value.

**Comment by aristath** [comment]
Oops you're right... I missed that one. Fixed now 👍
