### ISSUE TITLE
Allowing callbacks in active_callback

### ISSUE THREAD

**Issue by naxvog** [themeum/kirki#961]
Hi there,
are there plans to allow for constructs like this?

```
'active_callback'=> array(
    'is_page',
    array( 
        'FooBar',
        'testmethod',
    ),
    array(
        'setting' => 'some_numeric_setting',
        'operator' => '==',
        'value' => 120,
    ),
),
```

I have a modified version running to allow for this behaviour (based on your [commit  ee89184](https://github.com/aristath/kirki/commit/ee891845e947f95219dc5bf6b1bde23d3bb481e8)) let me know if I should issue a pull request

**Comment by aristath** [comment]
That's actually a great idea... Sure, if you can submit a PR :)

**Comment by aristath** [comment]
Marked as a feature request and added to the 3.1 milestone. 👍

**Comment by LebCit** [comment]
Hello ,
I had an hour of head pain trying to do this 🤣 
Searched 5 minutes in the issues and found that a request was maid and the feature will be in 3.1
Thanks a lot for your time and your efforts 👍
