### ISSUE TITLE
Live update is not working after 2.3.2 update

### ISSUE THREAD

**Issue by webgeckos** [themeum/kirki#964]
### Issue description:

I have Kirki integrated with my theme. Everything was working fine including the live update (js_vars). I deleted the old version and I integrated the new version 2.3.2. Now the changes are being saved but there is no instant update of the changes. I noticed that in the new version the customizer.js file is missing in the assets/js/-folder but probably this file was included somewhere else. The function "html" is working, it is just the function "css" which is not working.
### Version used:

2.3.2 - develop branch from github
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

Config:
Kirki::add_config( 'miga', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'theme_mod',
) );

function miga_customizer_config() {
    $args = array(
    'url_path'     => get_stylesheet_directory_uri() . '/inc/kirki/',
    );
    return $args;
    }
add_filter( 'kirki/config', 'miga_customizer_config' );

field (just one example but it doesn't work for all of the fields with css-function):
Kirki::add_field( 'miga', array(
        'type'        => 'color-alpha',
        'settings'    => 'footer_bg_color',
        'label'       => __( 'Footer Background Color', 'miga' ),
        'section'     => 'footer-settings',
        'default'     => 'rgba(0,0,0,0.1)',
        'priority'    => 20,
        'output' => array(
            'element'  => '.footer-bg-color',
            'property' => 'background-color',
        ),
        'transport' => 'postMessage',
        'js_vars'   => array(
            array(
                'element'  => '.footer-bg-color',
                'function' => 'css',
                'property' => 'background-color',
            ),
        ),
    ) );

Thank you.

**Comment by webgeckos** [comment]
I figured out why its not working but I still don't know how to fix it. The problem is that I am using inline css in my template for the "home" page. If I remove the inline css and add the css to the wp_head the live update is working.

Unfortunately for some other reasons I _have to_ use inline css.

Is there a way to make the live update work even with inline css?

**Comment by Rayken** [comment]
Well, as I see it there are two questions in this one. Firstly, though, I believe output is meant to be an array with sets of arrays for each change you want to apply. So basically, what I mean is that this:

``` php
...
'output' => array(
    'element'   => '.footer-bg-color',
    'property'  => 'background-color',
),
...
```

should probably be:

``` php
...
'output' => array(
    array(
        'element'   => '.footer-bg-color',
        'property'  => 'background-color',      
    ),
),
...
```

Give that a whirl and see if it works. I could be wrong though and there might be logic for just having one array overall. Then there's the question about using inline css. @aristath recently added a very useful filter for such needs: 

``` php
function my_custom_styles( $css ) {
    // $css['media-query']['element']['property'] = 'value';
    $css['global']['.div1']['width'] = '30%';
    $css['@media (max-width: 600px)']['.div1']['width'] = '50%';
    $css['@media (max-width: 600px)']['.div1']['max-width'] = '300px';
    $css['global']['.div2']['width'] = '15rem';

    return $css;
}

// here's the magic
add_filter( 'kirki/{$config_id}/styles', 'my_custom_styles' );
```

This will add the styles to  `<head>` using `<style id='kirki-styles-{$config_id}-inline-css' type='text/css'> the styles </style>`.

Hope this helps! If none of the above works I'm sure someone else will might have some more insight.

**Comment by webgeckos** [comment]
Thank you Quaked for your reply.

I changed the output argument to be a set of arrays and removed the inline css from the template file. The live update woks but when I click "Save and Publish" button the changes are not being saved. 

So I have two problems: When I use the output argument without inline css the live update works but the changes are not saved. And when I use inline css in my template the live update doesn't work.

The reason why I have to use inline css is because I am using a loop for kirki sections and inside my template file. So it is easier to use inline css than applying the custom changes to the "head" using filters or similar functions.

My kirki fields inside the loop look like this:

Kirki::add_field( 'miga', array(
                'type'        => 'color-alpha',
                'settings'    => 'bg_'**.$section_nr**,
                'label'       => __( 'Section Background Color', 'miga' ),
                'section'     => $section_title,
                'output' => array(
                    array(
                        'element'  => '#section-bg-'**.$section_nr**,
                        'property' => 'background-color',
                    ),
                ),
                'transport' => 'postMessage',
                'js_vars'   => array(
                    array(
                        'element'  => '#section-bg-'**.$section_nr**,
                        'function' => 'css',
                        'property' => 'background-color',
                    ),
                ),
) );

Do you have an idea why the "output" argument is not being saved?

Thanks.

**Comment by Rayken** [comment]
As far as I know, using `output` will end up in your `<head>` with the other kirki styles. I don't see why it shouldn't be working. Have you inspected your `<head>` and checked the styles applied by Kirki? Maybe the styles are added, just not targetting the elements you were hoping for? If there isn't any output at all, no `<style>` to be found, something is wrong indeed.

If that's the case, make sure your values have been saved by fetching the corresponding setting with `get_theme_mod()` or `get_option()` if that's what you use. E.g. `get_theme_mod( 'bg_1' );` or whatever `$section_nr` might be set to. If that's empty, it's more likely the actual "field" is wrong and not the saving of it. Some debugging is needed!

**Comment by webgeckos** [comment]
On one of my other themes the following is being added to the `<head>` element and everything works fine:

`<link id="kirki-styles-css" media="all" type="text/css" href=".../inc/kirki/assets/css/kirki-styles.css" rel="stylesheet">`
`<style id="kirki-styles-inline-css" type="text/css">`...

But on my current theme there is no kirki styling added to the `<head>` element at all. And as far as I can see the only difference between these themes is the version of kirki.

I also get a strange Firebug error: "NetworkError: A network error occurred". But only if I refresh the page and the theme customizer is already open. I don't know if this is anyhow related to the issue I have.

Any ideas?

**Comment by Rayken** [comment]
So, again, are your settings being saved? Do you get any data fetching the settings manually? It'd be quite obvious that there isn't a `<style>` in your head if there aren't any theme mods to apply (i.e. no theme mods, no styles).

**Comment by aristath** [comment]
We no longer use inline CSS for anything, everything is added on stylesheets.
The reason this was done was to solve issues with pseudo-elements not being able to apply their CSS properly because inline styles were overriding the styles via stylesheets.

You can simply add `!important` in your js_vars...
There are 2 ways you can do that:
1. Using suffix: simply add `'suffix' => ' !important'` to your js_var arguments.
2. Use the value_pattern: add `'value_pattern' => '$ !important'` to your js_vars. the `$` there is a placeholder for the actual value to allow for more complex CSS if you need it.

As for the syntax @Quaked is right, it should be an array of arrays.

Let me know if that helps!

**Comment by webgeckos** [comment]
Thank you aristath! It worked using `'suffix' => ' !important'` I know that its not best practice to use "!important" that often but I am glad that it works.

I still have one last problem (let me know if I should open a new issue): I can't get Google Fonts to work. I have already checked out this issue here #238 and when the page refreshes the new font has been applied but when I click the save-button and close the customizer the new font its not being saved.

Here is my setting:

```
Kirki::add_field( 'miga', array(
        'type'     => 'select2',
        'settings' => 'font_family_h',
        'label'    => __( 'Font Family Headlines', 'miga' ),
        'section'  => 'fonts',
        'default'  => 'Roboto',
        'priority' => 10,
        'choices'  => Kirki_Fonts::get_font_choices(),
        'output' => array(
            array(
                'element'  => '.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6', //used from bootstrap.css
                'property' => 'font-family',
                'units'    => ' !important'
            ),
        ),
    ) );
```

Even with extra custom css I can't get it to work. Do you have any suggestions?

Thank you.

**Comment by aristath** [comment]
>  I know that its not best practice to use "!important" that often but I am glad that it works.

Well, since this in only used in your `js_vars` it's not an issue... it will only be used when previewing changing in the customizer. :)

> when the page refreshes the new font has been applied but when I click the save-button and close the customizer the new font its not being saved.

Not saved, or not applied?
If you do this, do you see the options were properly saved?

``` php
var_dump( get_theme_mod( 'font_family_h' ) );
```

**Comment by webgeckos** [comment]
Ah yes of course, its only for the preview :-)

Using `var_dump( get_theme_mod( 'font_family_h' ) );` I get the following output: string(7) "Iceberg".
So, yes the changes are saved but not applied.

If I don't use any custom css I get an empty `h2 { }` in Firebug. And if I use custom css like:

```
<?php function miga_customizer_css() {
?>
     <style type="text/css">

        .h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
            font-family: <?php echo get_theme_mod('font_family_h');?> !important;
        }

     </style>
<?php
}
add_action( 'wp_head', 'miga_customizer_css' );`
```

In Firebug the new font is applied but the name of the font is shown greyed (regardless if I use !important or not) so the new font is not showing up on the frontend.

What could be the reason?

**Comment by webgeckos** [comment]
I still haven't figured out how to display the new Google font on the frontend and why the font is shown greyed.

Any ideas?

Thanks.

**Comment by aristath** [comment]
@webgeckos I'm terribly sorry for the delay here, I dropped the ball on this one.
Do you still have an issue here?

**Comment by aristath** [comment]
Since there has been no reply in months I'll go ahead and close this one.
If you still require assistance with this feel free to reopen and post an update on your current status.
