### ISSUE TITLE
Scrolling issue with Safari OSX

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#966]
### Issue description:

After changing an option in the customiser and causing a live update, scrolling does not work until i either resize the screen or disable the `/* overflow: hidden; */` css value in `body - customise-controls.css`
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) Latest develop, issue on stable too.
### Code to reproduce the issue (config + field(s))

Seems to be working fine in chrome so don't believe its an issue with the theme. Resizing my window causes it to scroll normally again. Cheers!

**Comment by enkota** [comment]
Testing this morning it seems to be only happening on my localhost site. Will do some further testing and report back!

**Comment by aristath** [comment]
I can't replicate this issue....
I don't think however it has anything to do with Kirki!
The only place we have `overflow: hidden;` is for CodeMirror, selectize and repeater-specific classes.

**Comment by enkota** [comment]
Yeah I still haven't had time to figure the problem yet. Will keep the thread updated once i find out. Cheers 👍

**Comment by enkota** [comment]
Okay I decided to go and try with the kirki demo theme and WP plugin version. The issue is still apparent, i've not got any extensions/plugins running and cleaned out the cache etc. I'm using 10.11.4 + Safari 9.1.

Steps to reproduce:

Go into any setting and select to force refresh the preview.

Try and scroll the website and does not work. 

Slightly resize the window and the scroll functions again. I'm on 4.5.2 wp as well. Lemme know if you can reproduce it?

Added a video too if that's any help! 

https://www.youtube.com/watch?v=_0WexFG0hls&feature=youtu.be

EDIT: Hmm interesting, it even seems to be happening with twenty sixteen after an update too. Wonder if it's a bug in 4.5.2 WP.

**Comment by enkota** [comment]
Okay some more testing today I am 99% sure it's a bug with WP 4.5+ 

Problem occurs only in Safari after 4.5. Will try see if I can submit a bug report to core 👍
