### ISSUE TITLE
Partial refresh help.

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#970]
Hey @aristath 

I was checking out the partial refresh stuff today. Could you possibly give some more insight as to how it works. Am I able to apply it to any element or is it just specific wp functions such as the nav menu or page title?

```
        // Section Title/Description
        Kirki::add_field( 'kirki', array(
        'type'        => 'text',
        'settings'     => 'kirki_hero_title',
        'label'       => __( 'Hero Title', 'kirki' ),
        'description' => __( 'Add your hero title here.', 'kirki' ),
        'section'     => 'kirki_hero_content',
        'default'     => 'Hero',
        'priority'    => 20,
        'partial_refresh' => array(
        'kirki_hero_title' => array(
            'selector'        => '.kirki-full-text-header h1',
            'render_callback' => 'kirki_hero_title',
             ),
         ),
        ));
```

```
       <div class="hero-full-text-header">
            <h1><?php echo Kirki::get_option('kirki_hero_title'); ?></h1>
        </div>
```

I am guessing this isn't correct? I'm just a bit unsure about what you reference the 'render_callback' to. 

Any help would be great!

Scott 👍

**Comment by aristath** [comment]
Did you read the docs on https://kirki.org/docs/arguments/partial_refresh.html ?

If you've got this:

``` php
function kirki_hero_title() {
    ?>
    <div class="hero-full-text-header">
        <h1><?php echo Kirki::get_option('kirki_hero_title'); ?></h1>
    </div>
    <?php
}
```

Then the `partial_refresh` argument should look like this:

``` php
'partial_refresh' => array(
    'kirki_hero_title' => array(
        'selector'        => '.hero-full-text-header',
        'render_callback' => 'kirki_hero_title',
    ),
),
```

**Comment by aristath** [comment]
There was a bug, has now been fixed in the develop branch (https://github.com/aristath/kirki/commit/7cb50086edd70738c3575eede676ba11f5072fe2)

**Comment by enkota** [comment]
Great, cheers! I forgot to say I was having problems getting it to work. Will test it out now!
