### ISSUE TITLE
checkbox default value doesn't work in repeater

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#971]
### Issue description:

checkbox are always checked in the repeater no matter if i put 1 or 0 in the default value.
Tested also with true or false but didn't work neither
When i do var_dump( get_theme_mod( 'my_repeater' ) ) i didn't see checkbox in the value even if the checkbox are check by default i had to uncheck it to have 'cheky' => boolean false and if i recheck it. it works and give  'cheky' => boolean true
### Version used:

develop branch
### Code to reproduce the issue (config + field(s))

``` javascript
Kirki::add_field( 'my_config', array(
    'type'        => 'repeater',
    'label'       => esc_attr__( 'Repeater Control', 'my_textdomain' ),
    'section'     => 'my_section',
    'priority'    => 10,
    'settings'    => 'my_setting',
       'fields' => array(
              'cheky' => array(
            'type'        => 'checkbox',
            'label'       => esc_attr__( 'woocommerce', 'my_textdomain' ),
      'description' => esc_attr__( 'This will display the woocommerce post', 'my_textdomain' ),
            'default'     => '1',
        ),
                'cheko' => array(
            'type'        => 'checkbox',
            'label'       => esc_attr__( 'post', 'my_textdomain' ),
      'description' => esc_attr__( 'display the post', 'my_textdomain' ),
            'default'     => '0',
        ),
)
) );
```

if our repeater value is save in $row_values _**if ( $row_values['cheko'] === 'true' )**_  tell us if it's check in the repeater ?
also description display next to label. It isn't supported in the repeater ?

**Comment by aristath** [comment]
Hey there!

I only saw this now 'cause it was closed... Is this still an issue?

**Comment by robbisy** [comment]
checkbox are check by default with true or false but not with 1or 0. But the default value doesn't appear in var_dump result you had to change something to get result in var_dump. I don't know how to do to get the default value of the checkbox. It 's more a question than an issue report

**Comment by iliman** [comment]
+1
`'default'     => '0'` does not work
`'default'     => 0` works

Also the `toggle` control does not displays in repeater

**Comment by aristath** [comment]
default values should be boolean (`true`/`false` or `0`/`1`).

> Also the toggle control does not displays in repeater
 That's because they have not been implemented in repeaters (yet).
