### ISSUE TITLE
Adding HTML to Description text?

### ISSUE THREAD

**Issue by regan008** [themeum/kirki#976]
### Issue description:

Hi, I had one quick question for you. I've googled a bit and can't seem to find out if this is possible or not but I was wondering if its possible to add html to a section's description? The code is below but what I'm trying to do is add a link to the documentation in the description at the top of the section. Am I missing something simple or is this not advised/possible? Thanks so much!
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) Current Develop version.
### Using theme_mods or options?

options
### Code to reproduce the issue (config + field(s))

``` php
Kirki::add_section( 'Block2', array(
    'title'          => __( 'Block 2 Options', 'pressforward_tk_theme' ),
    'description'    => __( 'The second block on the homepage is made up of four “columns”. Each column includes a title which can (optionally) link to a page or post within the site. Above each title a icon from the <a href="www.fontawesome.io">FontAwesome</a> icon set can be displayed. If you wish include an icon above the title, enter the css class name of the FontAwesome icon in the box(s) below', 'pressforward_tk_theme' ),
    'panel'          => 'homepage', // Not typically needed.
    'priority'       => 160,
    'capability'     => 'edit_theme_options',
    'theme_supports' => '', // Rarely needed.
) );
```

**Comment by rahulv3a** [comment]
If you put `custom` field as the first field of the section, it could act as section description. HTML is allowed in `custom` field.

``` PHP
Kirki::add_field( 'my_config', array(
  'settings' => 'my_setting',
  'section'  => 'my_section',
  'type'     => 'custom',
  'default'  => __( '<a target="_blank" href="#">HTML content goes here</a>', 'kirki' ),
) );
```

I would recommend passing `dafault` through `wp_kses` so that translators don't mess up your theme.

``` PHP
Kirki::add_field( 'my_config', array(
  'settings' => 'my_setting',
  'section'  => 'my_section',
  'type'     => 'custom',
  'default'  => wp_kses( __( '<a target="_blank" href="#">HTML content goes here</a>', 'kirki' ), array(
    'a' => array(
      'target' => array(),
      'href' => array(),
    ),
  ) ),
) );
```

**Comment by aristath** [comment]
fixed in the latest develop branch. 👍
