### ISSUE TITLE
Notice: wp_editor() was called with an argument that is deprecated since version 3.9! TinyMCE editor IDs cannot have brackets. in C:\xampp\htdocs\wp-includes\functions.php on line 3842

### ISSUE THREAD

**Issue by peazz** [themeum/kirki#979]
### Issue description:

I get the following when using the editor type. Its the only one I am currently trying to use.

Notice: wp_editor() was called with an argument that is deprecated since version 3.9! TinyMCE editor IDs cannot have brackets. in C:\xampp\htdocs\wp-includes\functions.php on line 3842
### Version used:

Latest public
### Using theme_mods or options?

options
### Code to reproduce the issue (config + field(s))

```
Kirki::add_field( 'pm_kiri_config', array(
'settings' => 'show_exit_popover_custom_content',
'label'    => __( 'Custom Content','pixel-mag' ),
 'section'  => 'bj_popover_panel_general',
 'type'     => 'editor'
) );
```

**Comment by aristath** [comment]
when using serialized options the options name looks like this: `my_option_name[setting_id]`
Unfortunately tinyMCE doesn't support that...

I would advise you to use theme_mods instead of options if possible.
They are faster than options and better supported.
