### ISSUE TITLE
Error generated when using the WP theme check plugin after I packaged the kirki framework inside my theme

### ISSUE THREAD

**Issue by carl-alberto** [themeum/kirki#980]
### Issue description:

I'm packaging the whole kirki framework in my theme because the WP theme check plugin is giving error if there will be external dependencies. Also, when running the theme check plugin, I'm getting these errors:

RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 484: <button type='button' class='button upload-button' data-label='<?php esc_attr_e( $l10n['add-file'] ); ?>' data-alt-label='<?php esc_attr_e( $l10n['change-file'] ); ?>' >
Line 486: <?php esc_attr_e( $l10n['change-file'] ); ?>
RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 484: <button type='button' class='button upload-button' data-label='<?php esc_attr_e( $l10n['add-file'] ); ?>' data-alt-label='<?php esc_attr_e( $l10n['chang
Line 488: <?php esc_attr_e( $l10n['add-file'] ); ?>
RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 473: <figure class='kirki-file-attachment' data-placeholder='<?php esc_attr_e( $l10n['no-file-selected'] ); ?>' >
Line 478: <?php esc_attr_e( $l10n['no-file-selected'] ); ?>
RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 448: <button type='button' class='button upload-button' data-label='<?php esc_attr_e( $l10n['add-image'] ); ?>' data-alt-label='<?php esc_attr_e( $l10n['change-image'] ); ?>' >
Line 450: <?php esc_attr_e( $l10n['change-image'] ); ?>
RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 448: <button type='button' class='button upload-button' data-label='<?php esc_attr_e( $l10n['add-image'] ); ?>' data-alt-label='<?php esc_attr_e( $l10n['chan
Line 452: <?php esc_attr_e( $l10n['add-image'] ); ?>
RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 447: <button type='button' class='button remove-button<# if ( ! field.default ) { #> hidden<# } #>'><?php esc_attr_e( $l10n['remove'] ); ?></button>
Line 483: <button type='button' class='button remove-button<# if ( ! field.default ) { #> hidden<# } #>'><?php esc_attr_e( $l10n['remove'] ); ?></button>
Line 502: <button type='button' class='button-link repeater-row-remove'><?php esc_attr_e( $l10n['remove'] ); ?></button>
RECOMMENDED: Possible variable $l10n found in translation function in class-kirki-controls-repeater-control.php. Translation function calls must NOT contain PHP variables.
Line 437: <figure class='kirki-image-attachment' data-placeholder='<?php esc_attr_e( $l10n['no-image-selected'] ); ?>' >
Line 442: <?php esc_attr_e( $l10n['no-image-selected'] ); ?>

Is there a way that we do the internationalization the standard WP way to ward these errors? Thanks!
### Version used: 2.3.2

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
### Code to reproduce the issue (config + field(s))

I just installed https://wordpress.org/plugins/theme-check/ and ran it

**Comment by aristath** [comment]
These have already been fixed in the develop branch.
