### ISSUE TITLE
Question on dashicons pseudo element 

### ISSUE THREAD

**Issue by robbisy** [themeum/kirki#981]
Is it possible to use :before on the output element 

``` javascript
Kirki::add_field( 'my_config', array(
  'type'     => 'dashicons',
  'settings' => 'misato',
  'label'    => __( 'Dashicons Control', 'my_textdomain' ),
  'section'  => 'header',
  'priority' => 4,
  'default'  => 'menu',
  'output'      => array(
    array(
      'element' => 'ul.nav-menu li a span:before',
      'property' => 'content',
    ),
  ),
) );
```

**Comment by aristath** [comment]
The dashicons control does not save the values of th glyph.
It saves the dashicon name,
So for example it saves the value `menu` and not `f333`.
So no, you can't use the output argument there.

You can see a usage example on https://kirki.org/docs/controls/dashicons.html#usage
