### ISSUE TITLE
Real example of Partial Refresh with Kirki

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#982]
Hi
I 've tried a lot of ways , but this feature does not work , the document is poor , I hope you can give a real example of this feature and worked on the _s theme.
Regards,
Hung

**Comment by aristath** [comment]
@vunamhung Hey there!

As mentioned on the docs on https://kirki.org/docs/arguments/partial_refresh.html you will have to read the documentation on the WordPress Core implementation for partial refreshes first on https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/

Kirki just simplifies the WP-Core syntax, nothing more than that.
The example included there is real, and it's exactly the same one used in the wordpress.org docs.
