### ISSUE TITLE
Codemirror Dequeue function?

### ISSUE THREAD

**Issue by AshiqKiron** [themeum/kirki#985]
@aristath Hi there, I deleted the codemirrors and it's related files also commented out the enqueue function. In case I update kirki I guess I have to do that again. Is there any elegant solution( like a dequeue function) for this ? so that regardless of update, Code mirror will always be dequeued.

**Comment by aristath** [comment]
Hey there!

In the latest version codemirror is only enqueued if you add a `code` field.
So if you don't have such a field, all you have to do is delete the files, nothing more than that.

**Comment by AshiqKiron** [comment]
That's great, thanks for info.
