### ISSUE TITLE
Feature Request: Custom CSS Values

### ISSUE THREAD

**Issue by peazz** [themeum/kirki#987]
I checked the documentation but saw nothing in relation to a custom css value, unless I missing something.

It would be great to have a custom value output for things like check boxes and toggles, I currently have some switches I am using to enable bold links however the only way I can currently see to do it is embedding my own styles in the header.

**Comment by rahulv3a** [comment]
The following field would add `font-wight: bold` to `.my-element` when its on.

``` PHP
Kirki::add_field( 'my_config', array(
  'settings' => 'my_setting',
  'section'  => 'my_section',
  'label'    => esc_html__( 'Author', 'kirki' ),
  'type'     => 'toggle',
  'default'  => '0',
  'output'   => array(
    array(
      'element'       => '.my-element',
      'property'      => 'font-weight',
      'exclude'       => array( '0' ),
      'value_pattern' => 'bold',
    ),
  ),
) );
```

**Comment by peazz** [comment]
Great! I am going to give this a try. 

I did try a hacky solutions myself using prefix and exclude but it didnt work. 

Thanks!
