### ISSUE TITLE
multicolor: color picker closes even if a user clicks on input field

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#993]
### Issue description:

As stated, color picker closes if a user clicks on input field to type hex code.
### Version used:

Latest commit in develop branch, [556c23d](https://github.com/aristath/kirki/commit/556c23d41ce4bb60cf0bf4d223a6edcc49fc057d).
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` PHP
Kirki::add_config( 'my_config', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );
```

``` PHP
Kirki::add_field( 'my_config', array(
  'settings' => 'my_setting',
  'section'  => 'my_section',
  'label'    => esc_html__( 'Colors', 'kirki' ),
  'type'     => 'multicolor',
  'default'  => array(
    'normal' => '#777',
    'hover'  => '#333',
  ),
  'choices'  => array(
    'normal' => esc_html__( 'Normal', 'kirki' ),
    'hover'  => esc_html__( 'Hover', 'kirki' ),
  ),
) );
```

**Comment by aristath** [comment]
I can no longer replicate this in the develop branch so I'm assuming it has already been fixed by one of the other commits since this has been reported.
I'll go ahead and close the issue, feel free to reopen if it happens again for you. 👍
