### ISSUE TITLE
Translate Kirki strings in embedded theme not working

### ISSUE THREAD

**Issue by kkiln** [themeum/kirki#995]
### Issue description:

I followed [kirki/docs/advanced/integration.md](https://github.com/aristath/kirki/blob/gh-pages/docs/advanced/integration.md#translating-kirki-strings-in-embedded-theme) to add the translations for using my own textdomain, but they did not work on some controls such as typography, image and so on.
### Version used:

The latest develop branch. 
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

The function I added in Kirki configuration file:

```
function my_theme_kirki_textdomain( $l10n ) {
    $l10n['background-color']  = esc_attr__( 'Background Color', 'my-textdomain' );
    ...
    return $l10n;
}
add_filter( 'kirki/my_theme/l10n', 'my_theme_kirki_textdomain' );
```

BTW, I think the code `$l10n['background-color'] => esc_attr__( 'Background Color', my_textdomain );` in kirki/docs/advanced/integration.md is wrong, and it should be `$l10n['background-color'] = esc_attr__( 'Background Color', my_textdomain );`. :)

kirki/includes/controls/class-kirki-controls-typography-control.php

```
public function to_json() {
    parent::to_json();
    $this->add_values_backwards_compatibility();
    $this->json['l10n'] = Kirki_l10n::get_strings();
    $defaults = array(
        'font-family'    => false,
        'font-size'      => false,
        'variant'        => false,
        'line-height'    => false,
        'letter-spacing' => false,
        'color'          => false,
        'text-align'     => false,
    );
    $this->json['default'] = wp_parse_args( $this->json['default'], $defaults );
    $this->json['show_variants'] = ( true === Kirki_Fonts_Google::$force_load_all_variants ) ? false : true;
    $this->json['show_subsets']  = ( true === Kirki_Fonts_Google::$force_load_all_subsets ) ? false : true;
}
```

If I change `$this->json['l10n'] = Kirki_l10n::get_strings();` to `$this->json['l10n'] = Kirki_l10n::get_strings( $this->kirki_config );`, then the string "Font Family" can be translated correctly, but the strings for subset are still not working.

![image](https://cloud.githubusercontent.com/assets/3065531/15526781/0a49860a-2267-11e6-81eb-459f1546777c.png)

I checked kirki/includes/class-kirki-l10n.php

```
public static function get_strings( $config_id = 'global' ) {
    $translation_strings = array(
        'background-color'      => esc_attr__( 'Background Color', 'kirki' ),
        ...
    );

    $config = apply_filters( 'kirki/config', array() );

    if ( isset( $config['i18n'] ) ) {
        $translation_strings = wp_parse_args( $config['i18n'], $translation_strings );
    }

    return apply_filters( 'kirki/' . $config_id . '/l10n', $translation_strings );
}
```

To apply the filter, we need pass `$config_id` to the function `get_strings()`, right? Please help to check and thanks for your time.

**Comment by aristath** [comment]
Hey there!

Can you please pull the latest changes from the develop branch and let me know if the `kirki/{$config_id}/l10n` filter works for you now?

**Comment by kkiln** [comment]
Hi there, I do really appreciate your time on this issue. The `kirki/{$config_id}/l10n` filter works now. Thanks!

**Comment by kkiln** [comment]
Hey there, it seems that the drop-down list can not be translated.
![image](https://cloud.githubusercontent.com/assets/3065531/15620361/60b700ea-248c-11e6-864d-24f161e3d84a.png)
I checked the file `kirki/includes/class-kirki-fonts.php`, and I think the code `$i18n = Kirki_l10n::get_strings();` will ignore the `l10n` filter. I tried to fix it but failed. I would be really grateful if you could help to check this issue. Thanks!

**Comment by aristath** [comment]
@kkiln it's doable, but I'm not sure I want to do it.
Here's why:
The typography controls load the fonts from a json array that's loaded in the customizer.
In order to improve performance we're only loading that array once. This way, you can create multiple typography controls and all of them will use the same data.
The google-fonts array is HUGE so loading it multiple times would be completely inefficient.

In order to allow translation of these strings on a per-configuration basis, we'd have to load that data in the customizer multiple times.

You can use the `kirki/config` filter to change them if you want:

``` php
add_filter( 'kirki/config', function( $config ) {

    $config['i18n']['ultra-light'] = esc_attr__( 'My translation', 'textdomain' );
    // Add more translations here

    return $config;
});
```

The above method has the disadvantage that in case there are multiple plugins using Kirki installed on the site, the translations will be global and not only limited to your theme.
The advantage is that we won't risk performance and over-loading the customizer with unnecessary MB of data, so it's a good compromise.
