### ISSUE TITLE
Customizer not loading: Cannot read property 'l10n' of undefined

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#996]
Customizer doesn't load with any commit after [4b2b377](https://github.com/aristath/kirki/commit/4b2b3772f6c562f1c664fca5dca8f895afbc3feb) that fixes #976.

Console says `VM1824:11 Uncaught TypeError: Cannot read property 'l10n' of undefined`.

If it helps, I'm not using descriptions in any of my panel/section.

**Comment by aristath** [comment]
Can you please check if it works now?

**Comment by rahulv3a** [comment]
Nope. Now console says `Uncaught SyntaxError: Unexpected token <`

**Comment by rahulv3a** [comment]
Wait... It worked! Something was wrong at my end.

**Comment by aristath** [comment]
👍 awesome! Thanks for re-checking...
Closing this one.
